### ISSUE TITLE
Release new build, new Chrome version 80

### ISSUE THREAD

**Issue by jmakr0** [SeleniumHQ/docker-selenium#1005]
## Release with new Chrome version 80

On the 4th Chrome 80 was released. I've urgently need to test something with that new Chrome version and I've been waiting for the new Selenium release including this version. 

Before I build my own image, when are you going to release a new version? Is there any handy way of building an image with the recent Chrome myself, e.g. `$ VERSION=CHROME_XX make build`.

Any information is much welcome, cheers!

**Comment by diemol** [comment]
We are working on that but the build is failing, tests are not passing. Join us in the Slack channel if you want to give us a hand.

**Comment by jmakr0** [comment]
@diemol thank you for the amazingly quick response. I'll if the PM lets me.
