### ISSUE TITLE
Can I run docker-selenium with multiple OS's

### ISSUE THREAD

**Issue by petermartin2002** [SeleniumHQ/docker-selenium#101]
Hi 

I saw the Docker Selenium Getting Started presentation from Selenium Conf 2015.  It was a very informative presentation and has got me thinking about how we can use this inside my company.

We are building out selenium grid in our test farm and I am looking at the cucumber framework. 

My question is we need to be able to set up automation on multiple OSs both Linux (Ubuntu, Red Hat etc) and Windows ( 7, 8 server etc). 

Is there a way we can utilise docker to do this so we do not have to have several Virtual Servers running and spin up docker-selenium as required?

Also as the example appears to be *nix based there is only Chrome and Firefox supported but if we were to utilise windows would it be possible to support IE?

Thanks 

Peter

**Comment by rubytester** [comment]
Sorry, we don't have IE dockerized. You will need to use Windows machines and somehow provision them with your tool of choice (maybe https://chocolatey.org/) or 'manually' (ouch)

Thanks for the feedback on the SeConf talk. 

Current Docker Images are based on Ubuntu Vivid 15.04. You can run them on RedHat Hosts if you want. I run them on CentOS 7.1

**Comment by NickAb** [comment]
Microsoft and Docker announced collaboration on bringing Docker to Windows Server. Somewhere in a future it should be possible to create a dockerized environment to run Selenium tests against Internet Explorer or Edge. Currently it is in development and can be played with in Windows Server 2016 technical previews.

https://azure.microsoft.com/en-us/blog/microsoft-unveils-new-container-technologies-for-the-next-generation-cloud/
https://blog.docker.com/2015/08/tp-docker-engine-windows-server-2016/
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker
https://msdn.microsoft.com/virtualization/windowscontainers/about/work_in_progress

**Comment by elgalu** [comment]
Interesting @NickAb, but by reading the current docs I see no way to run different versions of IE on each windows-docker container so we will be able to only run the one latest version provided by Win 2016.

**Comment by NickAb** [comment]
@elgalu it might be so, I think that @nwlunatic was looking into this question, maybe he can shed some light on this.

**Comment by petermartin2002** [comment]
Thanks folks,  all good knowledge.

**Comment by alexkogon** [comment]
Hi folks,

Closest thing now to Docker for Windows is VMWare's Linked Clones, if you happen to have that expensive piece of non-Open Source software give it a shot ;)

**Comment by diemol** [comment]
As today, it is still not possible to run IE/EGDE in docker. There was a in [issue](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214) created about it but didn't get a positive answer.

Closing this issue since it is more a question than a real issue, feel free to mail the [Selenium Users Group](https://groups.google.com/forum/#!forum/selenium-users) to continue the thread.
