### ISSUE TITLE
Selenium version based on the "next-up" Chrome release

### ISSUE THREAD

**Issue by Galand-V** [SeleniumHQ/docker-selenium#1014]
## 🚀 Feature Proposal

Currently, the last supported version is based on : Chrome: 80. ...  
The idea of this issue is to have a docker Selenium version based on the "next-up" version. In this example, this would be the Chrome 81. .. version

https://www.chromestatus.com/features/schedule

## Motivation

Selenium seems to be mainly used by QA which are testing the "next-up" version of their own application. Having the "next-up" version of the browser used on the "next-up" version of their own application would be a great advantage.

**Comment by diemol** [comment]
@Galand-V this is already possible, you can build your own docker image with a Chrome browser in beta or canary status.
https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images#specify-chromedriver-and-chrome-versions
