### ISSUE TITLE
using new version -zirconium for selenium hub and selenium-node -chrome-debug.(chrome  80.0.3987.132  browser version) with new docker version:2.2.0.3 is throwing invalid Locator:invalid argument

### ISSUE THREAD

**Issue by ramya-KM** [SeleniumHQ/docker-selenium#1017]
## 🐛 Bug Report

using new version -zirconium for selenium hub and selenium-node -chrome-debug.(chrome browser version  80.0.3987.132  ) with new docker version:2.2.0.3 is throwing invalid Locator:invalid argument. while running in docker 
it is perfectly working running locally .only failing when running in docker

**Comment by diemol** [comment]
@ramya-KM how can we reproduce the issue? Most of the template was ignored 😢

**Comment by diemol** [comment]
Closing as we never got more information.
