### ISSUE TITLE
Unable to find chromedriver when initializing Selenium::WebDriver::Service

### ISSUE THREAD

**Issue by Valentyna** [SeleniumHQ/docker-selenium#1023]
## 🐛 Bug Report

When starting driver with `Selenium::WebDriver::Service.chrome` - Unable to find chromedriver (Selenium::WebDriver::Error::WebDriverError)

## To Reproduce

1. Initialize service = Selenium::WebDriver::Service.chrome(args: { verbose: true, log_path: '/tmp/chromedriver.log' })
2. Start new driver and pass service param to it

## Expected behavior

WebDriver should be initialized with parameters passed to Service

## Test script reproducing this issue (when applicable)

```
   args = %w[--ignore-certificate-errors --window-size=1360,998 --user-data-dir=/tmp]
   service = Selenium::WebDriver::Service.chrome(args: { verbose: true, log_path: '/tmp/chromedriver.log' })
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(chromeOptions: { args: args,
               prefs: { 'download.default_directory'=> '/tmp', 'download.prompt_for_download'=> false }})
  
Capybara.register_driver :selenium_chrome do |app|
    Capybara::Selenium::Driver.new(app, browser: :remote, url: 'http://selenium:4444/wd/hub',
                                        desired_capabilities: capabilities,
                                        service: service)
  end
```

which chromedriver returns '/usr/bin/chromedriver/
which is why I tried to specify
   path: '/usr/bin/chromedriver
   path: '/opt/selenium/chromedriver-80.0.3987.106'
the error is:
  not a file: "/usr/bin/chromedriver"
  not a file: "/opt/selenium/chromedriver-80.0.3987.106"

## Environment

OS: Mac OS Catalina
Docker-Selenium image version: standalone-chrome:3.141.59-zirconium
Docker version: Docker version 19.03.8, build afacb8b
Docker-Compose version: docker-compose version 1.25.4, build 8d51620a

**Comment by Valentyna** [comment]
Tried passing Selenium::WebDriver::Service to local webdriver configuration
```
  args = %w[--ignore-certificate-errors --window-size=1360,998 --user-data-dir=/tmp]
  service = Selenium::WebDriver::Service.chrome(args: { verbose: true, log_path: '/Users/user/work/data/chromedriver.log'})
  opts = Selenium::WebDriver::Chrome::Options.new(args: args, prefs:
      { 'download.default_directory' => Directories::DOWNLOADS })
  Capybara.register_driver :selenium_chrome do |app|
    Capybara::Selenium::Driver.new(app, browser: :remote,
                                        url: 'http://localhost:9515',
                                        options: opts,
                                        service: service)
```

Error:  unknown option: {:service=>#<Selenium::WebDriver::Chrome::Service:0x00007f91c261e990 @executable_path="/usr/local/bin/chromedriver", @host="127.0.0.1", @port=9515, @extra_args=["--log-path=/Users/vakalini/work/data/chromedriver.log", "--verbose"]>} (ArgumentError)

**Comment by diemol** [comment]
@Valentyna there is no need to specify the Chrome or ChromeDriver path, the docker images are already configured so there is no need to do that.

Could you please try again without setting those parameters? If there is still an error, can you please provide the logs from the docker container and your automation script?

**Comment by diemol** [comment]
Closing as we did not get any reply.
