### ISSUE TITLE
Not possible to pull opera image

### ISSUE THREAD

**Issue by christianbaumann** [SeleniumHQ/docker-selenium#1024]
## 🐛 Bug Report

Not possible to pull opera image

## To Reproduce

1. Create `docker-compose.yaml` (as described here: https://github.com/SeleniumHQ/docker-selenium#version-2) and run `docker-compose up`

## Expected behavior

Images get pulled, hub & nodes start

## Actual behavior

```
Pulling opera (selenium/node-opera:3.141.59-zirconium)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling opera (selenium/node-opera:3.141.59-zirconium)...
ERROR: pull access denied for selenium/node-opera, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

## Environment

OS: Windows 10
Docker-Selenium image version: <!-- 3, 3.141, 3.141.59-zirconium etc
Docker image id: selenium/node-opera:3.141.59-zirconium
Docker version: 19.03.8, build afacb8b
Docker-Compose version: 1.25.4, build 8d51620a
Exact Docker command to start the containers: `docker-compose up` with docker-compose.yaml from https://github.com/SeleniumHQ/docker-selenium#version-2

**Comment by diemol** [comment]
Hi @christianbaumann,

We just pushed it, please be aware that we had to change the tagging format in preparation for the Grid 4 Alphas.
https://hub.docker.com/r/selenium/node-opera/tags
