### ISSUE TITLE
I want to open the local HTML, but it is an error

### ISSUE THREAD

**Issue by downdawn** [SeleniumHQ/docker-selenium#1029]
## 💬 Questions and Help

I want to open the local HTML, but it is an error: 

`selenium.com mon. Exceptions. An InvalidArgumentException: Message: invalid argument`

my code:

`driver.get(r'/code/test.html')`

my docker-compose.yaml:

```powershell
version: "3.6"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
      - ./test.html:/code/test.html
```

**Comment by downdawn** [comment]
This is not the answer I want, please help me. thank you

**Comment by diemol** [comment]
@downdawn please understand that this is not a forum for questions and answers, for that we have different channels:
* 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
* 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
* 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
