### ISSUE TITLE
selenium/node-firefox docker hub image has no npm

### ISSUE THREAD

**Issue by hajdun** [SeleniumHQ/docker-selenium#1031]
## 🐛 Bug Report

I wanted to use this image for gitlab CI,
e2e testing (selenium js, mocha, headless firefox)

 npm: command not found 

is written when I have a gitlab ci setting like 
```
image: selenium/node-firefox:latest

stages:
  - e2e

e2e:
  stage: e2e
  before_script:
    - npm install
```
Can you please add node / npm to https://hub.docker.com/r/selenium/node-firefox/dockerfile ? 
This is not a compatibility issue, I only need one more dependency.
The name of the image made me think it has node, but it did not have npm.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
above

## Expected behavior

Please have npm / node in this image or in another one with firefox and selenium.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

above

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

gitlab ci, I am not an admin so I can't tell. Only the image is the problem for now (missing dependency)

**Comment by diemol** [comment]
Hi @hajdun,

You can always create your own docker image based on the ones we release. We won't add node to the images we release since we try to keep them as generic as possible,

A simple example on how to do that can be seen here https://stackoverflow.com/questions/52412693/dockerfile-add-npm-to-an-existing-docker-image

Closing as there is no issue with the images.
