### ISSUE TITLE
Missing start-selenium-standalone.sh in master/StandaloneChrome

### ISSUE THREAD

**Issue by shroffsagar91** [SeleniumHQ/docker-selenium#1037]
The dockerfile for standalone chrome expects start-selenium-standalone.sh in the context dir. 

Currently, there is no such file under: https://github.com/SeleniumHQ/docker-selenium/blob/master/StandaloneChrome/

**Comment by diemol** [comment]
The instructions to build the images are present in the [README](https://github.com/SeleniumHQ/docker-selenium#building-the-images), due to the different set of docker files we have built a few scripts that do the boilerplate work for us. Otherwise, there would be too many manual steps.
