### ISSUE TITLE
Please refresh images with latest ChromeDriver

### ISSUE THREAD

**Issue by mnohai-mdsol** [SeleniumHQ/docker-selenium#1045]
## 🐛 Bug Report

Need latest version of chromedriver (83.0.4103.39) included in the images. The packaged version (81.0.4044.69) is riddled with bugs and is causing issues.

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20200515
