### ISSUE TITLE
New release breaking on most pages RESULT_CODE_INVALID_CMDLINE_URL

### ISSUE THREAD

**Issue by chaseaucoin** [SeleniumHQ/docker-selenium#1051]
## 🐛 Bug Report

Release 3.141.59-20200525 
Platform: Docker selenium/standalone-chrome
Client Language .NET

With the latest release most pages are failing with RESULT_CODE_INVALID_CMDLINE_URL

## To Reproduce
Create a docker container using one of the following methods

$ docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-20200525
#OR
$ docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:3.141.59-20200525

`
            var chromeOptions = new ChromeOptions();

            chromeOptions.AddArguments(
                $"window-size=1920,1080"
            );

            var ip = "Address To Container";
            var dockerUri = new Uri($"http://{ip}:4444/wd/hub/");
            var driver = new RemoteWebDriver(dockerUri, chromeOptions.ToCapabilities());
            driver.Navigate().GoToUrl("https://www.disney.com");
            driver.Navigate().GoToUrl("https://www.amazon.com");
            driver.Navigate().GoToUrl("https://www.homedepot.com");
`

## Expected behavior

Pages should load. Instead the tab shuts down with the code RESULT_CODE_INVALID_CMDLINE_URL

Does not happen with image selenium/standalone-chrome-debug:3.141.59-zirconium

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Ubuntu
Docker-Selenium image version: 3.141.59-20200525
Also provide the docker image id 
-->
Docker version: selenium/standalone-chrome:3.141.59-20200525
Docker-Compose version (if applicable): none
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): $ docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:3.141.59-20200525

**Comment by diemol** [comment]
@chaseaucoin 

The 3.141.59-zirconium release has:
Google Chrome: 80.0.3987.106
ChromeDriver: 80.0.3987.106

The release 3.141.59-20200525 has:
- Google Chrome: 83.0.4103.61
- ChromeDriver: 83.0.4103.39

Everything else related to Selenium is the same, so this is probably a bug in Chrome or ChromeDriver. 

What happens when you try this locally with the different Chrome versions? Does it also fail?

**Comment by diemol** [comment]
Closing as we did not get any reply.
