### ISSUE TITLE
Null Pointer Exception, out of the box

### ISSUE THREAD

**Issue by robert-n-cristof** [SeleniumHQ/docker-selenium#1060]
## 🐛 Bug Report

out of the box:
http://127.0.0.1:4444/wd/hub shows a java NullPointerException and stack trace

{
  "sessionId": null,
  "status": 13,
  "value": {
    "class": "java.lang.NullPointerException",
    "error": "unknown error",
    "message": null,
    "stackTrace": [
      {
        "className": "org.openqa.grid.internal.ExternalSessionKey",
        "fileName": "ExternalSessionKey.java",
        "lineNumber": 79,
        "methodName": "fromWebDriverRequest"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.WebDriverRequest",
        "fileName": "WebDriverRequest.java",
        "lineNumber": 58,
        "methodName": "extractSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 240,
        "methodName": "getSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 123,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 85,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 63,
        "methodName": "doGet"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 687,
        "methodName": "service"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 790,
        "methodName": "service"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHolder",
        "fileName": "ServletHolder.java",
        "lineNumber": 865,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 535,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 146,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.security.SecurityHandler",
        "fileName": "SecurityHandler.java",
        "lineNumber": 548,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 257,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1595,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 255,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1340,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 203,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 473,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1564,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 201,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1242,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 144,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.Server",
        "fileName": "Server.java",
        "lineNumber": 503,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpChannel",
        "fileName": "HttpChannel.java",
        "lineNumber": 364,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpConnection",
        "fileName": "HttpConnection.java",
        "lineNumber": 260,
        "methodName": "onFillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
        "fileName": "AbstractConnection.java",
        "lineNumber": 305,
        "methodName": "succeeded"
      },
      {
        "className": "org.seleniumhq.jetty9.io.FillInterest",
        "fileName": "FillInterest.java",
        "lineNumber": 103,
        "methodName": "fillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
        "fileName": "ChannelEndPoint.java",
        "lineNumber": 118,
        "methodName": "run"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 333,
        "methodName": "runTask"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 310,
        "methodName": "doProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 168,
        "methodName": "tryProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 132,
        "methodName": "produce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 765,
        "methodName": "runJob"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 683,
        "methodName": "run"
      },
      {
        "className": "java.lang.Thread",
        "fileName": "Thread.java",
        "lineNumber": 748,
        "methodName": "run"
      }
    ],
    "stacktrace": "java.lang.NullPointerException\n\tat org.openqa.grid.internal.ExternalSessionKey.fromWebDriverRequest(ExternalSessionKey.java:79)\n\tat org.openqa.grid.web.servlet.handler.WebDriverRequest.extractSession(WebDriverRequest.java:58)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)\n\tat org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)\n\tat org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:63)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.Server.handle(Server.java:503)\n\tat org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)\n\tat org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)\n\tat org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)\n\tat java.lang.Thread.run(Thread.java:748)\n"
  }
}

http://127.0.0.1:4444/wd/hub/status
{
  "status": 0,
  "value": {
    "ready": false,
    "message": "No spare hub capacity",
    "build": {
      "revision": "e82be7d358",
      "time": "2018-11-14T08:25:53",
      "version": "3.141.59"
    },
    "os": {
      "arch": "amd64",
      "name": "Linux",
      "version": "4.19.76-linuxkit"
    },
    "java": {
      "version": "1.8.0_252"
    }
  }
}

## To Reproduce

docker-compose run (with or without any nodes in the .yml file)

\# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
\# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"

  \# chrome:
  \#   image: selenium/standalone-chrome-debug:3.141.59-20200525
  \#   volumes:
  \#     - /dev/shm:/dev/shm
  \#   depends_on:
  \#     - selenium-hub
  \#   environment:
  \#     - HUB_HOST=selenium-hub
  \#     - HUB_PORT=4444
  \#   ports:
  \#     - "5900:5900"

  \# firefox:
  \#   image: selenium/standalone-firefox-debug:3.141.59-20200525
  \#   volumes:
  \#     - /dev/shm:/dev/shm
  \#   depends_on:
  \#     - selenium-hub
  \#   environment:
  \#     - HUB_HOST=selenium-hub
  \#     - HUB_PORT=4444
  \#   ports:
  \#     - "5901:5900"

\#  opera:
\#    image: selenium/standalone-opera-debug:3.141.59-20200525
\#    volumes:
\#      - /dev/shm:/dev/shm
\#    depends_on:
\#      - selenium-hub
\#    environment:
\#      - HUB_HOST=selenium-hub
\#      - HUB_PORT=4444

check http://127.0.0.1:4444/wd/hub (listed above)

## Expected behavior

Not an exception on http://127.0.0.1:4444/wd/hub/ 
and http://127.0.0.1:4444/wd/hub/status to say "ready: true"

## Environment

**OS:** Windows 10
**Docker-Selenium image version:** selenium/hub:3.141.59-20200525
**Docker version:**  Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true
**Docker-Compose version (if applicable):** docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
**Exact Docker command to start the containers:** docker-compose up

**Comment by robert-n-cristof** [comment]
I removed docker image selenium/hub and re-ran docker-compose up and get a different error listed in http://127.0.0.1:4444/wd/hub/:

{
  "sessionId": null,
  "status": 13,
  "value": {
    "class": "org.openqa.grid.common.exception.GridException",
    "error": "unknown error",
    "message": "Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]",
    "stackTrace": [

**Comment by diemol** [comment]
This is the expected response, that endpoint is used to create sessions and it expects requests with the POST method, not GET.
I know it is not beautiful, but also Grid 3.x is not under development anymore and this is already being addressed in Grid 4.x (in the alpha stage now).
Closing this since it is not really a bug.

**Comment by robert-n-cristof** [comment]
Thanks for the reply.  (I thought this was grid 4.x..?)

**Comment by diemol** [comment]
Please check the released, Grid 4.x has a different set of tags.

**Comment by robert-n-cristof** [comment]
thanks again. I see now. will check out the other tagged images
