### ISSUE TITLE
Performance problem between 3.141.59-20200525 and 3.141.59-20200409

### ISSUE THREAD

**Issue by michalper** [SeleniumHQ/docker-selenium#1063]
## 💥 Regression Report

hi,
there is a big slowdown between standalone-chrome: 3.141.59-20200409 and 3.141.59-20200525 version. We ran same codeception tests on identical environment, but with different selenium-chrome versions -  there are performance problems in 85 percent of tests.

Left side: 3.141.59-20200525
Right side: 3.141.59-20200409

![image](https://user-images.githubusercontent.com/6458084/83737208-fb305800-a652-11ea-8a8d-39d0ab9af63e.png)

![image](https://user-images.githubusercontent.com/6458084/83737246-06838380-a653-11ea-8838-640c0a2a66e7.png)

## Last working version
3.141.59-20200409

Stopped working in version:
3.141.59-20200525

## Environment

OS: Debian 10
Docker-Selenium image version: 3.141.59-20200525
Docker version: Docker Engine - Community 19.03.3

**Comment by diemol** [comment]
@michalper 
the only difference between those images are the browser versions, could it be an issue with Chrome or Firefox? Have you digged more into the issue? Perhaps you have tested it locally with the different browser versions?

**Comment by diemol** [comment]
Closing as we did not get a reply.
