### ISSUE TITLE
Can't build Docker images after the latest release

### ISSUE THREAD

**Issue by take-five** [SeleniumHQ/docker-selenium#1066]
## 🐛 Bug Report

Dockerfiles in release 4.0.0-alpha6-20200609 refer to non-existent base docker image.

For example, Node Chrome image is based on `selenium/node-base:4.0.0-alpha-6-20200609`, but the image on Docker hub is tagged as `selenium/node-base:4.0.0-alpha6-20200609` (no dash after "alpha").

Because of this, it is not possible to build your own NodeChrome image on the latest release.

## To Reproduce

```
git clone https://github.com/SeleniumHQ/docker-selenium.git
cd docker-selenium
git checkout 4.0.0-alpha6-20200609
docker build --build-arg 'CHROME_VERSION=google-chrome-beta=84.0.4147.38-1' --build-arg 'CHROME_DRIVER_VERSION=84.0.4147.30' NodeChrome
```

It produces the error:
```
Step 1/12 : FROM selenium/node-base:4.0.0-alpha-6-20200609
manifest for selenium/node-base:4.0.0-alpha-6-20200609 not found: manifest unknown: manifest unknown
```

## Expected behavior

The image is built.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: OSX
Docker-Selenium image version: 4.0.0-alpha-6-20200609
Docker version: Docker version 19.03.1, build 74b1e89
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): N/A

**Comment by diemol** [comment]
Sorry, @take-five, that was my bad, the tag was generated wrongly.

I just pushed the images again with the correct formatted tag.
e.g. https://hub.docker.com/layers/selenium/node-base/4.0.0-alpha6-20200609/images/sha256-7c92f8107eebb433a3d8d526b1ea2f1590502754c2bece4757d41094f2567eb9?context=explore
