### ISSUE TITLE
Video recording support for Chrome using Chrome dev tools (No third party package needed)

### ISSUE THREAD

**Issue by bhaskard** [SeleniumHQ/docker-selenium#1070]
## 🚀 Feature Proposal

I have seen couple of issues like [this](https://github.com/SeleniumHQ/docker-selenium/issues/661) where people asking for video recording support. And the proposal got closed saying we can't have third party tools, which is a valid answer. But for the recent chrome browser we can have the video support using the chrome's in-built chromedev-tools, using screencast feature of it.

I agree `elgalu/selenium ` image has the support for the video, but not for the headless mode, so the users, to have the recording support in headless chrome mode, is still a gap, which can be solved using chrome dev tools API.

## Motivation

For one of our projects, we were in the need of recoding the tests, but the problem is we are running our tests in headless mode, and found that there is no possible way or solution available in the github and internet, that solves this issue. So after experimenting with the chrome dev tools API, we found that it is possible for chrome browser to have recording in headless mode. We have implemented it and it works as expected as well.

## Example

Using the chromedevtools API `Page.screencast` this is possible, if you are okay with the proposal, I can create a PR right away, which will help you to understand more about this. 

**Sample code below.**

  ```
def screen_cast_listener(self):
        """
        Get Screen cast Request Listener.
        """
        event = 'Page.startScreencast' //Start screencast
        self.page_interface.call_method(
            event)
        event = 'Page.screencastFrame'. //this is from chrome dev tools to start frame casting
        listener = self.page_interface.get_listener(event)
        if listener is None:
            listener = ScreenCastEventListener(self.page_interface)
        self.page_interface.set_listener(
            event, listener
        )
        return listener

    def remove_screen_cast_listener(self):
        """
        Remove Screen cast request listener.
        """
        event = 'Page.stopScreencast' //this is from chrome dev tools to stop casting
        self.page_interface.call_method(
            event)
```

**Comment by bhaskard** [comment]
@diemol

**Comment by diemol** [comment]
@bhaskard the idea is to add `ffmpeg`, but I am curious to know how your approach could work. What happens if the browser is Firefox?
Where and when would that code be invoked?

**Comment by bhaskard** [comment]
@diemol thanks for reply. The approach I do have works fine for Chrome browser but not on Firefox. Shall we have ffmpeg specifically for Firefox and for Chrome we can use my approach using screencasting?

**Comment by eugenepyvovarov** [comment]
I did some tests to record browser activity using ffmpeg but from another docker instance and did the record over the network.

**Comment by diemol** [comment]
That sounds like too much complexity to handle, besides we would be now depending on the DevTools, which changes on every release. I think it would be hard to maintain.

@eugenepyvovarov can you explain how you did it please?

**Comment by bhaskard** [comment]
Using ffmepg we can do easily for head browsers by recording the xvfb port numbers

**Comment by eugenepyvovarov** [comment]
I exposed port 99 alongside port 4444 in dockerfile of selenium/Standalone and modified xvfb start line to me like this 

`/usr/bin/Xvfb ${DISPLAY} -listen tcp -auth /tmp/xvfb.auth -screen 0 ${GEOMETRY} -dpi ${SCREEN_DPI} -ac +extension RANDR`

then from the other docker container, I do record like this:

`
sleep 3 && ffmpeg -f x11grab -video_size 1360x1020 -i selenium-webdriver:99.0 -c:v libx264rgb -crf 0 -preset ultrafast -r 20 -y /sides/out/video.mkv &
selenium-side-runner --server http://selenium-webdriver:4444/wd/hub /sides/*.side
sleep 3
killall ffmpeg
`

**Comment by bhaskard** [comment]
Shall we add this as a support in next release...if you want I will raise the PR for this

**Comment by eugenepyvovarov** [comment]
sleep added in the beginning and in the end since there is lag(i believe it comes because we record over the network)

**Comment by eugenepyvovarov** [comment]
I think if the images will have the possibility to connect to the X11 over the network - it will be awesome.

**Comment by diemol** [comment]
Actually, I think recording the video is not the hard part. I like the approach of doing it from another container by using the `xvfb` port. The problem is finding a good command for low CPU, a decent file size, and where will be the files stored?

**Comment by eugenepyvovarov** [comment]
> Actually, I think recording the video is not the hard part. I like the approach of doing it from another container by using the `xvfb` port. The problem is finding a good command for low CPU, a decent file size, and where will be the files stored?

To make it faster, I'd record it in the fastest mode and then encode it afterward.

**Comment by bhaskard** [comment]
Let me get back with a answer and approach for that

**Comment by bhaskard** [comment]
We can make the file path to be user configurable

**Comment by diemol** [comment]
>To make it faster, I'd record it in the fastest mode and then encode it afterward.
Where would that encoding happen?

**Comment by eugenepyvovarov** [comment]
well, it can be done elsewhere.

**Comment by diemol** [comment]
I know, but that is the thing. We cannot provide half a solution because we would end up getting tons of GitHub issues with questions about it. 
That is why it is taking a while, we need to provide a solution that is simple to maintain and has most of the answers ready for the users.

**Comment by eugenepyvovarov** [comment]
if it will be documented, how to record from another machine or process? will it be enough? or it should be done inside the same container where browser runs?

**Comment by bhaskard** [comment]
It should run in the machine where the test executes, like how we do save the screenshots

**Comment by diemol** [comment]
Documenting is an option, but a concept on how to manage the videos would be useful. For example, if I have a container running, and I run 10 tests on it. What is the output, 10 videos, or 1 long video? Or if I record video then I should only use a container once?
How are you collecting videos after a test suite is executed @eugenepyvovarov @bhaskard?

**Comment by bhaskard** [comment]
We do collect it without any compression in the running machine, in the same place where we store the screenshots.

We do have flags in our video recording library, which will help the user to record the video for all the tests as one, or separate videos for each test..it's configurable...also we have decorators to skip recording wherever you want @diemol

**Comment by diemol** [comment]
That sounds like code running on the client side, right? We should have something agnostic from frameworks I think.

**Comment by angiarao** [comment]
Looks like it might not be simple to make it framework agnostic. Correct me if i am wrong, I think atleast for headless mode, we need the client to pass remote debugging port. Then we need to listen to chrome port for open tabs and then we need to enable screencast and have service that collects the images. We should somehow identify its being closed (mitm?) and stop screencast and save it to a video. For head mode, I think the same or similar restrictions are present

**Comment by diemol** [comment]
@angiarao seems you are assuming we will use the Chrome DevTools for recording, which is not the case.

**Comment by diemol** [comment]
We added initial support through this [commit](https://github.com/SeleniumHQ/docker-selenium/commit/1a3b0e1cd6d9eb3f2d3b91a5f26e160ab50fcd6b). Improvements should come in the future.
