### ISSUE TITLE
multiple Selenium Nodes fail to connect to Hub occasionally when started simultaneously

### ISSUE THREAD

**Issue by maszczyn** [SeleniumHQ/docker-selenium#1072]
## 🐛 Bug Report

On a dockerized Selenium setup I get an occasional tests failure which is caused by a failed registration of the Selenium Node to Selenium Hub. It happens only when there's more than one dockerized node instance.

## To Reproduce

In order to help diagnose the issue I created a GitHub repo here:

https://github.com/maszczyn/selenium-registration-failure

Without the most recent commit ("add another node to reproduce the issue") the issue does NOT manifest itself. But even with the last commit, the issue appears only once per few hundred runs.

To reproduce the issue:
1. clone the repo & cd into it
```shell
$ git clone https://github.com/maszczyn/selenium-registration-failure.git
$ cd selenium-registration-failure
```

2. build the docker image with minimal application that will test whether Selenium Node registration succeeded
```shell
$ docker-compose build
```

3. make sure you have Selenium images available on your machine

```shell
$ docker-compose pull
```

4. run the verification loop with as many iterations as desired
```shell
$ ./run-loop.sh 1000
```

The verification loop will be stopped as soon as the issue is reproduced, and all diagnosis data will be saved to `run.log`. You may want to check / adjust what kind of data is saved to `run.log` by editing `run.sh` script.

## Actual result

An unsuccessful registration results in the following logs

### Selenium Hub

```
 Attaching to enveloop_selenium-hub_1
 selenium-hub_1  | 2020-06-22 01:22:24,254 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
 selenium-hub_1  | 2020-06-22 01:22:24,256 INFO supervisord started with pid 7
 selenium-hub_1  | 2020-06-22 01:22:25,258 INFO spawned: 'selenium-hub' with pid 10
 selenium-hub_1  | Starting Selenium Hub with configuration:
 selenium-hub_1  | 2020-06-22 01:22:25,266 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
 selenium-hub_1  | {
 selenium-hub_1  |   "host": "0.0.0.0",
 selenium-hub_1  |   "port": 4444,
 selenium-hub_1  |   "role": "hub",
 selenium-hub_1  |   "maxSession": 5,
 selenium-hub_1  |   "newSessionWaitTimeout": -1,
 selenium-hub_1  |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
 selenium-hub_1  |   "throwOnCapabilityNotPresent": true,
 selenium-hub_1  |   "jettyMaxThreads": -1,
 selenium-hub_1  |   "cleanUpCycle": 5000,
 selenium-hub_1  |   "browserTimeout": 0,
 selenium-hub_1  |   "timeout": 90,
 selenium-hub_1  |   "debug": true
 selenium-hub_1  | }
 selenium-hub_1  | 01:22:25.554 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
 selenium-hub_1  | 01:22:25.646 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
 selenium-hub_1  | 2020-06-22 01:22:26.010:INFO::main: Logging initialized @726ms to org.seleniumhq.jetty9.util.log.StdErrLog
 selenium-hub_1  | 01:22:26.176 INFO [Hub.start] - Selenium Grid hub is up and running
 selenium-hub_1  | 01:22:26.177 INFO [Hub.start] - Nodes should register to http://192.168.224.3:4444/grid/register/
 selenium-hub_1  | 01:22:26.177 INFO [Hub.start] - Clients should connect to http://192.168.224.3:4444/wd/hub
```

Hub reports that it's ready to receive connections from Nodes, but none happen.

### Selenium Node

```
 firefox_1       | 2020-06-22 01:22:25,668 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
 firefox_1       | 2020-06-22 01:22:25,669 INFO supervisord started with pid 7
 firefox_1       | 2020-06-22 01:22:26,671 INFO spawned: 'xvfb' with pid 10
 firefox_1       | 2020-06-22 01:22:26,672 INFO spawned: 'selenium-node' with pid 11
 firefox_1       | Connecting to the Hub using the host selenium-hub and port 4444
 firefox_1       | 2020-06-22 01:22:26,810 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
 firefox_1       | 2020-06-22 01:22:26,810 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
 firefox_1       | 01:22:27.001 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
 firefox_1       | 01:22:27.088 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
 firefox_1       | 2020-06-22 01:22:27.167:INFO::main: Logging initialized @352ms to org.seleniumhq.jetty9.util.log.StdErrLog
 firefox_1       | 01:22:27.431 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
 firefox_1       | 01:22:27.528 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
 firefox_1       | 01:22:27.528 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
 firefox_1       | 01:22:27.569 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
 firefox_1       | 01:22:27.898 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
```

Similarly on the Node side, it never completes the attempt to connect to Hub.

### Entropy source

While searching for root cause I also came across [this issue](https://github.com/SeleniumHQ/docker-selenium/issues/14), so I verified whether or not low entropy could be the problem.

`docker-compose exec -T firefox sudo cat /proc/sys/kernel/random/entropy_avail`:
```
3804
```

`docker-compose exec -T selenium-hub sudo cat /proc/sys/kernel/random/entropy_avail`:
```
3804
```

Apparently entropy is not the source of the issue.

BTW: values are the same, as the containers are run on the same host and, as far as I know, docker uses host's entropy source in the containers.

## Expected result

There should be a trace of a successful registration of Node(-s) to Hub:

### Selenium Hub
```
<output omitted>
selenium-hub_1  | 05:57:31.234 INFO [DefaultGridRegistry.add] - Registered a node http://172.21.0.3:5555
```

AND the Hub should report total slots count > 0 (this is actually the way the "test application" works in the repository I provided) - fetching `http://selenium-hub:4444/grid/api/hub` should return `slotCounts.total` number adequate to the number of registered node instances. See `e2e-tests/test_selenium_hub_availability.py` for more details.

### Selenium Node
```
<output omitted>
firefox_1       | 05:57:31.234 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
```

## Environment

OS: Linux
Docker-Selenium image version: 3.141.59-zirconium
Docker version: 19.03.12, build 48a66213fe
Docker-Compose version: 1.24.0, build 0aa59064

**Comment by diemol** [comment]
Hi @maszczyn,

You are very much likely bumping into a known issue, please check this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/1040#issuecomment-630233807).
You would need to build your own images to use that jar, but it is just a matter of changing this [line](https://github.com/SeleniumHQ/docker-selenium/blob/master/Base/Dockerfile#L70).

Please check that, and if the issue is not solved, feel free to reopen this issue.
