### ISSUE TITLE
"error": "unknown command"

### ISSUE THREAD

**Issue by cucamburs** [SeleniumHQ/docker-selenium#1088]
## 🐛 Bug Report

 Amazon Linux AMI
 SSH session to ec2-user@54.197.233.38
[ec2-user@ip-172-31-41-209 ~]$ sudo docker-compose up -d
Starting selenium-hub ... done
Starting ec2-user_chrome_1  ... done
Starting ec2-user_firefox_1 ... done
Starting ec2-user_opera_1   ... done

but during a move to http://54.197.233.38:4444 in Chrome browser
I get 
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002f",
    "stacktrace": ""
  }
}

**Comment by diemol** [comment]
@cucamburs could you please fill out the complete template? Most of it has been ignored.

**Comment by cucamburs** [comment]
A clear and concise description of what the bug is.





## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
when going to the address http://54.197.233.38:4444/
## Expected behavior

A clear and concise description of what you expected to happen.
I expected the welcome page
## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Amazon Linux
Docker-Selenium image version: 


Docker-Compose version (if applicable):
Docker version: Docker version 18.03.1-ce, build 9ee9f40
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.0.0-alpha-6-20200721
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.0.0-alpha-6-20200721
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:4.0.0-alpha-6-20200721
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub

  opera:
    image: selenium/node-opera:4.0.0-alpha-6-20200721
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub


Thank you

**Comment by cucamburs** [comment]
docker-compose version 1.22.0, build f46880fe

**Comment by diemol** [comment]
>I expected the welcome page

Which welcome page?

**Comment by cucamburs** [comment]
Selenium Grid Hub

**Comment by diemol** [comment]
Grid 4 is in alpha stages right now, perhaps you are looking for Grid 3?
If so, please check the readme on https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3
(Updates to the docs and readme are work in progress)

**Comment by cucamburs** [comment]
I was taking this image on AWS: buildkite-stack-2018-09-04T04-02-59Z - ami-002059eaf5c28a9e6
Buildkite CloudFormation Stack base image (Amazon Linux, buildkite-agent, docker, docker-compose, docker-gc, jq)
Next I updated Docker and install 1.8.0. java jdk

**Comment by diemol** [comment]
Did you check my previous comment? Grid 4 (the images you are using), does not have a UI yet. So no "welcome page" is available.

**Comment by cucamburs** [comment]
Yes you are right! Thank you! I took v.3 and everything worked out
