### ISSUE TITLE
https://hub.docker.com/r/selenium/hub/ Dockerfile link is broken

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#109]
Hi,
Kindly fix link selenium/hub Dockerfile under https://hub.docker.com/r/selenium/hub/.
currently it takes to invalid page sometimes.

Thanks,
Vikram

**Comment by diemol** [comment]
Hi @vikramvi !
I checked and the link is correct now, can you please close the issue? 
Thanks!
