### ISSUE TITLE
Container not connect the selenium hub

### ISSUE THREAD

**Issue by tanoggy** [SeleniumHQ/docker-selenium#1091]
## 🐛 Bug Report

Build image from docker file not connect to hub

## To Reproduce

docker build -t node-firefox . NodeFirefox

## Environment

OS: 20.04 LTS (Focal Fossa)
Docker-Selenium image version: selenium/hub:latest
Also provide the docker image id 
--> c944a48185ab
Docker version: Docker version 19.03.8, build afacb8b7f0
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Hi @tanoggy 
Please have a look at the instructions to build your own images here
https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images

Feel free to reopen in case something does not work.

**Comment by tanoggy** [comment]
I follow the instruction but image not working
