### ISSUE TITLE
[ReadMe] Dead link in Debugging section

### ISSUE THREAD

**Issue by lobsterick** [SeleniumHQ/docker-selenium#1093]
## 🐛 Bug Report

Tere is dead link inside README.md in `Debugging` section.

## To Reproduce

1. Enter https://github.com/SeleniumHQ/docker-selenium#debugging
2. In line `If you are running Boot2Docker on OS X then you already have a VNC client built-in. You can connect by entering vnc://<boot2docker-ip>:49160 in Safari or Alfred.` try to click on **VNC client**, that should redirect to [davidtheexpert.com](http://www.davidtheexpert.com/post.php?id=5) page.
3. This site is unavailable.

## Expected behavior

To be honest - i don't know. I didn't find good enough link to propose here.

Issues without a reproduction script are likely to stall and eventually be closed.

**Comment by diemol** [comment]
I removed that part of the section since `Boot2Docker` is quite old anyway. Thank you for reporting this.
