### ISSUE TITLE
Docker-Compose not working

### ISSUE THREAD

**Issue by ryanvito** [SeleniumHQ/docker-selenium#1102]
## 🐛 Bug Report

I have tried all the versions of docker-compose 100% stock and with tags changed to latest without success. As-written I get:
Ready: false,
message: Selenium Grid not ready

With latest tag:
{
  "status": 0,
  "value": {
    "ready": false,
    "message": "No spare hub capacity",
    "build": {
      "revision": "e82be7d358",
      "time": "2018-11-14T08:25:53",
      "version": "3.141.59"
    },
    "os": {
      "arch": "amd64",
      "name": "Linux",
      "version": "4.19.76-linuxkit"
    },
    "java": {
      "version": "1.8.0_252"
    }
  }
}

I have confirmed the nodes are online and I have tried this on docker-for-mac and on linux x86.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
docker-compose -f docker-compose-v2.yml -d
or
docker-compose -f docker-compose-v3.yml -d

Then check status at: http://localhost:4444/wd/hub/status

## Expected behavior

I expected the hub to become ready and have capacity as outlined in the README.md

## Environment

OS: OSX and Ubuntu 18.04 64-bit
Docker-Selenium image version: 4.0.0-alpha-6-20200730 and tag latest (Not built from source here)
Also provide the docker image id 
-->
Docker version: 10.03.8
Docker-Compose version (if applicable): 1.25
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): v2 and v3 from the master branch.

**Comment by diemol** [comment]
@ryanvito Our bad, we updated the readme before pushing the images.

We just did a pre-release, and updated the readme with instructions to use the Grid 4 Alpha 7 prerelease images.

Please have a look https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-alpha-7-prerelease-20200826

**Comment by ryanvito** [comment]
Thank you for your quick reply! It works now!

**Comment by despellhtb** [comment]
This also not work for version selenium 3.

`version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200730
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200730
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:3.141.59-20200730
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  opera:
    image: selenium/node-opera:3.141.59-20200730
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

`

**Comment by diemol** [comment]
@despellhtb no, that docker compose is only for Grid 4
Grid 3 resources can be found here https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3
