### ISSUE TITLE
Latest docker has outdated chromedriver - please update ASAP

### ISSUE THREAD

**Issue by rnonez** [SeleniumHQ/docker-selenium#1108]
## 🐛 Bug Report

The latest docker-selenium release 3.141.59-20200826
contains an outdated chromedriver: 85.0.4183.83
please release a new docker image with the latest chromedriver: 85.0.4183.87

## To Reproduce

N/A

## Expected behavior

N/A

## Test script reproducing this issue (when applicable)

N/A

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Hi @rnonez,
Thank you for opening this issue. Right now we do not have bandwidth to do a release. However, if you need this ASAP, you can do it yourself by building the Docker images locally and using them while we do a release. 
Here is a guide that will show you how to unblock yourself: https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images

**Comment by rnonez** [comment]
Ok thank you @diemol.
Do you have even a rough ETA for when this will become available?

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20201010
