### ISSUE TITLE
RemoteWebDriver not opening session with alpha 7 grid configuration in C#

### ISSUE THREAD

**Issue by shoaibshaikh7** [SeleniumHQ/docker-selenium#1109]
## 🐛 Bug Report

When we create a grid setup with the Selenium 4 Alpha 7 selenium-hub the RemoteWebDriver is not opening the browser when the code is run using C#.

Below is the Code used to debug :

`ChromeOptions options = new ChromeOptions();
  var capabilities = options.ToCapabilities();
 IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);
 driver.Navigate().GoToUrl("https://www.google.com/");
 driver.Quit();`

Whereas the same works fine with the Selenium Grid 3 Setup [https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3](url)

## To Reproduce

Start a container with below Docker-Compose file

`version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200907
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20200907
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"`

Once the Grid is up [http://localhost:4444/status](url)

![image](https://user-images.githubusercontent.com/45842410/92782576-b0954900-f3c2-11ea-8556-929b2d010217.png)

Please debug the below code using Visual Studio 19

`ChromeOptions options = new ChromeOptions();
  var capabilities = options.ToCapabilities();
 IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);
 driver.Navigate().GoToUrl("https://www.google.com/");
 driver.Quit();`

It gives error : 

OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out after 60 seconds.'

Inner Exception : TaskCanceledException: A task was canceled.

![image](https://user-images.githubusercontent.com/45842410/92782052-48defe00-f3c2-11ea-9dfc-3fe967cec239.png)

## Expected behavior

A Google browser should get open in the container which can be viewed from VNC viewer.

## Works Fine With below docker compose : 

`version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200826
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
       - GRID_MAX_SESSION=20
       - GRID_BROWSER_TIMEOUT=300

  chrome1:
    image: selenium/node-chrome-debug:3.141.59-20200826
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
    - "9001:5900"
    links:
     - selenium-hub
 `
![image](https://user-images.githubusercontent.com/45842410/92783876-c5bea780-f3c3-11ea-9eb5-d1c013928d3c.png)

## Environment where it is not working :

Windows 10
Docker version 19.03.12, build 48a66213fe
Selenium Image : 4.0.0-alpha-7-prerelease-20200907

-->
Docker : 

![image](https://user-images.githubusercontent.com/45842410/92782262-72982500-f3c2-11ea-9e2d-f2a0ea4d71b5.png)

**Comment by diemol** [comment]
@shoaibshaikh7 please do not delete the issue template
what version of the C# bindings are you using?

**Comment by shoaibshaikh7** [comment]
> what version of the C# bindings
.Net framework:  4.7.2 and C# version 8 by default
If I am not answering your question properly please direct me to appropriate resources on how can I find the binding version of C#.

**Comment by diemol** [comment]
You can find the versions here https://www.nuget.org/packages/Selenium.WebDriver

**Comment by shoaibshaikh7** [comment]
> You can find the versions here https://www.nuget.org/packages/Selenium.WebDriver

"Selenium.Chrome.WebDriver" version="85.0.0" targetFramework="net472"
 "Selenium.Support" version="4.0.0-alpha05" targetFramework="net472"
 "Selenium.WebDriver" version="4.0.0-alpha05" targetFramework="net472"

**Comment by lemieuxdevon** [comment]
I thought for the new grid, you would enter the uri into the RemoteWebDriver constructor without the /wd, just the http://localhost:4444/

**Comment by shoaibshaikh7** [comment]
> I thought for the new grid, you would enter the uri into the RemoteWebDriver constructor without the /wd, just the http://localhost:4444/

Yes, Correct, but when we try to run the test case with 4.0.0-alpha05 it doesn't start the browser, but it works with the 3.141.0 version.

**Comment by lemieuxdevon** [comment]
> > I thought for the new grid, you would enter the uri into the RemoteWebDriver constructor without the /wd, just the http://localhost:4444/
> 
> Yes, Correct, but when we try to run the test case with 4.0.0-alpha05 it doesn't start the browser, but it works with the 3.141.0 version.

So when you run the test case against the 4.0 grid, you are passing the url as http://localhost:4444/ and not http://localhost:4444/wd? And it still does not connect?

**Comment by shoaibshaikh7** [comment]
> > > I thought for the new grid, you would enter the uri into the RemoteWebDriver constructor without the /wd, just the http://localhost:4444/
> > 
> > 
> > Yes, Correct, but when we try to run the test case with 4.0.0-alpha05 it doesn't start the browser, but it works with the 3.141.0 version.
> 
> So when you run the test case against the 4.0 grid, you are passing the url as http://localhost:4444/ and not http://localhost:4444/wd? And it still does not connect?

yes, same Error.
![image](https://user-images.githubusercontent.com/45842410/94167102-bc483b80-fea9-11ea-833b-6426ec50b7a3.png)

**Comment by diemol** [comment]
👋 @shoaibshaikh7 
Could you please try again with the latest prerelease?
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-prerelease-beta-1-prerelease-20201127

**Comment by ghost** [comment]
Hey, I'm seeing the same thing.

I'm running in AKS, so not exactly the same scenario as @shoaibshaikh7, but am seeing the same outcome.

I have started the grid with ```4.0.0-beta-1-prerelease-20201130``` and am using ```4.0.0-alpha07``` c# bindings.

![image](https://user-images.githubusercontent.com/15614856/100899019-4966cc80-34b9-11eb-803b-9e3c7537a41f.png)

Happy to help wherever possible.

**Comment by ghost** [comment]
I have access to the grid without issue... from ```http://n.n.n.n.n:4444/status```

```
{
	"value": {
		"ready": true,
		"message": "Selenium Grid ready.",
		"nodes": [{
			"id": "b4aecc98-211e-47bc-b9c0-15ff961a6698",
			"uri": "http:\u002f\u002f10.240.0.172:5555",
			"maxSessions": 1,
			"slots": [{
				"lastStarted": "1970-01-01T00:00:00Z",
				"stereotype": {
					"browserName": "chrome"
				},
				"id": {
					"hostId": "b4aecc98-211e-47bc-b9c0-15ff961a6698",
					"id": "046acc8d-06f2-4b13-8a22-23bf53a55e5c"
				}
			}],
			"availability": "UP"
		}]
	}
}
```

**Comment by diemol** [comment]
@matthew-horrocks, how does your code look like?
What if you use the same code from above but in Java? 
Just trying to find out where the issue could be.

**Comment by ghost** [comment]
Hi, 

I'll need to try java tomorrow.

c#

```
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;
using System;

namespace simpletestforgithub
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void Test1()
        {
            ChromeOptions chromeOptions = new ChromeOptions();
            IWebDriver Driver = new RemoteWebDriver(new Uri("http://n.n.n.n:4444/"), chromeOptions.ToCapabilities());
        }
    }
}
```

**Comment by shoaibshaikh7** [comment]
> 👋 @shoaibshaikh7
> Could you please try again with the latest prerelease?
> https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-prerelease-beta-1-prerelease-20201127

@diemol : I tried running with 4.0.0-beta-1-prerelease-20201202 and am using 4.0.0-alpha07 c# bindings and it worked.

**Comment by diemol** [comment]
Great, thank you for letting us know.
