### ISSUE TITLE
Vulnerable Docker command lines in README

### ISSUE THREAD

**Issue by erno** [SeleniumHQ/docker-selenium#1117]
## 🐛 Bug Report

The presented "docker run -p 4444:4444 [...]" style commandlines let everyone on the internet connect to the container and there is no authentication in the examples. Docker even helpfully manipulates the firewall to make sure this works (
docker/for-linux#690). This should be changed to bind to localhost like so: "-p 127.0.0.1:4444:4444".

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
Clear self-contained example:
1. run the example in the readme: docker run -d -p 4444:4444 --shm-size 2g selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200921
2. verify that it binds to 0.0.0.0 with eg netstat

## Expected behavior

The Selenium server is only accessible by me.

## Test script reproducing this issue (when applicable)

docker run -d -p 4444:4444 --shm-size 2g selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200921; sleep 5; netstat -nat | grep 4444; sudo iptables -L|grep 4444

## Environment

OS:  Linux
Docker-Selenium image version: Tested with the README version (selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200921) but the bug is not image dependent 
Docker version: Docker version 19.03.8, build afacb8b7f0
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker run -d -p 4444:4444 --shm-size 2g selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200921

**Comment by diemol** [comment]
@erno thank you for creating this issue, it helps to raise more awareness about the care users should have when deploying a Selenium Grid.
However, securing access to it is out of the scope, as it is a task done that should be done by the infrastucture team. We also mention this in our documentation https://www.selenium.dev/documentation/en/grid/grid_3/setting_up_your_own_grid/

Therefore, I will close this since there is no action for us.

**Comment by erno** [comment]
Please reconsider: It's pretty frowned upon if your software, in this case allowing remote control of a browser in your network, is open by default to the whole internet without authentication in 2020. The fact that there is a mention of this in detailed documentation is small comfort for people who follow the quick start in the  README.  And the fix would be trivial.
