### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/selenium.conf" not found: not found

### ISSUE THREAD

**Issue by Tylersuard** [SeleniumHQ/docker-selenium#1118]
## 🐛 Bug Report

I downloaded the dockerfile for selenium/node-chrome:4.0.0-alpha-7-prerelease20200921

building the dockerfile gives this error:

failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/selenium.conf" not found: not found

## To Reproduce

1. Download Dockerfile from here https://github.com/SeleniumHQ/docker-selenium/blob/trunk/StandaloneChrome/Dockerfile
2.  Attempt to build

## Expected behavior

I expected the container image to be built.  Do I need to add any extra files?  Which ones, and what need to be in them?  Could you have more detailed instructions please?

## Environment

Windows 10

Docker-Selenium image version: selenium/node-chrome:4.0.0-alpha-7-prerelease20200921

**Comment by diemol** [comment]
@Tylersuard you'd need to use `make` commands to build the images. Here is a quick guide that shows how to do it. https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images
