### ISSUE TITLE
How / Where to set node related parameter values 

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#112]
Hi,

java -jar selenium-server-standalone.jar -role hub 
-hubConfig selenium_hub.json 
-nodeTimeout 61 
-remoteControlPollingIntervalInSeconds 180 
-sessionMaxIdleTimeInSeconds 240 
-newSessionMaxWaitTimeInSeconds 250 
-timeout 59

Please clarify how to set these values wrt Docker HUB / Node

I had checked https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile

But it doesn't have all the necessary parameters as above ?

https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/java/server/src/org/openqa/grid/common/defaults/NodeOptions.json

Thanks in advance.

Regards,
Vikram

**Comment by rubytester** [comment]
For Node I would recommend you make your own config.json file and build a new image based on base image. The node config.json is a minimalistic config.

For Hub the ENV values are used to generate the config.json for the hub (with 8 parameters using values from env var)
https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/generate_config

What is your usecase?

**Comment by vikramvi** [comment]
Hi RubyTester,

Thanks for reply. I'm trying out Docker + Grid setup per your Selenium conf tech talk

But facing with below issues

1. https://github.com/SeleniumHQ/docker-selenium/issues/111

2. How to determine how many nodes / docker containers I can have ?

Thanks in advance.

Regards,
Vikram

**Comment by apakhomov** [comment]
No need to rebuild image for node. You can add config.json as a volume into the containers.

**Comment by diemol** [comment]
Hi @vikramvi,
Right now it is possible to do that with the env vars present in the [Dockerfile](https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile#L15). 

You just need to pass them in the `docker run` command, adding (e.g.) `-e GRID_MAX_SESSION=10`.

**Comment by ddavison** [comment]
That's correct.  most (if not all) necessary parameters are added to the Dockerfile's, both for nodes and the hub.
