### ISSUE TITLE
docker-compose-v3-video.yml file is not working properly. It fails while pulling the selenium/video:ffmpeg-4.3.1-20200920 image. I tried to pull this manually too but getting the below error "Error response from daemon: manifest for selenium/video:ffmpeg-4.3.1-20200920 not found: manifest unknown: manifest unknown"

### ISSUE THREAD

**Issue by amuthansakthivel** [SeleniumHQ/docker-selenium#1120]
## Environment

Unable to pull the image selenium/video:ffmpeg-4.3.1-20200920 image.

When I tried build the selenium-grid infrastructure using docker-compose-v3-video.yml it is failing while pulling the selenium/video:ffmpeg-4.3.1-20200920 image.

Then I tried to pull it manually and again faced the same issue.

OS: Windows 10
Docker version: 19.03.1
Docker-Compose version (if applicable): 1.24.1

**Comment by diemol** [comment]
@amuthansakthivel you are right, there is an error in the example file, [here](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml#L46) and [here](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml#L56). The correct image is `selenium/video:ffmpeg-4.3.1-20200921`.

Would you like to send a pull request to fix that?

**Comment by amuthansakthivel** [comment]
Yes I will send a pull request soon.

**Comment by amuthansakthivel** [comment]
For some weird reasons i could not create a new branch for changes. Could you please make the change yourself. Thanks for understanding.

**Comment by diemol** [comment]
@amuthansakthivel could this guide help you to get the PR created?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by amuthansakthivel** [comment]
Thanks. This document helped. PR is raised.

**Comment by diemol** [comment]
Closed via #1123
