### ISSUE TITLE
Selenium console is not displayed after starting the containers using docker-compose-v3-video.yml

### ISSUE THREAD

**Issue by amuthansakthivel** [SeleniumHQ/docker-selenium#1122]
## 💥 Regression Report
I have spinned up all the containers for selenium grid using the docker-compose-v3-video.yml file.
I have verified the same using docker ps command
I have pointed my tests to http://localhost:4444/wd/hub and my tests ran fine. However I noticed that when I load the URL http://localhost:4444 in the browser, it is not showing the selenium-grid console page.

Instead I am getting this error 
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002f",
    "stacktrace": ""
  }
}

Also I could not see the videos in my local machine after the test execution.

OS: Windows 10
Docker version: 19.03.1
Docker-Compose version (if applicable): 1.24.1

**Comment by diemol** [comment]
The currently released Grid does not have a UI yet, please stay tuned for the upcoming released where one will be present.
