### ISSUE TITLE
Grid 4. Unable to limit number of maxSession within node via passing NODE_MAX_SESSION=3

### ISSUE THREAD

**Issue by seoslav** [SeleniumHQ/docker-selenium#1128]
## 🐛 Bug Report

Grid 4. Unable to limit number of maxSession within single node via passing NODE_MAX_SESSION=3 either on hub or node level.

## To Reproduce
Detailed steps to reproduce the behavior:
1. Create hub
`docker run -d -p 4442-4444:4442-4444 -e NODE_MAX_SESSION=3 -e NODE_MAX_INSTANCES=1 -e GRID_MAX_SESSION=5 --net grid --name selenium-hub selenium/hub:4.0.0-alpha-7-prerelease-20201009`
2. Create at least one node:
`docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e NODE_MAX_SESSION=3 -e NODE_MAX_INSTANCES=1 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009`
3. Check status page:
`"value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "a07dfee7-5136-4753-beb6-53c791536c83",
        "uri": "http:\u002f\u002f172.22.0.3:5555",
        "maxSessions": 4,
        "slots": [`

## Expected behavior
MAX_SESSION=3

## Environment

OS: Windows 10
Browser: Chrome
Selenium Grid version (if applicable):  4.0.0

**Comment by omarmhaimdat** [comment]
I am still experiencing the same issue, and nothing works. The "maxSessions" variable is always set up at 2. Tested on firefox and chrome. I'm using the docker-compose-v3-full-grid.yml file.

**Comment by youssefqarri** [comment]
I am facing the same issue from my side.

**Comment by diemol** [comment]
I just fixed this in the main repository, and it will be released in the next couple of days. Please keep an eye on the releases for this repo.

**Comment by anandshende06051994** [comment]
Hey, any updates on this?

**Comment by diemol** [comment]
This was already fixed and released. Please check the most recent release.

**Comment by mikej411** [comment]
I am running Server 4 Beta 1, and I can not set my max sessions past 2. From what I read, Server 4 is limiting the max sessions based on the servers processor count. Is this just temporary until the full release comes out? If not, why is it limiting? I have been executing 10 tests in parallel on each server with no issues, and now I have to limit that to only 2 tests if I want to upgrade?
