### ISSUE TITLE
Grid 4 Docker - Remote node is not registered to Hub

### ISSUE THREAD

**Issue by bpoobesh29** [SeleniumHQ/docker-selenium#1130]
## To Reproduce
I am trying to set up Hub and Node on 2 different hosts with docker - The Node Chrome from host machine 2 is not registered 
with Hub on host machine 1

**On Host machine 1: Started the Hub with below command**
> docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.0.0-alpha-7-prerelease-20201009

# Logs from Host machine 1
2020-10-28 15:35:10,312 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2020-10-28 15:35:10,313 INFO supervisord started with pid 8
2020-10-28 15:35:11,316 INFO spawned: 'selenium-grid-hub' with pid 11
Starting Selenium Grid Hub...
2020-10-28 15:35:11,322 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:35:11.632 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
15:35:11.633 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
15:35:11.702 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.17.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.17.0.2:4443]
15:35:11.735 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.17.0.2:4442 and tcp://172.17.0.2:4443
15:35:11.755 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:35:11.756 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
15:35:11.956 INFO [BoundZmqEventBus.<init>] - Event bus ready
15:35:12.417 INFO [Hub.execute] - Started Selenium hub 4.0.0-alpha-7 (revision bd15e4e88a): http://172.17.0.2:4444

**On Host machine 2: Starting the Node-Chrome with below command**
> docker run -d -e SE_EVENT_BUS_HOST=_<Host machine 1 IP address>_ -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009

# Logs from Host machine 2:
2020-10-28 15:37:33,866 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2020-10-28 15:37:33,867 INFO supervisord started with pid 8
2020-10-28 15:37:34,870 INFO spawned: 'xvfb' with pid 11
2020-10-28 15:37:34,871 INFO spawned: 'vnc' with pid 12
2020-10-28 15:37:34,873 INFO spawned: 'selenium-node' with pid 13
2020-10-28 15:37:34,985 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-10-28 15:37:34,985 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-10-28 15:37:34,985 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:37:36.567 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
15:37:36.568 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
15:37:36.637 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://_<Host machine 1 IP address>_:4442 and tcp://_<Host machine 1 IP address>_:4443
15:37:36.684 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:37:36.686 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
15:37:36.904 INFO [NodeServer.execute] - Reporting self as: http://172.17.0.2:5555
15:37:36.907 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
15:37:36.909 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://_<Host machine 1 IP address>_:4442 and tcp://_<Host machine 1 IP address>_:4443
15:37:36.911 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:37:36.912 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
15:37:37.189 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times
15:37:37.370 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-7 (revision bd15e4e88a): http://172.17.0.2:5555
15:37:37.371 INFO [NodeServer.execute] - Starting registration process for node id a63c1fb1-813e-478d-8fae-919bd950b399

**GRID Status:**
{
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
    ]
  }
}

## Expected behavior
Node Chrome should be registered with Hub - The same behavior observed even with docker-compose 

## Environment
OS: Linux/RHEL7 
Docker-Selenium image version: selenium-hub selenium/hub:4.0.0-alpha-7-prerelease-20201009 and selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009
Docker version: 19.03.13

**Comment by LubikR** [comment]
According to your commands you have no created separate docker network so you have to publish ports 4442 to 4444 on Selenium hub docker container. Better is to try with this example : https://github.com/SeleniumHQ/docker-selenium#docker-networking

**Comment by bpoobesh29** [comment]
> According to your commands you have no created separate docker network so you have to publish ports 4442 to 4444 on Selenium hub docker container. Better is to try with this example : https://github.com/SeleniumHQ/docker-selenium#docker-networking

Thanks @LubikR for the reply. 
I tried both options now and it does not seems to be resolving.

1. Published ports as below and still seeing same issue:
> docker run -d -p 4442-4444:4442-4444 --name selenium-hub selenium/hub:4.0.0-alpha-7-prerelease-20201009
 
2. I gave it a try by setting up the network "--net grid" as well on the host machine 1 and when connecting from host machine 2, still node is not registered. 

Any feedback is appreciated...!

**Comment by LubikR** [comment]
Hmm. Do you have any running container which has full internet access, meaning from container to outside? I read somewhere that RHEL has some problem with docker vs firewall, I don`t remember exactly. Try to stop firewalld and restart docker and contrainers.

**Comment by olivia-hhe** [comment]
We are experiencing the same issue. And we tried to run the hub in host network:
Started the Hub with below command in instance 1:
`docker run --network host  --name selenium-hub  --rm selenium/hub:4.0.0-alpha-7-prerelease-20201009`
Started the node with below command in instance 2:
`docker run -it --rm -p 5555:5555 -e SE_EVENT_BUS_HOST=<IP of instance 1> --network host   -e SE_EVENT_BUS_PUBLISH_PORT=4442   -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443   -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009`

Hope this helps!

**Comment by diemol** [comment]
@bpoobesh29, this should be fixed in the most recent prerelease, https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20201130, we also added some instructions on how to specify IPs when using more than one VM, https://github.com/SeleniumHQ/docker-selenium#using-different-machinesvms
