### ISSUE TITLE
Standalone container for MS Edge Chromium

### ISSUE THREAD

**Issue by reneadamqa** [SeleniumHQ/docker-selenium#1134]
## 🚀 Feature Proposal

Hi Selenium folks! It would be awesome to implement another standalone container for Microsoft Edge Chromium on this docker selenium image to reveal our E2E pipeline with more customer based browsers.

## Motivation

As mentioned in several articles ([Link1](https://www.extremetech.com/internet/308866-microsoft-edge-surpasses-firefox-usage-share) and [Link2](https://www.computerworld.com/article/3199425/top-web-browsers-2020-edge-makes-double-digits.html)), the market share of MS Edge is expanding and business users may will have a focus on adopting MS Edge with organization regulations which are adjustable on Edge but not on Chrome.

It is clear that both browsers are working and based on Chromium and have many similarities. Anyway, as mentioned in some articles ([Link3](https://www.digitaltrends.com/computing/microsoft-edge-vs-google-chrome/) and [Link4](https://www.lifewire.com/microsoft-edge-vs-google-chrome-4689177)), MS Edge offers way more Security & Privacy settings which can be used and adopted for E2E tests. Although tests are already created for Chrome, some customers of us are willing to invest time for adopting E2E tests for MS Edge operation as MS Edge will be their browser of choice in the whole company.

Microsoft [already released](https://hub.docker.com/_/microsoft-msedge-msedgedriver) a Docker Hub image for MS Edge driver but as its ONLY running on Windows machines, its not adoptable with our current Selenium setup. Just talked with the MS Edge Dev Team and they told be to happily support you to make Selenium ready for MS Edge Chromium 🙂 

## Example

Create a standalone container for MS Edge Chromium which can be used for E2E tests on Docker Selenium.

MS Edge DEV is [already released](https://www.microsoftedgeinsider.com/de-de/download) for Linux.

**Comment by diemol** [comment]
@rene1039, we will be happy to accept any PRs that add Microsoft Edge on Linux when it is on the `stable` channel.  We do not add browsers in any different state than `stable` because we do not have the bandwidth to support them.

I will close this since MS Edge under Linux is still in `dev`.
