### ISSUE TITLE
Router is unable to access nodes from another host

### ISSUE THREAD

**Issue by omarmhaimdat** [SeleniumHQ/docker-selenium#1141]
# 🐛 Bug Report

I have launched all the hub components simultaneously and launched a node in a **different** host, the node starts with no issues, the distributor added the node, but the router is unable to see the available node even though the distributor added the node. The status of the router doesn't change.

### selenium-distributor logs

![image](https://user-images.githubusercontent.com/2160742/99699628-731ffc80-2a92-11eb-80bf-17e92029584a.png)

## To Reproduce

- Start all the hub component at the same time using below code:
[docker-compose file to start the hub components](https://gist.github.com/omarmhaimdat/5e4afb5c4ccd6293643dcf32add5a876) 
- Then start a node in a **different** host, make sure to change the event-bus IP address
[docker-compose file to start a node in a **different** host](https://gist.github.com/omarmhaimdat/64ee0d41c6e34f99b84965049ab58951)

## Expected behavior

Router being able to register the node and be able to know the number of available sessions.

## Test script reproducing this issue (when applicable)

look at the steps to reproduce.

## Environment

OS: Windows 10,  Ubuntu 16.04.6 LTS
Docker-Selenium image version: 4.0.0-alpha-7-prerelease-20201009

Docker version: 19.03.13
Docker-Compose version (if applicable): 3
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose -f docker-compose-file.yml up -d`

**Comment by diemol** [comment]
Not sure why the bot closed it, I will double check.

**Comment by fnrcum** [comment]
I'm experiencing the same thing but in some instances the node does not connect at all to the hub

**Comment by olivia-hhe** [comment]
We are experiencing the same issue. 
It looks like the same issue as https://github.com/SeleniumHQ/docker-selenium/issues/1130, in which hub is a union of Router, Distributor, Session Map, and Event Bus
Please try run these components in host network, referring to https://github.com/SeleniumHQ/docker-selenium/issues/1130#issuecomment-730573435

**Comment by diemol** [comment]
@omarmhaimdat, this should be fixed in the most recent prerelease, https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20201130, we also added some instructions on how to specify IPs when using more than one VM, https://github.com/SeleniumHQ/docker-selenium#using-different-machinesvms
