### ISSUE TITLE
C# RemoteWebDriver: Content-Type header is missing exception when using alpha-7

### ISSUE THREAD

**Issue by victorBychinski** [SeleniumHQ/docker-selenium#1145]
## 🐛 Bug Report

Getting Content-Type header is missing exception when trying to use RemoteWebDriver on C#. It seems like relax-checks flag does not work as expected.

The probles reproduces on local docker and on Kubernetes env.
## To Reproduce

1. Follow the steps described in Readme:
```
docker network create grid
$ docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.0.0-alpha-7-20201119
$ docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /dev/shm:/dev/shm \
    selenium/node-chrome:4.0.0-alpha-7-20201119
$ docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /dev/shm:/dev/shm selenium/node-firefox:4.0.0-alpha-7-20201119
$ docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /dev/shm:/dev/shm selenium/node-opera:4.0.0-alpha-7-20201119
```
2. Try to use the grid

## Expected behavior

It should be possible to run tests using RemoteWebDriver

## Test script reproducing this issue (when applicable)

`           var options = new ChromeOptions();
            options.AddUserProfilePreference("download.default_directory", DownloadDirectory);
            options.AddUserProfilePreference("intl.accept_languages", "	en-GB");
            options.AddUserProfilePreference("disable-popup-blocking", "true");
            options.AddUserProfilePreference("profile.default_content_settings.popups", 0);
            options.AddUserProfilePreference("profile.default_content_settings.multiple-automatic-downloads", 1);
            options.AddUserProfilePreference("download.directory_upgrade", true);
            options.AddUserProfilePreference("download.prompt_for_download", false);
            options.AddUserProfilePreference("download.extensions_to_open", "");
            options.SetLoggingPreference("Browser", LogLevel.All);.`
            options.AddArgument("--headless");
            options.AddArgument("--no-sandbox");
            options.AddArgument("--disable-dev-shm-usage");
            options.AddArgument("--window-size=1920,1080");
            driver = new RemoteWebDriver(new Uri("REMOTE_URL_GOES_HERE"), options.ToCapabilities(), TimeSpan.FromSeconds(10000));
## Environment

OS:  Windows 10
Docker-Selenium image version:  4.0.0-alpha-7-20201119
Docker version:  19.03.13, build 4484c46d9d

**Comment by jimevans** [comment]
Fixed in [62bb990](https://github.com/SeleniumHQ/selenium/commit/62bb990cdb9e3ac05ea7ac5b4c73c0a691242da9)

**Comment by victorBychinski** [comment]
@jimevans  hello. I`ve talked with @diemol  about the issue - that is what he said:
 if you are using the alpha-7-20201119 docker images, you should not be bumping into this issue because (for now) they are started with a flag that ignores the check.

there is a flag in the hub called relax-checks, and it is set to true, it is now being configured through the config.toml file, so you should not be hitting that
if you are hitting that issue, probably the file configuration is not working
can you please create an issue

**Comment by diemol** [comment]
This was fixed in the linked commit above for C#, but there was also a bug in the Grid that made the `relax-checks` value to be ignored when it was configured through a file. 
We'll do a release in the following days for the docker images, and you can all try it again. Please keep an eye on the releases.
