### ISSUE TITLE
Docker Node on Dynamic Grid hangs when starting a new session on Ubuntu Server 20.04.1 LTS

### ISSUE THREAD

**Issue by Davipb** [SeleniumHQ/docker-selenium#1147]
## 🐛 Bug Report

When running a Dynamic Grid on Ubuntu Server 20.04.1 LTS, trying to start a new session causes the Docker Node to hang on "Waiting for server to start" and time out after 1 minute, despite the newly-created session container having started correctly. This doesn't happen when running on Windows 10.

## To Reproduce
1. Spin up a clean Ubuntu Server 20.04.1 LTS VM
2. Run this script as root: https://gist.github.com/Davipb/4799a2c76d91e5d16249ee0a5353d06a
3. Note how the new session request hangs forever or times out. 
   * If you check the logs with `docker-compose -f /selenium/docker-compose.yml logs`, you'll see the docker node is stuck waiting for the newly created Firefox container to start, despite it already having started
   * You can confirm the Firefox container started correctly by grabbing its assigned port with `docker container ls` then running `curl localhost:XXXX/wd/hub/status` (where `XXXX` is the port). It should return `"ready": true`.

Alternatively, if you want to do it manually or on an existing system:
1. Get a system running Ubuntu Server 20.04.1 LTS with Docker and Docker Compose installed, make sure the Docker daemon is listening on TCP port 2375
2. Use the following `docker-compose.yml` and `config.toml` to start a new Dynamic Grid: https://gist.github.com/Davipb/4941e60d28ec5abf3b399aad9da6d370
   * Paths might need to be tweaked, they assume all files are on `/selenium/`
3. Try to start a new session with `curl --request POST --header 'Content-Type: application/json;charset=utf-8' --data '{"desiredCapabilities":{"browserName":"firefox"}}' localhost:4444/wd/hub/session`
3. Note how the new session request hangs forever or times out. 
   * If you check the logs with `docker-compose logs`, you'll see the docker node is stuck waiting for the newly created Firefox container to start, despite it already having started
   * You can confirm the Firefox container started correctly by grabbing its assigned port with `docker container ls` then running `curl localhost:XXXX/wd/hub/status` (where `XXXX` is the port). It should return `"ready": true`.

## Expected behavior

A session should be created using the newly-spawned Firefox container and returned to the user.

## Test script reproducing this issue (when applicable)
For a clean Ubuntu Server 20.04.1 LTS VM (run as root): https://gist.github.com/Davipb/4799a2c76d91e5d16249ee0a5353d06a

For an existing system with Docker and Docker compose already installed:  
Download these files https://gist.github.com/Davipb/4941e60d28ec5abf3b399aad9da6d370 (Paths might need to be tweaked, they assume all files are on `/selenium/`) then run
```bash
docker-compose up -d
curl --request POST --header 'Content-Type: application/json;charset=utf-8' --data '{"desiredCapabilities":{"browserName":"firefox"}}' localhost:4444/wd/hub/session
```

## Environment

OS: Ubuntu Server 20.04.1 LTS
Docker-Selenium image version: `4.0.0-alpha-7-20201119`
`selenium/hub` image ID: `bbb6c93776f9`
`selenium/node-docker` image ID: `47572806ad04`
`selenium/standalone-firefox` image ID: `8cb05ddc50eb`
Docker version: 19.03.13, build 4484c46d9d
Docker-Compose version (if applicable): 1.27.4, build 40524192
Exact Docker command to start the containers: `docker-compose up -d` using these files: https://gist.github.com/Davipb/4941e60d28ec5abf3b399aad9da6d370

**Comment by diemol** [comment]
@Davipb, does it work if you do **not** use docker-compose?

**Comment by Davipb** [comment]
> @Davipb, does it work if you do **not** use docker-compose?

@diemol No, the same thing happens: `node-docker` hangs waiting for the (already started) container to start. I also tried using the latest prelease image versions (`4.0.0-beta-1-prerelease-20201130`), but it still hangs, both with and without docker-compose.

Here's the full script I used to start the grid without `docker-compose` (clean VM, run as root): https://gist.github.com/Davipb/b9321de6fc96d015da14e5be30de6c31

Here are the relevant commands:
```bash
docker network create selenium

docker run --rm -d \
    --net selenium \
    --name selenium-hub \
    -p 4442-4444:4442-4444 \
    selenium/hub:4.0.0-alpha-7-20201119

docker run --rm -d \
    --net selenium \
    --name node-docker \
    -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /selenium/config.toml:/opt/bin/config.toml \
    -v /selenium/assets:/opt/selenium/assets \
    selenium/node-docker:4.0.0-alpha-7-20201119

curl --request POST --header 'Content-Type: application/json;charset=utf-8' --data '{"desiredCapabilities":{"browserName":"firefox"}}' localhost:4444/wd/hub/session
```

**Comment by Davipb** [comment]
After experimenting a bit with VM settings, I think this might be a multi-threading issue, not an OS issue. Locally with Hyper-V on Windows 10 Pro, `node-docker` hangs when using a VM with 1 or 2 CPU cores, but works normally when using 3 or more CPU cores. On the cloud with Azure VMs, I had to go up to 8 vCPUs before `node-docker` stopped hanging.

**Comment by diemol** [comment]
Could you please share the logs?

**Comment by Davipb** [comment]
Here you go: https://gist.github.com/Davipb/07e6b6ef97878679301850b5d0315fc0

`failure.log`  is from a local Hyper-V machine with 1 CPU core, `success.log` is from a local Hyper-V machine with 4 CPU cores.

**Comment by mr-romeijn** [comment]
Having similar issues on EC2 ubuntu 18.04 machine. standalone-docker hangs on `Waiting for server to start`

**Comment by nickyromeijn** [comment]
Updating to the latest version of docker seems to resolve the issue. `Docker version 20.10.3, build 48d30b5`

**Comment by diemol** [comment]
The main issue was that Dynamic Grid was not working at all in `docker-compose` or when a custom network was being used. I've fixed this through https://github.com/SeleniumHQ/selenium/commit/909239cd9fe4a51f37347f048bd9cbc6be627010, and we'll do a prerelease soon so you can all try again.

**Comment by diemol** [comment]
Released https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-3-prerelease-20210321

I'll close this, if there are any new problems, please open a new issue.

**Comment by josesa-xx** [comment]
I've tested this release in my docker-compose tests and looks ok.

**Comment by diemol** [comment]
Thanks for letting us know, @josesa-xx!
