### ISSUE TITLE
Lack of self-certified certificates means FF/Chrome can hang/timeout with Selenium

### ISSUE THREAD

**Issue by alexellis** [SeleniumHQ/docker-selenium#115]
Some of the intranet sites I want to automate have their own self-certified certificates. I am finding that when connecting to Selenium hub/node on my Windows PC this is not an issue but on the NodeChrome or NodeFireFox containers I am getting a timeout ( which I think is due to the (invalid/insecure) certificate not being accepted )

Is there a recommended way of pushing our .cer down to the node container?

**Comment by apakhomov** [comment]
For Chrome use certutil from libnss3-tools to prepare db with cacerts:

certutil -d sql:~/.pki/nssdb -A -t TC -n "name_is_here" -i /path_to_cert.crt

After that mount nssdb as a volume into container

**Comment by jatinkapoor** [comment]
@apakhomov, @alexellis  Hi, I am facing a similar problem , I am creating an image by basing my image on chrome node debug, and I am creating a nssdb with my application certs in the image itself.
 When i am opening the application manually on the chrome node via vnc viewer its working fine and certs are available in the chrome certificate authority but those certs are not available when I am running the browser through webdriver. I am not sure what am I doing wrong here. 

I will appreciate any suggestions. Thanks 
---------
FROM selenium/node-chrome-debug:2.53.1

USER ROOT

RUN apt-get update -qqy \
  && apt-get -qqy install \
    curl
RUN apt-get update -qqy \
  && apt-get -qqy install \
    libnss3-tools

RUN curl -k https://xxxxxxxxxx/cacerts/cacerts/1.8/cacerts-1.8.jar -o /tmp/cacerts && mv /tmp/cacerts  /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security

RUN curl http://xxxxxxxxxxRoot.crt -o xxxxxx.pem \
 && curl http://xxxxxxxx%20CA01.crt -o xxxxxxx.pem \
 RUN mkdir -p $HOME/.pki/nssdb
 RUN certutil -d sql:$HOME/.pki/nssdb -N --empty-password
 RUN certutil -d sql:$HOME/.pki/nssdb -A -t "TC,C,T" -n xxxxx.pem -i xxxxxx.pem 
//For debugging
RUN certutil -d sql:$HOME/.pki/nssdb -L

**Comment by diemol** [comment]
Closing this since #518 addresses this same issue and it is solved. Please have a look to that one.
