### ISSUE TITLE
Duplicate code causes the node to fail to start when I am using environment variable SE_NODE_HOST or SE_NODE_PORT

### ISSUE THREAD

**Issue by zhq5101** [SeleniumHQ/docker-selenium#1154]
## 🐛 Bug Report

When I am using environment variable SE_NODE_HOST or SE_NODE_PORT, the node can not start. The main log is this:
cat /opt/selenium/config.toml
[node]
max-concurrent-sessions = 1
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[server]
[server]
hostname = "selenium-node"
port = "5555"

There are two '[server]'s. And the reason is some duplicate code in this file:
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeChrome/generate_config
The line 13-17 is same as the line 19-23.

**Comment by diemol** [comment]
Thank you for reporting this, @zhq5101!
We will have a look soon.

**Comment by diemol** [comment]
Fixed in the linked PR, a release will follow soon.
