### ISSUE TITLE
Selenium docker image used old version of jQuery EOM

### ISSUE THREAD

**Issue by gritsevski** [SeleniumHQ/docker-selenium#1165]
## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
@gritsevski, which Docker image? Which tag?

**Comment by gritsevski** [comment]
@diemol 
https://hub.docker.com/r/selenium/node-chrome 
selenium/node-chrome:4.0.0-beta-1-prerelease-20201208

**Comment by diemol** [comment]
I should have asked for more details :)

What is the version of jQuery you found? How did you find it? We are not using jQuery in Grid 4.

**Comment by gritsevski** [comment]
@diemol 
The vulnerability was reported during security monitoring. And was a surprise for me too :)

**Comment by diemol** [comment]
> What is the version of jQuery you found? How did you find it?

**Comment by gritsevski** [comment]
@diemol According to the self-reported version in the script, the version of JQuery hosted on the remote web server is greater than or equal to 1.2 and prior to 3.5.0. It is, therefore, affected by a cross-site scripting vulnerability.

**Comment by diemol** [comment]
Sorry, we need a bit more detail, probably the file or the URL where jQuery is getting loaded. We are blind-sighted without that.

**Comment by gritsevski** [comment]
@diemol Thanks for the support. Will return back with more information

**Comment by gritsevski** [comment]
@diemol The problematic file is : 4444/asserts/    in https://hub.docker.com/r/selenium/standalone-chrome-debug  
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.59"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>

**Comment by diemol** [comment]
I see you are using the `chrome-node-debug` image, therefore you are using Grid 3 and not Grid 4.

Grid 3 used jQuery but Grid 3 is not under development anymore, and we do not port back fixes to released versions.

We'd recommend to use the images for Grid 4, even if they are on alpha state, they are working well and no jQuery is used.
