### ISSUE TITLE
docker-compose v3 /wd/hub status:13

### ISSUE THREAD

**Issue by renanpaiva64** [SeleniumHQ/docker-selenium#1166]
## 🐛 Bug Report

Running the docker-compose v3 file the selenium doesn't work.

## To Reproduce

Execute docker-compose up on Windows 10.

## Expected behavior

Get the selenium hub working and available to run tests

## Test script reproducing this issue (when applicable)

Selenium wasn't able to run scripts

## Environment

OS: Windows 10 Enterprise Version 2004
Docker-Selenium image version: latest ID: 6328dcc4b7db

docker version: v20.10.0
docker-compose version 1.27.4, build 40524192
WSL Ubuntu 20.04 LTS

Start Command: docker-compose -f docker-compose.yml up

Docker-compose file:
\#To execute this docker-compose yml file use docker-compose -f docker-compose-v3.yml up
\#Add the -d flag at the end for detached execution
\#To stop the execution, hit Ctrl+C, and then docker-compose -f docker-compose-v3.yml down
version: "3"
services:
chrome:
image: selenium/node-chrome
volumes:
- /dev/shm:/dev/shm
depends_on:
- selenium-hub
environment:
- SE_EVENT_BUS_HOST=selenium-hub
- SE_EVENT_BUS_PUBLISH_PORT=4442
- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
ports:
- "6900:5900"

firefox:
image: selenium/node-firefox
volumes:
- /dev/shm:/dev/shm
depends_on:
- selenium-hub
environment:
- SE_EVENT_BUS_HOST=selenium-hub
- SE_EVENT_BUS_PUBLISH_PORT=4442
- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
ports:
- "6901:5900"

opera:
image: selenium/node-opera
volumes:
- /dev/shm:/dev/shm
depends_on:
- selenium-hub
environment:
- SE_EVENT_BUS_HOST=selenium-hub
- SE_EVENT_BUS_PUBLISH_PORT=4442
- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
ports:
- "6902:5900"

selenium-hub:
image: selenium/hub
container_name: selenium-hub
ports:
- "4442:4442"
- "4443:4443"
- "4444:4444"

**Comment by diemol** [comment]
@renanpaiva64, what does not work? I see most of the template has been deleted, could you please add the missing details? Also, please add the logs when running `docker-compose`.

**Comment by renanpaiva64** [comment]
Sorry, I've tried to be right to the point. Details added.

docker-compose log:
Starting selenium-hub ... done
Starting selenium_opera_1   ... done
Starting selenium_firefox_1 ... done
Starting selenium_chrome_1  ... done
Attaching to selenium-hub, selenium_firefox_1, selenium_chrome_1, selenium_opera_1
selenium-hub    | 2020-12-18 16:52:41,493 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium-hub    | 2020-12-18 16:52:41,495 INFO supervisord started with pid 10
selenium-hub    | 2020-12-18 16:52:42,496 INFO spawned: 'selenium-hub' with pid 13
selenium-hub    | Starting Selenium Hub with configuration:
selenium-hub    | 2020-12-18 16:52:42,508 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | {
selenium-hub    |   "host": "0.0.0.0",
selenium-hub    |   "port": 4444,
selenium-hub    |   "role": "hub",
selenium-hub    |   "maxSession": 5,
selenium-hub    |   "newSessionWaitTimeout": -1,
selenium-hub    |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub    |   "throwOnCapabilityNotPresent": true,
selenium-hub    |   "jettyMaxThreads": -1,
selenium-hub    |   "cleanUpCycle": 5000,
selenium-hub    |   "browserTimeout": 0,
selenium-hub    |   "timeout": 1800,
selenium-hub    |   "debug": false
selenium-hub    | }
selenium-hub    | 16:52:42.753 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1        | 2020-12-18 16:52:42,082 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1        | 2020-12-18 16:52:42,084 INFO supervisord started with pid 9
firefox_1       | 2020-12-18 16:52:41,959 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
firefox_1       | 2020-12-18 16:52:41,964 INFO supervisord started with pid 9
selenium-hub    | 16:52:42.867 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
opera_1         | 2020-12-18 16:52:42,929 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
opera_1         | 2020-12-18 16:52:42,930 INFO supervisord started with pid 8
firefox_1       | 2020-12-18 16:52:42,966 INFO spawned: 'xvfb' with pid 12
firefox_1       | 2020-12-18 16:52:42,967 INFO spawned: 'selenium-node' with pid 13
firefox_1       | E: [pulseaudio] main.c: Daemon startup failed.
firefox_1       | 2020-12-18 16:52:43,010 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1       | 2020-12-18 16:52:43,010 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1       | No PulseAudio daemon running, or not running as session daemon.
firefox_1       | No PulseAudio daemon running, or not running as session daemon.
firefox_1       | No PulseAudio daemon running, or not running as session daemon.
firefox_1       | Not linked with a running Hub container
firefox_1       | 2020-12-18 16:52:43,020 INFO exited: selenium-node (exit status 1; not expected)
chrome_1        | 2020-12-18 16:52:43,086 INFO spawned: 'xvfb' with pid 12
chrome_1        | 2020-12-18 16:52:43,087 INFO spawned: 'selenium-node' with pid 13
chrome_1        | E: [pulseaudio] main.c: Daemon startup failed.
chrome_1        | 2020-12-18 16:52:43,147 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2020-12-18 16:52:43,147 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | No PulseAudio daemon running, or not running as session daemon.
chrome_1        | No PulseAudio daemon running, or not running as session daemon.
chrome_1        | No PulseAudio daemon running, or not running as session daemon.
chrome_1        | Not linked with a running Hub container
chrome_1        | 2020-12-18 16:52:43,160 INFO exited: selenium-node (exit status 1; not expected)
selenium-hub    | 2020-12-18 16:52:43.229:INFO::main: Logging initialized @715ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub    | 16:52:43.376 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub    | 16:52:43.378 INFO [Hub.start] - Nodes should register to http://172.19.0.2:4444/grid/register/
selenium-hub    | 16:52:43.378 INFO [Hub.start] - Clients should connect to http://172.19.0.2:4444/wd/hub
opera_1         | 2020-12-18 16:52:43,932 INFO spawned: 'xvfb' with pid 11
opera_1         | 2020-12-18 16:52:43,933 INFO spawned: 'selenium-node' with pid 12
opera_1         | Not linked with a running Hub container
opera_1         | 2020-12-18 16:52:44,311 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opera_1         | 2020-12-18 16:52:44,311 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opera_1         | 2020-12-18 16:52:44,311 INFO exited: selenium-node (exit status 1; not expected)

/wd/hub payload:
{
  "sessionId": null,
  "status": 13,
  "value": {
    "class": "java.lang.NullPointerException",
    "error": "unknown error",
    "message": null,
    "stackTrace": [
      {
        "className": "org.openqa.grid.internal.ExternalSessionKey",
        "fileName": "ExternalSessionKey.java",
        "lineNumber": 79,
        "methodName": "fromWebDriverRequest"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.WebDriverRequest",
        "fileName": "WebDriverRequest.java",
        "lineNumber": 58,
        "methodName": "extractSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 240,
        "methodName": "getSession"
      },
      {
        "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
        "fileName": "RequestHandler.java",
        "lineNumber": 123,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 85,
        "methodName": "process"
      },
      {
        "className": "org.openqa.grid.web.servlet.DriverServlet",
        "fileName": "DriverServlet.java",
        "lineNumber": 63,
        "methodName": "doGet"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 687,
        "methodName": "service"
      },
      {
        "className": "javax.servlet.http.HttpServlet",
        "fileName": "HttpServlet.java",
        "lineNumber": 790,
        "methodName": "service"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHolder",
        "fileName": "ServletHolder.java",
        "lineNumber": 865,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 535,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 146,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.security.SecurityHandler",
        "fileName": "SecurityHandler.java",
        "lineNumber": 548,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 257,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1595,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 255,
        "methodName": "nextHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1340,
        "methodName": "doHandle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 203,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
        "fileName": "ServletHandler.java",
        "lineNumber": 473,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
        "fileName": "SessionHandler.java",
        "lineNumber": 1564,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 201,
        "methodName": "nextScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
        "fileName": "ContextHandler.java",
        "lineNumber": 1242,
        "methodName": "doScope"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
        "fileName": "ScopedHandler.java",
        "lineNumber": 144,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
        "fileName": "HandlerWrapper.java",
        "lineNumber": 132,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.Server",
        "fileName": "Server.java",
        "lineNumber": 503,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpChannel",
        "fileName": "HttpChannel.java",
        "lineNumber": 364,
        "methodName": "handle"
      },
      {
        "className": "org.seleniumhq.jetty9.server.HttpConnection",
        "fileName": "HttpConnection.java",
        "lineNumber": 260,
        "methodName": "onFillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
        "fileName": "AbstractConnection.java",
        "lineNumber": 305,
        "methodName": "succeeded"
      },
      {
        "className": "org.seleniumhq.jetty9.io.FillInterest",
        "fileName": "FillInterest.java",
        "lineNumber": 103,
        "methodName": "fillable"
      },
      {
        "className": "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
        "fileName": "ChannelEndPoint.java",
        "lineNumber": 118,
        "methodName": "run"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 333,
        "methodName": "runTask"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 310,
        "methodName": "doProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 168,
        "methodName": "tryProduce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill",
        "fileName": "EatWhatYouKill.java",
        "lineNumber": 132,
        "methodName": "produce"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 765,
        "methodName": "runJob"
      },
      {
        "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
        "fileName": "QueuedThreadPool.java",
        "lineNumber": 683,
        "methodName": "run"
      },
      {
        "className": "java.lang.Thread",
        "fileName": "Thread.java",
        "lineNumber": 748,
        "methodName": "run"
      }
    ],
    "stacktrace": "java.lang.NullPointerException\n\tat org.openqa.grid.internal.ExternalSessionKey.fromWebDriverRequest(ExternalSessionKey.java:79)\n\tat org.openqa.grid.web.servlet.handler.WebDriverRequest.extractSession(WebDriverRequest.java:58)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)\n\tat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)\n\tat org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)\n\tat org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:63)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\tat org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)\n\tat org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.seleniumhq.jetty9.server.Server.handle(Server.java:503)\n\tat org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)\n\tat org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)\n\tat org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)\n\tat org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)\n\tat java.lang.Thread.run(Thread.java:748)\n"
  }
}

wd/hub/status payload:
{
  "status": 0,
  "value": {
    "ready": false,
    "message": "No spare hub capacity",
    "build": {
      "revision": "e82be7d358",
      "time": "2018-11-14T08:25:53",
      "version": "3.141.59"
    },
    "os": {
      "arch": "amd64",
      "name": "Linux",
      "version": "4.19.128-microsoft-standard"
    },
    "java": {
      "version": "1.8.0_275"
    }
  }
}

**Comment by diemol** [comment]
Ah ok, I see the problem, the docker compose file is meant to be used with the Selenium Grid 4 images.  The example uses the current tag, which is `4.0.0-beta-1-prerelease-20201208`. 

If you use the tag, it will work. 

Currently, `latest` is still pointing to the Selenium Grid 3 images.
