### ISSUE TITLE
chrome standalone: when trying to maximize the window, no such session error is thrown

### ISSUE THREAD

**Issue by bitliner** [SeleniumHQ/docker-selenium#117]
I am running protractor test against chrome standalone webdriver docker container.

Every time it tries to maximize the browser window programmatically, it throws an error saying `no such session`.

What am I doing wrong?

**Comment by apakhomov** [comment]
Node logs please.

**Comment by Vanuan** [comment]
Could it be related to small `dev/shm`? https://code.google.com/p/chromium/issues/detail?id=522853

**Comment by diemol** [comment]
@bitliner is this still an issue for you? If so, can you please provide some log output, environment used, and docker images used?

If not, please close the issue.

Thanks!

**Comment by ddavison** [comment]
no response for a week, closing.
