### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by saramorsi** [SeleniumHQ/docker-selenium#1178]
## 🐛 Bug Report

Hello, I am getting this error recently when running my snapshot tests using this docker image "selenium/standable-chrome-debug" : 

```
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=85.0.4183.83)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'NYC-205503-C02ZR0AYLVDN', ip: 'fe80:0:0:0:e1:d1a5:e4b2:79e1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '11.0.8'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.83, chrome: {chromedriverVersion: 85.0.4183.83 (94abc2237ae0c..., userDataDir: /tmp/.com.google.Chrome.fjsAuF}, goog:chromeOptions: {debuggerAddress: localhost:39153}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: f24ea139d06d1bebba4fa67c710...}
Session ID: f24ea139d06d1bebba4fa67c71088e63
```
and this error: 

```
org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'NYC-205503-C02ZR0AYLVDN', ip: 'fe80:0:0:0:e1:d1a5:e4b2:79e1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '11.0.8'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.83, chrome: {chromedriverVersion: 85.0.4183.83 (94abc2237ae0c..., userDataDir: /tmp/.com.google.Chrome.fjsAuF}, goog:chromeOptions: {debuggerAddress: localhost:39153}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: f24ea139d06d1bebba4fa67c710...}
Session ID: f24ea139d06d1bebba4fa67c71088e63
```

I'm not entirely sure why this is occuring. I am using the latest version of the image and even tried to using some of the older versions of the image but I am getting the same issue. Previously it was working fine. This only started to happen recently. 

I'm wondering if there's a way to update the chrome and chrome driver version of this image since it appears to be old? Also, I have tried to use chrome options such as "--no-sandbox", "--disable-dev-shm-usage",  "--disable-gpu", and 
 "--headless" but they have not helped with this issue. Any further insights on fixing this issue would be welcome. Thank you! 

## Environment

OS: OSX 
Docker-Selenium image version: 3.141, 3.141.59-20200826
Also provide the docker image id : 53c1502c9d64, bd61f796694a

Docker version 20.10.2, build 2291f61
Docker-Compose version (if applicable): docker-compose version 1.27.4, build 40524192

**Comment by diemol** [comment]
@saramorsi, sorry, there is not enough information to see if this is a bug or just a question, many parts of the template were deleted (such as "how to reproduce the issue").

Could you please add the missing information? (How to reproduce, test and container logs)

**Comment by saramorsi** [comment]
> @saramorsi, sorry, there is not enough information to see if this is a bug or just a question, many parts of the template were deleted (such as "how to reproduce the issue").
> 
> Could you please add the missing information? (How to reproduce, test and container logs)

This is a possible bug I believe. I don't have any reproduceable steps to share other than starting the docker container (docker-compose up) and running our snapshot tests fail. Is there something else I can share? Otherwise, I can just close the issue then.

**Comment by diemol** [comment]
Closing as we are doing the troubleshooting in Slack.
