### ISSUE TITLE
Click not working with grid for onclick events

### ISSUE THREAD

**Issue by buckmaxwell** [SeleniumHQ/docker-selenium#1180]
## 🐛 Bug Report

I am using I docker compose file that looks very similar to https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3#version-3. I am running a simple test that finds an element on the page and clicks it. The click should execute an onclick function that loads a page on a different domain.

I have verified that connecting with a direct web driver, ie

```python
driver = webdriver.Firefox()
# or
driver = webdriver.Chrome()
```

works fine -- el.click() works as expected. however, when I attempt to connect using

```python
 driver = webdriver.Remote(
            command_executor="http://localhost:4444/wd/hub",
            desired_capabilities=DesiredCapabilities.CHROME,
        )
```

el.click() seems to select the button (screenshot verifies) but the page does not change. waiting does not change this result.

If the button is changed to something simpler (ie `<button type='button' onclick="location.href='http://www.example.com'" type="button">`) it can be verified that the click() exhibits expected behavior with either driver type.

Though this lead me to believe that the issue was related to javascript execution I have also verified that switching to javascript executor instead of a direct click does not change the result.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: MacOS Big Sur
Docker-Selenium image version: 3.141
Docker version: 3.0.4
Docker-Compose version 3:
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3#version-3

**Comment by diemol** [comment]
Do you have a public website or a simple html page where I can verify this?

**Comment by diemol** [comment]
Closing as we did not get more information, if you need more help or have any questions, feel free to drop by our Slack/IRC channel, see the links here https://www.selenium.dev/support/
