### ISSUE TITLE
Selenium 4 [docker] - Can't change maxSession parameter from default of 1

### ISSUE THREAD

**Issue by cttsg** [SeleniumHQ/docker-selenium#1182]
## 🐛 Bug Report

Passing an integer greater than 1 to the SE_NODE_MAX_CONCURRENT_SESSIONS environment variable for both the hub and the node chrome has no effect as when we spin up the grid, the default of 1 maxSession kicks in.

## To Reproduce

Steps to reproduce the behaviour (including the command to start the containers):

Set env SE_NODE_MAX_CONCURRENT_SESSIONS 3 in task definition file for hub. Also, set the same environment variable for the node-chrome docker image. Same results

## Expected behaviour

Multiple concurrent session to enable parallelisation when testing.

## Test script reproducing this issue (when applicable)
See ECS task definitions:
<img width="781" alt="Screenshot 2021-01-19 at 14 15 44" src="https://user-images.githubusercontent.com/77153789/105061449-6c513e00-5a71-11eb-8e28-4bf667fd98d7.png">

https://gist.github.com/cttsg/c1ee7a7ca5335326d55dbfdc48fd59b3

## Environment

OS: Linux
Docker-Selenium image version: 4.0.0-beta-1-prerelease-20210114
Docker version: 19.03.13-ce, build 4484c46
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): Started as part of an ECS cluster task defnition

**Comment by cttsg** [comment]
Hi Diemol,

Is there any update on this issue?

**Comment by diemol** [comment]
I have not had the time, but if I see the raw Docker logs, it'd be helpful.

**Comment by cttsg** [comment]
Hi Diemol,

Thanks for getting back to us. Here is a copy of the docker logs - we have SE_NODE_MAX_CONCURRENT_SESSIONS 3 and passing a -Dserenity.fork.count=2. The logs are in the gist here: https://gist.github.com/cttsg/8ba7df98290bd7ef9c030403c8efb259

**Comment by diemol** [comment]
Thanks for reporting this, @cttsg!

This was an issue with the UI, we have improved that, and this is how it looks now when you set the env var to `3`. Please use this prerelease: https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20210201

![image](https://user-images.githubusercontent.com/5992658/106475997-da9cf400-64a6-11eb-94df-4522bd26131f.png)

**Comment by cttsg** [comment]
Hi @diemol, thank you for looking into this. We tried passing in 3 into the env var but it still defaults back to 1. Can you confirm that the env var you are using is **SE_NODE_MAX_CONCURRENT_SESSIONS** or are we to use a different env var?

Many Thanks

**Comment by diemol** [comment]
Where do you see that it defaults back to 1? How many CPUs are available for Docker? There cannot be more "max sessions" than CPUs available.

**Comment by cttsg** [comment]
In our ECS task definition for the Hub, we pass 3 to the parameter SE_NODE_MAX_CONCURRENT_SESSIONS. However, when we use the latest Docker image "4.0.0-beta-1-prerelease-20210201", and set the sessions var, it shoe 0/1 sessions. 

We are using AWS instance type: t3.large which has 2 vCPUs. We will try using a maxSessions of 2 and see if that might be the issue.

**Comment by diemol** [comment]
You could try to run it locally with a docker-compose file, and then check that it works. With that, you can isolate where the issue is happening.
