### ISSUE TITLE
Selenium Grid becomes unresponsive after some time

### ISSUE THREAD

**Issue by ksnehi** [SeleniumHQ/docker-selenium#1183]
## 🐛 Bug Report

Selenium Grid 4 is spun up on AWS ECS (Fargate) by adopting and customising the available docker-compose script however, it throws a strange error after booting up and then becomes unresponsive after some time.

## To Reproduce

Deploy selenium 4 on AWS ECS using Fargate, (2 vcpu, 4096 MB RAM), after 5 minutes or so, below error is thrown and then selenium becomes unresponsive

INFO [LocalDistributor.add] - Added node 69ef5b07-2c49-4891-bfbd-273929a0de81 at http://10.51.132.102:5555.
INFO [GridModel.setAvailability] - Switching node 69ef5b07-2c49-4891-bfbd-273929a0de81 (uri: http://10.51.132.102:5555) from DOWN to UP
 **ERROR [HashedWheelTimer.reportTooManyInstances] - You are creating too many HashedWheelTimer instances. HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.**

## Expected behavior

Should run as smooth as running with docker-compose on local setup

## Test script reproducing this issue (when applicable)

ECS Terraform task definition of Selenium Hub - 

```
resource "aws_ecs_task_definition" "seleniumhub" {
  family                = "seleniumhub"
  network_mode = "awsvpc"
  container_definitions = <<DEFINITION
[
    {
         "name": "hub", 
         "image": "selenium/hub:4.0.0-beta-1-prerelease-20210114", 
         "portMappings": [
             {
             "hostPort": 4444,
             "protocol": "tcp",
             "containerPort": 4444
             },
             {
                "hostPort": 4442,
                "protocol": "tcp",
                "containerPort": 4442
            },
            {
                "hostPort": 4443,
                "protocol": "tcp",
                "containerPort": 4443
            }
         ], 
         "essential": true, 
         "entryPoint": [], 
         "command": [],
         "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-create-group":"true",
                "awslogs-group": "awslogs-selenium",
                "awslogs-region": "eu-central-1",
                "awslogs-stream-prefix": "selenium-hub"
            }
         
         }
    }
 ]
DEFINITION
  requires_compatibilities = ["FARGATE"]
  cpu = 2048
  memory = 4096
  execution_role_arn = aws_iam_role.ecsTaskExecutionRole.arn

}
```

## Environment

OS: AWS ECS
Docker-Selenium image version: selenium/hub:4.0.0-beta-1-prerelease-20210114
Also provide the docker image id 
-->
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Could you please attach the complete logs? Do you run any tests to get that error?

**Comment by ksnehi** [comment]
No, haven't run any tests yet. It starts and throws the error within 5 minutes, then becomes unresponsive to the state that it gets stuck at fetching status of running nodes on http://localhost:4444/ui/index.html#/ .

Here are the full logs right from startup--

```
> 2021-01-19 21:04:44,635 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
> 2021-01-19 21:04:44,637 INFO supervisord started with pid 7
> 2021-01-19 21:04:45,639 INFO spawned: 'selenium-grid-hub' with pid 9
> 21:04:45.964 INFO [LogManager$RootLogger.log] - Using the system default encoding
> 2021-01-19 21:04:45,965 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 21:04:45.967 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
> 21:04:46.046 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.51.148.21:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.51.148.21:4443]
> 21:04:46.117 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.51.148.21:4442 and tcp://10.51.148.21:4443
> 21:04:46.141 INFO [UnboundZmqEventBus.<init>] - Sockets created
> 21:04:46.158 INFO [UnboundZmqEventBus.lambda$new$7] - Bus started
> 21:04:46.357 INFO [BoundZmqEventBus.<init>] - Event bus ready
> 21:04:46.906 INFO [Hub.execute] - Started Selenium hub 4.0.0-beta-1 (revision 02d5e641d5): http://10.51.148.21:4444
> 21:04:54.247 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
> 21:04:54.489 INFO [LocalDistributor.add] - Added node ee1b54fa-a8cd-4422-bf5a-c1789aa70c23 at http://10.51.140.236:5555.
> 21:04:54.821 INFO [GridModel.setAvailability] - Switching node ee1b54fa-a8cd-4422-bf5a-c1789aa70c23 (uri: http://10.51.140.236:5555) from DOWN to UP
> 21:04:54.846 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
> 21:04:54.851 INFO [LocalDistributor.add] - Added node 69ef5b07-2c49-4891-bfbd-273929a0de81 at http://10.51.132.102:5555.
> 21:04:55.031 INFO [GridModel.setAvailability] - Switching node 69ef5b07-2c49-4891-bfbd-273929a0de81 (uri: http://10.51.132.102:5555) from DOWN to UP
> 21:09:59.733 ERROR [HashedWheelTimer.reportTooManyInstances] - You are creating too many HashedWheelTimer instances. HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.
```

**Comment by mcopjan** [comment]
I have experienced this error when executing high volume of tests
https://github.com/SeleniumHQ/selenium/issues/9112

**Comment by remorhaz** [comment]
We've experienced a similar problem today. In our case tests sessions were not creating at all (with the same `HashedWheelTimer.reportTooManyInstances` error) because of `selenium/session-queuer` not responding. Restarting it solved the problem; maybe this information will help somehow to fix the error.

**Comment by dylanlive** [comment]
I've been able to replicate this **outside** of docker. See my comment here:
https://github.com/SeleniumHQ/selenium/issues/9112#issuecomment-774291278

**Comment by diemol** [comment]
Thanks for the hint on the `session-queuer`, @remorhaz! 

Closing this one in favour of https://github.com/SeleniumHQ/selenium/issues/9112
