### ISSUE TITLE
Wrong image listed on the Debug section of the readme ?

### ISSUE THREAD

**Issue by williamdes** [SeleniumHQ/docker-selenium#1185]
https://github.com/SeleniumHQ/docker-selenium#debugging

```
$ docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210114
$ docker run -d -p 4445:4444 -p 5901:5900 -v /dev/shm:/dev/shm selenium/standalone-firefox:4.0.0-beta-1-prerelease-20210114
$ docker run -d -p 4446:4444 -p 5902:5900 -v /dev/shm:/dev/shm selenium/standalone-opera:4.0.0-beta-1-prerelease-20210114
```

Should it not be `selenium/standalone-{name}-debug` instead of `selenium/standalone-{name}`.

I can confirm that before switching to `-debug` images I could not connect to the VNC server.

**Comment by williamdes** [comment]
cc @diemol 

The bot closed the issue but it is a valid one. Please re-open

**Comment by diemol** [comment]
We reply to questions on our slack or irc channels, we don't have enough people and time to reply to questions :) However we are most of the time on Slack and IRC, and we can answer there faster.

Now, to the question, for Grid 4, all browser images include VNC by default, the `-debug` ones will be only for Grid 4.

**Comment by williamdes** [comment]
Hi @diemol 
This is not a question but a bug report on your readme ..

> the -debug ones will be only for Grid 4.

Okay, thanks

**Comment by diemol** [comment]
Sorry, was a typo. The debug ones are only for Grid 3.

The readme contents are correct.
