### ISSUE TITLE
usage of Selenium/node-chrome-2.53.1

### ISSUE THREAD

**Issue by Tonicku** [SeleniumHQ/docker-selenium#1188]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working version

Worked up to version:

Stopped working in version:

## To Reproduce

deploy stack from the docker-compose

`## Timezone is set to US ET, to match datacenter timezone.
##
## [https://github.com/SeleniumHQ/docker-selenium]

version: '3.7'

services:
  hub:
    image: selenium/hub:2.53.1
    environment:
      TZ: "America/New_York"
    ports:
      - "4449:4444"
    deploy:
      placement:
        constraints:
          #- node.role == manager
          - node.labels.grid-amt == test

  chrome:
    image: selenium/node-chrome:2.53.1
    volumes:
      - /dev/shm:/dev/shm
    environment:
      TZ: "America/New_York"
      HUB_HOST: hub
      HUB_PORT: 4444
      SCREEN_HEIGHT: 900
      SCREEN_WIDTH: 1600
      SCREEN_DEPTH: 24
    deploy:
      replicas: 8
      placement:
        constraints:
          - node.labels.grid == test
      resources:
        limits:
          cpus: '1.0'
          memory: 800M
        reservations:
          cpus: '0.25'
          memory: 100M
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    extra_hosts:
`

## Expected behavior

to have hub and node with status running

## Environment

OS: Centos 7
Docker-Selenium image version: 2.53.1

**Comment by diemol** [comment]
What is the error? Can you share the logs you see when you try to run the commands?

**Comment by Tonicku** [comment]
![image](https://user-images.githubusercontent.com/69209540/105974150-e4c98780-608d-11eb-81cb-2f2f5ac7a450.png)

Node log with failure status : Not Linked with a running Hub container

**Comment by diemol** [comment]
That screenshot is not telling us so much, I don't have any of the context you have. To understand better what is going on, I need to see the raw docker logs.

**Comment by Tonicku** [comment]
i got your point.
As you can see, i am using Portainer.
for a failed deployment, there are no logs
for a prepared / started deployment, the logs is not displaying

i tried, see below the screenshot, to check logs on the container 2.53.1, and please notice i don't have any log coming up
![image](https://user-images.githubusercontent.com/69209540/105980797-961feb80-6095-11eb-8526-07d9a61a5672.png)

should i try to active the debug mode ?

**Comment by diemol** [comment]
The hub looks good, maybe there is an error on the node logs.

**Comment by Tonicku** [comment]
definitively agree hub is up... but the node never goes up. and logs is empty

**Comment by diemol** [comment]
Not sure how I can help without more information. I cannot really say this is a bug in the image, seems something related to the environment. Also, we do not support the 2.x images anymore, so even if there is a bug in the image, we won't spend time working on it because those images are over 4 years old.

If you'd like to continue the conversation and see if we can find a way to make it work, please join our Slack/IRC channels, check the links here https://www.selenium.dev/support/
