### ISSUE TITLE
Selenium node takes a long time to stop

### ISSUE THREAD

**Issue by idontusenumbers** [SeleniumHQ/docker-selenium#1189]
## 🐛 Bug Report

When issuing `docker stop <selenium node container id>` to selenium/node-chrome-debug container, container takes multiple seconds to stop.

## To Reproduce

Start then stop a selenium node container

## Expected behavior

Container ends (nearly) instantly

## Actual behavior
SIGTERM is sent to entrypoint script which initiates a graceful shutdown of supervisord which then sequentially shuts down running services:

```
Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2021-01-27 07:40:33,647 WARN received SIGTERM indicating exit request
2021-01-27 07:40:33,648 INFO waiting for xvfb, fluxbox, vnc, selenium-node to die
2021-01-27 07:40:34,650 INFO stopped: selenium-node (terminated by SIGTERM)
2021-01-27 07:40:35,652 INFO stopped: vnc (terminated by SIGTERM)
2021-01-27 07:40:35,654 INFO stopped: fluxbox (terminated by SIGTERM)
2021-01-27 07:40:36,655 INFO stopped: xvfb (terminated by SIGTERM)
```

**Comment by diemol** [comment]
That is the main purpose of `docker stop`, to stop gracefully a container, and the responsibility of the container is to handle that and shutdown every process in the same way.

If you'd like to stop the container instantly, then please use `docker kill`.

**Comment by idontusenumbers** [comment]
Of the 12 containers in my docker-compose, selenium node is 1) the most ephemeral in nature and 2) takes 3x longer to shut down than the next longest container. This includes postgres, redis, caddy server, a java application, php, etc. The `docker-compose down` just stalls when it hits selenium node.

**Comment by diemol** [comment]
@idontusenumbers, I understand what you mean. But what should we do? Killing the processes is not really the way to do. One clear difference between the docker-selenium containers and the ones you mention (redis, caddy server, etc...), is that with a browser container several processes are needed to run things properly and they need to be stopped gracefully as well, whereas in redis, only one process needs to be stopped.

On the other hand, do you have suggestions on how to improve the shudown speed while gracefully stop the containers?

**Comment by idontusenumbers** [comment]
What goes through my thought process is what difference should there be to data and clients connected to the container when STOP is issues instead of KILL.

In either case, clients connected should be expected to see their connections drop and their browser sessions terminated. Here I see three possible differences:

1. Connections for a KILLed container might never get explicitly closed and thus might hang until timeout
2. Browser sessions might not send onunload events or similar
3. Theoretically a developer has volume mapped chrome profile directories in an effort to store localstorage data and this might get corrupted with a KILL

In either case, I don't think developers hitting against selenium will be interested the 'benefits' of a STOP. More likely, they will prefer the increased speed of the KILL. It's almost exclusively used for testing, after all.

I restart my containers by doing ctrl-c on docker-compose. It immediately hangs waiting for selenium. I quickly hit ctrl-c again to start killing containers. Occasionally docker enters a strange state and I have feelings this might explain why.

**Comment by diemol** [comment]
Thank you for your feedback. I think it makes sense for the developer scenario.

However, to keep backwards compatibity, as I assume there are users relying on the current behaviour, I would add a flag that changes the termination signal sent to processes. What do you think?

As we are tight on resources, would you like to send us a PR for that, @idontusenumbers?

**Comment by diemol** [comment]
Seems you can add `--stop-signal` with your preferred signal when doing `docker run...`, so the containers will use that signal to stop all processes.

**Comment by diemol** [comment]
I will close this issue as there is no action for us to take for now. We are happy to take PRs to improve this in any case.
