### ISSUE TITLE
unable to download the files

### ISSUE THREAD

**Issue by raghavendra-centime** [SeleniumHQ/docker-selenium#1197]
## 🐛 Bug Report

using the latest docker image of selenium/standalone-chrome

it's unable to download the files. 

earlier it was working and the downloaded files used to be available in /home/seluser/Downloads directory of the container.

**Comment by diemol** [comment]
How can we reproduce the issue? Most of the issue template fields were deleted 😢 

Can you please provide all the information required, including scripts that help to reproduce the issue?

**Comment by raghavendra-centime** [comment]
Hey diemol,

here are the details:

java code to reproduce this:

```java
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.LocalFileDetector;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;

public class Test {

    private static final String DRIVER_VERSION="88.0.4324.96";
    private static final String CHROME_CONTAINER_URL="http://localhost:4444/wd/hub"; // mac -> docker container, docker port mapping, class mediator
    private static final String DOMAIN_URL="https://maven.apache.org/download.cgi";

    private static RemoteWebDriver getRemoteWebDriver() {
        ChromeOptions options = new ChromeOptions();
        options.setHeadless(true);
        URL url=null;
        try {
            url= new URL(CHROME_CONTAINER_URL);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RemoteWebDriver driver = new RemoteWebDriver(url, options);
        driver.setFileDetector(new LocalFileDetector());
        return driver;
    }

    public static void main(String[] args) {
        WebDriver driver = getRemoteWebDriver();
        driver.get(DOMAIN_URL);
        driver.findElement(By.xpath("//*[@id=\"bodyColumn\"]/section/section[2]/table/tbody/tr[2]/td[2]/a")).click();
    }

}
```

Docker image used:
docker pull selenium/standalone-chrome

docker run -d -p 4444:4444 selenium-image

Expected Results:
should have the apache-maven-3.6.3-bin.zip file downloaded into containers /home/seluser/Downloads directroy

Actual Results:
unable to locate the file in the container's file system. tried find / filename [could not find the file]


Please do let me know if more details are required.

**Comment by diemol** [comment]
I am not sure why the download does not work when Chrome runs headless. If this was working before and it stopped working, it is most likely an issue in ChromeDriver. Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

On the other hand, there is no need to run Chrome headless in a docker container, it is already running "headlessly" by being containerized.
