### ISSUE TITLE
Node Chrome Debug missing 2.48.2 tag

### ISSUE THREAD

**Issue by pthorson** [SeleniumHQ/docker-selenium#120]
Looks like it was just an oversight, but Node Chrome Debug 2.48.2 tag is missing.

https://hub.docker.com/r/selenium/node-chrome-debug/tags/

Hub and Firefox seem to be OK.

**Comment by mathieu-pousse** [comment]
this one has been fixed with the last continuous integration run

@rubytester i think you can close this one
