### ISSUE TITLE
Can't use custom firefox profile or setting preferences

### ISSUE THREAD

**Issue by laoneo** [SeleniumHQ/docker-selenium#1211]
## 🐛 Bug Report

I'm trying to set a custom download directory in firefox, either with a custom profile or with a pref. But nothing works. The profile argument when firefox is launched is always a random dir. Basically my 'moz:firefoxOptions' are completely ignored so first I thought the problem is on the PHP side, but then the docker log revealed that the capabilities do arrive in selenium. So not sure if it is still a config issue or not. I tried to set the props according to the following sources:

- https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions
- https://github.com/SeleniumHQ/docker-selenium/wiki/How-to-use-a-Firefox-custom-profile

I think the log is probably the easiest way to see if the bug is on my side or on the selenium side. Here is the log:
```
06:23:18.603 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "goog:chromeOptions": {
    "prefs": {
      "download.default_directory": "\u002ftmp\u002ftests"
    }
  },
  "moz:firefoxOptions": {
    "prefs": {
      "browser.download.dir": "\u002ftmp\u002ftests"
    },
    "log": {
      "level": "trace"
    },
    "profile": "\u002fusr\u002fsrc\u002fProjects\u002fDPDocker\u002ftests\u002fconfig\u002fff_profile"
  },
  "unexpectedAlertBehaviour": "accept",
  "unhandledPromptBehavior": "accept"
}
06:23:18.603 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1613024598605	geckodriver	INFO	Listening on 127.0.0.1:9192
1613024598615	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileXHGWQZ"
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libEGL missing
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1613024600472	Marionette	INFO	Listening on port 44251
06:23:20.558 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
06:23:20.559 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 7a539bc1-5edb-4d2b-a99f-7c1083eaed45 (org.openqa.selenium.firefox.GeckoDriverService)
1613024600557	Marionette	ERROR	[15] No reply from Marionette:Register
1613024613663	Marionette	ERROR	[36] No reply from Marionette:Register
```
Using the following configuration:
Selenium container version: 3.141.59-20210128
Host OS: Ubuntu 20.04
Webdriver: PHP Webdriver with Codeception 4

**Comment by PuppetA17** [comment]
I have the same problem. Have you found a solution？

**Comment by laoneo** [comment]
Nope, spent hours on it, but had no way to set a custom profile.

**Comment by diemol** [comment]
As mentioned on the Wiki [page](https://github.com/SeleniumHQ/docker-selenium/wiki/How-to-use-a-Firefox-custom-profile)...
>**Note**: At the moment of the last edit of this guide, there is [an issue in GeckoDriver](https://github.com/mozilla/geckodriver/issues/1058) that does not allow us to use a profile in a given folder. The issue mentions a [workaround](https://github.com/mozilla/geckodriver/issues/1058#issuecomment-347952270) to bypass the problem, which you can use to build your own image and continue using this guide. The alternative for this is to send a Base64-encoded ZIP of a profile directory through the capabilities.

There is an issue in GeckoDriver preventing this.

**Comment by laoneo** [comment]
The problem is that sending a firefox_profile property base64 encoded doesn't work either.

**Comment by diemol** [comment]
If that is the case, I would create an issue in the Selenium repo, with a detailed description showing how to reproduce the issue and avoiding narratives.

**Comment by alpe12** [comment]
@laoneo Did you find a solution or open an issue somewhere else?

**Comment by laoneo** [comment]
Didn't had time to digg deeper into it.

**Comment by gyanadeeps** [comment]
Hi, 
Any update on this. I am getting this issue while executing a test case on Firefox Custom profile on Docker(Selenium Grid).

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '81c081e51c02', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_292'
Driver info: driver.version: unknown
*******************************************************************************************
Docker error: 

firefox_1  | }
firefox_1  | 17:47:56.716 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
firefox_1  | 1630432076727	geckodriver	INFO	Listening on 127.0.0.1:21305
firefox_1  | 1630432096661	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-profile" "/tmp/firefox_profiles/9simdfzq.SSLProfile" "--marionette-port" "2828" "-profile" "/tmp/firefox_profiles/2f9097d0.aaabbb" "-foreground" "-no-remote"
firefox_1  | [GFX1-]: glxtest: libpci missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
firefox_1  | [GFX1-]: glxtest: libEGL missing
********************************************************************************************
Selenium Logs: 
Aug 31, 2021 11:16:07 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
2021-08-31 23:19:16.666 ERROR k.k.c.m.CustomKeywordDelegatingMetaClass - ❌ Connection refused (os error 111)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '81c081e51c02', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 167.24 seconds
2021-08-31 23:19:16.671 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/New Test Case FAILED.
Reason:
com.kms.katalon.core.exception.StepErrorException: org.openqa.selenium.TimeoutException: Connection refused (os error 111)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '81c081e51c02', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 167.24 seconds................
************************************************************************************************

I tried all the options but was not able to move further.
Help would be appreciated.

Thanks,
[Docker_Log.txt](https://github.com/SeleniumHQ/docker-selenium/files/7085941/Docker_Log.txt)
