### ISSUE TITLE
Docker linux/arm64 images

### ISSUE THREAD

**Issue by sj26** [SeleniumHQ/docker-selenium#1212]
## 🚀 Feature Proposal

Build and push linux/arm64 flavoured docker images.

## Motivation

Many workloads are shifting to arm64. ARM is proving to have better price/performance than other architectures. Most mobile platforms and so many browsers are also now build for and on ARM. Docker for Mac now runs on Apple's new ARM silicon and can run linux/arm64 images. AWS Graviton2 machines are also linux/arm64, and are popular choices for workloads including CI/CD, which make use of Selenium — this is our motivation for wanting ARM images.

## Example

Some dependencies are already available in arm64, I think. Here's a branch I started to try it out, and it's not far off:

https://github.com/SeleniumHQ/docker-selenium/compare/trunk...sj26:arm64

I'd be happy to help, if it would be accepted! 🙇🏻‍♂️

Edit: I think this is harder than first imagined. It's possible in Debian using chromium and firefox, but upstream browsers don't seem to be available for arm64 natively yet.

**Comment by diemol** [comment]
Thank you for offering help, @sj26!

Absolutely, we are glad to receive a PR for this, we can continue the conversation here #1076

Closing this one and hoping we can concentrate all comments in the linked issue.

**Comment by sj26** [comment]
Great, I've added some context over there, but I'm not sure armhf == arm64.
