### ISSUE TITLE
Why is GRID_BROWSER_TIMEOUT set to 0?

### ISSUE THREAD

**Issue by mikewrighton** [SeleniumHQ/docker-selenium#122]
I'm just wondering why `GRID_BROWSER_TIMEOUT` (`browserTimeout`) is being set to 0 in the Hub config? I don't doubt it's correct but just wanted some clarification as I couldn't find much documentation on this value. Also, if I want to modify this, do I specify seconds or milliseconds?

Thanks

**Comment by aksharpanchal** [comment]
:+1:

**Comment by vikramvi** [comment]
+1

**Comment by mikewrighton** [comment]
So my guess is that a 0 value means never timeout.

With the GRID_UNREGISTER_IF_STILL_DOWN_AFTER variable defaulted to 30 seconds, it seems like  nodes that take longer than 30 seconds to respond (e.g. because they're accessing a slow web page) will get deregistered. That's certainly what appears to be happening in my setup.

Wouldn't it make more sense for these timeouts to be switched around so that GRID_UNREGISTER_IF_STILL_DOWN_AFTER is infinite, and GRID_BROWSER_TIMEOUT is 30 seconds? That way, if a command takes longer than 30 seconds, it fails but the node stays registered?

**Comment by diemol** [comment]
@mikewrighton It is set to 0 since it is just the default in Selenium Grid. The parameter is [there](https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile#L25) so it can be overwritten when the container is started.

From the Selenium jar:

>     -browserTimeout
       <Integer> in seconds : number of seconds a browser session is allowed to
       hang while a WebDriver command is running (example: driver.get(url)). If the
       timeout is reached while a WebDriver command is still processing, the session
       will quit. Minimum value is 60. An unspecified, zero, or negative value means
       wait indefinitely.
       Default: 0

If this answers you question, could you please close the issue?

Thanks!
