### ISSUE TITLE
Max Concurrency Not Being Applied

### ISSUE THREAD

**Issue by IanDT** [SeleniumHQ/docker-selenium#1223]
## 🐛 Bug Report

Docker version of Selenium not using SE_NODE_MAX_CONCURRENT_SESSIONS parameter.

## To Reproduce

The following commands were run using Docker Desktop:

docker pull selenium/hub:4.0.0
docker pull selenium/node-chrome:4.0.0
docker run -d -p 4444:4444 -e JAVA_OPTS=-Xmx512m -e SE_NODE_MAX_CONCURRENT_SESSIONS=3 --name selenium-hub selenium/hub:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0

This resulted in the following screen.  Nodes were added one at a time, with sufficient delay for each one to have been detected by the grid before the next one was added.

![Sel Grid](https://user-images.githubusercontent.com/13036217/109685471-32e41600-7b79-11eb-84d9-c8bd04c48878.jpg)

## Expected behavior

I expected the display to be similar to this screenshot taken from https://github.com/SeleniumHQ/docker-selenium/issues/1182

![106475997-da9cf400-64a6-11eb-94df-4522bd26131f](https://user-images.githubusercontent.com/13036217/109685606-51e2a800-7b79-11eb-9b6f-66b84c238269.png)

## Test script reproducing this issue (when applicable)

docker pull selenium/hub:4.0.0
docker pull selenium/node-chrome:4.0.0
docker run -d -p 4444:4444 -e JAVA_OPTS=-Xmx512m -e SE_NODE_MAX_CONCURRENT_SESSIONS=3 --name selenium-hub selenium/hub:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0
Hub image ID: c42d1c11d82f
Node image ID: 3e2a33219f8a

-->
Docker version: 20.10.0
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

docker run -d -p 4444:4444 -e JAVA_OPTS=-Xmx512m -e SE_NODE_MAX_CONCURRENT_SESSIONS=3 --name selenium-hub selenium/hub:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0
docker run -d -e SE_EVENT_BUS_HOST=172.17.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0

**Comment by diemol** [comment]
`-e SE_NODE_MAX_CONCURRENT_SESSIONS=3 ` is an env var for the Nodes, not for the Hub.
