### ISSUE TITLE
can not connect the grid when set platform capability parameter

### ISSUE THREAD

**Issue by mengzi007** [SeleniumHQ/docker-selenium#1227]
## 🐛 Bug Report

Can not create remote webdriver when setting platform parmeter

## To Reproduce

I setup local grid 4 by using docker image, version are 4.0.0-beta-1-20210215. the grid contain hub and chrome node, firefox node. When I use following code in my script. 

ChromeOptions options = new ChromeOptions();
options.setCapability("browserName", "chrome");
options.setCapability("platform", "Linux");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), options);

Then it will throw following exception during driver creation
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {browserName: chrome, platform: LINUX}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

And if I set platform to ANY, then it will works. But I'm sure this docker image is Linux system. Same problem for firefox image.
options.setCapability("platform", "ANY");

## Environment

Docker version: 
4.0.0-beta-1-20210215

**Comment by diemol** [comment]
Just fixed this in the Selenium repo. There will be a release including this fix in 1-2 days.
