### ISSUE TITLE
Outdated Google Chrome and Driver versions in standalone-chrome-debug:3.141.59-20210310

### ISSUE THREAD

**Issue by GarrisonD** [SeleniumHQ/docker-selenium#1230]
## 🐛 Bug Report

We have outdated Google Chrome and Driver versions in `standalone-chrome-debug:3.141.59-20210310`:
it's **87.x** instead of **89.x** as specified [here](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210310).

## To Reproduce

```
$ docker run -it selenium/standalone-chrome-debug:3.141.59-20210310 google-chrome --version

> Google Chrome 87.0.4280.88
```

```
$ docker run -it selenium/standalone-chrome-debug:3.141.59-20210310 chromedriver --version

> ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761})
```

## Expected behavior

I expect to have Google Chrome and Driver versions as specified [here](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210310).

## Environment

OS: macOS Big Sur 11.2.3
Docker version: 20.10.5

This issue can also be reproduced on Windows 10 with Docker for Windows via WSL setup.

**Comment by GarrisonD** [comment]
Here is what I get when I inspect the image:

```
{
  "Id": "sha256:6373259933b2673c6bdfcfe099135a4474421727f59cc9e339ac5ef6f455bfb6",
  "RepoTags": [
    "selenium/standalone-chrome-debug:3.141.59-20210310"
  ],
  "RepoDigests": [
    "selenium/standalone-chrome-debug@sha256:0e7f25401aa0e4cb277f5bdf8b4ad52e07276104874d609548d05a03ae8dc862"
  ],

  ...
}
```

The repo digest matches the one specified on the Docker Hub.

**Comment by diemol** [comment]
Thank you for pointing this out, there was a docker cache issue. I just released it again https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210311.
