### ISSUE TITLE
Add support for RedisBackedSessionMap session map backend

### ISSUE THREAD

**Issue by gmichels** [SeleniumHQ/docker-selenium#1241]
## 🚀 Feature Proposal

Add support for the `RedisBackedSessionMap` session backend in the Session Docker container. 

https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-beta-2/java/server/src/org/openqa/selenium/grid/commands/sessionmaps.txt

## Motivation

For long running Grids, failures will inevitably happen, so high-availability is important for reliability. With a persistent backend, sessions are stored in disk rather than in memory, so one can run multiple instances of the session map.

**Comment by gmichels** [comment]
I am not 100% up-to-speed with Grid 4 architecture, but by looking at the current documentation, the Session Map seems to be the only component that can't be scaled horizontally due to storage being in memory.

**Comment by diemol** [comment]
What would be the expectation here?

**Comment by gmichels** [comment]
Well, for now just some confirmation if this makes sense and would be accepted to be added to the docker stack. If so, I can certainly give it a shot myself.

Am I correct in saying the only component that would require persistence to achieve high availability in all grid components would be the session map?

Thanks

**Comment by diemol** [comment]
Yes, that is how it would work. We would happily accept documentation contributions, but we won't add a docker image for Redis to this repo.

**Comment by gmichels** [comment]
I am not 100% sure the underlying RedisBackedSessionMap is even functional, I tried a few times and was unable to achieve anything, so feel free to close this. I can revisit in the future, if things change.

Thanks

**Comment by diemol** [comment]
When we implemented it, it was working well. However we might have broken it during a few bug fixes. Double checking this is on our to-do list before we do a release candidate. 

I will close this as we are tracking this and we will also document it properly.
