### ISSUE TITLE
How can we set the Maxsession parameter for selenium hub?

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#125]
How can we set the Maxsession parameter for selenium hub?
I can se that maxSession value is set as 5 for hub config? I want to run more than 20 selenium node at a time. Please help.

**Comment by JeffHall** [comment]
I have a similar situation where I need to run multiple Chrome and Firefox nodes, and I found that using Docker Compose was a good solution for this.  

The basic idea is that once you bring the services up (docker-compose up -d), you can then scale the browser-specific nodes with commands like this:

docker-compose scale chrome=5
docker-compose scale firefox=5

...which gives you 5 nodes for each of the two browsers.

This has worked really well for a Selenium Grid that I'm maintaining on an Amazon EC2 instance.

More info here: http://www.conductor.com/nightlight/running-selenium-grid-using-docker-compose/

**Comment by dgangwar** [comment]
Hi Jeff,

Thanks for the reply.
I have seen this post and using the docker in the same way. But i am having multiple machine and want to have node running on each machine and connected to a single hub machine. As i have high number of test case and want to reduce execution time using multi node on various machine.

Any idea???

**Comment by apakhomov** [comment]
There is no problem with launching hub and node on different machines. Simply run node with env vars, pointing to grid host and port (for ex. -e HUB_PORT_4444_TCP_ADDR=addr here HUB_PORT_4444_TCP_PORT=port). For the purpose of not using nf_conntrack in hub and node interconnection, you can use Weave network (and also its DNS).

**Comment by dgangwar** [comment]
Thanks @apakhomov .
Is there any way that we can configure this node set up on remote machine using docker compose which will connect to remote Hub automatically and scaling of the images will be easy using the compose?

**Comment by apakhomov** [comment]
@dgangwar 
docker-compose.yml:
  environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-grid
    - HUB_PORT_4444_TCP_PORT=4444

**Comment by dgangwar** [comment]
Thanks @apakhomov 

I will try this solution.

**Comment by dgangwar** [comment]
This solution worked.
