### ISSUE TITLE
ERROR 404: Not Found. selenium-server-4.0.0-prerelease-beta-3-909239cd9f.jar 

### ISSUE THREAD

**Issue by jzlatovtwl** [SeleniumHQ/docker-selenium#1250]
## 🐛 Bug Report

Build of Base docker image (docker-selenium/Base/Dockerfile) fails with error:
```
 ---> Running in 7dd44e6d919a
https://github.com/SeleniumHQ/docker-selenium/raw/beta-jars/selenium-server-4.0.0-prerelease-beta-3-909239cd9f.jar:
2021-03-26 16:43:14 ERROR 404: Not Found.
```

**Comment by jzlatovtwl** [comment]
Looks like was deleted https://github.com/SeleniumHQ/docker-selenium/commit/9fe19bfdfcfdd69a2c1f2f838fb35b4745d496b5 ...

**Comment by diemol** [comment]
Apologies, I was going to do a new prerelease and got into something else. 

The linked commit has the updated version which is available in the other branch.
