### ISSUE TITLE
Session timeout to start the running the tests

### ISSUE THREAD

**Issue by lsantos10** [SeleniumHQ/docker-selenium#1252]
## 🐛 Bug Report

Getting the error to start the running the tests on selenium grid on k8s suing the documentation provided:

```
I/testLogger - [chrome #121] PID: 16572
[chrome #121] [18:03:00] I/hosted - Using the selenium server at http://localhost:8080/wd/hub
[chrome #121] [18:06:01] E/runner - Unable to start a WebDriver session.
[chrome #121] [18:06:01] I/runnerCli - java.util.concurrent.TimeoutException
[chrome #121] Build info: version: '4.0.0-beta-3', revision: '909239cd9f'
[chrome #121] System info: host: 'selenium-router-deployment-d6bd85d4c-w6l4b', ip: '<removed>', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.150+', java.version: '1.8.0_282'
[chrome #121] Driver info: driver.version: unknown
```
## To Reproduce
Created the cluster for selenium and deployed the services using `kubectl apply -f k8s-deployment-full-grid.yaml`
The chrome-nodes is scaled to 5 (no firefox nodes or edge nodes used)
Run my 282 tests using the max-sessions to 4 (so there will be one extra chrome node).
Some tests run and some present the error above.

## Expected behavior
Expected all the tests to run 

## Environment

OS: machine launching the tests: Windows 10 (local)
Build info: version: '4.0.0-beta-3', revision: '909239cd9f'
System info: host: 'selenium-router-deployment-d6bd85d4c-w6l4b', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.150+', java.version: '1.8.0_282'

**Comment by diemol** [comment]
How can we reproduce the issue? How was it deployed?

**Comment by lsantos10** [comment]
Hi @diemol ,
I think I found what the issue is.
I'm trying to make the browser-nodes autoscalable depending on cpu consumption, but there is an implicitly timeout somewhere that while the pods are scaling up, the tests are waiting for an initial answer from the session created. Since the grid does not create a new session because there aren't enough pods, thus the timeout to create a new session.
Is this possible? Should the queue system interact with the requester about the job on queue?
Has anyone tried that before and have a good idea if this can be achieved?
What I would like to do is to on demand create pods with new browser-nodes when new sessions are required, but as they finish the number of pods should be reduced to 1.

**Comment by brendon-r** [comment]
I think I may have run into this too. My setup is a little different in that it's deployed to Azure but what I've found is that if I scale my nodes, more tests pass. It appears as though tests are only waiting for 60 seconds to get a session but given there are no free nodes, they're timing out. I'm going to scale my nodes closer to the number of tests I'm running and see what happens.

**Comment by brendon-r** [comment]
So I scaled up the nodes to 80 and I no longer get timeouts when running my ~130 tests. I do see a lot of these warnings though

```
05: 41: 32.941 WARN [SeleniumSpanExporter$1.lambda$export$0
] - {
    "traceId": "07d9b77ab1a3182cd66383bed5439ad8",
    "spanId": "552fcc8e3f75e6f6",
    "spanKind": "INTERNAL",
    "eventTime": 1617860492940334000,
    "eventName": "exception",
    "attributes": {
        "exception.message": "Unable to execute request for an existing session: Unable to find handler for (GET) \u002fse\u002fgrid\u002fsession\u002f\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'selenium-router-deployment-57598f9fb8-bhfht', ip: '10.240.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1040-azure', java.version: '1.8.0_282'\nDriver info: driver.version: unknown",
        "exception.stacktrace": "org.openqa.selenium.UnsupportedCommandException: Unable to find handler for (GET) \u002fse\u002fgrid\u002fsession\u002f\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'selenium-router-deployment-57598f9fb8-bhfht', ip: '10.240.0.24', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1040-azure', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:140)\n\tat org.openqa.selenium.grid.web.Values.get(Values.java:48)\n\tat org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.makeRequest(RemoteSessionMap.java:119)\n\tat org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.get(RemoteSessionMap.java:90)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:136)\n\tat io.opentelemetry.context.Context.lambda$wrap$1(Context.java:185)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n",
        "exception.type": "org.openqa.selenium.UnsupportedCommandException",
        "http.flavor": 1,
        "http.handler_class": "org.openqa.selenium.grid.router.HandleSession",
        "http.host": "selenium-router.default.svc.cluster.local:4444",
        "http.method": "GET",
        "http.scheme": "HTTP",
        "http.target": "\u002fsession\u002f\u002falert\u002ftext",
        "http.user_agent": "selenium\u002f3.141.0 (.net windows)",
        "session.id": ""
    }
}
```

**Comment by diemol** [comment]
Could you please help us to find a way to reproduce this?

How do you start the Grid and what tests can I run to get the same behavior?

**Comment by brendon-r** [comment]
@lsantos10's setup may be easiest to reproduce but to reproduce my setup, follow Microsoft's instructions here https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli to setup an AKS cluster with the virtual node addin (I use Azure Container Instances for the grid nodes). 

Once that's setup, use `kubectl apply -f k8s-deployment-full-grid.yaml` to deploy the grid and leave only a single chrome node running (delete the others). 

Once it's ready, run a suite of 50-100 tests. In my tests, I have the grid url set to "http://selenium-router.default.svc.cluster.local:4444/".

**Comment by diemol** [comment]
Can we get some tests to run and see this behavior?

**Comment by brendon-r** [comment]
I'll create some basic tests tomorrow and see if I can reproduce the issue on my end and then post here.

**Comment by brendon-r** [comment]
Ok, I've got some tests @diemol 
[Class1.txt](https://github.com/SeleniumHQ/docker-selenium/files/6282511/Class1.txt)
[Class2.txt](https://github.com/SeleniumHQ/docker-selenium/files/6282512/Class2.txt)
[Class3.txt](https://github.com/SeleniumHQ/docker-selenium/files/6282513/Class3.txt)
[Class4.txt](https://github.com/SeleniumHQ/docker-selenium/files/6282514/Class4.txt)
[Class5.txt](https://github.com/SeleniumHQ/docker-selenium/files/6282515/Class5.txt)

My runsettings has the following MsTest configuration so the tests run in parallel:
```xml
  <MSTest>
    <MapInconclusiveToFailed>True</MapInconclusiveToFailed>
    <CaptureTraceOutput>true</CaptureTraceOutput>
    <DeleteDeploymentDirectoryAfterTestRunIsComplete>False</DeleteDeploymentDirectoryAfterTestRunIsComplete>
    <DeploymentEnabled>False</DeploymentEnabled>
    <Parallelize>
      <Workers>0</Workers>
      <Scope>ClassLevel</Scope>
    </Parallelize>
  </MSTest>
```

If you run these when the grid has 0-3 nodes, some tests will timeout instead of queuing. If you scale the number of nodes to the number of tests, all will pass.

**Comment by diemol** [comment]
Ok, I see the issue happens when you are trying to scale up the Nodes before tests run and tests end up timing out ocassionally due to the lack of nodes (as they are starting up). 

I cannot provide any advice as we have not spent any time dealing with Kubernetes so far, we don't have the bandwith to document and recommend ways to scale this for now. However, please follow this [issue](https://github.com/SeleniumHQ/docker-selenium/issues/1184), which will allows (when time permits) to offer a Helm Chart and eventually we will be able to offer some recommendations on how to scale the nodes properly.
