### ISSUE TITLE
edge node is not shown on selneium grid

### ISSUE THREAD

**Issue by raychendl** [SeleniumHQ/docker-selenium#1261]
I noticed we recently published a new docker image for the node-edge. I am trying to use it for test automation. I started up Selenium grid hub docker container, then started this node-edge. But when I go to the grid console (localhost:4444/grid/console), the edge node is not shown.

https://hub.docker.com/r/selenium/node-edge/tags?page=1&ordering=last_updated

Can you please advise anything I missed here? Or which selenium hub docker version it is supposed to work with?

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Edge is only for the Selenium Grid 4 images

**Comment by raychendl** [comment]
Thanks for quick response.

I did try Selenium 4 docker hub:

  *   I started selenium 4 docker hub;
  *   Started  selenium/node-edge:91.0
  *   Started selenium/standalone-firefox-debug:latest
  *   Went to http://192.168.99.100:4444/ui/index.html#/, there is an error "No connection"
<http://192.168.99.100:4444/ui/index.html#/>

[cid:b0850961-9c8b-4512-9372-306e9e2ebd4e]


Best Regards,
Ray Chen


________________________________

**Comment by diemol** [comment]
Please check the readme and follow the instructions to get set in there.
