### ISSUE TITLE
PYTHON: Unable to Download

### ISSUE THREAD

**Issue by mrkgoh** [SeleniumHQ/docker-selenium#1262]
## 💬 Questions and Help
I am running selenium/standalone-chrome in a docker container in a home Synology DS220+ NAS. I trigger it using a python script:
` client = docker.from_env()
    #Check if there are Selenium containers
if client.containers.list(filters={'ancestor':'selenium/standalone-chrome'})==[]:
        # Then run a selenium container
        container = client.containers.run('selenium/standalone-chrome',
                                          detach=True,
                                          auto_remove=True,
                                          ports={'4444/tcp':('127.0.0.1',4444)},
                                          volumes = {'/dev/shm':{'bind':'/dev/shm','mode':'rw'}})`

I am unable to download to a folder located on the NAS:
`CONTRACT_NOTE_LOCATION = '/volume1/homes/admin/Drive/Personal/investments/equity/contract note/'`

And in my Webscraping.py file I have:
`        chrome_options = Options()
        
        self.download_dir_ = config.CONTRACT_NOTE_LOCATION
        
        chrome_options.add_experimental_option('prefs',  {
                "download.default_directory": self.download_dir_,
                "download.prompt_for_download": False,
                "download.directory_upgrade": True,
                "plugins.always_open_pdf_externally": True
                }
            )
self.driver_ = webdriver.Remote("http://127.0.0.1:4444/wd/hub",options=chrome_options)`

I am not sure what do I need to do to be able to configure the docker image to the CONTRACT_NOTE_LOCATION?

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!
