### ISSUE TITLE
Getting  Cannot start service node-docker: OCI runtime create failed: /config.toml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### ISSUE THREAD

**Issue by hojbotas** [SeleniumHQ/docker-selenium#1263]
## 🐛 Bug Report

tries to use docker-compose for the dynamic hub

## To Reproduce

1. https://github.com/SeleniumHQ/docker-selenium/edit/trunk/docker-compose-v3-dynamic-grid.yml use this docker compose
2. docker compose up -> ERROR: for ui_e2e_node-docker_1  Cannot start service node-docker: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/host_mnt/Users/nb100289-user/repos/ui_e2e/NodeDocker/config.toml" to rootfs at "/var/lib/docker/overlay2/13f672894767ad5e25da0b21468a98ca0df4a8390a911474babb5fd2b1d430a6/merged/opt/bin/config.toml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for node-docker  Cannot start service node-docker: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/host_mnt/Users/nb100289-user/repos/ui_e2e/NodeDocker/config.toml" to rootfs at "/var/lib/docker/overlay2/13f672894767ad5e25da0b21468a98ca0df4a8390a911474babb5fd2b1d430a6/merged/opt/bin/config.toml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

## Expected behavior

The hub is up and running

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: OSX
Docker-Selenium image version: 3.2.2
Also provide the docker image id 
-->
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
How can we reproduce the issue? Can you provide detalied steps? I used the sample file and did not bump into an issue.

**Comment by diemol** [comment]
Closing as we did not get a reply.

**Comment by theqa-ninja** [comment]
not the OP, but i hit this same issue.  I have a fresh build (literally installed docker this morning).  I'm able to run https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml fine, but when I try the https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-dynamic-grid.yml file, I get the OCI issue.  

Environment: 
Windows WSL environment that's using Ubuntu version 2
Docker version 20.10.6, build 370c289

Image:  selenium/node-docker    4.0.0-beta-4-prerelease-20210517   f017ac2738cf   6 days ago   364MB

My exact errors are...

```$ docker-compose -f docker-compose-v3-dynamic-grid.yml up
Creating selenium-hub ... done
Creating docker_node-docker_1 ... error

ERROR: for docker_node-docker_1  Cannot start service node-docker: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/67630e325f03774ecf26a025d9af77966ce956eaa0b22f616d1b144275ad6975" to rootfs at "/var/lib/docker/overlay2/08f01161bc565e3a17f3de87171beb99283dcc47784322473bcfa64bff55d5a3/merged/opt/bin/config.toml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for node-docker  Cannot start service node-docker: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/67630e325f03774ecf26a025d9af77966ce956eaa0b22f616d1b144275ad6975" to rootfs at "/var/lib/docker/overlay2/08f01161bc565e3a17f3de87171beb99283dcc47784322473bcfa64bff55d5a3/merged/opt/bin/config.toml" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project. ```
