### ISSUE TITLE
Problem with JAVA_OPTS

### ISSUE THREAD

**Issue by tiaguiar** [SeleniumHQ/docker-selenium#127]
Problem with JAVA_OPTS

-maxSession

Unrecognized option: -maxSession
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

In version 2.47.1 is OK

in version 2.48.2 not work

**Comment by mathieu-pousse** [comment]
if this is a selenium option, you must now provide this value in the SE_OPTS environment variable. checkout the readme, it has been updated about that

**Comment by tiaguiar** [comment]
Hi @mathieu-pousse thanks! it works now!

**Comment by mathieu-pousse** [comment]
@rubytester you can close this one I think
