### ISSUE TITLE
Grid 4 doesn't work with Appium as node

### ISSUE THREAD

**Issue by dbudim** [SeleniumHQ/docker-selenium#1272]
## 🐛 Bug Report
Hi!
I'm running few Appium servers as Grid nodes `- appium --nodeconfig config.json` and it works perfect with grid 3.

While trying to start same configuration with grid 4 i receive:
`[debug] [Appium] Hub down or not responding: Request failed with status code 404 [Appium] An attempt to register with the grid was unsuccessful: Request failed with status code 404`

Are there some changes in config that i need to make for run same configuration with grid 4?
Seems node registration url was changed

My config file:
`{ "capabilities": 
[ { "browserName": "iPhone 12 Pro Max", "version":"14.5", "maxInstances": 1, "platform":"iOS" } ],
 "configuration": { "cleanUpCycle":2000, "timeout":30000, "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy", "url":"http://192.168.0.1:4723/wd/hub", "host": "192.168.0.1", "port": 4723, "maxSession": 1, "register": true, "registerCycle": 5000, "hubPort": 4444, "hubHost": "192.168.0.101", "hubProtocol": "http" } }`

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
- run grid 4 hub
- start appium as node  `- appium --nodeconfig config.json`

## Expected behavior
node registerd

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
@dbudim, yes, this is not working yet as both projects (Appium & Selenium) need to work together to make it work.

This will be tracked here https://github.com/SeleniumHQ/selenium/issues/9127

**Comment by dbudim** [comment]
@diemol Thanks)
