### ISSUE TITLE
Upgrade jdk8 to jdk11

### ISSUE THREAD

**Issue by Deycoesr** [SeleniumHQ/docker-selenium#1277]
## 🚀 Feature Proposal

upgrade [`openjdk-8-jre-headless`](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Base/Dockerfile#L23) to `openjdk-11-jre-headless`

## Motivation

I cannot use jdk11 new features in this image   : (

**Comment by diemol** [comment]
Would you like to send a PR to upgrade the Java version in the Docker images?
