### ISSUE TITLE
Router and session queuer problem in Beta 4

### ISSUE THREAD

**Issue by dironel** [SeleniumHQ/docker-selenium#1288]
## 🐛 Bug Report

Hello i run new 4.0.0-beta-4-prerelease-20210513 on kubernetes cluster.
After i restart all pods with new version Session queuer has in it's logs this.
Included extra file "/etc/supervisor/conf.d/selenium-grid-session-queuer.conf" during parsing
2021-05-17 07:57:54,141 INFO supervisord started with pid 8
2021-05-17 07:57:55,146 INFO spawned: 'selenium-grid-session-queuer' with pid 10
Starting Selenium Grid SessionQueuer...
2021-05-17 07:57:55,156 INFO success: selenium-grid-session-queuer entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Selenium Server commands

A list of all the commands available. To use one, run `java -jar selenium.jar
commandName`.

  completion    Generate shell autocompletions
  distributor   Adds this server as the distributor in a selenium grid.
  hub           A grid hub, composed of sessions, distributor, and router.
  info          Prints information for commands and topics.
  node          Adds this server as a node in the selenium grid.
  router        Creates a router to front the selenium grid.
  sessionqueue  Adds this server as the new session queue in a selenium grid.
  sessions      Adds this server as the session map in a selenium grid.
  standalone    The selenium server, running everything in-process.

For each command, run with `--help` for command-specific help

Use the `--ext` flag before the command name to specify an additional classpath
to use with the server (for example, to provide additional commands, or to
provide additional driver implementations). For example:

  java -jar selenium.jar --ext example.jar:dir standalone --port 1234

2021-05-17 07:57:55,625 INFO exited: selenium-grid-session-queuer (exit status 0; expected)

and router this
 Included extra file "/etc/supervisor/conf.d/selenium-grid-router.conf" during parsing
2021-05-17 07:57:55,210 INFO supervisord started with pid 8
2021-05-17 07:57:56,214 INFO spawned: 'selenium-grid-router' with pid 10
Starting Selenium Grid Router...
2021-05-17 07:57:56,225 INFO success: selenium-grid-router entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Was passed main parameter '--sessionqueuer-host' but no main parameter was defined in your arg class
Usage: router [options]
  Options:
    --allow-cors
      Whether the Selenium server should allow web browser connections from
      any host
      Default: false
    --config
      Config file to read from (may be specified more than once)
    --config-help
      Output detailed information about config options
      Default: false
    -d, --distributor
      Url of the distributor.
    --distributor-host
      Host on which the distributor is listening.
    --distributor-implementation
      Full classname of non-default distributor implementation
      Default: org.openqa.selenium.grid.distributor.local.LocalDistributor
    --distributor-port
      Port on which the distributor is listening.
    --healthcheck-interval
      How often, in seconds, will the health check run for all Nodes.This
      ensures the server can ping all the Nodes successfully.
      Default: 300
    --host
      Server IP or hostname: usually determined automatically.
    --https-certificate
      Server certificate for https. Get more detailed information by running
      "java -jar selenium-server.jar info security"
    --https-private-key
      Private key for https. Get more detailed information by running "java
      -jar selenium-server.jar info security"
    --log
      File to write out logs
    --log-encoding
      Log encoding
    --log-level
      Log level. Default logging level is INFO. Log levels are described here
      https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
      Default: INFO
    --max-threads
      Maximum number of listener threads. Default value is: (available
      processors) * 3.
      Default: 3
    --plain-logs
      Use plain log lines
      Default: true
    -p, --port
      Port to listen on. There is no default as this parameter is used by
      different components, for example Router/Hub/Standalone will use 4444
      and Node will use 5555.
    --registration-secret
      Node registration secret
    --relax-checks
      Relax checks on origin header and content type of incoming requests, in
      contravention of strict W3C spec compliance.
      Default: false
    --session-request-timeout
      Timeout in seconds. New incoming session request is added to the queue.
      Requests sitting in the queue for longer than the configured time will
      timeout.
      Default: 300
    --session-retry-interval
      Retry interval in seconds. If all slots are busy, new session request
      will be retried after the given interval.
      Default: 5
    --sq, --sessionqueue
      Address of the session queue server.
    --sessionqueue-host
      Host on which the session queue server is listening.
    --sessionqueue-port
      Port on which the session queue server is listening.
    -s, --sessions
      Address of the session map server.
    --sessions-host
      Host on which the session map server is listening.
    --sessions-port
      Port on which the session map server is listening.
    --slot-matcher
      Full classname of non-default slot matcher to use. This is used to
      determine whether a Node can support a particular session.
      Default: org.openqa.selenium.grid.data.DefaultSlotMatcher
    --slot-selector
      Full classname of non-default slot selector. This is used to select a
      slot in a Node once the Node has been matched.
      Default: org.openqa.selenium.grid.distributor.selector.DefaultSlotSelector
    --structured-logs
      Use structured logs
      Default: false
    --version
      Displays the version and exits.
      Default: false

2021-05-17 07:57:56,478 INFO exited: selenium-grid-router (exit status 0; expected)

 how can I restart both components to run correctly ?

Regards Libor

**Comment by dironel** [comment]
session queue: in script start-selenium-grid-session-queuer.sh 
there should be 
java ${JAVA_OPTS} -jar /opt/selenium/selenium-server.jar **sessionqueue** \
  --publish-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_PUBLISH_PORT} \
  --subscribe-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_SUBSCRIBE_PORT} \
  ${HOST_CONFIG} \
  ${PORT_CONFIG} \
  ${SE_OPTS}

instead of 
java ${JAVA_OPTS} -jar /opt/selenium/selenium-server.jar **sessionqueuer** \
  --publish-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_PUBLISH_PORT} \
  --subscribe-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_SUBSCRIBE_PORT} \
  ${HOST_CONFIG} \
  ${PORT_CONFIG} \
  ${SE_OPTS}

**Comment by dironel** [comment]
seems same problem in router 
--sessionqueuer-host was changed to 
--sessionqueue-host

**Comment by diemol** [comment]
Thank you for reporting this, it has been fixed and available in https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-4-prerelease-20210517
