### ISSUE TITLE
Fully Distributed Grid UI - Exception while fetching data (/nodesInfo/nodes) : java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by HariSekhon** [SeleniumHQ/docker-selenium#1292]
## 🐛 Bug Report

When running a Grid 4.0.0 in hub and node mode it works fine, but in fully distributed grid mode I get this exception trying to load the UI:

```
Selenium Grid
Exception while fetching data (/grid/totalSlots) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/nodeCount) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/maxSession) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/sessionCount) : java.lang.reflect.InvocationTargetException

There has been an error while loading the Nodes from the Grid.
Exception while fetching data (/nodesInfo/nodes) : java.lang.reflect.InvocationTargetException
```

Do I need to load another component like hub - I've looked through your k8s yaml when designing my own and I don't see a hub deployment there.

## To Reproduce

Open the Router url in browser as you would have opened the hub url:

http://router:4444/ui/index.html#/

## Expected behavior

I expected to see the connected nodes, similar to using hub and node mode.

## Test script reproducing this issue (when applicable)

My Selenium Grid fully distributed Kubernetes yamls are here:

https://github.com/HariSekhon/Kubernetes-templates/

See `selenium-grid-distributed-kustomization.yaml` for what I am loading.

I have tested it using code and the actual browsers worked fine when running this test script:

https://github.com/HariSekhon/DevOps-Python-tools/blob/master/selenium_hub_browser_test.py

## Environment

GKE

**Comment by dironel** [comment]
According to this issue
https://github.com/SeleniumHQ/docker-selenium/issues/1288
session queuer was renamed to the session queue and all settings in grid too.

Look at this fix https://github.com/SeleniumHQ/docker-selenium/pull/1290

**Comment by HariSekhon** [comment]
It's noticed that session queue was renamed as it still broke in the 4.0.0 docker image and I worked around while testing, but it wasn't clear that this is the cause of the UI not finding grid nodes URLs as per the UI error:

`/grid/totalSlots`

`/nodesInfo/nodes`

I thought I'd updated my k8s yamls according - did you see something in them that referenced this fix?

**Comment by diemol** [comment]
Yes, we had to rename it do to internal refactoring and to be consitant with the naming. We preferred to do it now and not when 4.0 was released, causing more pain.
This release contains the fix https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-4-prerelease-20210517
