### ISSUE TITLE
Change of number of Session in Standalone FireFox V4 Beta3

### ISSUE THREAD

**Issue by matclayton** [SeleniumHQ/docker-selenium#1308]
## 💥 Regression Report

In Migrating from 3.141.59 to v4 beta3 we discovered the need to set the env var SE_NODE_MAX_SESSIONS=0 to maintain the existing behaviour of 1 session per CPU core. 

I believe this is the culprit, but haven't chased it down through history.
 
https://github.com/SeleniumHQ/docker-selenium/blob/fb77532c4f74cb3f09f2cbfa326fa324b12755d7/NodeBase/Dockerfile.txt#L163

## Last working version

Worked up to version: selenium/standalone-firefox-debug:3.141.59-selenium 

Stopped working in version: selenium/standalone-firefox:4.0.0-beta-4-prerelease-20210517

## To Reproduce

Run multiple selenium tests in parallel on the standalone version

## Expected behavior

We can run as many tests as CPU cores

## Test script reproducing this issue (when applicable)

Sorry I don't have a simple repro

## Environment

OS: OSX Docker for Mac + Linux
Docker-Selenium image version: selenium/standalone-firefox:4.0.0-beta-4-prerelease-20210517

Docker version: 3.3.3

**Comment by diemol** [comment]
@matclayton, please have a look at this [section](https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container) in the README.

If you find any issues after following those docs, please comment here with enough details and I will reopen the issue.

**Comment by matclayton** [comment]
It works as described in the docs, I was expecting it to default to 0 (no. of cores) as per previous versions, came as a bit of a debugging nightmare to locate and fix this up moving from 3 to 4, thats all.
