### ISSUE TITLE
exposing grid to public servers

### ISSUE THREAD

**Issue by Truth1984** [SeleniumHQ/docker-selenium#1311]
## 🚀 Feature Proposal

currently, exposing grid to a public server is pretty dangerous, because you have no security implementation, anyone can connect to your webdriver. Thus adding some sort of authentications would be helpful.

## Motivation

Centralize testing on public servers / bypass ip rate limit restriction by using different grid. 

## Example

`docker run --env SELENIUM_PASSWORD="password" ...`

wd:

```js
{
    protocol: 'http:',
    hostname: 'SERVER-IP',
    port: '4444',
    path: '/wd/hub',
    password:'password' //default to none
}
```

**Comment by diemol** [comment]
Duplicate of https://github.com/SeleniumHQ/selenium/issues/9372
