### ISSUE TITLE
StandaloneEdge - No latest tag found on Docker

### ISSUE THREAD

**Issue by unickq** [SeleniumHQ/docker-selenium#1313]
## 🚀 Feature Proposal

Add the latest tag to https://hub.docker.com/r/selenium/standalone-edge/tags

Or is there a particular problem not having it there? StandaloneChrome and StandaloneFirefox have it

Thanks

**Comment by diemol** [comment]
This is because the Docker images with Edge are using Grid 4, and all `latest` tags are pointing to Grid 3 images. 

Using `latest` for Edge would confuse users for now. When Grid 4 is released, `latest` tags will move as well.

**Comment by unickq** [comment]
But how doesn't it confuse users on chrome and ff? Or those latest tags are Grid 4 based too @diemol ?

**Comment by diemol** [comment]
They are not, `latest` in Chrome and Firefox only point to Grid 3 images
See https://github.com/SeleniumHQ/docker-selenium/wiki/Tagging-Convention
