### ISSUE TITLE
Interacting with inputs is broken in latest release

### ISSUE THREAD

**Issue by acbramley** [SeleniumHQ/docker-selenium#1316]
## 🐛 Bug Report

Some of our tests started failing on June 8 after a new image was released. The tests that failed were ones that did setValue and getValue on inputs in both PHP based mink tests along with nightwatch tests.

Pinning to `selenium/standalone-chrome:3.141.59-20210422` fixed it.

## To Reproduce
For the PHP tests, these are Drupal based tests using https://gitlab.com/weitzman/drupal-test-traits/ and the Selenium2 driver which comes from `behat/mink-selenium2-driver`

The nightwatch tests were doing very straight forward assertions:

```
    browser
      .betterClearValue(input)
      .setValue(input, 'sydney 2000')
      .click(submit);
    browser.expect.element(input).value.equals('Sydney 2000').before(5000);
```

## Expected behavior

Tests continue to pass when updating container image.

## Test script reproducing this issue (when applicable)

See nightwatch test above.

## Environment

OS: OSX
Docker-Selenium image version: latest (18ad843ba098)
Docker version: 20.10.6
Docker-Compose version (if applicable): 1.29.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): Default command

These same tests also failed in circleci.

**Comment by diemol** [comment]
The only difference between the released docker 3.x images and the previous ones is the Chrome and ChromeDriver version, therefore, please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
