### ISSUE TITLE
Failed to load resource: net::ERR_FAILED

### ISSUE THREAD

**Issue by mblanloeil** [SeleniumHQ/docker-selenium#1322]
## 🐛 Bug Report

We regularly get errors like "Failed to load resource: net::ERR_FAILED" when chrome tries to load JS & CSS files. These errors are visible in the browser console. 
These files do exist, we can access them. 
Have you already noticed this error?

## To Reproduce

The bug is difficult to reproduce, 

## Environment

Docker-Selenium image version: selenium/standalone-chrome:3.141.59-20210128
deploy on jenkins agent

**Comment by diemol** [comment]
Could you please create a new issue with all the template fiels filled out? There is no information to actually triage this issue. If you have any questions, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
