### ISSUE TITLE
Outdated Google Chrome and Driver versions in standalone-chrome-debug:3.141.59-20210607

### ISSUE THREAD

**Issue by mil7** [SeleniumHQ/docker-selenium#1323]
## 🐛 Bug Report

In [current 3.141.59 release tag](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210607) fairly outdated Chrome and Chromedriver versions are shipped.

## To Reproduce
In shipped versions
* Chrome: 91.0.4472.77
* ChromeDriver: 91.0.4472.19
at least one major bug is contained: https://bugs.chromium.org/p/chromium/issues/detail?id=1205107

## Expected behavior

With [latest versions](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop.html)

* Chrome: 91.0.4472.101
* ChromeDriver: 91.0.4472.101
 
at least this bug is fixed.

**Comment by diemol** [comment]
We just released new images
https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210713
