### ISSUE TITLE
null value in entry: message=null

### ISSUE THREAD

**Issue by szamacz** [SeleniumHQ/docker-selenium#1329]
## 🐛 Bug Report

Tests running on selenium standalone chrome docker failing with error
OpenQA.Selenium.WebDriverException null value in entry: message=null
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
The same tests running on local chrome browser works fine.
This error is thrown after 5 min during which the test is stuck.

## To Reproduce

Run a bunch of tests (in my case it's 180), some of them fail with the above error.

## Expected behavior

Tests running fine, without stuck and throwing errors.

## Environment

OS: windows 10
Docker-Selenium image version: standalone-chrome:91.0
Last working version: standalone-chrome:89.0
https://hub.docker.com/layers/selenium/standalone-chrome/91.0/images/sha256-bf8e08f540803b4207c2bac8b69e37f6834553a7d6e600c337a8fb5476b11d12?context=explore
-->
Docker version: 3.5.1 (66090)

Exact Docker command to start the containers 
docker run -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm selenium/standalone-chrome:91.0

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by szamacz** [comment]
Hi @diemol, thanks for looking into this, as I wrote in the description, the issue is reproducible when running a higher amount of tests, that's why I'm not able to provide a single test case to reproduce it.

**Comment by diemol** [comment]
Can you please provide a test suite we can use to reproduce the issue?

**Comment by diemol** [comment]
Closing this as no means to reproduce this issue were provided.
