### ISSUE TITLE
Can't connect plain selenium-server-4.0.0-beta-4.jar node to Docker-based grid

### ISSUE THREAD

**Issue by fkrivsky** [SeleniumHQ/docker-selenium#1331]
## 🐛 Bug Report

We are trying to connect some Windows 10 / IE 11 nodes to our existing Docker-based Selenium Grid using selenium-server-4.0.0-beta-4.jar
However, the nodes do not finish registration with server, retrying ``Sending registration event...`` over and over again.

## To Reproduce
The same failure happens with the grid located in Docker Swarm or in Kubernetes on CentOS7.
NOT reproducible with Grid v3/selenium-server-standalone-3.141.59.jar.

Steps to reproduce the behavior (including the command to start the containers):
1. Start Selenium Hub: ``docker run -d --name=hub -p 4442:4442 -p 4443:4443 -p 4444:4444 selenium/hub:4``
2. Download latest Selenium Server jar via https://www.selenium.dev/downloads/ (i.e. https://selenium-release.storage.googleapis.com/4.0-beta-4/selenium-server-4.0.0-beta-4.jar)
3. Download IEDriverServer and place it in the same directory as the selenium-server-4.0.0-beta-4.jar, and/or add it in the system PATH.
3. Try to start the jar in node mode, connecting to the hub from step 1: ``java -jar selenium-server-4.0.0-beta-4.jar node --detect-drivers true --grid-url http://localhost:4444 --publish-events tcp://localhost:4442 --subscribe-events tcp://localhost:4443``
4. The node should be able to connect but does not, with the following node logs:
```java -jar selenium-server-4.0.0-beta-4.jar node --detect-drivers true --grid-url http://localhost:4444 --publish-events tcp://localhost:4442 --subscribe-events tcp://localhost:4443
16:13:40.684 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:13:40.688 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:13:40.962 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://localhost:4442 and tcp://localhost:4443
16:13:41.025 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:13:42.028 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:13:42.424 INFO [NodeServer.createHandlers] - Reporting self as: http://<ip>:5555
16:13:42.763 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
16:13:42.802 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
16:13:42.824 INFO [NodeOptions.report] - Adding Internet Explorer for {"browserName": "internet explorer","platformName": "WIN10"} 1 times
16:13:42.832 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
16:13:43.642 INFO [NodeServer$1.start] - Starting registration process for node id b4d5f369-ee2c-4d32-8647-311fc48d3564
16:13:43.644 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-4 (revision 29f46d02dd): http://<ip>:5555
16:13:43.663 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:13:53.667 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:14:03.665 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```
5. The Grid server shows the following errors for these events:
```
14:14:02.914 WARN [UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2] - Caught exception from listener: org.openqa.selenium.events.EventListener@7aa85ecf,
org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.grid.data.NodeStatus,
Build info: version: '4.0.0-rc-1', revision: '74745cf081',
System info: host: 'f160c67909e4', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.72-microsoft-standard-WSL2', java.version: '11.0.11',
Driver info: driver.version: unknown,
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61),
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145),
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127),
	at org.openqa.selenium.json.Json.toType(Json.java:69),
	at org.openqa.selenium.json.Json.toType(Json.java:55),
	at org.openqa.selenium.json.Json.toType(Json.java:50),
	at org.openqa.selenium.events.Event.getData(Event.java:59),
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:43),
	at org.openqa.selenium.events.EventListener.accept(EventListener.java:25),
	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2(UnboundZmqEventBus.java:273),
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515),
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628),
	at java.base/java.lang.Thread.run(Thread.java:829),
Caused by: java.lang.reflect.InvocationTargetException,
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.base/java.lang.reflect.Method.invoke(Method.java:566),
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59),
	... 14 more,
Caused by: java.lang.IllegalArgumentException: Node id must be set,
	at org.openqa.selenium.internal.Require.nonNull(Require.java:56),
	at org.openqa.selenium.grid.data.NodeStatus.<init>(NodeStatus.java:58),
	at org.openqa.selenium.grid.data.NodeStatus.fromJson(NodeStatus.java:123),
	... 18 more
```

## Expected behavior

The node should be able to register with the grid.

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-rc-1-prerelease-20210713, f9f455fc4e84
Docker version: 
```Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
- ``docker run -d --name=hub -p 4442:4442 -p 4443:4443 -p 4444:4444 selenium/hub:4``
- ``java -jar selenium-server-4.0.0-beta-4.jar node --detect-drivers true --grid-url http://localhost:4444 --publish-events tcp://localhost:4442 --subscribe-events tcp://localhost:4443``

**Comment by dahud10001** [comment]
I have this same issue, I find that if connecting docker to docker from different machines it will connect, but if its like he said or Docker Hub (either fully distributed or just the hub) the docker nodes will connect but a windows node will fail for the same reason.

**Comment by dahud10001** [comment]
what worked for me, which was referred to me, was to use the latest RC build.

**Comment by fkrivsky** [comment]
> 
> 
> what worked for me, which was referred to me, was to use the latest RC build.

Where did you get the RC build please? 
As for Docker images, I'm already using the latest, for jars I only see the beta-4 as [latest release](https://github.com/SeleniumHQ/selenium/releases).

**Comment by dahud10001** [comment]
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713 

for the docker images use the tag :4.0.0-rc-1-prerelease-20210713.

**Comment by fkrivsky** [comment]
Thanks, I'm already using that one though...

**Comment by diemol** [comment]
@fkrivsky the jar can be found in the downloads section of the prerelease 
https://github.com/SeleniumHQ/docker-selenium/releases/download/4.0.0-rc-1-prerelease-20210713/selenium-server-4.0.0-prerelease-rc-1-74745cf081.jar

I will close this as this is a duplicate from the issue @dahud10001 reported (and helped to troubleshoot here 🙌 )
