### ISSUE TITLE
Proxy vnc requests from UI dashboard when deploying to Kubernetes cluster

### ISSUE THREAD

**Issue by komby** [SeleniumHQ/docker-selenium#1333]
## 🚀 Feature Proposal
Add a configuration option to the grid UI so that when it is deployed in the Kubernetes cluster the VNC icon goes through a proxy instead of trying to directly access the Selenium Node by IP:Port.  

## Motivation

When deployed in k8s the UI for viewing the sessions has a video icon that seems to attempt to load a VNC viewer to connect and view the VNC on the Selenium node (Pod).  In our kubernetes cluster none of the pod IPs are available outside of the cluster so a web browser attempting to connect from the grid cannot view the VNC.  

## Example

Please provide an example for how this feature would be used.
![image](https://user-images.githubusercontent.com/3027079/125812574-cd5c972a-6279-442c-89e1-f439c75c46f3.png)
![image](https://user-images.githubusercontent.com/3027079/125812768-50ef763d-0f82-417c-81e1-300d4269dd30.png)

**Comment by diemol** [comment]
The requests are already proxied, the issue is that containers start by default with a VNC password, and we need to add a dialog in the UI to ask the user for the password. 
If you start the containers without a VNC passwords, you should see the live view.

I will keep this open so we can track when we add this to the UI.

**Comment by komby** [comment]
I double checked this.  I have setup that they do not start with a VNC password.  Since none of our chrome nodes (k8s pods) are available outside of the cluster and they are on a different IP/subnet from the external ip address of the selenium-router which is being exposed as a LoadBalancer type.  In my case the external IP of the selenium router is in 10.30.13.x subnet and the chrome node (depending on what k8s node will vary) but in the debugging example I have seen 10.244.3.x  used for the chrome nodes.  When connecting to the UI and trying to initiate the connection to the No Password VNC I see requests from my web browser in Chrome dev tools to connect to   ws://10.244.3.80:5555/session/33c973dffd67256c2d89c827e60bd484/se/vnc   In this case 10.244.3.80  is running inside the K8s cluster and is never going to be accessible from code running on my browser?  
![image](https://user-images.githubusercontent.com/3027079/127721945-8cecbf58-a73a-48cb-91cd-abd6361e85af.png)

Maybe I am just not clear on how the parts work.

I tried seeting the VNC_NO_PASSWORD like this
![image](https://user-images.githubusercontent.com/3027079/127722794-7b5348b9-f7a1-4f46-ae79-78469a57fd5b.png)

**Comment by diemol** [comment]
This is because the Node needs to send back the Grid publicly accessible url, please check https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout.

With that being set, the vnc connection should use the Hub/Router url.

**Comment by komby** [comment]
I will try. Why would this not be the default setting when deploying using the k8s-deployment-full-grid.yaml?

**Comment by komby** [comment]
Ok that change, If I manually put the EXTERNAL-IP from the selenium-router (LoadBalancer type)  http://<EXTERNAL-IP:PORT>  in the setting SE_NODE_GRID_URL for the chrome nodes does change what I see. Looks like that does fix the VNC part but I am still not seeing the browser.

![image](https://user-images.githubusercontent.com/3027079/128204000-17da8c0a-d80d-40c3-8d30-462a41908920.png)

**Comment by komby** [comment]
Update: I had been running the --headless options.  With that removed I have working VNC. Game Changer. Thank you!  I think this issue can now be closed.

**Comment by diemol** [comment]
This has been fixed, and will be released soon in docker-selenium as well. Now a prompt will be present, allowing the user to enter the password.

![image](https://user-images.githubusercontent.com/5992658/131591735-337038d2-a7fa-4c5d-a779-c1e47439e503.png)
