### ISSUE TITLE
TypeError: an integer is required (got type str) when setting VIDEO_READY_PORT

### ISSUE THREAD

**Issue by therealdjryan** [SeleniumHQ/docker-selenium#1335]
## 🐛 Bug Report

if a video container is created with the env variable VIDEO_READY_PORT set python throws a TypeError. I am including the fix for it

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Expected behavior

A clear and concise deion of what you expected to happen.

## Test script
[video_ready.py.txt](https://github.com/SeleniumHQ/docker-selenium/files/6826028/video_ready.py.txt)
[video_ready.py.txt](https://github.com/SeleniumHQ/docker-selenium/files/6826034/video_ready.py.txt)
 reproducing this issue (when applicable)

Please provide a test  to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.
```
$ cat container-compose.yml
version: '3'
services:
    video:
        image: selenium/video:ffmpeg-4.3.1-20210618

        volumes:
            - /tmp:/videos
        environment:
            - VIDEO_READY_PORT=9001
```
logs show:
```
Waiting before next display check...
Traceback (most recent call last):
  File "/opt/bin/video_ready.py", line 18, in <module>
    httpd = HTTPServer( ('0.0.0.0', video_ready_port), Handler )
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
TypeError: an integer is required (got type str)
2021-07-15 20:09:32,717 INFO exited: video-ready (exit status 1; not expected)
```

## Environment
OS: Linux RHE8
Docker-Selenium image version: selenium/video:ffmpeg-4.3.1-20210618
Docker version: podman version 3.0.2-dev
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
podman-compose up -d

**Comment by diemol** [comment]
Closed via #1336, thank you!
