### ISSUE TITLE
When I use docker-compose to start, node cannot run normally

### ISSUE THREAD

**Issue by maomaokeen** [SeleniumHQ/docker-selenium#1338]
When I use the command to start hub and node, everything is normal.

When I started with docker-compose, after running the script, I saw that node stopped working after executing "Started new session"

docker-compose:
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210713
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20210713
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

node logs:
chrome_1        | 2021-07-16 06:44:52,335 INFO spawned: 'xvfb' with pid 9
chrome_1        | 2021-07-16 06:44:52,338 INFO spawned: 'selenium-node' with pid 10
chrome_1        | Connecting to the Hub using the host selenium-hub and port 4444
chrome_1        | 2021-07-16 06:44:52,752 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2021-07-16 06:44:52,753 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 06:44:53.028 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1        | 06:44:53.162 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
chrome_1        | 2021-07-16 06:44:53.261:INFO::main: Logging initialized @503ms to org.seleniumhq.jetty9.util.log.StdErrLog
chrome_1        | 06:44:53.630 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
chrome_1        | 06:44:53.726 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1        | 06:44:53.727 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1        | 06:44:53.855 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
chrome_1        | 06:44:58.391 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
selenium-hub    | 06:44:58.466 INFO [DefaultGridRegistry.add] - Registered a node http://172.22.0.3:5555
chrome_1        | 06:44:58.469 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
selenium-hub    | 06:45:09.840 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu], extensions: []}, version: , zal:name: dwedwdwedewdewdwedewdewdwe}
selenium-hub    | 06:45:09.845 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=bdc891d9-60c4-49a6-b258-06a126b3df5f, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=91.0.4472.114, applicationName=, platform=LINUX}
chrome_1        | 06:45:09.939 INFO [ActiveSessionFactory.apply] - Capabilities are: {
chrome_1        |   "browserName": "chrome",
chrome_1        |   "goog:chromeOptions": {
chrome_1        |     "args": [
chrome_1        |       "--disable-gpu"
chrome_1        |     ],
chrome_1        |     "extensions": [
chrome_1        |     ]
chrome_1        |   },
chrome_1        |   "version": "",
chrome_1        |   "zal:name": "dwedwdwedewdewdwedewdewdwe"
chrome_1        | }
chrome_1        | 06:45:09.940 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
chrome_1        | Starting ChromeDriver 91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}) on port 8098
chrome_1        | Only local connections are allowed.
chrome_1        | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
chrome_1        | ChromeDriver was started successfully.
chrome_1        | [1626417909.972][SEVERE]: bind() failed: Cannot assign requested address (99)
chrome_1        | 06:45:10.815 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
chrome_1        | 06:45:10.853 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 7919b4ee01c9f0bc5e63f41f77e23e09 (org.openqa.selenium.chrome.ChromeDriverService)

**Comment by stickperson** [comment]
I'm experiencing the same issue on Ubuntu 20.04.2 LTS. It's working on OSX 10.15.7. Image id `182cec1ea35f`
