### ISSUE TITLE
Docker selenium hub is not reachable using the public ip.

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#134]
Hi,

I can see that docker hub and node are running on a linux machine but when i try to access hub using<htpp://linux machine:4444/grid> from remote host then I can not access.

It worked only once but after machine reboot i can not access the hub.

Can any one help?

**Comment by dgangwar** [comment]
Issue solved - I was using root user for docker machine start and was not able to access docker selenium HUB. I switched to docker group user as per the docker docs and it worked.

**Comment by elgalu** [comment]
Ok, I guess you can close this issue mabye?

**Comment by dgangwar** [comment]
Hi,
I am again getting this issue after machine restart. I can not connect the grid url. I tried the solution above also reinstalled docker and machine but no luck. Can any one provide any help?

**Comment by dgangwar** [comment]
After Reinstallation few times and few reboot finally i was able to again get it working.
