### ISSUE TITLE
Video file stream not getting released even after xvfb session ends

### ISSUE THREAD

**Issue by Satish-duvvuri** [SeleniumHQ/docker-selenium#1342]
## 🐛 Bug Report

Though the video file is getting recorded, it cannot be viewed until the Grid is brought down. The video file remains locked as long as the node container is running.

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

1. docker-compose -f docker-compose-v3-video.yml up
2. Run a test against Chrome Browser
3. After the test finishes, try viewing the video file saved by ffmpeg. The file remains locked.
4. The video cannot be played until the containers are brought down using docker-compose -f docker-compose-v3-video.yml down

## Expected behavior

The video file stream should be killed immediately after the xvfb session ends.

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-rc-1-prerelease-20210713

-->
Docker version: 20.10.7, build f0df350
Docker-Compose version (if applicable):
Exact Docker command to start the containers : docker-compose -f docker-compose-v3-video.yml up

**Comment by diemol** [comment]
This is the expected behaviour, `ffmpeg` is still recording and the video file is not ready to be played. `ffmpeg` will release and close the recording appropriately when the container is stopped gracefully (not killed).
