### ISSUE TITLE
session deleted because of page crash

### ISSUE THREAD

**Issue by stickperson** [SeleniumHQ/docker-selenium#1343]
## 🐛 Bug Report

I'm getting multiple errors while trying to fetch a page using the standalone chrome docker image. When I run the application code (shown in the `To Reproduce` section below) in a container, I get one of two tracebacks: The first traceback is:

[traceback 1](https://gist.github.com/stickperson/8ad85a3c8f65f53cdb47bb0a1b65b452)
[traceback 2](https://gist.github.com/stickperson/d99cdb5f289cb810e92545c6bdd2dd2c)

When I run the application code on the host (as opposed to inside a container) I get a [different traceback](https://gist.github.com/stickperson/6b30306e192dbec2620ed7ac502db885).

Since adding `shm_size: 2g` to the `docker-compose` file did not help, I also tried a bind mount (`/dev/shm:/dev/shm`) which did not work either.

One last weird thing to mention is this works just fine when I run the image on my laptop (OSX 10.15.7) but not on Debian.

## To Reproduce
Setup the `docker-compose.yml` file and run `docker-compose up -d`

```
version: "3.3"
services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
    - 4444:4444
```

Then start a python shell and run the following:

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

options = webdriver.ChromeOptions()
options.headless = True
# options.add_argument(f'load-extension={ublock_path}')
options.add_argument('disable-popup-blocking')
options.add_argument('disable-notifications')
driver = webdriver.Remote('http://0.0.0.0:4444/wd/hub', DesiredCapabilities.CHROME)
driver.get('http://google.com')
```

## Expected behavior

Code should run without hanging and without any exceptions thrown.

## Test script reproducing this issue (when applicable)

See steps above to reproduce. The code may work initially but fails if you run it more than a couple of times.

## Environment

OS: Debian 10 Buster
Docker-Selenium image version: Not entirely sure since I'm just using the latest. The image ID is `182cec1ea35f`
Docker version: `20.10.7, build f0df350`
Docker-Compose version (if applicable): `1.29.2, build 5becea4c`
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose up -d`

**Comment by diemol** [comment]
Can you try with the full Docker tag for the latest Selenium 3 release? Also, what do you see in the container logs?

What happens if you try in a different operating system?

**Comment by stickperson** [comment]
I scaled up my digital ocean droplet last night from 1gb -> 2gb ram and everything seems to be working fine (well, after installing `haveged`). I'm reasonably confident this was just a memory issue. I'd be happy to run it again on an instance with 1gb memory if you'd like for testing purposes. Otherwise feel free to close this issue.

**Comment by diemol** [comment]
1gb might be too little depending for what you want to do, 2gb is an ideal size. 

Closing this, thank you for your quick reply, @stickperson.
