### ISSUE TITLE
New standalone-chrome image: SessionNotCreatedError

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/docker-selenium#1351]
## 🐛 Bug Report

Yesterday, DockerHub selenium/standalone-chrome:3.141.59 image (and also lastest) was overriden with a broken version.

## To Reproduce

```
docker run --init -p8000:8000 selenium/standalone-chrome:3.141.59@sha256:9943ba9d2a89e984080f5681b390229fb47f7d3bb732e4f440456fc52335bae8 xvfb-run chromedriver --log-level=DEBUG --port=8000 --allowed-ips
```

```
node -e 'const {Builder} = require("selenium-webdriver"); new Builder().forBrowser("chrome").usingServer("http://localhost:8000/").build().quit()'
```

## Expected behavior

I expected the Node.js program to create a webdriver and exit.

However, it waits for 10 minutes then says 

> SessionNotCreatedError: session not created from timeout: Timed out receiving message from renderer: 600.000

If I use the former `selenium/standalone-chrome:3.141.59@sha256:4a590fc95d67a8eb13464799583991daa6a8548c9a9e2e7f234a92c9c4fa8f29` image, it works as expected.

## Environment

OS: Ubuntu 20.04
Docker-Selenium image version: selenium/standalone-chrome:3.141.59@sha256:9943ba9d2a89e984080f5681b390229fb47f7d3bb732e4f440456fc52335bae8
Docker version: 19.03.14

**Comment by lasdou** [comment]
Exactly the same issue on my CI. I have fixed my docker-compose files to use the previous version 3 release.

**Comment by arjenzorgdoc** [comment]
I used `selenium/standalone-chrome:3.141.59-20210713` in stead of `selenium/standalone-chrome:latest` to work around this issue

**Comment by barisarican** [comment]
Same issue for us since yesterday.

**Comment by phil-mitchell** [comment]
Same here

**Comment by ZheSun88** [comment]
we are having the same issue and pin the version to previous one makes everything better again.

**Comment by kbratanis** [comment]
Same issue since yesterday.

**Comment by turbolasers** [comment]
plus one

**Comment by diemol** [comment]
As mentioned in #1346, seems Chrome 92 has CPU issues when running in Docker. For now, users can pass `--disable-gpu` in their `ChromeOptions` so things work again, see an [example](https://github.com/testcontainers/testcontainers-java/pull/4315/files) of how to do it from our friends  at TestContainers.

I've also pinned the issue in the issues tab, so anyone can see it right away.

**Comment by diemol** [comment]
Also, please submit the issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver. With that, they can have a look as well and probably make another release with a fix.

**Comment by phil-mitchell** [comment]
@diemol any chance of rolling back the `:latest` tag to a working version so that people aren't forced to update all of their CI pipelines to work around a broken Chrome version?

**Comment by dahaupt** [comment]
> Also, please submit the issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver. With that, they can have a look as well and probably make another release with a fix.

@diemol Looks like there is already an open issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1228625

**Comment by diemol** [comment]
Thanks for sharing the link, @dahaupt!
After reading the comments, seems Chrome 93 will have the issue too, looks like the fix will come in Chrome 94.

**Comment by ruescar** [comment]
Seems that the last Chrome 93 build could also fix it.
