### ISSUE TITLE
Node standalone-chrome-debug timeouts

### ISSUE THREAD

**Issue by CGCampbell07** [SeleniumHQ/docker-selenium#1357]
## 🐛 Bug Report

With the latest change to 3.141.x all of our tests are failing as it appears the tests are not ending or the nodes are not becoming available.  Nothing on our end has change and only thing i can see that has changed is the node container for chrome was updated 5 days ago right at the time the tests all started to fail. 

<img width="805" alt="selenium" src="https://user-images.githubusercontent.com/9217087/128076541-9cbfa258-ce33-4a0f-9e3e-2ad6663ab85a.PNG">

I am not sure if this is a selenium issue or if the driver needs updating but everything works fine on container selenium/node-chrome-debug:3.141.59-20210713

## To Reproduce

1. Create kubenetes with selenium grid and spin up 22 standalone-chrome-debug containers with image selenium/node-chrome-debug:3.141
2. point tests to the grid 
3. execute tests 
4. check grid console and see that 20 tests are running and eventually the 2 free nodes become unavailable and tests start backing up.  

## Expected behavior

Expect for the chrome nodes to become free after tests.

## Environment

Docker-Selenium image version: selenium/hub:3.141,  selenium/node-chrome-debug:3.141 
Azure Kubenetes version: 1.20.7

**Comment by diemol** [comment]
There is an issue with Chrome 92, please check https://github.com/SeleniumHQ/docker-selenium/issues/1346, the workaround is mentioned there.
