### ISSUE TITLE
Python 2 pytest

### ISSUE THREAD

**Issue by Burnsedia** [SeleniumHQ/docker-selenium#1362]
## 🐛 Bug Report

Selenium with time out before pytest runs testSetup method in python 2 or 3, but works on bare metal, not in docker

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Can you please fill out the information needed in the template?

**Comment by Burnsedia** [comment]
sorry, typo, I was using the phone app

**Comment by diemol** [comment]
Ok, closing the issue then.
