### ISSUE TITLE
Add a possibility to specify the browser image tag (in our case for selenium/standalone-chrome-debug)

### ISSUE THREAD

**Issue by mjh-c** [SeleniumHQ/docker-selenium#1366]
## 🚀 Feature Proposal

The browser image name is determined from the selenium version, but without the timestamp suffix. For Selenium 3, the image 
"selenium/standalone-chrome-debug:3.141.59" is chosen which is the latest image of the 3.141.59 series. In some cases we would like to fix the image to a concrete version, e.g. to "3.141.59-20210729".

## Motivation

Once a new image is released this one is taken for testing. This changes the test environment and might lead to test breaks independent of the application test environment itself. This happened with recent chrome drivers.
At least for troubleshooting it would be handy to check if an older image worked before.
So the motivation is on one hand the possibility to repeat and reproduce tests and on the other hand to have better troubleshooting capabilities in case of problems.

## Example

Something like this
```
final BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>()
                ...
                .withImageTag("3.141.59-20210804")
```

**Comment by diemol** [comment]
Seems my answer was not posted... 🤔 
@mjh-c this is already possible, all docker images have a unique tag. Maybe you can clarify a bit more what you mean?

**Comment by diemol** [comment]
Closing as we did not get more info.
