### ISSUE TITLE
Docker + Jenkins failing with error Command duration or timeout

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#137]
Hi,
Since last week , I'm having test failures with Jenkins + Docker Grid setup only.

If I run Docker Grid setup stand alone ( outside Jenkins ) it runs perfectly fine. 

Jenkins + Docker Grid setup failure log

Error while quitting the driver (Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '5fe53996cc22', ip: '172.17.0.17', os.name: 'Linux', os.arch: 'amd64', os.version: '4.0.9-boot2docker', java.version: '1.8.0_45-internal'
Driver info: driver.version: unknown
Command duration or timeout: 16 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: '6wbuildbot.local', ip: '10.165.210.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.bE0SCz}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.71, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=d672ffe2-8561-4d29-9492-e11e5270759b, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

This is how I launch HUB and Nodes

docker run -ti -m 150M --memory-swap 300M --cpu-shares=104 -d -p 4444:4444 --name selenium-hub -e GRID_BROWSER_TIMEOUT=15000 selenium/hub:2.48.2

docker run -ti -m 750M --memory-swap 900M --cpu-shares=460 -d --link selenium-hub:hub -v /dev/shm:/dev/shm selenium/node-chrome:2.48.2 ( 2 times )

Please let me know if I'm doing something wrong here

Thanks in advance.

Regards,
Vikram

**Comment by eyal919** [comment]
+1

**Comment by tommyz0123** [comment]
+1 
using chrome and ff 2.53

**Comment by rohantilekar** [comment]
+1

**Comment by diemol** [comment]
Hi @vikramvi, is this still an issue?

Perhaps sharing the host memory would help?

**Comment by diemol** [comment]
I'll close this issue since we didn't get feedback from the OP. Feel free to reopen when more accurate info is provided.
