### ISSUE TITLE
SE_NODE_MAX_SESSIONS doesn't work as expect

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/docker-selenium#1388]
## 🐛 Bug Report

When I start a standalone service with the following command
docker run -d --name selenium4-chrome -p 4444:4444 -v /dev/shm:/dev/shm -e SE_NODE_MAX_SESSIONS=16 -e SE_NODE_SESSION_TIMEOUT=60 -e SE_OPTS="--grid-url http://myhost.com:4444/wd/hub --max-threads 8" selenium/standalone-chrome:4.0.0-rc-2-prerelease-20210908

What I expect is the max concurrency of browser is 16, but turn out it is 2. It works well on the rc1 docker image and I don't know why it didn't work after upgrade to rc2.

**Comment by diemol** [comment]
Can you please share the commands how you start RC 1 and RC 2, including the logs?

**Comment by link89** [comment]
The command is same. I check the dockerfile and find that a new option is introduced in RC2: `SE_NODE_OVERRIDE_MAX_SESSIONS` need to be set to true to make it work.

**Comment by diemol** [comment]
That option was introduced several versions ago.

In any case, closing as you found the env var needed to override that setting.
