### ISSUE TITLE
Chrome Doesn't Take Proxy Server Option (Capability) Into Account

### ISSUE THREAD

**Issue by Tensho** [SeleniumHQ/docker-selenium#1389]
## 🐛 Bug Report

When I pass `proxy:` option to Selenium Remote WebDriver capability seems like Chrome browser doesn't take it into account.

```
proxy = Selenium::WebDriver::Proxy.new(http: "#{ENV['HTTP_PROXY_HOST']}:#{ENV['HTTP_PROXY_PORT']}")

driver = Selenium::WebDriver.for(
  :remote, url: "http://#{ENV['SELENIUM_HOST']}:#{ENV['SELENIUM_PORT']}/wd/hub",
  capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
    "goog:chromeOptions" => chrome_options,
  proxy: proxy
  )
)
```

I definitely see ChromeDriver is configured correctly, but Chrome doesn't care:

> selenium-chrome_1  |  [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors]}, **proxy: {httpProxy: selenium-chrome:8080, proxyType: manual}**}]
> ...
> selenium-chrome_1  | 09:22:03.334 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 9faf18312226cf44417f9d468d25ae5f, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.131, chrome: {chromedriverVersion: 92.0.4515.107 (87a818b10553..., userDataDir: /tmp/.com.google.Chrome.MILr78}, goog:chromeOptions: {debuggerAddress: localhost:42313}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, **proxy: Proxy(manual, http=selenium...**, se:cdp: ws://172.27.0.3:4444/sessio..., se:cdpVersion: 92.0.4515.131, se:vnc: ws://172.27.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://localhost:7900/websockify, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
> ...

On the other hand, if I specify `HTTP_PROXY`/`HTTPS_PROXY` env var in selenium container, everything works fine – Chrome proxies requests.

## To Reproduce

I've prepared a sample repo for testing – [selenium-docker-issue-proxy-server](https://github.com/Tensho/selenium-docker-issue-proxy-server).

1. Clone git repo:
```
$ git clone git@github.com:Tensho/selenium-docker-issue-proxy-server.git
$ cd selenium-docker-issue-proxy-server
```
2. Look around the Docker composition.
3. Check out git branch with enabled `HTTP(S)_PROXY` env var and disabled `proxy:` option:
```
$ git checkout http_proxy_env_var
```
4. Run Docker composition:
```
$ docker-compose up
```
5. Make sure  HTTP requests to https://github.com run through `mitmproxy` service and have `foo: bar` header:
```
...
mitmproxy_1        | 172.27.0.3:51070: GET https://github.com/ HTTP/2.0
mitmproxy_1        |     sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
mitmproxy_1        |     sec-ch-ua-mobile: ?0
mitmproxy_1        |     upgrade-insecure-requests: 1
mitmproxy_1        |     user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
mitmproxy_1        |     accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
mitmproxy_1        |     sec-fetch-site: none
mitmproxy_1        |     sec-fetch-mode: navigate
mitmproxy_1        |     sec-fetch-user: ?1
mitmproxy_1        |     sec-fetch-dest: document
mitmproxy_1        |     accept-encoding: gzip, deflate, br
mitmproxy_1        |     accept-language: en-US,en;q=0.9
mitmproxy_1        |     foo: bar
mitmproxy_1        |  << HTTP/2.0 200 OK 44.32k
...
^C
```
Everything works as expected – HTTP requests are passed through proxy and headers are modified.

6. Check out git branch with disabled `HTTP(S)_PROXY` env var and enabled `proxy:` option:
```
$ git checkout selenium_driver_proxy_option
```
7. Run Docker composition:
```
$ docker-compose up
```
8. Make sure  HTTP requests to https://github.com **don't** run through `mitmproxy` service and hence don't have `foo: bar` header:
```
...
selenium-chrome_1  | 09:11:39.359 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 134c9b85c67f1b562e592cebb233679f, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.131, chrome: {chromedriverVersion: 92.0.4515.107 (87a818b10553..., userDataDir: /tmp/.com.google.Chrome.CbXSg5}, goog:chromeOptions: {debuggerAddress: localhost:44645}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(manual, http=selenium..., se:cdp: ws://172.27.0.3:4444/sessio..., se:cdpVersion: 92.0.4515.131, se:vnc: ws://172.27.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://localhost:7900/websockify, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
client_1           | https://github.com/
selenium-docker-issue-proxy-server_client_1 exited with code 0
^C
```

## Expected behavior

Chrome inside `selenium/standalone-chrome` container should proxy requests when Selenium Remote WebDriver is [configured respectively](https://www.selenium.dev/documentation/webdriver/http_proxies/).

```
Selenium::WebDriver.for(
  :remote, url: "http://#{ENV['SELENIUM_HOST']}:#{ENV['SELENIUM_PORT']}/wd/hub",
  capabilities: Selenium::WebDriver::Remote::Capabilities.chrome("goog:chromeOptions" => { ... }, proxy: proxy)
)
```

## Test script reproducing this issue (when applicable)

https://github.com/Tensho/selenium-docker-issue-proxy-server

## Environment

OS: **macOS Big Sure 11.3**
Docker-Selenium image version: **selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804** (from DockerHub)
Docker version: 20.10.8
Docker-Compose version: 1.29.2, build 5becea4c
Exact Docker command to start the containers: `docker-compose up`

**Comment by diemol** [comment]
It is not that Chrome does not care about the proxy, basically it's what you said here:
>On the other hand, if I specify HTTP_PROXY/HTTPS_PROXY env var in selenium container, everything works fine – Chrome proxies requests.

If you want to use a proxy, you need to let the container know about it, otherwise Chrome will try to use a proxy url it cannot reach.

**Comment by Tensho** [comment]
@diemol Thank you for checking this so quickly 🙇 I don't understand this part "Chrome will try to use a proxy url it cannot reach". Selenium webdriver configuration specifically describes proxy host+port, which is passed downstream to the Chrome execution command as `--proxy-server` flag value. All services in Docker composition are reachable by their names. Proxy service is referenced at Selenium side by the respective `docker-compose` service name. Please could you elaborate on the reachability moment?

**Comment by diemol** [comment]
Right, but the Docker container has no proxy configured, therefore Chrome cannot reach it.

**Comment by Tensho** [comment]
I'd expect **explicit** proxy configuration (with `Selenium::WebDriver::Remote::Capabilities.chrome( ... , proxy: proxy)`) should configure Chrome instance to work with target proxy server the same way as **implicit** proxy configuration with env vars (`HTTP(S)_PROXY`). In my head these 2 methods are alternatives, not complement.

![image](https://user-images.githubusercontent.com/892721/134220234-cdf1e66d-ad5b-4f1e-b7da-cb35dcf560d2.png)

**Comment by diemol** [comment]
Not really. A docker container has its own network, it is a completely standalone operating system and it is not getting any network properties from the host system. Therefore you need to tell the container which proxy to use by setting the env var. It is simply how the container works.

**Comment by Tensho** [comment]
@diemol I reproduced the issue without Docker, running Chrome locally. Here is a code snippet diff: 
```diff
- proxy = Selenium::WebDriver::Proxy.new(http: "#{ENV['HTTP_PROXY_HOST']}:#{ENV['HTTP_PROXY_PORT']}")
- 
- driver = Selenium::WebDriver.for(
-   :remote, url: "http://#{ENV['SELENIUM_HOST']}:#{ENV['SELENIUM_PORT']}/wd/hub",
-   capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
-    "goog:chromeOptions" => chrome_options,
-     proxy: proxy
-   )
- )
+ proxy = Selenium::WebDriver::Proxy.new(http: "localhost:8080")
+ 
+ driver = Selenium::WebDriver.for(
+   :chrome,
+   capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
+     proxy: proxy
+   )
+ )
```
The `mitmproxy` process is bound to `localhost:8080`. When I run ruby script with Selenium WebDriver – nothing goes within proxy service. When I send HTTP request with `curl` – it goes within proxy service.
```
$ mitmdump
Proxy server listening at http://*:8080
[::1]:64854: client connect
[::1]:64854: server connect github.com:443 (140.82.121.3:443)
[::1]:64854: GET https://github.com/ HTTP/2.0
 << HTTP/2.0 200 OK 233.34k
[::1]:64854: client disconnect
[::1]:64854: server disconnect github.com:443 (140.82.121.3:443)
```
```
$ curl -I --proxy localhost:8080 https://github.com
HTTP/1.1 200 Connection established

HTTP/2 200
server: GitHub.com
date: Thu, 23 Sep 2021 12:48:06 GM
...
```
---
MacOS: 11.3
Selenium WebDriver: 4.0.0.rc1
ChromeDriver: 92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634})
Google Chrome: 93.0.4577.82
