### ISSUE TITLE
Documentation related to connecting through VNC needs update

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#139]
current
In case you have RealVNC binary vnc in your path, you can always take a look, view only to avoid messing around your tests with an unintended mouse click or keyboard interrupt:

$ ./bin/vncview 127.0.0.1:49160
If you are running Boot2Docker on OS X then you already have a VNC client built-in. You can connect by entering vnc://<boot2docker-ip>:49160 in Safari or Alfred.

expected

Install RealVNC and goto Safari browser and load URL 

vnc://<docker vm IP Address>:<49338>

Enter password "secret"

**Comment by chadxz** [comment]
If you're using boot2docker on osx, the host will not actually be localhost, but will be the ip address of the docker vm, which can be obtained via `$docker-machine ip $(docker-machine active)`

**Comment by vikramvi** [comment]
One more related note

I found below quite confusing to understand

( https://github.com/SeleniumHQ/docker-selenium )
docker run -d -P -p <port4VNC>:5900 --link selenium-hub:hub selenium/node-chrome-debug:2.53.1

instead liked the approach

( https://github.com/SeleniumHQ/docker-selenium/tree/master/NodeChromeDebug )
docker run -d -P --link selenium-hub:hub selenium/node-chrome-debug
docker port <container-name|container-id> 5900

vnc://xxx.yyy.z.aa:12345/   on safari browser

**Comment by diemol** [comment]
Hi @vikramvi,

I didn't really understand what you want to achieve... Could you please elaborate a bit more?

**Comment by diemol** [comment]
I'll close this issue since we didn't get feedback from the OP. Feel free to reopen when more accurate info is provided.
