### ISSUE TITLE
SE_SESSION_RETRY_INTERVAL ENV doesn't seem to be taking

### ISSUE THREAD

**Issue by kmcrawford** [SeleniumHQ/docker-selenium#1394]
## 🐛 Bug Report

SE_SESSION_RETRY_INTERVAL ENV doesn't seem to be taking

## To Reproduce

![image](https://user-images.githubusercontent.com/40531/133320306-a10e7684-e79c-48d4-9376-38549765d669.png)

![image](https://user-images.githubusercontent.com/40531/133320413-a0754ca8-807a-4327-9fe7-f3215831488c.png)

I actually added to all deployments as it wasn't working for the above 2.

## Expected behavior

In the chrome node logs I see it is still trying every 5 seconds. So I assume SE_SESSION_RETRY_INTERVAL isn't taking.

```
19:05:55.604 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "0e2bf2a53a2df2c0dd3999115f4a676c","eventTime": 1631646355603467935,"eventName": "Max session count reached","attributes": {"current.session.count": 1,"logger": "org.openqa.selenium.grid.node.local.LocalNode","max.session.count": 1,"session.request.capabilities": "Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu]}}","session.request.downstreamdialect": "[W3C, OSS]"}}

19:06:00.611 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "0e2bf2a53a2df2c0dd3999115f4a676c","eventTime": 1631646360610608450,"eventName": "Max session count reached","attributes": {"current.session.count": 1,"logger": "org.openqa.selenium.grid.node.local.LocalNode","max.session.count": 1,"session.request.capabilities": "Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu]}}","session.request.downstreamdialect": "[W3C, OSS]"}}
```

## Environment
Using tag 4.0.0-rc-2-prerelease-20210908 running in kubernetes GKE v1.19.12-gke.2101

**Comment by diemol** [comment]
You are right, this value is read properly but we are not using it in the Distributor. I am fixing this in the upstream code and we will do another pre-release tomorrow with this fix.

**Comment by diemol** [comment]
This got closed as I linked this issue with the commit, but the release will be done tomorrow.

**Comment by diemol** [comment]
Prerelease will be done when [this](https://github.com/SeleniumHQ/docker-selenium/pull/1395) gets merged.
