### ISSUE TITLE
Node chrome running on windows 10 doesn't connect to docker swarm running on Linux machine

### ISSUE THREAD

**Issue by sumeet-kushwah** [SeleniumHQ/docker-selenium#1397]
## 🐛 Bug Report

We have a Redhat server running as a docker swarm manager and windows 10 machines are added as the swarm workers. Node chrome's initiated on windows machine are stuck at "Sending registration event..." and selenium grid shows no nodes are registered.

### Docker file

version: '3.7'

services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210915
    shm_size: 2gb
    ports:
      - target: 5555
        published: 5555
        mode: host
    environment:
      - SE_EVENT_BUS_HOST=<Manager_RedHat_Linux_Server_IP_Address>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
    image: selenium/hub:4.0.0-rc-2-prerelease-20210915
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    deploy:
      placement:
        constraints:
          - "node.role==manager"

## Expected behavior

Nodes running on the worker machines should connect to the grid.

## Test script reproducing this issue (when applicable)

Given swarm manager is running on the Linux machine
And Swarm workers are running on the windows 10 machines
When the above docker file is deployed as stack
Then Selenium grid should start on the Linux machine
And Selenium Node chrome should start on the windows 10 worker machines
And Selenium grid should show all nodes as connected 

## Environment

OS: 
Windows 10 for swarm workers and Redhat for swarm manager
Docker-Selenium image version:  4.0.0-rc-2-prerelease-20210915

Docker version:
Linux : Docker version 20.10.8, build 3967b7d
Windows 10 : Docker version 20.10.8, build 3967b7d
 
Docker-Compose version 
Windows 10 : Docker Compose version v2.0.0-rc.2
Linux : docker-compose version 1.25.5, build 8a1c60f6

Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): 

Docker swarm init  ##on Redhat linux machine##
##Join the worker nodes on the windows 10 machine 
## Then run the below command on the Linux machine to deploy the dockerfile provided above
docker stack deploy -c docker-compose-v3-swarm.yml grid

**Comment by diemol** [comment]
Can you share the logs of the hub and the nodes that get stuck with "Sending registration event..."?

Also, can the hub reach the nodes? The hub needs to check the status endpoint of the node to complete the registration.

**Comment by diemol** [comment]
Closing as we did not get more information.
