### ISSUE TITLE
Change Default File Permissions for Seluser

### ISSUE THREAD

**Issue by therealdjryan** [SeleniumHQ/docker-selenium#1398]
## 🚀 Feature Proposal

It would be helpful if the browser images included umask so the default file permissions for the 'seluser' user can be changed. It would be even better if /etc/profile included `umask 002` 

## Motivation

I am running docker-selenium in podman. Our tests depend heavily on operations such as downloading file templates from sites, updating them and re-uploading. A major pain point is because the user running tests has a different userid and groupid. Given the default file permission for seluser is 644 our tests can't directly write to downloaded files. The most straightforward way to handle this is to map the local user to seluser, but I have not been successful doing this. I propose the addition of `umask 002` to /etc/profile (in NodeBase/Dockerfile?) in order for the default permissions for files become 664. At this time umask is not included in the distribution on the docker image so that would need to be included as well.

## Example

Please provide an example for how this feature would be used.

**Comment by therealdjryan** [comment]
Actually, doing the following will get me what I want but in a less draconian way:
```
#!/bin/bash
# Note: exec -a below is a bashism.
umask 002
exec -a "$0" "/opt/google/chrome/google-chrome-base" --no-sandbox "$@"
```
I'm happy to do make the changes myself if you approve this sort of change.

**Comment by diemol** [comment]
Fixed by the merged PR. Will be part of the next release.
