### ISSUE TITLE
Node registration is occasionally delayed many minutes

### ISSUE THREAD

**Issue by c0nstructer** [SeleniumHQ/docker-selenium#14]
Status 13 keeps popping on selenium grid after some time of usage. Been using webdriverio, server throws error that timeout expired. Help, anyone?

**Comment by mekhami** [comment]
I had this issue when spinning up my grid earlier. This fix solved it, but I was wondering if I need to open an issue elsewhere to see about getting this resolved, because in selenium-standalone-server-2.45 it's not.

**Comment by dhruvbhatia** [comment]
I'm experiencing the same issue running `docker-selenium` on AWS EC2 instances (tested both `Amazon Linux AMI 2015.03 (HVM) using Amazon's Docker release` and `Ubuntu Server 14.04 LTS (HVM) using Docker 1.7`).

The `docker run -v /dev/urandom:/dev/random ...` solution helps a little (selenium progresses further in my queue), but things still eventually freeze up given enough time. What's weird is the entropy of the host system appears fine whenever the freeze occurs.

Has anybody experienced the same thing? For reference my grid is running 20 Chrome instances and my queue freezes after about ~1500 sessions.

**Comment by lucacri** [comment]
I spent the last 48 hours trying to fix this problem too!
@eugene-dounar 's suggestion to install `haveged` worked wonderfully. THANK YOU!

**Comment by nirvdrum** [comment]
@mekhami The issue is induced by the number of times random data is read (e.g., SecureRandom) and the rate at which /dev/random is being drained on a given machine.  It may very well be that your selenium-server just isn't as active or isn't contending with as much.  Unfortunately, it's a thorny issue.

**Comment by RoryHunter** [comment]
FYI, I just fixed an issue with a selenium docker container hanging during startup by setting the container environment variable JAVA_OPTS to "-Djava.security.egd=file:/dev/./urandom", which the container entrypoint script respects.
