### ISSUE TITLE
Push containers to ghcr?

### ISSUE THREAD

**Issue by gazal-k** [SeleniumHQ/docker-selenium#1401]
## 🚀 Feature Proposal

Please push these container images to ghcr.

## Motivation

ghcr unlike docker hub does not rate limit image pulls.

**Comment by diemol** [comment]
I agree that the pull rate limit in Docker is not ideal but 600 pulls every 6 hours for authenticated (free) users is not that bad.

In addition, we prefer to keep things on a single place, as using a new registry would demand to push all images again and ask users to change their pull scripts, which would be a massive change. 

For now, we are not considering this option, but if things get much more restrictive with the rate limits, we will definitely have a look again.
