### ISSUE TITLE
Remote Desktop instead of VNC?

### ISSUE THREAD

**Issue by alexkogon** [SeleniumHQ/docker-selenium#141]
Hi folks,

We use Remote Desktop to connect to our Linux VMs instead of VNC, it shouldn't be too difficult to support via the Debug Docker images...is this already there or is there any interest?

**Comment by elgalu** [comment]
You mean through [xrdp](https://github.com/neutrinolabs/xrdp) ? Is there any advantage over VNC? like better performance or increased security? or is just to avoid installing a VNC client on Windows?

**Comment by alexkogon** [comment]
According to this guy (whose posts I've read often in the past and seems to know what he is talking about), Remote Desktop is much more performant than VNC: http://blog.codinghorror.com/vnc-vs-remote-desktop/ and is the best solution for using a remote computer or VM as a workstation (I run it both for Linux and Windows often and it works great).

That said, it is also installed by default on Windows (and widely available for other platforms), and for many of us is in frequent use for connecting to Windows VMs or remote Windows machines, so saves the headache of having to use two different programs to connect (and remember which to use for what machine).

I'm not saying to ditch VNC, I'm just saying it would be nice to have both options.

Thanks

**Comment by elgalu** [comment]
The arguments summarized at codinghorror blog post only apply when the remote desktop server is on Windows.

**Comment by alexkogon** [comment]
Fair enough, I don't really know; honestly, I haven't used VNC in probably a decade, but I do connect to Linux with RDP all the time. The remaining argument is valid however. Is there any particular reason supporting both would be a bad thing?

**Comment by Vanuan** [comment]
Windows' RDP is the like XOrg over SSH, but only for one application: http://unix.stackexchange.com/questions/1960/differences-between-vnc-and-ssh-x

**Comment by ddavison** [comment]
closing this.  VNC will stay.  using something like RDP is windows specific.  VNC at least keeps it generic.

**Comment by cypa** [comment]
no, RDP is much more convenient even with linux client ... I'd treat VNC as obsolete to RDP and SPICE

**Comment by elgalu** [comment]
I guess someone needs to give it a try to the RDP linux server, perhaps by installing [xrdp](https://github.com/neutrinolabs/xrdp) and see [how it goes in a Dockerfile](https://github.com/SvenDowideit/dockerfiles/tree/master/xrdp#step-1-the-ms-remote-desktop-server) , do some performance comparison vs VNC so a decision can be made.

**Comment by alexkogon** [comment]
I've done it long ago and it works fine, never performance tested it
though. Didn't seem to be much interest and like all Selenium related
topics the community is too much like kindergarten to bother to participate.

Btw certainly are good RDP clients for Mac too, with Windows it is
integrated so easy and convenient...

Also btw Leo got Docker with Windows inside running fine for the grid the
problem is that (at least with the Virtual Box implementation we did) it
requires the Linux headers so is strongly bound to the Kernel and must be
produced for each version of the Kernel it is to be used on...I was hoping
to create a general version and maybe it is possible with a different VM
but I already had one that solved my problem and haven't had the time to
invest yet.

**Comment by elgalu** [comment]
Cool @alexkogon! how much space does RDP-in-docker adds to the image? I read is 500mb.

Regarding IE inside docker, your experience is very useful, the kernel hard dependency might be something acceptable for users that really want this. How much time does it take for the IE browser to start from the moment do you `docker run .. ie ..` until is able to accept tests the first time? I see the difference is that with Chrome & Firefox you don't need to boot the OS but with VBox inside docker I'm guessing Windows needs to boot, or is it able to preserve the state in hibernation mode somehow?

**Comment by alexkogon** [comment]
Hi Leo

Give me a few days and I'll get you the answers to your questions :)

Hope to see you again for some beers in a few months when the sun shines
again...if you are still around!
