### ISSUE TITLE
Way to close open file dialog 

### ISSUE THREAD

**Issue by kaylezhangzhaoLin** [SeleniumHQ/docker-selenium#1411]
## 🚀 Feature Proposal
Way to close open file dialog

## Motivation
I use selenium in ubuntu headless.
Is there any way to close "open file" dialog at selenium?
The input tag is only visible when the system pop-up window pops up.
l have to close the file dialog.

## Example

![5a1af40f428723d7bd49426aafedfab](https://user-images.githubusercontent.com/85552832/135414374-a61b1e68-5e78-45eb-8439-5c9a524e6fed.png)
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.FileDetector;
import org.openqa.selenium.remote.LocalFileDetector;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Screen;

import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
//from tkinter import *
//from tkinter.filedialog import askopenfilename
/**
 * @Classname test
 * @Date 9/18/2021 4:16 PM
 * @Description TODO
 */
public class Test {

    public static void main(String[] args) {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setVersion("93.0");
        capabilities.setBrowserName("chrome");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", true);
        RemoteWebDriver driver = null;
        try {
             driver = new RemoteWebDriver(
                    URI.create("http://165.88.124.96:4444/wd/hub").toURL(),
                    capabilities
            );
            FileDetector localFileDetector = new LocalFileDetector();
            driver.setFileDetector(localFileDetector);
            driver.get("http://165.88.125.153");
            sleep(3000);
            driver.findElement(By.name("username")).sendKeys("auto_sld");
            sleep(2000);
            driver.findElement(By.name("password")).sendKeys("auto_sld");
            sleep(2000);
            driver.findElement(By.xpath("//div[@class='ng-binding']")).click();
            sleep(2000);
            driver.findElement(By.xpath("//span[text()='Analytics']")).click();
            sleep(2000);
            driver.findElement(By.xpath("//div[text()='Browse local file...']")).click();
            sleep(2000);
            driver.findElementById("AddDataFromFile").sendKeys("/opt/docker/fileDownloadLocation/test.xlsx");
            sleep(2000);
            Screen screen = new Screen();
            screen.click("/opt/docker/fileDownloadLocation/close.png");
            sleep(5000);
            driver.close();
            driver.quit();

//            root = Tk()
//            root.withdraw()
//            file_path = askopenfilename()
//            root.destroy()
//            Call root.update() before askopenfilename()

        } catch (Exception e) {
            if(driver != null){
                driver.close();
                driver.quit();
                e.printStackTrace();
            }

        }
    }
    public void fileUpload (String path) throws AWTException {
        StringSelection strSelection = new StringSelection(path);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(strSelection, null);

        Robot robot = new Robot();

        robot.delay(300);
        robot.keyPress(KeyEvent.VK_ENTER);
        robot.keyRelease(KeyEvent.VK_ENTER);
        robot.keyPress(KeyEvent.VK_CONTROL);
        robot.keyPress(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_CONTROL);
        robot.keyPress(KeyEvent.VK_ENTER);
        robot.delay(200);
        robot.keyRelease(KeyEvent.VK_ENTER);
    }
    public static  void sleep(long time){
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
// ########################### pom ################################
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>UITest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <webdriver.driver>remote</webdriver.driver>
        <serenity.version>2.2.12</serenity.version>
        <serenity.jbehave.version>1.46.0</serenity.jbehave.version>
        <mvn.surefire.version>3.0.0-M5</mvn.surefire.version>
        <mvn.failsafe.version>3.0.0-M5</mvn.failsafe.version>
        <mvn.compiler.version>3.8.0</mvn.compiler.version>
    </properties>
    <dependencies>

        
        <dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.vidstige</groupId>
                    <artifactId>jadb</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>com.nativelibs4java</groupId>
            <artifactId>bridj</artifactId>
            <version>0.7.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>2.44.0</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${mvn.surefire.version}</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${mvn.failsafe.version}</version>
                
                <configuration>
                    <includes>
                        <include>**/main/Main.java</include>
                        
                    </includes>
                    <argLine>-Xmx512m</argLine>
                    <systemPropertyVariables>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver>
                    </systemPropertyVariables>
                    <parallel>all</parallel>
                    <forkCount>4</forkCount>
                    <reuseForks>false</reuseForks>
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${mvn.compiler.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by diemol** [comment]
Selenium WebDriver cannot interact with that window because it is part of the operating system, it is not part of the web page.

If you need to download a file without a prompt with Chrome, check the `Set download directory` at [Common use cases](https://chromedriver.chromium.org/capabilities#h.p_ID_64).

**Comment by kaylezhangzhaoLin** [comment]
Thank you very much for your answers.

Do you know that the following operation can prevent the pop-up of the system pop-up window (operating system)?



Block pop-up windows

By default, ChromeDriver configures Chrome to allow pop-up windows. If you want to block pop-ups (i.e., restore the normal Chrome behavior when it is not controlled by ChromeDriver), do the following:

ChromeOptions options = new ChromeOptions();

options.setExperimentalOption("excludeSwitches",

     Arrays.asList("disable-popup-blocking"));

**Comment by kaylezhangzhaoLin** [comment]
Sorry, this is a pop-up window for uploading files.

**Comment by diemol** [comment]
That is an operating system dialog, and Selenium cannot interact with those. That is why I pointed the alternative above.

**Comment by kaylezhangzhaoLin** [comment]
Excuse me.
Sorry, I set a ban on pop-ups on the chrome of windows, he can ban non-system pop-ups. , I still don’t understand how to disable the pop-up window for uploading files.
![c94d3bad03d93a38f0e4bb165a90f92](https://user-images.githubusercontent.com/85552832/135480248-3ac22063-6152-4f8d-a3b3-a7a552ea6ff6.png)
![ee2c3ad0d5c1e3a021b8ed23245ce97](https://user-images.githubusercontent.com/85552832/135480484-50be1f52-d1a1-44ad-a17e-3877b95f369a.png)

**Comment by diemol** [comment]
If you need help, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by kaylezhangzhaoLin** [comment]
OK,　Thanks.

**Comment by kaylezhangzhaoLin** [comment]
I have read the post about headless file upload, and the post about how to close the system pop-up window has not been solved. I think this problem cannot be solved for the time being. Thank you for your reply above.

**Comment by kaylezhangzhaoLin** [comment]
I have an idea. I don't know if it is possible or not. Do you think the following ideas are feasible?
![H9)TYL{T$93{ W}9AM_40J1](https://user-images.githubusercontent.com/85552832/136194737-aa07d51e-26e4-4db1-a230-b66dce24bb3a.png)
When the file pop-up window pops up, a process will be created in the task manager provided by chrome. If I can kill the process, I can close the window. I can kill the process manually. Do you know that you can close the process with selenium?

**Comment by kaylezhangzhaoLin** [comment]
I look forward to your reply, no matter whether the idea is feasible or not.
