### ISSUE TITLE
Selenium grid unable to load Nodes

### ISSUE THREAD

**Issue by Chandrakala-KH** [SeleniumHQ/docker-selenium#1413]
## 🐛 Bug Report

I have deployed standalone chrome in openshift(4.0.0-rc-2-prerelease-20210923).

At the beginning - selenium grid was working fine and after many tests, Now selenium grid is giving 500 error and unable to load node.

Observation:
Selenium grid was working fine till 3 to 4 times deployment in openshift namespace .
For the 5th time deployment in the same namespace - grid is failing to fetch node

Please let me know if any session cached or in deployment yaml file any environment variable needs to be added

![image](https://user-images.githubusercontent.com/42860183/135834700-46cc46c4-775c-4381-b149-8a92300b7d41.png)

## To Reproduce

Attaching deployment yaml , same thing needs to be deployed to openshift 5 to 6 times, 7th time grid fail to load node.
oc apply -f deployment.yaml
` 
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/standalone-chrome:4.0.0-rc-2-20210930
        ports:
          - containerPort: 4444
          - containerPort: 5900
          - containerPort: 7900
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port1
  - port: 5900
    targetPort: 5900
    name: port2
  - port: 7900
    targetPort: 7900
    name: port3
  selector:
    app: selenium-hub
  sessionAffinity: None
  type: ClusterIP
 
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: selenium-hub
  name: selenium-hub
spec:
  host: selenium-hub
  port:
    targetPort: 4444
  to:
    kind: Service
    name: selenium-hub
    weight: 100
  wildcardPolicy: None
 
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: selenium-hub
  name: selenium-vnc
spec:
  host: selenium-vnc
  port:
    targetPort: 7900
  to:
    kind: Service
    name: selenium-hub
    weight: 100
  wildcardPolicy: None
 `
## Expected behavior

Selenium grid must load chrome (standalone `chrome` image)

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Hard to say what is going on without any logs. Could you please post the logs of each component?

**Comment by Chandrakala-KH** [comment]
From the logs, I dont see any errors, One thing have observed is-  earlier i used to see jq queries with nodesinfo and session information in the logs. But now could not see any node info in the appln logs

Grid is unable to load node info , not sure if any environment variable needs to be passed  
could you pls confirm - Standalone chrome (4.0.0-rc-2-prerelease-20210923)works in Openshift?

Kindly let me know if am missing anything in the abouve code snippet provided earlier.

Below the startup logs

Starting Selenium Grid Standalone...
19:19:29.874 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
19:19:29.886 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
19:19:31.470 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
19:19:31.579 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "92.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
19:19:31.613 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
19:19:31.662 DEBUG [GridModel.add] - **Adding node** with id d250c788--8fe08ca2ef48 and URI http://x.x.x.x:4444
19:19:31.667 DEBUG [LocalDistributor.lambda$asRunnableHealthCheck$3] - Running health check for d250c788-465a-40f8-************
19:19:31.668 INFO [LocalDistributor.add] - **Added node** d250c788-***** at http://x.x.x.x:4444. Health check every 120s
19:19:31.671 DEBUG [LocalDistributor.lambda$asRunnableHealthCheck$3] - Health check result for d250c78**** was UP
19:19:31.678 INFO [GridModel.setAvailability] - **Switching nod**e d250c788****** (uri: http://x.x.x.x:4444 ) from DOWN to UP

**Comment by diemol** [comment]
Maybe you can get more information from the pods, is something getting stuck? Why are the pods not starting?

**Comment by Chandrakala-KH** [comment]
Please find below key points,

Post deployment of standalone chrome to open shift, Pod is up and running
From the pod logs, could see selenium grid started and added node as well

But from browser when I hit route url for 4444 grid, getting error " error loading nodes from the grid"

But Which was working with same deployment configuration for 4 to 5 times when I deploy in the same open shift namespace.



Observations,
If I deploy same deployment yaml to other open shift namespace for 3 to 4 times selenium grid is working fine even now, for the 5th time getting 500 error.

Not sure if it's cache session issue, 
Tried cleanup open shift namespace and redeploy ,still no luck.

**Comment by diemol** [comment]
From the information you provide, I cannot really say what is wrong. I'd suggest to analyse the logs when the deployment fails, probably run the Grid on debug mode and analyse the logs. So far we have not spent so much time deploying the Grid to Kubernetes, so we do not have much insights to offer.

I will leave this open in case someone can give ideas on what to troubleshoot.

**Comment by diemol** [comment]
I'll close this because no more information was provided and there is no pending action from our side. Feel free to open a new issue if more information is available.
