### ISSUE TITLE
Websocket request is failing

### ISSUE THREAD

**Issue by GeorgeMarinM** [SeleniumHQ/docker-selenium#1419]
## 🐛 Bug Report

Hello,

So I'm testing an application that opens an editor that is managed through WebSocket connections. For a long time It 've been using Firefox 63-66 inside a docker container (an image that I downloaded 2-3 years ago from this repository), but today I wanted to update the Firefox version and I've downloaded the latest release (selenium/standalone-firefox-debug) and I noticed that the WebSocket requests are not working any longer. I'm getting this error:

Firefox can't establish a connection to the server at wss://{SERVER}/ooe/document/{fileId};jsessionid=XXXXX

Is strange cause if I switch back to image selenium/standalone-firefox-debug:3.141.59-mercury, it's working as it should. Do you know anything regarding an issue with this type of WebSocket connection?

If it's needed I can provide more details, but I'm thinking this can be reproducible 100% on the Live version of the application.

Thank you,
George

**Comment by diemol** [comment]
There has been tons of changes in Firefox during the last 2-3 years. This project only wraps Firefox and other browsers into Docker containers, we do not really troubleshoot issues with the browser itself.

Most likely a change in how Firefox handles security is affecting you. Maybe you can go over the Firefox [release notes](https://www.mozilla.org/en-US/firefox/releases/) to find what is causing this and find ways to improve the application you are using.
