### ISSUE TITLE
403 when accessing container URL

### ISSUE THREAD

**Issue by niksy** [SeleniumHQ/docker-selenium#142]
I’m following instructions on how to install standalone version of Firefox.

``` sh
docker run -d -p 4444:4444 selenium/standalone-firefox
```

Since I’m on OS X (10.11.2), accessing Selenium from host is achieved not by `0.0.0.0:4444`, but by using IP from `docker-machine ip dev`, in my case `192.168.99.100`.

When I open `192.168.99.100:4444` inside browser, I get the following page:

![screen shot 2016-01-05 at 10 11 03](https://cloud.githubusercontent.com/assets/389286/12111318/a7b3008e-b394-11e5-9ffd-ee9b4e6c4a88.png)

Am I doing something wrong?

**Comment by diemol** [comment]
@niksy if you are using the standalone image, you need to go to http://192.168.99.100:4444/wd/hub/static/resource/hub.html (localhost in case you are using a more recent version of docker).

**Comment by ddavison** [comment]
closing. feel free to reopen if this is still an issue.
