### ISSUE TITLE
[Dynamic grid rc3] opt:selenium:assets access denied exception

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1421]
## 🐛 Bug Report

[Dynamic grid rc3] opt:selenium:assets access denied

![image](https://user-images.githubusercontent.com/44854923/137058709-dace6598-28a7-43d4-8b7f-83a04e281e04.png)

## To Reproduce

1. docker-compose-v3-dynamic-grid.yml  download
2. docker-compose -f  docker-compose-v3-dynamic-grid.yml  up
3. remote webdrvier connect to selenium docker hub

## Expected behavior

connect success

## Test script reproducing this issue (when applicable)

Opt/selenium/assets folder access denied error when running dynamic grid

![image](https://user-images.githubusercontent.com/44854923/137058680-ef8b2823-3bf7-4982-9936-720472b95b06.png)

## Environment

OS: ubuntu & centOs
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
This happens if the mounted directory has some permission restriction. What you can do to fix it is to create the directory in advance and give write permissions to all users or narrow it down to the same user id that is used inside the container.

**Comment by diemol** [comment]
Closing as no more comments were made.
