### ISSUE TITLE
Kubernetes HPA kills browser nodes running tests instead of free ones

### ISSUE THREAD

**Issue by prashanth-volvocars** [SeleniumHQ/docker-selenium#1423]
### What happened?

So we are using the KEDA Selenium Grid scaler in our Kubernetes setup to scale our browser nodes up and down based on testing requests pending in queue. The problem we are facing is when the browser nodes are being scaled down by HPA, It ends up killing the nodes that are running the tests currently instead of free ones. Is this something that could be handled with SIGTERM signal handler to wait until the current running session is ended?.

### Command used to start Selenium Grid with Docker

```shell
We are using the Kubernetes example from the repo
```

### Relevant log output

```shell
[firefox 93.0 linux #1-9] script timeout: Unable to execute request for an existing session: java.util.concurrent.TimeoutException
[firefox 93.0 linux #1-9] script timeout: Unable to execute request for an existing session: java.util.concurrent.TimeoutException
[firefox 93.0 linux #1-9] Build info: version: '4.0.0', revision: '3a21814679'
[firefox 93.0 linux #1-9] System info: host: 'selenium-hub-58c74db56b-d9mh9', ip: '172.24.80.41', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1056-azure', java.version: '11.0.11'

The above is one of example where the test started to execute on firefox node and the node was killed by Kubernetes HPA. the test failed with the above error
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.0.0-20211013

**Comment by diemol** [comment]
The Nodes have different useful endpoints, see https://www.selenium.dev/documentation/grid/advanced_features/grid_endpoints.

You can use `/status` to monitor if a session is running, or `/drain` to stop the server when no more sessions are running.

Feel free to share your learnings, and also your HPA config so other ones can learn!

**Comment by prashanth-volvocars** [comment]
The problem with HPA is it just sends a SIGTERM signal to the running pod and we cannot control which pod it selects to remove. Using the endpoint would not be a viable solution in this case

**Comment by prashanth-volvocars** [comment]
@diemol That was lighting fast to close an issue. I would really like to share my findings but this issue is making the whole progress useless. Any help in this direction would be really appreciated.

**Comment by diemol** [comment]
I am not that familiar with HPA yet, but if you feel this could be added to the shutdown process of the container, feel free to send us a PR for that and we can go over the changes.

I closed the issue because it was described as a bug, which is not really the case. Maybe this is more a feature request? 

However, I would double check if you can downscale based on given conditions.

**Comment by prashanth-volvocars** [comment]
@diemol How does the dynamic grid function? I mean how does it throw away container when session request ends.

**Comment by diemol** [comment]
It uses the docker API to start and stop containers.

**Comment by prashanth-volvocars** [comment]
How does it determine that container running test is done and can be tossed off

**Comment by diemol** [comment]
Because the container is stopped after the session is stopped. 

For more questions, please join our Slack/IRC/Matrix channels, see the links at https://www.selenium.dev/support/
