### ISSUE TITLE
[🚀 Feature]: Provide standalone docker image for Chrome 95

### ISSUE THREAD

**Issue by tobiasstadler** [SeleniumHQ/docker-selenium#1429]
### Feature and motivation

Could you please provide a (standalone) docker image for Chrome 95.

### Usage example

Testing with latest Chrome

**Comment by diemol** [comment]
Released https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-20211025

**Comment by tobiasstadler** [comment]
Thank You!
