### ISSUE TITLE
The standalone debug chrome/firefox image isn't forwarding the vnc ports

### ISSUE THREAD

**Issue by atrioom** [SeleniumHQ/docker-selenium#143]
Hey there,
I setup docker-machine (0.5.4) on my OSX (10.11) and used `docker run -d -p 4444:4444 selenium/standalone-chrome-debug` to run the container.
After that there should be a port on my host machine forwarded to 5900 to guest, right? `docker port <container-id>`  only gives `4444/tcp -> 0.0.0.0:4444` though. Is my assumption correct, that there should be an open port to 5900 (vnc server)?

**Comment by alexkogon** [comment]
Yup glad it is not just me...or am I doing something wrong?

[~]$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
2148b3622072        selenium/node-chrome-debug    "/opt/bin/entry_point"   9 minutes ago       Up 9 minutes        5900/tcp            romantic_cray
e8cbf99532c7        selenium/node-firefox-debug   "/opt/bin/entry_point"   10 minutes ago      Up 10 minutes       5900/tcp            jovial_noyce
[~]$ docker port jovial_noyce 5900
Error: No public port '5900/tcp' published for jovial_noyce
[~]$ docker port romantic_cray 5900
Error: No public port '5900/tcp' published for romantic_cray

**Comment by alexkogon** [comment]
BTW as you can see from my console output this applies to both Firefox and Chrome

**Comment by alexkogon** [comment]
Sorry, I just figured out you have to explicitly map the port with the -p XXXX:5900 flag to docker when you launch the node

**Comment by elgalu** [comment]
Thanks @alexkogon indeed that part was missing `-p 5900:5900`

**Comment by alexkogon** [comment]
btw (of course) if you run multiple instances on a single machine you will need to give them each a different port #...
