### ISSUE TITLE
[🚀 Feature]: Example on how to run Dynamic Grid in different VMs

### ISSUE THREAD

**Issue by alok773968** [SeleniumHQ/docker-selenium#1438]
### Feature and motivation

Hi, As discussed in forum.

Can we get an example on how to setup dynamic grid on multiple VMs using Docker. suppose if we have 4 VMS and one we are using for hub and 3 we are using for nodes(node1 node2 node3). How we can achieve this. please help in creating this feature. if we can get some readme example for this then it will help us.

Thanks a lot in advance. You guys are amazing!!!

### Usage example

I will use this feature to setup dynamic grid on multiple node where i have 4 VMs using Docker.

**Comment by alok773968** [comment]
any update?

**Comment by namilkimfree** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/1408

No other VMs are registered. That seems to be the problem.

**Comment by diemol** [comment]
This has been answered in this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/1403#issuecomment-959134307).
