### ISSUE TITLE
[🐛 Bug]: I'm seeing "Could not start a new session. New session request timed out"     C#

### ISSUE THREAD

**Issue by NickSx9** [SeleniumHQ/docker-selenium#1440]
### What happened?

I start the selenium tests, I get a long pause (2-3mins) and then I see this error.
"Could not start a new session. New session request timed out" which is linked to RemoteWebDriver

I see the connection to the hub 4.0 (in the que) but that's it... it stays in the que for awhile, then I get that error.

I created a very simple standalone test, and that works fine.  
start -> navigate to page -> close  

I'll admit, I'm very new to Docker (about a week now) so there maybe a chance its a config issue (I used docker-compose -f docker-compose-v2.yml up -d )      is there a timeout tag that needs to be added? 

unfortunately, I'm unable to share code (Work/Privacy) but I can mention, before the tests runs, there is a call out to a internal service like 'a setup process'.   
so I initially thought it was a proxy issue?, but as the tests NEVER leave the que, i'm not so sure..

### Command used to start Selenium Grid with Docker

```shell
docker-compose -f docker-compose-v2.yml up -d
```

### Relevant log output

```shell
"Could not start a new session. New session request timed out"
```

### Operating System

Windows Server 2019 vm

### Docker Selenium version (tag)

4.0.0.-20211025

**Comment by diemol** [comment]
I need to see the capabilities being sent to the Grid to understand better what the issue might be. Can you share them please?

**Comment by diemol** [comment]
Closing as we did not get any reply.

**Comment by NickSx9** [comment]
hello, sorry for the delay - I needed to get permission to share this - then was given a different work task.

 {
   acceptInsecureCerts: true, 
   browserName: chrome, 
   goog:chromeOptions: {
        args: [
            start-maximized, 
            --no-sandbox, 
            --disable-infobars, 
            --disable-backgrounding-occ...
            ], 
        excludeSwitches: [
            enable-automation
            ], 
            prefs: {
              credentials_enable_service: false, 
              profile.password_manager_enabled: false
              
            },
            useAutomationExtension: false
    }, 
    pageLoadStrategy: none, 
    platformName: windows, 
    unhandledPromptBehavior: ignore
 }
