### ISSUE TITLE
[🐛 Bug]: NodeDocker start-selenium-grid-node-docker.sh config file path

### ISSUE THREAD

**Issue by eravion** [SeleniumHQ/docker-selenium#1442]
### What happened?

Hello,

The path for toml config file is different between NodeDocker and NodeBase.
--config /opt/bin/config.toml
vs 
--config /opt/selenium/config.toml

This may be linked to the fact that NodeDocker is not build from NodeBase despite firefox, chrome and edge docker.

Sorry, I don't know how to propose a PR to fix it.

Path to files :
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeDocker/start-selenium-grid-node-docker.sh

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/start-selenium-node.sh

In addition, this line are not on NodeBase .sh file

java ${JAVA_OPTS} -jar /opt/selenium/selenium-server.jar node \
  --publish-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_PUBLISH_PORT} \
  --subscribe-events tcp://"${SE_EVENT_BUS_HOST}":${SE_EVENT_BUS_SUBSCRIBE_PORT} \
  --detect-drivers false \
  --config /opt/bin/config.toml \
  ${SE_GRID_URL} ${SE_OPTS}

It mean that config.toml have to include 
[events]
publish = "tcp://{{ hub_selenium_4_ip }}:4442"
subscribe = "tcp://{{ hub_selenium_4_ip }}:4443"

### Operating System

Docker

### Docker Selenium version (tag)

4.0.0

**Comment by diemol** [comment]
This is not clear to me, why is ths a bug?

**Comment by diemol** [comment]
Closing as we did not get a reply.
