### ISSUE TITLE
[🐛 Bug]: Files are not downloaded

### ISSUE THREAD

**Issue by theunreal** [SeleniumHQ/docker-selenium#1445]
### What happened?

Trying to download files using docker-selenium, I don't see any files anywhere, ran the docker using the following command:

`$ docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.0.0-20211102`

I tried to look at /home/seluser without setting a default:

```
new Builder().forBrowser('chrome')
        .usingServer('http://172.18.0.5:4444')
        .setChromeOptions(new chrome.Options()
            .addArguments([
                '--no-sandbox', '--disable-dev-shm-usage', 'log-path=/chromedriver.log',
                '--headless', '--window-size=1920,1080', '--ignore-certificate-errors'])
            .setUserPreferences({
                "profile.default_content_settings.popups": 0,
                "download.prompt_for_download": false,
                "safebrowsing.enabled": true,
            }))
        .build()
```

and with: (check default_directory)
```
new Builder().forBrowser('chrome')
        .usingServer('http://172.18.0.5:4444')
        .setChromeOptions(new chrome.Options()
            .addArguments([
                '--no-sandbox', '--disable-dev-shm-usage', 'log-path=/chromedriver.log',
                '--headless', '--window-size=1920,1080', '--ignore-certificate-errors'])
            .setUserPreferences({
                "download.default_directory": process.env.DOWNLOAD_FOLDER,
                "profile.default_content_settings.popups": 0,
                "download.prompt_for_download": false,
                "safebrowsing.enabled": true,
            }))
        .build()
```

In both cases I can't find any downloaded files. in  `home/seluser`/ I don't have any files.

My docker looks like this:
Node app (Docker 1 - connected to the selenium instnace) --> Selenium (Chrome) (Docker 2)

I don't see anyting related to download in selenium logs.

Any idea what could have gone wrong or where I should look / debug this?

Thanks!

### Command used to start Selenium Grid with Docker

```shell
`$ docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.0.0-20211102`
```

### Relevant log output

```shell
no relevant output
```

### Operating System

Linux (redhat)

### Docker Selenium version (tag)

4.0.0-20211102

**Comment by diemol** [comment]
Files are normally downloaded to `/home/seluser/Downloads`. If you mounted a directory, probably permissions are blocking the browser to download the file. Can you double check that?

**Comment by theunreal** [comment]
> Files are normally downloaded to `/home/seluser/Downloads`. If you mounted a directory, probably permissions are blocking the browser to download the file. Can you double check that?

As I mentioned above, I don't see any folder inside home/seluser (in the selenium docker). I didn't mount any directory - I just want to see the files anywhere before I do any mount.

Any suggestion?

**Comment by diemol** [comment]
What happens if you use Ubuntu?

**Comment by theunreal** [comment]
> What happens if you use Ubuntu?

Sorry, it was ubuntu.
```
[root@mail ~]# docker exec -it 33e /bin/bash
seluser@33e588576233:/$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
```

Host is (not sure it's related)
`[root@mail ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
`

**Comment by diemol** [comment]
I meant the host, the images are using Ubuntu indeed.

**Comment by theunreal** [comment]
> I meant the host, the images are using Ubuntu indeed.

I can't change the host - it's my VPS, I have no other machine. Any suggestion?
btw, why the host is important here?

**Comment by diemol** [comment]
The idea behind suggesting Ubuntu is to narrow down the issue. If it works in Ubuntu, we can focus on understanding what the issue with the other OS is.

**Comment by theunreal** [comment]
> The idea behind suggesting Ubuntu is to narrow down the issue. If it works in Ubuntu, we can focus on understanding what the issue with the other OS is.

Anything else I can do without changing my OS on the host since it's not possible?

**Comment by therealdjryan** [comment]
@theunreal,
I see you are running headless. If you run "headfull", do you see a save file dialog? If you must run headless can you invoke a screenshot to see if this is the case?

I had a similar problem and the culprit turned out to be insufficient file permissions. In your case it seems unlikely, since you are not mounting a remote directory but it's worth a check. 

Dennis

**Comment by theunreal** [comment]
> @theunreal, I see you are running headless. If you run "headfull", do you see a save file dialog? If you must run headless can you invoke a screenshot to see if this is the case?
> 
> I had a similar problem and the culprit turned out to be insufficient file permissions. In your case it seems unlikely, since you are not mounting a remote directory but it's worth a check.
> 
> Dennis

Thanks, @therealdjryan , it sounds like a great idea - but I have no idea how I can see the browser doing the action. I saw there is a VPN port where I can see the browser window, but it just shows "open VPN" and I'm not sure how I can check the browser while it's working. I'm just running a node script that talks to the remote selenium and check the logs.

How you can monitor the browser screen?

**Comment by diemol** [comment]
@theunreal https://github.com/seleniumhq/docker-selenium/#debugging

**Comment by diemol** [comment]
Were you able to find a solution, @theunreal?
