### ISSUE TITLE
[🐛 Bug]: Selenium standalone crashes on startup when running on build agent on WSL2 on Windows 10

### ISSUE THREAD

**Issue by idontusenumbers** [SeleniumHQ/docker-selenium#1447]
### What happened?

I'm running
* selenium/standalone-chrome:4.0.0-20211025
* Docker-in-Docker TeamCity agent docker container
* WSL2 (docker)
* Windows 10 

Also:
* selenium/standalone-chrome:4.0.0-20211025
* Docker-in-Docker TeamCity agent docker container
* Ubuntu 20.04.3

When starting on the Windows machine, the selenium container starts, it immediately crashes:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

When I run the same image on the same machine except directly on docker-on-WSL2 instead of the TeamCity docker-in-docker or on Ubuntu, it works fine.

I'd report to Docker or WSL2 teams but selenium is the only container failing to start among many.

I'm not really sure how to diagnose further.

### Command used to start Selenium Grid with Docker

```shell
docker run selenium/standalone-chrome:4.0.0-20211025
```

### Operating System

Windows 10 

### Docker Selenium version (tag)

4.0.0-20211025

**Comment by diemol** [comment]
What is "Docker-in-Docker TeamCity agent docker container"? How can I reproduce the issue with that?

**Comment by idontusenumbers** [comment]
While trying to get a nice set of simple repro steps, I'm no longer able to reproduce. I rebuilt the container and it's running fine now. Sorry for the noise.
