### ISSUE TITLE
missing capability - platform

### ISSUE THREAD

**Issue by strowi** [SeleniumHQ/docker-selenium#145]
Hi,

i dont know if this is intended, but the config.json is missing the platform specification:

```
  "capabilities": [
    {
      "platform": "LINUX",
...
```

regards,
strowi

**Comment by diemol** [comment]
Hi @strowi,

I think this is not needed because, if I am not wrong, the Grid will detect this and it is part of the capabilities.

E.g.: (check the capabilities part).

![image](https://cloud.githubusercontent.com/assets/5992658/26531534/51eaa650-43eb-11e7-8eb6-f47c9b062d12.png)
