### ISSUE TITLE
[🐛 Bug]: WATCH EXECUTION IN REAL TIME WHEN I USED HTTPS - This request has been blocked; this endpoint must be available over WSS

### ISSUE THREAD

**Issue by fescobar** [SeleniumHQ/docker-selenium#1450]
### What happened?

I've installed selenium 4.1.0 in Kubernetes with HTTPS.
I can navigate and run tests without any problem.

The issue is when I try to access the session to watch the execution in real-time (camera icon from any browser). The pop up to see the execution is open (it's blank), but in the console log from the browser appears a message `This request has been blocked; this endpoint must be available over WSS`

Seems to be internally is doing other calls without HTTPS. 
I don't have any issues when I use only HTTP.

Is there any other configuration that I need to do when I use HTTPS?

![image](https://user-images.githubusercontent.com/1236418/141306720-fdd23dd0-98b9-4c02-919b-8d3789a4b9d8.png)

### Command used to start Selenium Grid with Docker

```shell
helm upgrade --namespace selenium4 --create-namespace --wait --install sg4 ./selenium4
```

### Relevant log output

```shell
Mixed Content: The page at 'https://selenium4.xxx-xxx.com/ui/index.html#/sessions' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://selenium4.xxx-xxx.com:4444/session/6a9182dc-3ca1-4001-a924-5f0b47ccaf38/se/vnc'. This request has been blocked; this endpoint must be available over WSS.

```sh
Failed when connecting: Error when opening socket (SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.)
```
```


### Operating System

UBUNTU

### Docker Selenium version (tag)

4.1.0

**Comment by diemol** [comment]
I can see where the bug happens, I will have a look soon.

**Comment by fescobar** [comment]
@diemol Thank you so much for your quick response.

**Comment by diemol** [comment]
Thanks for reporting this, I just fixed it in the main repo. 
Ideally, we will do a release in one week or so. 
If this does not happen, I will do a pre-release so you can use this fix.

**Comment by fescobar** [comment]
@diemol no problem. I will check the new version the next week. Thank you so much. I'm really happy about this new version of Selenium Grid. It's working great!
