### ISSUE TITLE
[🐛 Bug]: LiveView (VNC) Password

### ISSUE THREAD

**Issue by dfmerchan2** [SeleniumHQ/docker-selenium#1455]
### What happened?

In selenium Grid "LiveView (VNC) Password" is asking me for a password, what should that password be?
![image](https://user-images.githubusercontent.com/53876379/142495484-811ea95d-3920-4675-89ce-bc91c7766d76.png)

### Command used to start Selenium Grid with Docker

```shell
In selenium Grid "LiveView (VNC) Password" is asking me for a password, what should that password be?
```

### Relevant log output

```shell
In selenium Grid "LiveView (VNC) Password" is asking me for a password, what should that password be?
```

### Operating System

Windows

### Docker Selenium version (tag)

4.1.0

**Comment by diemol** [comment]
Step 4, https://github.com/seleniumhq/docker-selenium/#quick-start

**Comment by diemol** [comment]
`secret`
