### ISSUE TITLE
Add custom configurations/settings to Dynamic grid

### ISSUE THREAD

**Issue by erikkovacs** [SeleniumHQ/docker-selenium#1457]
### What happened?

According to the documentation:
https://www.selenium.dev/documentation/grid/configuring_components/toml_options/

It's possible to protect the grid with basic auth like this:
[router]
username = "admin"
password = "myStrongPassword"

If it's not the way, how I can protect the grid?

### Command used to start Selenium Grid with Docker

```shell
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    selenium/node-docker:4.1.0-20211123


No protection is there
```

### Relevant log output

```shell
no logs at all
```

### Operating System

MacOs BigSur

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
A couple of things:
- The config needed for Dynamic Grid to work is not present in the toml file you provide above. You can take this [configuration](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeDocker/config.toml) as a base
- The `router` section only applies to either the Hub, the Router or Standalone. So you would need to provide that file to any of those images. You can provide the CLI [args via SE_OPTS](https://github.com/SeleniumHQ/docker-selenium#se_opts-selenium-configuration-options).
