### ISSUE TITLE
[🐛 Bug]: Running grid 4.0 on ECS fargate doesn't seem to register nodes

### ISSUE THREAD

**Issue by fedezubo** [SeleniumHQ/docker-selenium#1458]
### What happened?

I am trying to update my fargate infrastructure with grid 4.0 but I can't get the nodes to register to the hub. I have updated the docker launch settings to get them in line with the new naming conventions etc but i did not manage to get the grid to see the nodes. 

### Command used to start Selenium Grid with Docker

```shell
"name": "hub", 
            "image": "selenium/node-chrome:4.1.0-20211123", 
            "portMappings": [
                {
                    "hostPort": 5555,
                    "protocol": "tcp",
                    "containerPort": 5555
                }
            ],
            "essential": true, 
            "entryPoint": [], 
            "command": [ "/bin/bash", "-c", "PRIVATE=$(curl -s http://169.254.170.2/v2/metadata | jq -r '.Containers[0].Networks[0].IPv4Addresses[0]') ; export REMOTE_HOST=\"http://$PRIVATE:5555\" ; /opt/bin/entry_point.sh" ],
            "environment": [
                {
                  "name": "SE_EVENT_BUS_HOST",
                  "value": "hub.selenium"
                },
                {
                  "name": "SE_EVENT_BUS_PUBLISH",
                  "value": "4442"
                },
                {
                 "name": "SE_EVENT_BUS_SUBSCRIBE_PORT"
                 "value": "4443"
                {
                    "name":"NODE_MAX_SESSION",
                    "value":"3"
                },
                {
                    "name":"NODE_MAX_INSTANCES",
                    "value":"3"
                }
            ],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group":"true",
                    "awslogs-group": "awslogs-selenium",
                    "awslogs-region": "eu-west-1",
                    "awslogs-stream-prefix": "firefox"
                }
            }
        }
```

### Relevant log output

```shell
this is with grid 3.0
12:37:21.119 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://hub.selenium:4444/grid/register

this is with grid 4.0
Connecting to tcp://hub.selenium:4442 and tcp://hub.selenium:4443 failed
java.net.UnknownHostException: hub.selenium
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.1.0-20211123

**Comment by fedezubo** [comment]
The hub has the relevant ports opened and the security groups have those ports inclueded within them

**Comment by diemol** [comment]
But some env vars are not correct, for example `SE_EVENT_BUS_PUBLISH` is missing `_PORT` at the end. Also, `REMOTE_HOST` is not available in Grid 4. I think this swarm [file](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-swarm.yml) can guide you better.

Also, not sure about it, but is the file you posted above declaring a `hub` but using `node-chrome`?

**Comment by fedezubo** [comment]
the hub part is just a name, i am running the same name for all the parts and it's been working fine in grid 3.0. The _PORT part was a good catch but unfortunately it's just a typo. The swarm file you linked seems like a good place to start investigating. Thanks a lot for your help so far!

**Comment by fedezubo** [comment]
Upon further investigation, changing the way I supply the entry point command did not change the behaviour. I am working on some other possibile fixes. 

If I get to the bottom of this it might be useful to maybe add the info to your main wiki as an addendum or something. 

Info on this implementation is available from other sources but all the framework relies on grid 3.0 which you have deprecated and have discontinued the image support. 

I will keep updating the post with my discoveries

**Comment by hupling** [comment]
Sometimes I have the same problem with this config https://github.com/kubernetes/examples/tree/master/staging/selenium . I have one selenium grid with a firefox and chrome node. I also tried to update to selenium 4.1 and I had still problems. With this config I don't have problems https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml Selenium-eventbus, selenium-sessions, selenium-session-queue, selenium-distrubutor, selenium-router and the node are different deployments

**Comment by fedezubo** [comment]
>https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml Selenium-eventbus, selenium-sessions, selenium-session-queue, selenium-distrubutor, selenium-router and the node are different deployments

WIth this config, where do you see the grid UI? At the router or at the event bus? 
I am asking because with my fargate setup I am running a load balancer and I would need to know to which service do i need to attach my load balancer to.

Thanks a lot in advance!

**Comment by hupling** [comment]
Here is how you do it. https://github.com/SeleniumHQ/docker-selenium#deploying-to-kubernetes

The deployment is  `selenium-router-deployment`, I saw it on the gui.

**Comment by diemol** [comment]
Thanks, @hupling, for being helpful and providing more information! 

I will close this issue and if more help is needed, you can still add comments or join our community channels [here](https://www.selenium.dev/support/#ChatRoom).
