### ISSUE TITLE
[🐛 Bug]: Selenium hub and nodes throw error Received message without a valid secret. Rejecting

### ISSUE THREAD

**Issue by amansharif** [SeleniumHQ/docker-selenium#1460]
### What happened?

I have tried deploying selenium 4.1.0-20211123 with in EKS with the following two ways

1. [helm chart](https://github.com/ilpianista/docker-selenium/tree/selenium-grid-helm-chart-0.3.0/chart/selenium-grid)
2. [k8s manifests](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml)

In both scenarios I faced two issues

1. Sometimes it did register and sometimes it did not without throwing any useful information about why it did not register.

2. (Sometimes when nodes did register) some simple tests are being executed for sanity tests but the sessions did not stop after the tests. It keeps running.

### Command used to start Selenium Grid with Docker

```shell
https://github.com/ilpianista/docker-selenium/tree/selenium-grid-helm-chart-0.3.0/chart/selenium-grid

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml
```

### Relevant log output

```shell
2021-11-26 11:56:50,644 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2021-11-26 11:56:50,646 INFO supervisord started with pid 8
2021-11-26 11:56:51,648 INFO spawned: 'selenium-grid-hub' with pid 10
11:56:52.242 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
2021-11-26 11:56:52,247 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
11:56:52.250 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:56:52.403 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.52.5.150:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.52.5.150:4443]
11:56:52.573 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.52.5.150:4442 and tcp://10.52.5.150:4443
11:56:52.604 INFO [UnboundZmqEventBus.<init>] - Sockets created
11:56:53.608 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:56:54.456 INFO [Hub.execute] - Started Selenium Hub 4.1.0 (revision 87802e897b): http://10.52.5.150:4444
11:57:16.031 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=aedf32f6-d3a7-47db-a9b2-1f7724cff379, type=selenium-rejected-event, data={"data": "\u0004\u0003\b\u0007\b\u0005\b","name": "��ʷQ�O�F��\u0026�RH\u001e�� ��2�>w����w\u0006E�>�Fr]\r\u0012)�}\u0015�����c\u0000 �\u002f�0�+�,̨̩�\u0013�\t�\u0014�\n\u0000�\u0000�\u0000\u002f\u00005�\u0012\u0000\n\u0001\u0000\u0000O\u0000\u0005\u0000\u0005\u0001\u0000\u0000\u0000\u0000\u0000\n\u0000\n\u0000\b\u0000\u001d\u0000\u0017\u0000\u0018\u0000\u0019\u0000\u000b\u0000\u0002\u0001\u0000\u0000\r\u0000\u001a\u0000\u0018"}] -> 
```

### Operating System

EKS version 1.21

### Docker Selenium version (tag)

4.1.0-20211123

**Comment by diemol** [comment]
This happens because the EventBus is receiving events on 4442 that are not part of the Selenium Grid recognised events. In Kubernetes envs, the cause for this is (usually) monitoring on those endpoints. That message is an output after fixing https://github.com/SeleniumHQ/selenium/issues/9959.

So, this is normal because events not recognised and without a secret are being rejected.
