### ISSUE TITLE
[🐛 Bug]: Unable to change max sessions inside standalone container via docker environmental variable.

### ISSUE THREAD

**Issue by MajesticOl** [SeleniumHQ/docker-selenium#1461]
### What happened?

I am trying to figure out how to setup a docker standalone grid that accepts more than 1 concurrent session without consoling into the container and manually editing the `config.toml.max-sessions` setting... This however seems to be a very difficult task, since there literally is no documentation whatsoever about that. 

I tried to set docker enviromental variables, but the available sessions dont change.

i have tried following commands:

`docker run -d -p 4444:4444 -e SE_NODE_MAX_INSTANCES=40 -e SE_NODE_MAX_SESSION=40  selenium/standalone-chrome:latest`

`docker run -d -p 4444:4444 -e NODE_MAX_INSTANCES=40 -e NODE_MAX_SESSION=40  selenium/standalone-chrome:latest`

Those variations of the 2 (supposedly) relevant environmental variables concerning max sessions have failed me so far... i cant find any additional info anywhere else. Every provided example only uses a docker compose file with a hub and a grid. Literally none example is about the standalone version. This place is my last resort.

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 -e SE_NODE_MAX_INSTANCES=40 -e SE_NODE_MAX_SESSION=40  selenium/standalone-chrome:latest
```

### Relevant log output

```shell
Max. Concurrency: 1
```

### Operating System

Ubuntu 20.04 LTS

### Docker Selenium version (tag)

4.1.0 (revision 87802e897b)

**Comment by diemol** [comment]
>This however seems to be a very difficult task, since there literally is no documentation whatsoever about that.

I beg to differ :) This is documented -> https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container
