### ISSUE TITLE
[🐛 Bug]: Unable to change max-sessions for selenium/standalone with CircleCI

### ISSUE THREAD

**Issue by unickq** [SeleniumHQ/docker-selenium#1462]
### What happened?

I'm trying to set up selenium/standalone-chrome on CircleCI.
After updating to Selenium 4 I found that the max-sessions param is hardcoded to 1 by default which makes it impossible to run.

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L180

I tried to set **SE_NODE_MAX_SESSIONS** and **SE_NODE_OVERRIDE_MAX_SESSIONS** env variables but looks like that env variables are set after selenium image pulled and started
![image](https://user-images.githubusercontent.com/6696821/144472350-f9012c4c-a15e-488c-8841-6ddb06cd8236.png)

Selenium images v3.14 didn't have such a problem. Is there a way to do something with it?

### Command used to start Selenium Grid with Docker

```shell
https://circleci.com/docs/2.0/building-docker-images/

docker:
  - image: selenium/standalone-chrome:96.0-20211123
```

### Relevant log output

```shell
Selenium Grid Standalone configuration: 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "96.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Standalone...
```

### Operating System

CirleCi

### Docker Selenium version (tag)

4.1.0

**Comment by diemol** [comment]
You can pass env vars to override that behaviour https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container
I am not a Circle CI user, but I can see one can pass env vars in Circle CI https://circleci.com/docs/2.0/env-vars/

I am closing this as this is a matter of figuring out Circle CI, which is out of the scope of this project.

If you need help, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
