### ISSUE TITLE
[🚀 Feature]: RemoteWebDriver - custom headers, at least for Authorization.

### ISSUE THREAD

**Issue by RevoltEnergy** [SeleniumHQ/docker-selenium#1470]
### Feature and motivation

`RemoteWebDriver` internally has an HTTP client and request filters and `RemoteWebDriverBuilder` seems like gives the possibility to configure a request handler with the custom `Filter` (which is supposed to add the bearer token to headers) but it does not participate in the filter chain during the session creation and the request fails to the secured container with the _standalone-chrome_ running.

### Usage example

I was able to successfully run the _standalone-chrome_ image in the Google Cloud Run container with _allowed unauthenticated access_ and _allowed internal traffic only_ so it is still not private, exposed to the world, just returns 403.

**Comment by diemol** [comment]
I am not sure I follow all the details. Can you share the scripts you used and what you bumped into?

**Comment by RevoltEnergy** [comment]
@diemol hello, my mistake, this issue needs to be moved here - https://github.com/SeleniumHQ/selenium, can we move it?

I'm using a Java `RemoteWebDriver` to connect the **chromedriver** of the _[standalone-chrome](https://hub.docker.com/r/selenium/standalone-chrome)_ running in GCP Cloud Run in my case. This connection requires authentication - an access token in the header, and there is no possibility to add the token to the `RemoteWebDriver`. I was trying to intercept the request to add this header but no luck. I suppose the same problem can exist with the `RemoteWebDriver` written in other languages.

Related conversation on stackoverflow - [here](https://stackoverflow.com/questions/70200171/remote-chrome-webdriver-on-gcp/).
