### ISSUE TITLE
[🐛 Bug]: SessionID rather than testName is shown on sessions page when se:name is set

### ISSUE THREAD

**Issue by therealdjryan** [SeleniumHQ/docker-selenium#1475]
### What happened?

when chrome option se:name is set to the name of the test, the session name not the test name is not shown on the sessions page

### Command used to start Selenium Grid with Docker

```shell
N/A
```

### Relevant log output

```shell
se:name is being passed in. here’s what gets queued (goog:chromeOptions removed for brevity):
{
    "browserName": "chrome",
    "se:name": "testStuff",
    "se:recordVideo": true,
    "se:screenResolution": "1550x880",
    "se:timeZone": "US/Eastern",
    "timeouts": {
        "pageLoad": 900000,
        "script": 300000
    }
}
```

### Operating System

RHEL8

### Docker Selenium version (tag)

4.1.1-20211217

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/selenium/commit/a6d74f9569b29b5358f13747947f155db93a64b4, will be available in the next release.
