### ISSUE TITLE
[🐛 Bug]: RemoteDisconnected error when running Standalone Chrome docker image

### ISSUE THREAD

**Issue by peter-kinzelman** [SeleniumHQ/docker-selenium#1476]
### What happened?

- After upgrading to Selenium 4, creating a Remote Driver on a local Standalone container is no longer working 
- Process is: 
1) Create a standalone container on local Mac (new MacBookPro M1 Chip) 
```
docker run --name standalone -d -p 5555:4444 -p 7901:7900 -p 5901:5900 --shm-size="2g" selenium/standalone-chrome:4.1.1-20211217
```
2) Try to create a driver:
```
self.driver = webdriver.Remote(
            "http://localhost:5555/wd/hub", desired_capabilities=self.options.to_capabilities()
        )
```
3 Receive error:
```
ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Note: Version of Selenium `selenium==4.1.0`

Note: Same configuration works on old MacBookPro

### Command used to start Selenium Grid with Docker

```shell
See above.
```

### Relevant log output

```shell
See above.
```

### Operating System

MacOS Monteray Apple M1 Max 

### Docker Selenium version (tag)

selenium/standalone-chrome:4.1.1-20211217

**Comment by diemol** [comment]
These images are not supported on that architecture yet, please follow #1076.
