### ISSUE TITLE
[🐛 Bug]: Chrome node cannot register when set environment vars SE_NODE_HOST/SE_NODE_PORT

### ISSUE THREAD

**Issue by wikingwei** [SeleniumHQ/docker-selenium#1484]
### What happened?

I'm trying deploying hub and chrome nodes on same or different VM hosts following the guide in REAEME. When set environment vars SE_NODE_HOST/SE_NODE_PORT, (and even  SE_NODE_GRID_URL) the registration always fails with several message "Sending registration event…", (chrome node reports itselft as the specified SE_NODE_HOST IP and port, which is I want).
 See details  in the following command and log sections.

When not set environment vars SE_NODE_HOST/SE_NODE_PORT, as below,  

```
docker run -d --restart=always \
        -p 15585:5555 \
        -e SE_EVENT_BUS_HOST=10.128.100.100 \
        -e SE_EVENT_BUS_PUBLISH_PORT=14442  \
       -e SE_EVENT_BUS_SUBSCRIBE_PORT=14443 \
        -v /dev/shm:/dev/shm \
        --name test-node-chrome \
        selenium/node-chrome:96.0-chromedriver-96.0-grid-4.1.1-20211217
```

the registration is successful. But node reports self as an internal address: http://172.17.0.6:5555, which is not what I want.

Could some one help with this? or ever got the same issue ?

Thanks.

### Command used to start Selenium Grid with Docker

```shell
docker run -d --restart=always \
        -p 15585:5555 \
        -e SE_NODE_HOST=10.128.100.100 \
        -e SE_NODE_PORT=15585 \
        -e SE_NODE_GRID_URL="http://10.128.100.100:14444" \
        -e SE_EVENT_BUS_HOST=10.128.100.100 \
        -e SE_EVENT_BUS_PUBLISH_PORT=14442  \
        -e SE_EVENT_BUS_SUBSCRIBE_PORT=14443 \
        -v /dev/shm:/dev/shm \
        --name test-node-chrome \
        selenium/node-chrome:96.0-chromedriver-96.0-grid-4.1.1-20211217
```

### Relevant log output

```shell
…
2022-01-24 21:16:21,651 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Generating Selenium Config
Selenium Grid Node configuration: 
[events]
publish = "tcp://10.128.100.100:14442"
subscribe = "tcp://10.128.100.100:14443"

[server]
host = "10.128.100.100"
port = "15585"
[node]
grid-url = "http://10.128.100.100:14444"
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "96.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Node...
13:16:22.499 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:16:22.505 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:16:22.634 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.128.100.100:14442 and tcp://10.128.100.100:14443
13:16:22.691 INFO [UnboundZmqEventBus.<init>] - Sockets created
13:16:23.694 INFO [UnboundZmqEventBus.<init>] - Event bus ready
13:16:23.844 INFO [NodeServer.createHandlers] - Reporting self as: http://10.128.100.100:15585 
13:16:23.866 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
13:16:23.932 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "96.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
13:16:23.944 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
13:16:24.175 INFO [NodeServer$1.start] - Starting registration process for node id c4958900-0028-4173-9d82-dd8fb2a54a43
13:16:24.176 INFO [NodeServer.execute] - Started Selenium node 4.1.1 (revision e8fcc2cecf): http://10.128.100.100:15585 
13:16:24.180 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:16:34.191 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:16:44.195 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:16:54.198 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:17:04.202 INFO [NodeServer$1.lambda$start$1] - Sending registration event…
…
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

96.0-chromedriver-96.0-grid-4.1.1-20211217

**Comment by luiscspinho** [comment]
Happens in v97.0 as well

**Comment by diemol** [comment]
If you want to start and run the containers separately on the same VM, the steps to do that can be seen in the [Docker networking section](https://github.com/SeleniumHQ/docker-selenium#docker-networking). However, the easiest approach to run all containers in the same VM is to use this [docker-compose file](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml).

To run the containers on different VMs, please check the [Use different VMs/Machines section](https://github.com/SeleniumHQ/docker-selenium#using-different-machinesvms). 

In the command you share to start the container, you are using the same IP for `SE_NODE_HOST` and `SE_EVENT_BUS_HOST`. Which does not make sense if you want to run the containers in different machines, because `SE_EVENT_BUS_HOST` is the IP where the Hub is running. Therefore `SE_NODE_HOST` should be the IP of the machine where the Node is running.

If you have more questions, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by wikingwei** [comment]
> If you want to start and run the containers separately on the same VM, the steps to do that can be seen in the [Docker networking section](https://github.com/SeleniumHQ/docker-selenium#docker-networking). However, the easiest approach to run all containers in the same VM is to use this [docker-compose file](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml).
> 
> To run the containers on different VMs, please check the [Use different VMs/Machines section](https://github.com/SeleniumHQ/docker-selenium#using-different-machinesvms).
> 
> In the command you share to start the container, you are using the same IP for `SE_NODE_HOST` and `SE_EVENT_BUS_HOST`. Which does not make sense if you want to run the containers in different machines, because `SE_EVENT_BUS_HOST` is the IP where the Hub is running. Therefore `SE_NODE_HOST` should be the IP of the machine where the Node is running.
> 
> If you have more questions, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

Thanks @diemol for your information. 
My issue is, no matter that they run on same or different VMs (IP same or not), specifying the SE_NODE_HOST always causes registration fail. I will try latest versions to check again.

**Comment by wikingwei** [comment]
This issue still exists using latest  selenium/node-chrome:98.0-chromedriver-98.0-grid-4.1.2-20220217, no matter that on the same VM or different ones. BTW, my docker run commands are always following the [Use different VMs/Machines section](https://github.com/SeleniumHQ/docker-selenium#using-different-machinesvms).
