### ISSUE TITLE
[🐛 Bug]: Chrome 94.0.4606.61 seems to be pretty unstable in 3.141.59-20210929

### ISSUE THREAD

**Issue by falsyvalues** [SeleniumHQ/docker-selenium#1498]
### What happened?

Hello,
We have updated both grid and selenium node-chrome from 3.141.59-20210422 (Chrome: 90.0.4430.85
) to 3.141.59-20210929 (Chrome 94.0.4606.61). Nothing except that was change on the env that we running it on. And we started observing following exceptions.

Is there any change for another 3.141.59 release with newer Chrome 🙏 ?

### Command used to start Selenium Grid with Docker

```shell
Images being build on pipeline and pushed to Amazon ECR.
```

### Relevant log output

```shell
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed   (Session info: headless chrome=94.0.4606.61) Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: '977575f6e1d3', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.256-197.484.amzn2.x86_64', java.version: '12-ea'
```

### Operating System

Amazon Linux 2

### Docker Selenium version (tag)

3.141.59-20210929

**Comment by diemol** [comment]
Not sure what the issue might be as the only change is the Chrome version. I understand you are using Grid 3 but we are not doing any more releases for that version. 

I'd recommend to start using the Grid 4 images and let us know if you bump into the same issue.

Alternatively, you can build your own images https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images based on the Grid 3 branch https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3

**Comment by falsyvalues** [comment]
Hi @diemol,

We have a plan to move to Grid 4, but its not trivial in out setup. Problem is probably related to Chrome itself, I will consider building our own images, thanks.
