### ISSUE TITLE
[🐛 Bug]: Roll new version for Chrome 98

### ISSUE THREAD

**Issue by andrewnicols** [SeleniumHQ/docker-selenium#1501]
### What happened?

Chrome 98 was released

### Command used to start Selenium Grid with Docker

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Docker Selenium version (tag)

N/A

**Comment by diemol** [comment]
Holding this new release due to https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999

**Comment by diemol** [comment]
The fix in ChromeDriver is taking a while, so I went ahead and did a release. Please check the link above for workarounds. As soon as  bugfix for ChromeDriver is released, we will do a new release.
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.1.2-20220208

**Comment by andrewnicols** [comment]
Hi @diemol,

Chrome and Chromedriver have now been updated with the fix for the sendKeys issue.

Any chance we can do another release?

Thanks
