### ISSUE TITLE
[🐛 Bug]: The site banzai.io crashes after opening it in selenium hub.

### ISSUE THREAD

**Issue by ravetisy** [SeleniumHQ/docker-selenium#1506]
### What happened?

I am using standalone/chrome for automating the web page. Starting from chrome:96 , the website banzai.io is crashing after opening it in selenium-hub chrome session.

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 --name test selenium/standalone-chrome:96
```

### Relevant log output

```shell
System info: host: '9b298721c714', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.72-microsoft-standard-WSL2', java.version: '11.0.13'
```

### Operating System

Windows 12

### Docker Selenium version (tag)

Docker Desktop 4.4.4 (73704)

**Comment by diemol** [comment]
How can I reproduce this? There is no automation script attached to the issue description.

**Comment by diemol** [comment]
No more info was proovided.
