### ISSUE TITLE
[🐛 Bug]: Hub stop Registering nodes though secret is valid

### ISSUE THREAD

**Issue by madhusudhancogn** [SeleniumHQ/docker-selenium#1513]
### What happened?

I am getting error "Received Message without valid secret" when I create node with valid secret (second time)

**Steps to reproduce:**
1. Create hub with a registration secret 
2. Create a node with invalid registration secret
3. Now create a node with valid secret

### Command used to start Selenium Grid with Docker

```shell
Hub:
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub -e SERVER_REGISTRATION_SECRET=cheese selenium/hub:4.1

Chrome:
docker run -d --net grid -e SE_EVENT_BUS_HOST=hub \
    --shm-size="2g" \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SERVER_REGISTRATION_SECRET=cheese \
    selenium/node-chrome:4.1
```

### Relevant log output

```shell
Received Message without valid secret
```

### Operating System

windows 10

### Docker Selenium version (tag)

4.1

**Comment by diemol** [comment]
Can you share the full logs and not just that line please? Both Node and Hub.

**Comment by diemol** [comment]
Closing as no more information was provided.
