### ISSUE TITLE
[🚀 Feature]: Dynamic Grid support in helm chart

### ISSUE THREAD

**Issue by Swapnil-CSI** [SeleniumHQ/docker-selenium#1517]
### Feature and motivation

Selenium docker deployment has dynamic grid support but it is not present for the helm chart. Is there any way to use the dynamic grid in helm chart.

https://github.com/SeleniumHQ/docker-selenium#dynamic-grid

### Usage example

It will help to create the node(chrome, firefox) pods as per the usage.

Zalenium has similar support but the project is deprecated.
https://github.com/zalando/zalenium/tree/master/charts/zalenium

**Comment by diemol** [comment]
For this topic, please follow https://github.com/SeleniumHQ/selenium/issues/9845
