### ISSUE TITLE
Need new image as per v2.49.0

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#152]
Please release new docker image wrt latest release of selenium v2.49.0

Thanks in advance.

**Comment by rubytester** [comment]
We got 2.49.1 and 2.50.0 images going. 

Do you still need 2.49.0 ? If not please close. Thanks.

**Comment by vikramvi** [comment]
Closing as per earlier comment.

Thanks for clarification @rubytester 

Regards,
Vikram
