### ISSUE TITLE
[🚀 Feature]: autoscaling based on queue size

### ISSUE THREAD

**Issue by manuschillernordlb** [SeleniumHQ/docker-selenium#1527]
### Feature and motivation

It would be great if we could configure this chart to automatically spin up new nodes when the queue reaches a certain length. This could probably done with K8s HPAs and custom metrics.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects

### Usage example

Depending on the size of the queue it would take a while until new runs can get executed.
A deployment with HPA would solve that by spinning up new nodes on demand.

**Comment by Wolfe1** [comment]
@manuschillernordlb This might be of some interest to you then: https://github.com/SeleniumHQ/selenium/issues/9845#issuecomment-1046976533

I have been using keda coupled with the PreStop drain command to scale my pods up and down based on queue size and session use.

**Comment by diemol** [comment]
Thank you, @Wolfe1, for linking the issues. 

@manuschillernordlb please follow the conversation in the linked issue.
