### ISSUE TITLE
[🐛 Bug]: HelmChart should use /readyz endpoint to check the health - so that k8s can restart a failed grid

### ISSUE THREAD

**Issue by Bjego** [SeleniumHQ/docker-selenium#1529]
### What happened?

The Http statuscodes for the /readyz endpoint have been adjusted (https://github.com/SeleniumHQ/selenium/issues/10391). The status endpoint as you can see in the Selenium ticket returns always 200 - Ok even if the grid isn't running properly.

We should adjust the helmchart to use the readyz endpoint for health checks. So that kubernetes can restart the grid on it's own.

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/chart/selenium-grid/values.yaml#L199

### Command used to start Selenium Grid with Docker

```shell
Helm deployment
```

### Relevant log output

```shell
non
```

### Operating System

Linux

### Docker Selenium version (tag)

Latest helm chart

**Comment by diemol** [comment]
@Bjego, would you like to help us with a PR?

Probably @ilpianista can help us by reviewing it.

**Comment by Bjego** [comment]
> @Bjego, would you like to help us with a PR?
> 
> Probably @ilpianista can help us by reviewing it.

I think I can give it a quick shot, do all components expose the /readyz endpoint?

**Comment by Bjego** [comment]
Guess I'm too late. Was busy this week doing features at work. Thanks for implementing it!
