### ISSUE TITLE
How to set Java arguments?

### ISSUE THREAD

**Issue by kierr** [SeleniumHQ/docker-selenium#153]
I need to set -DPOOL_MAX=512, since I'm having performance issues the closer I get to 50 nodes.

I'm using Docker Compose. Any ideas how I can do this?

**Comment by rubytester** [comment]
We send values to  jvm with JAVA_OPTS env variable. And we send values to selenium jar wth SE_OPTS
https://github.com/SeleniumHQ/docker-selenium#java_opts-java-environment-options
https://github.com/SeleniumHQ/docker-selenium#se_opts-selenium-configuration-options

example:

`$ docker run -d -p 4444:4444 -e JAVA_OPTS="-Xmx4G" -e SE_OPTS="-DPOOL_MAX=512" selenium/hub`

We append SE_OPTS args at the end.

Would this work for you? Please let us know.

**Comment by kierr** [comment]
Thank you, that's perfect.
