### ISSUE TITLE
[🐛 Bug]: helm-chart healthcheck failed with basic auth enabled

### ISSUE THREAD

**Issue by tgruenert** [SeleniumHQ/docker-selenium#1535]
### What happened?

while deploying selenium hub with helm-chart and user credentials config, container keeps restarting because liviness probe failed. 

### Command used to start Selenium Grid with Docker

```shell
deploy a configmap 

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}-config
data:
  config.toml: |-
    [router]
    username = "seluser"
    password = "selpass"
```
and mount them in hub deployment
```


### Relevant log output

```shell
INFO [BasicAuthenticationFilter.lambda$apply$0] - Unauthorized request to (GET) /wd/hub/status
```

### Operating System

Kubernetes on Ubuntu 

### Docker Selenium version (tag)

selenium/hub:4.1.3-20220327

**Comment by diemol** [comment]
This [commit](https://github.com/SeleniumHQ/docker-selenium/commit/c38937c6596edd2f0d089be5fdbade0e852e5b5e) changed the endpoint from `/status` to `/readyz`, which is not under basic auth.

Please update the chart you are using to get this recent change.

**Comment by IamGroot19** [comment]
@tgruenert  Can you tell me how you added authentication via configmap on helm charts? Did you have to edit the template files as well?

**Comment by tgruenert** [comment]
@IamGroot19 
Yes i modified the helm chart. 

in values.yaml
```
        hub:
          extraEnvironmentVariables: 
            - name: HOST_CONFIG
              value: "--config /opt/selenium/config.toml"
```

and add a configmap to charts:

```
{{- $fullName := include "seleniumGrid.hub.fullname" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}-config
data:
  config.toml: |-
    [router]
    username = "replaceIt"
    password = "forYourSecurity"
```

that´s all.

**Comment by IamGroot19** [comment]
@tgruenert Thanks for the update. 

@diemol I want to add send in a PR for mounting this config.toml.  Would there be a better way to implement or can I go ahead & follow the above comment?

**Comment by diemol** [comment]
@IamGroot19 sure, that is a good idea. Ideally it should be configurable.
