### ISSUE TITLE
[🚀 Feature]: Documentation / Update Helm chart with instructions how to configure video recording

### ISSUE THREAD

**Issue by SBe** [SeleniumHQ/docker-selenium#1542]
### Feature and motivation

We are trying to turn on video recording on Kubernetes cluster, however there is no information in documentation or in Helm chart, how this can be enabled. Is it possible to add missing information at least in the docs? I can create a PR to update helm chart by myself if I knew some details that are needed

### Usage example

We are currently using Zalenium Grid and we love the feature that we are able to record videos and check what is going on when the tests fail.

**Comment by diemol** [comment]
Please follow the conversation at https://github.com/SeleniumHQ/selenium/issues/9845, this request will be eventually addressed over there.
