### ISSUE TITLE
[🐛 Bug]: Unable to configure auth

### ISSUE THREAD

**Issue by IamGroot19** [SeleniumHQ/docker-selenium#1547]
### What happened?

I am not sure how to add basic and other config related options to this helm char tsetup.

This [documentation](https://www.selenium.dev/documentation/grid/configuration/toml_options/) tells it is possible to add configs via TOML file. 

And from this earlier issue (https://github.com/SeleniumHQ/docker-selenium/issues/1535), I making a guess that it's to be done via a  Kubernetes `ConfigMap`. 

My doubts are these:
1. Are there alternate / better ways to add configs? (For eg, by simply passing the key-value pairs in config.toml as environment variables in the values.yaml file)
2. If at all I want to add it via a configmap, what other additions need to be done here? ( My guess would be: 1. Add Volume-Mount templating code in hub-deployment.yaml  so as to inject the config.toml in /opt/in of container)

### Command used to start Selenium Grid with Docker

```shell
(This is a kubernetes deployment)
```

### Relevant log output

```shell
NA
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.1.3-20220405

**Comment by diemol** [comment]
Maybe you can ask this question to the OP on #1535, I see you are already asking in Slack, probably @ilpianista can help to reply there too.

I will close this issue as it is a question and it can be addressed as a part of #1535.
