### ISSUE TITLE
Connecting to other docker container

### ISSUE THREAD

**Issue by mkurzeja** [SeleniumHQ/docker-selenium#155]
Hi,

I'm trying to use docker-selenium containers to test my app on a CI server. I have currently two containers:
- web container with my app + test runner
- mysql container

I plan to add a selenium container and connect it to the web container so the test runner can access it.
Is there any way to tell selenium that example.dev runs on the web container?

Not sure this is doable but maybe you can suggest something :)

**Comment by rubytester** [comment]
Zobacz #133

If you make your own network using docker-compose you can see this example: 

https://github.com/SeleniumHQ/docker-selenium/issues/133#issuecomment-165249099

**Comment by mkurzeja** [comment]
Thank you! Using network instead of links is the answer!
