### ISSUE TITLE
[🐛 Bug]: K8s Selenium Grid 4 throws UnboundZmqEventBus$PollingRunnable.rejectEvent after the latest version of prisma vulnerability scan deployed to our cluster nodes.

### ISSUE THREAD

**Issue by MithunDavid** [SeleniumHQ/docker-selenium#1550]
### What happened?

We have been running selenium grid 4 for some time in our Org using HELM chart and recently started started seeing this exception after the last Prisma cloud version went in.  We were using  [4.1.3-20220327] and last week migrated to latest version [4.1.3-20220405] But we are hitting this issue consistently and all running nodes gets stuck and hang round as orphans and become unresponsive.  The only way to resolve is to redeploy and it works for some time and again it happens quite frequently now a days. 

Our current configuration is using HELM (isolateComponents: false) and hub & nodes using ClusterIP and Ingress with certificate on https connection. 

Prisma latest version: https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-01/prisma-cloud-compute-edition-release-notes/release-information/release-notes-22-01-update1

 

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid ./selenium-grid-0.3.0.tgz -n seleniumgrid-dev
```

### Relevant log output

```shell
Exception: ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Could not parse event secret, rejecting event. Unable to parse: node-heartbeat. Event[id=9ad1d1c0-d76a-4c39-b2d9-a75536242f77, type=selenium-rejected-event, data={"data": "node-heartbeat","name": "�>� \u0012�����\u003cT�.�`�� %+��\rfw�g��H�6�Js\u000f\u0013\fY�m0�\")}�۵�\u0000\u0026�+�\u002f�,�0̨̩�\t�\u0013�\n�\u0014\u0000�\u0000�\u0000\u002f\u00005�\u0012\u0000\n\u0013\u0001\u0013\u0002\u0013\u0003\u0001\u0000\u0000{\u0000\u0005\u0000\u0005\u0001\u0000\u0000\u0000\u0000\u0000\n\u0000\n\u0000\b\u0000\u001d\u0000\u0017\u0000\u0018\u0000\u0019\u0000\u000b\u0000\u0002\u0001\u0000\u0000\r\u0000\u001a\u0000\u0018\b\u0004\u0004\u0003\b\u0007\b\u0005\b\u0006\u0004\u0001\u0005\u0001\u0006\u0001\u0005\u0003\u0006\u0003\u0002\u0001\u0002\u0003�\u0001\u0000\u0001\u0000\u0000\u0012\u0000\u0000\u0000+\u0000\t\b\u0003\u0004\u0003\u0003\u0003\u0002\u0003\u0001\u00003\u0000\u0026\u0000$\u0000\u001d\u0000 ��jEY��\u0013\n\u0000\u001d�n�\u0011,�-\b׵�����\u0014"}]
```

### Operating System

OS: Red Hat Enterprise Linux

### Docker Selenium version (tag)

4.1.3-20220405

**Comment by diemol** [comment]
Duplicate of https://github.com/SeleniumHQ/selenium/issues/10485
