### ISSUE TITLE
[🚀 Feature]: Install libnss3-tools in images in order to be able to setup certificates

### ISSUE THREAD

**Issue by algoritmus** [SeleniumHQ/docker-selenium#1565]
### Feature and motivation

To add custom certificates, CAs, etc to nssdb (or create a new one) it would be nice to have libnss3-tools preinstalled in images.

### Usage example

certutil -d ....

pk12util -d .....

**Comment by diemol** [comment]
@algoritmus how much would the Docker images grow if tho are added?

If they do not grow much, would you like to send a PR wit the change and documentation?

**Comment by algoritmus** [comment]
based on standalone-edge:latest
it will be 487.35 vs 485.22 compressed, if I delete the update list folder rm -rf /var/lib/apt/lists/* (19Mb).

the package itself is roughly 4Mb

Pls guide me, this will be the first time for me here in GitHub. What should I do exactly ? Modify the Dockerfile.txt files with the additional install command ?

**Comment by algoritmus** [comment]
I think it is valid (nssdb) only for chromium based browsers, so chrome and edge

**Comment by algoritmus** [comment]
Did my best....

**Comment by diemol** [comment]
Closing, it got documented here https://github.com/SeleniumHQ/docker-selenium#install-certificates-for-Chromium-based-browsers
