### ISSUE TITLE
[🐛 Bug]: Selenium Grid on Minikube Failing. Please provide updated workflow

### ISSUE THREAD

**Issue by PavanMudigondaTR** [SeleniumHQ/docker-selenium#1570]
### What happened?

I have attempted to run Selenium Grid on Minikube following this with latest Selenium Grid docker file but it failed. The pods are not coming in to running state and getting timed out. Could you please correct the minikube workflow as per latest selenium full grid docker file ?

https://github.com/SeleniumHQ/docker-selenium/actions/runs/1338139240/workflow

### Command used to start Selenium Grid with Docker

```shell
copied this below workflow as it. 
https://github.com/SeleniumHQ/docker-selenium/actions/runs/1338139240/workflow

copied below docker-compose-v3-full-grid as is.  and i tried in my private repo.

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-full-grid.yml
```

### Relevant log output

```shell
Run echo "Waiting for pods to attain ready state...."
  echo "Waiting for pods to attain ready state...."
  kubectl wait --for=condition=ready pod -l name=selenium-router --timeout=300s
  kubectl wait --for=condition=ready pod -l name=selenium-distributor --timeout=300s
  kubectl wait --for=condition=ready pod -l name=selenium-event-bus --timeout=300s
  kubectl wait --for=condition=ready pod -l name=selenium-chrome-node --timeout=800s
  kubectl get pods -l component=selenium-grid-4
  echo "All pods are in ready state now"
  shell: /usr/bin/bash -e {0}
  env:
    MINIKUBE_HOME: /home/runner/work/_temp
Waiting for pods to attain ready state....
error: timed out waiting for the condition on pods/selenium-router-deployment-858876f9c-s6qgj
Error: Process completed with exit code 1.
```

### Operating System

Github Actions with Ubuntu runner

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
The workflow was removed because it was not working well and at the moment we do not have one. This is something that could be improved. 

Also, the recommended way is to use the helm chart https://github.com/SeleniumHQ/docker-selenium#deploying-to-kubernetes.

I will close this since there is no bug in the repository right now, but we are open to receive a PR where the workflow can be implemented using helm charts.

**Comment by PavanMudigondaTR** [comment]
@diemol thanks will try helm chart and see if I can make PR
