### ISSUE TITLE
[🐛 Bug]:The method getDevTools() is undefined for the type ChromeDriver in latest 4.1.4

### ISSUE THREAD

**Issue by sriharircb** [SeleniumHQ/docker-selenium#1576]
### What happened?

driver.getDevTools() is not recognising in latest selenium 4.1.4 version. due to that getting compilation error

### Command used to start Selenium Grid with Docker

```shell
grid not using
```

### Relevant log output

```shell
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method getDevTools() is undefined for the type ChromeDriver
```

### Operating System

macos 12.3.1

### Docker Selenium version (tag)

4.1.4

**Comment by diemol** [comment]
Please report this issue to https://github.com/SeleniumHQ/selenium and fill out the whole template.
