### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by Affan-selenium** [SeleniumHQ/docker-selenium#1579]
### What happened?

[Docker ](http://localhost:4444/) shows The Grid has no registered Nodes yet, despite images being created and linked to the hub node

Expected :

![image](https://user-images.githubusercontent.com/106099341/169857447-53b0d677-99a4-4149-b750-56df13fac5e5.png)

Actual : 

![image](https://user-images.githubusercontent.com/106099341/169857345-61375b5d-c938-4d69-855f-17dcccba5a00.png)

### How can we reproduce the issue?

```shell
I was trying to run my scripts in a container : these were the commands that I used in the terminal :

Install docker 
Open CMD on Windows and run the below commands 

docker pull selenium/hub
docker pull selenium/node-chrome
docker pull selenium/node-firefox
docker images
docker run -d -p 4444:4444 -P --name selenium-hub selenium/hub
docker run -d --link selenium-hub:hub -P --name chrome selenium/node-chrome
docker run -d --link selenium-hub:hub -P --name firefox selenium/node-firefox

Expected :

Should be 

Actual :
The Grid has no registered Nodes yet.
More information about Selenium Grid can be found at the Help section.
```

### Relevant log output

```shell
No such log output,issue seems to be only in docker setup .
```

### Operating System

Windows 11

### Selenium version

Java 8

### What are the browser(s) and version(s) where you see this issue?

Chrome 101

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.67

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment]
Please follow the docs for the current version -> https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes
