### ISSUE TITLE
Update to 2.50.1

### ISSUE THREAD

**Issue by jbalbien** [SeleniumHQ/docker-selenium#158]
2.50.1 fixes timeout issue introduced by 2.50.0 (https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG)

All my tests are failing with timeout errors since updating docker-selenium to 2.50.0 (2.49.1 works fine)

**Comment by vikramvi** [comment]
+1 Thanks in advance.

**Comment by aanisimov** [comment]
+1. Thank you!

**Comment by apakhomov** [comment]
+1

**Comment by foneox** [comment]
+1

**Comment by foneox** [comment]
#157

**Comment by jeffjk-me** [comment]
I think this issue can be closed. Issue https://github.com/SeleniumHQ/docker-selenium/issues/191 also supersedes by version. Pull request https://github.com/SeleniumHQ/docker-selenium/pull/192 addresses upgrade to version 2.53.0.

**Comment by kayabendroth** [comment]
Superseded by and fixed with https://github.com/SeleniumHQ/docker-selenium/pull/194.
