### ISSUE TITLE
[🐛 Bug]: helm chart in tag 4.1.4-20220427 uses 4.1.3-20220427

### ISSUE THREAD

**Issue by getsomebread** [SeleniumHQ/docker-selenium#1583]
### What happened?

I tried to deploy Selenium 4.1.4-20220427 with the helm chart using the proper git tag, but when I do, it deploys with 4.1.3-20220427 chart + docker images. 

### Command used to start Selenium Grid with Docker

```shell
# Suppsed to deploy 4.1.4-20220427, but does 4.1.3-20220427 instead
git clone -b  4.1.4-20220427 https://github.com/SeleniumHQ/docker-selenium.git
helm install selenium-grid-dev docker-selenium/chart/selenium-grid

# How to actually deploy 4.1.4-20220427
# Note that it uses 'charts' directory instead of 'chart'
git clone -b  trunk https://github.com/SeleniumHQ/docker-selenium.git
helm install selenium-grid-dev docker-selenium/charts/selenium-grid
```

### Relevant log output

```shell
# Note the APP VERSION column, even though I used git tag 4.1.4-20220427
helm list
NAME             	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART               APP VERSION
selenium-grid-dev	selenium-dev	6       	2022-05-20 16:34:09.902465859 +0000 UTC	deployed	selenium-grid-0.3.0 4.1.3-20220427
```

### Operating System

Linux

### Docker Selenium version (tag)

4.1.4-20220427

**Comment by diemol** [comment]
This makes sense because we do not have the release tags for Docker images in sync with the chart releases. However, a recent contribution has enabled us to have tags for chart releases. Please check the updated docs at https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid
