### ISSUE TITLE
[🐛 Bug]: Not able to get to automatically download files without the file dialog opening in docker-selenium agent machine.

### ISSUE THREAD

**Issue by sshivhare89** [SeleniumHQ/docker-selenium#1586]
### What happened?

Hi,

I am trying to get downloaded file automatically under the download folder in docker-selenium agent machine. But it always shows a dialog box asking for the specific location to download a file.
This pop-up is coming on Chrome only. It's directly downloading file without displaying popup in Edge browser.

I tried to hide/ignore it using below desired capabilities in chrome, but it's not working-
chromeOptions.addArguments("--disable-popup-blocking");
chromeOptions.setExperimentalOption("excludeSwitches",Arrays.asList("disable-popup-blocking"));
Map<String, Object> prefs = new HashMap<>();
prefs.put("download.prompt_for_download", "false");

![pop-upbox-image](https://user-images.githubusercontent.com/106511364/171000846-8a5e409a-9927-4892-b0a6-c8fa1f22e92a.png)

### Command used to start Selenium Grid with Docker

```shell
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    volumes:
      - /target:/home/seluser/Downloads
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  edge:
    image: selenium/node-edge:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  #firefox:
   # image: selenium/node-firefox:latest
   # shm_size: 2gb
   # depends_on:
   #   - selenium-hub
   # environment:
   #   - SE_EVENT_BUS_HOST=selenium-hub
    #  - SE_EVENT_BUS_PUBLISH_PORT=4442
    #  - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


Command to start selenium grid with docker- docker-compose up -d
```

### Relevant log output

```shell
No logs available to attach. It's just a pop-up coming after click on download.
```

### Operating System

Linux

### Docker Selenium version (tag)

4.1.3-20220405

**Comment by diemol** [comment]
I see you are using Linux, here is the needed workaround
https://github.com/SeleniumHQ/docker-selenium#mounting-volumes-to-retrieve-downloaded-files
