### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by yacov-ma** [SeleniumHQ/docker-selenium#1599]
### What happened?

Hi,
I used to run our tests on ubuntu 20.04 using "selenium/standalone-chrome:4.1.2-20220217" docker image. 
since last week tests start to fail constantly on "NoSuchElementException" , Iv'e checked for update with the latest selenium and after upgrade continue to fail. The issues that i face here it's very similar to [this](https://github.com/SeleniumHQ/docker-selenium/issues/629) since this close i opened a new issue.

By the way all tests pass successfully with all version in local env (mac os)
let me know if more info required  

### Command used to start Selenium Grid with Docker

```shell
selenium/standalone-chrome
```

### Relevant log output

```shell
return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":""}
  (Session info: headless chrome=101.0.4951.41)
```

### Operating System

ubuntu 20.04

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
How can I reproduce the issue?

**Comment by yacov-ma** [comment]
Hi @diemol,
First of all, thank you for your response.
in order to reproduce the issue follow the steps:

prerequisite:

1. running on ec2 instance inside docker (Linux/amd64)
2. selenium v- 4.2.0
3. create  dockerfile based on 'selenium/standalone-chrome:4.2.2-20220609' 
4. add python3.9 code, that runs the selenium test to the dockerfile
4. build a new image 

steps to reproduce:

1. init chrome with options (--no-sandbox, --headless, --disable-gpu, --disable-dev-shm-usage, --window-size=1920,1080)
2. run the code inside the container base on an image from the prerequisite steps.

expected result:
the test will pass like in local env

actual result:
even if the elements are displayed and the enabled driver throws the exception 'NoSuchElementException'

**Comment by diemol** [comment]
Can you please provide the actual files to reproduce the issue? Narrative descriptions leave lots of room for ambiguity.

**Comment by yacov-ma** [comment]
@diemol 
for example, try to run this:

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

ser = Service(ChromeDriverManager().install())
options = webdriver.ChromeOptions()
options.add_argument('--no-sandbox')
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--window-size=1920,1080')
options.add_argument('--start-maximized')

selenium_driver = webdriver.Chrome(service=ser, options=options)


def is_select_size_err_displayed(driver: webdriver):
    select_size_err = driver.find_element(By.CLASS_NAME, 'styles_product-sizes__label--error__uUfVk')
    if select_size_err.text == 'Please Select a Size':
        return True
    return False


def main():
    url = 'https://www.everlane.com/products/womens-cloud-cable-knit-vest-oatmeal?collection=womens-newest-arrivals'

    selenium_driver.get(url)

    add_to_bag = selenium_driver.find_element(By.CLASS_NAME, 'styles_product-cta__pjhy3')
    add_to_bag.click()
    return is_select_size_err_displayed(selenium_driver)


if __name__ == "__main__":
    main()
    selenium_driver.quit()
```

**Comment by diemol** [comment]
@yacov-ma but that code is not using Selenium Grid nor the Docker images from this repository. Am I missing something?

**Comment by yacov-ma** [comment]
@diemol 
yes, run this code inside a running container (FROM selenium/standalone-chrome:4.2.2-20220609)

**Comment by diemol** [comment]
Ah OK, got it. What happens if you remove the headless flag?

Can you share the GitHub repo with the whole setup? I apologize if I was not clear. But we are not enough people around and spending time building a scenario to reproduce is not how we can use our time these days. It'd be easier if you provide all the files in a GitHub repository so I can clone it and run the commands needed to reproduce the issue.

**Comment by yacov-ma** [comment]
@diemol 
gotcha, It's a bit complicated to share our private repo, However, I'll work on a public one to share the data.
Meanwhile, without a headless flag local it's working fine, even with a headless flag local it works.

**Comment by diemol** [comment]
Why do you use the headless flag? It is know that Chrome has different behavior when running headless. If it works without the flag but does not with the flag, there is not much we can do at the Selenium project. You would need to create an issue at the Chrome/ChromeDriver project.

**Comment by yacov-ma** [comment]
The reason why using headless is that test run without UI Linux based os.
"If it works without the flag but does not with the flag" - this is not what I said.
 
 It's not working at the testing env at all.

**Comment by diemol** [comment]
Apologies it took a while for understand the whole context. 

So you are not using the Docker images with Xvfb. And your tests are now failing after a Chrome update. 

If the main difference between the environments is the Chrome and ChromeDriver version, then I do not think it is related to the images but rather the browser.

What is the exact tag you are using (not `latest` please), does it work locally with the same Chrome version? Have you checked on an Ubuntu machine?

**Comment by yacov-ma** [comment]
I already mention,
tag selenium/standalone-chrome:4.2.2-20220609 working on local and ubuntu but not in ec2 ubuntu.

**Comment by diemol** [comment]
What is the difference between the local environment and the EC2?

**Comment by yacov-ma** [comment]
@diemol 
It was a resource issue.

10x.

**Comment by diemol** [comment]
Can you share more details about the root cause? Then others can learn from it.

**Comment by yacov-ma** [comment]
basically,
locating elements locally vs  ec2 instance,
in ec2 is much faster therefore return element not found

**Comment by lucassfernando** [comment]
I'm facing the same issue when running my project locally vs server. On the server it is happening the error: `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[6]/div"}`   being that locally it is running correctly.
My script accesses a page where it logs in and collects some information. I noticed that the error happens after logging in, it seems that it gets lost and does not find the next elements of the other pages.

My server settings:
Ubuntu 20.04
Python 3.10
Chrome 100.0.5

Any solution?
