### ISSUE TITLE
[🚀 Feature]: Selenium Grid 4 doesn't support video recording in Kubernetes.

### ISSUE THREAD

**Issue by ArsenMiq** [SeleniumHQ/docker-selenium#1601]
### Feature and motivation

**Pipeline AWS/Kubernetes support:**

I run my tests in AWS clusters with Kubernetes support. So I used helm to run the Selenium grid.

```
# Add docker-selenium helm repository
helm repo add docker-selenium https://www.selenium.dev/docker-selenium

# Update charts from docker-selenium repo
helm repo update

# List all versions present in the docker-selenium repo
helm search repo docker-selenium --versions

# Install basic grid latest version
helm install selenium-grid docker-selenium/selenium-grid

# Or install full grid (Router, Distributor, EventBus, SessionMap and SessionQueue components separated)
helm install selenium-grid docker-selenium/selenium-grid --set isolateComponents=true

# Or install specified version
helm install selenium-grid docker-selenium/selenium-grid --version 0.3.1

# In both cases grid exposed by default using ingress. You may want to set hostname for the grid. Default hostname is selenium-grid.local.
helm install selenium-grid --set ingress.hostname=selenium-grid.k8s.local docker-selenium/chart/selenium-grid/.
```
I used some configurations - https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid

**Run locally with Docker:**

In local, I run tests as a docker container with screen video recording.

```
$ docker network create grid
$ docker run -d -p 4444:4444 -p 6900:5900 --net grid --name selenium --shm-size="2g" selenium/standalone-chrome:4.2.2-20220609
$ docker run -d --net grid --name video -v /tmp/videos:/videos selenium/video:ffmpeg-4.3.1-20220609
# Run your tests
$ docker stop video && docker rm video
$ docker stop selenium && docker rm selenium
```

Or YAML file - https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-video.yml

### Example in Zalando/Zalenium:

Before switching to Selenium 4 I was running my tests in Zalenium and it supported screen video recording in Kubernetes helm.

```
$ helm repo add zalenium-github https://raw.githubusercontent.com/zalando/zalenium/master/charts/zalenium
$ helm install ${EKS_NAMESPACE} zalenium-github/zalenium --namespace ${EKS_NAMESPACE} \
    --set hub.image="095415062695.dkr.ecr.us-west-2.amazonaws.com/eso/zal-hub" \
    --set hub.seleniumImageName="095415062695.dkr.ecr.us-west-2.amazonaws.com/eso/zal-sel" \
    --set hub.serviceType="LoadBalancer" \
    --set hub.videoRecordingEnabled=true \
    --set hub.maxDockerSeleniumContainers=${SESSIONS} \
    --set hub.desiredContainers=${SESSIONS}
```

For more details - https://opensource.zalando.com/zalenium/

And also I can get video recordings for each test case.

_It is possible to enable or disable video recording while the test is running regardless of what is setup when the session starts. This is done by sending a cookie with the name zaleniumVideo with a value of true (to enable recording) or false (to disable recording). Disabling recording while it is originally enable will result in a new video file. This can be useful when you have multiple tests in one session and want to split up each test in its own file. This feature is only available with elgalu/selenium. Here is an example in Java:_

```
    Cookie cookie = new Cookie("zaleniumVideo", "true");
    webDriver.manage().addCookie(cookie);
```

### Actual

The video recording in Selenium grid 4 is not supported in the Kubernetes helm chart.
It's possible to record a browser video with running Docker.

### Expectation

I run 1000+ tests in the pipeline and I want to get only the failed test case video recordings. So if Selenium will have a library like a TakesScreenshot, users can get only failed test cases video recording and it will very useful for testers.

For example:

```
  @Test
  public void videoRecordingForFirstTest {
    SessionId sessionId = ((RemoteWebDriver) webDriver).getSessionId();
    TakesVideo video = new TakesVideo(sessionId, "path/to/download");
    video.setName("videoRecordingForFirstTest.mp4");
    video.start();

    /*** 
     * Some tests goes there
     * ***/

    video.stop();
  }

  @Test
  public void videoRecordingForSecondTest {
    SessionId sessionId = ((RemoteWebDriver) webDriver).getSessionId();
    TakesVideo video = new TakesVideo(sessionId, "path/to/download");
    video.setName("videoRecordingForFirstTest.mp4");
    video.start();

    /*** 
     * Some tests goes there
     * ***/

    video.stop();
  }
```

**Comment by diemol** [comment]
Efforts for this are being tracked in https://github.com/SeleniumHQ/selenium/issues/9845
