### ISSUE TITLE
[🐛 Bug]: Print-Pdf - Emojis not getting printed on PDF

### ISSUE THREAD

**Issue by grijeshsaini** [SeleniumHQ/docker-selenium#1614]
### What happened?

As we have a web page where we have used emojis when we are trying to generate the pdf using selenium the pdf doesn't have emojis in it.

I believe the reason is that node-chrome doesn't have emoji fonts installed in it.

-- Steps were taken locally-
As I am using the docker so I started the node-chrome container locally and I installed the emoji font inside the container using the below commands
```
sudo apt-get update
sudo apt-get install -y fonts-noto-color-emoji
``` 
And then when I am generating the pdf it works fine, it has emoji characters in it. (I can see the emoji on chrome session as well)

### Command used to start Selenium Grid with Docker

```shell
version: '3'
services:

  hub:
    image: selenium/hub:4.2.2
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'

  chrome-pdf:
    image: selenium/node-chrome:102.0
    container_name: web-automation-chrome-pdf
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_OPTS: --detect-drivers false --publish-events tcp://hub:4442 --subscribe-events tcp://hub:4443 --grid-url http://localhost:4444 --driver-configuration display-name=chrome max-sessions=5 stereotype={"browserName":"chrome","browserVersion":"102.0","networkname:applicationName":"pdf_node","nodename:applicationName":"pdf_app"}
      GENERATE_CONFIG: "false"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '9001:5900'
    links:
      - hub
```

### Relevant log output

```shell
N/A
```

### Operating System

macos

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
The containers do not have those fonts. If you want and the images don't grow much, please submit a PR that install the font in the images.

**Comment by PDUBEY00** [comment]
Hi @diemol I have picked this issue and created a PR. Please let me know in case of any issues. Thanks

**Comment by grijeshsaini** [comment]
Thanks, @PDUBEY00 .

**Comment by diemol** [comment]
Merged, thank you for contributing, @PDUBEY00!
