### ISSUE TITLE
Video file is not appearing after running the test using Dynamic Grid

### ISSUE THREAD

**Issue by sabbir-aust** [SeleniumHQ/docker-selenium#1621]
### What happened?

I've copy pasted the exact same code of both the config.toml file and dynamic grid compose file. Then i've run the "docker compose up" command and run a test. According to the configuration, under my project the test recording video should be available along with a "sessionCapabilities.json" file. But there only the json file is appearing. No video file.

### Command used to start Selenium Grid with Docker

```shell
this is the docker compose file: 



# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.3.0-20220628
    volumes:
      - ./test/assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.3.0-20220628
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"



this is the config.toml file: 


[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.3.0-20220628", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.3.0-20220628", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.3.0-20220628", "{\"browserName\": \"MicrosoftEdge\"}"
]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted
# If var/run/docker.sock is not mounted:
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://localhost:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20220628"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

### Relevant log output

```shell
Test is successfully running but only the json file is appearing under a folder named with the session id. Not any video.
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.3.0-20220628

**Comment by diemol** [comment]
How does the test look like? What capabilities did you send?

**Comment by sabbir-aust** [comment]
> How does the test look like? What capabilities did you send?

Here's the xml file (https://prnt.sc/KrPNfQAOZyr3 ) I normally pass some parameter along with the browser which initiates the browser. 
and here's the browser capabilities file (https://prnt.sc/wraUIf5CXo6T )  

@diemol

**Comment by diemol** [comment]
Seems you are not sending `se:recordVideo` with `true` in all cases, which is why video is not recorded.

Please make sure of that and then you'll see the video file.

If you still do not see it, please provide a complete code snippet I can use to reproduce the issue.

**Comment by sabbir-aust** [comment]
> Seems you are not sending `se:recordVideo` with `true` in all cases, which is why video is not recorded.
> 
> Please make sure of that and then you'll see the video file.
> 
> If you still do not see it, please provide a complete code snippet I can use to reproduce the issue.

Thanks for the info. That was my mistake. Anyway, thanks a lot. It worked. 
I've another question to you @diemol that is, Can i dynamically change the video file name or the folder name according to the test name instead of just "session id / video" as a folder or file name?

**Comment by diemol** [comment]
This is not possible because too many corner cases need to be handled. If you pass `se:name` then it will be shown in the UI and it will be part of the capabilities file.
