### ISSUE TITLE
[🐛 Bug]: Selenium grid does not work well when launching several tests. What is the max number of sessions a grid can handle?

### ISSUE THREAD

**Issue by albertalgi** [SeleniumHQ/docker-selenium#1629]
### What happened?

My Selenium grid v4.0.0 is was working well launching tests, however, when I put more tests it started creating data:, (void browsers) and my nodes crashed reducing the number of available sessions, thus, producing more zombie sessions.

The probleam appears to be that there is a max number of tests per grid. My question is, what is the max number of sessions a grid can handle?

### Command used to start Selenium Grid with Docker

```shell
-
```

### Relevant log output

```shell
Unable to execute request: java.net.ConnectException: Connection refused: 

INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.

ERROR [OsProcess.destroy] - Unable to kill process Process[pid=-----, exitValue=143]
```

### Operating System

Linux

### Docker Selenium version (tag)

4.0.0

**Comment by diemol** [comment]
It supports fairly well up to the number of available processors in the Node. However, without a way to reproduce this, we cannot troubleshoot this issue. Ideally a set of tests and some server specs are needed.

**Comment by diemol** [comment]
Closing this as no more info provided.
