### ISSUE TITLE
[🚀 Feature]: do we have docker node for safari in grid 4?

### ISSUE THREAD

**Issue by RayChenLDL** [SeleniumHQ/docker-selenium#1635]
### Feature and motivation

Most of the senior managers these days are using safari, so web testing on safari is becoming more and more popular. wondering if we have a docker node for safari?

### Usage example

Most of the senior managers these days are using safari, so web testing on safari is becoming more and more popular. wondering if we have a docker node for safari?

**Comment by diemol** [comment]
We won't provide macOS images in Docker because Apple is not providing them. Building and running them on our own requires nested virtualization and in the end, macOS license agreement only allows you to run macOS on Apple hardware.
