### ISSUE TITLE
[🐛 Bug]: Error 'Grid not ready' or session not created on standalone chrome container on MacOS

### ISSUE THREAD

**Issue by Rupasri33** [SeleniumHQ/docker-selenium#1637]
### What happened?

I'm trying to run selenium + Pytest-BDD tests on real browser (not Headless) on selenium/standalone-chrome container. 

python project @https://github.com/AndyLPK247/tau-pytest-bdd . (I updated the browser launch to user webdriver.Remote(command_executor="http://localhost:4444/wd/hub") 

The selenium/standalone-chrome container doesn't pick the test , its queued . 
noVNC (http://localhost:7900)  doesn't show the browser being launched. [same with Firefox as well)

**output**:     http://localhost:4444/session

{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002fsession",
    "stacktrace": ""
  }
}

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:4.3.0-20220706
```

### Relevant log output

```shell
2022-07-21 22:38:43,389 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing

2022-07-21 22:38:43,394 INFO RPC interface 'supervisor' initialized

2022-07-21 22:38:43,394 CRIT Server 'unix_http_server' running without any HTTP authentication checking

2022-07-21 22:38:43,395 INFO supervisord started with pid 8

2022-07-21 22:38:44,401 INFO spawned: 'xvfb' with pid 10

2022-07-21 22:38:44,403 INFO spawned: 'vnc' with pid 11

2022-07-21 22:38:44,406 INFO spawned: 'novnc' with pid 12

2022-07-21 22:38:44,407 INFO spawned: 'selenium-standalone' with pid 13

Setting up SE_NODE_GRID_URL...

2022-07-21 22:38:44,418 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-07-21 22:38:44,418 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-07-21 22:38:44,418 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-07-21 22:38:44,418 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Selenium Grid Standalone configuration: 

[network]

relax-checks = true
[node]

session-timeout = "300"

override-max-sessions = false

detect-drivers = false

drain-after-session-count = 0

max-sessions = 1


[[node.driver-configuration]]

display-name = "chrome"

stereotype = '{"browserName": "chrome", "browserVersion": "103.0", "platformName": "Linux"}'

max-sessions = 1


Starting Selenium Grid Standalone...

22:38:45.004 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

22:38:45.009 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

22:38:45.704 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors

22:38:45.752 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "103.0","se:noVncPort": 7900,"browserName": "chrome","platformName": "LINUX","se:vncEnabled": true} 1 times

22:38:45.770 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative

22:38:45.791 INFO [GridModel.setAvailability] - Switching Node b6a0920d-0700-4eb2-bef0-142476f5c0c0 (uri: http://xxx.xx.0.x:4444) from DOWN to UP

22:38:45.791 INFO [LocalDistributor.add] - Added node b6a0920d-0700-4eb2-bef0-142476f5c0c0 at http://xxx.xx.0.x:4444. Health check every 120s

22:38:45.991 INFO [Standalone.execute] - Started Selenium Standalone 4.3.0 (revision a4995e2c09*): http://xxx.xx.0.x:4444
```

### Operating System

macOS bigSur with Intel I7

### Docker Selenium version (tag)

selenium/standalone-chrome:4.3.0-20220706

**### _http://localhost:4444/status_**

{
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
      {
        "id": "cb069963-89d3-4869-9354-5cfa1cbbe333",
        "uri": "http:\u002f\u002f1xxx.xx.0.x:4444",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "5.10.104-linuxkit"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.3.0 (revision a4995e2c09*)",
        "slots": [
          {
            "id": {
              "hostId": "cb069963-89d3-4869-9354-5cfa1cbbe333",
              "id": "119d4f2d-190a-4967-aeb8-cc4e31dc4a4d"
            },
            "lastStarted": "2022-07-22T16:48:27.420979Z",
            "session": {
              "capabilities": {
                "acceptInsecureCerts": false,
                "browserName": "chrome",
                "browserVersion": "103.0.5060.114",
                "chrome": {
                  "chromedriverVersion": "103.0.5060.53 (a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs\u002fbranch-heads\u002f5060@{#853})",
                  "userDataDir": "\u002ftmp\u002f.com.google.Chrome.aZ46NZ"
                },
                "goog:chromeOptions": {
                  "debuggerAddress": "localhost:34383"
                },
                "networkConnectionEnabled": false,
                "pageLoadStrategy": "normal",
                "platformName": "LINUX",
                "proxy": {
                },
                "se:cdp": "ws:\u002f\u002fxxx.xx.0.x:4444\u002fsession\u002fe98c346eaedb3ad7c7089135804eba46\u002fse\u002fcdp",
                "se:cdpVersion": "103.0.5060.114",
                "se:vnc": "ws:\u002f\u002fxxx.xx.0.x:4444\u002fsession\u002fe98c346eaedb3ad7c7089135804eba46\u002fse\u002fvnc",
                "se:vncEnabled": true,
                "se:vncLocalAddress": "ws:\u002f\u002fxxx.xx.0.x:7900",
                "setWindowRect": true,
                "strictFileInteractability": false,
                "timeouts": {
                  "implicit": 0,
                  "pageLoad": 300000,
                  "script": 30000
                },
                "unhandledPromptBehavior": "dismiss and notify",
                "webauthn:extension:credBlob": true,
                "webauthn:extension:largeBlob": true,
                "webauthn:virtualAuthenticators": true
              },
              "sessionId": "e98c346eaedb3ad7c7089135804eba46",
              "start": "2022-07-22T16:48:27.420979Z",
              "stereotype": {
                "browserName": "chrome",
                "browserVersion": "103.0",
                "platformName": "LINUX",
                "se:noVncPort": 7900,
                "se:vncEnabled": true
              },
              "uri": "http:\u002f\u002fxxx.xx.0.x:4444"
            },
            "stereotype": {
              "browserName": "chrome",
              "browserVersion": "103.0",
              "platformName": "LINUX",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      }
    ]
  }
}

**Comment by diemol** [comment]
I don't see where in the sample project the Grid is used. Can you share a code snippet to reproduce the issue?

**Comment by diemol** [comment]
Closing as no more information has been provided.
