### ISSUE TITLE
slim docker image [🚀 Feature]: 

### ISSUE THREAD

**Issue by IAseven** [SeleniumHQ/docker-selenium#1639]
### Feature and motivation

I checked the code repository, and it seems that I only see that the supervisor and video depend on python. If my judgment is correct, I think we can use supervisord instead of supervisor. supervisord is written in go, and it doesn't depend on Python. I think this can reduce the size of the whole image.
Thank you for reading.
Go-superversord Code Address: https://github.com/ochinchina/supervisord

### Usage example

xx

**Comment by diemol** [comment]
What would be the size difference?

**Comment by diemol** [comment]
Closing as we did not get more information.
