### ISSUE TITLE
How do you pass in custom timeout and other se_options to individual nodes

### ISSUE THREAD

**Issue by slugics** [SeleniumHQ/docker-selenium#164]
By default this is set to following 
timeout:30 and maxSessions=1
How can I change that when running individual nodes? 

Thanks

**Comment by elsonrodriguez** [comment]
The Hub looks like it takes a lot of options as env variables:
https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/generate_config

For Nodes, you can use SE_OPT, but I'm not sure if you an set timeouts that way.
https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/entry_point.sh

**Comment by diemol** [comment]
@slugics you can now also do it by passing the variables when you start the container, see https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile#L15

You can pass them, for example, as `-e GRID_MAX_SESSION=30`.

**Comment by ddavison** [comment]
@slugics also, since you want to pass to individual nodes, this proves a difficult situation since docker containers are spun up in clusters.   

If all you are editing is the timeout, then you should have different clusters spun up with different timeouts and not worry about node-individuality.
