### ISSUE TITLE
[🐛 Bug]: Selenium Grid GraphQL endpoint not responding

### ISSUE THREAD

**Issue by Trigtrig** [SeleniumHQ/docker-selenium#1640]
### What happened?

We are currently experiencing a bug similar to the one described here: [#1318 ](https://github.com/SeleniumHQ/docker-selenium/issues/1318). If we start a Selenium Grid (version 4.3.0) and leave this grid idle, the GraphQL endpoint stops responding after a while. The problem occurs within approx. 24 hours. Restarting the grid fixes the problem only for the mentioned period of time before the GraphQL endpoint stops responding again.

This is the desired state of the grid after startup:
![Selenium Grid Docker](https://user-images.githubusercontent.com/7973740/181194814-c977519d-a7db-45c7-b204-adaec01f9d9e.png)

And this is the state of the grid when the error occurs:
![Selenium Grid Docker Loading](https://user-images.githubusercontent.com/7973740/181195091-a5c8beae-98ce-4944-bd55-987fda0f5098.png)

### Command used to start Selenium Grid with Docker

```shell
version: "3.7"

services:
  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: /opt/bin/check-grid.sh
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    env_file:
      - ../localization-variables.env
    environment:
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_SESSION_REQUEST_TIMEOUT=30
      - SE_SESSION_RETRY_INTERVAL=5

  node-docker:
    image: selenium/node-docker:4
    container_name: selenium-node
    volumes:
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    env_file:
      - ../localization-variables.env
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
```

### Relevant log output

```shell
There are no error messages in the hub log
```

### Operating System

RHEL

### Docker Selenium version (tag)

4

**Comment by Trigtrig** [comment]
I have now encountered the same problem with a second Selenium Grid. It is the same Selenium Grid version, but with the [Selenium Server JAR](https://www.selenium.dev/downloads/) on a Mac.

This is what the Selenium Grid looks like after startup:
![Selenium Grid Mac](https://user-images.githubusercontent.com/7973740/181445567-cac18abe-24c1-459d-9fc0-e023eb8b1c1a.png)
 
And when the problem occurs the behaviour is the same as in the second screenshot (see above). So I assume that the bug is not related to Docker.

Operating System: MacOS Monterey Version 12.5
Selenium Version: Selenium Server 4.3.0

**Comment by diemol** [comment]
I believe I was able to reproduce the issue. When this happens again, could you please check the `/status` endpoint and report back its contents please?

**Comment by diemol** [comment]
Can you share the contents of your `config.toml` please?

**Comment by Trigtrig** [comment]
> I believe I was able to reproduce the issue. When this happens again, could you please check the `/status` endpoint and report back its contents please?

```{
    "value": {
        "ready": true,
        "message": "Selenium Grid ready.",
        "nodes": [
            {
                "id": "50166c95-e505-4f71-af77-3994b864a39a",
                "uri": "http://<IP>:4444",
                "maxSessions": 6,
                "osInfo": {
                    "arch": "aarch64",
                    "name": "Mac OS X",
                    "version": "12.5"
                },
                "heartbeatPeriod": 60000,
                "availability": "UP",
                "version": "4.3.0 (revision a4995e2c09*)",
                "slots": [
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "4d5bf370-e70f-4ce4-9d1b-a2719bca0e86"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "browserName": "safari",
                            "platformName": "MAC"
                        }
                    },
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "24ce7490-deb0-4a2a-9be1-e742b67f1c89"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "appium:platformVersion": "14.8",
                            "appium:udid": "<UDID>",
                            "browserName": "iPhone 11",
                            "platformName": "IOS"
                        }
                    },
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "6947d4c2-5997-4597-990a-d84830597ef6"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "appium:platformVersion": "11",
                            "appium:udid": "<UDID>",
                            "browserName": "Pixel 5",
                            "platformName": "ANDROID"
                        }
                    },
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "81b1fd2e-c9c5-42d0-9cbc-b546e90ac483"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "appium:platformVersion": "14.2",
                            "appium:udid": "<UDID>",
                            "browserName": "iPhone 12",
                            "platformName": "IOS"
                        }
                    },
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "12e4a5bf-a7be-4858-a74e-a39a3684dc92"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "appium:platformVersion": "10",
                            "appium:udid": "<UDID>",
                            "browserName": "Samsung SM_G780F",
                            "platformName": "ANDROID"
                        }
                    },
                    {
                        "id": {
                            "hostId": "50166c95-e505-4f71-af77-3994b864a39a",
                            "id": "b80a158d-0073-4118-a37b-fb4696701a2e"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "appium:platformVersion": "10",
                            "appium:udid": "<UDID>",
                            "browserName": "Samsung SM_G973F",
                            "platformName": "ANDROID"
                        }
                    }
                ]
            }
        ]
    }
}
```

I replaced the IP in uri with '\<IP>' and the UDIDs with '\<UDID>'.

**Comment by Trigtrig** [comment]
> Can you share the contents of your `config.toml` please?

```
[node]
# detect-drivers = false

[relay]
# default Appium server endpoint
url = "http://localhost:4723"
status-endpoint = "/status"

# Stereotypes supported by the service
configs = [
    "1", '{"appium:udid": "<UDID>", "browserName": "Pixel 5", "platformName": "android", "appium:platformVersion": "11"}',
    "1", '{"appium:udid": "<UDID>", "browserName": "Samsung SM_G973F", "platformName": "android", "appium:platformVersion": "10"}',
    "1", '{"appium:udid": "<UDID>", "browserName": "Samsung SM_G780F", "platformName": "android", "appium:platformVersion": "10"}',
    "1", '{"appium:udid": "<UDID>", "browserName": "iPhone 11", "platformName": "iOS", "appium:platformVersion": "14.8"}',
    "1", '{"appium:udid": "<UDID>", "browserName": "iPhone 12", "platformName": "iOS", "appium:platformVersion": "14.2"}'
]
```

I replaced the UDIDs with '\<UDID>'.

**Comment by diemol** [comment]
This seems to happen because the `status-endpoint` stops responding with a 200 and the Node goes `DOWN`, however the Node keeps sending a heartbeat so it gets registered again. This cycle repeats until the Distributor gets into a state of not being able to continue. 

I've made a fix to avoid registering the Node when it is `DOWN`. It will be available in a couple of days.

**Comment by Trigtrig** [comment]
Hi @diemol, unfortunately the bug is not fixed with Selenium 4.4.0 (revision e5c75ed026a). The GraphQL endpoint is still not responding after approx. 24 hours. This happens reproducibly with the Docker setup (see first comment) as well as with the Selenium server on Mac.

I have additionally changed the configuration on the Mac so that Appium is no longer present. Here is the new config.toml for this:

```
[node]
#detect-drivers = false
```

This is what that minimal setup looks like now:
<img width="645" alt="Selenium Grid Mac mimimal" src="https://user-images.githubusercontent.com/7973740/185142774-c5d31965-3f0b-4f5d-a16d-54f5b016cb56.png">

Still, the GraphQL endpoint stops responding within the 24 hours here as well. This is the ``/status`` endpoint response when GraphQL is no longer responding:

```
{
    "value": {
        "ready": true,
        "message": "Selenium Grid ready.",
        "nodes": [
            {
                "id": "e718dd8a-7954-4b36-8bfb-300ec0e42ef9",
                "uri": "http://<IP>:4444",
                "maxSessions": 1,
                "osInfo": {
                    "arch": "aarch64",
                    "name": "Mac OS X",
                    "version": "12.5"
                },
                "heartbeatPeriod": 60000,
                "availability": "UP",
                "version": "4.4.0 (revision e5c75ed026a)",
                "slots": [
                    {
                        "id": {
                            "hostId": "e718dd8a-7954-4b36-8bfb-300ec0e42ef9",
                            "id": "9727fe01-ec03-47f7-ba01-1ff9cc95f590"
                        },
                        "lastStarted": "1970-01-01T00:00:00Z",
                        "session": null,
                        "stereotype": {
                            "browserName": "safari",
                            "platformName": "MAC"
                        }
                    }
                ]
            }
        ]
    }
}
```

Is there any other information I can provide you to debug?

**Comment by diemol** [comment]
is the `config.toml` only containing that?

Can you share the logs of the Hub?

**Comment by Trigtrig** [comment]
> is the `config.toml` only containing that?

Yes, I just checked again.

> Can you share the logs of the Hub?

I started the grid with the following command ``` selenium-server.jar standalone --config /path/to/config.toml --log-level FINE --log ./hub.log``` and let it run until the GraphQL endpoint stopped responding. This is the log: [hub.log](https://github.com/SeleniumHQ/docker-selenium/files/9413428/hub.log)

**Comment by diemol** [comment]
Why are you querying `/grid/api/hub/`? That endpoint does not exist.

**Comment by Trigtrig** [comment]
The reason is a legacy component of us from the Selenium 3 era. We have several Selenium Grids on the network where we monitor the load of each Grid through ```/grid/api/hub/``` endpoint. This legacy component simply scans certain IPs and tries to reach this endpoint. 

I am aware that ```/grid/api/hub/``` no longer exists in Selenium Grid 4. And we won't be using it anymore when we migrate our Selenium Grids to version 4.

However, I assume that a call to an endpoint that no longer exists should simply trigger an appropriate HTTP status. Or do you suppose that this call has some other effect on the Grid?

**Comment by diemol** [comment]
Are you using a scanning tool on the Grid?

**Comment by Trigtrig** [comment]
The mentioned legacy component is something self-written. But if you like, it can be called a scanning tool for Selenium Grid 3🙂 

I have now excluded the impacted Selenium Grid 4 from the scan to make sure we don't call the non-existent endpoint ```grid/api/hub``` again. I will restart the grid now and watch whether the GraphQL endpoint stops responding again.

**Comment by Trigtrig** [comment]
Sadly, no improvement. The GraphQL endpoint does not respond again.

**Comment by Trigtrig** [comment]
Is SeleniumHQ/selenium#10986 perhaps a related issue?

**Comment by pczerkas** [comment]
I'm observing the same in partial backport of GraphQL to Selenium 3 (back onto servlets) https://github.com/pczerkas/selenium-backports

**Comment by Trigtrig** [comment]
I have now identified the root cause. The company I work for scans its servers daily with Nexpose. Since there are already issues #1646 #1497 #1434  here about this problem, I think this issue can be closed. I will try to report more information in #1646.
