### ISSUE TITLE
Running Protractor with Docker Selenium Grid  + Firefox or Chrome

### ISSUE THREAD

**Issue by nserebry** [SeleniumHQ/docker-selenium#165]
Hi,
I'm currently running into the problem running e2e tests with  **protractor on Docker selenium grid**.
I have setup Selenium Grid locally  with linked firefox browser (both are docker containers)
My protractor.config file contains selenium grid address and browser as firefox 
  ```
exports.config = { seleniumAddress: 'http://192.168.99.100:4444/wb/hub', 
multiCapabilities: [ { browserName: 'firefox' }], baseUrl: "sameUrl"}
```
Test run failing with error 

```
 var template = new Error(this.message);
                  ^
 UnknownError:  <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
Error 405 
HTTP ERROR: 405
Problem accessing /wb/hub/session/null. Reason:
  Http method DELETE is not supported by this URL
[launcher] Process exited with error code 1
>> Exited with code: 1.
Warning: Task "exec:runProtractor" failed. Use --force to continue.
```

I'm new to this kind of setup : selenium grid + docker  and probably missing something . tried to google and stackoverflow but no luck for above error.   Maybe someone had a similar problem ? 
Thank you in advance.

**Comment by elgalu** [comment]
The problem is that you should be testing your AngularJS page not selenium page, check your [baseUrl](https://github.com/angular/protractor/blob/fa0c692414fa98721dff80202ef95e9b3ccadebb/docs/referenceConf.js#L199) and remember that localhost inside the docker container is not the same as your Mac localhost where your app is probably running in development mode.

**Comment by nserebry** [comment]
hi @elgalu thank you for your reply. the above baseUrl was the just an example. Can you please help, It seems like I do not fully understand how it should be setup. 
1. I have two docker containers: hub and chrome/firefox.
2. I'm trying locally to start the protractor e2e test 
3. My baseUrl is == my qa env (e2e tests are working, but not with current setup)
I can reach the qa Url from the docker container.

The test failure I'm getting is :
Failures:
```
  1) SignupPage should be able to redirect to the signup page url with the correct title 
   Message:
     Error while waiting for Protractor to sync with the page: "<html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.50.0<br>Find help on the official selenium wiki : <a href='https://github.com/SeleniumHQ/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>"
   Stacktrace:
     undefined
```
thank you again.

**Comment by elgalu** [comment]
You need to `browser.get('yourAngularJSpageURL!');` before starting your expectations.

This is not a docker-selenium issue, if you have problems using Protractor please consider opening those issues in https://github.com/angular/protractor/issues/
