### ISSUE TITLE
live preview issue with Selenium Grid 4 in kubernetes 

### ISSUE THREAD

**Issue by balajig18** [SeleniumHQ/docker-selenium#1651]
### What happened?

Hi Team,

We have deployed Selenium Grid 4 in our kubernetes cluster. When we trying to access live preview, we getting black page in UI  

In Chrome node logs, we getting messages like Rejecting request with non local origin.

Grid Url - https://v1-selenium-grid.testenv.domain.com/

### Command used to start Selenium Grid with Docker

```shell
Kubernetes deployment
```

### Relevant log output

```shell
Rejecting request with non local origin https://v1-selenium-grid.testenv.domain.com/
```

### Operating System

Linux

### Docker Selenium version (tag)

4.3.0

**Comment by diemol** [comment]
We cannot do much with such little information. When the noVNC request is sent, something should be logged in the Node. Please provide the complete Hub and Node logs.

**Comment by balajig18** [comment]
I'm unable share the entire logs because of security reasons.

When trying to open live preview link in UI.

I'm seeing below error in Chrome node pod.

HTTP/1.1 500 Internal Server Error. Host header or Origin header is specified and is not whitelisted or localhost.

In the vnc request, I'm seeing origin and host headers pointing to https://v1-selenium-grid.testenv.domain.com

**Comment by diemol** [comment]
OK. We cannot do much without logs. Let us know if you can share them or if we should close this issue.

**Comment by lirany1** [comment]
@balajig18 can you share your selenium-hub and selenium-node-chrome values.yaml?
BTW did you implemented using helm?

**Comment by diemol** [comment]
Closing as no more information was provided.
