### ISSUE TITLE
run SE_OPTS=-htmlsuite

### ISSUE THREAD

**Issue by lindsaymacvean** [SeleniumHQ/docker-selenium#166]
How could i pass the htmlsuite flag to the container. I have tried:

docker run -d -P -v=/hostdir selenium/standalone-firefox-debug SE_OPTS=-htmlsuite *firefox http://site.com suite.html .results.html

And this returned

a62a22900e1fe12f90130dec4114e553dd727769892fa07a437be2c544001a03
Error response from daemon: Cannot start container a62a22900e1fe12f90130dec4114e553dd727769892fa07a437be2c544001a03: [8] System error: exec: "SE_OPTS=-htmlsuite": executable file not found in $PATH

**Comment by Deseao** [comment]
You need to pass it as an environment variable, like docker run -e SE_OPTS=htmlsuite

**Comment by rubytester** [comment]
You may not want to give the whole world access to your private intranet. 

you run docker container and asking it to execute SE_OPTS program

Please review docker information on how docker run invocation sequence works. Docker website has lots of examples on how to start docker images as containers.

**Comment by lindsaymacvean** [comment]
thanks noted, stupid mistake. It was a dummy site anyway but will be locking that down.

**Comment by diemol** [comment]
Closing this issue as it should be solved based on the comment above.
