### ISSUE TITLE
[🐛 Bug]: 4.4.0 much slower than 4.3.0

### ISSUE THREAD

**Issue by brondsem** [SeleniumHQ/docker-selenium#1661]
### What happened?

One of our test suites got much slower on docker-selenium 4.4.0.  Previously on 4.3.0 and before, it took about 20 minutes and when run on 4.4.0 it takes about an hour.  This test suite uses [Gemini](https://gemini-testing.github.io/) to generate screenshots.  Interestingly, a different test suite that uses python selenium (v4.3.0) did not experience any slowdowns when swapping the docker-selenium version.  Maybe that gives a clue?  Both test suites use Chrome.  I know Gemini is an older tool, so maybe it uses some old APIs compared to what selenium 4 prefers, and the older stuff is slow?  Sorry that's as good of a guess as I have.

### Command used to start Selenium Grid with Docker

```shell
docker run -p 4444:4444 -p 5900:5900 -p 7900:7900 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
```

### Relevant log output

```shell
none
```

### Operating System

CentOS

### Docker Selenium version (tag)

4.4.0-20220812

**Comment by diemol** [comment]
Thanks for reporting this, I will consolidate it with https://github.com/SeleniumHQ/selenium/issues/10984.
