### ISSUE TITLE
[🐛 Bug]: WebGL doesn't work 

### ISSUE THREAD

**Issue by eltos85** [SeleniumHQ/docker-selenium#1664]
### What happened?

Hello everyone
WebGL stopped working after the 100.0th version of chrome. The tested content started giving the error "Enable WebGL". I tried both virtual displays and different magic, nothing helps. Rolled back /selenium/standalone-chrome to version 100 and everything worked. Help please.

Starting the container:
docker run -d -p 4444:4444 --name MOB -e SE_SESSION_REQUEST_TIMEOUT=500 -e JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= -e SE_NODE_MAX_SESSIONS=5 -e SE_NODE_OVERRIDE_MAX_SESSIONS=true --shm-size=2g selenium/standalone-chrome:100.0

Driver Settings:
options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-notifications")
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("disable-infobars")
    options.add_argument("--disable-extensions")
    options.add_argument("--no-proxy-server")
    options.add_argument("--whitelisted-ips=''")
    chrm_caps = DesiredCapabilities.CHROME.copy()
    chrm_caps['goog:loggingPrefs'] = {'performance': 'ALL'}
    options.add_argument(
        '--user-agent=Mozilla/5.0 (Linux; Android 10; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36')
    driver = webdriver.Remote("http://localhost:4444/wd/hub", desired_capabilities=chrm_caps, options=options)

    driver.implicitly_wait(5)
    driver.set_window_size(400, 900)
    yield driver
    driver.close()

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 --name MOB -e SE_SESSION_REQUEST_TIMEOUT=500 -e JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= -e SE_NODE_MAX_SESSIONS=5 -e SE_NODE_OVERRIDE_MAX_SESSIONS=true --shm-size=2g selenium/standalone-chrome:100.0
```

### Relevant log output

```shell
.
```

### Operating System

Ubuntu, Debian

### Docker Selenium version (tag)

101

**Comment by cocorossello** [comment]
Have you tried with chrome 104? I had the same problem and it works with chrome >= 104

**Comment by diemol** [comment]
Closing as this is a Chrome issue and it seems it works in Chrome 104 again.

**Comment by frossigneux** [comment]
WebGL seems to not work again.
I need to record the browser (from Video container) with WebGL working in Chrome.
Xvfb is not compatible with WebGL. Is there a workaround?

I saw this PR https://github.com/SeleniumHQ/docker-selenium/pull/319 but it is not clear if video recording can work.
