### ISSUE TITLE
[🚀 Feature]: Allow to overwrite SE_NODE_STEREOTYPE

### ISSUE THREAD

**Issue by schmetzyannick** [SeleniumHQ/docker-selenium#1665]
### Feature and motivation

We wanted to set an applicationName in the stereotype of the node. Currentry it seems that the env variable will be overwritten, no matter what is set by the user: https://github.com/SeleniumHQ/docker-selenium/blob/3c74143ea1ec48eef1aad8d4066d7a5ea3dd8c65/NodeBase/generate_config#L62

It would be great if we had the possibility to set this variable.

### Usage example

Would provide a possibility to perform this:
https://www.selenium.dev/documentation/grid/configuration/toml_options/#setting-custom-capabilities-for-matching-specific-nodes

**Comment by diemol** [comment]
Would you like to send a pull request for this?

**Comment by schmetzyannick** [comment]
Sure

**Comment by schmetzyannick** [comment]
Done, testing it now: https://github.com/SeleniumHQ/docker-selenium/pull/1666

**Comment by diemol** [comment]
PR was merged
