### ISSUE TITLE
[🐛 Bug]: standalone-chrome as GitLab CI service not working from v104

### ISSUE THREAD

**Issue by sabadroiback** [SeleniumHQ/docker-selenium#1675]
### What happened?

I'm using `selenium/chrome-standalone` Docker image as a service in my GitLab CI for functional testing using Cucumber and Selenium. It was working great up to `selenium/chrome-standalone:103.0`, but upgrading to `selenium/chrome-standalone:104.0` or higher makes tests fail. Is there any breaking change between those version that I should keep in mind to apply changes on my code?

### Command used to start Selenium Grid with Docker

```shell
# GitLab CI configuration

functional_tests:
  image: node:14-alpine
  services:
    - name: selenium/standalone-chrome:105.0
      alias: selenium
  variables:
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
  script:
    - node tests/functional

# Driver configuration
{
    driver: 'server',
    driverServer: 'http://selenium:4444/wd/hub',
    driverCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['ignore-certificate-errors']
        }
    }
}
```

### Relevant log output

```shell
# It fails right after starting with the tests
Error: function timed out after 10000 milliseconds
```

### Operating System

GitLab CI

### Docker Selenium version (tag)

selenium/chrome-standalone:104.0

**Comment by jamesmortensen** [comment]
Hi @sabadroiback would you be able to supply us with a minimal example, in a public GitLab repo, that we can use to reproduce the problem?  I'm also curious to see if you get the same problem with selenium/standalone-chrome:dev and beta.

**Comment by sabadroiback** [comment]
Hello @jamesmortensen, I've just tried it and it is working with `selenium/standalone-chrome:dev`, but not with `selenium/standalone-chrome:beta`. Any idea? I will try to generate a minimal example, but it can take a while.

**Comment by jamesmortensen** [comment]
The current dev channel for Chrome Dev browser version:  Google Chrome 107.0.5300.0 dev.
And for the beta channel:  Google Chrome 106.0.5249.40

If the problem happens on Chrome 104, 105, and 106 but not 107, then it suggests that Google may have fixed whatever the problem is, and that the fix should be released in a month or two when 107 stabilizes and moves to Beta and then Stable.

Is there any other relevant log output which suggests what might be leading to the timeout?

**Comment by sabadroiback** [comment]
Thanks a lot for your help! There's no other relevant log output, so I'll wait for version 107 to be released and I will test then if the issue is solved.
