### ISSUE TITLE
[🚀 Feature]: Auto scaling Seleniun Grid running in Kubernetes using KEDA

### ISSUE THREAD

**Issue by prashanth-volvocars** [SeleniumHQ/docker-selenium#1688]
### Feature and motivation

Auto scaling selenium grid was a problem that was pending to be solved for long. So i took it up when there was a requirement at current my work place. KEDA seemed to the best candidate for the Job and i wrote a new scalar for Selenium Grid a year ago. I would like to have this enabled by default in our charts. But i am not sure how to make it a part of the current setup. I have shared my whole setup [here](https://github.com/prashanth-volvocars/docker-selenium/tree/auto-scaling).

Any suggestions on how to make this part of the default helm charts and docker images would be great. I would want this to be a part of this repo so it could benefit others.

### Usage example

You can grab all information about the setup [here](https://medium.com/@rprashanth27/auto-scaling-selenium-grid-using-keda-easy-way-out-97d7f7d19a35)

On a nutshell, It can

- Auto Scale browser nodes up and down.
- Record videos and store them named under session id
- Capture logs and store them named under session id
- Upload captured logs and videos to S3

**Comment by jamesmortensen** [comment]
Hi @prashanth-volvocars It looks like you forked and made the changes already, so why don't you open a pull request. That will make it easier for us to review the changes, give feedback, and hopefully get the changes merged.

**Comment by prashanth-volvocars** [comment]
Hi @jamesmortensen 

Sure i have raised a pull request https://github.com/SeleniumHQ/docker-selenium/pull/1689 with the above mentioned changes

**Comment by abhitrivedi2006** [comment]
Hi @prashanth-volvocars .. I have deployed your solution on AKS. I have intentionally set Keda max chrome count to 15 Pods. expecting hub to hold the tests in the queue and once slots are available then submit jobs to them.

when looked at the logs I see below msg which I am not able to understand as where are setting up this .. also attaching full logs from Hub.. 


Unable to create session: Could not start a new session. Could not start a new session. **Max session count reached.**



{"class": "SeleniumSpanExporter$1","log-level": "WARNING","log-message": "{\"traceId\": \"19c0c1b38424816c7c84bb15a3364879\",\"eventTime\": 1665152671099678865,\"eventName\": \"exception\",\"attributes\": {\"exception.message\": \"_Unable to create session: Could not start a new session. Could not start a new session. Max session count reached._\\nBuild info: version: '4.3.0', revision: 'a4995e2c09*'\\nSystem info: host: 'selenium-chrome-node-6b5cb59f79-swpjn', ip: '10.250.1.122', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1090-azure', java.version: '11.0.16'\\nDriver info: driver.version: unknown \\nHost info: host: 'selenium-hub-5945f7d875-knq64', ip: '10.250.0.138'\\nBuild info: version: '4.5.0', revision: 'fe167b119a'\\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1090-azure', java.version: '11.0.16'\\nDriver info: driver.version: unknown\",\"exception.stacktrace\": \"org.openqa.selenium.RetrySessionRequestException: Could not start a new session. Could not start a new session. Max session count reached.\\nBuild info: version: '4.3.0', revision: 'a4995e2c09*'\\nSystem info: host: 'selenium-chrome-node-6b5cb59f79-swpjn', ip: '10.250.1.122', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1090-azure', java.version: '11.0.16'\\nDriver info: driver.version: unknown \\nHost info: host: 'selenium-hub-5945f7d875-knq64', ip: '10.250.0.138'\\nBuild info: version: '4.5.0', revision: 'fe167b119a'\\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1090-azure', java.version: '11.0.16'\\nDriver info: driver.version: unknown\\n\\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:148)\\n\\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:639)\\n\\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:558)\\n\\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:812)\\n\\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)\\n\\tat java.base\\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\\n\\tat java.base\\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\\n\\tat java.base\\u002fjava.lang.Thread.run(Thread.java:829)\\n\",\"exception.type\": \"org.openqa.selenium.RetrySessionRequestException\",\"logger\": \"org.openqa.selenium.grid.distributor.local.LocalDistributor\",\"request.payload\": \"[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]\"}}\n","log-name": "org.openqa.selenium.remote.tracing.opentelemetry.SeleniumSpanExporter","log-time-local": "2022-10-07T14:24:31.101Z","log-time-utc": "2022-10-07T14:24:31.101Z","method": "lambda$export$3"}




[abhi (1).log](https://github.com/SeleniumHQ/docker-selenium/files/9735500/abhi.1.log)

**Comment by diemol** [comment]
Implemented via https://github.com/SeleniumHQ/docker-selenium/commit/f0bbfe02c318ac58b8875f8f26c607ca86b9cf42
