### ISSUE TITLE
iron.io microcontainers

### ISSUE THREAD

**Issue by Vanuan** [SeleniumHQ/docker-selenium#169]
Currently, selenium images are huge (700 mb)
Probably, it is possible to shrink that down:
http://www.iron.io/microcontainers-tiny-portable-containers/

**Comment by Vanuan** [comment]
Selenium base images is built on top of ubuntu:15.10
Let's try to replace it with alpine:3.3 (replacing `apt-get install` by `apk add`) and see what happens.

**Comment by Vanuan** [comment]
Oh, this looks to be a duplicate of #161

**Comment by Vanuan** [comment]
[Base image](http://imagelayers.iron.io/?images=selenium%2Fbase:latest) consists of ubuntu (134 mb) and jre (320 mb) and selenium itself (31 mb).

**Comment by Vanuan** [comment]
[Alpine + minimal jre](http://imagelayers.iron.io/?images=iron%2Fjava:latest) is 111 mb, saving us 375 mb!

**Comment by nisaacson** [comment]
+1, dockerhub is moving towards alpine linux as well for the base library images https://www.brianchristner.io/docker-is-moving-to-alpine-linux/

**Comment by jgielstra** [comment]
One issue is alpine uses `musl` for it's c library and it isn't 100% compatible with stuff compiled using `glibc`.

They do have ports of xvfb, chromium, openjdk8, firefox, and chromium-chromedriver  _webdriver_ in their main repo.
  
It doesn't seem stable and I get <defunct> processes but it looks like people are working on it  
     http://git.alpinelinux.org/cgit/aports/log/community/chromium

But something basic: openjdk + chromium + xvfb + chromium webdriver is ~350 megs..

**Comment by Vanuan** [comment]
Yeah, as I wrote, we only save 375 mb.

**Comment by ddavison** [comment]
closing in favor of #224
