### ISSUE TITLE
Tag With Different Browser Version

### ISSUE THREAD

**Issue by danggrianto** [SeleniumHQ/docker-selenium#17]
is it possible to tag the container based on different browser version?

**Comment by rubytester** [comment]
This is an issue for me, I am solving this with 'Freezing' the image in time, Basically I build an image with Chrome:43 and tag the image `node-chrome:43` and never build this tag again unless I know the current active "chrome" version has not advanced yet. 

The con of this is that I need to use this as a base for other downstream images and I can't recreate the image if I wanted to after Chrome releses 44.

**Comment by ddavison** [comment]
You are able to build your own images with specific Firefox and Chrome versions.

I do not plan on releasing different tags with different browser versions considering the maintenance cost of this.  I will bundle all tags with copacetic versions of the browser with the Selenium version.

Please see the wiki page [Building your own images](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images) to see how to do this.
