### ISSUE TITLE
[🚀 Feature]: Exiting container when Standalone or Node exits (on error too)

### ISSUE THREAD

**Issue by DamianFekete** [SeleniumHQ/docker-selenium#1703]
### Feature and motivation

From https://github.com/SeleniumHQ/docker-selenium/pull/1504

> The behaviour we have always had is one where supervisor controls all processes and keeps the container running. This is great because it has improved maintainability and readability. However, when the most important process, the Selenium Server, exits... the container has no purpose anymore. Users need to stop/kill the container themselves.
>
> This change will make the container exit when the Selenium Server process exits.

It would be nice if the container would exit even if the Selenium Server process exits with an error code (e.g. processes is killed because of OOM).

Instead of
```
command=bash -c "/opt/bin/start-selenium-node.sh && kill -s SIGINT `cat /var/run/supervisor/supervisord.pid`"
```
we should have
```
command=bash -c "/opt/bin/start-selenium-node.sh; kill -s SIGINT `cat /var/run/supervisor/supervisord.pid`"
```

### Usage example

K8s will restart the pod if the Selenium Server process is not available anymore.

**Comment by diemol** [comment]
Would you like to send a PR?

**Comment by DamianFekete** [comment]
Yes, sure.
