### ISSUE TITLE
[🚀 Feature]: connect an available session

### ISSUE THREAD

**Issue by demon071** [SeleniumHQ/docker-selenium#1707]
### Feature and motivation

Connect to an existing session and continue working

### Usage example

when opening a session the jobs are done but no driver.quit() statement the session is still running I want to connect to that session and continue using it or is there some way to use it common one browser session for python code runs

**Comment by jamesmortensen** [comment]
Hi. Are you saying that when you're done running one job, the session doesn't end?  Or are you trying to use the same session for all of your tests?  Would you be able to provide an example that highlights the issue you're facing?

**Comment by demon071** [comment]
I found a way to reuse a session if it hasn't ended, i would like to ask is there any way to know if session is making a request or not, by default sessions will close when there is no request for 300 seconds, how to know session is waiting or in use
```python
session_id = random.choice(sessionLists)
            def attach_to_session(executor_url, session_id):
                original_execute = WebDriver.execute
                def new_command_execute(self, command, params=None):
                    if command == "newSession":
                        # Mock the response
                        return {'success': 0, 'value': None, 'sessionId': session_id}
                    else:
                        return original_execute(self, command, params)
                # Patch the function before creating the driver object
                WebDriver.execute = new_command_execute
                driver = webdriver.Remote(command_executor=executor_url, desired_capabilities={})
                driver.session_id = session_id
                # Replace the patched function with original function
                WebDriver.execute = original_execute
                return driver
            driver = attach_to_session('http://127.0.0.1:4444/wd/hub', session_id)
```

**Comment by diemol** [comment]
Right, there is no way to connect to an available session unless you know the session id. There is no easy way to know if the session is idle or not, given that the client end should know that information since it is handling the state.

Seems you have a very specific functionality in your application, so if you have more questions and need community help, feel free to join us in the [IRC/Slack channel](https://www.selenium.dev/support/).
