### ISSUE TITLE
[🚀 Feature]: add nightly build 

### ISSUE THREAD

**Issue by andrewnicols** [SeleniumHQ/docker-selenium#1712]
### Feature and motivation

It would be helpful to have an image containing a nightly build of _selenium_ (with the current latest stable browser version).

Many of us may be able to run such an image in our CI infrastructure and help to discover bugs and issues with selenium before a release is tagged if this we’re available.

### Usage example

In our case we typically run the `selenium/standalone-chrome:latest` and `selenium/standalone-firefox:latest` images, and we are currently planning to add additional builds for the beta tags of these images in the coming weeks. The hope is that this will help us discover any issues with those browsers, or their respective drivers ahead of time.

We would also like to add similar builds for a nightly build of Selenium itself so that we can be more proactive in reporting any issues we encounter as a result _prior_ to the release of that version so that fewer people are impacted by any issues.

**Comment by diemol** [comment]
We do want to have something like that in the near future, like offering a weekly build or so, but so far it is an issue of time, we do not have enough people to do something like this for now.

**Comment by VietND96** [comment]
@diemol, if we pick up binary selenium nightly to build and release images nightly, which tag name is suitable to tag those images?

**Comment by diemol** [comment]
I would use `nightly`

**Comment by VietND96** [comment]
Nightly images delivered via https://github.com/SeleniumHQ/docker-selenium/releases/tag/nightly
Continue to add Nightly for Helm chart and configure tests on nightly images

**Comment by diemol** [comment]
Great, thank you @vietnd96!

This should be mentioned in the readme.

**Comment by VietND96** [comment]
> Great, thank you @vietnd96!
> 
> This should be mentioned in the readme.

Yes, I updated a short description in README for both docker and chart https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#nightly-images
@diemol you can review and put additional if any is missing.

**Comment by diemol** [comment]
Looks good.
