### ISSUE TITLE
Build > 2.50 failed

### ISSUE THREAD

**Issue by arthur-c** [SeleniumHQ/docker-selenium#172]
Hi,

The last successful docker build is 2.50.0 and this one is buggy and unusable (timeouts, issue closed and fix released in 2.50.1).

https://hub.docker.com/r/selenium/hub/builds/

**Comment by jbalbien** [comment]
+1

**Comment by at88mph** [comment]
+1

**Comment by aanisimov** [comment]
+1, No tag was added for selenium/base image of 2.52.0

**Comment by mhemesath** [comment]
+1

**Comment by jeffjk-me** [comment]
https://github.com/SeleniumHQ/docker-selenium/pull/192

**Comment by kayabendroth** [comment]
Fixed with 2.52.0 and 2.53.0.
