### ISSUE TITLE
[🐛 Bug]: Azure Kubernetes Services and Keda Selenium Grid scaler: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by abhitrivedi2006** [SeleniumHQ/docker-selenium#1722]
### What happened?

We are using AKS with Keda Selenium auto scaler for our tests ..Keda scaler seems to be working fine. We are seeing Chrome Pods are going for autoscale. we are seeing now below  exceptions.

java.net.SocketException: Connection reset

Also if we keep all the pods up and running in advance all the tests are working fine.

### Command used to start Selenium Grid with Docker

```shell
Instruction were followed from https://github.com/SeleniumHQ/docker-selenium#deploying-to-kubernetes
```

### Relevant log output

```shell
exception:



java.net.SocketException: Connection reset
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$fsm9NW9G
Command: [40b88db16bea8e9bd87898b05bcc4bf4, getElementText {id=0a2127d5-dea1-45a1-826b-cd9790d27089}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.91, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /tmp/.com.google.Chrome.BeEpBc}, goog:chromeOptions: {debuggerAddress: localhost:34973}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://52.226.210.47:4444/ses..., se:cdpVersion: 106.0.5249.91, se:vnc: ws://52.226.210.47:4444/ses..., se:vncEnabled: true, se:vncLocalAddress: ws://10.250.0.49:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver$ByteBuddy$fsm9NW9G: chrome on LINUX (40b88db16bea8e9bd87898b05bcc4bf4)] -> xpath: //table[@class = 'recentsList']//a[@data-refid = 'recordId']]
Session ID: 40b88db16bea8e9bd87898b05bcc4bf4
```

### Operating System

Azure Kubernetes Services/ Chrome

### Docker Selenium version (tag)

4.5.0-20221004

**Comment by abhitrivedi2006** [comment]
Hub Config.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: selenium-hub
  namespace: selgrid
  uid: d6209415-6bc7-4324-94fe-b5edc50cec78
  resourceVersion: '18607262'
  generation: 10
  creationTimestamp: '2022-10-14T18:13:48Z'
  labels:
    app: selenium-hub
    app.kubernetes.io/component: selenium-grid-4.5.0-20221004
    app.kubernetes.io/instance: selenium-grid
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: selenium-hub
    app.kubernetes.io/version: 4.5.0-20221004
    helm.sh/chart: selenium-grid-0.12.0
  annotations:
    deployment.kubernetes.io/revision: '10'
    meta.helm.sh/release-name: selenium-grid
    meta.helm.sh/release-namespace: selgrid
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: apps/v1
      time: '2022-10-14T18:13:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:app.kubernetes.io/component: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/name: {}
                f:app.kubernetes.io/version: {}
                f:helm.sh/chart: {}
            f:spec:
              f:containers:
                k:{"name":"selenium-hub"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"SE_OPTS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":4442,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":4443,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":4444,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits: {}
                    f:requests: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-08T14:48:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:spec:
              f:containers:
                k:{"name":"selenium-hub"}:
                  f:env:
                    k:{"name":"SE_SESSION_REQUEST_TIMEOUT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"SE_SESSION_RETRY_INTERVAL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:resources:
                    f:limits:
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      f:cpu: {}
                      f:memory: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-08T14:48:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
      app.kubernetes.io/instance: selenium-grid
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium-hub
        app.kubernetes.io/component: selenium-grid-4.5.0-20221004
        app.kubernetes.io/instance: selenium-grid
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/name: selenium-hub
        app.kubernetes.io/version: 4.5.0-20221004
        helm.sh/chart: selenium-grid-0.12.0
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.5.0-20221004
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
          env:
            - name: SE_OPTS
              value: >-
                --log-level INFO --structured-logs true --http-logs true
                --plain-logs false
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: '1800'
            - name: SE_SESSION_RETRY_INTERVAL
              value: '20'
          resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '2'
              memory: 8Gi
          livenessProbe:
            httpGet:
              path: /readyz
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 12
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-11-08T01:11:33Z'
      lastTransitionTime: '2022-11-08T01:11:33Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-11-08T14:48:27Z'
      lastTransitionTime: '2022-10-14T18:13:48Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "selenium-hub-6bdc8475f9" has successfully progressed.

**Comment by abhitrivedi2006** [comment]
Chrome config

kind: Pod
apiVersion: v1
metadata:
  name: selenium-chrome-node-5d445df794-jbdqc
  generateName: selenium-chrome-node-5d445df794-
  namespace: selgrid
  uid: d614adc7-4050-49c1-abda-f09e1308fe30
  resourceVersion: '19180800'
  creationTimestamp: '2022-11-09T17:01:45Z'
  labels:
    app: selenium-chrome-node
    app.kubernetes.io/component: selenium-grid-4.5.0-20221004
    app.kubernetes.io/instance: selenium-grid
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: selenium-chrome-node
    app.kubernetes.io/version: 4.5.0-20221004
    helm.sh/chart: selenium-grid-0.12.0
    pod-template-hash: 5d445df794
  annotations:
    checksum/event-bus-configmap: a0d6542fd55c53ee0aca5194f7477f2516ea51a04ffa966b5d05f37622496f26
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: selenium-chrome-node-5d445df794
      uid: 72b1dc1d-3c1c-4922-9c3b-5ca14c8b403a
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-11-09T17:01:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:checksum/event-bus-configmap: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"72b1dc1d-3c1c-4922-9c3b-5ca14c8b403a"}: {}
        f:spec:
          f:containers:
            k:{"name":"selenium-chrome-node"}:
              .: {}
              f:envFrom: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:lifecycle:
                .: {}
                f:preStop:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":5555,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:protocol: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:startupProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/dev/shm"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"dshm"}:
              .: {}
              f:emptyDir:
                .: {}
                f:medium: {}
                f:sizeLimit: {}
              f:name: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-11-09T17:01:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.250.0.53"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
    - name: kube-api-access-rvrgk
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: selenium-chrome-node
      image: selenium/node-chrome:4.5.0-20221004
      ports:
        - containerPort: 5555
          protocol: TCP
      envFrom:
        - configMapRef:
            name: selenium-event-bus-config
      env:
        - name: NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME
          value: aks-sel-poc001
        - name: NEW_RELIC_METADATA_KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NEW_RELIC_METADATA_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME
          value: selenium-chrome-node
        - name: NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME
          value: selenium/node-chrome:4.5.0-20221004
        - name: NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME
          value: selenium-chrome-node
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: kube-api-access-rvrgk
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      startupProbe:
        httpGet:
          path: /status
          port: 5555
          scheme: HTTP
        timeoutSeconds: 60
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 120
      lifecycle:
        preStop:
          exec:
            command:
              - bash
              - '-c'
              - >
                curl -X POST 127.0.0.1:5555/se/grid/node/drain --header
                'X-REGISTRATION-SECRET;' && \

                while curl 127.0.0.1:5555/status; do sleep 1; done; sleep 10;
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 3600
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: aks-selenium-74602795-vmss000073
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-09T17:01:45Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-09T17:01:50Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-09T17:01:50Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-09T17:01:45Z'
  hostIP: 10.250.0.33
  podIP: 10.250.0.53
  podIPs:
    - ip: 10.250.0.53
  startTime: '2022-11-09T17:01:45Z'
  containerStatuses:
    - name: selenium-chrome-node
      state:
        running:
          startedAt: '2022-11-09T17:01:46Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: docker.io/selenium/node-chrome:4.5.0-20221004
      imageID: >-
        docker.io/selenium/node-chrome@sha256:eaff1dbccfbfec514e38b8e3035d0f68661ad86071a3efe506d15de3beb0fc0b
      containerID: >-
        containerd://84be5545183c8945b82cabbaa2463e7924feb3d4e091230ee26af72561edfcf0
      started: true
  qosClass: Guaranteed

**Comment by abhitrivedi2006** [comment]
Chrome Env:

  SE_DRAIN_AFTER_SESSION_COUNT: '1'
  SE_EVENT_BUS_HOST: selenium-hub
  SE_EVENT_BUS_PUBLISH_PORT: '4442'
  SE_EVENT_BUS_SUBSCRIBE_PORT: '4443'
  SE_NODE_GRID_URL: http://<<EXTERNALIP of HUB>>:4444 
  SE_NODE_SESSION_TIMEOUT: '600'

**Comment by abhitrivedi2006** [comment]
[hub (1).log](https://github.com/SeleniumHQ/docker-selenium/files/9984902/hub.1.log)

sometime also getting .

org.openqa.selenium.NoSuchSessionException: Unable to execute request for an existing session: Unable to find session with ID: 383828aaeb64ed1033856dbcecdeb141
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1090-azure', java.version: '11.0.16'
Driver info: driver.version: unknown
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.19.1.el8_6.x86_64', java.version: '17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$4L8FgEQR
Command: [383828aaeb64ed1033856dbcecdeb141, findElements {using=xpath, value=//div[@data-test = 'landing:boardSubmittalCount']/h3}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.91, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /tmp/.com.google.Chrome.U0wlOs}, goog:chromeOptions: {debuggerAddress: localhost:35293}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://20.81.3.213:4444/sessi..., se:cdpVersion: 106.0.5249.91, se:vnc: ws://20.81.3.213:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://10.250.1.55:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 383828aaeb64ed1033856dbcecdeb141
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$12(RemoteWebDriverBuilder.java:450)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$13(RemoteWebDriverBuilder.java:456)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$14(RemoteWebDriverBuilder.java:460)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.lambda$createExecutor$15(RemoteWebDriverBuilder.java:469)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:179)
	at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:102)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:372)
	at com.framework.utils.AllegisDriver.findElements(AllegisDriver.java:283)
	at grid.pages.connected.RedZonePage.getBoardSubmittalCount(RedZonePage.java:116)
	at grid.tests.connected.SalesforceTests11.salesforceTest(SalesforceTests11.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by diemol** [comment]
Is this happening after upgrading to 4.6.0? 

Is this the first time this happens?

**Comment by abhitrivedi2006** [comment]
we haven't upgraded to 4.6 yet. its very intermittent.

**Comment by abhitrivedi2006** [comment]
We stopped seeing this after increasing SE_SESSION_REQUEST_TIMEOUT value.
