### ISSUE TITLE
[🐛 Bug]: Selenium-hub ignoring parameters GRID_BROWSER_TIMEOUT and "GRID_TIMEOUT"

### ISSUE THREAD

**Issue by Schtil** [SeleniumHQ/docker-selenium#1724]
### What happened?

Good day!
I'm trying to set server timeouts for a browser session.
So that when the set value is exceeded, the session is terminated by a timeout.
Having searched in the current issues, I found parameters GRID_BROWSER_TIMEOUT and GRID_TIMEOUT.
However, they seem to be ignored.
Sessions continue to live.
Tell me where am I wrong?

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/51741271/201472307-370dcf66-7ff3-4477-8536-1b9315af89c4.png">

### Command used to start Selenium Grid with Docker

```shell
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=5
      - GRID_BROWSER_TIMEOUT=30
      - GRID_TIMEOUT=30
```

### Relevant log output

```shell
-
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.3.0-20220726

**Comment by diemol** [comment]
They are not valid for Grid 4, please check https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes.

**Comment by Schtil** [comment]
@diemol 
I also tried `SE_NODE_SESSION_TIMEOUT`
Which is listed in the documentation

> Containers can be further configured through environment variables, such as SE_NODE_SESSION_TIMEOUT and SE_OPTS.
> When a child container is created, all environment variables prefixed with SE_ will be forwared and set in the container. 
> You can set the desired environment variables in the standalone-docker or node-docker containers. 
> The following example sets the session timeout to 700 seconds for all sessions:

Nothing changed

```                                                    
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=30
  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=5
      - SE_NODE_SESSION_TIMEOUT=30
