### ISSUE TITLE
[🐛 Bug]: docker-compose-v3.yml and docker-compose-v3-full-grid-swarm.yml are the same

### ISSUE THREAD

**Issue by arp-mbender** [SeleniumHQ/docker-selenium#1727]
### What happened?

Seems like the files `docker-compose-v3.yml` and `docker-compose-v3-full-grid-swarm.yml` are the same. Based on the name the latter should fire up the full grid setup...

### Command used to start Selenium Grid with Docker

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Docker Selenium version (tag)

N/A

**Comment by diemol** [comment]
Just reread this, the files are different, one is meant to be used for Docker Swarm, while the other is with docker-compose.
