### ISSUE TITLE
[🐛 Bug]: The docker container selenium/video:ffmpeg-4.3.1-20221202 make my docker crashed

### ISSUE THREAD

**Issue by RichMan-Yi** [SeleniumHQ/docker-selenium#1738]
### What happened?

My steps
- Create selenium container
- Create selenium-video container
- Run my test
  - When the test process start to run on Selenium, my Docker Desktop will crash.
 
This is not happening when I downgrade to selenium/video:ffmpeg-4.3.1-20221104

### Command used to start Selenium Grid with Docker

```shell
docker network create selenium-net
docker container prune -f
docker run -d --net selenium-net --name selenium \
  -p 4444:4444 --shm-size="2g" \
  -e SE_NODE_GRID_URL=http://localhost:4444 \
  -e SE_VNC_NO_PASSWORD=1 \
  selenium/standalone-chrome:107.0
docker run -d --net selenium-net --name video \
  -v /Users/alexander.yi/Storage/docker-selenium-video:/videos \
  selenium/video:ffmpeg-4.3.1-20221202

# Execute my testing process
# And Docker Desktop crashed
```

### Relevant log output

```shell
No, Docker Desktop just stopped and unable to restart.
```

### Operating System

macOS 13.0.1 (22A400)

### Docker Selenium version (tag)

selenium/standalone-chrome:107.0

**Comment by diemol** [comment]
How can we recreate the issue? Can you share execution logs? Does this happen in any other machines or just yours?

**Comment by RichMan-Yi** [comment]
I was running Selenium with JAVA Serenity.
But I guess arbitrary way can recreate this issue.
Or maybe I gotta find out where the docker log located in Mac

**Comment by diemol** [comment]
I cannot recreate the issue, so please let us know how it goes after trying in a different machine. Please share the logs as well.

**Comment by RichMan-Yi** [comment]
currently cannot find anything useful in files below
~/Library/Containers/com.docker.docker/Data/log/vm/dockerd.log
~/Library/Containers/com.docker.docker/Data/log/vm/containerd.log

I'll try some other machine later.
And btw selenium/video:ffmpeg-4.3.1-20221208 won't trigger this issue (just one try though)
And selenium/video:ffmpeg-4.3.1-20221104 triggered this issue as well, but it's like 1/50 (only happened once)

**Comment by RichMan-Yi** [comment]
btw I found my Docker Desktop just keep crashing now, no matter video container is started or not...
so maybe it's other problem, for not I just give up Docker Desktop and try some other alternative

**Comment by diemol** [comment]
We would have more issue reports regarding this particular case. I'll gladly reopen if more data shows that it is related to the images we offer.
