### ISSUE TITLE
[🐛 Bug]: Change default Font

### ISSUE THREAD

**Issue by uzvaio** [SeleniumHQ/docker-selenium#1742]
### What happened?

Hello guys.
I am running latest docker image. everything is ok. i just wanted to change font of the chrome for taking screenshots.
I have changed the font in settings, it is ok, but when i run python tests, it uses the default font! 
i have used this in my docker when running : 
-v /usr/share/fonts/:/usr/share/fonts/truetype/host/
so the container has access to my font.

thanks.

### Command used to start Selenium Grid with Docker

```shell
docker run -d \
	--name selenium \
	--restart always \
	--shm-size="1g" \
	-p 127.0.0.1:7900:7900 \
	-e SE_SCREEN_WIDTH=1366 \
	-e SE_SCREEN_HEIGHT=768 \
	-e SE_SCREEN_DEPTH=24 \
	-e SE_NODE_SESSION_TIMEOUT=30 \
	-v /home/:/home/seluser/files \
	-v /usr/share/fonts/:/usr/share/fonts/truetype/host/ \
	selenium/standalone-chrome:4.7.0-20221202
```

### Relevant log output

```shell
no output
```

### Operating System

ubuntu 20.04

### Docker Selenium version (tag)

4.7.1-20221208

**Comment by diemol** [comment]
You need to install the font in the docker image, mounting them is not enough.
