### ISSUE TITLE
[🐛 Bug]: Downloaded files are not copying into linux machine for dynamic grid setups

### ISSUE THREAD

**Issue by Audithya1990** [SeleniumHQ/docker-selenium#1747]
### What happened?

We setup a dynamic grid by adding a volume folders to the nodes. But the downloaded files are not copying into the linux machines from dynamic nodes.

Steps we followed:
1. Created a folder in linux server and gave owner permission as 1200: 1201
2. Provided volume mapping folders `-v /mnt/vol0/jenkins/downloaded_files:/home/seluser/Downloads` when creating dynamic nodes
 
We verified the downloaded path in dynamic nodes for the chrome browsers by taking screenshots and it showed as "/home/seluser/Downloads" but still the files are not copying into the linux machines
<img width="668" alt="image" src="https://user-images.githubusercontent.com/40178095/208110187-78c76816-f12b-4329-81b3-77ecd531c954.png">

### Command used to start Selenium Grid with Docker

```shell
docker network create grid

docker run -d -p 4442-4444:4442-4444 -e GRID_TIMEOUT=30000 -e GRID_BROWSER_TIMEOUT=30000 --net grid --name selenium-hub selenium/hub:4.5.3-20221024

docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v ${PWD}/config.toml:/opt/bin/config.toml -v ${PWD}/assets:/opt/selenium/assets -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/vol0/jenkins/downloaded_files:/home/seluser/Downloads selenium/node-docker:4.5.3-20221024
```

### Relevant log output

```shell
[root@***** downloaded_files]# pwd
/mnt/vol0/jenkins/downloaded_files
[root@***** downloaded_files]# ll
total 0
```

### Operating System

centos8

### Docker Selenium version (tag)

4.5.3-20221024

**Comment by Audithya1990** [comment]
Volume mapping is working fine for normal hub and node setup but it is not working for dynamic grids

**Comment by diemol** [comment]
A few things:
- This functionality has been implemented recently but it does not work through mounting volumes to containers. We decided to avoid that approach to enable the feature out of the box in other environments (like Kubernetes).
- `GRID_TIMEOUT`, `GRID_BROWSER_TIMEOUT` do not exist for Docker images in Grid 4. For all supported ones, please refer to the [Dynamic Grid docs](https://github.com/SeleniumHQ/docker-selenium#dynamic-grid).
- As mentioned, this was very recently implemented (big thanks to @krmahadevan), and the [docs](https://www.selenium.dev/documentation/grid/configuration/cli_options/#specifying-path-from-where-downloaded-files-can-be-retrieved) about it were recently merged.
