### ISSUE TITLE
[🐛 Bug]: docker-selenium cannot config language

### ISSUE THREAD

**Issue by chenkehao1998** [SeleniumHQ/docker-selenium#1749]
### What happened?

I use java to connect to the remote chrome.
And I set the language to chinese.
But it will not change the language of chrome in docker.

### Command used to start Selenium Grid with Docker

I start chrome with docker
```
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome
```
the code is
```         
DesiredCapabilities desiredCap = DesiredCapabilities.chrome();             
ChromeOptions op = new ChromeOptions();             
op.addArguments("--lang=zh-CN");             
desiredCap.setCapability("chromeOptions", op);             
driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), desiredCap);
```
```


### Operating System

all

### Docker Selenium version (tag)

latest

**Comment by chenkehao1998** [comment]
the  accept-language of request header is en-us

**Comment by diemol** [comment]
You are missing the `goog:` prefix.
It should be `desiredCap.setCapability("good:chromeOptions", op);`

**Comment by chenkehao1998** [comment]
I used
```
desiredCap.setCapability(ChromeOptions.CAPABILITY, options);
```

`ChromeOptions.CAPABILITY` is `"goog:chromeOptions"`

but it also doesn't work.

When I config it to chrome not in docker, it works.

**Comment by jsa34** [comment]
I have just had a PR merged which should resolve this issue with Chrome and Edge.
