### ISSUE TITLE
Question : How to initialize standalone version?

### ISSUE THREAD

**Issue by pavelpp** [SeleniumHQ/docker-selenium#175]
I've run in terminal
`docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:2.52.0` 

which has given me some kind of id, now what? How do I tell selenium to use this driver? I'm using selenide, which is a wrapper around selenium. Appreciate any help

**Comment by pavelpp** [comment]
OK, I've passed remote url to selenide via Configuration.remote="http://localhost:4444/ws/hub" , but still getting the UnreachableBrowserException

**Comment by elgalu** [comment]
quoting `http://localhost:4444/ws/hub` is `wd` not `ws`

**Comment by pavelpp** [comment]
just a typo, sorry, I do have "wd" actually

**Comment by elgalu** [comment]
please paste the whole log from test start to bottom error, if too large put it on a gist.github.com

**Comment by pavelpp** [comment]
https://gist.github.com/pavelpp/84bb5ea0b5fcc8ceca7f

**Comment by elgalu** [comment]
try to change localhost with the result of `boot2docker ip` or `docker-machine ip default` in `http://localhost:4444/wd/hub`

**Comment by pavelpp** [comment]
amazingly that worked

**Comment by elgalu** [comment]
cool, so works with `localhost` if you are on Linux, when I saw your logs figured out you were on OSX and in that case docker uses a Linux VM to run docker so is a different IP

**Comment by pavelpp** [comment]
ah, ok, so I assume when I run this on Jenkins with linux, it should work with localhost?

**Comment by elgalu** [comment]
exactly
