### ISSUE TITLE
[🐛 Bug]: Session capbility not generating in asset folder in dynamic selenium grid for firefox browser

### ISSUE THREAD

**Issue by ATTO-RATHORE** [SeleniumHQ/docker-selenium#1752]
### What happened?

Session capbility json file nt generating in asset folder for each session folder in dynamic selenium grid for firefox browser

### Command used to start Selenium Grid with Docker

```shell
FirefoxProfile prof = new FirefoxProfile();
	      prof.setPreference("layout.css.devPixelsPerPx", "0.90");
		  FirefoxOptions options = new FirefoxOptions();
		  options.setProfile(prof);
		  options.addArguments("--ignore-certificate-errors");
		  options.addArguments("--disable-blink-features=AutomationControlled");
		  options.setCapability("se:recordVideo", true);
		  options.setCapability("se:name","testcase" );
          driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), options);
```

### Relevant log output

```shell
only video.mp4 file generated in assets folder of session folder
```

### Operating System

Linux

### Docker Selenium version (tag)

4.5.3-20221024

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#mounting-volumes-to-retrieve-downloaded-files

**Comment by ATTO-RATHORE** [comment]
I m not getting from above link can you please tell me the step to generate json file in assets folder or it's not possible on linux

**Comment by ATTO-RATHORE** [comment]
after given 777 permission to assets folder able to  see thanks
