### ISSUE TITLE
How to change LiveView (VNC) password in selenium grid

### ISSUE THREAD

**Issue by omdhimar28** [SeleniumHQ/docker-selenium#1753]
### What happened?

I have deployed selenium hub and selenium chrome node using the docker/selenium-hub image and docker/selenium-chrome-node image in my kubernetes cluster. Currently I can watch live sessions using password "secret", how can I change this password?
![image](https://user-images.githubusercontent.com/71244798/208644997-1e824759-ab03-4bda-9563-686278f4aa62.png)

### Command used to start Selenium Grid with Docker

```shell
selenium hub deployment.yaml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: stage
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:4.6.0
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"

selenium node chrome deployment.yaml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: stage
  labels:
    app: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome:106.0-chromedriver-107.0
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_NODE_MAX_SESSIONS
            value: "15000"
          - name: SE_NODE_OVERRIDE_MAX_SESSIONS
            value: "true"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
```

### Relevant log output

```shell
What changes should I do in my yaml files or image so that I can be able to change the password from "secret" to something else.
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

I am using chrome node version 106 and Hub version 4.6

**Comment by omdhimar28** [comment]
Please check on this (Help needed)

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#using-a-vnc-client

In short:
- Build a new image with the password. 
- Or send a PR to change it via an env var.

**Comment by omdhimar28** [comment]
Thanks for the help!! @diemol

**Comment by hager-yousri** [comment]
@omdhimar28 @diemol 
if you are able to change the password could you please provide detailed steps for this either 
1- how to Build a new image with the password.
Or 
2- how to send a PR to change it via an env var.

**Comment by omdhimar28** [comment]
Hello @hager-yousri ,
@diemol has already provided the link above. Let me share it with you again.
https://github.com/SeleniumHQ/docker-selenium#using-a-vnc-client

create a Dockerfile and add the content from the above link. Then after build the image using that Dockerfile and you will have your VNC password changed.

Thanks
