### ISSUE TITLE
How to make my Selenium-Hub URL password protected?

### ISSUE THREAD

**Issue by omdhimar28** [SeleniumHQ/docker-selenium#1754]
### What happened?

I have deployed my selenium grid architecture using docker images in my kubernetes cluster. Also I have made my selenium hub service publicly accessible via ingress. I want to make my publicy accessible URL password protected by some basic level authentication. For example, by changing config file for selenium hub or grid.

![image](https://user-images.githubusercontent.com/71244798/209128756-2f264494-af48-4241-be71-8dc1477d829f.png)

### Command used to start Selenium Grid with Docker

```shell
Selenium-hub deployment.yaml :

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:latest
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
```

### Relevant log output

```shell
How to make my Selenium URL password protected?

Reference URL:
https://www.selenium.dev/documentation/grid/configuration/toml_options/#basic-auth-enabled
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

Hub version 4.6

Please help!!!
@diemol

**Comment by omdhimar28** [comment]
Is there anyway that I can do some changes in the configuration file as shown in this link "https://www.selenium.dev/documentation/grid/configuration/toml_options/#basic-auth-enabled" and How can I do that using Dockerfile as I need to do change the configuration in docker image!!!

Please Help! @diemol

**Comment by ghost** [comment]
@omdhimar28 I added the ability to use `config.toml` files on the hub.

You can check out this compose file if you are interested on how to add basicauth:

https://github.com/SeleniumHQ/docker-selenium/pull/1757/files#diff-a627c055a568a3c52aef1a4363aefcc87d8f5b0595ad5d1714693d902bc23142

Obviously, the PR needs to be approved and merged first before it is available to everyone.

**Comment by omdhimar28** [comment]
Thanks @Xcalizorz , this will for sure help a lot of users.
Do you have any idea about how can I edit the config.toml file before running my docker image in a container.
Like if I can just do some kind of changes in my Dockerfile.

For example: [Dockerfile]

FROM selenium/hub:4.7.2-20221219
RUN (some changes by which I can edit the configuration file)

**Comment by jamesmortensen** [comment]
@omdhimar28 in the docker-compose.yml, he's mapped the example-config.toml on the host with the config.toml file in the container.  I believe you can edit the example-config.toml on the host with the values you need for username and password and then start the grid via docker-compose.  There are default values supplied, and you can change them to whatever you want.

You can see this in the pull request here:
https://github.com/SeleniumHQ/docker-selenium/pull/1757/files#diff-a627c055a568a3c52aef1a4363aefcc87d8f5b0595ad5d1714693d902bc23142R44

Note that this isn't merged yet, so you'd have to clone https://github.com/Xcalizorz/docker-selenium.git and build the Base, NodeBase, Hub, and any browser Nodes yourself.  You can do this with `make build`

**Comment by dipakparmar13** [comment]
Do you have any idea about how can I edit the config.toml file before running my docker image in a container, secure selenium hub url password protected in kubernetes.

**Comment by dipakparmar13** [comment]
Do you have any idea  I have run a docker image of selenium hub and deployed in kubernetes but the url is not password protected ?

Please help!!!

**Comment by jamesmortensen** [comment]
@dipakparmar13 I'm not sure about exact details in Kubernetes.  Are you using the modified docker-compose from here:  https://github.com/SeleniumHQ/docker-selenium/pull/1757/files#diff-a627c055a568a3c52aef1a4363aefcc87d8f5b0595ad5d1714693d902bc23142.  This includes a config.toml that you can modify in order to set your own username and password.

If you still have more questions, I suggest visiting one of the [support channels](https://www.selenium.dev/support/) or opening a new issue in this repository so you can share in greater detail what you've tried and what output you're getting.
