### ISSUE TITLE
Session Cleanup not working

### ISSUE THREAD

**Issue by caioquirino** [SeleniumHQ/docker-selenium#176]
Hi,

I am using Selenium Hub + Chrome Node Dev both with version 2.52 and the Session Cleanup job are not working. The log does not print anything about the Session Cleanup. I have checked both in hub and the node.

After the execution of some tests using Jenkins + Surefire, the node have 100+ opened chrome windows and the machine was too slow.

Node Chrome Dev config.json:
`{
  "capabilities": [
    {
      "browserName": "chrome",
      "seleniumProtocol": "WebDriver",
      "maxInstances": 10
    }
  ],
  "configuration": {
    "maxSession": 10,
    "port": 5555,
    "register": true,
    "registerCycle": 5000,
    "nodePolling": 15000,
    "browserTimeout": 300,
    "timeout": 300,
    "nodeStatusCheckTimeout": 5000,
    "cleanupCycle": 10000
  }
}`

HUB configuration:
`image: selenium/hub:2.52.0
environment:
- GRID_BROWSER_TIMEOUT=300
- GRID_TIMEOUT=300
- GRID_NODE_POLLING=10000
- GRID_CLEAN_UP_CYCLE=10000
- GRID_NEW_SESSION_WAIT_TIMEOUT=10000
- GRID_UNREGISTER_IF_STILL_DOWN_AFTER=60000`

**Comment by diemol** [comment]
Hi @caioquirino,

When the test completes, do you use `driver.quit()`?
Otherwise the browser will not close.

**Comment by ddavison** [comment]
closing as this is assumed no longer an issue.  if it is we can reopen.
