### ISSUE TITLE
XDAMAGE is not working well... misses: 203/203

### ISSUE THREAD

**Issue by caioquirino** [SeleniumHQ/docker-selenium#178]
I'm using selenium-chrome-debug version 2.52 and getting this message.
Should we disable XDAMAGE for the debug images?

selenium-chrome   | 15/03/2016 07:31:41 XDAMAGE is not working well... misses: 203/203
selenium-chrome   | 15/03/2016 07:31:41 Maybe an OpenGL app like Beryl or Compiz is the problem?
selenium-chrome   | 15/03/2016 07:31:41 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
selenium-chrome   | 15/03/2016 07:31:41 To disable this check and warning specify -xdamage twice.

**Comment by diemol** [comment]
@caioquirino, I am not seeing this message in the latest debug images, could you please check again?

**Comment by pwaller** [comment]
I have just hit this. A firefox tab crashes, then this appears on the console. The crash is 100% reproducible on my side, but unfortunately I can't easily provide a minimal reproducer.

I'm using the `selenium/node-firefox-debug:3.4.0` image.

```
firefox_1    | [Parent 2149] WARNING: pipe error (52): Connection reset by peer: file /home/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
firefox_1    | [Parent 2149] WARNING: pipe error (45): Connection reset by peer: file /home/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
firefox_1    | 
firefox_1    | ###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
firefox_1    | 
firefox_1    | 22/06/2017 14:32:13 cursor_noshape_updates_clients: 0
firefox_1    | 22/06/2017 14:32:19 XDAMAGE is not working well... misses: 220/227
firefox_1    | 22/06/2017 14:32:19 Maybe an OpenGL app like Beryl or Compiz is the problem?
firefox_1    | 22/06/2017 14:32:19 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
firefox_1    | 22/06/2017 14:32:19 To disable this check and warning specify -xdamage twice.
firefox_1    | 22/06/2017 14:32:31 cursor_noshape_updates_clients: 0
firefox_1    | 22/06/2017 14:32:31 cursor_noshape_updates_clients: 0
firefox_1    | 22/06/2017 14:32:40 XDAMAGE is not working well... misses: 213/217
firefox_1    | 22/06/2017 14:32:40 Maybe an OpenGL app like Beryl or Compiz is the problem?
```

**Comment by peterstory** [comment]
Does loading this URL trigger the issue for you?
http://www.firsttouchgames.com/w/?page_id=1427

**Comment by pwaller** [comment]
I have resolved the issue, it turned out to be an issue of shm-size, see https://github.com/SeleniumHQ/docker-selenium/pull/485 and related issues. Increasing it to 1G and haven't encountered the crash since.

**Comment by peterstory** [comment]
Cool, hopefully that will fix the issue for me as well! Still waiting on the FF v54 image to be released (currently using a custom image with a beta), but then I'll give it a shot.
