### ISSUE TITLE
[🚀 Feature]: There is currently no direct option to disable VNC in selenium

### ISSUE THREAD

**Issue by Nagam-Naidu** [SeleniumHQ/docker-selenium#1781]
### Feature and motivation

There is currently no direct option to disable VNC in selenium

### Usage example

There is currently no direct option to disable VNC in selenium

**Comment by diemol** [comment]
What use case do you have?

**Comment by esaari** [comment]
I can think of a couple - 

1. We never use it. I'd prefer to not have any unnecessary processes running, especially when CPU capacity is already pretty tight on a remote. build server. 

2. On some k8 setups, you can be charged for every little CPU cycle. If you're looking to cut costs, even a small amount of extra CPU across many nodes with high uptime, that $ can add up.

**Comment by Nagam-Naidu** [comment]
VNC is utilizing higher cpu if we are increasing the number of parallel threads. It will be better if we have an option to make vnc optional in selenium grid.

**Comment by ccsuperstar** [comment]
I'm also interested in adding this option, since version 4.7, I experience CPU load peaks that cause parallel tests to freeze and never finish

**Comment by diemol** [comment]
Sure. 
The idea would be to add a variable that works in the same way as https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L169

**Comment by jamesmortensen** [comment]
Just to clarify on this issue, we want xvfb to still be running, but for VNC to be disabled? I assume this is so tests can still be run headfully (not headless)?

**Comment by sachin6757** [comment]
Thanks @diemol

**Comment by ccsuperstar** [comment]
Thanks @diemol ^^
