### ISSUE TITLE
[🚀 Feature]: Configurable serviceAccount.name

### ISSUE THREAD

**Issue by gianluca-soffredini** [SeleniumHQ/docker-selenium#1783]
### Feature and motivation

Essentially, for security reasons, it could be helpful to be able to specify the serviceAccount.name in the template.spec section of the yaml files which have Deployment as kind, and make it configurable through the values.yaml file.
It will provide the opportunity to avoid using the default service account.

### Usage example

In the installation or upgrade phase of the chart it could be possible to use the helm syntax as follow:

helm install selenium-grid docker-selenium/selenium-grid --set serviceAccount.name=<your-service-account-name>.

I think it could be specified in the values.yaml, in the same way the isolateComponents property is used, if you do not want to implement the feature for each Deployment "object".

**Comment by diemol** [comment]
Feel free to send us a PR.

**Comment by VietND96** [comment]
Fixed by #1919
