### ISSUE TITLE
[🐛 Bug]: Cannot download file

### ISSUE THREAD

**Issue by GaleSS** [SeleniumHQ/docker-selenium#1790]
### What happened?

I'm using selenium/standalone-chrome to run java selenium tests. Some of the tests download files, no settings have been changed for this part, but after last update file download stops to work (the folder **/home/seluser/Downloads**, which were set using preference "download.default_directory" is empty in container file system). On image version selenium/standalone-chrome:109.0-chromedriver-109.0 everything still works perfectly fine.

Just in case, java code used for setting up the folder:
```
ChromeOptions options = new ChromeOptions();
String[] chromeOptions = properties.getProperty("chrome.options", "--?").split(",");'
options.addArguments(chromeOptions);
HashMap<String, Object> chromePrefs = new HashMap<>();
chromePrefs.put("profile.default_content_settings.popups", 0);
chromePrefs.put("download.directory_upgrade", true);
chromePrefs.put("download.default_directory", properties.getProperty("chrome.downloads.path"));
options.setExperimentalOption("prefs", chromePrefs);
```

### Command used to start Selenium Grid with Docker

```shell
docker run -d --name chrome -p 4444:4444 -v D:\downloads:/home/seluser/Downloads selenium/standalone-chrome:latest
docker exec -i chrome  bash < "sudo chmod -R 777 /home/seluser/Downloads"
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.8.0-20230210

**Comment by diemol** [comment]
Seems Chrome 109 and 110 have issues around this. I recommend following these issues and wait for a resolution.
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=4322
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=4258
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=4143
- https://bugs.chromium.org/p/chromedriver/issues/detail?id=4356
