### ISSUE TITLE
[🚀 Feature]: default hub parameters

### ISSUE THREAD

**Issue by Hugues862** [SeleniumHQ/docker-selenium#1791]
### Feature and motivation

I'd like to be able to modify selenium hub default values, for example default rows per page on the hub, default sorting, etc...

### Usage example

In docker, you would be able to pass this through env variables or a param.

**Comment by diemol** [comment]
What is the use case? 
I am not sure how feasible that is because those options get decided when the front end is packed into the Selenium jar.

**Comment by diemol** [comment]
Closing as no more feedback was provided.
