### ISSUE TITLE
[🐛 Bug]: trying to run edge in IE mode hangs in the queue indefinetely 

### ISSUE THREAD

**Issue by cuipengfei** [SeleniumHQ/docker-selenium#1792]
### What happened?

started a container like this, running edge in it:
```shell
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-edge:4.8.0
```

try to connect to it with IE Options:
```java
        InternetExplorerOptions options = new InternetExplorerOptions();//if using edge options here, then it is ok
        options.ignoreZoomSettings();
        options.attachToEdgeChrome();

        RemoteWebDriver remoteWebDriver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"), options);

        try {
            remoteWebDriver.get("http://home.global.hsbc/");
        } finally {
            remoteWebDriver.quit();
        }
```

then it just hangs in the queue without running:
![image](https://user-images.githubusercontent.com/1311541/219549370-0874c33b-5291-48e7-8b8f-37ef6e5532a5.png)

is edge's ie compatible mode supported by this image **_selenium/standalone-edge_**? 

I have tried using edge options, that works ok. 
But we are trying to test an old legacy system that nedds ie to run.

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-edge:4.8.0


not a grid, just a standalone edge
```

### Relevant log output

```shell
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:4444 after 180000 ms
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)


timeout waiting
```

### Operating System

win 10

### Docker Selenium version (tag)

selenium/standalone-edge:4.8.0

**Comment by diemol** [comment]
That only works on Windows, these images are based on Ubuntu.

**Comment by cuipengfei** [comment]
> That only works on Windows, these images are based on Ubuntu.

thanks for the reply.

Suggest to make that point more visible in the readme.

**Comment by diemol** [comment]
You still need the IEDriver to make IE on Edge work, and that has been always Windows.
