### ISSUE TITLE
[🐛 Bug]: SE_SESSION_RETRY_INTERVAL and SE_SESSION_REQUEST_TIMEOUT are not working as expected

### ISSUE THREAD

**Issue by zetendra** [SeleniumHQ/docker-selenium#1794]
### What happened?

Here is the my scenario. I have a Grid setup with 2 nodes initially (Will scale later when CPU utilisation is more than 30%). There are 60 test cases in my suite, out of which when 2 tests gets executed 58 will be in Queue and at later after few seconds, the queue becomes 100 and later it also becomes 150.

So overcome this, i have added SE_SESSION_REQUEST_TIMEOUT as 300 seconds and SE_SESSION_RETRY_INTERVAL as 300 seconds in Environment variables to make sure that retry doesn't happen at-least for 5 minutes. Still it was not working. Is any one facing similar issue ?

Reference i used [Link](https://www.selenium.dev/documentation/grid/configuration/cli_options/#sessionqueue)

### Command used to start Selenium Grid with Docker

```shell
resource "aws_ecs_task_definition" "session_queue_task_definition" {
  family                   = "selenium-session-queue"
  ....
  container_definitions = jsonencode([
    {
      name      = "selenium-session-queue-task"
      image     = "selenium/session-queue:4.8.0-20230210"
      essential = true
      "environment": [
      {
          "name" : "SE_SESSION_RETRY_INTERVAL",
          "value" : "300"
        },
        {
          "name" : "SE_SESSION_REQUEST_TIMEOUT",
          "value" : "300"
        }
      ]
      ...
      portMappings = [
        {
          containerPort = 5559
          hostPort      = 5559
          protocol      = "tcp"
        }
      ]
  }])
}
```

### Relevant log output

```shell
NA
```

### Operating System

Linux

### Docker Selenium version (tag)

4.8.0-20230210

**Comment by diemol** [comment]
You either need to increase the size of your Grid to process more sessions concurrently or reduce the number of session requests that can be sent to the Grid. By default each Node in Docker supports only one session.

https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container
https://www.selenium.dev/documentation/grid/getting_started/#grid-sizes

If you have more questions, feel free to reach out to https://www.selenium.dev/support/

**Comment by zetendra** [comment]
@diemol Thank you for replying to this :) , I know i can increase the sessions. Nodes gets increased automatically after CPU utilisation goes beyond the Threshold value. But for that to happen it would take a minute or two, until that to happen i need to make sure tests wait in the queue with out timeout

**Comment by zetendra** [comment]
@diemol Not sure, if SE_SESSION_RETRY_INTERVAL and SE_SESSION_REQUEST_TIMEOUT are working as expected

**Comment by diemol** [comment]
You also need to increase the timeout on the client side.
