### ISSUE TITLE
[🚀 Feature]: Standby Grid with automated container creation/deletion and API Authentification: 

### ISSUE THREAD

**Issue by prononext** [SeleniumHQ/docker-selenium#1797]
### Feature and motivation

A production-ready on-demand Grid Deployment for Selenium with following features:

**Selenium Hub:** 
 - [ ]  API Access for (test start, log request, screenshot requests, session video requests)
 - [ ] API Authentification
 - [ ] Browser UI Authentification

The Hub should be the basic entrypoint for the Webdriver API which:
-  [ ] Starts test via API without any local test files on the docker stack
-  [ ] Creates the required docker containers for every test with the version specified in the API Call to the hub
-  [ ] Deletes the docker containers which have finished a test

### Usage example

Controlling Selenium via a central API endpoint on the hub, fully secure and authenticated and without having test node containers running 24/7 without using them. Also the Web UI doesnt seem to have any Authentification possibility for checking in while testing. 

I am quite new to Selenium and was trying around with the Docker Compose v3 full grid swarm and also others.
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-full-grid-swarm.yml

I could not find a complete API with the functionality to make calls to a single endpoint to
- Create Tests on different Browsers
- Get Test Info like Progress and Logs
- Get Test Screenshots
- Get Test Video Recordings

It seems to be quite a hassle getting it running on docker and changing your setup every time a new test is created. 

The goal is to integrate different testings in a workflow management system which is running inside projects management, uptime monitoring and performance testing while calling a central Selenium Endpoint to make that testing with the desired configuration. 

Let me know what you guys think?

**Comment by diemol** [comment]
Most of those things are already provided through a combination of Selenium 4 bindings, and the docker-selenium project. I recommend you get an intro by checking these docs https://www.selenium.dev/documentation/overview/ and these https://github.com/SeleniumHQ/docker-selenium.

If you have more questions, I will leave some links below that you can use.
