### ISSUE TITLE
[🚀 Feature]: helm chart VolumeMounts for hub deployment

### ISSUE THREAD

**Issue by menvol3** [SeleniumHQ/docker-selenium#1801]
### Feature and motivation

Hi
To be able to use basic auth for the Selenium UI there is an option to add login and pass to the `config.toml` which can be converted to the config map.
But to be able to use that config map as a local file Kubernetes volume and volume mount should be used. 
At this moment volume and volume mount are available only for browser nodes. 
Please add the same part of the code to the hub deployment template file.

### Usage example

https://github.com/SeleniumHQ/docker-selenium/blob/595a98332b7092e331ac2d47d177ddeacbc50377/charts/selenium-grid/templates/edge-node-deployment.yaml#L56
https://github.com/SeleniumHQ/docker-selenium/blob/595a98332b7092e331ac2d47d177ddeacbc50377/charts/selenium-grid/templates/edge-node-deployment.yaml#L86

**Comment by tkrisztian95** [comment]
Hello, i stumbled upon the same issue and i would be interested.
