### ISSUE TITLE
[🚀 Feature]: Java  latest version 11.0.18

### ISSUE THREAD

**Issue by PrinceKq55iw** [SeleniumHQ/docker-selenium#1802]
### Feature and motivation

We are facing security issue due to old JAVA version '11.0.17', can you please publish new image with latest JAVA version '11.0.18'

### Usage example

We are facing security issue due to old JAVA version '11.0.17', can you please publish new image with latest JAVA version '11.0.18'

**Comment by diemol** [comment]
Bumped the base image and seems it helps

https://github.com/SeleniumHQ/docker-selenium/actions/runs/4322557562/jobs/7545114743#step:9:481

Will be part of the next release, which will happen next week
