### ISSUE TITLE
[🐛 Bug]: VNC viewer cannot display Chinese title

### ISSUE THREAD

**Issue by liuruibin** [SeleniumHQ/docker-selenium#1806]
### What happened?

VNC viewer cannot display Chinese title, but chrome is ok

### Command used to start Selenium Grid with Docker

```shell
version: "3"
services:
  chrome:
    image: seleniarm/node-chromium:4.8.0
    shm_size: 2gb
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - TZ=Asia/Shanghai
      - SE_NODE_MAX_SESSIONS=12
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - JAVA_OPTS=-Xmx400m
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - LANGUAGE=zh_CN
      - LANG=zh_CN

  firefox:
    image: seleniarm/node-firefox:4.8.0
    shm_size: 2gb
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - TZ=Asia/Shanghai
      - SE_NODE_MAX_SESSIONS=12
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - JAVA_OPTS=-Xmx400m
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - LANGUAGE=zh_CN
      - LANG=zh_CN

  selenium-hub:
    image: seleniarm/hub:4.8.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - LANGUAGE=zh_CN
      - LANG=zh_CN
```

### Relevant log output

<img width="1826" alt="image" src="https://user-images.githubusercontent.com/23045261/224006381-333e67e6-c483-4ca6-bd47-627cea65d2f9.png">

### Operating System

linux

### Docker Selenium version (tag)

4.8.0

**Comment by diemol** [comment]
That comes from Fluxbox, which is the window manager we use for these containers. That does not affect how the browser is rendered at all, which is what actually matters.

**Comment by liuruibin** [comment]
When I upload a file with a Chinese name, it will not be displayed

<img width="588" alt="image" src="https://user-images.githubusercontent.com/23045261/224204796-c055bf9a-bdc9-49da-a7b9-04099c8e1ba5.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/23045261/224204893-89fcc776-a625-4353-984a-c79f9abd0bf9.png">

**Comment by diemol** [comment]
Where is that, can you please add more details or post the whole screenshot and not just a small part of it?
