### ISSUE TITLE
[🐛 Bug]: Docker is sunsetting Free Teams

### ISSUE THREAD

**Issue by madflow** [SeleniumHQ/docker-selenium#1809]
### What happened?

Hi there,

Docker is sunsetting Free Team Organizations on April 14th.

Are the images  published in such a "Free Team Organisation" ?

From the looks of it, it is: https://hub.docker.com/u/selenium - but maybe SeleniumHQ is is in the sponsored program?

Can anyone confirm that we can happily pull after the deadline?

I am sorry for the noise... I do not want to spread the FUD, but still...

https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

### Command used to start Selenium Grid with Docker

```shell
n.a
```

### Relevant log output

```shell
n.a
```

### Operating System

n.a

### Docker Selenium version (tag)

n.a

**Comment by diemol** [comment]
We are in the process of getting an Open Source license, thanks for raising the concern!
