### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedError: Could not start a new session. Error while creating session with the driver service.

### ISSUE THREAD

**Issue by nwtgck** [SeleniumHQ/docker-selenium#1811]
Thank you so much for providing Docker images. They help a lot for developing E2E testing.

### What happened?

I had the following error after updating Docker images.

```
SessionNotCreatedError: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 
Host info: host: '16af38dc41b8', ip: '172.17.0.2'
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown
```

The following images work fine.
* selenium/standalone-firefox:108.0
* selenium/standalone-firefox:78.0
* selenium/standalone-chrome:109.0
* selenium/standalone-chrome:108.0
* selenium/standalone-chrome:84.0

However, I had the error when recently updated the images as follows.
* selenium/standalone-firefox:110.0
* selenium/standalone-firefox:109.0
* selenium/standalone-chrome:110.0

Techinically, chrome:110.0 and firefox:110.0 work fine 2 weeks ago:
* https://github.com/nwtgck/piping-ui-web/pull/1468
* CI: https://github.com/nwtgck/piping-ui-web/actions/runs/4330444953/jobs/7561671111

But at some point, I have the session errors.

### Command used to start Selenium Grid with Docker

I'd like to create a minimal case. Until then, I can show a directory using Selenium in Docker.

full directory: https://github.com/nwtgck/piping-ui-web/tree/04304eab580eae1a334b4aa9b7f11523de3de225/e2e-test

docker run: https://github.com/nwtgck/piping-ui-web/blob/04304eab580eae1a334b4aa9b7f11523de3de225/e2e-test/src/docker-selenium-standalone.ts#L28-L34

GitHub Actions error log:

https://github.com/nwtgck/piping-ui-web/actions/runs/4444438653/jobs/7802644433

### Relevant log output

```shell
I already provided logs.
```

### Operating System

Linux, Mac

### Docker Selenium version (tag)

I already provided versions

**Comment by nwtgck** [comment]
I tried to rerun a CI because [new version released](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.8.2-20230325) but I still have the problem.

```
 SessionNotCreatedError: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'e0f722b61e58', ip: '172.17.0.2'
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1034-azure', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1034-azure', java.version: '11.0.18'
Driver info: driver.version: unknown
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:587:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:515:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by nwtgck** [comment]
@PgDavitec Thank you for your reactions. Do you have the same issue too?

**Comment by PgDavitec** [comment]
Yes, got the same error, but next to selenium/standalone-chrome:110.0 also in Versions selenium/standalone-chrome:109.0 and selenium/standalone-chrome:108.0.

I tried also the newest firefox-images. Found no image to work with and never had a running system, because i run into this issues during my first steps.



```
[Facebook\WebDriver\Exception\SessionNotCreatedException] Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'XXX', ip: 'XXX.XXX.XX.XX'
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.18'
Driver info: driver.version: unknown 
```

```#1  /var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:130
#2  /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:359
#3  /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
#4  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:230
#5  /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:59
#6  /var/www/html/vendor/bin/codecept:120```

**Comment by jamesmortensen** [comment]
Hi.  Thank you for reporting the issues you're facing.  Would anyone be able to supply a minimal test case example we can run to help us replicate the issue you're facing?  This would help us further troubleshoot the issue.  It looks like one person is using the JS Selenium Webdriver bindings and the other is using PHP Webdriver.

Having a quick sample to replicate would really help us troubleshoot.

**Comment by nwtgck** [comment]
@jamesmortensen Thank you so much for your response.

I created a minimal test case.

Run the following code after docker-run.
```bash
node index.js
```

```js
// index.js

const webdriver = require("selenium-webdriver");

(async () => {
  const driver = new webdriver.Builder()
    .forBrowser(webdriver.Browser.FIREFOX)
    .usingServer("http://localhost:4444/wd/hub").build();
  console.log("driver created");

  console.log("Getting...");
  await driver.get("https://example.com");
  const title = await driver.getTitle();
  console.log(`title=${title}`);
  // expected => title=Example Domain
})();
```

complete npm project: https://github.com/nwtgck/public-code/tree/4a4e1086e6c10937da7605a838f29033b6469764/docker-selenium-session-not-created-error

## Not work
The error occurred when we use `-e SE_START_XVFB=false`.
```bash
docker run --rm -p 4444:4444 -e SE_START_XVFB=false selenium/standalone-firefox:110.0
```

## Work
But, no error occurred when we do not use `-e SE_START_XVFB=false`.
```bash
docker run --rm -p 4444:4444 selenium/standalone-firefox:110.0 # no SE_START_XVFB=false
```

OR

```bash
docker run --rm -p 4444:4444 -e SE_START_XVFB=false selenium/standalone-firefox:108.0 # lower version
```

**Comment by jamesmortensen** [comment]
@nwtgck The sample you sent helps identify the possible problem. Thank you.  

If you disable XVFB then there is no user interface to support the browser running headfully (with the UI support, like how we use a browser day to day as users).  

You'll need to run the browser headlessly if disabling XVFB.  You can set this using the `firefox.Options()` object via the `addArguments` method.  Can you try the sample below where I've added this in:

```
// index.js

const webdriver = require("selenium-webdriver");
const { Builder, Capabilities } = require("selenium-webdriver");
const firefox = require('selenium-webdriver/firefox');

(async () => {
  var capabilities = Capabilities.firefox();

  var options = new firefox.Options();
  options.addArguments('--headless');

  const driver = new webdriver.Builder()
    .forBrowser(webdriver.Browser.FIREFOX)
    .setFirefoxOptions(options)
    .usingServer("http://localhost:4444/wd/hub")
.build();
  console.log("driver created");

  console.log("Getting...");
  await driver.get("https://example.com");
  const title = await driver.getTitle();
  console.log(`title=${title}`);
  // expected => title=Example Domain
})();
```

**Comment by nwtgck** [comment]
Thank you so much for your the fixed code! It works in my environment too.

**Comment by jamesmortensen** [comment]
Glad this helped.  @nwtgck

**Comment by diemol** [comment]
Thank you for troubleshooting, @jamesmortensen!
