### ISSUE TITLE
[🚀 Feature]: Ability to update hosts file on browser nodes in dynamic selenium grid

### ISSUE THREAD

**Issue by ravinice** [SeleniumHQ/docker-selenium#1812]
### Feature and motivation

I would like the ability to add hosts file entry to the browser nodes that get launched in the dynamic grid.

It would be good if below config is supported on the docker-compose for node-docker section and the same can be used to launch new browser nodes.

extra_hosts:
  - "cust.examplecompany.com:10.8.23.76"

### Usage example

We use selenium grid to test an internally hosted application which can be accessed using a custom dns entry in the hosts file where the browser is getting launched.

However, with dynamic selenium grid - I don't see an option to add this host file entry to the browser node.

**Comment by deepakguna** [comment]
I am in need of this for the grid running in kubernetes cluster , deployed with HELM chart .This would be a nice addition . 

Is the host aliases meant for it ? 

hostAliases:
    # - ip: "198.51.100.0"
    #   hostnames:
    #     - "example.com"
    #     - "example.net"
    # - ip: "203.0.113.0"
    #   hostnames:
    #     - "example.org"

**Comment by diemol** [comment]
Dynamic Grid does not work in Kubernetes. Can you clarify the use case and environment?
