### ISSUE TITLE
[🐛 Bug]: Release 4.8.3-20230328 points to another version

### ISSUE THREAD

**Issue by d4vke** [SeleniumHQ/docker-selenium#1819]
### What happened?

When doing a helm repo update to get the chart for release 4.8.3-20230328, it points to the 4.8.1 release as the latest (selenium-grid-0.15.4.tgz).
And when checking the charts in the source code for version 4.8.3-20230328, it points to version 4.8.2-20230325, however when you browse the charts in Github it points to the correct version.

### Command used to start Selenium Grid with Docker

```shell
Not applicable
```

### Relevant log output

```shell
Not applicable
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.8.3-20230328

**Comment by jamesmortensen** [comment]
It looks like the selenium-grid helm release hasn't yet been published for the 4.8.3 version.  Most of the Selenium committers and leadership were at the conference.  I think once they are back we can see about publishing an update.  

It also makes me think it would be cool to include the details of which selenium-grid-0.x.tgz version is associated with which grid.

**Comment by diemol** [comment]
Just fixed that. Unfortunately that release is still manual.
