### ISSUE TITLE
[🚀 Feature]: Direct link to access specific Session VNC

### ISSUE THREAD

**Issue by marcelo-cintra** [SeleniumHQ/docker-selenium#1820]
### Feature and motivation

The commom use:
On Selenium Grid UI, navigate to menu Sessions and then search for id, then click on camera link, type password and finally watch our session on VNC.

Proposal:
Has a link to go direct to VNC like: https://localhost:4444/ui#/sessions/<session_id>/vnc?password=<secret>

### Usage example

I have 30 sessions running same time.
When I start a session, I save the ID on my database and have a page showing every session running and what each one is doing.

My proposal would make easier for the users to access the session, just by clicking in one link, instead of doing 4 or 5 steps they do now.

**Comment by jamesmortensen** [comment]
The Zalenium project had a modified Selenium Grid UI that not only had a link to the various VNC sessions but also had embedded previews in the Selenium Grid UI.  You can find that project here:  https://github.com/zalando/zalenium/#additional-features and see some screenshots of what that looked like.

I think the code for the Grid UI is in the https://github.com/SeleniumHQ/selenium repository though, not here in the docker-selenium project.  It also sounds like it might be a big job to make it handle various use cases.  Here are some scenarios that come to mind to make sure various Selenium users have a good experience:

- If Grid is not running with Docker, there are no VNC sessions and no previews to show.
- If the Grid is running in Docker, but port 7900 is not open and/or noVNC is not running, then there's no previews to show. 
- If some nodes expose a noVNC port but others don't, what would that look like in the Grid UI?
- Would some users who rely on the existing Grid UI want to disable the previews but still have noVNC running and port 7900 open?
- How would we test for these things so it's maintainable?

Another idea would be to provide an alternative UI for managing and viewing the noVNC sessions.

We could gather more details here, but I think @diemol would also be able to provide more guidance regarding this topic and what would be involved in making a successful pull request.

**Comment by jamesmortensen** [comment]
@marcelo-cintra When you describe your "usage example", is this something you're able to do today, to keep track of sessions and easily view them in separate VNC windows?

**Comment by marcelo-cintra** [comment]
@jamesmortensen yes, today I have by myself a control of all sessions running, so I can give names for them identifying each one. But this is controlled by my own app. 

I wish I could make it easier for me to open the VNC window, cause now I go to selenium grid ui > sessions > search for session ID > vnc > password.

My proposal is to have a link or a route for me to go direct to VNC video using session ID.

**Comment by jamesmortensen** [comment]
Is the app that manages the VNC sessions something that you've open sourced, @marcelo-cintra ?  It sounds like it is something a lot of people would find useful.

**Comment by diemol** [comment]
This is a deeplink that needs to be implemented in the Grid UI. https://github.com/SeleniumHQ/selenium/tree/trunk/javascript/grid-ui

I guess it should be a route that grabs the parameters and loads the component that shows the VNC session.

**Comment by diemol** [comment]
Moving the conversation to the upstream repo https://github.com/SeleniumHQ/selenium/issues/12075
