### ISSUE TITLE
[🐛 Bug]: Custom CA Certificate installation incorrectly/poorly documented and difficult

### ISSUE THREAD

**Issue by andrewnicols** [SeleniumHQ/docker-selenium#1835]
### What happened?

The [instructions on install custom certs for Chrome](https://github.com/SeleniumHQ/docker-selenium#install-certificates-for-chromium-based-browsers) are poor and confusing.

They:
- are missing the full instructions to run `apt-get update && apt-get install -qyy libnss3-tools` as _root_
- have missing steps to create the directory with the relevant permissions

i'd really suggest that libnss3-tools should be installed as standard for Chromium images.

There are also no notes for other browsers so it's unclear if any steps need to be taken.

### Command used to start Selenium Grid with Docker

```shell
docker run selenium/standalone-chrome:latest
```

### Relevant log output

```shell
N/A
```

### Operating System

MacOS

### Docker Selenium version (tag)

4.17.0 (99724)

**Comment by diemol** [comment]
They have been added as contributions because some users want to know how to install certificates. Could you please help us to improve them?

**Comment by diemol** [comment]
@andrewnicols do you have time to help us?

**Comment by roderickgreen** [comment]
it would also be helpful to me if libnss3-tools was included in chromium images by default. our use case is probably the same. we have an enterprise ca, but are a relatively small org so it's somewhat of a burden to maintain our own images just to add a root cert. with certutil baked in we can script at startup the addition of the required cert. i'd be happy to send up a patch to the dockerfiles if you are open to it.

**Comment by krishtoautomate** [comment]
**.sh**


echo "$USER running cert script"
certfile="/usr/local/share/ca-certificates/RootCA1.crt"
certname="RootCA1"
echo "running certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:$HOME/.pki/nssdb"
certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:$HOME/.pki/nssdb


**Dockerfile**
FROM selenium/node-chrome:120.0

COPY ./BellCerts/*.* /usr/local/share/ca-certificates/
RUN sudo chmod -R 577 /usr/local/share/ca-certificates/
RUN sudo apt update
RUN sudo update-ca-certificates
RUN sudo apt-get install libnss3-tools
COPY ./cert-script.sh /usr/local/share/cert-script.sh

RUN sudo -u seluser mkdir -p $HOME/.pki/nssdb && \
    sudo -u seluser sh /usr/local/share/cert-script.sh

**Comment by VietND96** [comment]
Thank you @krishtoautomate for your suggestion script. For now, by default, the based image is installed `libnss3-tools` and initializes `/home/seluser/.pki/nssdb`, so you can add your certs with rootless.
I added it to README in part of #2136 the script is locally testable.
