### ISSUE TITLE
[🐛 Bug]: 请给我一个解释，为什么会有挖矿病毒，内置到docker中的

### ISSUE THREAD

**Issue by TigerShuai** [SeleniumHQ/docker-selenium#1848]
### What happened?

![image](https://github.com/SeleniumHQ/docker-selenium/assets/35909241/cf36d787-6643-4140-b4b4-9d2b02a3766d)
![image](https://github.com/SeleniumHQ/docker-selenium/assets/35909241/c8d8bee1-d006-4d01-8c46-edfe223fc5cc)
![image](https://github.com/SeleniumHQ/docker-selenium/assets/35909241/eb563d80-7db8-45e6-8f98-b00806563a41)

### Command used to start Selenium Grid with Docker

```shell
同上
```

### Relevant log output

```shell
同上
```

### Operating System

linux centos7.5

### Docker Selenium version (tag)

Docker version 19.03.4, build 9013bf583a

**Comment by sam30606** [comment]
I had same issue, the mining process named "xm" and "wxm", it always start mining from "entry_point.sh" on 02:00 GMT+8.

selenium/node-chrome 3.141.59  
selenium/hub 3.141.59

![xm mining](https://github.com/SeleniumHQ/docker-selenium/assets/61706675/7ae547eb-cebb-4156-87c9-b34a0b019c5d)

**Comment by diemol** [comment]
Those images are not supported anymore, can you help us check if this is present in the latest ones?

**Comment by sam30606** [comment]
The latest version is functioning properly, but it's strange that the recent image has a mining virus."

**Comment by diemol** [comment]
> The latest version is functioning properly, but it's strange that the recent image has a mining virus."

Where, @sam30606?

**Comment by sam30606** [comment]
@diemol https://github.com/SeleniumHQ/docker-selenium/issues/1848#issuecomment-1573278028

**Comment by diemol** [comment]
But is it present in the latest image? How do you know it is a mining virus? Can you share a link showing that?

**Comment by TigerShuai** [comment]
> 但它出现在最新的图片中吗？你怎么知道这是挖矿病毒？你可以分享一个显示该内容的链接吗？

是不是也有中可能，默认密码没有修改，被扫描到了，黑客通过打开特定网页，下载到病毒脚本到docker-selenium的容器内，执行运行操作的？？？

**Comment by diemol** [comment]
![image](https://github.com/SeleniumHQ/docker-selenium/assets/5992658/c6b37717-7f7a-4d95-8270-e99ab8c71407)

**Comment by TigerShuai** [comment]
> ![图像](https://user-images.githubusercontent.com/5992658/279313295-c6b37717-7f7a-4d95-8270-e99ab8c71407.png)

y 😄，我的英语很烂

**Comment by sam30606** [comment]
> But is it present in the latest image? How do you know it is a mining virus? Can you share a link showing that?

It may only be present in selenium/node-chrome 3.141.59 or selenium/hub 3.141.59.

I noticed very high CPU usage and a file containing mining configuration.

What link you mean? The issue happened a long time ago, and I've almost forgotten the details.

**Comment by diemol** [comment]
> > But is it present in the latest image? How do you know it is a mining virus? Can you share a link showing that?
> 
> It may only be present in selenium/node-chrome 3.141.59 or selenium/hub 3.141.59.
> 
> I noticed very high CPU usage and a file containing mining configuration.
> 
> What link you mean?

Yeah, what evidence do you have it is a mining virus?

**Comment by TigerShuai** [comment]
> > 但它出现在最新的图像中吗？你怎么知道这是挖矿病毒？您能分享一个显示该内容的链接吗？
> 
> 它可能仅存在于 selenium/node-chrome 3.141.59 或 selenium/hub 3.141.59 中。
> 
> 我注意到 CPU 使用率非常高，并且有一个包含挖掘配置的文件。
> 
> 你指的是什么链接？这个问题已经发生很久了，细节我都快忘记了。

@sam30606 是不是当时密码使用的是默认密码？

@diemol 我中挖矿病毒时，当时有可能是默认密码没有修改，后续几台服务器上修改了默认密码，挖矿病毒这个问题没有在发生过。

**Comment by sam30606** [comment]
> > > But is it present in the latest image? How do you know it is a mining virus? Can you share a link showing that?
> > 
> > 
> > It may only be present in selenium/node-chrome 3.141.59 or selenium/hub 3.141.59.
> > I noticed very high CPU usage and a file containing mining configuration.
> > What link you mean?
> 
> Yeah, what evidence do you have it is a mining virus?

1. High CPU usage and mining configuration form those relative process
2. I can't remember anymore; it was a long time ago, and I didn't record them.

But when I update to latest image, it didn't happen again.

**Comment by sam30606** [comment]
> > > 但它出现在最新的图像中吗？你怎么知道这是挖矿病毒？您能分享一个显示该内容的链接吗？
> > 
> > 
> > 它可能仅存在于 selenium/node-chrome 3.141.59 或 selenium/hub 3.141.59 中。
> > 我注意到 CPU 使用率非常高，并且有一个包含挖掘配置的文件。
> > 你指的是什么链接？这个问题已经发生很久了，细节我都快忘记了。
> 
> @sam30606 是不是当时密码使用的是默认密码？
> 
> @diemol 我中挖矿病毒时，当时有可能是默认密码没有修改，后续几台服务器上修改了默认密码，挖矿病毒这个问题没有在发生过。

默認密碼是指系統的嗎？

**Comment by diemol** [comment]
You have not clarified if this is still happening with the most recent image.

**Comment by TigerShuai** [comment]
> > > > 但它出现在最新的图片中吗？你怎么知道这是挖矿病毒？你可以分享一个显示该内容的链接吗？
> > > 
> > > 
> > > 它可能只存在于 selenium/node-chrome 3.141.59 或 selenium/hub 3.141.59 中。
> > > 我注意到 CPU 使用率非常高，并且有一个包含挖掘配置的文件。
> > > 你指的链接是什么？这个问题已经很久以前了，细节我都快忘记了。
> > 
> > 
> > @sam30606是不是当时密码是使用默认密码？
> > @diemol我中挖矿病毒时，当时有可能是默认密码没有修改，后续几台服务器上修改了默认密码，挖矿病毒这个问题没有在发生过。
> 
> 默认密码是指系统的吗？

 你不清楚的话，大概率就是你没注意这个配置了，应该大概率确实使用的是默认密码，所以，确定测试环境很重要，这很有可能是被黑客扫描到你的服务器的docker-selenium端口，导致的黑客进入你的控制窗口，通过网页下载了挖矿病毒

**Comment by sam30606** [comment]
> > > > > 但它出现在最新的图片中吗？你怎么知道这是挖矿病毒？你可以分享一个显示该内容的链接吗？
> > > > 
> > > > 
> > > > 它可能只存在于 selenium/node-chrome 3.141.59 或 selenium/hub 3.141.59 中。
> > > > 我注意到 CPU 使用率非常高，并且有一个包含挖掘配置的文件。
> > > > 你指的链接是什么？这个问题已经很久以前了，细节我都快忘记了。
> > > 
> > > 
> > > @sam30606是不是当时密码是使用默认密码？
> > > @diemol我中挖矿病毒时，当时有可能是默认密码没有修改，后续几台服务器上修改了默认密码，挖矿病毒这个问题没有在发生过。
> > 
> > 
> > 默认密码是指系统的吗？
> 
> 你不清楚的话，大概率就是你没注意这个配置了，应该大概率确实使用的是默认密码，所以，确定测试环境很重要，这很有可能是被黑客扫描到你的服务器的docker-selenium端口，导致的黑客进入你的控制窗口，通过网页下载了挖矿病毒

可能，後續更新也不是我操作的，可能他有設定密碼挖礦病毒才沒回來，不過我確定我們新的expose port 有設定只限localhost

**Comment by TigerShuai** [comment]
> 您尚未阐明最新图像是否仍然发生这种情况。

后续没有在发现过，后续服务器增加了安全措施，需要在1个网络环境下才能互相访问资源，所以永远不会再出现了，可以谷歌下，是否还有其他人存在类似问题，如果能确认是没有修改默认密码导致的挖矿病毒，这个风险问题也就不存在了

**Comment by yexk** [comment]
我也遇到了。
---
```
[root@ecs-test-and-vpn completions]# cat xm
# bash completion for xm                                   -*- shell-script -*-

_xen_domain_names()
{
    COMPREPLY=( $( compgen -W "$( xm list 2>/dev/null | \
        awk '!/Name|Domain-0/ { print $1 }'  )" -- "$cur" ) )
}

_xen_domain_ids()
{
    COMPREPLY=( $( compgen -W "$( xm list 2>/dev/null | \
        awk '!/Name|Domain-0/ { print $2 }' )" -- "$cur" ) )
}

_xm()
{
    local cur prev words cword
    _init_completion || return

    # TODO: _split_longopt

    local command options

    commands='console vncviewer create new delete destroy domid domname
        dump-core list mem-max mem-set migrate pause reboot rename reset
        restore resume save shutdown start suspend sysrq trigger top unpause
        uptime usb-add usb-del vcpu-list vcpu-pin vcpu-set debug-keys dmesg
        info log serve sched-credit sched-sedf block-attach block-detach
        block-list block-configure network-attach network-detach network-list
        vtpm-list pci-attach pci-detach pci-list pci-list-assignable-devices
        scsi-attach scsi-detach scsi-list vnet-list vnet-create vnet-delete
        labels addlabel rmlabel getlabel dry-run resources dumppolicy setpolicy
        resetpolicy getpolicy shell help'

    if [[ $cword -eq 1 ]] ; then
        COMPREPLY=( $( compgen -W "$commands" -- "$cur" ) )
    else
        if [[ "$cur" == *=* ]]; then
            prev=${cur/=*/}
            cur=${cur/*=/}
        fi

        command=${words[1]}
        if [[ "$cur" == -* ]]; then
            # possible options for the command
            case $command in
                create)
                    options='-c'
                    ;;
                dmesg)
                    options='--clear'
                    ;;
                list)
                    options='--long'
                    ;;
                reboot)
                    options='-w -a'
                    ;;
                shutdown)
                    options='-w -a -R -H'
                    ;;
                sched-credit)
                    options='-d -w -c'
                    ;;
                block-list|network-list|vtpm-list|vnet-list)
                    options='-l --long'
                    ;;
                getpolicy)
                    options='--dumpxml'
                    ;;
                new)
                    options='-h --help --help_config -q --quiet --path= -f=
                        --defconfig= -F= --config= -b --dryrun -x --xmldryrun
                        -s --skipdtd -p --paused -c --console_autoconnect'
                    ;;
            esac
            COMPREPLY=( $( compgen -W "$options" -- "$cur" ) )
        else
            case $command in
                console|destroy|domname|domid|list|mem-set|mem-max| \
                pause|reboot|rename|shutdown|unpause|vcpu-list|vcpu-pin| \
                vcpu-set|block-list|network-list|vtpm-list)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                    esac
                    ;;
                migrate)
                    _count_args
                        case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            _known_hosts_real "$cur"
                            ;;
                    esac
                    ;;
                restore|dry-run|vnet-create)
                    _filedir
                    ;;
                save)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            _filedir
                            ;;
                    esac
                    ;;
                sysrq)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            COMPREPLY=( $( compgen -W "r s e i u b" \
                                -- "$cur" ) )
                            ;;
                    esac
                    ;;
                block-attach)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            COMPREPLY=( $( compgen -W "phy: file:" \
                                -- "$cur" ) )
                            ;;
                        5)
                            COMPREPLY=( $( compgen -W "w r" -- "$cur" ) )
                            ;;
                        6)
                            _xen_domain_names
                            ;;
                    esac
                    ;;
                block-detach)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            COMPREPLY=( $( compgen -W "$( xm block-list $prev \
                                2>/dev/null | awk '!/Vdev/ { print $1 }' )" \
                                -- "$cur" ) )
                            ;;
                    esac
                    ;;
                network-attach)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        *)
                            COMPREPLY=( $( compgen -W "script= ip= mac= bridge=
                                backend=" -- "$cur" ) )
                            ;;
                    esac
                    ;;
                network-detach)
                    _count_args
                    case $args in
                        2)
                            _xen_domain_names
                            ;;
                        3)
                            COMPREPLY=( $(compgen -W "$( xm network-list $prev \
                                2>/dev/null | awk '!/Idx/ { print $1 }' )" \
                                -- "$cur" ) )
                            ;;
                    esac
                    ;;
                sched-credit)
                    case $prev in
                        -d)
                            _xen_domain_names
                            return
                            ;;
                    esac
                    ;;
                create)
                    _filedir
                    COMPREPLY+=( \
                        $( compgen -W '$( command ls /etc/xen 2>/dev/null )' \
                        -- "$cur" ) )
                    ;;
                new)
                    case $prev in
                        -f|-F|--defconfig|--config)
                            _filedir
                            return
                            ;;
                        --path)
                            _filedir -d
                            return
                            ;;
                    esac

                    _count_args
                        case $args in
                        2)
                            _xen_domain_names
                            ;;
                    esac
                    ;;
            esac
        fi
    fi
} &&
complete -F _xm xm

# ex: filetype=sh

```
