### ISSUE TITLE
[🐛 Bug]: Can't specify download path

### ISSUE THREAD

**Issue by marcelo-cintra** [SeleniumHQ/docker-selenium#1853]
### What happened?

When calling http://localhost:4444/session/{session_id}/se/files getting the error:

`{
  "value": {
    "error": "script timeout",
    "message": "Please specify the path wherein the files downloaded using the browser would be available via the command line arg [--downloads-path] and restart the node\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1104-gcp', java.version: '11.0.18'\nDriver info: driver.version: unknown",
    "stacktrace": "org.openqa.selenium.WebDriverException: Please specify the path wherein the files downloaded using the browser would be available via the command line arg [--downloads-path] and restart the node\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1104-gcp', java.version: '11.0.18'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.local.LocalNode.downloadFile(LocalNode.java:490)\n\tat org.openqa.selenium.grid.node.DownloadFile.execute(DownloadFile.java:39)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:248)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n"
  }
}`

### Command used to start Selenium Grid with Docker

```shell
version: "3.3"
services:
  chrome1:
    image: selenium/node-chrome 
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_DOWNLOADS_PATH=/home/seluser/Downloads

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
C# code used:

var options = new ChromeOptions();
options.AddUserProfilePreference("download.default_directory", "/home/seluser/Downloads/");
options.AddArguments("--start-maximized");
options.AddAdditionalOption("se:downloadsEnabled", true);
var capabilities = options.ToCapabilities();
driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
The feature is still in beta and was revamped for 4.9.

Please update to 4.9.1 and follow the updated docs https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node

**Comment by marcelo-cintra** [comment]
Tks @diemol , wasn't using :latest on images.
Also added SE_OPTS on chrome node.

current 100% working version of docker-compose:

`version: "3.3"
services:
  chrome1:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_DOWNLOADS_PATH=/home/seluser/Downloads
      - SE_OPTS=--enable-managed-downloads true

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"`

**Comment by diemol** [comment]
`SE_NODE_DOWNLOADS_PATH` this environment variable does not exist.

**Comment by marcelo-cintra** [comment]
ok, but it worked because /home/seluser/Downloads is the default folder, right?
I will remove to avoid future problems...

**Comment by diemol** [comment]
No, those folders are temporal and used internally. The user does not know where they are, and they get removed when the session ends.

**Comment by arthursantosololu** [comment]
@diemol Sometimes even if the session id is open the error above is shown:

http://localhost:4444/session/96a9f53ef33f405bd582aea64595bcef/se/files

{
  "value": {
    "error": "invalid session id",
    "message": "Cannot find session with id: 96a9f53ef33f405bd582aea64595bcef\nBuild info: version: '4.9.1', revision: 'eb2032df7f'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1104-gcp', java.version: '11.0.18'\nDriver info: driver.version: unknown",
    "stacktrace": "org.openqa.selenium.NoSuchSessionException: Cannot find session with id: 96a9f53ef33f405bd582aea64595bcef\nBuild info: version: '4.9.1', revision: 'eb2032df7f'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1104-gcp', java.version: '11.0.18'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.local.LocalNode.downloadFile(LocalNode.java:605)\n\tat org.openqa.selenium.grid.node.DownloadFile.execute(DownloadFile.java:39)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:255)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n"
  }
}

What can it be?
