### ISSUE TITLE
[🐛 Bug]: Standalone chromium hangs indefinitely

### ISSUE THREAD

**Issue by ash14** [SeleniumHQ/docker-selenium#1857]
### What happened?

When running multiple sessions concurrently, specifically with one under mobile emulation, it appears that clicks don't get triggered and we just hang indefinitely. No timeouts are triggered.

Minimally reproducible example:

```py
import selenium
print(selenium.__version__)  # 4.9.1
from selenium import webdriver
from selenium.webdriver.common.by import By

options = webdriver.ChromeOptions()
options.add_experimental_option('mobileEmulation', {
    'deviceMetrics': {
        'width': 375,
        'height': 812,
        'pixelRatio': 1,
    }
})
d1 = webdriver.Remote('http://localhost:4444/wd/hub', options=options)
# d1 = webdriver.Chrome('chromedriver', options=options)

d2 = webdriver.Remote('http://localhost:4444/wd/hub', options=webdriver.ChromeOptions())
# d2 = webdriver.Chrome('chromedriver', options=webdriver.ChromeOptions())

d1.get('http://example.com')

d2.get('http://example.com')

print(d1.find_element(By.XPATH, '//a')) # <selenium.webdriver.remote.webelement.WebElement (session="1dbed03158da4ddf077c90e8d43cf597", element="41E3C216C74A9E517BB1B4893F9E2CCC_element_1")>

d1.find_element(By.XPATH, '//a').click() # This hangs indefinitely

d1.quit()
d2.quit()
```

- This issue isn't reproducible when running chromedriver natively
- I assume this is unrelated to using the arm images

Curiously, just moving one of the windows seems to "unstick" this:

https://github.com/SeleniumHQ/docker-selenium/assets/7367512/b0544c4a-be47-469d-9b5e-35485a343ead

### Command used to start Selenium Grid with Docker

```shell
docker run --rm -p 4444:4444 -p 7900:7900 --shm-size="2g" --env "SE_NODE_MAX_SESSIONS=2" seleniarm/standalone-chromium:4.9.1
```

### Relevant log output

```shell
(no relevant logs)
```

### Operating System

Mac OS 13.4

### Docker Selenium version (tag)

4.9.1

**Comment by tobytang1987** [comment]
I have the same issue, any update on this?

**Comment by ash14** [comment]
> I have the same issue, any update on this?

@tobytang1987 can you confirm the image/version you're using? I'm not sure if this issue is specific to the Seleniarm images or not

**Comment by tobytang1987** [comment]
@ash14 I tested it on "selenium/standalone-chrome:111.0" image.  

i did more investigate on your 'moving one of the windows seems to "unstick"' video scenario.   

It seams it's all about the visibility of browser window when Selenium is trying to operate, **if the browser window is not visible when Selenium trying to click an element on it**, script hangs and end up with a Timeout error(TCPSocket closed).  

It means if we minimize the second browser to make the first browser is visible before operating the first browser, the click element operation will success.
It also means if both browser windows are visible(with proper window size and position), the click element operation will success.

**Comment by tobytang1987** [comment]
I can reproduce this issue against,
```
Ruby 3.2.2
selenium-webdriver gem 4.10.0
selenium/standalone-chrome:114.0 image
```
**mobile emulation** is a required precondition.

Script to reproduce:
```ruby
require "selenium-webdriver"

options = Selenium::WebDriver::Chrome::Options.new
options.add_emulation(device_name: "Galaxy S5")
driver_1 = Selenium::WebDriver.for :remote, url: "http://localhost:4444/wd/hub", options: options
driver_1.manage.window.maximize
driver_1.navigate.to "https://www.google.com"

options_2 = Selenium::WebDriver::Chrome::Options.new
driver_2 = Selenium::WebDriver.for :remote, url: "http://localhost:4444/wd/hub", options: options_2
driver_2.manage.window.maximize
driver_2.navigate.to "https://www.google.com"
element_1 = driver_1.find_element(css: "a.active") # "ALL" tab link in the header of Google.com mobile
element_1.click
```

**Comment by Specii** [comment]
I am also facing the same issue. I suspect there is a chrome option that is enabled by dafault which deprioritizes rendering/processing if the window is offscreen or not visible.

**Comment by VietND96** [comment]
Reading the report, I understand that your situation is you started a Grid using a docker image standalone, and there is another mobile emulation registered to the Grid. Then you ran a test on that emulator node and faced the issue.
Another statement I also saw
`This issue isn't reproducible when running chromedriver natively`
`mobile emulation is a required precondition`
So, in my point of view, there is nothing actionable for docker-selenium. Can you try newer image tags recently (4.16.x) with the new emulator chrome version and confirm?

**Comment by diemol** [comment]
We are closing as we did not get more information.

**Comment by ash14** [comment]
Sorry, missed the request for an update on this.

> you started a Grid using a docker image standalone, and there is another mobile emulation registered to the Grid. Then you ran a test on that emulator node and faced the issue.

Correct, although only one session is under mobile emulation

> Can you try newer image tags recently (4.16.x) with the new emulator chrome version and confirm?

Can confirm the issue is still present in 4.16.0 using the `seleniarm/standalone-chromium:4.16.1` image.

**Comment by diemol** [comment]
Did you use Ubuntu as a host OS when trying to running ChromeDriver natively?

**Comment by ash14** [comment]
No, I'm on MacOS 14.2.1 (M2 Pro)
