### ISSUE TITLE
Reporting/getting node browser version

### ISSUE THREAD

**Issue by bobbotron** [SeleniumHQ/docker-selenium#186]
It would be super useful for testing if there were an easy way to see each node's browser version in the selenium hub.  Currently the configuration tab for each node doesn't report browser version, is this something that could be added in the future?

**Comment by vbyjsue** [comment]
In case you did not know, this is retrievable from the tests. I use the rubydrivers and capybara: `driver.browser.capabilities.version`
Then print it to your favourite reporter.

**Comment by diemol** [comment]
@bobbotron this seems to be included in the most recent versions.

![image](https://cloud.githubusercontent.com/assets/5992658/26531594/705b0318-43ec-11e7-9fad-73512c8b3887.png)

Looks like the issue can be closed, right?
