### ISSUE TITLE
[🐛 Bug]: Cannot connect to remote selenium grid 4

### ISSUE THREAD

**Issue by neswine** [SeleniumHQ/docker-selenium#1861]
### What happened?

I am trying to connect the grid setup in my cloud. I am able to create the session but for some reason, I cant run the tests.
Seems like websocket connection is getting timed out.

I tried to setup in my mac M1 using docker and the tests run fine.

### Command used to start Selenium Grid with Docker

```shell
SELENIUM_REMOTE_URL=<REMOTE_URL> npx playwright test
```

### Relevant log output

```shell
browserType.launch: WebSocket error: connect ETIMEDOUT 100.98.0.2:4444
    =========================== logs ===========================
    <selenium> connecting to https://selenium-grid-hub.shopk8sd.int.aws.zooplus.io/
    <selenium> connected to sessionId=f539a10634af5631464e697ce97a4b64
    <selenium> using selenium v4
    <selenium> retrieved endpoint ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp for sessionId=f539a10634af5631464e697ce97a4b64
    <ws connecting> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp
    <ws error> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp error connect ETIMEDOUT 100.98.0.2:4444
    <ws connect error> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp connect ETIMEDOUT 100.98.0.2:4444
    <ws disconnected> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp code=1006 reason=
    <selenium> disconnecting from sessionId=f539a10634af5631464e697ce97a4b64
    <selenium> disconnected from sessionId=f539a10634af5631464e697ce97a4b64
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.6.0

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

**Comment by neswine** [comment]
@diemol I tried this but did not work for me. I used this in my local setup and worked but not in remote setup.

**Comment by diemol** [comment]
I do not know how that works with Playwright, sorry. The instructions shared work for Selenium tests.

**Comment by neswine** [comment]
@diemol Can you provide any insight on this? I can see the session being created but I believe the webscoket connection inside the browser is what's getting timed out. Anyway to get some more logs on this?
