### ISSUE TITLE
how do I get the ssh account and password[🚀 Feature]: 

### ISSUE THREAD

**Issue by mlzboy** [SeleniumHQ/docker-selenium#1862]
### Feature and motivation

 I execute long term task if I want keep selenium server running on remote,I need two container,one is selenium server standalone,another one is jupyter notebook with novnc also. So I want to know the standalone chrome image ssh account and password I want to add a jupyter notebook above it 
 

### Usage example

as above description

**Comment by diemol** [comment]
I am not sure if ssh is enabled or not. But the root user and the seluser do not have passwords.
