### ISSUE TITLE
[🚀 Feature]: 

### ISSUE THREAD

**Issue by subin-krishna-test** [SeleniumHQ/docker-selenium#1866]
### Feature and motivation

In the current Selenium grid deployed with helm in Kubernetes, I can only run the tests  in a specific browser version( for example in Selenium grid 4.9 the Chrome node uses selenium/node-chrome:latest image to run the test. It uses Chrome version v103.0 and for Firefox selenium/node-firefox:latest with version v112.0 ). 

![image](https://github.com/SeleniumHQ/docker-selenium/assets/93134410/3ebfac7c-80e6-4ea6-8fd9-61fc1d90b456)
![image](https://github.com/SeleniumHQ/docker-selenium/assets/93134410/b126b0fb-5ca3-4f10-bed1-38736bba052f)
 
What if I want to run the selenium tests in multiple versions of a browser? like Chrome v102, v104, v112, and v113. Run the tests in different browser versions when I specified the browser version. What if I want to run on an OS other than Linux.

### Usage example

selenium-side-runner --server <url> -c "browserName='chrome' version='103.0' platform='Windows 8.1'"  it should run the tests in chrome browser version 103.0 with windows 8.1 platform in Kubernetes

**Comment by diemol** [comment]
You can always pass the image tag to change the browser version https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid#configuration. Also these images are based on Ubuntu, Windows does not work.

**Comment by subin-krishna-test** [comment]
> You can always pass the image tag to change the browser version https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid#configuration. Also these images are based on Ubuntu, Windows does not work.

@diemol What if I want multiple versions of Chrome in a grid? Can I pass multiple image tags?
