### ISSUE TITLE
[🚀 Feature]: All live preview in single window like Zalenium

### ISSUE THREAD

**Issue by iamsethi** [SeleniumHQ/docker-selenium#1878]
### Feature and motivation

I know selenium suppports live preview but is there any that i can view all live preview of test execution in single window
like Zalenium - https://opensource.zalando.com/zalenium/

### Usage example

![image](https://github.com/SeleniumHQ/docker-selenium/assets/12969857/c0d35151-d372-40c3-b6e5-eafa545ace01)

**Comment by diemol** [comment]
No, this is not supported and folks can view only one session at a time. You can open several tabs to view different sessions. Zalenium had that feature because it was nice for demos, but in reality it does not add much value when checking or debugging a test.
