### ISSUE TITLE
[🐛 Bug]: Description on https://hub.docker.com/r/selenium/standalone-chrome talks of "Edge"

### ISSUE THREAD

**Issue by jochenberger** [SeleniumHQ/docker-selenium#1880]
### What happened?

In the heading, it says "This image provides a [Selenium Grid Standalone](https://www.selenium.dev/documentation/grid/getting_started/#standalone) with Edge, which enables you to run [WebDriver tests remotely](https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/)."
It should probably say Chrome instead.
I tried to create a PR but could not find the respective source for the content.
Then I tried to create a regular non-bug issue but that is not possible.

### Command used to start Selenium Grid with Docker

```shell
null
```

### Relevant log output

```shell
null
```

### Operating System

null

### Docker Selenium version (tag)

null

**Comment by diemol** [comment]
Good catch, thank you. Just updated the content.
