### ISSUE TITLE
[🐛 Bug]: Containers size increases filling up disk space

### ISSUE THREAD

**Issue by atranou** [SeleniumHQ/docker-selenium#1884]
### What happened?

Image(s):
selenium/node-chrome: selenium/node-chrome:4.3.0-20220726
selenium/hub:  selenium/hub:4.3.0-20220726
Docker Version:
Docker version 20.10.5+dfsg1, build 55c4c88

Chrome creates a lot of files in tmp check image in the section "Relevant log output"

This leads to a huge disk usage
![image](https://github.com/SeleniumHQ/docker-selenium/assets/60021063/99c63a13-8497-45aa-b90f-8ab50a59c19d)

Is there any way to fix it?
Thank you in advance!

### Command used to start Selenium Grid with Docker

```shell
We have set up a docker-compose yaml file with the relevant services.
The images we are using are: 
selenium/node-chrome: selenium/node-chrome:4.3.0-20220726
selenium/hub:  selenium/hub:4.3.0-20220726

We don't have this issue with the firefox node (selenium/node-firefox:4.3.0-20220726)
```

### Relevant log output

```shell
![image](https://github.com/SeleniumHQ/docker-selenium/assets/60021063/45e26d4f-a6ba-4933-86c5-8b9185234c96)
```

### Operating System

ubuntu

### Docker Selenium version (tag)

selenium/hub:4.3.0-20220726 image

**Comment by diemol** [comment]
That is a very old version, please use the latest and comment if the issue still happens. We can reopen then.
