### ISSUE TITLE
[🐛 Bug]: TimeZone change behavior changed

### ISSUE THREAD

**Issue by Zoupers** [SeleniumHQ/docker-selenium#1888]
### What happened?

take a look at https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806

Here is what happend to me.
![image](https://github.com/SeleniumHQ/docker-selenium/assets/29817738/2db8df20-5cdb-4420-ab32-61b680f5a6a7)

### Command used to start Selenium Grid with Docker

```shell
You can try to set timezone in the container like the way in the Dockerfile, and you will find it not work.
```

### Relevant log output

```shell
No
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

selenium/standalone-chrome:114.0-20230614

**Comment by Zoupers** [comment]
https://github.com/SeleniumHQ/docker-selenium/blob/077862f91a925a246d13027f482a0be69e51de10/Base/Dockerfile#L41C3-L41C3

**Comment by diemol** [comment]
Would you like to send a pull request?

**Comment by Zoupers** [comment]
Cool, I will have a try.

**Comment by VietND96** [comment]
Hi @Zoupers, I made a PR #2031 updated this with the result is
```bash
Step 7/19 : RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     cat /etc/timezone
 ---> Running in 5ddabe277c0d

Current default time zone: 'Asia/Shanghai'
Local time is now:      Wed Nov 29 03:16:57 CST 2023.
Universal Time is now:  Tue Nov 28 19:16:57 UTC 2023.

Asia/Shanghai

```
Can you please confirm if this corrects your expectations?
