### ISSUE TITLE
[🚀 Feature]: Helm Chart does not support Selenium Grid Basic Auth

### ISSUE THREAD

**Issue by trungprivate** [SeleniumHQ/docker-selenium#1890]
### Feature and motivation

When enabling selenium grid basic auth (by using ROUTER_USERNAME and ROUTER_PASSWORD) the autoscaling feature is not working - no nodes will get created. 

Upon investigation, it was found chrome|edge|firefox.node.hpa.url is set to {{ include "seleniumGrid.graphqlURL" . }} which does not include the username/password required for basic auth.

I made a hacky change to prove this by changing chromenode.hpa.url to "http://username:password@selenium-hub:4444/graphql" which worked.

This is not ideal, and I'd like to ask if the template can be updated to support basic auth username and password in the hpa url.

### Usage example

1. Allow global variables to be specified for hub username / password
2. If a username/password is specified, automatically pass these as environment variables to selenium hub
3. If a username/password is specified, automatically update the hpa.url to include basic auth credentials

**Comment by diemol** [comment]
Would you like to send a pull request?

**Comment by trungprivate** [comment]
Sure, let me put something together and I will send through

**Comment by trungprivate** [comment]
I have raised PR: https://github.com/SeleniumHQ/docker-selenium/pull/1894
