### ISSUE TITLE
[🐛 Bug]: selenium/standalone-chrome(grid docker) devtools(cdp) not work

### ISSUE THREAD

**Issue by w2650489** [SeleniumHQ/docker-selenium#1892]
### What happened?

when java run :driver = new Augmenter().augment(driver);   
ERROR:java.net.ConnectException: connection timed out: /172.17.0.6:4444
Unable to establish websocket connection to http://172.17.0.6:4444/session/ef499e9888d5197b4c162f636a94b777/se/cdp
this ip is in docker network ,not server ip. so java can't use devtools(cdp).i want use 192.168.1.x ip like this.

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest
```

### Relevant log output

```shell
ERROR:java.net.ConnectException: connection timed out: /172.17.0.6:4444
Unable to establish websocket connection to http://172.17.0.6:4444/session/ef499e9888d5197b4c162f636a94b777/se/cdp
```

### Operating System

server centos7 

### Docker Selenium version (tag)

4.10

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout
