### ISSUE TITLE
Need MinReplicaCount in ScaleObject Templates

### ISSUE THREAD

**Issue by petkovp** [SeleniumHQ/docker-selenium#1899]
### What happened?

When template scaleObject is turn on the pods restarted permanently.

Every 20 seconds pod restarted, because KEDA scaleDown the pod to 0.

The KEDA scaling use activation phase. More info here: https://keda.sh/docs/2.11/concepts/scaling-deployments/#activating-and-scaling-thresholds

We need from scaling phase and we need from value MinReplicaCount in ScaleObject Templates

### Command used to start Selenium Grid with Docker

```shell
We need from additional value or specification in ScaleObject Templates: minReplicaCount

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
-----------------
spec:
  minReplicaCount: {{ .Values.chromeNode.replicas }}
  maxReplicaCount: {{ .Values.chromeNode.maxReplicaCount }}
```

### Relevant log output

```shell
Log message from k8s cluster ScaleObject

ScaleObject down replicas from 1 to 0
```

### Operating System

macOS

### Docker Selenium version (tag)

4.10.

**Comment by nVizzz** [comment]
I have the same situation too. I also need the possibility to define MinReplicaCount in ScaledObject.

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium/pull/1932
