### ISSUE TITLE
Chrome docker browser sometimes fails to respond to the first command sent to it.

### ISSUE THREAD

**Issue by stenver** [SeleniumHQ/docker-selenium#190]
I dont know if this is the right project to write. We have a big GRID docker setup with over 100 chrome/firefox dockers attached to it. When running the tests, almost all of them are occupied.

Sometimes, a test gets stuck and eventually times out. We tracked down the bug to be with chrome only. We are using ruby and Capybara. Basically when connecting to the browser for the first time:
```
  def visit_blank_page
    session.driver.browser.navigate.to("https://#{@host}/blank")
  end
```
The chrome seems to boot up, but it doesn't give a response back to the test. After a timeout period the test fails with "Error forwarding the new session Error forwarding the request Read timed out".

See full stack from here: 

https://gist.github.com/stenver/b6d2f16f1f4aae3547a53f348cb13f1a

When looking at the GRID logs, we can see that GRID successfully distributes the borwser.
When looking at the node logs, the last message is simply that starting chrome.
When looking at the chrome debug logs, we can see that the command to visit the page was never received.

We eventually fixed the issue, by simply timing out and retrying. It seems that the browser is brought up, but loses the first command. The workaround is to just send the command again, until we receive response. Usually the second attempt already works. See full code example in here: 

https://gist.github.com/stenver/87f56519ae495a6b7d47bd08816c129d

**Comment by JesseChezenko-AI** [comment]
My team was having the exact same error "Error forwarding the new session Error forwarding the request Read timed out". 

I used the DBUS hack described here and the error never occurred again. https://github.com/SeleniumHQ/docker-selenium/issues/87

Maybe the same can work for you?

**Comment by stenver** [comment]
Thanks, we will try it out!

**Comment by stenver** [comment]
This fixed it, thanks!
