### ISSUE TITLE
[🐛 Bug]: Bump io.netty:netty-handler and com.google.guava:guava versions 

### ISSUE THREAD

**Issue by Satyadm123** [SeleniumHQ/docker-selenium#1900]
### What happened?

 io.netty:netty-handler and com.google.guava:guava are installed versions are getting flagged in vulnerability scans  .
current versions  io.netty:netty-handler 4.1.92.Final and 4.1.79.Final . required version 4.1.94.Final.

com.google.guava:guava installed version 31.1-jre and 31.1-android -required version 32.0.0.

### Command used to start Selenium Grid with Docker

```shell
FROM selenium/standalone-firefox:dev
```

### Relevant log output

```shell
Flagged as vulunerable packages.
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

dev

**Comment by pradeep-rhythm** [comment]
We are also getting same in vulnerability scans.

**Comment by diemol** [comment]
Versions were bumped in the upstream Selenium repository. 4.12 should be released in a week or so.

**Comment by cloverdiego** [comment]
Hi, when will the new version with the fix be released? Thanks!
