### ISSUE TITLE
[🚀 Feature]: Kerberos auth for nodes inside docker

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/docker-selenium#1902]
### Feature and motivation

We are getting more and more webapps that use kerberos as authentication. 

Is there a way to put a kerberos ticket from a Windows AD user inside a docker container and use it to authenticate against a webapp? Else this would be a nice feature for us. 

### Usage example

Login into a webapp with a windows user.

**Comment by diemol** [comment]
This is out of the scope of this project.
