### ISSUE TITLE
Upgrade Selenium to version 2.53 and Latest browser version for Chrome & Firefox

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#191]

**Comment by jeffjk-me** [comment]
I have an updated version, I'll commit a branch and submit a pull request this afternoon.

**Comment by jeffjk-me** [comment]
https://github.com/SeleniumHQ/docker-selenium/pull/192

**Comment by kayabendroth** [comment]
Fixed with https://github.com/SeleniumHQ/docker-selenium/pull/194.
