### ISSUE TITLE
[🐛 Bug]: Webdriver takes long time to load in restricted docker environment

### ISSUE THREAD

**Issue by soumya173** [SeleniumHQ/docker-selenium#1917]
### What happened?

I'm using `selenium/standalone-chrome:115.0` docker image as base and put my test scripts to execute them inside the container.
Everytime the webdriver is loaded it takes 5 minutes to load. And gives the below error:
```
Exception trying to discover chromedriver version: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out
```
It is clear that the firewall doesn't allow outside access from the container. The question is why do the webdriver need to query for versions from internet?
The chrome driver and other pre-requisites are already packaged in the docker container. The selenium version is: `4.11.2`
Along with this error the test suite runs properly but gets delayed due to this timeout wait.

Is there any way to disable this version check? or reduce the timeout for a workaround?

### Command used to start Selenium Grid with Docker

```shell
FROM selenium/standalone-chrome:115.0

USER root

RUN apt-get update && apt-get install python3-distutils python3-pip -y
RUN pip install selenium html-testRunner paramiko requests pymongo==3.11.4

ADD config.json /root/config.json
ADD field-mappings.json /root/field-mappings.json
ADD utils.py /root/utils.py
ADD constants.py /root/constants.py
ADD SanityTestMain.py /root/SanityTestMain.py
```

### Relevant log output

```shell
Exception trying to discover chromedriver version: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out
Chrome driver loaded successfully
```

### Operating System

Ubuntu 20.04.5 LTS

### Docker Selenium version (tag)

selenium/standalone-chrome:115.0

**Comment by dkrowl** [comment]
@soumya173 

My guess would be that the selenium-manager got the chromedriver version from PATH but after that it tries to check compatibility from github.

I too want to disable this feature as I have everything already installed in the image and would need to configure proxy to allow internet access. Configuring proxy via `SE_PROXY` environment variable works but I'd really like to be able to disable this feature.

EDIT: with `SE_OFFLINE=true` you can disable the check.

**Comment by diemol** [comment]
Good catch. We will find time to improve that.
