### ISSUE TITLE
[🐛 Bug]: The Selenium Grid Scaler incorrectly scales Linux pods when Windows nodes are present in the cluster.

### ISSUE THREAD

**Issue by Doofus100500** [SeleniumHQ/docker-selenium#1925]
### What happened?

Hi, I've opened an [issue](https://github.com/kedacore/keda/issues/4908) in the KEDA project, but they say that the problem is in Selenium.

### Command used to start Selenium Grid with Docker

```shell
helm chart 0.20.0
```

### Relevant log output

```shell
All the information is available in the issue at the provided link.
```

### Operating System

k8s

### Docker Selenium version (tag)

4.11.0-20230801

**Comment by diemol** [comment]
I don't understand. Do you expect that Windows containers are started?

**Comment by Doofus100500** [comment]
No, the Windows nodes are located on VMs. The problem arises precisely with Linux containers when there are Windows nodes in the cluster, namely scaling fewer containers than the requested number of sessions.

**Comment by diemol** [comment]
I see. I am not sure what needs to be changed to have that working. Any help is appreciated.

**Comment by Doofus100500** [comment]
I think trouble is not in selenium https://github.com/kedacore/keda/issues/4908#issuecomment-1699023782

**Comment by Doofus100500** [comment]
Hi @VietND96 , I'm ultimately being ignored in the Keda project. Perhaps you have the power to fix this bug?

**Comment by VietND96** [comment]
@Doofus100500, I also started understanding what the scaler did in https://github.com/kedacore/keda/blob/main/pkg/scalers/selenium_grid_scaler.go and try to add a possible fix
As you can see, most current open issues related to autoscaling in K8s need the proper fix in the scaler, which is present only in the KEDA project.

**Comment by Doofus100500** [comment]
Yes, I noticed progress in this direction here: https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/values.yaml#L721 =) I even want to study Go lang in order to submit a Pull Request to them, but life circumstances are currently stronger than me.

**Comment by Doofus100500** [comment]
@VietND96 Hi, made a PR to keda to fix that https://github.com/kedacore/keda/pull/5917

**Comment by VietND96** [comment]
@Doofus100500, by fixing this, do you have any clue on the issue (in a few tickets mentioned) - when using strategy: accurate, the number of pods scales up is greater than the number of requests in the queue (e.g. 1 request - 2 or 3 pod could come up).

**Comment by Doofus100500** [comment]
@VietND96 No, I haven’t encountered such issues without Windows nodes

**Comment by VietND96** [comment]
@Doofus100500 I started refactoring the scaler calculation via PR https://github.com/kedacore/keda/pull/6169
If have time, can you walk through changes in unit tests to see your scenarios is covered

**Comment by VietND96** [comment]
@Doofus100500, I saw a unit test in your last PR, so I will include it in my PR and check it.

**Comment by Doofus100500** [comment]
@VietND96 That's it! https://github.com/kedacore/keda/pull/6169/files#diff-59589fb3c981e73ac59806307eb5a26330cafb0260a88777cba9124621748a8cR335

**Comment by VietND96** [comment]
You can follow https://github.com/SeleniumHQ/docker-selenium/tree/trunk/.keda
Replace KEDA component image tag and try out to see how it works
