### ISSUE TITLE
[🐛 Bug]: Unable to add extension to Firefox 

### ISSUE THREAD

**Issue by nobodykr** [SeleniumHQ/docker-selenium#1927]
### What happened?

Webdriver doesnt allow to add addons/extension to firefox.
I am running 4 firefox instances.
I have a volume mapped to all instances.
In python there's no function to read the file and add it as extension.

if u use the path within the container

example 1:
`    profile.add_extension("/opt/selenium/selenium_extensions/noptcha-0.3.13.xpi")
`
Error seen: 

- Unexpected error: [Errno 2] No such file or directory: '/opt/selenium/selenium_extensions/noptcha-0.3.13.xpi'

example 2:
`    profile.add_extension("D:/selenium-grid2/extensions/noptcha-0.3.13.xpi")
`

error seen: 

- Unexpected error: [WinError 267] The directory name is invalid: 'C:\\Users\\Diogo\\AppData\\Local\\Temp\\tmp35wjdd25\\extensions\\NopeCHA:CAPTCHASolver@0.3.13'

### Command used to start Selenium Grid with Docker

```shell
version: '3.8'

services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    networks:
      - grid

  firefox-node:
    image: selenium/node-firefox:latest
    depends_on:
      - hub
    volumes:
      - selenium_extensions:/opt/selenium/selenium_extensions # Here we use the named volume
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

networks:
  grid:

volumes:  # Define the volume
  selenium_extensions:


docker-compose up -d --scale firefox-node=4
```

### Relevant log output

```shell
example 1:
`    profile.add_extension("/opt/selenium/selenium_extensions/noptcha-0.3.13.xpi")
`
Error seen: 

- Unexpected error: [Errno 2] No such file or directory: '/opt/selenium/selenium_extensions/noptcha-0.3.13.xpi'

example 2:
`    profile.add_extension("D:/selenium-grid2/extensions/noptcha-0.3.13.xpi")
`

error seen: 

- Unexpected error: [WinError 267] The directory name is invalid: 'C:\\Users\\Diogo\\AppData\\Local\\Temp\\tmp35wjdd25\\extensions\\NopeCHA:CAPTCHASolver@0.3.13'
```

### Operating System

Windows 10 

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
Please check https://www.selenium.dev/documentation/webdriver/browsers/firefox/#add-ons, and remember that the path needs to be on the same host where your code is running (not inside Grid).
