### ISSUE TITLE
[🐛 Bug]: update dockerhub with latest version of selenium

### ISSUE THREAD

**Issue by fprin** [SeleniumHQ/docker-selenium#1928]
### What happened?

The last time that this repo was updated was two years ago: https://hub.docker.com/r/selenium/standalone-chrome-debug/tags, could you push the lates image at least?

**Comment by fprin** [comment]
related with this: https://github.com/SeleniumHQ/selenium/issues/12619#issuecomment-1694595875

**Comment by diemol** [comment]
Chrome Debug does not exist anymore. It was removed over 2 years ago. The regular Chrome image has all those features now.
