### ISSUE TITLE
[🚀 Feature]:  undetected-chromedriver

### ISSUE THREAD

**Issue by Lee2532** [SeleniumHQ/docker-selenium#1936]
### Feature and motivation

I think it'd be nice to be able to do a undetected-chromedriver here, too What do you think?

lib : https://github.com/ultrafunkamsterdam/undetected-chromedriver

### Usage example

More effective selenium control with undetected-chromedriver

**Comment by diemol** [comment]
We do support the intention of websites (and their owners) to opt out of being automated, which is the primary purpose of the [WebDriver flag](https://www.w3.org/TR/webdriver1/#interface). Therefore, we won't add this to the repository. You are always free to build your image with that ChromeDriver binary.
