### ISSUE TITLE
[🐛 Bug]: Duplicate node instance with 1 session is getting created by default 

### ISSUE THREAD

**Issue by ketanb02** [SeleniumHQ/docker-selenium#1937]
### What happened?

After upgrading the selenium node Chrome and Firefox to 4.12.1-20230904 - we have observed that it is creating a duplicate instance of Chrome and Firefox respectively along with the session mentioned in max-session or per CPU count. 

We are using the same yaml and toml files, we used for previous version - 4.11.0-20230801

### Command used to start Selenium Grid with Docker

```shell
podman-compose -f chrome-compose.yml up



version: "3.0"
services:

 chrome_Container1:
    container_name: chromenode
    environment:
      - SE_EVENT_BUS_HOST=<hub-host>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=<node-host>
      - SE_NODE_PORT=5151
      - REMOTE_HOST=https://${HOSTNAME}:5151
      - SE_OPTS=--https-certificate /home/seluser/selgrid.pem --https-private-key /home/seluser/selgrid.key --config /opt/bin/config-chrome.toml
      - SE_NODE_GRID_URL=https://<hub-host>:4444
    image: selenium/node-chrome:4.12.1-20230904
    privileged: true
    shm_size: 2gb
    ports:
      - 5151:5151
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - /opt/grid/cert:/home/seluser
      - ${PWD}/config-chrome.toml:/opt/bin/config-chrome.toml
```

### Relevant log output

```shell
Additional node instances with 1 session is created. Along with the 3 other instances.

07:55:49.233 INFO [NodeOptions.getSessionFactories] - Detected 3 available processors
07:55:49.279 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "116","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 3 times
07:55:49.280 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "116.0","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times
07:55:49.301 INFO [Node.<init>] - Binding additional locator mechanisms: relative
07:55:49.789 INFO [UnboundZmqEventBus.<init>] - Event bus ready
07:55:49.889 INFO [NodeServer$1.start] - Starting registration process for Node https://<node-ip>:5151
07:55:49.902 INFO [NodeServer.execute] - Started Selenium node 4.12.1 (revision 8e34639b11): https://<node-ip>:5151
07:55:49.930 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
07:55:50.626 INFO [NodeServer.lambda$createHandlers$2] - Node has been added


Apart from the above I have observed below error in the logs

W: [pulseaudio] core-util.c: Failed to open configuration file '/home/seluser/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
2023-09-11 07:55:47,936 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Failed to create secure directory (/home/seluser/.config/pulse): Permission denied
No PulseAudio daemon running, or not running as session daemon.
Failed to create secure directory (/home/seluser/.config/pulse): Permission denied
No PulseAudio daemon running, or not running as session daemon.
Failed to create secure directory (/home/seluser/.config/pulse): Permission denied
No PulseAudio daemon running, or not running as session daemon.
```

### Operating System

Linux

### Docker Selenium version (tag)

4.12.1-20230904

**Comment by diemol** [comment]
Can you share the full yml file?

**Comment by ketanb02** [comment]
version: "3.0"
services:

 chrome_Container1:
    container_name: chromenode
    environment:
      - SE_EVENT_BUS_HOST=<hub-host>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=<node-host>
      - SE_NODE_PORT=5151
      - REMOTE_HOST=https://${HOSTNAME}:5151
      - SE_OPTS=--https-certificate /home/seluser/selgrid.pem --https-private-key /home/seluser/selgrid.key --config /opt/bin/config-chrome.toml
      - SE_NODE_GRID_URL=https://<hub-host>:4444
    image: selenium/node-chrome:4.12.1-20230904
    privileged: true
    shm_size: 2gb
    ports:
      - 5151:5151
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - /opt/grid/cert:/home/seluser
      - ${PWD}/config-chrome.toml:/opt/bin/config-chrome.toml

**Comment by ketanb02** [comment]
`version: "3.0"
services:

 chrome_Container1:
    container_name: chromenode
    environment:
      - SE_EVENT_BUS_HOST=<hub-host>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=<node-host>
      - SE_NODE_PORT=5151
      - REMOTE_HOST=https://${HOSTNAME}:5151
      - SE_OPTS=--https-certificate /home/seluser/selgrid.pem --https-private-key /home/seluser/selgrid.key --config /opt/bin/config-chrome.toml
      - SE_NODE_GRID_URL=https://<hub-host>:4444
    image: selenium/node-chrome:4.12.1-20230904
    privileged: true
    shm_size: 2gb
    ports:
      - 5151:5151
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - /opt/grid/cert:/home/seluser
      - ${PWD}/config-chrome.toml:/opt/bin/config-chrome.toml`

**Comment by diemol** [comment]
A Node Chrome cannot work on its own, you need something like a Hub. Which is why I'd like to see the complete yml

**Comment by ketanb02** [comment]
Tried with hub 4.12.1-20230904 - same issue observed


version: "3"
services:

 selenium-hub:
    environment:
      - SE_OPTS=--https-certificate /home/seluser/selgrid.pem --https-private-key /home/seluser/selgrid.key
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    privileged: true
    extra_hosts:
      - "servername:serverip"
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    volumes:
      - /opt/sel4/certs:/home/seluser
      - /opt/sel4/certs/cacerts:/etc/ssl/certs/java/cacerts
    restart: always

**Comment by diemol** [comment]
>4.10.0-20230607

This is not the latest

In any case, please share the yml file that has both NodeChrome and Hub so I understand how you start this.

**Comment by ketanb02** [comment]
we use separate yml as our hub and node are running on different servers and we start it using command

podman-compose -f <filename.yml> up

**Comment by ketanb02** [comment]
Here the toml for chrome

[node]
detect-drivers = false

[[node.driver-configuration]]
display-name = "chrome"
stereotype="{\"browserName\":\"chrome\", \"browserVersion\":\"116\",\"platformName\": \"linux\"}"

**Comment by diemol** [comment]
This is because two config files are being used. The one you are mounting and the system default. 

Either use this [environment variable](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L175) to set the file name, or use the default name when mounting it.
