### ISSUE TITLE
Unicode characters being replaced by question marks on NoVnc clipboard

### ISSUE THREAD

**Issue by 1muratbulbul** [SeleniumHQ/docker-selenium#1942]
### What happened?

I am using Turkish keyboard and I enabled Turkish language UTF-8 in Selenium Docker. However, when i copied some special words(ŞşİğĞöÖÜü) from my host to inside docker or opposite way, characters has been replaced by question marks in NoVnc Clipboard. 

Here, what is the problem? Does it VNC Server capability?

LANG=tr_TR.UTF-8
LANGUAGE=tr_TR.UTF-8
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC="tr_TR.UTF-8"
LC_TIME="tr_TR.UTF-8"
LC_COLLATE="tr_TR.UTF-8"
LC_MONETARY="tr_TR.UTF-8"
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER="tr_TR.UTF-8"
LC_NAME="tr_TR.UTF-8"
LC_ADDRESS="tr_TR.UTF-8"
LC_TELEPHONE="tr_TR.UTF-8"
LC_MEASUREMENT="tr_TR.UTF-8"
LC_IDENTIFICATION="tr_TR.UTF-8"
LC_ALL=tr_TR.UTF-8

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest
```

### Relevant log output

```shell
No error logs captured
```

### Operating System

standalone-chrome:latest on Ubuntu

### Docker Selenium version (tag)

standalone-chrome:latest

**Comment by diemol** [comment]
I'd suggest raising this to the https://github.com/novnc/noVNC project, we simply embed their solution.
