### ISSUE TITLE
[🚀 Feature]: Patching OS packages for vulnerabilities

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#1943]
### Feature and motivation

I recently scanned the images for security vulnerabilities and found many OS packages having High vulnerabilities.
I had to extend all the docker images to pass the security scan in organization.
Is there some reason we are not using `apt-get upgrade -yq` in Dockerfiles ?

I can raise PR if apt-get upgrade is acceptable solution for OS related vulnerabilities. 

### Usage example

Many enterprise want to scan docker images before using.

**Comment by diemol** [comment]
Sure, happy to review a PR for that.

**Comment by amardeep2006** [comment]
Thanks , I will try to raise one this weekend.

**Comment by amardeep2006** [comment]
https://github.com/SeleniumHQ/docker-selenium/pull/1950 fixed this
