### ISSUE TITLE
[🚀 Feature]: Integrated docker config for changing owner while creating container for better download support

### ISSUE THREAD

**Issue by diyoyo** [SeleniumHQ/docker-selenium#1947]
### Feature and motivation

I just read the README file of the repo, and noticed that I had read some interesting lines while setting up Jupyter-Spark containers.

Here is what is reads:
```
    sudo docker run  \
        -d \
        --name jupyter-spark \
        --restart always \
        --shm-size 512M \
        --user root \
        -e NB_USER=$mainuser \
        -w "/home/${NB_USER}/" \
        -e CHOWN_HOME=yes \
        -p 8888:8888 \
...
```

And indeed, it does reconfigure the rights in the virtual environment created by the docker.
So maybe there could be a similar proposal for selenium-node.

### Usage example

I would use this to avoid users to forget to perform the workaround mentioned at the bottom of the README file.

PS: Also, the README file could be edited to mention whether or not, in addition to the workaround, one should set the `--enable-managed-downloads true`somewhere ?
Is it by default or do we need:        ` -e SE_OPTS="--enable-managed-downloads true" `

Thanks.

**Comment by VietND96** [comment]
Hi @diyoyo, `--enable-managed-downloads true` is not enabled by default. We have to set via `-e SE_OPTS="--enable-managed-downloads true"` only.

**Comment by diemol** [comment]
@diyoyo did you test that? Does that actually removes the need for the work around?

**Comment by VietND96** [comment]
@diemol, I am testing this, if it works I think we also can close 2 PRs are pending on removal of chmod 777

**Comment by diemol** [comment]
Sounds good, then we can add this to the README. Thanks!

**Comment by diyoyo** [comment]
I haven't tested it actually as I had other priorities, but I'm glad to hear it works 😄
