### ISSUE TITLE
[🐛 Bug]: Helm chart is not deploying  browser node max instances

### ISSUE THREAD

**Issue by rajeshl8** [SeleniumHQ/docker-selenium#1949]
### What happened?

Issue: We are using selenium-docker repo (https://github.com/SeleniumHQ/docker-selenium) and trying to deploy multiple browser instances per pod, but the deployment always gives as one instance of the browser. 

Command used 
![image](https://github.com/SeleniumHQ/docker-selenium/assets/5583674/3c63a5fd-d568-4904-a216-d52f8d01eb10)

<img width="1713" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/5583674/c467a55c-145f-4ac4-9ac9-4815c3c6337c">

### Command used to start Selenium Grid with Docker

```shell
helm install my-grid ./selenium-grid          
--set isolateComponents=false           
--set hub.nameOverride=my-grid-selenium-hub           
--set chromeNode.nameOverride=my-grid-selenium-chrome           
--set chromeNode.enabled=true         
--set chromeNode.replicas=3          
--set chromeNode.nodeMaxInstances=6           
--set chromeNode.nodeMaxSession=3           
--set chromeNode.imageName= selenium4/node-chrome           
--set router.imageName= selenium4/router           
--set router.nameOverride=my-grid-selenium-router           
--set distributor.imageName=selenium4/distributor          
--set distributor.nameOverride=my-grid-selenium-distributor           
--set eventBus.imageName=selenium4/event-bus          
--set eventBus.nameOverride=my-grid-selenium-eventBus           
--set busConfigMap.name=my-grid           
--set sessionMap.imageName=selenium4/sessions          
--set sessionMap.nameOverride=my-grid-selenium-sessionMap           
--set sessionQueue.imageName=selenium4/session-queue          
 --set sessionQueue.nameOverride=my-grid-selenium-sessionQueue          
 --set hub.imageName= selenium4/hub          
 --set chromeNode.imageTag=latest          
 --set hub.imageTag=latest
```

### Relevant log output

```shell
No helm out put related to this issue
```

### Operating System

ubuntu

### Docker Selenium version (tag)

4.9.1

**Comment by amardeep2006** [comment]
You should try `chromeNode.maxReplicaCount` instead of `chromeNode.nodeMaxInstances` .

**Comment by rajeshl8** [comment]
Thanks Amardeep. No luck. It did not help me. I mean it installed only one browser per container.
<img width="1174" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/5583674/cf8a55d5-de09-4651-81b9-2ea5c353bdb6">

**Comment by amardeep2006** [comment]
@rajeshl8 If you want more than one browser per container than you have to pass two environment variables to container.
Please refer this  https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container

You can use helmchart for this via extraEnvironmentVariables

I had misunderstood the initial request.

**Comment by rajeshl8** [comment]
Thanks @amardeep2006 , Will test and update.

**Comment by amardeep2006** [comment]
@rajeshl8 Did you manage to verify . If yes you can close the issue.

**Comment by rajeshl8** [comment]
Actually I tried multiple things, but non of them worked with helm charts.

**Comment by VietND96** [comment]
Hi @rajeshl8, I think you have to set 2 things via node `extraEnvironmentVariables`. Let's create a custom values to give in helm command via `-f` or `--values`
```yaml
chromeNode:
  extraEnvironmentVariables:
    - name: SE_NODE_OVERRIDE_MAX_SESSIONS
      value: "true"
    - name: SE_NODE_MAX_SESSIONS
      value: "10"
```
By default, `SE_NODE_OVERRIDE_MAX_SESSIONS` is false, we have to enable it before setting max sessions
