### ISSUE TITLE
[🐛 Bug]: Chrome-node cannot trigger click

### ISSUE THREAD

**Issue by dragonphoenix** [SeleniumHQ/docker-selenium#1953]
### What happened?

I compared Chrome and Firefox DesiredCapabilities, find Firefox DesiredCapabilities has moz:webdriverClick, but Chrome without se:webdriverClick.

Chrome DesiredCapabilities
{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "117.0.5938.88",
  "chrome": {
    "chromedriverVersion": "117.0.5938.88 (be6afae4721209be42944bbcd325665f9f44563b-refs/branch-heads/5938_62@{#9})",
    "userDataDir": "/tmp/.org.chromium.Chromium.j8pBz3"
  },
  "fedcm:accounts": true,
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:44023"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "linux",
  "proxy": {},
  "se:bidiEnabled": false,
  "se:cdp": "ws://172.31.0.4:4444/session/b287ccb04a672b3b6fde591b12c3e483/se/cdp",
  "se:cdpVersion": "117.0.5938.88",
  "se:vnc": "ws://172.31.0.4:4444/session/b287ccb04a672b3b6fde591b12c3e483/se/vnc",
  "se:vncEnabled": true,
  "se:vncLocalAddress": "ws://172.31.0.4:7900",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:extension:minPinLength": true,
  "webauthn:extension:prf": true,
  "webauthn:virtualAuthenticators": true
}

Firefox DesiredCapabilities
{
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "browserVersion": "117.0.1",
  "moz:accessibilityChecks": false,
  "moz:buildID": "20230912013654",
  "moz:debuggerAddress": "127.0.0.1:30706",
  "moz:firefoxOptions": {
    "args": [
      "--window-size=1920,1080"
    ],
    "binary": "/opt/firefox-latest/firefox"
  },
  "moz:geckodriverVersion": "0.33.0",
  "moz:headless": false,
  "moz:platformVersion": "3.10.0-1160.el7.x86_64",
  "moz:processID": 11074,
  "moz:profile": "/tmp/rust_mozprofile0o10gL",
  "moz:shutdownTimeout": 60000,
  **"moz:webdriverClick": true,**
  "moz:windowless": false,
  "pageLoadStrategy": "normal",
  "platformName": "linux",
  "proxy": {},
  "se:bidiEnabled": false,
  "se:cdp": "ws://172.31.0.6:4444/session/a799af3f-b9a9-4cb5-a28f-2972869ed3c5/se/cdp",
  "se:cdpVersion": "85.0",
  "se:noVncPort": 7900,
  "se:vnc": "ws://172.31.0.6:4444/session/a799af3f-b9a9-4cb5-a28f-2972869ed3c5/se/vnc",
  "se:vncEnabled": true,
  "se:vncLocalAddress": "ws://172.31.0.6:7900",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify"
}

### Command used to start Selenium Grid with Docker

```shell
version: "3" 
services:
  chrome:
    image: selenium/node-chrome:117.0
    #container_name: chrome
    shm_size: 2gb 
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    #ports:
    #  - "7901:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=350
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_PASSWORD=123456
      - SE_VNC_NO_PASSWORD=1
  edge:
    image: selenium/node-edge:117.0
    #container_name: edge
    shm_size: 2gb 
    depends_on:
      - selenium-hub
    #ports:
    #  - "7902:7900"
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=350
      - SE_NODE_MAX_SESSIONS=5
      - SE_VNC_PASSWORD=123456
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: selenium/node-firefox:117.0
    #container_name: firefox
    #shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 2
    #ports:
    #  - "7903:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=350
      - SE_NODE_MAX_SESSIONS=20
      - SE_VNC_PASSWORD=123456
      - SE_VNC_NO_PASSWORD=1
  selenium-hub:
    image: selenium/hub:4.12.1
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
None
```

### Operating System

CentOS 7.9

### Docker Selenium version (tag)

117.0

**Comment by diemol** [comment]
If you have something working on Firefox and not Chrome, you should report it to the Google folks. 

Please submit Chrome/ChromeDriver issues to the Chromium team at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
