### ISSUE TITLE
[🐛 Bug]: noVNC stops working if you specify a subPath different from the standard one.

### ISSUE THREAD

**Issue by Doofus100500** [SeleniumHQ/docker-selenium#1954]
### What happened?

If you specify a subPath & ingress.path for example "/staging" in the values file noVNC stops working in the UI

### Command used to start Selenium Grid with Docker

```shell
helm
```

### Relevant log output

```shell
no log's were founded
```

### Operating System

k8s

### Docker Selenium version (tag)

4.13.0-20230926

**Comment by VietND96** [comment]
Looks like similar the case was discussed in https://github.com/SeleniumHQ/docker-selenium/issues/1991#issuecomment-1793207009

**Comment by VietND96** [comment]
This issue was fixed in upstream SeleniumHQ/selenium#12791 released `4.16`, new image tag `4.16.0-20231206` and chart version `0.26.0` taken it. Can you retest and confirm?
