### ISSUE TITLE
[🚀 Feature]: Update ubuntu:focal-20230301 to the latest version to resolve security vunerabilities

### ISSUE THREAD

**Issue by imtheish97** [SeleniumHQ/docker-selenium#1955]
### Feature and motivation

“ubuntu:focal-20230301” is nearly 7 months old (1st March) there is a more recent replacement “focal-20230801” (from 1st Aug). There have also been a number of images released since focal-20230301, prior to focal-20230801:
•	focal-20230308 (6 months old)
•	focal-20230412 (5 months old)
•	focal-20230605 (3 months old)
•	focal-20230624 (3 months old)

### Usage example

Selenium’s base Dockerfile should be updated to use the newer ubuntu “focal” releases, or even moving to a newer version of Ubuntu (Focal = 20.04, Jammy = 22.04, Lunar = 23.04).
Moving to focal-20230801 (1st Aug) will resolve:
•	ncurses-bin (high)
•	libncursed6 (high)
•	libncursesw6 (high)
•	libtinfo6 (high)
•	ncurses-base (high)

**Comment by diemol** [comment]
There is a PR to move to Jammy but it is blocked because Firefox is a snap package in Jammy. You are welcome to help us.

For the focal bump, could you please send a PR?

**Comment by imtheish97** [comment]
> There is a PR to move to Jammy but it is blocked because Firefox is a snap package in Jammy. You are welcome to help us.
> 
> For the focal bump, could you please send a PR?

no problem will make a PR thanks!

**Comment by amardeep2006** [comment]
I added a PR few days back that patches all os packages during build. It should be already addressed. https://github.com/SeleniumHQ/docker-selenium/pull/1950

**Comment by imtheish97** [comment]
Yes however there are some vulnerabilities that will also be solved with an upgrade of focal @amardeep2006. I have created a branch @diemol however I cannot push as I have permission denied. Possibly my contribution form may need to be verified? Thanks

**Comment by imtheish97** [comment]
created a PR here: https://github.com/SeleniumHQ/docker-selenium/pull/1962
