### ISSUE TITLE
[🐛 Bug]: minReplicaCount not available in the xxx-node-scaledjobs.yaml files, which prevents downscaling of pods when done

### ISSUE THREAD

**Issue by d4vke** [SeleniumHQ/docker-selenium#1956]
### What happened?

I updated selenium grid from v4.10 to v4.12.1 and saw that keda is now incorporated.
However when running the grid, I see that pods are no longer downscaling automatically.

When adding the line minReplicaCount: {{ .Values.chromeNode.minReplicaCount }} at spec level in the xxx-node-scaledjobs.yaml files (for chrome, edge and firefox), the automatic downscaling is working again.

I see that this is also not available in the latest version of the grid (selenium-grid-0.21.3.)
Could you add this in future releases?

### Command used to start Selenium Grid with Docker

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

Kubernetes

### Docker Selenium version (tag)

4.13.0-20230926

**Comment by VietND96** [comment]
Hi,
I think you can add extra minReplicaCount under config "autoscaling.scaledJobOptions". Tested in chart selenium-grid-0.22.0
```
autoscaling:
  scaledJobOptions:
    minReplicaCount: 0
    ...
```

**Comment by diemol** [comment]
Thanks for answering, @vietnd96!
