### ISSUE TITLE
[🐛 Bug]:  Auto cleanup /var/lib/docker/overlay2 for sessions not closed properly on standalone container

### ISSUE THREAD

**Issue by nkgiovannivl** [SeleniumHQ/docker-selenium#1968]
### What happened?

When the user uses `docker stop container_name` with a active session and does not uses `driver.close` before it, the container still uses space in `/var/lib/docker/overlay2`, below image of sessions that does not close properly:

![image](https://github.com/SeleniumHQ/docker-selenium/assets/48342344/64186b7d-edbc-44a2-9165-ea9326cdc489)

How can delete those old sessions without delete/create the container again and avoid full disk space usage in my docker?.

Thanks for your support

### Command used to start Selenium Grid with Docker

```shell
version: '3'

services:
  selenium:
    container_name: sele_chrome_lxc_102015
    image: selenium/standalone-chrome:4.13.0-20230926
    shm_size: "2gb"
    ports:
      - "4445:4444"
      - "5900:5900"
    restart: always
```

### Relevant log output

```shell
N/A
```

### Operating System

Ubuntu 23.04

### Docker Selenium version (tag)

4.13.0-20230926

**Comment by diemol** [comment]
There is not much we can do as either you need to either close the session properly with `.quit()`, let the Grid stop the idle session, or remove the container yourself.
