### ISSUE TITLE
What is the number of nodes a hub can handle and is it customizable?

### ISSUE THREAD

**Issue by wehappyfew** [SeleniumHQ/docker-selenium#197]
How many nodes does a hub handle without problems?
I have set up a grid with selenium-docker images and when I launch 20 nodes the tests occupy only the 9.
Is there a documentation of how master handles tests between agents? 
Shouldn't be some limits and configs for defining how many nodes can each master handle?

**Comment by tparikka** [comment]
I would assume it is based on how you are driving the tests. For example, if you are driving the tests with NUnit and marking your test fixtures or the entire assembly with the [Parallelizable](https://github.com/nunit/docs/wiki/Parallelizable-Attribute) attribute, NUnit will default to running only as many concurrent tests as you have CPU cores. For NUnit you can override this in AssemblyInfo.cs for whatever assembly drives the tests by setting the [LevelOfParallelism](https://github.com/nunit/docs/wiki/LevelOfParallelism-Attribute) attribute.

Moving from the test assembly side of things, you might also need to set the GRID_MAX_SESSION environment variable in your hub. In the dockerfile GRID_MAX_SESSION defaults to 5 (same as the default if you run the hub natively); using `-e GRID_MAX_SESSION=20` should tell your hub server to accept up to 20 sessions concurrently.

**Comment by ddavison** [comment]
ultimately it would depend on what sort of resources you are devoting to the docker machine from the host.  that being said,  there is no "clear distinction" where the thresholds are.

If you find it, let me know and we can create a wiki page on it!
