### ISSUE TITLE
[🐛 Bug]: Can't update selenium nodes since 4.8.3, because of slow down

### ISSUE THREAD

**Issue by piotrlaczykowski** [SeleniumHQ/docker-selenium#1972]
### What happened?

Hello,
we are facing this problem for about 3 months.
We can't update selenium chrome/edge nodes higher than 4.8.3, because our pass rate drops by half.
It looks like higher versions like 4.10, 4.11, 4.12, 4.13 work much slower.

Thanks to these problems we switched from old selenium deployments to helm chart.
We are running our cluster on K8s 1.21
Switching to the helm chart didn't help at all. Pass rate is the same.

So right now we are stuck on version 4.8.3 with our nodes but the rest of the components run the newest 4.13 without any problems

### Command used to start Selenium Grid with Docker

```shell
.
```

### Relevant log output

```shell
.
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.13.0-20231004

**Comment by diemol** [comment]
I am not sure what is expected from this issue. There is nothing actionable for us. You can come to our chat and ask questions if you need help.
