### ISSUE TITLE
[🐛 Bug]: SessionNotCreated Could not start a new session. Response code 500 error.

### ISSUE THREAD

**Issue by pranesh517** [SeleniumHQ/docker-selenium#1977]
### What happened?

Using docker-compose.yml to start the Selenium GRID with docker compose command as mentioned in documentation.
When tried to execute the test cases via mvn test on GRID, getting :
_SessionNotCreated Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)_ 

### Command used to start Selenium Grid with Docker

```shell
docker-compose -f docker-compose.yml up

        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX.name());
        desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, "chrome");
        driver = new RemoteWebDriver(new URL("http://localhost:4444/"), desiredCapabilities);
        String url = readConfigFile.getConfigData().getProperty("url");
        driver.get(url);
        driver.manage().window().maximize();
```

When tried to run the tests on firefox, it worked as expected. Issue is with Chrome

### Relevant log output

```shell
[SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ac0c265b01fd38c6168960feba357362","eventTime": 1697722822517328655,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: '16d2bed6e50d', ip: '172.18.0.3'\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: '16d2bed6e50d', ip: '172.18.0.3'\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:151)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:644)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:563)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:823)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:783)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, platformName: linux}]"}}
```

### Operating System

All

### Docker Selenium version (tag)

4.14.1-20231016

**Comment by hanbz** [comment]
I got the same problem and not use the docker composer. 
Just run the command : `docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.14.1-20231020`
My programming language is PHP. Use php-webdriver library.

**Comment by VietND96** [comment]
Can you share the version of selenium client driver used in your test automation fwk?
I have tested the same image tags `4.14.1-20231016` and `4.14.1-20231020` with client driver version `4.13.0` (Java). It works fine.
Suspect the issue could be version compatibility between the client and browser node

**Comment by pranesh517** [comment]
@vietnd96 I am using 4.13.0 in pom.xml

Image tags: 4.11.0-20230801

**Comment by aviv-saranrajprabhakaran** [comment]
Hi @vietnd96 I'm encountering the same problem as well using docker compose for both chrome & MicrosoftEdge browsers. 

**Note**: 
1. Encountering the issue in almost every image tags from 4.10 till 4.14.1. 
2. Firefox works fine

**Trace:**

**_Chrome:_**

`wdio-automation-chrome-1        | Driver info: driver.version: unknown
wdio-automation-chrome-1        | 08:08:34.353 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
wdio-automation-chrome-1        |   (unknown error: DevToolsActivePort file doesn't exist)
wdio-automation-chrome-1        |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
wdio-automation-chrome-1        | Host info: host: 'd6e97e2c0b8e', ip: '172.30.0.3'
wdio-automation-chrome-1        | Build info: version: '4.10.0', revision: 'c14d967899'
wdio-automation-chrome-1        | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.51-0-virt', java.version: '11.0.19'`

**_Microsoft Edge:_**
`wdio-automation-edge-1        | Driver info: driver.version: unknown
wdio-automation-edge-1        | 08:24:11.406 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: crashed.
wdio-automation-edge-1        |   (unknown error: DevToolsActivePort file doesn't exist)
wdio-automation-edge-1        |   (The process started from msedge location /usr/bin/microsoft-edge is no longer running, so msedgedriver is assuming that msedge has crashed.) 
wdio-automation-edge-1        | Host info: host: '050fc8548c38', ip: '192.168.16.3'
wdio-automation-edge-1        | Build info: version: '4.10.0', revision: 'c14d967899'
wdio-automation-edge-1        | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.51-0-virt', java.version: '11.0.19'`

_**Firefox: (Works fine in almost every image tags from 4.10 to 4.14.1)**_
`wdio-automation-firefox-1        | 08:28:45.323 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
selenium-hub                         | 08:31:30.118 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
selenium-hub                         |  [Capabilities {acceptInsecureCerts: true, browserName: firefox}]
wdio-automation-firefox-1        | 08:31:31.115 INFO [DriverService$Builder.getLogOutput] - Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
wdio-automation-firefox-1        | 08:32:01.223 INFO [LocalNode.newSession] - Session created by the Node. Id: c0a2ace0-e30e-44cc-9cf9-6dceec1a3ac4, Caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 114.0, moz:accessibilityChecks: false, moz:buildID: 20230608214645, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 6.1.51-0-virt, moz:processID: 319, moz:profile: /tmp/rust_mozprofiletaFP51, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidi: ws://192.168.32.3:4444/sess..., se:cdp: ws://192.168.32.3:4444/sess..., se:noVncPort: 7900, se:vnc: ws://192.168.32.3:4444/sess..., se:vncEnabled: true, se:vncLocalAddress: ws://192.168.32.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
`

**Comment by VietND96** [comment]
Hi @aviv-saranrajprabhakaran , I also tried to reproduce based on info that you guys posted. Btw, is it possible for you to share the docker compose file which is used to bring containers up? Then I can try the same deployment in my local and see.

**Comment by aviv-saranrajprabhakaran** [comment]
Hi @vietnd96, Thanks for the prompt response. Please find the sample docker compose file

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=2

  edge:
    image: selenium/node-edge:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=2

  firefox:
    image: selenium/node-firefox:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=2

  chrome_video:
    image: selenium/video:ffmpeg-6.0-20231025
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
  
  edge_video:
    image: selenium/video:ffmpeg-6.0-20231025
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4

  firefox_video:
    image: selenium/video:ffmpeg-6.0-20231025
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4
  selenium-hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

**Comment by therealdjryan** [comment]
Have you tried adding SE_NODE_GRID_URL to the docker-compose file?
https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

**Comment by aviv-saranrajprabhakaran** [comment]
Hi @therealdjryan , I tried with SE_NODE_GRID_URL but encountering the same issue. Thanks for the suggestion!

**Comment by diemol** [comment]
You are using an old version of the images, I believe Chrome had a bug. Try with the latest https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.14.1-20231025

**Comment by aviv-saranrajprabhakaran** [comment]
Hi @diemol , I have also tried the latest image which you mentioned but am encountering the same issue.

**Comment by diemol** [comment]
Then please report the issue to the Chrome team, we simply pack the browsers in Docker images.
