### ISSUE TITLE
[🐛 Bug]: Images missing for 4.14.0

### ISSUE THREAD

**Issue by AB-xdev** [SeleniumHQ/docker-selenium#1979]
### What happened?

The images for Selenium ``4.14.0`` are missing. Images are however present for ``4.14.1`` and ``4.13.0``.

### Command used to start Selenium Grid with Docker

```shell
-
```

### Relevant log output

```shell
docker pull selenium/standalone-firefox:4.14.0
Error response from daemon: manifest for selenium/standalone-firefox:4.14.0 not found: manifest unknown: manifest unknown
```

### Operating System

OS independent

### Docker Selenium version (tag)

4.14.0

**Comment by diemol** [comment]
4.14.0 had a bug so we skipped it.
