### ISSUE TITLE
[🚀 Feature]: Updating base image to Ubuntu 22.04 or latest LTS Debian 

### ISSUE THREAD

**Issue by rambangaru** [SeleniumHQ/docker-selenium#1997]
### Feature and motivation

Ubuntu focal works on most cases but in our user case, we do add additional python packages for the purpose of intercepting the network requests and other internal ones. All our packages works from python 3.10 or above where focal comes with python 3.8

I can install python 3.10 by creating a docker file keeping Selenium image as base but however, I wonder may be some other people have similar problem with python or other base environment comes with focal. 

so making this request to update base image to more modern LTS.  

### Usage example

It makes it easier to install additional libraries to make testing flexible and reliable.

**Comment by diemol** [comment]
See https://github.com/SeleniumHQ/docker-selenium/pull/1923. Maybe you can help us to complete that work?

**Comment by rambangaru** [comment]
Thank you. Let me close this as the work is already in plan and in progress as part #1923 and will try my best to help moving to jammy.
