### ISSUE TITLE
[🐛 Bug]: Timeout on create session

### ISSUE THREAD

**Issue by YanK-fr** [SeleniumHQ/docker-selenium#1999]
### What happened?

When i want to create a session with `php-webdriver 1.13` i have a timeout.
I can see an empty session in selenium grid interface but after i have a timeout.
On docker i have a warning in logs (relevant log output).

I use novnc to see if chrome work and it's work fine.

PHP version : `PHP 8.2.10-2ubuntu1`
Docker version `4.15.0 (revision 1d14b5521b)`
Chromedriver version is `119.0.6045.105`
Chrome version is `119.0.6045.123`

### Command used to start Selenium Grid with Docker

```shell
sudo docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest
```

### Relevant log output

```shell
WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "6f6a299a485c09976b06ff4ecc6128d6","eventTime": 1699467875443483729,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "67","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession"}}
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.15.0

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout
