### ISSUE TITLE
Node communication doesn't work when docker icc=false

### ISSUE THREAD

**Issue by devinrsmith** [SeleniumHQ/docker-selenium#20]
IMO, it's best practice to set icc=false (https://docs.docker.com/articles/networking/#between-containers). I'm assuming the wire protocol between hub and node is more complex than the single simple client/server socket. As such, the hub and node don't successfully communicate with each other when icc=false. Any workarounds besides setting icc=true?

**Comment by saifsysim** [comment]
0
down vote
favorite
I am trying to run docker Selenium on diff hosts

using these commands on Hub

> docker run -d -p 4444:4444 --name hub selenium-hub:1.0.0

Node

> docker run -d -p 5556:5556 -e REMOTE_HOST="http://nodeip:5556" -e HUB_PORT_4444_TCP_ADDR=hubip -e HUB_PORT_4444_TCP_PORT=4444 --name chrome-node3 selenium-chrome-node:1.0.0

How ever,I see the that the node is registered , but when i fire a test the request says pending

Here are the Hub logs

 

> 14:50:29.078 WARN - Cleaning up stale test sessions on the unregistered node http://10.205.87.185:5557
> 14:50:29.107 INFO - Registered a node http://10.205.87.185:5557
> 14:50:29.473 INFO - Marking the node http://10.205.87.185:5556 as down: cannot reach the node for 2 tries
> 14:50:39.121 INFO - Marking the node http://10.205.87.185:5557 as down: cannot reach the node for 2 tries
> 14:50:59.489 INFO - Unregistering the node http://10.205.87.185:5556 because it's been down for 30016 milliseconds
> 14:50:59.489 WARN - Cleaning up stale test sessions on the unregistered node http://10.205.87.185:5556
> 14:50:59.516 INFO - Registered a node http://10.205.87.185:5556
> 14:51:09.192 INFO - Unregistering the node http://10.205.87.185:5557 because it's been down for 30071 milliseconds
> 14:51:09.192 WARN - Cleaning up stale test sessions on the unregistered node http://10.205.87.185:5557
> 14:51:09.541 INFO - Marking the node http://10.205.87.185:5556 as down: cannot reach the node for 2 tries

The Node seems to be up and running. Not sure what can be the issue

**Comment by yatheeshAtzenq** [comment]
I am trying to run docker Selenium on diff hosts

using these commands on Hub
> docker run -p 4444:4444 -d -P --name selenium-hub selenium/hub
on Node
> docker run -d -p 5558:5556 -e SE_OPTS="-host 10.20.50.53 -port 5558" -e HUB_PORT_4444_TCP_ADDR="10.20.50.92" -e HUB_PORT_4444_TCP_PORT="4444" --name firefox selenium/node-firefox

How ever,I see the that the node is registered , but when i fire a test the request says pending
Here are the Hub logs and screenshot 

> 12:26:43.302 INFO - Unregistering the node http://10.20.50.53:5558 because it's been down for 60014 milliseconds
 12:26:43.302 WARN - Cleaning up stale test sessions on the unregistered node http://10.20.50.53:5558
 12:26:43.389 INFO - Registered a node http://10.20.50.53:5558
 12:27:03.395 INFO - Marking the node http://10.20.50.53:5558 as down: cannot reach the node for 2 tries

![image](https://cloud.githubusercontent.com/assets/10920243/22064802/2b94f394-ddab-11e6-9c12-5975b658af03.png)
 
 The Node seems to be up and running. Not sure what can be the issue

**Comment by diemol** [comment]
Hi @devinrsmith,

I am now going through old issues to find ways to solve them and close them. I was reading the docs about `--icc=false` [here](https://docs.docker.com/engine/userguide/networking/default_network/container-communication/#communication-between-containers), and the most relevant part of it is this one:
>If you choose the most secure setting of --icc=false, then how can containers communicate in those cases where you want them to provide each other services? The answer is the --link=CONTAINER_NAME_or_ID:ALIAS

But this puts me in a loop because in a different part of the [documentation](https://docs.docker.com/compose/compose-file/#links), docker recommends to avoid using `--link`
>Warning: >The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

So I am not sure how to proceed here... what I see if that the `icc=false` topic has only been touched in this issue and nowhere else in this repo, which might point that it is not a common case/concern. My first thought would be to close this issue since it didn't get too much activity from the community, but we are open to any suggestions or changes if they make sense.

I'll leave the issue open for a few days to wait for feedback.

**Comment by devinrsmith** [comment]
Hi @diemol . It's been a while since I've used selenium or Docker. At the time I believe I would have used `--link`, but I can't remember specifically. Other than that, I don't think I can provide any useful feedback. Feel free to continue with this ticket or close! Thanks.

**Comment by diemol** [comment]
Thanks for the quick answer @devinrsmith!
I'll close it then.
