### ISSUE TITLE
[🚀 Feature]: Support video uploader to GCP bucket (GS) from helm-charts (k8s)

### ISSUE THREAD

**Issue by cr-liorholtzman** [SeleniumHQ/docker-selenium#2000]
### Feature and motivation

Many organizations use GCP rather then AWS 

### Usage example

Many organizations use GCP rather then AWS

**Comment by Doofus100500** [comment]
What about to use image with rclone?
https://github.com/SeleniumHQ/docker-selenium/issues/2007#issuecomment-1809556456

**Comment by VietND96** [comment]
This will be added via #2097

**Comment by VietND96** [comment]
RCLONE is added as the default video uploader. Let's read https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid#video-uploader for configuring different remote targets.
