### ISSUE TITLE
[🐛 Bug]: Forwarded SE_VNC_NO_PASSWORD=1 not applied

### ISSUE THREAD

**Issue by alxweis** [SeleniumHQ/docker-selenium#2021]
## My Setup

**docker-compose.yml**
```
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.15.0-20231110
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    shm_size: 2gb

  selenium-hub:
    image: selenium/hub:4.15.0-20231110
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```
**config.toml**
```
[docker]
configs = [
    "selenium/standalone-chrome:100.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"100.0\"}",
    "selenium/standalone-chrome:93.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"93.0\"}"
]

url = "http://127.0.0.1:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20231016"
```

## What happend?

When I run a test, it shows up in the grid sessions as intended as a running session (http://localhost:4444/ui#/sessions). From there I can watch the execution of a test via VNC (by clicking on the small camera icon to the left of the test session).

![image](https://github.com/SeleniumHQ/docker-selenium/assets/105790090/934b9a58-89a1-45c1-826c-f297afb85350)
This image shows that the variable `SE_VNC_NO_PASSWORD=1` is forwarded and set in the generated container, where the test session will execute. Hence password authentication for VNC should be disabled.

![image](https://github.com/SeleniumHQ/docker-selenium/assets/105790090/cd316821-5781-4211-a723-2d42795eb844)
But as you can see password (`secret`) for VNC is still required.

Why do I still have to enter my VNC password even though I've set `SE_VNC_NO_PASSWORD=1`?
Thank you for your assistance in advance!

### Command used to start Selenium Grid with Docker

```shell
docker-compose up
```

### Relevant log output

```shell
18:22:18.399 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 96b2e20c562d1de33179a7cd2701784f 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.82, chrome: {chromedriverVersion: 93.0.4577.63 (ff5c0da2ec0ad..., userDataDir: /tmp/.com.google.Chrome.KICKh3}, goog:chromeOptions: {debuggerAddress: localhost:44815}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.19.0.3:4444/sessio..., se:cdpVersion: 93.0.4577.82, se:forwardCdp: ws://172.19.0.4:4444/sessio..., se:vnc: ws://172.19.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.19.0.4:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
18:22:58.465 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 96b2e20c562d1de33179a7cd2701784f
18:22:58.465 INFO [GridModel.release] - Releasing slot for session id 96b2e20c562d1de33179a7cd2701784f
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.15.0-20231110

**Comment by VietND96** [comment]
It looks like similar this thread https://github.com/SeleniumHQ/docker-selenium/issues/1319, still don't have way to pass ENV through dynamic grid

**Comment by VietND96** [comment]
> It looks like similar this thread #1319, still don't have way to pass ENV through dynamic grid

I have misunderstood this, #1319 was done to implement all ENV start with `SE_` will pass through child containers.
With your compose file shared, it works at my end, however I am using docker engine on linux not docker desktop.
Can you try one thing, update version of compose file to `version: "3.8"`

**Comment by diemol** [comment]
This is happening because you are using old images in the `config.toml`.

```
[docker]
configs = [
    "selenium/standalone-chrome:100.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"100.0\"}",
    "selenium/standalone-chrome:93.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"93.0\"}"
]
```

The fix was released in June 2023, and the Chrome 100 and Chrome 93 images are older than that. Please use recent versions of the images.

**Comment by alxweis** [comment]
> This is happening because you are using old images in the `config.toml`.
> 
> ```
> [docker]
> configs = [
>     "selenium/standalone-chrome:100.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"100.0\"}",
>     "selenium/standalone-chrome:93.0", "{\"browserName\": \"chrome\", \"browserVersion\": \"93.0\"}"
> ]
> ```
> 
> The fix was released in June 2023, and the Chrome 100 and Chrome 93 images are older than that. Please use recent versions of the images.

Thanks, that worked for me!
