### ISSUE TITLE
[🐛 Bug]: Selenium tests failing on download

### ISSUE THREAD

**Issue by cjproud** [SeleniumHQ/docker-selenium#2032]
### What happened?

We have some tests that run on a self-hosted runner that uses the standalone-chrome container as a service. I've noticed that some of these tests now fail on `selenium/standalone-chrome:latest` but successfully ran on the `selenium/standalone-chrome:119.0` image. The specific tests were checking if a file download was successful.

### Command used to start Selenium Grid with Docker

```shell
jobs: 
  test-lint:
    name: Test
    runs-on: [self-hosted, integration_tests]
    container: 
      image: ubuntu:22.04
      options: --name test
      volumes:
        - tmp_volume:/tmp_volume
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      selenium_test:
        image: selenium/standalone-chrome
        ports: 
          - 4444:4444
          - 7900:7900
        env:
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080
        options: >-
          --shm-size 2gb
          --name selenium
        volumes:
          - tmp_volume:/tmp_volume
```

### Relevant log output

```shell
FAIL: test_export_results (design.tests.integrations_tests.test_results_page.ResultsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/<Folder1>/<App1>/<Folder2>/design/tests/integrations_tests/test_results_page.py", line 53, in test_export_results
    self.assertEquals(temp_files[0], "Test Simulation - Current.xlsx")
AssertionError: 'Test Simulation - Current.xlsx.crdownload' != 'Test Simulation - Current.xlsx'
- Test Simulation - Current.xlsx.crdownload
?                               -----------
+ Test Simulation - Current.xlsx
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.15.0-20231128

**Comment by diemol** [comment]
@vietnd96 we switched to Chrome for Testing, which might be the reason for this issue. Probably we need to revert https://github.com/SeleniumHQ/docker-selenium/commit/82603e902fcd7bb820cabd17540d9c7bf28682f9 and use the regular Chrome.

**Comment by VietND96** [comment]
Hello @cjproud, may I know in your test is adding these args or not?
```
options.addArguments("--incognito")
options.addArguments("disable-features=DownloadBubble,DownloadBubbleV2")
```
In these 2 images, there is Chrome version different also
`selenium/standalone-chrome:119.0` -> `119.0.6045.159`
`selenium/standalone-chrome:latest` -> `119.0.6045.105`

**Comment by VietND96** [comment]
Ok, let's ignore the args. Something that I am able to reproduce when the docker volume is set to mount `/home/seluser/Downloads`, if permission is improper, the download is not triggered.
In your case, it is able to download, but the file with extension `.crdownload` which means the download is still in progress or stuck somewhere.
I will continue check this, if there is no clue, commit switch to Chrome for Testing will be reverted
