### ISSUE TITLE
[🚀 Feature]: Ubuntu Based video Image

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2037]
### Feature and motivation

I noticed that recently we switched to Alpine based images for Video Recorder ffmpeg Images. While Alpine may be slightly lightweight but at the same time Ubuntu is more acceptable in Enterprise environments. It took Alpine years to address famous dns "issue" in musl libc lib. Overall ubuntu also has great track record on patching . I have seen tons of backporting in os or framework related patches.

I am not suggesting immediate switch back but I just want to discuss if we should stick to Ubuntu as all the Images are Ubuntu based.

### Usage example

Enterprise environments.

**Comment by VietND96** [comment]
Thank you for your suggestion. Actually, the switch to Alpine was done via my PR #1981, I think I can switch it back easily.
In this situation, probably a uniform platform is better than a image lightweight.

**Comment by amardeep2006** [comment]
@vietnd96  Please hold  and don't roll back immediately. We should hear from more people as well.

**Comment by diemol** [comment]
I think either works well. Probably easier to maintain Ubuntu.

**Comment by amardeep2006** [comment]
@vietnd96 I guess there a base ubuntu image for ffmpeg 6 from jrottenberg (Julien Rottenberg) as well. That will make sense for base since we are on ffmpeg 6 already.
