### ISSUE TITLE
[🚀 Feature]: We should stick to main chrome channel instead of CFT (Chrome for Testing)

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2041]
### Feature and motivation

I am sharing my thoughts that why we should stick to existing method of Chrome installation untill there is apt-get way to install CFT.

1. The business users use chrome so to keep it closest possible to real case scenarios. CFT may share the same source code but installation method differs so sharing my doubts.
2. CFT is supplied without OS dependency graph just a zip. No matter how hard we try, we cannot replicate apt-get . Apt not only takes care of chrome installations but also takes care of os package compatibility. 

We are already getting chrome driver from CFT endpoints which is tried tested and stable method.

We should stick with existing method for stability in my opinion untill Google provides an easy way ( e.g. ppa repo) for CFT and we are able to install via apt-get OR we have some solid reason to do so.
Please share your thoughts .

### Usage example

Stability of chrome.

**Comment by diemol** [comment]
We already moved back to the regular Chrome installation, and we will keep using it. One of the main use cases of CfT is to allow users to test with previous versions to verify regressions. Which they can also do by selecting the correct tag in our images.

**Comment by VietND96** [comment]
CfT was introduced via #2018 and very fast it was rolled back in #2033 due to the issue reported.
Of course, Chrome is installed via apt-get only in released image, however I am thinking that will reuse scripts to support user can build their own image with Chrom is downloaded from CfT, it only will be triggered via --build-arg
