### ISSUE TITLE
[🐛 Bug]: ImagePullBackOff using selenium-grid helm chart

### ISSUE THREAD

**Issue by xdoncalvox** [SeleniumHQ/docker-selenium#2057]
### What happened?

After upgrading my helm chart from 0.25.1 to 0.26.1, selenium-hub and browser-node's pod started to show ImagePullBackOff, looking into the deployment for each of them I found the image field for the pod template now shows `selenium/selenium/hub ` instead of `selenium/hub` (as previously) causing the mentioned error.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: selenium-grid
  namespace: qa1
spec:
  chart:
    spec:
      chart: selenium-grid
      version: "0.26.1"
      sourceRef:
        kind: HelmRepository
        name: docker-selenium
  interval: 1h0m0s
```

### Relevant log output

```shell
Failed to pull image "selenium/selenium/hub:4.16.1-20231208": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/selenium/selenium/hub:4.16.1-20231208": failed to resolve reference
```

### Operating System

kubernetes

### Docker Selenium version (tag or chart version)

0.26.1

**Comment by VietND96** [comment]
Hi @xdoncalvox, recently there was a breaking change in the image name via PR #2030. Please read https://github.com/SeleniumHQ/docker-selenium/issues/2039#issuecomment-1837414504, or https://github.com/SeleniumHQ/docker-selenium/issues/2035#issuecomment-1832486785 or README for more details.
Probably you are using an old YAML that was created before `0.25.3`

**Comment by xdoncalvox** [comment]
Thank you @vietnd96 for the reply. I have now readed the comments and the readme.
I would expect that if `imageRegistry` is not specified in the values.yaml the default value would be used. I did not specified anything under `global.seleniumGrid` and still got into this error. So having to add `imageRegistry` is strange.

**Comment by VietND96** [comment]
Ah yes, I guess your situation would be that you took the chart values.yaml and modified something there, then you provide it via `--values (-f)`
However, helm strategy would always take chart values.yaml to merge with your YAML given via `-f`.

chart/values.yaml (`0.25.3` onwards)
```yaml
global:
  seleniumGrid:
    imageRegistry: selenium # default global is enabled
```
your_values.yaml (previous version)
```yaml
chromeNode:
  imageName: selenium/node-chrome
```
When deploying the your old values on top of new chart version, merge strategy would render the image `selenium/selenium/hub:4.16.1-20231208`
```tpl
          {{- $imageTag := default .Values.global.seleniumGrid.imageTag .Values.hub.imageTag }}
          {{- $imageRegistry := default .Values.global.seleniumGrid.imageRegistry .Values.hub.imageRegistry }}
          image: {{ printf "%s/%s:%s" $imageRegistry .Values.hub.imageName $imageTag }}
```

**Comment by VietND96** [comment]
![image](https://github.com/SeleniumHQ/docker-selenium/assets/23253546/4be9b53d-935e-4f6b-ba89-b94f3ba0cd33)
Attach a visual for my comment above. Chart `values.yaml` is referring always when merging.
That is the reason for my comments
> try a practice that your custom YAML file should keep override values only, for remaining no different helm will refer to default chart values

**Comment by xdoncalvox** [comment]
Thank you for the quick reply
