### ISSUE TITLE
[🐛 Bug]:  The environment variable SE_VNC_PASSWORD contains sensitive data

### ISSUE THREAD

**Issue by mrbusche** [SeleniumHQ/docker-selenium#2060]
### What happened?

In https://github.com/SeleniumHQ/docker-selenium/pull/2056 an environment variable `SE_VNC_PASSWORD` was added which is flagged by security scanners. The first release with this commit is https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.16.1-20231212

If I create the image locally as is with `ENV SE_VNC_PASSWORD=secret` the secret is flagged. If I create with `ENV SE_VNC_PASSWORD=` then it is not flagged. Is it possible to set the variable without a default value?

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
This is an environment variable issue
```

### Relevant log output

```shell
This is an environment variable issue
```

### Operating System

all

### Docker Selenium version (tag or chart version)

4.16.1-20231212

**Comment by diemol** [comment]
It has been always hardcoded somewhere, before it was in the script, and now in the Dockerfile. Why is that different now?

**Comment by mrbusche** [comment]
> It has been always hardcoded somewhere, before it was in the script, and now in the Dockerfile. Why is that different now?

Now it's an explicit ENV variable being set, I don't believe that was the previous functionality based on the commit history I have looked at.

**Comment by VietND96** [comment]
Before it was
```Dockerfile
RUN mkdir -p ${HOME}/.vnc \
  && x11vnc -storepasswd secret ${HOME}/.vnc/passwd
```
I guess the scan tool evaluates it as ENV and contains PASSWORD or something.
Is it a blocker for running the container in your organization? or we can slowly fix in next deploy?

**Comment by mrbusche** [comment]
> Before it was
> 
> ```dockerfile
> RUN mkdir -p ${HOME}/.vnc \
>   && x11vnc -storepasswd secret ${HOME}/.vnc/passwd
> ```
> 
> I guess the scan tool evaluates it as ENV and contains PASSWORD or something. Is it a blocker for running the container in your organization? or we can slowly fix in next deploy?

We have "allowed" the specific image to run, so we're not at a hard stop. If you could fix for the next release that would be great.

**Comment by mcdanr3** [comment]
The scanner we use didn't pick up on the previous usage. It did flag it when you converted over to using ENV on Base/NodeBase.

**Comment by VietND96** [comment]
@mrbusche, may I know any vulnerability reported in Base image at line `ARG SEL_PASSWD=secret`?
Updated: after reading some best practices, I think the default value in ARG would not be a problem.
