### ISSUE TITLE
[🚀 Feature]: Make download owner-group adjustable in Standalone Containers

### ISSUE THREAD

**Issue by heikowulf** [SeleniumHQ/docker-selenium#2062]
### Feature and motivation

Hello,

the latest update to selenium standalone containers added the fix-permission file that set's the download directory ownergroup to root.
We used the usual workaround on linux and modified the ownergroup on our own so far, setting the directory owner to seluser, which we also added to a usergroup on our hostsystem, and left the owner-group of the directory on our custom one prior to launching the container.

Now, if we launch the container it resets the ownergroup to root, which causes some trouble for us to delete those directories after usage, because our application is not running with root-permissions.

It would be great if we could modify the usergroup the downloaddirectory is set on as environment variable.

### Usage example

just edit line 21 in fix-permissions `chgrp -R 0 "${d}"` so that it uses an ENV argument that we can set to a different value than 0 before launching the container.

**Comment by heikowulf** [comment]
Ah nevermind I think this is already customizable. I was just blind.

**Comment by VietND96** [comment]
Thank you for your writing, let me think if we can make this experience better via ENV

**Comment by VietND96** [comment]
`chgrp -R 0 "${d}"` is used to support arbitrary user ids https://docs.openshift.com/container-platform/4.14/openshift_images/create-images.html#use-uid_create-images

> Because the container user is always a member of the root group, the container user can read and write these files.

This does not effect the user `root` or `seluser` can create or update a folder that it's owner
