### ISSUE TITLE
[🐛 Bug]: Cant set Languages as multi item Array

### ISSUE THREAD

**Issue by D3M05** [SeleniumHQ/docker-selenium#2066]
### What happened?

Chrome in docker is launched with the ENV variable for language as the "navigator.language" and "navigator.language**s**", but there is no way to set multiple/alternative languages for the "navigator.language**S**" property. 

I have tried:
`Object.defineProperty(navigator, "languages", {
		get: function() {
			return ["en-US", "en"];
		}
});`

but languages always results in "languages": [ "en-US"]

This causes the browser to fail "inconsistentLanguages" on https://bot.incolumitas.com/ and it will not pass https://nowsecure.nl anymore.

If I manually go into the browser in noVNC and toggle the languages in Chrome's settings, it will then show "languages": [ "en-US", "en"] and pass all tests until the session closes.

Selenium should respect setting the languages through defineProperty, and I believe it did previously?

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run -d -p 4444:4444 -p 7900:7900 -e LANGUAGE=en_US,en -e LANG=en_US,en selenium/standalone-chrome:4.16
```

### Relevant log output

```shell
none
```

### Operating System

Ubuntu Linux 20.04.6

### Docker Selenium version (image tag)

4.16

**Comment by diemol** [comment]
Has this worked before or are you just trying to figure out how to change the browser's language?

**Comment by D3M05** [comment]
Hey diemol

I can change the browser's "language (string)" and "languages (array)" property to a single language, but I can not set multiple/fallback languages in the "languages (array)" property.  I can not confirm if or when this worked before, but I can see in the code for [puppeteer-exta](https://github.com/berstend/puppeteer-extra/blob/c44c8bb0224c6bba2554017bfb9d7a1d0119f92f/packages/puppeteer-extra-plugin-stealth/evasions/navigator.languages/index.js) that there was code designed to set it 3 years ago.  For my own code, I use a forked version, and oddly I had disabled it from setting "languages (array)", so I assume it must have done something or else I wouldn't have bothered disabling it.

I noticed earlier in the year "NodeChrome/wrap_chrome_binary" was changed to set Language, but perhaps this has nothing to do with it.  It's completely possible this could be a bug in Selenium, but I'm not familiar enough to say.  For whatever reason though, this is being flagged as a strong signal to identify selenium-chrome.

Thanks

**Comment by diemol** [comment]
Puppeteer talks to Chrome via DevTools, so it is not the same. 

I think if you need to set a fallback language you need to use the flag https://peter.sh/experiments/chromium-command-line-switches/#lang. It might be that the option only accepts one locale. 

While Googling, I found things like this one: https://sqa.stackexchange.com/a/32459, so you might need to find Chrome specific properties to set what you need.

In the end, these images are just wrapping the browser, and Selenium is only forwarding the information you provide.

I will close this as there is nothing for us to change, but I will leave a few links below in case you want to ask more questions.
