### ISSUE TITLE
[🚀 Feature]: Webkit Support

### ISSUE THREAD

**Issue by Tiberriver256** [SeleniumHQ/docker-selenium#2078]
### Feature and motivation

Testing Safari is quite a challenge. Running on the WebKit engine instead would be much simpler and likely good enough for the majority of cases.

### Safari

* Only runs on Apple hardware
* Requires special licensing
* Relies on Apple patching for versioning, making it hard to control

### WebKit

* Runs on Windows/Linux/MacOS (good docker candidate)
* No special licensing requirements
* Any version can be downloaded directly from the site

### Real-world examples

Playwright has had some success with this
https://playwright.dev/docs/browsers#webkit

### Usage example

Would love a Docker image to be used in Selenium Grid 👍👍

**Comment by amardeep2006** [comment]
Creating Docker image may not be difficult , jamesmortensen did it with epiphany/mini browser https://github.com/jamesmortensen/WebKitWebDriver-Browser-Images .
The bigger question is does selenium-server supports it?
Here is one older thread for it https://github.com/SeleniumHQ/selenium/issues/10178

**Comment by diemol** [comment]
Thanks @amardeep2006 for providing this context. As today, it stands the same. 

In addition, we aim to provide real browsers for general use cases, and Webkit is not a general use case. I know that having a Safari instance is not trivial, but if you are serious about testing, you should test in the same browser your user browses.
