### ISSUE TITLE
[🐛 Bug]: se:recordVideo not being used to determine if video should be recorded

### ISSUE THREAD

**Issue by eugenek5** [SeleniumHQ/docker-selenium#2086]
### What happened?

By documentation, it is stated that on setting se:recordVideo to true the grid should record a video, and inversely I understood that setting it to false should not record that session.  

In reality it does not seem that this flag is being checked.

> To record your WebDriver session, you need to add a se:recordVideo field set to true.

In the Video sidecar container the script /opt/bin/video.sh is constantly running and only checking if a session begins to start recording

```shell
while curl -s --request GET http://localhost:5555/status > /tmp/status.json
do
    session_id=$(jq -r '.[]?.node?.slots | .[0]?.session?.sessionId' /tmp/status.json)
    echo $session_id
    if [[ "$session_id" != "null" && "$session_id" != "" && "$recording_started" = "false" ]]
``` 

I believe there should be an additional query to the GraphQL endpoint to check browser compatibilities
```shell
curl -X POST -H "Content-Type: application/json" --data '{"query":"{ session (id: \"<session-id>\") { id, capabilities, startTime, uri, nodeId, nodeUri, sessionDurationMillis, slot { id, stereotype, lastStarted } } } "}' -s <LINK_TO_GRAPHQL_ENDPOINT>
``` 
parsing capabilities will reveal the requested tags including se:recordVideo
```
{
  "data": {
    "sessionsInfo": {
      "sessions": [
        {
          "id": "38047fee2791262004330c3131904a2f",
          "capabilities": "{\n  \"acceptInsecureCerts\": false,\n  \"browserName\": \"chrome\",\n  \"browserVersion\": \"120.0.6099.109\",\n  \"chrome\": {\n    \"chromedriverVersion\": \"120.0.6099.109 (34191
40ab665596f21b385ce136419fde0924272-refs\\u002fbranch-heads\\u002f6099@{#1483})\",\n    \"userDataDir\": \"\\u002ftmp\\u002f.org.chromium.Chromium.xqUtVT\"\n  },\n  \"fedcm:accounts\": true,\n  \"goog:chromeOp
tions\": {\n    \"debuggerAddress\": \"localhost:45553\"\n  },\n  \"networkConnectionEnabled\": false,\n  \"pageLoadStrategy\": \"normal\",\n  \"platformName\": \"linux\",\n  \"proxy\": {\n  },\n  \"se:bidiEna
bled\": false,\n  \"se:cdp\": \"wss:\\u002f\\u002fadmin:admin@testops.ceridian.com\\u002fgrid-qa\\u002fsession\\u002f38047fee2791262004330c3131904a2f\\u002fse\\u002fcdp\",\n  \"se:cdpVersion\": \"120.0.6099.10
9\",\n  \"se:recordVideo\": \"false\",\n  \"se:vnc\": \"wss:\\u002f\\u002fadmin:admin@testops.ceridian.com\\u002fgrid-qa\\u002fsession\\u002f38047fee2791262004330c3131904a2f\\u002fse\\u002fvnc\",\n  \"se:vncEn
abled\": true,\n  \"se:vncLocalAddress\": \"ws:\\u002f\\u002f10.254.36.194:7900\",\n  \"setWindowRect\": true,\n  \"strictFileInteractability\": false,\n  \"timeouts\": {\n    \"implicit\": 0,\n    \"pageLoad\
": 300000,\n    \"script\": 30000\n  },\n  \"unhandledPromptBehavior\": \"dismiss and notify\",\n  \"webauthn:extension:credBlob\": true,\n  \"webauthn:extension:largeBlob\": true,\n  \"webauthn:extension:minP
inLength\": true,\n  \"webauthn:extension:prf\": true,\n  \"webauthn:virtualAuthenticators\": true\n}",
          "startTime": "08\u002f01\u002f2024 05:37:45",
          "uri": "http:\u002f\u002f10.254.36.194:5555",
          "nodeId": "9172aba1-c457-4568-96d1-b6f4b04702e8",
          "sessionDurationMillis": "1189"
        }
      ]
    }
  }
```

In this example it shows "se:recordVideo":"false", which should be parsed and used as part of the video.sh logic to determine if we should start recording video or loop until the next session begins.  

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Stock helm chart with the following config:

isolateComponents: true
videoRecorder:
  enabled: true
autoscaling:
  enabled: true
  scalingType: deployment   # Bug would be relevant for both deployment and job strategies
```

### Relevant log output

```shell
n/a
```

### Operating System

Kubernetes

### Docker Selenium version (image tag)

4.16.1-20231219

### Selenium Grid chart version (chart version)

0.26.3

**Comment by diemol** [comment]
That capability is shown in the Dynamic Grid section, and does not apply to the Helm chart.

**Comment by eugenek5** [comment]
@diemol Would this be a feature request to bring the k8s version up to feature parity or is this not in the roadmap and we should build this ourselves?

**Comment by diemol** [comment]
The suggested solution is to use the Helm chart with Keda and video. Which should be explained in the docs.

That particular feature as it is won't be implemented for Kubernetes.

**Comment by eugenek5** [comment]
Understood.  That's how we are using the grid now, but we don't want to record and upload all videos, only a small subset of tests with a history of flakiness or failure.   

Should I open another ticket as a feature proposal or can this be re-tagged?

**Comment by VietND96** [comment]
I remember that on Slack there was a discussion similar this, listen on capabilities `se:recordVideo` to enable/disable video recorder container will be started with Node in K8s, instead of the current implement need to `--set videoRecorder.enabled=true` in Helm chart and it starts always
It would be a feature request. You can raise, have time I can take a look. If you already had the solution ready, you can raise the PR also

**Comment by diemol** [comment]
Probably something like that could be done. However, we do not want to add those features inside the Java code, because it makes it hard to maintain and probably it can be handled in a similar way as it is today.

**Comment by eugenek5** [comment]
I added a feature request, please let me know what you guys think about implementing it on the video.sh script or if there is a better way.

https://github.com/SeleniumHQ/docker-selenium/issues/2090
