### ISSUE TITLE
proxied browser

### ISSUE THREAD

**Issue by jcranky** [SeleniumHQ/docker-selenium#209]
Is there some trick to run a browser, like with standalone-firefox, using proxy? I tried setting the selenium proxy via the driver capabilities but is seems to be ignored. I also tried to set the _http_proxy_ env to the container with a _standalone_chrome_, also without success.

**Comment by mickfeech** [comment]
for what it's worth i created a wrapper of the firefox command exporting http_proxy, https_proxy, and no_proxy environment variables which seems to have worked.

**Comment by orieken** [comment]
it worked for me to launch the containers with 
```
-e http_proxy="<proxy setting>"
-e https_proxy="<proxy setting>"
-e no_proxy="<proxy setting>"
```

like 
```
docker run -d -P --name standalone-chrome -e GRID_TIMEOUT=10000 \
     -e no_proxy='localhost' \
     -e http_proxy='whatever-setting' \
     -e https_proxy='whatever-setting' \
     selenium/standalone-chrome
```
