### ISSUE TITLE
[🚀 Feature]: Allow child node containers provisioned in dynamic grid to copy resolv.conf from node-docker container

### ISSUE THREAD

**Issue by theswordsmahin** [SeleniumHQ/docker-selenium#2098]
### Feature and motivation

If I add 

```
    dns:
      - "x.x.x.xxx"
    dns_search: testdomain.com
```

in my docker-compose file, the node-docker container's resol.conf file is updated and the container is able to resolve names using machine shortnames, and FQDN's from the custom DNS server, but any containers that are dynamically created are using the standard resolv.conf file and thus are forced to use IP addresses. 

It would be great if the child containers could copy this file, or, an option was provided to allow further customization of the child containers that the node-docker container creates. 

### Usage example

Would allow usage of dynamic grid and the use of domain names on a custom DNS server, ie local intranet, rather than being forced to use IP addresses

**Comment by VietND96** [comment]
@diemol, I guess this has to be implemented on upstream, right?

**Comment by diemol** [comment]
Yes. It would be nice to have a generic way to add those things and not add them one by one.
