### ISSUE TITLE
Nodes will occasionally hang, seemingly forever

### ISSUE THREAD

**Issue by ericfrancis** [SeleniumHQ/docker-selenium#21]
Firefox-Node log (Missing the last 'Done:')
```
21:06:53.553 INFO - Executing: [get: http://172.17.42.1:8080/])
21:06:53.599 INFO - Done: [get: http://172.17.42.1:8080/]
21:06:53.613 INFO - Executing: [find element: By.selector: [node-name='account-body'] tr])
```

Selenium-Hub log
```
21:27:54.078 INFO - Got a request to create a new session: Capabilities [{platform=ANY, firefox_profile=UEsDBBQACAAIAHt7ikUAAAAAAAAAA..., javascriptEnabled=true, browserName=firefox, version=}]
21:27:54.078 INFO - Available nodes: [host :http://172.17.0.6:5555, host :http://172.17.0.4:5555, host :http://172.17.0.5:5555, host :http://172.17.0.3:5555]
21:27:54.078 INFO - Trying to create a new session on node host :http://172.17.0.6:5555
21:27:54.078 INFO - Trying to create a new session on test slot {platform=LINUX, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=1}
```

```
[ec2-user@ci ~]$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
selenium/node-firefox   2.44.0              8f4193404eb1        3 hours ago         558.2 MB
selenium/hub            2.44.0              4a9111e45347        3 hours ago         337.8 MB
```

**Comment by VolkerK** [comment]
I think the problem is that firefox and/or selenium and/or chrome uses _/dev/random_.
Inside docker containers this could be a problem, see this stackoverflow question [Not enough entropy to support /dev/random in docker containers](http://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d)

**Comment by ericfrancis** [comment]
Right on. My issue ended up being something that is most likely internal. I
was able to get the nodes to stop hanging by using my own config.json and
setting browser timeout to 45 seconds.

**Comment by mtscout6** [comment]
So, does this issue need to remain open for any reason?

**Comment by ericfrancis** [comment]
I vote no. With overriding config.json and the /dev/random solution, I
think we are good.

**Comment by kingkevin** [comment]
Mounting /dev/random only seems to work in boot2docker. On a debain installation I'm seeing this message when I try to mount /dev/urandom

```
cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/b41c7b07be67d286e558958a32d891b7f432d0c0e3268a778a05c9dd8cfa3d75/dev/random
```

**Comment by kingkevin** [comment]
Fixed this issue by updating docker-compose to 1.4 on the Debian install.

**Comment by gabriel-sagula-hs** [comment]
Thanks @VolkerK 

selenium docker stopped hanging with -v /dev/urandom:/dev/random

**Comment by cpanato** [comment]
I can use the container for tests once and when try to re-run the tests the hub looks like hangs

**Comment by doomsbuster** [comment]
I am trying to run a Firefox node on docker containers with `selenium-server-2.47.1` and `firefox-45.7.0` on RHEL 7. My tests run fine for 70% of the time. 30% of the time, the node gets hung up on trying to execute the `get` command and my test script times out.

I installed rng-tools to increase the entropy on the container without luck.

When i look up the Node Logs there arent any errors but it gets hung up on the `get` command

```
19:56:04.266 INFO - The node is registered to the hub and ready to use
19:56:12.890 INFO - Executing: [new session: Capabilities [{browserName=firefox, version=, platform=ANY}]])
19:56:12.898 INFO - Creating a new session for Capabilities [{browserName=firefox, version=, platform=ANY}]
19:56:14.719 INFO - Done: [new session: Capabilities [{browserName=firefox, version=, platform=ANY}]]
19:56:14.771 INFO - Executing: [get: http://myurl])
```
