### ISSUE TITLE
How to disable add on window for Firefox container.

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#210]
Hi,
![firefox docker](https://cloud.githubusercontent.com/assets/5100732/14734706/27243c9c-0864-11e6-9a9a-1d350ca6296d.png)

When i start my test and the browser is invoked, then for firefox an addon window is displayed.

How can we disable it?

**Comment by azakordonets** [comment]
I would love to find out how as well. So far, tried to provide next options to Firefox profile, but that didn't help 
```java
profile.setPreference("extensions.blocklist.enabled", false);
		profile.setPreference("app.update.enabled", false);
		profile.setPreference("browser.search.update", false);
		profile.setPreference("extensions.update.enabled", false);
		profile.setPreference("plugins.update.url", "");
		profile.setPreference("plugins.hide_infobar_for_outdated_plugin", true);
```

**Comment by dgangwar** [comment]
Try this code. It worked for me.

DesiredCapabilities cap = new DesiredCapabilities().firefox();
 FirefoxProfile profile = new ProfilesIni().getProfile("default");
 cap.setCapability(FirefoxDriver.PROFILE, profile)		         profile.setPreference("xpinstall.signatures.required", false);
