### ISSUE TITLE
[🚀 Feature]: Update objects name convention with prefix is Chart RELEASENAME

### ISSUE THREAD

**Issue by VietND96** [SeleniumHQ/docker-selenium#2109]
### Feature and motivation

Get motivation from #2107, by default the chart RELEASENAME will be appended to all objects name to make it unique.
`.name`, or `overrideName` will be retained for setting different names if any.

### Usage example

`helm upgrade -i prod1 [...] selenium-grid`
```bash
prod1-selenium-hub-64dff846b7-ccvb8               1/1     Running   0              2m3s
```

**Comment by Opvolger** [comment]
I can do that :)

**Comment by VietND96** [comment]
> I can do that :) 

Yes, welcome your contribution, since I have not started yet

**Comment by VietND96** [comment]
While doing this, can you consider something
- `_helpers.tpl` seems quite long now. Let's create a new tpl file, something like `_name.tpl` to centralize object names, naming helpers there.
- Synchronize config key `.nameOverride` to override the name in each object if any. If a different key used before, we correct it to the same

For any good practices that you are referring from other charts, feel free to add :)

**Comment by Opvolger** [comment]
Sorry, see your comments for now... Already made the change. But I can refactor it.

**Comment by VietND96** [comment]
@Opvolger, I have done and merged your PR to trunk. Kindly use chart `nightly` to preview and hands-on to see if it works as expected

**Comment by Opvolger** [comment]
Thnx will do

**Comment by Opvolger** [comment]
@VietND96 it works! Deployed from trunc (multiple times) without overriding names. and tests are still green :)
