### ISSUE TITLE
Docker selenium node are stopping immediately after start.

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#211]
Hi,

Selenium node(chrome & firefox) are immediately getting stopped after we start with the below error.

/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 34: get_server_num: command not found
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...

Docker Version:      1.11.0-rc5
Docker-machine version 0.5.0 (04cfa58)
Docker-compose version 1.5.2, build 7240ff3

**Comment by kayabendroth** [comment]
@dgangwar Which images are you using? The ones tagged with ```latest```? Can you post an image id?

**Comment by kayabendroth** [comment]
Likely a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/208.

**Comment by dgangwar** [comment]
On Latest version, node registration is working Fine.
