### ISSUE TITLE
[🐛 Bug]: WebDriverError: unknown error: net::ERR_NAME_NOT_RESOLVED when running docker image for selenium/standalone chrome

### ISSUE THREAD

**Issue by zshigri23** [SeleniumHQ/docker-selenium#2110]
### What happened?

When trying to run selenium test case on jenkins using selenium stand alone chrome image, i get this error 
WebDriverError: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=120.0.6099.224)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
      

I'm using node js and a windows machine with a linux agent in jenkins. 
I have specified the URL in code as well. 

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
command used: 
sh 'docker run -d -p 4444:4444 --shm-size="2g" -e PROXY_SETTINGS="${PROXY_SETTINGS}" selenium/standalone-chrome:4.17.0-20240123'

environment set up in pipeline script:
 environment {
        npm_config_cache='npm-cache'
        PROXY_SETTINGS = '''
            https_proxy=http://sub.proxy.company.com:1234
            HTTPS_PROXY=http://sub.proxy.company.com:1234
            '''
    }

Javascript code:
const loggingPrefs = new Preferences();
    loggingPrefs.setLevel(logging.Type.BROWSER, logging.Level.ALL);
    const options = new chrome.Options();
    options.setLoggingPrefs({ performance: 'ALL' });
    options.addArguments("--incognito");
    const caps = Capabilities.chrome();
    caps.setLoggingPrefs(loggingPrefs);
driver = new Builder().withCapabilities(Capabilities.chrome())
      .setChromeOptions(options.addArguments('--headless=new'))
      .usingServer('http://localhost:4444/wd/hub')
      .build();
    // setting values for prod and preprod urls
    const prodUrl = process.env.npm_package_config_prod;
    const preprodUrl = process.env.npm_package_config_preprod;
    //Now we check if uatURL is defined and uat is being passed in command line like --uat
    if (preprodUrl && process.argv.includes('--preprod')) {
      console.log("opening e-tst3 URL");
      await driver.get(preprodUrl);
    } else if (prodUrl && process.argv.includes('--prod')) {
      console.log("Trying the PROD version");
      await driver.get('https://www.google.com/');
    } else {
      console.log("None of the environments worked! :(");
    };

It throws the error at the 'driver.get'
I have tried to change the URL to without "www" still no luck.
```

### Relevant log output

```shell
WebDriverError: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=120.0.6099.224)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
```

### Operating System

windows 11 but linux agent on jenkins

### Docker Selenium version (image tag)

4.17

**Comment by diemol** [comment]
I do not think `PROXY_SETTINGS` is used by Docker. Has this worked before or are you trying to figure out how to set a proxy?

**Comment by zshigri23** [comment]
No its never worked, i was just trying out different ways to make it work. 
I saw one of your answers to a related post to set up proxy but not sure how. 
I've tried pass in as a command as listed on the docker documentation, but to no avail. For example
docker run --env HTTP_PROXY="http://proxy.example.com:3128" redis

Also to clarify, my command to run the docker is being used in the pipeline script.

**Comment by zshigri23** [comment]
I just tested it to change the URL to google.com(with no proxy) and it opened that but not able to open company website.
any idea how i can set the proxy?
below is without proxy
`stage('Run Selenium Container') {
            steps {
                script {
                    // Run Selenium container
                    sh 'docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.17.0-20240123'
                }
            }
        }`

**Comment by VietND96** [comment]
Can you try to configure the proxy at level Docker network? https://docs.docker.com/network/proxy/

**Comment by zshigri23** [comment]
are you talking about the ~/.docker/config.json set up?

**Comment by VietND96** [comment]
> are you talking about the ~/.docker/config.json set up?

Yes
Also, your error is similar to this one https://github.com/SeleniumHQ/docker-selenium/issues/1920

**Comment by VietND96** [comment]
> I'm using node js and a windows machine with a linux agent in jenkins

Also, are your test script and selenium container running on the same machine?
I guess it might not in the same machine, test script is checked out and executed in linux agent, and container run on windows machine.

> .usingServer('http://localhost:4444/wd/hub')

`localhost` in node js script might try to reach the service on the localhost within that machine

> docker run -d -p 4444:4444 --shm-size="2g" -e PROXY_SETTINGS="${PROXY_SETTINGS}" selenium/standalone-chrome:4.17.0-20240123

Try to add `--network=host` to docker command run to see any help

**Comment by filisko** [comment]
any? this is the very default way of initializing the tool in docker compose :| so it doesn't work by default

**Comment by VietND96** [comment]
I close this ticket since there is no input further
