### ISSUE TITLE
[🚀 Feature]: Support custom node types besides chrome/firefox/edge in helm chart

### ISSUE THREAD

**Issue by andrii-rymar** [SeleniumHQ/docker-selenium#2111]
### Feature and motivation

Currently Selenium Grid deployed with helm chart only supports 3 main web browsers to run the tests against. It would be great to have a custom node besides `chromeNode`/`firefoxNode`/`edgeNode` to run mobile tests or the tests against another browser supported by Selenium. 

### Usage example

Let's say I want to run the mobile tests against Android emulator and I have an image with the node (with relay configured), appium and the emulator itself. It would be nice to have a separate `customNode` where I can specify this image and something like `browserName: android` to spin off these nodes when this type is requested by the tests.

**Comment by amardeep2006** [comment]
hi @andrii-rymar do you have a Docker Image ready that has selenium node + relay + appium + android emulator built in?
Want to check before someone attempts to build the image.

**Comment by andrii-rymar** [comment]
Sorry @amardeep2006 I cannot share it because of NDA. I guess any image with Selenium Server in Node mode will work for this ticket.

**Comment by amardeep2006** [comment]
@andrii-rymar I asked as wanted to avoid duplicate work in case you have image ready and source code is public.
Do you have everything bundled up in single image or separate image for relay node and appium server? 
i feel for kubernetes we may have to bundle up relay node and appium in single image . 
It may be a fun side project something like https://github.com/budtmo/docker-android

**Comment by andrii-rymar** [comment]
@amardeep2006 I've combined everything into a single image: selenium node, appium server and android emulator. The only thing that didn't work out was the video in selenium grid UI as selenium server doesn't seem to support it in relay mode.
