### ISSUE TITLE
[🐛 Bug]: Selenium Grid 4 does not remove orphaned sessions immediately. 

### ISSUE THREAD

**Issue by kherath17** [SeleniumHQ/docker-selenium#2112]
### What happened?

**Background:**   
I have configured a setup for Selenium Grid in Kubernetes with all relevant services which has the capability to understand incoming requests and create browser pods on demand and also to bring down the browsers after test execution through a Custom Scaler built.

**Issue**:  
When a test execution is happened and when the browser POD is removed the removed Session is still available when hit the below curl command because of this , when another test execution is started **immediately** it gets pointed to the already removed session and runs into **_Connection Exception_**

`cURL GET 'http://something.net/something/status'`

**Sample output** 

{
        "id": "09c97f7c-ba9a-4ee5-ab64-2cfbda510595",
        "uri": "http:\u002f\u002f10.133.13.58:5555",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "5.10.198-187.748.amzn2.x86_64"
        },
        "heartbeatPeriod": 60000,
        "availability": "DOWN",
        "version": "4.17.0 (revision e52b1be057*)",
        "slots": [
          {
            "id": {
              "hostId": "09c97f7c-ba9a-4ee5-ab64-2cfbda510595",
              "id": "fa07a6f6-bbf5-4a64-8c17-c470809fc078"
            },
            "lastStarted": "1970-01-01T00:00:00Z",
            "session": null,
            "stereotype": {
              "browserName": "chrome",
              "browserVersion": "120.0",
              "goog:chromeOptions": {
                "binary": "\u002fusr\u002fbin\u002fgoogle-chrome"
              },
              "platformName": "linux",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      }
    ]
  }
}

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
I start the Selenium Grid Hub through below Deployment file 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        #image: selenium/hub:4.13.0-20231004 #4.1,4.13
        image: selenium/hub:latest
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
          requests:
            memory: "4000Mi"
            cpu: "2"  
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:          
          - name: SE_SUB_PATH 
            value: /something
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: "900"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "900"
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. java.net.http.HttpConnectTimeoutException: HTTP connect timed out
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.198-187.748.amzn2.x86_64', java.version: '11.0.21'
Driver info: driver.version: unknown 
Host info: host: 'selenium-hub-6f8c9bb8b9-zvvrd', ip: '10.133.13.169'
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.16.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless], extensions: []}}}]
Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless], extensions: []}}
```

### Operating System

Kubernetes - EKS

### Docker Selenium version (image tag)

4.17.0

**Comment by VietND96** [comment]
At Node deployment, is there a lifecycle exec preStop? The idea is before the pod is terminated, it will send Node drain command for graceful node shutdown, and it will be detached from hub.
For example in a race condition, before node drain command come to hub, Node is assigned to take another session, the preStop also wait for that session completed and node is drained. At that time pod also keep the status Terminating, instead of terminated immediately.
A script of preStop in chart https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/configs/node/nodePreStop.sh

**Comment by kherath17** [comment]
@vietnd96  

Nodes are spawned up by a Custom Scaler built using Python, where the pod template as below is defined, and this custom scaler is up and running 24/7 365 which continuously monitor the incoming requests to the hub and create PODs as needed.

On the preStop script provided it throws ` "Unable to find handler for (POST) \u002fse\u002fgrid\u002fnode\u002fdrain"`, when POST request is initiated but `${SE_NODE_PORT}/status` is returned correctly, what might be the issue? BTW by calling `node/drain` how can it identify which specific node are we referring to when there are multiple nodes? 

As of now what Im doing is calling this end point manually with respective session ID to remove them , but this not practical when there are too much sessions

`cURL --request DELETE 'https://something/testPath/se/grid/distributor/node/<replacing Session ID>' --header 'X-REGISTRATION-SECRET;'`

**POD defined within:**

pod_template = {
        "apiVersion": "v1",
        "kind": "Pod",
        "metadata": {
            "name": pod_name,
            "labels": {
                "name": pod_name,
                "app": "selenium-node-chrome"
            }
        },
        "spec": {
            "volumes": [
                {
                    "name": "dshm",
                    "emptyDir": {
                        "medium": "Memory"
                    }
                }
            ],
            "containers": [
                {
                    "name": "selenium-node-chrome",
                    "image": "selenium/node-chrome:latest",
                    "imagePullPolicy": "IfNotPresent", #Newly Added
                    "ports": [
                        {
                            "containerPort": 5555
                        }
                    ],
                    "volumeMounts": [
                        {
                            "mountPath": "/dev/shm",
                            "name": "dshm"
                        }
                    ],
                    "env": [
                        {
                            "name": "SE_EVENT_BUS_HOST",
                            "value": "selenium-hub"
                        },
                        {
                            "name": "SE_EVENT_BUS_SUBSCRIBE_PORT",
                            "value": "4443"
                        },
                        {
                            "name": "SE_EVENT_BUS_PUBLISH_PORT",
                            "value": "4442"
                        },
                        {
                            "name": "SE_NODE_MAX_SESSIONS",
                            "value": "1"
                        }
                    ],
                    "resources": {
                        "requests": { #Newly Added
                            "memory": "1000Mi",
                            "cpu": ".1"  
                        },                        
                        "limits": {
                            "memory": "1000Mi",
                            "cpu": ".2" #.5
                        }
                    }
                }
            ]
        }
    }

**Comment by diemol** [comment]
>When a test execution is happened and when the browser POD is removed the removed Session is still available when hit the below curl command because of this , when another test execution is started immediately it gets pointed to the already removed session and runs into Connection Exception

> when the browser POD is removed

How is this removed? How are you stopping the session?

>when another test execution is started immediately it gets pointed to the already removed session and runs into Connection Exception

Grid does not reuse sessions, so this is something you need to debug in your test code.

**Comment by kherath17** [comment]
@diemol 

1. How is this removed? How are you stopping the session?

As mentioned above I have a custom scaler written that runs on K8 which continuosly monitor the browser pods for specific log values and when matched the PODs are brought down , irrespective of the Custom scaler even if I manually delete the browser POD its is still shown when below curl command is hit 


`cURL GET 'http://something.net/something/status'`

_Response is attached on top_


2. Grid does not reuse sessions, so this is something you need to debug in your test code.

My code is only responsible for creating and deleting a browser POD, but in this case it's a different issue which seems to be that Session Infor are not removed from the hub backend but gets removed from the Grid UI

And also noted that after 2-3 mins of inactivity the sessions info are cleared out

**Comment by diemol** [comment]
>As mentioned above I have a custom scaler written that runs on K8 which continuosly monitor the browser pods for specific log values and when matched the PODs are brought down , irrespective of the Custom scaler even if I manually delete the browser POD its is still shown when below curl command is hit

When you do this, Grid cannot know the session was stopped. You are removing the POD and then the Grid Distributor cannot know the session is not there anymore. You would need to stop the session correctly by sending a DELETE to the session endpoint, and then remove the POD.

**Comment by VietND96** [comment]
> On the preStop script provided it throws  "Unable to find handler for (POST) \u002fse\u002fgrid\u002fnode\u002fdrain", when POST request is initiated but ${SE_NODE_PORT}/status is returned correctly, what might be the issue? BTW by calling node/drain how can it identify which specific node are we referring to when there are multiple nodes?

This preStop will be executed in Node pod only, it is not executed in the Hub/Router
Whenever Node pod is deleted/scaled down, preStop hooks executed `${SE_SERVER_PROTOCOL}://127.0.0.1:${SE_NODE_PORT}/se/grid/node/drain`
then Node /status will have `"node": { "availability": "DRAINING",...` until the last session is completed, Node pod terminated gracefully, and on Grid UI node also is disappeared immediately
Noted that `SE_SERVER_PROTOCOL` is an extra ENV defined in chart, not standard ENV with default value, so replace `http` if it not present in your Node container

**Comment by kherath17** [comment]
@vietnd96 

I've set it up as you've mentioned the node POD gets deleted but still the issue is same and availability doesn't change to DRAINING as well.

lifecycle:
          preStop:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - |
                  if [ ! -z "${SE_REGISTRATION_SECRET}" ]; then
                    HEADERS="X-REGISTRATION-SECRET: ${SE_REGISTRATION_SECRET}"
                  else
                    HEADERS="X-REGISTRATION-SECRET;"
                  fi
                  if curl -sfk http://myGrid/testPath/status; then
                    curl -k -X POST http://myGrid/testPath/se/grid/node/drain --header "${HEADERS}"
                  while curl -sfk http://myGrid/testPath/status; do sleep 1; done
                  else
                    echo "Node is already drained. Shutting down gracefully!"
                  fi

**Comment by kherath17** [comment]
> > As mentioned above I have a custom scaler written that runs on K8 which continuosly monitor the browser pods for specific log values and when matched the PODs are brought down , irrespective of the Custom scaler even if I manually delete the browser POD its is still shown when below curl command is hit
> 
> When you do this, Grid cannot know the session was stopped. You are removing the POD and then the Grid Distributor cannot know the session is not there anymore. You would need to stop the session correctly by sending a DELETE to the session endpoint, and then remove the POD.

Thanks for shedding some light on this area , Checking on this

**Comment by VietND96** [comment]
I guess the URL should not this `http://mygrid/testPath/se/grid/node/drain` ... `http://mygrid/testPath` is the Hub endpoint, it is not the Node endpoint.
Keep it as `http://127.0.0.1:${SE_NODE_PORT}/se/grid/node/drain` or `http://localhost:${SE_NODE_PORT}/se/grid/node/drain` only

**Comment by kherath17** [comment]
@vietnd96 tried seems it clearing out the nodes in some instances only (rare), but in most attempts the behavior is still the same

**Changed as below**


        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - |
                  if [ ! -z "${SE_REGISTRATION_SECRET}" ]; then
                    HEADERS="X-REGISTRATION-SECRET: ${SE_REGISTRATION_SECRET}"
                  else
                    HEADERS="X-REGISTRATION-SECRET;"
                  fi
                  if curl -sfk http://127.0.0.1:${SE_NODE_PORT}/status; then
                    curl -k -X POST http://127.0.0.1:${SE_NODE_PORT}/se/grid/node/drain --header "${HEADERS}"
                  while curl -sfk http://127.0.0.1:${SE_NODE_PORT}/status; do sleep 1; done
                  else
                    echo "Node is already drained. Shutting down gracefully!"
                  fi

**_After Triggering : kubectl delete pod_**

![image](https://github.com/SeleniumHQ/docker-selenium/assets/54758666/2bc8371b-1be8-4646-adbe-e1cf1b4ece74)

**Comment by VietND96** [comment]
@kherath17 , ok let me check how it is different. Here is my result when executing the preStop script, while looping until the node drained, container also stopped

![image](https://github.com/SeleniumHQ/docker-selenium/assets/23253546/b9efce96-4fde-4732-997a-cdaa2dcf462c)

**Comment by kherath17** [comment]
@vietnd96  btw do you think preStop endpoints should be pointed to the `hub-service` created rather than calling localhost directly?

![image](https://github.com/SeleniumHQ/docker-selenium/assets/54758666/617a39e5-ea91-4e89-bed4-40ced6a6c8d4)

**Comment by VietND96** [comment]
> @vietnd96 btw do you think preStop endpoints should be pointed to the `hub-service` created rather than calling localhost directly?

As documentation https://www.selenium.dev/documentation/grid/advanced_features/endpoints/#node - the endpoint `/se/grid/node/drain` belongs to Node. So the preStop of Node pod using localhost is fine, since the request internally in Node pod to the container.

**Comment by kherath17** [comment]
> @kherath17 , ok let me check how it is different. Here is my result when executing the preStop script, while looping until the node drained, container also stopped
> 

@vietnd96 were you able to find any more insights on this?

**Comment by kherath17** [comment]
> At Node deployment, is there a lifecycle exec preStop? The idea is before the pod is terminated, it will send Node drain command for graceful node shutdown, and it will be detached from hub. For example in a race condition, before node drain command come to hub, Node is assigned to take another session, the preStop also wait for that session completed and node is drained. At that time pod also keep the status Terminating, instead of terminated immediately. A script of preStop in chart https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/configs/node/nodePreStop.sh

@vietnd96 the issue is resolved with the above approach, my bad I was pointing to the grid port rather than node port, thank you for your prompt response and support!

**Comment by VietND96** [comment]
@kherath17, that's great to hear it can help!
Also regarding the `Custom Scaler built using Python`, is it built on top of KEDA or other open-source Scalers? Since I want to know how the current helm chart can integrate/extend with other scalers to have a unified K8s deployment rather than user creating different YAML

**Comment by kherath17** [comment]
@vietnd96 its actually an in-house built solution with python, capable of scaling up according to user requirements and also scaling down once test execution completes and also removing un-used browser PODs, we have currently dockerized the solution and deploy to K8 via Deployments.

This is been further improved continuously, and we haven't integrated helm chats yet.

**Comment by kherath17** [comment]
Hi @vietnd96 the mentioned fix was working for couple of days and now suddenly the nodes are getting drained as soon as it is created , hence running into `Gateway timeout`
