### ISSUE TITLE
[🐛 Bug]: x11vnc delayed

### ISSUE THREAD

**Issue by 0xC4N1** [SeleniumHQ/docker-selenium#2118]
### What happened?

[xdpyinfo](https://github.com/0xC4N1/docker-selenium/blob/b9c8494d21d32a550d2dd969f09e94b33f5ff5d1/NodeBase/start-vnc.sh#L40) and [fbsetbg](https://github.com/SeleniumHQ/docker-selenium/blob/b9c8494d21d32a550d2dd969f09e94b33f5ff5d1/NodeBase/start-vnc.sh#L12) are missing since packages are installed with `--no-install-recommends` (see #2061) causing x11vnc to be delayed.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run selenium/standalone-firefox:4.17.0-20240123
```

### Relevant log output

```shell
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Centering wallpaper
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Waiting for Xvfb...
Trying to update the open file descriptor limit from 1048576 to 100000.
Successfully update the open file descriptor limit
```

### Operating System

Ubuntu 22.04

### Docker Selenium version (image tag)

4.17.0-20240123

**Comment by VietND96** [comment]
Yes, `--no-install-recommends` was added following the Trivy scanned `Vulnerability DS029\nSeverity: HIGH\nMessage: '--no-install-recommends' flag is missed: ""\nLink: [DS029](https://avd.aquasec.com/misconfig/ds029)`
Instead of installing recommends, can we define transparent which package needed in Dockerfile?

**Comment by VietND96** [comment]
Ok, I saw your PR has added those 2 packages correctly.
