### ISSUE TITLE
[🐛 Bug]: 504 Gateway timeout when tests executed immediately after another

### ISSUE THREAD

**Issue by kherath17** [SeleniumHQ/docker-selenium#2132]
### What happened?

**Background:**
I have configured a setup for Selenium Grid in Kubernetes with all relevant services which has the capability to understand incoming requests and create browser pods on demand and also to bring down the browsers after test execution through a Custom Scaler built.

**Issue:**
When a test first starts and reaches the quitDriver Method it will bring down the respective browser pod (with node draining), and when another browser is initiated soon after that the previous run, it runs into 504 gateway timeout.

_Note - Pefectly working fine when a `Thread.Sleep(5000);` is used to hold the script just before initializing the second browser request._

**Ingress File:**

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qlabv2-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360" 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: selenium-hub
                port:
                  number: 4444
            path: /sandbox_qlabv2(/|$)(.*)
            pathType: ImplementationSpecific
               

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
I start the Selenium Grid Hub through below Deployment file 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        #image: selenium/hub:4.13.0-20231004 #4.1,4.13
        image: selenium/hub:latest
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
          requests:
            memory: "4000Mi"
            cpu: "2"  
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:          
          - name: SE_SUB_PATH 
            value: /something
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: "900"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "900"
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

### Operating System

Kubernetes - EKS

### Docker Selenium version (image tag)

4.17.0

**Comment by diemol** [comment]
That timeout comes from a layer above the Grid, probably that ingress.

**Comment by VietND96** [comment]
```yaml
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: "900"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "900"
```
I think the retry interval should not be equal to the timeout
The timeout is 900, so proxy timeout at ingress should be at least 900 instead of 360

**Comment by kherath17** [comment]
@VietND96 I increased it upto 3600 as below but same behaviour

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qlabv2-ingress
  annotations:
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: selenium-hub
                port:
                  number: 4444
            path: /sandbox_qlabv2(/|$)(.*)
            pathType: ImplementationSpecific

**Comment by VietND96** [comment]
Yes, how about the situation that caused this error? Is that something like there were a few sessions in progress and a few sessions waiting in the queue? Immediately a batch of queue sessions throw this error or just randomly some of the sessions? How long does a session wait in queue before it raises this error?

**Comment by kherath17** [comment]
@VietND96  I recently noticed that the second request reaches the grid but gets terminated instantly , it happens very fast I do not have time to even see the logs , not sure whats causing such behaviour , but when some` Thread.Sleep `is provided work without any issue

**Comment by VietND96** [comment]
Can you try to have these annotations in ingress configs to see how it behaves?
```yaml
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
```
