### ISSUE TITLE
[🐛 Bug]: Can't deploy default browsers

### ISSUE THREAD

**Issue by Doofus100500** [SeleniumHQ/docker-selenium#2144]
### What happened?

I'm trying to update the chart version to 0.28.1, but I'm getting errors when deploying standard browsers. I also tried to do a clean installation. However, if I disable the Firefox deployment, errors start to occur with Edge and so on.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm
```

### Relevant log output

```shell
Release "selenium-grid" does not exist. Installing it now.
Error: template: selenium-grid/templates/firefox-node-deployment.yaml:29:4: executing "selenium-grid/templates/firefox-node-deployment.yaml" at <include "seleniumGrid.podTemplate" $podScope>: error calling include: template: selenium-grid/templates/_helpers.tpl:395:23: executing "seleniumGrid.podTemplate" at <tpl (default (include "seleniumGrid.common.secrets.fullname" $) .Values.uploaderConfigMap.secretVolumeMountName) $>: error calling tpl: error during tpl function execution for "{{ include \"seleniumGrid.common.secrets\" $ }}": template: selenium-grid/templates/firefox-node-deployment.yaml:1:3: executing "selenium-grid/templates/firefox-node-deployment.yaml" at <include "seleniumGrid.common.secrets" $>: error calling include: template: no template "seleniumGrid.common.secrets" associated with template "gotpl"
```

### Operating System

k8s

### Docker Selenium version (image tag)

4.18.0-20240220

### Selenium Grid chart version (chart version)

0.28.1

**Comment by VietND96** [comment]
May I know which value input for key `uploaderConfigMap.secretVolumeMountName` via --set or YAML?
In chart `0.28.1` by default it is empty and render internally.

**Comment by VietND96** [comment]
`no template "seleniumGrid.common.secrets"` since this template has already been renamed.
I am aware that `values.yaml` should not contain `tpl` syntax e.g `include` template, `.Values.` hence it is already removed.
If you are deploying the new chart with the YAML modification on top of the old chart values, please correct it

**Comment by Doofus100500** [comment]
Thank you! Got it, I'll go tidy up the values.yaml file.

**Comment by Doofus100500** [comment]
Now I'm getting this error: "Error: YAML parse error on selenium-grid/templates/chrome-node-deployment.yaml: error converting YAML to JSON: yaml: line 127: found character that cannot start any token"

**Comment by VietND96** [comment]
It seems difficult to guess. Can you try a dry run with `helm template --debug [args] > output.yaml`

**Comment by Doofus100500** [comment]
Many thanks! I managed to figure it out using helm template --debug. The issue was with the uploader:
```
        - name: uploader
          image: %!s(<nil>)/uploader:%!s(<nil>)
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
```

**Comment by VietND96** [comment]
Yes, now RCLONE binary is installed in video recorder image, so no need the third sidecar container if someone prefers to use RCLONE. In chart, config key to pass --set-file is renamed to `upload.conf`
I believe it would reduce workload, and resource consumption in a Node pod.
Hopefully, it is still working correctly!
