### ISSUE TITLE
[🐛 Bug]:  Selenium grid noVnc gives error as "SyntaxError: Identifier 'originalPrompt' has already been declared"

### ISSUE THREAD

**Issue by nilanjan-mandal03** [SeleniumHQ/docker-selenium#2145]
### What happened?

I have started the selenium grid docker composer and expose the port 7900. 

![image](https://github.com/SeleniumHQ/docker-selenium/assets/153057572/1d54c674-965a-40c2-8c34-fbbe4fa5bd64)

Then after opening the noVnc i am getting an error.

![image](https://github.com/SeleniumHQ/docker-selenium/assets/153057572/26b792fa-3482-417f-9510-27109f14a304)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Below is the code in my docker composer file:

version: "3"
services:
  edge:
    image: selenium/node-edge:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_SESSION_TIMEOUT=60
    ports:
      - "7902:7900"
 
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

------------x---------------x-------------------
Command to start the docker composer:

docker-compose -f docker-compose.yml up

------------x---------------x-------------------
Open below url in any browser:

http://localhost:7902/?autoconnect=1&resize=scale&password=secret

------------x---------------x-------------------
```

### Relevant log output

```shell
Error:

noVNC encountered an error:
Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js:1:1
SyntaxError: Identifier 'originalPrompt' has already been declared
```

### Operating System

windows 11

### Docker Selenium version (image tag)

4.18.0-20240220

**Comment by VietND96** [comment]
Hi, is there any extension is enabled? Or is this test executed on Selenium IDE?

**Comment by nilanjan-mandal03** [comment]
yes i have selenium ide extension installed in my local on disabling it the error is removed, but not sure how come selenium ide creating this issue with novnc of selenium grid.

**Comment by VietND96** [comment]
Yes, years ago this issue was discussed https://github.com/SeleniumHQ/selenium-ide/issues/326 but looks like there is no solution.
Just a workaround found "deactivating Selenium IDE while not using the add-on"

**Comment by VietND96** [comment]
As the last comment, IDE v4 is delivered as a standalone binary, so I think you can remove the extension and switch to use .exe binary. You can find it here https://github.com/SeleniumHQ/selenium-ide/releases
I will close the ticket
