### ISSUE TITLE
[🐛 Bug]: selenium/video no longer writing videos to the /video directory as of ffmpeg-6.1-20240220

### ISSUE THREAD

**Issue by tscamell** [SeleniumHQ/docker-selenium#2146]
### What happened?

We run nightly regression tests and utilitse the selenium/video container to record videos. These are automatically uploaded to blob storage if the tests fail.

Our nightly run on 20th Feb (01:00 UTC) was successfully uploading videos.
Our nightly run on 21st Feb (01:00 UTC) was failing to see any videos to upload.

I noticed a new release has come out (ffmpeg-6.1-20240220). I'm not 100% sure, but I think the problem **may** be related to this change?
https://github.com/SeleniumHQ/docker-selenium/pull/2122/commits/5d8c1c0610f4644a2c319c4e83de5ff6cbc03861

The workaround I'm using is to simply tag to the previous release (ffmpeg-6.1-20240123), and videos are now viewable again and are successfully being uploaded.

Temporary workaround (tagging to sepecific version)
`  
chrome_screen_recorder:
    image: selenium/video:ffmpeg-6.1-20240123
    shm_size: 2gb
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=${RELEASE_ID}-${TEST_CATEGORY}-${RUN_LOCATION}-chrome.mp4
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    volumes:
      - ./Videos/:/videos
      - `

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker-compose run automation



chrome_screen_recorder:
    image: selenium/video
    shm_size: 2gb
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=${RELEASE_ID}-${TEST_CATEGORY}-${RUN_LOCATION}-chrome.mp4
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    volumes:
      - ./Videos/:/videos
```

### Relevant log output

```shell
None I'm afraid, other than seeing an empty directory :D
```

### Operating System

Ubuntu

### Docker Selenium version (image tag)

4.18.0

**Comment by VietND96** [comment]
I added a note in README after non-root change in video image - https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#mounting-volumes-to-retrieve-video-files
Can you try something like
```bash
mkdir -p ./Videos
sudo chown 1200:1201 ./Videos
docker compose up -d
```

**Comment by tscamell** [comment]
Thank you @VietND96 , I can confirm that changing ownership to 1200 does work with the latest build.

Many thanks for your help
