### ISSUE TITLE
[🐛 Bug]: Wrong naming of the pods

### ISSUE THREAD

**Issue by piotrlaczykowski** [SeleniumHQ/docker-selenium#2147]
### What happened?

After release of version 0.28.1 there is a problem with pods naming
![image](https://github.com/SeleniumHQ/docker-selenium/assets/108880904/5936f62d-3ce1-495e-a116-0a75254cb4fa)
in last release it was for example selenium-router

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm upgrade -i selenium-grid docker-selenium/selenium-grid -n cicd -f values-job.yaml
```

### Relevant log output

```shell
.
```

### Operating System

kubernetes

### Docker Selenium version (image tag)

4.18.0-20240220

### Selenium Grid chart version (chart version)

0.28.1

**Comment by VietND96** [comment]
From version `0.28.x`, the release name would be set as the prefix in all components name
With this new naming convention, how does it impact your deployment?

**Comment by VietND96** [comment]
If you feel the naming is too long, or not pretty. I am able to give an option that allows users to disable the prefix RELEASE-NAME (as before versions)

**Comment by piotrlaczykowski** [comment]
If it is possible, please. It destroyed my ingress routes and internal connectivity to selenium

**Comment by VietND96** [comment]
Yes, the fix is ready, if you deploy chart with the release name `selenium` only, object naming will be same as before.
I need to check something else for release, so the patch `0.28.2` will be out soon.
