### ISSUE TITLE
[🐛 Bug]: Problem with event bus naming

### ISSUE THREAD

**Issue by piotrlaczykowski** [SeleniumHQ/docker-selenium#2148]
### What happened?

I asked for changing a naming of pods and it happend but there is a bug releated to event bus:
![image](https://github.com/SeleniumHQ/docker-selenium/assets/108880904/f86b1365-345d-4e6c-a527-9954a210894b)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm upgrade -i selenium docker-selenium/selenium-grid -n cicd -f values-job.yaml
```

### Relevant log output

```shell
.
```

### Operating System

kubernetes

### Docker Selenium version (image tag)

4.18.1-20240224

### Selenium Grid chart version (chart version)

0.28.2

**Comment by VietND96** [comment]
I have updated and added template test to verify it. Chart '0.28.3' is out
