### ISSUE TITLE
[🐛 Bug]: grid url in node-chrome logs contains credentials

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2157]
### What happened?

Grid is deployed on kubernetes.
I was looking at node-chrome logs and I see that at least 4 times per pod life cycle it prints grid-url in logs.
Issue : If your grid is protected by basic auth then it leaks credentials in logs. This is a potential security issue.

![image](https://github.com/SeleniumHQ/docker-selenium/assets/50517840/ed20d808-cdba-468e-9f29-9e69b74bc2f6)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Helm chart 0.28.1
```

### Relevant log output

```shell
Pls see Attached screen shot
```

### Operating System

Kubernetes

### Docker Selenium version (image tag)

4.18.1

### Selenium Grid chart version (chart version)

0.28.1

**Comment by amardeep2006** [comment]
I can send a PR if we just need to delete the lines generating logs from shell script.

**Comment by VietND96** [comment]
The logs belong to the startup probe, in another fix I already refactored it.
Also, another setting added to allow enable/disable stdout of probes or preStop scripts `global.seleniumGrid.stdoutProbeLog`

**Comment by amardeep2006** [comment]
I can not appreciate your work enough. Blazing fast !!!!
I have seen very few engineers like you !!! Awesome work @VietND96
