### ISSUE TITLE
connecting through VNC documentation issue

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#216]
For first time user who is reading the documentation related to VNC connection there are few confusing points , please review and enhance
1. vnc://<boot2docker-ip>:49160 instead of hard coding  49160 , it should be mentioned as <port4VNC> value
2. <port4VNC>:5900 this is not clear as one point it says "...5900 is fine if it is free, but.."
   but it also mentions
   $ docker run -d -P -p 5900:5900 --link selenium-hub:hub selenium/node-chrome-debug:2.53.0
   $ docker run -d -P -p 5901:5900 --link selenium-hub:hub selenium/node-firefox-debug:2.53.0

this part needs more info to understand for new comers.

thanks & regards,
Vikram

**Comment by zypherman** [comment]
I am not sure that your second point really needs clarification. If you understand what the port flag means then it should be clear what the documentation is saying. All it's saying is that the vnc service is running on 5900 on the node but externally you can map it to whichever port you please.

**Comment by thataustin** [comment]
On this topic, is the `--link` part necessary to get the VNC server running correctly?

**Comment by vikramvi** [comment]
@thataustin Thanks for asking this query.

This proves that documentation is not clear enough for all the audiences. IMO any technical documentation should be written in as simple english as possible without "assuming" all are experts in networking and/or selenium usage. cc: @zypherman

**Comment by ddavison** [comment]
if there is an improvement you can make to the documentation - please! submit a pr! :)

**Comment by zypherman** [comment]
@thataustin The --link flag is to enable the hub and node to talk to each other correctly when they are both running on the same machine. It links the containers together to establish that communication. For the VNC part its not really directly related since you can have a standalone node running and connect to the VNC through that.

**Comment by diemol** [comment]
Closing this issue as since the doubts were solved by the community. If something is missing from the documentation, please send us a PR and become a contributor :)
