### ISSUE TITLE
Disable session timeout

### ISSUE THREAD

**Issue by secureighty** [SeleniumHQ/docker-selenium#2166]
Hey, I've got a project which involves a selenium instance that is storing clientside data and needs to idle for a potentially very long amount of time. In my docker compose, I set SE_NODE_SESSION_TIMEOUT to roughly 30 years as a temporary fix as shown below,

```  
selenium:
    environment:
      - SE_NODE_SESSION_TIMEOUT=999999999
    image: selenium/standalone-firefox
    expose:
      - "4444"
``` 
but I'd like to disable the timeout permanently with a value of -1. I can disable other timeouts by setting them to -1, but in this case, setting the SE_NODE_SESSION_TIMEOUT to -1 results in the session dying in 30 seconds. Below is a note brought up in a similar issue that states that session timeout can be greater than or equal to the value of defaultTimeout. How can I set it to less or disable it?

> HI @pedrofig-td,
> 
> Thanks for raising the issue.
> 
> 1. I see you're using `wdio/selenium-standalone-service` in the provided example, i.e `WebdriverIO` starts the selenium in standalone mode === standalone grid mode
> 
> 2. As @pujagani  mentioned above, the grid has a default timeout of 30 seconds in `Selenium3` and `Selenium4`
> 
> 3. When the WDIO starts the standalone service using Selenium4, the default timeout is set to 300 seconds (as Selenium4 expects a `--session-timeout` to override default timeout ignoring other timeouts mentioned in the config file)
> 
> The solution is, you need to pass arguments `--session-timeout` which can be greater or eq to defaultTimeout. ...

_Originally posted by @harsha509 in https://github.com/SeleniumHQ/selenium/issues/10030#issuecomment-977700897_

**Comment by VietND96** [comment]
@diemol, I think this should be implemented on upstream Selenium, right?

**Comment by diemol** [comment]
Session timeout is a safety net to release resources and control some session caches. Your workaround is excellent for your use case. 

I don't think we need to implement this, it would make the session handling code more complicated and potentially misuse this feature.
