### ISSUE TITLE
[🚀 Feature]: node-edge on Windows 11 platform

### ISSUE THREAD

**Issue by extravio** [SeleniumHQ/docker-selenium#2171]
### Feature and motivation

Our testing team would like to perform tests on Microsoft Edge on Windows 11.
We're using Selenium Grid 4.9.1 on AKS

Is there a solution documented anywhere?
Is there a plan to support it in the future?

### Usage example

-

**Comment by diemol** [comment]
Microsoft does not provide a Windows Docker image with a GUI. It is only possible with that. 

Related issues:
- https://github.com/SeleniumHQ/docker-selenium/issues/936
- https://github.com/SeleniumHQ/docker-selenium/issues/350
- https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214
