### ISSUE TITLE
How to make it run with net=host

### ISSUE THREAD

**Issue by lcacciagioni** [SeleniumHQ/docker-selenium#218]
Is there any practical way to run selenium grid with net=host?

**Comment by robtec** [comment]
Hey @lcacciagioni as in run the Selenium Grid Server on `net=host` VS `-p 4444:4444`... or do you mean the grid slave nodes?

**Comment by robvelor** [comment]
I would like to do this too, basically have the grid server on `net=host` and have the nodes connect connect to this server (should be at localhost).

**Comment by cbrevik** [comment]
I would also like to do this (use `net=host` on nodes), but it cannot be done at the moment because the nodes require that you link the Selenium Hub. If you try to link the hub and use `net=host`, you will get the following error (on Windows): `Conflicting options: host type networking can't be used with links. This would result in undefined behavior` 

Would be cool if instead of requiring a link to the hub, you could optionally provide IP+port.

**Comment by robvelor** [comment]
@cbrevik That error should popup regardless of OS, I believe the browser images require the `hub` host to point to the selenium hub, so it might work by just adding the extra host to the browser containers?

**Comment by cbrevik** [comment]
@robvelor That's pretty much what I said? 

Anyway, you can add `net=host` without using `link`, by setting the correct environment variables (`HUB_PORT_4444_TCP_ADDR` and `HUB_PORT_4444_TCP_PORT`. 

Something like:
`docker run -d -P -v /dev/shm:/dev/shm --net=host -e "HUB_PORT_4444_TCP_ADDR=10.0.75.2" -e "HUB_PORT_4444_TCP_PORT=4444" selenium/node-chrome`

**Comment by senpl** [comment]
To me default setting for google dns make no sense. How many people want to test pages that are currently in google DNS ??? Most will want their locally existing sites.

**Comment by diemol** [comment]
The way to make it work is shown in this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/218#issuecomment-229667544), nevertheless keep in mind that the `--net=host` only works currently in Linux machines where docker runs natively.

This is not working so far for Mac/Windows, but there is a workaround I explained in this [comment](https://github.com/SeleniumHQ/docker-selenium/issues/511#issuecomment-313932680).

Closing this issue.
