### ISSUE TITLE
Missing HttpOnly cookies

### ISSUE THREAD

**Issue by cbrevik** [SeleniumHQ/docker-selenium#219]
Unsure if this is Selenium, chromedriver or IIS-specific. I am using Docker for Windows (beta, with Hyper-V) on my PC. On the same PC, I am using IIS to serve a website.

When using the `selenium/standalone-chrome-debug:2.53.0` image to run a test on that website, the Chrome instance in the container does not receive any HttpOnly-cookies (I have used VNC to check). It does get normal cookies though. This means the CSRF token is gone, and trying to POST a form fails. 

Works fine if I visit the website on my PC. Both my PC and the container has the domain for the website in their HOSTS-file.

Normal traffic (HTTP GET) works fine fron the container, the only difference (thus far) is that it does not get HttpOnly-cookies.

**Comment by zypherman** [comment]
Does it allow them if you go onto the node and start chrome through the command line? You will have to open the terminal emulator and run something like 'google-chrome --user-data-dir' to open chrome. Then run through your scenario just like the test would. I am having some strange issues with the latest chrome-debug image and I am wondering if this is another thing its doing.

**Comment by cbrevik** [comment]
Thanks for the suggestion, just tried it. Sadly, still experiencing the same issue. 
I did get an error when running that command though:
```
# google-chrome --user-data-dir
[107:107:0523/213838:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[107:121:0523/213838:ERROR:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[316:316:0523/213839:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process
LaunchProcess: failed to execvp:

(google-chrome:107): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Address does not contain a colon
LaunchProcess: failed to execvp:
LaunchProcess: failed to execvp:
etc (several times)

(google-chrome:107): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Address element '/dev/null' does not contain a colon (:)
LaunchProcess: failed to execvp:
LaunchProcess: failed to execvp:
LaunchProcess: failed to execvp:
etc (several times)
```

Not sure if this is part of the problem?

**Comment by cbrevik** [comment]
When I opened up for navigating to external sites I do receive HttpOnly-cookies. So this is probably not related to docker-selenium or chromedriver.

It might be related to use of VPN on my host PC, which I need for the local IIS website (SQL-server related). Anyway, closing the issue. Thanks!
