### ISSUE TITLE
[🐛 Bug]: The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out

### ISSUE THREAD

**Issue by amistry96** [SeleniumHQ/docker-selenium#2200]
### What happened?

I am seeing this error The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out after 300 seconds (I have this set to 5mins) when running tests with Selenium and docker.

Our setup runs using agent linux agent machines once an agent is up it spins up the hub and nodes then test execution begins.

i have tried multiple versions and still seeing this. i have been seeing this intermittently  but now more consistently  

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
-----Docker Compose File----

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.19.1-20240402
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  selenium-hub:
    image: selenium/hub:4.19.1-20240402
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - NO_PROXY=localhost
      - SE_SESSION_REQUEST_TIMEOUT=500
      - SE_SESSION_RETRY_INTERVAL=5

-----Starting the chrome driver-----

private void StartRemoteDriver()
        {
            string userAgentValue = "*User Agent Value*";

            string userAgentPreprodConv = "*User Agent Value*";

            var chromeOptions = new ChromeOptions
           {
              BrowserVersion = "latest",
              PlatformName = configuration.platform
           };

            chromeOptions.AddArgument("--no-sandbox");

            chromeOptions.AddArgument("--disable-blink-features=AutomationControlled");

            chromeOptions.AddArgument("--window-size=1920x1080");

            chromeOptions.AddArgument($"--user-agent={userAgentValue}");

           chromeOptions.AddArgument($"--user-agent={userAgentPreprodConv}");          

            if (_scenarioSettings.IncognitoMode)
            {
                chromeOptions.AddArgument("--incognito");
            }
            if (configuration.DeviceName != string.Empty)
            {
                chromeOptions.EnableMobileEmulation(configuration.DeviceName);
            }
            _driver = new RemoteWebDriver(new Uri(configuration.remoteDriverUrl), chromeOptions.ToCapabilities(), TimeSpan.FromMinutes(5));
```

### Relevant log output

```shell
Error Message:
   OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out after 300 seconds.
```

### Operating System

Docker selenium 

### Docker Selenium version (image tag)

selenium/node-chrome:4.19.1-20240402

### Selenium Grid chart version (chart version)

selenium/hub:4.19.1-20240402

**Comment by diemol** [comment]
>BrowserVersion = "latest",

You need to use the exact browser version. Otherwise, the request will be placed in the queue, hoping a Node comes up with the requested capability, and then it will time out.

**Comment by amistry96** [comment]
This worked and allowed the test to run however, intermittently I am seeing a connection refused error part way through the test. 

The tests will start to run okay, then I see this error a couple of steps in 

-> error: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session/5f5035708d98a9f1797ce3f2796a6f0c/url. The exception message was: An error occurred while sending the request. (9.7s)

After the error above is seen I then start to see the connection refused error.

-> error: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session/df5b2d650152e5945cc9494564ea58b5/element. The exception message was: Connection refused (92.5s)

Stack trace 

Error Message:
   OpenQA.Selenium.WebDriverException : Error when trying to click on element 
OpenQA.Selenium.WebDriverException: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session/fd2d4554233ac69431aa7a75625921d9/element/f.11589A3A6A02E10DCE24761A85DE3A9E.d.7CB9BA1650C74D8B0F55F7FAF9A9A6E2.e.54/click. The exception message was: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.<>c__DisplayClass33_0.<<Execute>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Click()
   at PageObjects.BasePage.ClickElement(IWebElement element) in /agent/_work/1/s/next_autotest_dotnetcore/PageObjects/BasePage.cs:line 615
