### ISSUE TITLE
[🐛 Bug]: Many directories like .org.chromium.Chromium.TVyeMO in \tmp

### ISSUE THREAD

**Issue by uh-zuh** [SeleniumHQ/docker-selenium#2204]
### What happened?

After about 3 weeks of work there are about 8000 directories like `.org.chromium.Chromium.TVyeMO` in \tmp and total weight is about 1.9Gb.
I think directories shoud be deleted autmoatically.

Also there are about 44000 directories like `.com.google.Chrome.zZTYMG` in \tmp and total wight is about 64Mb.

All tests work normal and call quit() after each test.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
services:
  selenium-prod-service:
    image: selenium/standalone-chrome:${SELENIUM_VERSION:?Variable-is-undefined}
    container_name: selenium-prod-container
    restart: always
    shm_size: 2gb
    env_file:
      - ../config/selenium.all.env
      - ../config/selenium.prod.env
    networks:
      - prod-network
    ports:
      - target: ${NO_VNC_PORT_INTERNAL:?Variable-is-undefined}
        published: ${NO_VNC_PORT_EXTERNAL:?Variable-is-undefined}
        host_ip: 127.0.0.1
    volumes:
      - type: bind
        source: ../../share
        target: /app/share
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "${SELENIUM_WEB_DRIVER_PORT_INTERNAL:?Variable-is-undefined}"]
      start_period: 15s
      start_interval: 5s
      interval: 15s
      timeout: 30s
      retries: 5

networks:
  prod-network:
    name: prod-network
```

### Relevant log output

```shell
N/A
```

### Operating System

Ubuntu

### Docker Selenium version (image tag)

120.0.6099.224-chromedriver-120.0.6099.109-grid-4.17.0-20240123

**Comment by diemol** [comment]
There was a bug in Chrome some releases ago.

In addition, we have now this https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#automatic-browser-leftovers-cleanup
