### ISSUE TITLE
[🚀 Feature]: Question - is there a way IE Mode in EDGE supported in Linux OS based Grid edge node.

### ISSUE THREAD

**Issue by sharathchandran2001** [SeleniumHQ/docker-selenium#2237]
### Feature and motivation

In our case Selenium Grid EDGE node is hosted Linux OS Based Openshift Container Pods along with Hub.
Selenium tests are running in local windows machine. Is there a way IE Mode in Edge supports when tests from local windows machine routes to runs in Openshift linux edge pod/nodes. Ie on edge works fine when in windows based machine (without grid) where edge browser and IEdriver capabilities are added but it fails when routed to openshift edge pods/nodes.
For ie on edge tests with edge node in openshift , I refered latetest grid versions and selenium 4 desired capabilities per official docs.

### Usage example

Would to leverage IE mode on edge with openshift linux based Edge nodes/pods.

**Comment by diemol** [comment]
No, because you need the IEDriverServer, which is a binary for Windows.

**Comment by sharathchandran2001** [comment]
Thank you @diemol for confirming. I assume building grid (hub&nodes) in azure or on windows os base images shall be a Solution for this.

**Comment by diemol** [comment]
That is not possible either. There are no Windows Docker images with a UI.

**Comment by sharathchandran2001** [comment]
Ok, Thank you @diemol .  In summary,  the edge node machines in Selenium Grid architecture, needs to be a windows OS Based virtual machine or a windows server in order to support IE on Edge use case. Our vendor app runs only on IE Mode on Edge.
