### ISSUE TITLE
[🚀 Feature]: Upgrade to ubuntu 24.04 as Docker base image

### ISSUE THREAD

**Issue by StegSchreck** [SeleniumHQ/docker-selenium#2251]
### Feature and motivation

Currently, the docker image `selenium/standalone-firefox` is based on ubuntu 22. I understand that you might want to stick to LTS, but there is also a new LTS available with Ubuntu 24.04.

Not sure if "feature" is the best ticket type for this, please feel free to transfer into how it fits best into your model.

### Usage example

This would give access to newer software, e.g. python 3.12

**Comment by diemol** [comment]
Would you like to help us with a PR?

**Comment by StegSchreck** [comment]
> Would you like to help us with a PR?

I had a quick look, and it seems fairly easy to upgrade the reference. So it was already nicely extracted. Here is a PR #2252 - I wasn't sure how to execute tests. I hope this is covered by a CI job.
