### ISSUE TITLE
Correct possible error in the documentation 

### ISSUE THREAD

**Issue by lasest** [SeleniumHQ/docker-selenium#2261]
### Feature and motivation

The README.md file in the section "Using a bash script to wait for the Grid" suggests the following command to run wait-for-grid.sh:

`$ ./wait-for-grid.sh mvn clean test`

In my case, the command doesn't work as nothing happens when `Selenium Grid is up - executing tests` is printed. Inspecting the script, I find no evidence that something should happen in that case as it just finishes execution at that point.

Suggest correcting the command to:

`$ ./wait-for-grid.sh && mvn clean test`

In this case the command will be executed, if the script finishes normally. It it times out, 1 is returned and the command will not proceed

### Usage example

`$ ./wait-for-grid.sh && mvn clean test`

**Comment by diemol** [comment]
Good catch, can you please send us a pull request?

**Comment by VietND96** [comment]
Thank you @lasest, I have corrected it while changing another thing.
