### ISSUE TITLE
[🚀 Feature]: Support for pod labels and annotations for patch-scaledobjects-finalizers job

### ISSUE THREAD

**Issue by visit1985** [SeleniumHQ/docker-selenium#2262]
### Feature and motivation

Please provide a way to specify custom annotations (maybe labels too) in .spec.template.metadata for the patch-scaledobjects-finalizers job introduced in #2222.

### Usage example

We have to inject annotations for service mesh compatibility.

**Comment by VietND96** [comment]
Hi @visit1985, for the annotations, you can configure via `autoscaling.patchObjectFinalizers.annotations`

**Comment by visit1985** [comment]
@VietND96, unfortunately `.Values.autoscaling.patchObjectFinalizers.annotations` is propagated to the jobs  `.metadata`, not to `.spec.template.metadata` (which will be propagated to the jobs pod).
