### ISSUE TITLE
[🚀 Feature]: Selenium Grid Helm Chart: Do Not Patch Keda If Disabled

### ISSUE THREAD

**Issue by AndreasPetersen** [SeleniumHQ/docker-selenium#2268]
### Feature and motivation

We have disabled autoscaling on our Selenium Grid:

```
autoscaling:
  enabled: false
```

But when we update the grid, Keda is still patched, because 

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml#L1

does not check if autoscaling is also enabled.

This unexpectedly caused some issues for us, as we were not expecting Keda to patch. Specifically we need to fetch our Docker images through a corporate Artifactory, so the default `kubectlImage` was being blocked, causing upgrade failure.

I propose that patching of Keda is disabled if autoscaling is disabled.

### Usage example

Setting

```
autoscaling:
  enabled: false
```

in `values.yaml` will disable Keda patching.

**Comment by VietND96** [comment]
Hi, for the reason the patch job is running even `autoscaling.enabled: false` to ensure cleanup in case upgrade an existing deployment with enabled autoscaling to disabled autoscaling.
Of course, I agree that it will cause annoying for common usage. Will update another mechanism for this.
In the meantime, you can use config `autoscaling.patchObjectFinalizers.enabled` to disable it separately.

**Comment by AndreasPetersen** [comment]
Thanks for the quick reply @VietND96 .

Like you said, I specifically disabled the patcher, and upgrading the grid then works as expected.
