### ISSUE TITLE
[🐛 Bug]: Cannot see what is happening inside the container using  --network=host

### ISSUE THREAD

**Issue by creative-andrew** [SeleniumHQ/docker-selenium#2286]
### What happened?

When using `docker run --rm -it --shm-size 2g --network=host selenium/standalone-chromium:latest`, I cannot longer access `http://localhost:7900/?autoconnect=1&resize=scale&password=secret` to watch the container.

In the logs, the IP `192.168.65.3` as mentioned, and its the one I am able to connect correctly.

2024-06-24 11:14:11 09:14:11.405 INFO [Standalone.execute] - Started Selenium Standalone 4.22.0 (revision c5f3146703): http://192.168.65.3:4444

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run --rm -it --shm-size 2g --network=host selenium/standalone-chromium:latest
```

### Relevant log output

```shell
2024-06-24 11:14:11 09:14:11.405 INFO [Standalone.execute] - Started Selenium Standalone 4.22.0 (revision c5f3146703): http://192.168.65.3:4444
```

### Operating System

MacOs

### Docker Selenium version (image tag)

latest

**Comment by VietND96** [comment]
I also tried to reproduce on macOS M1 and could see the result below. How it displays in your end?

<img width="1027" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/23253546/dac46416-c40b-4ba1-b586-a76b42f3ba27">

**Comment by creative-andrew** [comment]
Hi there! Thanks for your quick reply:


<img width="1440" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/18492002/77eb879a-8378-47c3-87b9-49399aaf0762">

<img width="1440" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/18492002/51e1457a-b6c8-4e1d-93c1-4cefa0f6276d">

<img width="1163" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/18492002/0322be3e-5afa-4ac5-826b-8487920ea4c8">

**Comment by VietND96** [comment]
In this case, can you try to open Chrome Dev Tool (F12) in the Console tab, is there any error raised?
Or in tab Network, any request gets 404 or error there?

**Comment by VietND96** [comment]
Also, if you are using Docker Desktop, is this config enabled?
<img width="994" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/23253546/3ee69789-3174-47c1-a4ca-21866e3799f7">

**Comment by creative-andrew** [comment]
@VietND96 after enabling that option (that was disabled on my system), it works now as expected.

**Comment by creative-andrew** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/2286#issuecomment-2186272659
