### ISSUE TITLE
[🐛 Bug]: PHPUnit unable to establish session with latest version of docker-selenium

### ISSUE THREAD

**Issue by bkline** [SeleniumHQ/docker-selenium#2291]
### What happened?

I see that [docker-seleniarm](https://github.com/seleniumhq-community/docker-seleniarm) has been merged into this project, but it appears that the issues have not been carried over. A little over a year ago I filed a [bug report](https://github.com/seleniumhq-community/docker-seleniarm/issues/33) that a regression in the latest version of the images prevented a `phpunit` `FunctionalJavascript` test against a Drupal site from connecting to the chromium container on an M1 Mac ("regression" because the older version from April 2022 still works). @jamesmortensen (the maintainer of docker-seleniarm) closed that ticket and told me to reopen it when I was able to provide a small enough repro case for him to be able to reproduce the problem. However, there was no mechanism available to reopen the ticket, so a few months ago I filed a [second ticket](https://github.com/seleniumhq-community/docker-seleniarm/issues/68) providing the requested repro case. James never responded to that ticket, and now it's been archived, blocking me from adding any further comments, so I'm filing this ticket with the repro case.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
# Start the older version of the Docker image.
docker run --rm -it -p 4444:4444 -e "SE_SESSION_REQUEST_TIMEOUT=5" \
  seleniarm/standalone-chromium:4.1.4-20220429
# From a separate terminal window, request a session. Output is shown in the
# attached session-test-success.out, with HTTP code 200, and a response
# which includes a valid session ID.
php session-test.php
# Stop the container (control+C) in the first terminal window, and start a fresh
# container with the current version of the image.
docker run --rm -it -p 4444:4444 -e "SE_SESSION_REQUEST_TIMEOUT=5" \
  selenium/standalone-chromium:latest
# Back to the second terminal window, running the same PHP scriot.
# This time a 500 error will be returned (see attached sessison-test-failure.out).
php session-test.php
```

### Relevant log output

```shell
See attached output.
```

### Operating System

Mac M1 Pro Sonoma 14.5

### Docker Selenium version (image tag)

4.22.0-20240621

### Selenium Grid chart version (chart version)

N/A

**Comment by bkline** [comment]
Here is the repro script, along with the captured output referenced above, as well as the output for the containers.

[docker-selenium-issue-2291.tgz](https://github.com/user-attachments/files/16015695/docker-selenium-issue-2291.tgz)

**Comment by jamesmortensen** [comment]
Hi @bkline I apologize for the lack of communication on my part.  Since our last interaction, there's been a flurry of life changes for my family and I, including repatriating from India back to the USA, and we're still working on settling in.  Unfortunately, I don't know if I'll be able to dig into the repro script anytime soon, but if I do find time for this project, this would be one of the first things I'd dig into. 

I do recall an issue someone reported with PHP, where we couldn't replicate with other language bindings, like JavaScript or Python or Java, and we did trace the issue back to the https://github.com/php-webdriver/php-webdriver project.  PHP is unique in that another group of open source developers maintains those bindings.  If I had time to debug, I'd probably start by seeing if I could isolate the issue to either Selenium or php-webdriver.  Hope this helps, and thank you for continuing to post updates.  I sincerely wish that I had more time than I do right now.

**Comment by bkline** [comment]
Welcome back, @jamesmortensen. You probably saw in the previous ticket that I was scratching my head with the contradictory information about whether you were in Chattanooga or Chennai. Don't know how long you were there, but you may have come across our friend Andy Simkin, who was stationed at our consulate there a decade or so back.

I am pretty sure I boiled down the repro script far enough that it's just talking directly over HTTP to the chromium container using pure PHP. There are no dependencies on _any_ external packages, so I think that rules out the `php-webdriver` project as the culprit. In fact, unless there's something funky going on in core PHP (and its `curl` wrapper), I should be able to come with an equivalent repro script in any language. I'll try to whip up a Python script.

**Comment by bkline** [comment]
Sure enough. When you run the following Python script against `seleniarm/standalone-chromium:4.1.4-20220429` you'll get output reporting the successfully-obtained session ID. Run the same script when the container is using the image for the latest released version (from either project, `selenium` or `seleiarm`), and you'll get "HTTP Error 500: Internal Server Error."

```python
#!/usr/bin/env python3

from json import dumps, loads
from urllib.request import Request, urlopen

PARAMETERS = {
    "desiredCapabilities": {
        "browserName": "chrome",
        "name": "Behat Test",
        "chromeOptions": {
            "w3c": False,
            "args": [
                "--disable-gpu",
                "--no-sandbox",
                "--disable-dev-shm-usage",
            ],
        },
    },
}

request = Request("http://localhost:4444/session")
request.add_header("Content-Type", "application/json;charset=UTF-8")
request.add_header("Accept", "application/json;charset=UTF-8")
request.add_header("Expect", "")
try:
    with urlopen(request, dumps(PARAMETERS).encode("ascii")) as response:
        payload = loads(response.read())
    session_id = payload["sessionId"]
    print(f"successfully retrieved session id {session_id}")
except Exception as e:
    print(e)
``` 

Please let me know if you need any further information.

**Comment by bkline** [comment]
Does this project have any other active maintainers (given @jamesmortensen's current unavailability)?

**Comment by diemol** [comment]
I forgot to reply to this. You are using an old version of the protocol that is not supported since Selenium 4.9. Read more at https://www.selenium.dev/blog/2022/legacy-protocol-support/.

You probably need to check the latest version of the PHP bindings.

**Comment by bkline** [comment]
Thanks, @diemol. I'll read the materials to which you linked and see what needs to change in `PHPUnit`. If what you say is true, wouldn't a 4xx HTTP code be more appropriate than a 500 error?

4xx codes -> there's a problem in the client's request; fix it and try again
5xx codes -> there's a problem with the server; nothing you can do about it

**Comment by diemol** [comment]
That is what was decided in the standard https://w3c.github.io/webdriver/#errors

**Comment by bkline** [comment]
So they decided that the distinction between an error caused by the client and an error caused by the server is no longer appropriate? That seems unfortunate, to put it politely.

**Comment by diemol** [comment]
I am just trying to explain why you were getting an error, and I wish not to get into why a decision was made several years ago.

**Comment by bkline** [comment]
I'm not saying _you_ made a bad decision. I'm just saying that whoever made that decision is ignoring the [original semantics](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) of the HTTP status codes.

> 4xx client error – the request contains bad syntax or cannot be fulfilled
5xx server error – the server failed to fulfil an apparently valid request

It doesn't seem appropriate to tell the client its request was "apparently valid" when it's not.
