### ISSUE TITLE
[🚀 Feature]: Manage TLS Certificate Externally

### ISSUE THREAD

**Issue by declan-fitzpatrick** [SeleniumHQ/docker-selenium#2293]
### Feature and motivation

The [tls-cert-secret.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/templates/tls-cert-secret.yaml) has limited functionality. 

It only allows self signed cert generation if ingress is enabled, and tls is disabled. Alternatively, you have to pass the values of the certificate in as non-base64 literals, which causes an issue with the `selenium.jks` binary. 

Ideally, the helm chart would allow you to manage the secret yourself, and pass the name into a value like `.Values.tls.existingSecretName`. Functionally, only `seleniumGrid.tls.fullname` needs an update,  and then [tls-cert-secret.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/templates/tls-cert-secret.yaml) would need an overall toggle

### Usage example

To use the feature, you would manage your secret yourself, provisioning however you deem fit, for example: 

```shell
./cert.sh
kubectl -n selenium-grid create secret generic ca-selenium --from-file=selenium.pem --from-file=selenium.jks --from-file=selenium.pkcs8
```

And use the TLS secret in Selenium Grid.
```helm
...
tls: 
  enabled: true
  existingSecretName: "ca-selenium"
...
```

**Comment by VietND96** [comment]
In part of this, I am doing the refactoring on helm chart config keys to enable TLS ingress only or the secure connection in both server and ingress in front
