### ISSUE TITLE
[🐛 Breaking change]: Harmonized configuration mount point between docker images to /opt/selenium/config.toml

### ISSUE THREAD

**Issue by Trigtrig** [SeleniumHQ/docker-selenium#2340]
### What happened?

*This is more an inconsistency instead of a bug but it may lead to confusion when mounting a configuration file.*

When setting up a Selenium Grid using Docker we can mount a `config.toml` for configuration as shown in the [documenation](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#dynamic-grid). But the mount point differs in the images. Here is a small table showing the current state:
| Docker image | mount point |
|---------------|---------------|
| [Hub](https://github.com/SeleniumHQ/docker-selenium/blob/547f97e9ac5e58d44bde8ca8c742e1e61170c4b2/Hub/start-selenium-grid-hub.sh#L120) | /opt/**selenium**/config.toml |
| [NodeDocker](https://github.com/SeleniumHQ/docker-selenium/blob/547f97e9ac5e58d44bde8ca8c742e1e61170c4b2/NodeDocker/start-selenium-grid-docker.sh#L96) | /opt/**bin**/config.toml |
| [NodeBase](https://github.com/SeleniumHQ/docker-selenium/blob/547f97e9ac5e58d44bde8ca8c742e1e61170c4b2/NodeBase/generate_config#L12) | /opt/**selenium**/config.toml |
| [Standalone](https://github.com/SeleniumHQ/docker-selenium/blob/547f97e9ac5e58d44bde8ca8c742e1e61170c4b2/Standalone/start-selenium-standalone.sh#L152) | /opt/**selenium**/config.toml |
| [StandaloneDocker](https://github.com/SeleniumHQ/docker-selenium/blob/547f97e9ac5e58d44bde8ca8c742e1e61170c4b2/StandaloneDocker/start-selenium-grid-docker.sh#L82) | /opt/**bin**/config.toml |

This may lead to configuration errors since the `config.toml` is mounted to a valid location in one container but will be silently ignored in another container where the mount point differs. I added a simple hub-node-setup using docker-compose which shows that.

I would suggest to always use the same mount point for `config.toml` and I'm willing to send in a PR but since this can break existing docker setups, I'm not sure what is the best way to change this.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
# docker-compose.yml
name: selenium-grid

services:
  selenium-hub:
    image: selenium/hub:4.23.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    volumes:
      # mounted to /opt/bin/ instead of expected mount point /opt/selenium/ will run the hub by mistake without the desired configuration
      - ./hub-config.toml:/opt/bin/config.toml

  selenium-node:
    image: selenium/node-docker:4.23.0
    container_name: selenium-node
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
    volumes:
      # same mount point will work for the node
      - ./node-config.toml:/opt/bin/config.toml


# hub-config.toml
[router]
username = "foo"
password = "bar"


# node-config.toml
[server]
host = "selenium-node"
port = "5555"

[node]
detect-drivers = true
override-max-sessions = false
```

### Relevant log output

```shell
no relevant log output
```

### Operating System

doesn't matter

### Docker Selenium version (image tag)

4.23.0

### Selenium Grid chart version (chart version)

no chart involved

**Comment by VietND96** [comment]
@diemol, what do you think?

**Comment by diemol** [comment]
This makes sense. We might have just missed being consistent across images. We should be using `/opt/selenium/config.toml` in all of them.
