### ISSUE TITLE
Chrome images need updating to v2.22 of ChromeDriver

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#236]
The official Docker images for Chrome here are still at 2.21. Would be great if they are updated to v2.22 (released June 6) as they support the latest Chrome browser versions and have important fixes.

http://chromedriver.storage.googleapis.com/2.22/notes.txt

**Comment by testphreak** [comment]
@smmcarthy I noticed you had filed the same ticket #234 . Any idea when the change will be official? I still see the container uses v2.21.

```
seluser@29e3519b95b0:/opt/selenium$ ls
chromedriver-2.21  config.json  selenium-server-standalone.jar
```

**Comment by testphreak** [comment]
@elgalu @kayabendroth would be great if the chrome Docker images can be updated with the latest ChromeDriver version.

**Comment by RubyGemTSL** [comment]
+1 for getting latest ChromeDriver version.

**Comment by Deshke** [comment]
maybe jump directly to http://chromedriver.storage.googleapis.com/2.23/notes.txt ?

**Comment by ddavison** [comment]
closing in preference of #250
