### ISSUE TITLE
[🐛 Bug]: xmessage in selenium test video 

### ISSUE THREAD

**Issue by johndaniel7** [SeleniumHQ/docker-selenium#2369]
### What happened?

After starting the Selenium Grid with the setup provided, the tests execute successfully and a video is uploaded to Azure Blob Storage. However, the video is only 1 second long and does not actually show the test execution. 
The error message "fbsetbg: Something went wrong while setting the wallpaper. Run 'Esetroot -c /usr/share/images/fluxbox/ubuntu-light.png' from an xterm to find out what suggests there’s a problem with the wallpaper setting process." This issue is likely preventing the video from being recorded properly. please check the attached video 

https://github.com/user-attachments/assets/81d38c22-f892-4fc0-8758-55899bfab003

In summary:
Tests run but are not recorded.
The video is only 1 second long. 
An error with setting the wallpaper is causing the problem. 
![Screenshot from 2024-08-23 21-39-52](https://github.com/user-attachments/assets/eba266ee-6b58-405b-b67e-211578d91809)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
#hub
services:
   selenium-hub:
    image: selenium/hub:4.23.0-20240727
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
#chrome 
services:

  chrome:
    image: selenium/node-chrome:4.23.1-20240813
    shm_size: 1gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_ENABLE_TRACING=false
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"

  chrome_video:
    image: selenium/video:ffmpeg-7.0.1-20240813
    shm_size: 1gb
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_UPLOAD_ENABLED=true
      - SE_VIDEO_INTERNAL_UPLOAD=true
      - SE_VNCENABLED=false
      - SE_VIDEO_END_SCREEN_ENABLED=false
      - SE_UPLOAD_DESTINATION_PREFIX=azureblob://${AZURE_CONTAINER_NAME}
      - RCLONE_CONFIG_AZUREBLOB_TYPE=azureblob
      - RCLONE_CONFIG_AZUREBLOB_ACCOUNT=${AZURE_ACCOUNT_NAME}
      - RCLONE_CONFIG_AZUREBLOB_KEY=${AZURE_ACCOUNT_KEY}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
```

### Relevant log output

```shell
the error message is posted above in the video . The error message "fbsetbg: Something went wrong while setting the wallpaper. Run 'Esetroot -c /usr/share/images/fluxbox/ubuntu-light.png' from an xterm to find out what suggests there’s a problem with the wallpaper setting process." This issue is likely preventing the video from being recorded properly
```

### Operating System

ubuntu 20.04

### Docker Selenium version (image tag)

selenium/video:ffmpeg-7.0.1-20240813

**Comment by VietND96** [comment]
```
      - SE_VNCENABLED=false
      - SE_VIDEO_END_SCREEN_ENABLED=false
```
These 2 env vars are customized in your deployment?

**Comment by johndaniel7** [comment]
yes, they are. sorry for late reply, was off work

**Comment by VietND96** [comment]
I update the command to set background. However, ensure that VNC is enabled
