### ISSUE TITLE
Chromium node in grid helm chart

### ISSUE THREAD

**Issue by rChaoz** [SeleniumHQ/docker-selenium#2377]
I'm curious. Is there a reason why there is no `chromiumNode` in the helm chart? If I want to use chromium, is it as simple as forking and cloning the `chromeNode` to add it myself?

**Comment by VietND96** [comment]
Do you want to use both Chrome and Chromium at the same time?
Since, there is no doubt on this before, so I guess mostly people change the image name

**Comment by diemol** [comment]
Why do you need it?

**Comment by rChaoz** [comment]
I don't want to use both, and somehow I missed that you can change the image name. I want to be able to run grid on ARM, and the chromium image runs on ARM. It seems like changing the image name worked, thanks!
