### ISSUE TITLE
[🚀 Feature]: Topology spread constrains for nodes

### ISSUE THREAD

**Issue by piotrlaczykowski** [SeleniumHQ/docker-selenium#2381]
### Feature and motivation

Hello, Unfortunately, all of our edge nodes go to one k8s worker node. Could you please add topologySpreadConstraints?
Example down below. Right now I am adding it manually to the keda ScaledJob 

### Usage example

        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app: selenium-edge-node
            maxSkew: 4
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule

**Comment by VietND96** [comment]
Fixed by https://github.com/SeleniumHQ/docker-selenium/commit/4f2a6e41e793e5c17c41ae000f6499bdd311782d
