### ISSUE TITLE
selenium node debug container exited(127) immediately

### ISSUE THREAD

**Issue by luisxiaomai** [SeleniumHQ/docker-selenium#239]
Hi,

I installed docker for mac beta recently, but I can't start node debug container, it always exit(127) immediately.
Container log is 
```
 Waiting xvfb...
 Waiting xvfb...
 Waiting xvfb...
```

The hub container can be up. I used below docker commands to run:
$ docker run -d -p 4444:4444 --name selenium-hub selenium/hub:2.53.0
$ docker run -d -P --link selenium-hub:hub selenium/node-chrome-debug:2.53.0

It's ok when I use toolbox to install docker, can you give some help for this.

B.R.
Luis

**Comment by bayandin** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/227

For me `-e no_proxy=""` works.

**Comment by luisxiaomai** [comment]
@bayandin , thanks giving related link. 
``` -e no_proxy=localhost -e HUB_ENV_no_proxy=localhost ``` works for me

**Comment by vikramvi** [comment]
@luisxiaomai @bayandin can you please paste complete command here ? 

As I tried docker run -P -p 5900:5900 -e no_proxy=localhost -e HUB_ENV_no_proxy=localhost --link selenium-hub:hub selenium/node-firefox-debug:2.53.0

does work for me Mac mini ( 10.10.5 ) with docker 1.12.1 ( build: 121333)

**Comment by vikramvi** [comment]
docker run -d -P -e no_proxy=localhost -e HUB_ENV_no_proxy=localhost --link selenium-hub:hub selenium/node-chrome-debug

This worked for me. Had missed -d in earlier command.

https://docs.docker.com/engine/reference/commandline/run/ , but didn't understand why missing this parameter is causing issue ?

**Comment by saradcd77** [comment]
Sarads-MBP:~ saraddhungel$ docker run -d -P -e no_proxy=localhost -e HUB-ENV_no_proxy=localhost --link selenium-hub-P:hub selenium/node-chrome-debug

I got e39b20bbe9379e102cee533f8da87d4e27986018d5a15e0668ccc7051287c97b after entering the above line. Yet I don't see the nodes connected to the hub. What could be the issue? Some help please!
