### ISSUE TITLE
[🚀 Feature]: Selenium grid Authentication password is stored as plain text in Helm chat values.yaml file

### ISSUE THREAD

**Issue by manojgorantla23** [SeleniumHQ/docker-selenium#2391]
### Feature and motivation

currently the selenium grid auth password is stored as a plain text in the values.yaml of helm chart can we fetch it from secrets

### Usage example

fetch the password from  different secret stores so it is not exposed public

**Comment by VietND96** [comment]
In scope of this, another config key will be added provide an external Secret resource name that contains basic auth for reference. Otherwise, the default plain text in chart values.yaml will be used.
