### ISSUE TITLE
[🐛 Bug]: Invalid Capability Causes Selenium Hub Pod to restart

### ISSUE THREAD

**Issue by amardeep2006** [SeleniumHQ/docker-selenium#2394]
### What happened?

One of my developer accidentally passed a capability that does not exist on the selenium grid. The developer used webdriver io framework. The capability passed was browserVersion: 'v.stable' . The same is reproducable with browserVersion: 'stable' as well. 
Within few attempts, It caused grid to crash as hub pod was restarted due to probe failures. 
It has cascading effect on grid and causes all running sessions crash and few browser nodes also restart.

The sessions appear pending on grid for few seconds and then hub pod restarts as kubernetes kills it. 

![image](https://github.com/user-attachments/assets/21766c1f-92b6-4eae-a964-fb1d9316b563)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
I am using helm chart version 0.35.0 .

Attaching the event logs from Selenium Hub pod.
```

### Relevant log output

```shell
Type Reason Updated Message
Warning	Unhealthy (8)	7 mins ago	(combined from similar events): Liveness probe failed: 02:13:11.581 DEBUG [Probe.Liveness] - GraphQL endpoint http://masked:masked@selgrid-selenium-hub.dev-selgrid:4444/graphql is not reachable. Status code: 000.
Normal	Created (5)	8 mins ago	Created container selgrid-selenium-hub
Normal	Started (5)	8 mins ago	Started container selgrid-selenium-hub
Normal	Pulling (5)	8 mins ago	Pulling image "myregistry/selenium-grid/hub:4.24.0-20240910"
Normal	Pulled	8 mins ago	Successfully pulled image "myregistry/selenium-grid/hub:4.24.0-20240910" in 574.304063ms (574.319173ms including waiting)
Normal	Killing (4)	8 mins ago	Container selgrid-selenium-hub failed liveness probe, will be restarted
Warning	Unhealthy	8 mins ago	Liveness probe failed: 02:12:40.661 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:12:40.664 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	8 mins ago	Liveness probe failed: 02:12:30.625 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:12:30.628 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	8 mins ago	Liveness probe failed: 02:12:20.622 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:12:20.624 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	8 mins ago	Liveness probe failed: 02:12:10.696 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:12:10.699 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	9 mins ago	Liveness probe failed: 02:12:00.654 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:12:00.657 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	9 mins ago	Liveness probe failed: 02:11:50.662 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:11:50.665 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	9 mins ago	Liveness probe failed: 02:11:40.619 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:11:40.621 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	9 mins ago	Liveness probe failed: 02:11:30.705 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:11:30.708 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
Warning	Unhealthy	9 mins ago	Liveness probe failed: 02:11:20.618 DEBUG [Probe.Liveness] - Session Queue Size: 3, Session Count: 0, Max Session: 125 02:11:20.621 DEBUG [Probe.Liveness] - It seems the Distributor is delayed in processing a new session in the queue. Probe checks failed.
```

### Operating System

kubernetes 1.26.15

### Docker Selenium version (image tag)

4.24.0

### Selenium Grid chart version (chart version)

0.35.0

**Comment by amardeep2006** [comment]
For now I have applied workaround to reject such requests to protect the grid.
```yaml
  extraEnvironmentVariables:
    - name: SE_REJECT_UNSUPPORTED_CAPS
      value: "true"    
```

**Comment by VietND96** [comment]
Ah yes, this is a feature for Hub/Distributor liveness probe - https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid#distributor-probes
I think you can update timeout or failureThreshold in probe settings
I think this is also a way to signal something is wrong, which causes the queue to increase without a new session coming up.

**Comment by VietND96** [comment]
However, via this ticket, we can consider if `SE_REJECT_UNSUPPORTED_CAPS` can be enforce as `true` by default

**Comment by amardeep2006** [comment]
Thanks for prompt response @VietND96 . Was worried as small/wrong payload from developer caused grid to burn and crash. 
Can this flag `SE_REJECT_UNSUPPORTED_CAPS` cause some issue with keda based autoscaling ?
I will also check the settings you mentioned.

**Comment by VietND96** [comment]
The condition unhealthy once active sessions is keeping 0 for a long time. For example, few sessions are ongoing well, and few incorrect requests in queue, it will not impact the liveness probe.

> Can this flag SE_REJECT_UNSUPPORTED_CAPS cause some issue with keda based autoscaling ?

In my view, it should not cause any issue in autoscaling.

**Comment by amardeep2006** [comment]
@VietND96  I tried SE_REJECT_UNSUPPORTED_CAPS with KEDA enabled for Jobs based autoscaling and seems it does not play nice with autoscaling. The hub simply rejected all valid requests as well since browser nodes were scaled to zero.

**Comment by VietND96** [comment]
Yes, that's right. I am just aware that behavior should have at least 1 Node of each stereotype is available for the checks.
In this case I think you can disable the liveness probe, or switch to use another method e.g httpGet

**Comment by amardeep2006** [comment]
Thanks Viet. I am closing the issue with following possible solutions:
1. We can use SE_REJECT_UNSUPPORTED_CAPS with min 1 replica.
2. Tune the Health check probes as per need.
3. Clarification that it does not impact the when active sessions are more than 0 .

Thanks.
