### ISSUE TITLE
[🐛 Bug]: Resource Limits missing for pre-pull InitContainer

### ISSUE THREAD

**Issue by Koeppchen** [SeleniumHQ/docker-selenium#2398]
### What happened?

With https://github.com/SeleniumHQ/docker-selenium/commit/44d922495cc686d3fc48605e2b3d9d0836f399a5 an Init Container without resource limits was added. All containers should have resource limits.
Changing templates/_helpers.tpl initContainer to 
            
    initContainers:
      - name: "pre-puller-{{ .name }}"
        image: {{ printf "%s/%s:%s" $nodeImageRegistry .node.imageName $nodeImageTag }}
        command: ["bash", "-c", "'true'"]
      {{- with .node.resources }}
        resources: {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- if $.Values.videoRecorder.enabled }}
      - name: "pre-puller-{{ $.Values.videoRecorder.name }}"
    
  would already be suficient do do this.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm install
```

### Relevant log output

```shell
36s         Warning   FailedCreate        replicaset/selenium4-selenium-edge-node-688b799797      Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [container-must-have-limits] container <pre-puller-selenium4-selenium-edge-node> has no resource limits
```

### Operating System

Kubernetes

### Docker Selenium version (image tag)

4.24.0-20240907

### Selenium Grid chart version (chart version)

0.35.2

**Comment by VietND96** [comment]
We will also consider to add the `admission webhook "validation.gatekeeper.sh"` https://github.com/open-policy-agent/gatekeeper to the test cluster to detect such issue early.

**Comment by Koeppchen** [comment]
Thank you,
it might be hard to define gatekeeper configuration for those test cases. But of course resource limits is a very common one.
