### ISSUE TITLE
Can't download files in standalone-firefox

### ISSUE THREAD

**Issue by mateuyabar** [SeleniumHQ/docker-selenium#241]
I've a selenium script that, among other things downloads some files. It works fine without docker.

When I use the standalone-firefox docker image, the downloads do not work.
A part file is created (in ./tmp/mozilla_mozillaUser0/X5_NP22k.pdf.part), but the final pdf is never creaded.

Thanks

**Comment by istinspring** [comment]
Same i ended up downloading this folder to the host using docker-py

```
cli = docker.Client()
strm, stat = cli.get_archive(cont, '/tmp/mozilla_mozillaUser0')
print(stat)
archive = tarfile.TarFile(
    fileobj=io.BytesIO(strm.data)
)
archive.extractall(path='var/reports/{}'.format(cont))
```

Do you setup the firefox profile?

**Comment by ddavison** [comment]
if i understand this correctly, @mateuyabar you are trying to download a file from the browser into the docker container?  why are you doing this instead of putting the downloaded file on the host machine?

**Comment by mateuyabar** [comment]
This was three months ago. I wanted to download it anywhere. Just could not get the downloaded file.
I ended up using chrome-docker to solve this, so I can't tell you more about this problem.

**Comment by istinspring** [comment]
@ddavison can you tell me how to download file directly into the host machine?

**Comment by zuernBernhard** [comment]
perhaps its possible to configure a browser-profile to automaticall accept downloads and save them do a certain directory eg ~/downloads 

but how to clean that up after eacht test run ?

**Comment by istinspring** [comment]
i end up with mount the download directory from the container to the host.

@zuernBernhard you can use scripts https://docker-py.readthedocs.io

**Comment by ddavison** [comment]
there you go ^.  mounting directories is the best way to accomplish this.  by mounting, then you will have the directory on your machine.

**Comment by gokulganthtm** [comment]
We have certain Automation Test which downloads reports from web appl and store in default downloads directory in chrome or firefox .......how does docker chrome or Firefox containers handle this ?
While ./bash into chrome containers ->  /opt directory has some files related to chrome but not any downloaded files
Mounting volumes while spinning up the containers and binding it with host machine didn't provide any promising results.....

How do we handle this in docker-compose or docker run ????

**Comment by diemol** [comment]
Hi, the downloads should be found in the `/home/seluser/Downloads` folder, please check #461 for more details.

Closing this one.
