### ISSUE TITLE
[🚀 Feature]: Add "--noproxy '*'" to Base/check-grid.sh curl

### ISSUE THREAD

**Issue by Zalutskii** [SeleniumHQ/docker-selenium#2431]
### Feature and motivation

If the docker proxy settings on the host machine include localhost, there might be an issue with the "Base/check-grid.sh" check. This can be avoided by adding "--no proxy '*'" to the curl request line. In this case, the curl request will never go outside the docker container.

### Usage example

`curl -skSL --noproxy '*' -H "Authorization: Basic ${BASIC_AUTH}" ${SE_SERVER_PROTOCOL:-"http"}://${HOST}:${PORT}/wd/hub/status | jq -r '.value.ready' | grep -q "true" || exit 1
`

**Comment by VietND96** [comment]
Good catch! I already added it
