### ISSUE TITLE
[🚀 Feature]: Updating firefox for the standalone selenium 2 image

### ISSUE THREAD

**Issue by uuf6429** [SeleniumHQ/docker-selenium#2454]
### Feature and motivation

At the [Mink](https://github.com/minkphp/) project, we are still supporting Selenium 2 and in some recent tests we added retroactively, [we found](https://github.com/minkphp/MinkSelenium2Driver/pull/359#issuecomment-2033764953) that they fail for the Firefox / Selenium 2 image due to Firefox 47 (which is 8 years old - [latest is 132](https://www.mozilla.org/en-US/firefox/releases/), by comparison).

Is there any chance of pushing and tagging an updated image (not necessarily with the latest Firefox, just a small update from 47)?

Alternatively, we can somehow do it ourselves, but I've figured this could be in the interest of the community.

### Usage example

This would help supporting users of Selenium 2.

**Comment by VietND96** [comment]
Are you using this image tags https://github.com/SeleniumHQ/docker-selenium/releases/tag/2.53.1-beryllium ?

**Comment by aik099** [comment]
@VietND96 we use this command to start Docker:

```
docker run --net host --name selenium --volume /dev/shm:/dev/shm --volume ./vendor/mink/driver-testsuite/web-fixtures:/fixtures --shm-size 2g selenium/standalone-firefox:2.53.1 &> ./logs/selenium.log &
```

If I'm not mistaken the `selenium/standalone-firefox:2.53.1` is the tag name.

**Comment by VietND96** [comment]
I see, but when upgrading to the new Firefox, we also need to consider the Geckodriver version. Moreover, if you are still using Selenium 2, how do we ensure the combination of those 3 works together?

**Comment by uuf6429** [comment]
@VietND96 before reporting this issue I noticed that there is a script that somehow builds an image based on minimal input (selenium version, browser type, browser version):
https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#build-the-images-with-specific-versions

I'm not deeply familiar with this project, so I cannot answer how images are being tested.

However: doing a minimal upgrade should probably not break too many things and secondly our test suite would be able to say if it worked fine or not.

**Comment by aik099** [comment]
@VietND96 I can tell, that Firefox 132.0 + geckodriver 0.35.0 combination works with Selenium 2.

Both versions mentioned are current.

**Comment by VietND96** [comment]
Yes, that note is written for images built on top of Selenium 4. For older version, I am not sure it will work, since there is a big gaps in env vars configuration between v2 and v4.
Anyhow, which version of Firefox do you want to upgrade in v2 image now?

**Comment by VietND96** [comment]
> @VietND96 I can tell, that Firefox 132.0 + geckodriver 0.35.0 combination works with Selenium 2.

Ok, let me try to see the patch can be done

**Comment by uuf6429** [comment]
> Yes, that note is written for images built on top of Selenium 4. For older version, I am not sure it will work, since there is a big gaps in env vars configuration between v2 and v4.

Sorry to hear that, I hoped it would be straightforward.

> Anyhow, which version of Firefox do you want to upgrade in v2 image now?

At least Firefox 92, but higher (as @aik099 reported) wouldn't hurt. :)

> Ok, let me try to see the patch can be done

Thanks for your time!

**Comment by diemol** [comment]
You need to check out the tag for that version https://github.com/SeleniumHQ/docker-selenium/tree/2.53.1, and then modify the Firefox version there https://github.com/SeleniumHQ/docker-selenium/blob/2.53.1/NodeFirefox/Dockerfile.txt#L8. The GeckoDriver version is below that. The README shows how to do the build process https://github.com/SeleniumHQ/docker-selenium/blob/2.53.1/README.md

I am unsure if everything will work because those images rely on old packages. 

Please note that Mozilla does not support Selenium 2: https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

I will close this because we are focused on the Selenium 4 images and the Helm chart. If you need help, you can open a discussion. Thanks!

**Comment by uuf6429** [comment]
That's slightly disappointing, but understandable. 😅 

Thanks for the pointers though.
