### ISSUE TITLE
[🐛 Bug]: Firefox: "Some of Nightly's security features may offer less protection on your current operating system"

### ISSUE THREAD

**Issue by AB-xdev** [SeleniumHQ/docker-selenium#2463]
### What happened?

When executing ``selenium/standalone-firefox`` the following warning shows up:
![](https://github.com/user-attachments/assets/dbfec116-55e1-48c4-a0df-fd4a1a36e050)

The link seems to lead to https://support.mozilla.org/en-US/kb/install-firefox-linux#w_security-features-warning

### Docker Selenium version (image tag)

4.26.0

**Comment by VietND96** [comment]
I think that docs for Firefox running on host, since in the container, we don't have a config of `apparmor.service`
Sometime before, I also tried another installation ways e.g via Mozilla apt, or install without root in $HOME dir, but that flag does not clear.
Do you have any suggestion for this?

**Comment by AB-xdev** [comment]
NOTE: So far this only seems to happen on the ARM64 variant of the image. Somehow there is Firefox **Nightly** used while normal Firefox is used for AMD64.

**Comment by VietND96** [comment]
For case Nightly build in ARM64 image, it is a known issue that noted in README

> Mozilla Firefox now is available for Linux/ARM64 via [Nightly channel](https://blog.nightly.mozilla.org/2024/04/19/firefox-nightly-now-available-for-linux-on-arm64/). The Firefox version in ARM64 will be different with the AMD64 until the stable release is available. The Firefox (node and standalone) images are available in multi-arch.

The version in both arch will be in sync once Mozilla release for linux/arm64 on stable channel
