### ISSUE TITLE
[🐛 Bug]: Fails to start a new session using Firefox v130, v131, v132 for Linux operating system

### ISSUE THREAD

**Issue by prajaktak15** [SeleniumHQ/docker-selenium#2473]
### What happened?

Not able to run scripts on selenium grid  Firefox node 4.25, 4.26 for linux operating system.

It works fine if I start the node on 4.24

Error message while running scripts on firefox node:
[[1;31mERROR[m] [1;31mFailures: [m
[[1;31mERROR[m] [1;31m  RunCukesByFeatureGSGWeb.feature » SessionNotCreated Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: binary is not a Firefox executable

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Docker compose file used:

selenium-tst-firefox:
    container_name: firefoxnode
    environment:
      - SE_EVENT_BUS_HOST=<server-host>
      - SE_EVENT_BUS_PUBLISH_PORT=<port>
      - SE_EVENT_BUS_SUBSCRIBE_PORT=<port>
      - SE_NODE_HOST=<node-host>
      - SE_NODE_PORT=<port>
      - REMOTE_HOST=https://${HOSTNAME}:<port>
      - SE_OPTS=<certificate-path>
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_DRAIN_AFTER_SESSION_COUNT=100
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_GRID_URL=<Hub-url>
      - JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=2000000
    image: node-firefox:4.26.0-20241101
    privileged: true
    logging:
      driver: "none"
    shm_size: 2gb
    ports:
      - <port>:<port>
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - /opt/grid/cert:/home/seluser
```

### Relevant log output

```shell
Error message while running scripts on firefox node:
[[1;31mERROR[m] [1;31mFailures: [m
[[1;31mERROR[m] [1;31m  RunCukesByFeatureGSGWeb.feature » SessionNotCreated Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: binary is not a Firefox executable
```

### Operating System

RHEL 8

### Docker Selenium version (image tag)

4.26.0-20241101

**Comment by prajaktak15** [comment]
Hello Team,

Is there any update on this issue.
Thank you.

**Comment by VietND96** [comment]
I am not able to reproduce. Can you share the test, where RemoteWebDriver is created with all browser options set?

**Comment by prajaktak15** [comment]
Here is the code:

			FirefoxOptions firefoxProxyOptions = new FirefoxOptions();
			firefoxProxyOptions.setCapability("acceptInsecureCerts", true);
			firefoxProxyOptions.setCapability(CapabilityType.PROXY, proxy);
			firefoxProxyOptions.setPlatformName("LINUX");
			firefoxProxyOptions.setBrowserVersion("132.0");
			driver = new RemoteWebDriver(new URL(HUB_URL), firefoxProxyOptions, false);
			driver.get(app_url);
			
Let me know if you need any other information.
Thank you.

**Comment by prajaktak15** [comment]
Hello Team,

Is there any update on this issue.
Thank you.

**Comment by VietND96** [comment]
Hi, please update in docker compose file
`image: node-firefox:nightly`
to verify and confirm. Thanks!

**Comment by prajaktak15** [comment]
Hello 

Thank you for the fix.

I confirm it is working fine for Platform = Linux  Browser = Firefox   Version = v133.

Could you please let us know what was causing this issue? Thanks!

**Comment by VietND96** [comment]
The fix was: Moving installed Firefox directory back to `/opt/firefox-$VERSION` from `/home/seluser/firefox`
In a change, firefox is downloaded and extracted to `/home/seluser/firefox` then link to `/usr/bin/firefox`.
I guess due to your volume mount `- /opt/grid/cert:/home/seluser` causing firefox binary has issue with r/w perms or something.
`/home/seluser` could be mounted with different purposes by the user, to avoid disturbing the program executable, I moved it back `/opt`
