### ISSUE TITLE
[🐛 Bug]: novnc does not start: problem with export named 'supportsWebCodecsH264Decode'

### ISSUE THREAD

**Issue by betelgeuse** [SeleniumHQ/docker-selenium#2474]
### What happened?

With container image d8061a466074 noVNC does not start

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
selenium:
    container_name: selenium_chrome
    image: "selenium/standalone-chrome:dev"
    platform: linux/amd64
    # https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#--shm-size2g
    shm_size: 2G
    environment:
      SE_NODE_SESSION_TIMEOUT: 1800
    ports:
      - "127.0.0.1:7900:7900" # VNC via HTTP
    networks:
      - internal_network
```

### Relevant log output

```shell
noVNC encountered an error:

Uncaught SyntaxError: The requested module './util/browser.js' does not provide an export named 'supportsWebCodecsH264Decode'
http://localhost:7900/core/rfb.js:13:25
SyntaxError: The requested module './util/browser.js' does not provide an export named 'supportsWebCodecsH264Decode'
```

### Operating System

Linux VM provided by Docker version 27.3.1, build ce12230

### Docker Selenium version (image tag)

d8061a466074

**Comment by VietND96** [comment]
Hi, can you try the image tag `nightly` to see if the issue is fixed?
Since I saw on repo noVNC, a few commits related to this recently - https://github.com/novnc/noVNC/commits/master/

**Comment by betelgeuse** [comment]
> Hi, can you try the image tag `nightly` to see if the issue is fixed? Since I saw on repo noVNC, a few commits related to this recently - https://github.com/novnc/noVNC/commits/master/

Same issue with image af98c65d0355

**Comment by VietND96** [comment]
Thanks for your response. Currently, we are getting the latest code from their main branch. I will probably switch to using the last stable version to fix this.
