### ISSUE TITLE
[🐛 Bug]: chromeNode.service.enabled regression

### ISSUE THREAD

**Issue by aidanthewiz** [SeleniumHQ/docker-selenium#2482]
### What happened?

While attempting to upgrade to `selenium-grid-0.38.0`/`4.27.0-20241127`, I received this error:
```
Error: template: selenium-grid/templates/chrome-node-service.yaml:8:24: executing "selenium-grid/templates/chrome-node-service.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

#2475 appears to be the cause, with the below minimum replication (broken.yaml):

```yaml
chromeNode:
  service:
    enabled: true
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm upgrade --install selenium-grid docker-selenium/selenium-grid --namespace selenium -f broken.yaml
```

### Relevant log output

```shell
Error: template: selenium-grid/templates/chrome-node-service.yaml:8:24: executing "selenium-grid/templates/chrome-node-service.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

### Operating System

Kubernetes 1.30.5 on Docker Desktop 4.36.0 (175267) on macOS 15.2 Beta (24C5089c)

### Docker Selenium version (image tag)

4.27.0-20241127

### Selenium Grid chart version (chart version)

0.38.0

**Comment by VietND96** [comment]
Thanks for your report. This and something else are ongoing to fix and will be out in chart 0.38.1.
