### ISSUE TITLE
[🐛 Bug]: Node: Disable/Enable VNC view only (or GUI interaction)

### ISSUE THREAD

**Issue by alramostpt** [SeleniumHQ/docker-selenium#2485]
### What happened?

Documentation explain the enable/disable of GUI interactions with the use of the env var as follows:
If you want to run VNC in view-only mode you can set the environment variable `SE_VNC_VIEW_ONLY=1`.
https://github.com/SeleniumHQ/docker-selenium/blob/cf0c839ab05a6ae958ef2ef813c6d9aaddbf65d7/README.md?plain=1#L1666

But flag for that settings works as follow:
if [ ! -z $VNC_VIEW_ONLY ];
https://github.com/SeleniumHQ/docker-selenium/blob/cf0c839ab05a6ae958ef2ef813c6d9aaddbf65d7/NodeBase/start-vnc.sh#L25

Where this IF operation enables the view only mode when this env contains any value instead of the documented method of setting that value to 1.

This creates an unintended behavior when the value is set to 0 expecting to disable the view only mode.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
N/A (any)
```

### Relevant log output

```shell
N/A
```

### Operating System

Any

### Docker Selenium version (image tag)

Any

### Selenium Grid chart version (chart version)

Any

**Comment by VietND96** [comment]
The value `0`, `1` seems not make sense to me. Since in bash, `0` stands for true, and of course it is correct when comparing as string. I am preferred to `true` or `false`.
However, to avoid regression breaking, I keep comparing with `true` or `1`

**Comment by alramostpt** [comment]
> The value `0`, `1` seems not make sense to me. Since in bash, `0` stands for true, and of course it is correct when comparing as string. I am preferred to `true` or `false`. However, to avoid regression breaking, I keep comparing with `true` or `1`

Reaching the conclusion of doing nothing to avoid regression breaking with even updating documentation to clarify expected behavior seems non-sense to me. It seems that the real intention done here is just to close this issue.
