### ISSUE TITLE
[🐛 Bug]: selenium/node-firefox Docker Image has Differing Browser Versions per Architecture

### ISSUE THREAD

**Issue by kbarnesMCC** [SeleniumHQ/docker-selenium#2487]
### What happened?

The amd64 and arm64 builds of "node-firefox" appear to be using different Firefox versions for the same tag.

For example, when leveraging `selenium/node-firefox:130.0` the on an x64 machine; the resulting version in Selenium Hub is `130.0` as expected. Unforutnately, when using this same tag on `arm64`; the resulting version is actually `132.0`.

I noticed when attempting to update to `132.0` tag the amd64 updates properly but the arm64 version is actually `134.0`.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
services:
  selenium:
    container_name: selenium
    image: selenium/hub:4.19
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    healthcheck:
      disable: true

  selenium-node:
    container_name: selenium-firefox
    image: selenium/node-firefox:130.0
    ports:
      - 50001:7900
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    depends_on:
      - selenium
    healthcheck:
      disable: true
```

### Relevant log output

```shell
Will Attach Screenshots after ticket creation.
```

### Operating System

Linux, MacOSX

### Docker Selenium version (image tag)

4.19

**Comment by kbarnesMCC** [comment]
Here's the screenshot for amd64 when using `130.0` as the docker tag.
![image](https://github.com/user-attachments/assets/5cff64d3-8710-47d0-8f5d-829d5da823f2)

**Comment by kbarnesMCC** [comment]
Here's the screenshot for arm64 when using `130.0` as the docker tag.
<img width="630" alt="image" src="https://github.com/user-attachments/assets/7077b55a-d9f2-46cb-9f59-d6779d174799">

**Comment by VietND96** [comment]
Unfortunately, we rely on Firefox, they are not shipping Linux/arm64 in Beta/Stable channel
You can follow their progress on https://bugzilla.mozilla.org/show_bug.cgi?id=1677963

**Comment by VietND96** [comment]
The note of mismatch version in README https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#experimental-multi-arch-amd64aarch64armhf-images

**Comment by kbarnesMCC** [comment]
I see, apologies didn't see that subtlety in the README. Going to close this one then and work around the limitation on our end (e.g. not specify a `browserVersion` capability for our local development teams who are mixed architecture.)

**Comment by VietND96** [comment]
I just rechecked, Firefox also archives Nightly packages https://download-installer.cdn.mozilla.net/pub/firefox/nightly
So, I will pin the version to be synced with Linux/AMD64 for a while
Hopefully, this will help user experience is better.
