### ISSUE TITLE
Selenium version(2.53.1) update required to work with firefox 47.

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#252]
Selenium new version 2.53.1 is released which will work with the latest firefox 47. 
Could you please update the selenium version to 2.53.1 for docker-selenium images?

**Comment by davehunt** [comment]
See #251

**Comment by dgangwar** [comment]
@davehunt is there any update about the fix #251

**Comment by davehunt** [comment]
@dgangwar only what you can already see on that pull. I won't have any time to work on this until next week at the earliest, but anyone else is welcome to pick this up before then and address the comments.

**Comment by ddavison** [comment]
this has been updated.  2.53.1 has FF 47
