### ISSUE TITLE
node-firefox-debug run error with xvfb.

### ISSUE THREAD

**Issue by wywincl** [SeleniumHQ/docker-selenium#253]
I use selenium-hub and node-firefox-debug.and when i run node-firefox-debug, it run error with logs .
My Platform info:
OSX 10.11.6
Docker 1.12.0

wangyang  wangyangdeMacBook-Pro  ~  %  docker ps                                                                                                            10:14:01
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
da8c2598666f        selenium/hub        "/opt/bin/entry_point"   2 days ago          Up 4 minutes        0.0.0.0:32768->4444/tcp   selenium-hub
 wangyang  wangyangdeMacBook-Pro  ~  %  docker run -d -P --link selenium-hub:hub selenium/node-firefox-debug                                                 10:14:06
e64d6282f71cca5e6c41d24acf7539439c314fd99e562d494b1a546609af034b
 wangyang  wangyangdeMacBook-Pro  ~  %  docker ps                                                                                                            10:14:12
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                     NAMES
e64d6282f71c        selenium/node-firefox-debug   "/opt/bin/entry_point"   3 seconds ago       Up 2 seconds        0.0.0.0:32771->5900/tcp   elegant_varahamihira
da8c2598666f        selenium/hub                  "/opt/bin/entry_point"   2 days ago          Up 4 minutes        0.0.0.0:32768->4444/tcp   selenium-hub
 wangyang  wangyangdeMacBook-Pro  ~  %  docker logs e64d                                                                                                     10:14:14
Waiting xvfb...
-bash: 169.254/16: No such file or directory
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
 wangyang  wangyangdeMacBook-Pro  ~  %  docker ps                                                                                                            10:14:32
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
da8c2598666f        selenium/hub        "/opt/bin/entry_point"   2 days ago          Up 13 minutes       0.0.0.0:32768->4444/tcp   selenium-hub

**Comment by jnarowski** [comment]
+1

**Comment by h4n0l1** [comment]
In my case, there is an env var called `no_proxy`, and somehow this env var makes `xvfb run` execution failed. So I set `no_proxy` to null and also put `sudo -i -u seluser` before executing `x11vnc`, and now it's running, but please CMIIW

**Comment by saikrishna321** [comment]
@h4n0l1 how do we set your solution in docker-compose.yml ?

**Comment by h4n0l1** [comment]
@saikrishna321 I put `export no_proxy=` in `entry_point.sh` just before `SERVERNUM=$(get_server_num)` or maybe you can even put that after `export GEOMETRY`. Also, in `docker-compose.yml` you can put that as `ARGS` below `build` option inside service. CMIIW
