### ISSUE TITLE
DefaultRemoteProxy Connection Timed out, trying to connect physical mac mini device to docker hub

### ISSUE THREAD

**Issue by kevinyu-ias** [SeleniumHQ/docker-selenium#254]
OS: AWS, Docker, Mac Mini 10.11.5

Selenium Version: selenium server 2.53.0

Browser:

Created a docker hub and able to connect other docker nodes to the docker hub
`docker run -d -p 4444:4444 --name selenium-hubselenium/hub:${selenium_version_2.53.0}`

When I attempt to connect a physical node (mac mini)

`java -jar selenium-server-standalone-2.53.0.jar -role node -hub http:// hub_ip:4444/grid/register -browser browserName=firefox`

I've also tried adding -remoteHost mac_mini_ip:port 
I get the output
INFO - The node is registered to the hub and ready to use

When I navigate to the grid/console it takes a significant amount of time to load and I receive the 
DefaultRemoteProxy unknown version, connect to :port / failed: Connection timed out

The docker hub is sitting on an AWS instance with openVPN installed. The openVPN configs exist on the node as well.

From the physical node (mac mini) I am able to wget hub_ip:4444/grid/register and it returns a 200
While the node is attempting to connect to the hub, I am able to do a wget from the hub -> node
`wget http://mac_mini_host:5555/wd/hub/status`
It returns a 200. 

When I ssh into the hub, I try to telnet mac_mini_ip:port I get ERROR 403: Forbidden for Proxy

Not sure if this is causing the DefaultRemoteProxy, but as of now I'm unable to connect a physical node to a hub on AWS is there a solution for this?

**Comment by ddavison** [comment]
for your hub_ip, try prepending "http://" to it.

`java -jar selenium-server-standalone-2.53.0.jar -role node -hub http://hub_ip:4444/grid/register -browser browserName=firefox`

**Comment by kevinyu-ias** [comment]
@ddavison tried that as well, no luck

**Comment by kevinyu-ias** [comment]
Is it possible to connect a non linux node to a docker hub?

**Comment by kevinyu-ias** [comment]
@rubytester  Hey, I watched your selenium conf 2015 video and was wondering if you could help me connect physical nodes to an aws instance running a docker selenium hub

**Comment by kevinyu-ias** [comment]
Using docker's --net=host resolved this issue

**Comment by ddavison** [comment]
glad you figured it out! 👍
