### ISSUE TITLE
selenium/standalone-chrome fails on restart command

### ISSUE THREAD

**Issue by nuggit32** [SeleniumHQ/docker-selenium#257]
selenium/standalone-chrome fails on restart command with the following error:
xvfb-run: error: Xvfb failed to start

1.  docker run -d -p 6666:4444 --name Chrome -P selenium/standalone-chrome

2. docker ps -a results
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                    NAMES
0ff7f108a98f        selenium/standalone-chrome   "/opt/bin/entry_point"   3 seconds ago       Up 2 seconds        0.0.0.0:6666->4444/tcp   Chrome

3.. docker restart Chrome
Error Message in log:
xvfb-run: error: Xvfb failed to start

4. docker ps -a results
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                     PORTS               NAMES
0ff7f108a98f        selenium/standalone-chrome   "/opt/bin/entry_point"   37 seconds ago      Exited (1) 1 seconds ago                       Chrome

The restart command works fine for selenium/standalone-chrome-debug.

**Comment by gurukiran007** [comment]
https://github.com/SeleniumHQ/docker-selenium/pull/256 Solves it, issue with debug containers only

**Comment by nuggit32** [comment]
@gurukiran007 this issue is not with debug containers. 

"selenium/standalone-chrome fails on restart command"
