### ISSUE TITLE
node-chrome docker image build throws "gpg: no valid OpenPGP data found." error

### ISSUE THREAD

**Issue by sqavenky** [SeleniumHQ/docker-selenium#265]
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && apt-get update -qqy && apt-get -qqy install google-chrome-stable && rm /etc/apt/sources.list.d/google-chrome.list && rm -rf /var/lib/apt/lists/*

gpg: no valid OpenPGP data found.

Getting the above error when building from Dockerfile.

**Comment by ddavison** [comment]
do you still get this error with the newest version?

**Comment by saifsysim** [comment]
I am encountering the same issue , was there a resolution for this??? @sqavenky @ddavison

**Comment by diemol** [comment]
@sqavenky @saifsysim 
This usually happens when you are behind a proxy or have some network problems.

Can you please double check your network config and report back?

**Comment by sqavenky** [comment]
You are right

On Sep 10, 2017 1:35 PM, "Diego Molina" <notifications@github.com> wrote:

@sqavenky <https://github.com/sqavenky> @saifsysim
<https://github.com/saifsysim>
This usually happens when you are behind a proxy or have some network
problems.

Can you please double check your network config and report back?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SeleniumHQ/docker-selenium/issues/265#issuecomment-328362438>,
or mute the thread

**Comment by diemol** [comment]
OK, thanks for reporting back.
