### ISSUE TITLE
Feature request:node-chrome docker image :Request team to make the dockerfile generic to add a version parameter like node-firefox image, so that we can build different versions of chrome nodes.

### ISSUE THREAD

**Issue by sqavenky** [SeleniumHQ/docker-selenium#266]
Request team to make the dockerfile generic to add a version parameter like node-firefox image, so that we can build different versions of chrome nodes.

**Comment by ddavison** [comment]
to be clear here, you're asking for a `CHROME_VERSION`?  right now, there is `CHROME_DRIVER_VERSION` but no way to explicitly install a different version of chrome.  Is this what you're asking?

**Comment by sqavenky** [comment]
node-firefox has a ENV variable "ENV FIREFOX_VERSION 45.0.2" which helps you to build a docker image with specific version of firefox. In this case Firefox 45.0.2.  I am looking something similar for Chrome as well. Today if i try to build with the node-chrome Dockerfile. I always get the latest stable version of chrome installed in the docker image. Correct me if I am wrong? Today I am creating multiple images for chrome as and when a new version of chrome is release and I run my selenium scripts against the docker container and try to print the browser version to know the version of browser inside the container. But with this parameter in place, I do not have to worry about browser version. You are correct about CHROME_DRIVER_VERSION. It is already in place. I am not talking about that.

**Comment by ddavison** [comment]
take a look at the referenced commit. this is what you want. give me some time, I'll merge it in.

**Comment by sqavenky** [comment]
You got it right. Thanks for the quick turn around.
