### ISSUE TITLE
Latest docker build for selenium/standalone-chrome cannot accept confirms

### ISSUE THREAD

**Issue by doits** [SeleniumHQ/docker-selenium#268]
I have a ruby test which does this:

```
page.accept_confirm { page.find_button('Some text').click }
```

The button opens a confirm dialog which should be accepted.

With `selenium/standalone-chrome:2.49.1` it works and accepts the confirm dialog. With current `selenium/standalone-chrome:latest` (pushed ~7 hours ago) it hangs forever there.

I was already crazy why my tests hung/fail until I discovered the cause seems to be the latest docker build 😢 

Is this known or does it happen only for me (because of my setup maybe?)?

**Comment by TaysirTayyab** [comment]
Can confirm this is an issue in 2.53 which was pushed sometime yesterday. Have also had issues with tab inserting literal tabs into fields instead of moving to the next field. I don't know why the ninja push without changing the version number, but we've had to grab the previous 2.53 image off local cache and add it as our own image to the registry.

**Comment by ckortekaas** [comment]
Also seeing my test runners now fail with the latest changes to 2.53.0. Could the release team please change tags for rebuilds to avoid issues like this in the future? Only finding success going as far back as 2.49.1 right now - just like @doits.

**Comment by jagalan** [comment]
Same here, hours chasing that until I found this issue and realized our tests started failing a bit after these new builds were executed and our runners picked them up.

Going back to 2.49.1 solved the issue.

**Comment by philjones88** [comment]
👍  having issues suddenly with protractor and accepting alert's and the new version

**Comment by Yantrio** [comment]
I amalso seeing this issue with node-chrome-debug image, the latest image is not allowing us to close alerts. Going to try rolling back to an earlier version

**Comment by FelikZ** [comment]
I guess this is done because this commit:
https://github.com/SeleniumHQ/docker-selenium/commit/82d0a45a8dd184eff6699f621b85dfd60e1173a1#diff-6bc64b0868b8e4376e4bb89ca55caa46R20

Maybe `latest` chrome not compatible enough anymore

**Comment by doits** [comment]
@FelikZ faulty commit must be earlier already, it started happening on 08.09.2016 (5 days ago).

**Comment by FelikZ** [comment]
@doits yes, since registry image [being rebuilt](https://hub.docker.com/r/selenium/node-chrome-debug/tags/) and start using latest Chrome (I bet this is the issue)

**Comment by doits** [comment]
Hopefully when #280 is implemented at least once stable tags will not break sporadically because they are rebuilt with incompatible versions like now.

**Comment by doits** [comment]
Just built 2.53.1 myself (https://hub.docker.com/r/stellenticket/standalone_chrome/) but it has the same problem 😢 

Looks like it is not easy to fix ...

**Comment by ddavison** [comment]
just ran this against the latest selenium/standalone-chrome image with the following ruby script, and it works for me

```ruby
#!/usr/bin/env ruby

require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:remote, :url => 'http://localhost:4444/wd/hub', :desired_capabilities => :chrome)
driver.get 'https://the-internet.herokuapp.com/javascript_alerts'
driver.find_element(:css, "button[onclick='jsConfirm()']").click
driver.switch_to.alert.accept
driver.switch_to.default_content
puts driver.title
driver.quit
```
