### ISSUE TITLE
Error while pulling image

### ISSUE THREAD

**Issue by rogoit** [SeleniumHQ/docker-selenium#269]
I can not install it. Do i have to do something else before? Can you make a install tutorial from scratch on a plain webserver ;)

Error while pulling image: Get https://index.docker.io/v1/repositories/selenium/standalone-chrome/images: dial tcp: lookup index.docker.io on 213.203.208.212:53: no such host
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/selenium/standalone-chrome/images: dial tcp: lookup index.docker.io on 213.203.208.212:53: no such host.
See '/usr/bin/docker-current run --help'

**Comment by ddavison** [comment]
what command exactly are you running so we can try it from our end.  at first glance, it looks like it could be some sort of limitation on your corporate network?

**Comment by rogoit** [comment]
Hi,

this here
$ docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:2.53.0
Unable to find image 'selenium/standalone-chrome:2.53.0' locally
Trying to pull repository docker.io/selenium/standalone-chrome ...
Pulling repository docker.io/selenium/standalone-chrome
Error while pulling image: Get https://index.docker.io/v1/repositories/selenium/standalone-chrome/images: dial tcp: lookup index.docker.io on 213.203.208.212:53: no such host
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/selenium/standalone-chrome/images: dial tcp: lookup index.docker.io on 213.203.208.212:53: no such host.
See '/usr/bin/docker-current run --help'.

But i can open the index.docker.io url with wget and get it.

**Comment by rogoit** [comment]
The help command gives me a list of commands and is working fine.

**Comment by rogoit** [comment]
This was my fault. It has to do with internal dns for the webserver. Sorry for that. Can be closed!!
