### ISSUE TITLE
updated 2.53.1 selenium artifact images not available in docker.io/selenium/hub 

### ISSUE THREAD

**Issue by ipai84** [SeleniumHQ/docker-selenium#272]
Based  on docker-selenium latest update to 2.53.1, we updated our docker-compose configs to pull latest (2.53.1) images,  but we always get the following error: 

> Pulling hub (selenium/hub:2.53.1)...
> Pulling repository docker.io/selenium/hub
> ERROR: Tag 2.53.1 not found in repository docker.io/selenium/hub

It seems the official Selenium release has been updated without updating the official Selenium docker images. We need to access the latest selenium docker images for our frameworks, would be great to have them accessible in the registry asap.

**Comment by eXorus** [comment]
Hello,

Is it possible to push the updated images to docker.io ? the lastest images doesn't work WITH GRID_TIMEOUT and I hope it will be fixed in 2.53.1 ...

Thanks

**Comment by ddavison** [comment]
both the issues you speak of, @eXorus  have been pushed today
