### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by westlakem** [SeleniumHQ/docker-selenium#278]
Dockerfiles are missing from node/chrome and chrome-standalone images

**Comment by CaptainMack** [comment]
Would be nice to have, so we can update the chromedriver ourselves.

**Comment by davehunt** [comment]
The Dockerfile is generated by the make script. See https://github.com/SeleniumHQ/docker-selenium/blob/master/Makefile#L63-L64 for example.

**Comment by tomfun** [comment]
@davehunt this information need to be added to readme.

**Comment by ddavison** [comment]
I'm still in the process of getting myself involved in docker-selenium, and I would love to spend some time with @kayabendroth so he could show me around.

I wouldn't mind doing this once i understand everything :wink:

**Comment by ddavison** [comment]
in fact, let's leave this discussion open.  @kayabendroth - let's talk.  shoot me an email and let's set up a time where you can give me a knowledge transfer of the docker stuff so i could help maintain this repository
