### ISSUE TITLE
Change debug image vnc port number

### ISSUE THREAD

**Issue by jackmahoney** [SeleniumHQ/docker-selenium#281]
Hi. I've noticed that the `entry_point.sh` scripts for debug nodes execute an x11vnc server passing it the flag `-rfbport 5900`. Is there a way to change the port myself? Aside from a PR.

**Comment by bhaku** [comment]
@jackmahoney why you need this? When you run docker container you can use port forwarding:

`docker run -p 5999:5900 ...`

**Comment by jackmahoney** [comment]
Good point @bhaku , will try this. Thanks.
