### ISSUE TITLE
Is there a docker image planned for selenium 3 beta?

### ISSUE THREAD

**Issue by F2X** [SeleniumHQ/docker-selenium#282]
Hi! I would like to know if there is some docker image planned for selenium 3.0-beta?
I need the SafariDriver support ([https://webkit.org/blog/6900/webdriver-support-in-safari-10/](https://webkit.org/blog/6900/webdriver-support-in-safari-10/)), and my testing architecture is based on docker

**Comment by davehunt** [comment]
There is https://github.com/SeleniumHQ/docker-selenium/pull/271, which includes 3.0-beta3.

**Comment by F2X** [comment]
Thanks, there is any delivery planned on docker registry?

**Comment by ddavison** [comment]
ASAP!  hopefully tomorrow

**Comment by ddavison** [comment]
Released 3.0.0-beta3 and 3.0.0-beta4 tonight
