### ISSUE TITLE
Environment variable overrides are ignored with latest image

### ISSUE THREAD

**Issue by gerich-home** [SeleniumHQ/docker-selenium#283]
Hi,
I have identified that hub ignores environment variable overrides.
I am not able to change the value of config options in docker-compose file:
```
  hub:
    image: selenium/hub
    environment:
      - GRID_TIMEOUT=36000
```

I see that my change has no effect (it is critical!).

I try ssh'ing into container:
```
docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS
                             NAMES
...
357362562d6f        selenium/hub                  "/opt/bin/entry_point"   About a minute ago   Up About a minute   4444/tcp
                             e2e_hub_1
...

docker exec -it 357362562d6f sh
```

There I view config.json and see that it has default content in it!
```
$ cat /opt/selenium/config.json

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
```

I try regenerating it manually:
```
$ /opt/selenium/generate_config > /opt/selenium/config.json
```

And it now contains valid values:
```
$ cat /opt/selenium/config.json

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 36000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
```

The issue seems to be introduced by https://github.com/SeleniumHQ/docker-selenium/pull/185

My comment on it: https://github.com/SeleniumHQ/docker-selenium/pull/185#issuecomment-249556790

**Comment by ddavison** [comment]
as the author of this change - i'm looking into this.  already have a pull request ( #284 ) that fixes this.  i'll merge when ready.  however - I still don't have the ability to push to docker hub just yet.

**Comment by gerich-home** [comment]
Thank you so much for your quick response!
For now I have just reverted my docker-compose to the previous version of image:
```
image: selenium/hub:2.49.1
```

**Comment by ddavison** [comment]
this is fixed
