### ISSUE TITLE
node-chrome-debug:2.53.0 not registering with selenium hub

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/docker-selenium#285]
I'm having Mac mini ( 10.10.5 ) with docker  1.12.1 ( build: 121333)

I've installed selenium-hub  2.53.0 and tried to register debug version of chrome 2.53.0 but it's not getting registered.

Although node-chrome:2.53.0 getting registered properly

doing docker ps -a  showing STATUS code Exited (127) for debug version of chrome.

Is there something I'm missing to configure ?

Thanks,
Vikrma

**Comment by ddavison** [comment]
hi @vikramvi, the 2.53.0 versions are unstable at the moment.  I'm in the process right now of pushing up 2.53.1.  maybe try those versions?  later i will work on getting 2.53.0 stable again
