### ISSUE TITLE
VNC server is off for 2.53.1 (latest) docker images

### ISSUE THREAD

**Issue by MegaUkrainian** [SeleniumHQ/docker-selenium#291]
Hello,

I faced with an issue of connecting to firefox/chrome-node-debug for 2.53.1 (latest) images. According to the logs, starting of the vncserver was failed:

```
Waiting xvfb...
05:55:43.976 INFO - Launching a Selenium Grid node
03/10/2016 05:55:44 passing arg to libvncserver: -rfbport
03/10/2016 05:55:44 passing arg to libvncserver: 5900
Enter VNC password: stty: 'standard input': Inappropriate ioctl for device
fgets: No such file or directory
stty: 'standard input': Inappropriate ioctl for device
x11vnc -usepw: could not find a password to use.
```

I think the following statement was failed while image was creating:
```
RUN mkdir -p ~/.vnc \
 && x11vnc -storepasswd secret ~/.vnc/passwd
```

Please check. Thank you in advance.

**Comment by ddavison** [comment]
hi @MegaUkrainian thanks for reporting this.. this change actually directly goes against @gurukiran007 's change in #256 , so i'd like to make sure that he has some input on this.

**Comment by TheBay0r** [comment]
As an alternative to b3c9fa5 it might be possible to start x11vnc in the entry script as seluser as well?

**Comment by ddavison** [comment]
it does work as root, and i'm going to leave it that way, really doesn't matter who is running the vnc server.  i've pushed up a new version of the 2.53.1, 3.0.0-beta3 and 3.0.0-beta4 versions, and they are currently building.  they will push when done (and of course, if tests pass.) will close this issue when they are released

**Comment by TheBay0r** [comment]
Your fix was my first local quick fix as well. Just tried running x11vnc as seluser now, because I don't know why it does matter where the secret is stored. 
Thanks for taking care!

**Comment by ddavison** [comment]
well it matters since whoever runs `x11vnc -usepw...`, the `-usepw` param will look for ~/.vnc.  if root is running the command, then it will look at `~root/.vnc`.  if seluser runs that command, it will look for `~seluser/.vnc`.  

i will say, that running the `x11vnc` command from seluser with the `~seluser/.vnc` command would probably work, but since the entry_point.sh is already running as root, might as well keep it that way, and put the `passwd` file in `~root/.vnc` 👍

**Comment by ddavison** [comment]
pushed all versions

**Comment by gurukiran007** [comment]
👍
