### ISSUE TITLE
StandaloneFirefox 2.53.0 image hosted on hub.docker.com was updated and broke internal build.

### ISSUE THREAD

**Issue by sanscore** [SeleniumHQ/docker-selenium#293]
I, unfortunately, didn't save the errors that I could have shared, and I have logged errors that I *cannot* share.

Before this weekend, I had been using the `selenium/standalone-firefox:2.53.0` image. It was using Firefox version 45.0.2 prior to this past weekend. After the weekend, it now uses `47.0.1` and something about is not working properly. It seems like Firefox crashes at startup. On a whim, I updated to`selenium/standalone-firefox:2.53.1` which works.

However, I want to keep tests reproducible, so I want to use Firefox 45.0.2. To resolve the issue, I have resorted to building and locally hosting the image from this commit https://github.com/SeleniumHQ/docker-selenium/commit/645aa674b05180b60f7ad8f24e3147021489682f.

I suppose this issue should be a discussion about the release strategy to hub.docker.com. For me, this issue invalidated a weekends worth of tests and forced me off of upstream releases.

I'm curious. Was overriding the existing image tag intentional, or a mistake? Maybe there should be a better image tagging scheme that distinguishes which version of Selenium is installed AND which version of the browser!?

IMO, it's probably just better to not touch publicly published images. But, maybe, there's a difference of opinion!?

**Comment by ddavison** [comment]
there definitely is room for discussion, but the docker containers themselves are most of use when you build them yourselves.

in the StandaloneFirefox container, you are able to specify your own `FIREFOX_VERSION` and build it yourself.  

regarding the "touching publicly published images", there were many discrepancies found between the 2.53.1 and .0 release, and some images did not work at all, so they were pushed up.  it might've been a lack of foresight of updating the firefox version, but again - can be alleviated by building/using your own images pertinent to what your organization needs

**Comment by ddavison** [comment]
i will work on pushing that change to fix this firefox issue though - it is reproducible.  i'm not so versed in the firefox world, and i was organizing everything, and this version slipped through the cracks of testing.

**Comment by ddavison** [comment]
confirmed - switching back to 45.0.2 works with 2.53.0.  my apologies for this: you can monitor the build [here](https://travis-ci.org/SeleniumHQ/docker-selenium/builds/164742962).  if the tests pass (which before, they didn't. and again - was an oversight on my part.) then the 2.53.0 version will be rebuilt with that version of FF.  

keep in mind that again - you may build your own.  I will close this issue after it is pushed up.

**Comment by sanscore** [comment]
Cool, thanks for your time and response. With rolling internal images based off this repo, do you have any suggestions? 

Specifically, as far as having fixed versions is concerned? NodeFirefox has a fixed version (presumably because of compatibility issues with 47.0.0 and 48+), so that should be fairly straightforward. 

Chrome has the policy that after each new release, the previous version becomes unavailable. So, that would be a matter of staying aware of Chrome releases.

Any other concerns that jump out at you?

**Comment by ddavison** [comment]
ok, it's all pushed up.   well - like i said about firefox; i'm not too well-versed in the firefox world. i do most of my personal testing in chrome.  there are all kinds of incompatibilities with firefox and webdriver, especially now with geckodriver coming out only working on versions 49+ or whatever.. (see i don't even know what version it started :P)

it's hard to keep track of those.  i'll do a better job at asking the other committers on IRC if specific versions are compatible with the versions i release.

**Comment by sanscore** [comment]
Okay. Thanks, again, for the quick fix, and your responses have been informative and helpful.
