### ISSUE TITLE
Operation timed out after 30000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by nekulin** [SeleniumHQ/docker-selenium#297]
I often get this error, although I have a lot of free memory and kernel

**Comment by ddavison** [comment]
really no information for me to help you out.. what version are you using?  what images are you using?

**Comment by nekulin** [comment]
I think the problem is in the sites that they have not answered or not available

**Comment by ddavison** [comment]
ok cool, glad you figured it out!
