### ISSUE TITLE
browser.sleep(45) results in session timeout.

### ISSUE THREAD

**Issue by crocket** [SeleniumHQ/docker-selenium#30]
Thus, I can't make a browser sleep for 45 seconds.

Can you make it possible to pass -timeout and -browserTimeout options to selenium hub?

**Comment by mtscout6** [comment]
@crocket Does that satisfy your need?

**Comment by willroden** [comment]
Additionally, when #35 get's merged, you can run `docker run -e "GRID_TIMEOUT=120000" -e "GRID_BROWSER_TIMEOUT=120000" selenium/hub:2.44.0`

**Comment by crocket** [comment]
I think #35 can close the issue.

**Comment by mtscout6** [comment]
Closing, #35 should help you out.
