### ISSUE TITLE
Multi threading

### ISSUE THREAD

**Issue by nekulin** [SeleniumHQ/docker-selenium#301]
I want to run 30 browser simultaneously to work with them, but now if you connect to a single container then is one line of work, you cannot work with 2 sessions. Is it possible to run 2-3 copies on the same machine selenium ? And how better to launch a large number of browsers to manage all at the same time

**Comment by ddavison** [comment]
this functionality was released with `2.53.1-americium`. 

you can specify a node to run multiple browsers by passing in an environment variable to `node-chrome` or `node-firefox`.

Examples:

```bash
$ docker run -d --link selenium-hub:hub -e NODE_MAX_INSTANCES=10 -e NODE_MAX_SESSION=5 selenium/node-chrome:2.53.1-americium
```

bear in mind that the docker images are supposed to be minimal.  I haven't thoroughly tested the results in having a lot of browsers at the same time running in the same machine.  you might have to play with it.
