### ISSUE TITLE
Selenium Hub unable to connect to application

### ISSUE THREAD

**Issue by amitgaikwad85** [SeleniumHQ/docker-selenium#304]
## Meta -

Image(s):  
node-chrome
Docker Version:  
1.9.1

## Expected Behavior -

Selenium Node to connect to application with DNS entry.
## Actual Behavior -

I have pulled selenium/hub and selenium/node-chrome. The containers are working and the selenium testing also working. However the selenium is only connecting to http://<host>:<port>/App. not http://<DNSENTRY>/App

**Comment by ddavison** [comment]
what docker image versions are you using?

**Comment by amitgaikwad85** [comment]
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

**Comment by ddavison** [comment]
no, you are pulling selenium/node-chrome and selenium/hub.  what are the versions of THOSE images are you using?

2.53.1?  2.53.1-beryllium?  latest?

**Comment by amitgaikwad85** [comment]
its 2.53.1

**Comment by ddavison** [comment]
there's really not much for me to go on here.. you say "DNS entry" in your description, but don't provide, and you didn't specify the command you are using to run the docker containers, so i'm operating under the assumption right now that the DNS entry isn't being specified appropriately

**Comment by amitgaikwad85** [comment]
Let me put in more information

Docker Run commands:

docker run -d --name seleniumhub -p 4444:4444 selenium/hub
docker run -d -P --sig-proxy=true --link seleniumhub:hub selenium/node-chrome

I'm my code

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setBrowserName("chrome");
		capabilities.setPlatform(org.openqa.selenium.Platform.LINUX);
driver = new RemoteWebDriver(new URL("http://<DockerHost>:4444/wd/hub"),capabilities);

The issue is, when i try to connect to the applications say at http://test.domain.com/<applicationname>, it fails with the error http://test.domain.com/<applicationname> is not available"; however when run my program with http://10.0.0.1/<applicationname>, it runs successfully.

let me know if this helps.

**Comment by testphreak** [comment]
The IP of the host running the containers seems to be missing -

`driver = new RemoteWebDriver(new URL("http://:4444/wd/hub"),capabilities);`

**Comment by ddavison** [comment]
perhaps related to #238 ?

**Comment by diemol** [comment]
@amitgaikwad85, are you still having this issue? The container should pick the same DNS config as the host VM.

**Comment by amitgaikwad18** [comment]
@diemol , no i'm not facing this issue anymore

Thanks,
Amit

**Comment by diemol** [comment]
Thanks for reporting back, closing this issue.
