### ISSUE TITLE
How to setup docker containers to allow self-signed certs?

### ISSUE THREAD

**Issue by go2guy** [SeleniumHQ/docker-selenium#310]
I'm looking for a way to allow the browser to continue to my website URL that has a self-signed cert.

Locally I can add the exception to my JRE cacert with the following for local Selenium tests.

1.. keytool -import -alias {AliasName} -file ~/Desktop/{Certfile} -keystore $JAVA_HOME/jre/lib/security/cacerts
2.. Password change
3.. Answer yes

How do you allow self-signed certs in the docker containers?  

Image(s):  
Any
Docker Version:  
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
## Expected Behavior -

A way to to open the browser and self-signed certs.
## Actual Behavior -

Url is opened by needs to allow the self-signed cert to be accepted before URL endpoint is reached.

**Comment by zuernBernhard** [comment]
Perhaps you can use a browser profile that accepts the certificate

**Comment by nuggit32** [comment]
Yeah tried that and selenium test did not work but a manual test on the container did.

**Comment by ddavison** [comment]
perhaps related to #313 ?

**Comment by diemol** [comment]
@go2guy, if you were using Firefox and this is actually related to #313, the most recent image already has Firefox 53 that allows use insecure certificates. 

Could you please try again to use the additional [capability](https://github.com/mozilla/geckodriver#webdriver-capabilities) and report back to see how it went?

**Comment by diemol** [comment]
Closing this since we didn't get feedback and this issue was addressed in #518
