### ISSUE TITLE
dockerish/flexible docker tags

### ISSUE THREAD

**Issue by graingert** [SeleniumHQ/docker-selenium#312]
It would be great to support semverish tags eg:
# Current

latest -> 3.0.0-dubnium
# Proposed

latest -> 2.53.1
2.x.x -> 2.53.1
2.53.x -> 2.53.1
2.52.x -> 2.52.0
beta -> 3.0.0-dubnium
3.0.x -> 3.0.0-dubnium
3.x.x -> 3.0.0-dubnium

**Comment by graingert** [comment]
(using latest automatically upgraded me to the 3.0.0 beta releases, which broke my build)

**Comment by davehunt** [comment]
> (using latest automatically upgraded me to the 3.0.0 beta releases, which broke my build)

Selenium 3.0 is no longer in beta, and is considered the latest stable version.

**Comment by graingert** [comment]
Ok here's my new proposal: 

Current
======
latest -> 3.0.0-dubnium

Proposed
=====

latest -> 3.0.0
2.x.x -> 2.53.1
2.53.x -> 2.53.1
2.52.x -> 2.52.0
3.0.x -> 3.0.0
3.x.x -> 3.0.0

**Comment by davehunt** [comment]
Looks reasonable to me, though the '-dubnium' indicates docker image updates that do not change the Selenium version in use, so latest would still point to this.

**Comment by graingert** [comment]
is there an explanation of what -dubnium means anywhere?

**Comment by graingert** [comment]
Ok here's my new proposal: 

Current
======
latest -> 3.0.0-dubnium

Proposed
=====

latest -> 3.0.0-dubnium
2.53.1-x -> 2.53.1
2.53.x-x -> 2.53.1
2.52.x-x -> 2.52.0
2.x.x-x -> 2.53.1
3.0.0-x -> 3.0.0-dubnium
3.0.x-x -> 3.0.0-dubnium
3.x.x-x -> 3.0.0-dubnium

**Comment by davehunt** [comment]
> is there an explanation of what -dubnium means anywhere?

Not sure, but there should be. @ddavison?

**Comment by graingert** [comment]
can you switch to using +dubnium (-plus-) to comply with http://semver.org/#spec-item-9 and http://semver.org/#spec-item-10

**Comment by graingert** [comment]
I suspect most people will use 3.x.x-x or 2.x.x-x

**Comment by elgalu** [comment]
I think the "use -plus- +" comment was removed but just to leave it clear; it [doesn't seem to be supported by docker](https://github.com/docker/docker/issues/16304).

Regarding `3.x.x-x` or `2.x.x-x` maybe is the correct way but so many `x` (more than 2) reads awkward. I don't have a strong opinion on the subject though.

**Comment by graingert** [comment]
I removed the plus comment because it's wrong. You're not providing build
metadata it's transitive deps. For semver you need a different strategy

On 18 Oct 2016 13:25, "Leo Gallucci" <notifications@github.com> wrote:

I think the "use -plus- +" comment was removed but just to leave it clear;
it doesn't seem to be supported by docker
<https://github.com/docker/docker/issues/16304>.

Regarding 3.x.x-x or 2.x.x-x maybe is the correct way but so many x (more
than 2) reads awkward. I don't have a strong opinion on the subject though.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/SeleniumHQ/docker-selenium/issues/312#issuecomment-254491545>,
or mute the thread

**Comment by graingert** [comment]
Ok here's my new proposal: 

Current
======
latest -> 3.0.0-dubnium

Proposed
=====

latest -> 3.0.0-dubnium
2.53.1 -> 2.53.1
2.53 -> 2.53.1
2.52 -> 2.52.0
2 -> 2.53.1
3.0.0 -> 3.0.0-dubnium
3.0 -> 3.0.0-dubnium
3 -> 3.0.0-dubnium

**Comment by elgalu** [comment]
I like `v4`, looks more like the official docker approach to tags, e.g. https://hub.docker.com/_/python/

**Comment by graingert** [comment]
it's not semver at all, I'd clone the docker way of doing things

**Comment by ddavison** [comment]
> is there an explanation of what -dubnium means anywhere?
Not sure, but there should be. @ddavison?

dubnium is a chemical element.  I've created a [wiki page](https://github.com/SeleniumHQ/docker-selenium/wiki/Tagging-Convention) to explain the tagging convention of this repository.

I've been bitten in the past updating "recent" tags like this.  I definitely like the idea, but force pushing tags back up you run into the problem of breaking something that somebody else expects to work.

**Comment by graingert** [comment]
> I've been bitten in the past updating "recent" tags like this. I definitely like the idea, but force pushing tags back up you run into the problem of breaking something that somebody else expects to work.

which is what latest did to me. I want latest `2` for example

**Comment by ddavison** [comment]
the more i think about it, the more i do like it.  if it did break for somebody, they could always specify the 3.0.0-<element> version to make it remain unchanged.

3 and 3.0 would be good versions to push to docker tag as latest.. i do like this convention.

**Comment by graingert** [comment]
@ddavison is this something that will be applied going forward?

**Comment by ddavison** [comment]
@graingert the next release i'll work on it

**Comment by graingert** [comment]
Woop woop

**Comment by ddavison** [comment]
forgot to update you guys on this, [this is FIXED](https://hub.docker.com/seleniumhq)!

**Comment by graingert** [comment]
that's a link to a 404...
