### ISSUE TITLE
Missing Env NODE_MAX_INSTANCES & NODE_MAX_SESSION for NodeDebug images

### ISSUE THREAD

**Issue by niQo** [SeleniumHQ/docker-selenium#315]
as done in #295 , it wil be usefull to have the same environment variables in the NodeDebug images (NodeFirefoxDebug & NodeChromeDebug)

**Comment by diemol** [comment]
@niQo The NodeDebug images are created based on the NodeBase images, therefore those env vars are included by default.

**Comment by niQo** [comment]
@diemol you're right, it has been done. This issue can be closed.
