### ISSUE TITLE
Browser cannot displays my language

### ISSUE THREAD

**Issue by porsuv** [SeleniumHQ/docker-selenium#318]
I run the container on selenium hub, firefox, and chrome.
I saw the captured image that the browser cannot display my language correctly.
I think it is about encoding problem on specific language but English displayed correctly.
I am new to docker and not sure this is a bug or not ?

Can anyone help me on this issue ?

**Comment by HackToday** [comment]
maybe same requirements like this one https://github.com/SeleniumHQ/docker-selenium/issues/314

**Comment by diemol** [comment]
@porsuv which language?

**Comment by porsuv** [comment]
Previously I tested abd used Thai language.

**Comment by elgalu** [comment]
@porsuv you could try to figure out with Ubuntu package needs to be installed, see for example how this was done for japanese/chinese fonts: https://github.com/elgalu/docker-selenium/pull/153/files

Once you do that make sure to report here how much disk space it takes.

**Comment by kellinwood** [comment]
I ran into the same issue testing our website.   We discovered issues caused by missing fonts for japanese, chinese, korean, and thai in the stock selenium-docker images and worked around the problem by building custom docker images.  An example Dockerfile given is shown below:

```
# The stock selenium-docker images are missing some fonts required in order to properly 
# render all of the supported languages on our website. Install the following:

# fonts-ipafont-gothic fonts-ipafont-mincho # jp (Japanese) fonts, install seems to solve missing Chinese hk/tw fonts as well.
# ttf-wqy-microhei fonts-wqy-microhei       # kr (Korean) fonts
# fonts-tlwg-loma fonts-tlwg-loma-otf       # th (Thai) fonts

FROM selenium/standalone-chrome-debug
USER root
RUN apt-get update && \
    apt-get install -y \
        fonts-ipafont-gothic fonts-ipafont-mincho \
        ttf-wqy-microhei fonts-wqy-microhei       \
        fonts-tlwg-loma fonts-tlwg-loma-otf       \
    && apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
```

**Comment by diemol** [comment]
This should be solved in the latest release
https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.11.0-bismuth

Feel free to reopen in case the issue persists.
