### ISSUE TITLE
selenium/standalone-chrome-debug with --net=host flag fails

### ISSUE THREAD

**Issue by urban235** [SeleniumHQ/docker-selenium#320]
Docker Version:  1.12.2

Adding --net=host to Selenium standalone image so it would work with localhost, but the image fails:

➜  ~ docker run --net=host -ti selenium/standalone-chrome-debug
sudo: unable to send audit message: Operation not permitted
Waiting xvfb...
sudo: unable to send audit message: Operation not permitted
/opt/bin/entry_point.sh: line 32:    17 Segmentation fault      (core dumped) sudo -E -i -u seluser $(for E in $(grep -vxFf asseluser asroot); do echo $E=$(eval echo \$$E); done) DISPLAY=$DISPLAY xvfb-run -n $SERVERNUM --server-args="-screen 0 $GEOMETRY -ac +extension RANDR" java ${JAVA_OPTS} -jar /opt/selenium/selenium-server-standalone.jar ${SE_OPTS}
Waiting xvfb...
Waiting xvfb...
Waiting xvfb...
➜  ~

**Comment by diemol** [comment]
This issue was fixed in #459 
@ddavison this issue can be closed.
