### ISSUE TITLE
I am trying to scale a selenium/node-chrome-debug using the docker-compose. How do I expose host ports for the containers on the fly or some way to expose the host ports?

### ISSUE THREAD

**Issue by yashassai** [SeleniumHQ/docker-selenium#321]
## Meta -
Image(s):  

Docker Version:

**Comment by yashassai** [comment]
version: '2'
services :
hub:
image: selenium/hub
hostname: hub
ports:
- "4446:4444"
environment:
- no_proxy=localhost

chrome:
image: selenium/node-chrome-debug
hostname: chrome
links:
- hub
ports:
- "5901:5900"
environment:
- HUB_PORT_4444_TCP_ADDR=hub
- HUB_PORT_4444_TCP_PORT=4444

**Comment by ddavison** [comment]
just like the way youare doing, by specifying `ports:`.  the format you should be using is:

```yaml
ports:
  - "<container_port>:<host_port>"
```

that will publish `<container_port>` on the host's `<host_port>` port.

**Comment by yashassai** [comment]
When you do a `docker-compose up d` 
after that creates a hub and register the node.
Now you do `docker-compose scale chrome=4`
it creates an error and

**Comment by ddavison** [comment]
that's the way docker works, you are trying to expose 5901 several times.  what you need, is

```yaml
ports:
  - "5900"
```

then docker will select a random available port to publish that on.
