### ISSUE TITLE
Crash happening when run two web browsers

### ISSUE THREAD

**Issue by RomanGrekov** [SeleniumHQ/docker-selenium#322]
## Meta -
Image(s):  docker-selenium

Docker Version:  1.10.3

## Expected Behavior -
I am running my selenium tests inside the docker container https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneChrome
Everything goes well till the moment when I try to open two browsers in one container. When I open two browsers and try to go with some address, my test crashes. Webdriver shows next error:
`WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3),platform=Linux 4.2.0-42-generic x86_64)`

## Actual Behavior -
Webdriver doesn't crash when open two browser within the container

**Comment by ddavison** [comment]
have you seen https://github.com/SeleniumHQ/docker-selenium#running-the-images ?

**Comment by RomanGrekov** [comment]
It works!!! Thank you

**Comment by speedplane** [comment]
@ddavison I'm running into this bug. I can't allow the docker container to access shared memory for security reasons. Are there any other options?
