### ISSUE TITLE
Unable to use more than 20 nodes on Selenium Grid Hub

### ISSUE THREAD

**Issue by kuroiokami** [SeleniumHQ/docker-selenium#323]
## Meta -
Image(s):  

selenium/hub:2.53.1 
selenium/node-firefox-debug:2.53.1 
Docker Version:  

## Expected Behavior -
Able to fire up any number of nodes (within reason and hardware limits) and have it show up correctly on the hub.

## Actual Behavior -
Unable to get more that 20 FF nodes connected to the hub at once time (for a single server). If I start up more than 20 it doesn't show on the grid. On top of that if I start up a second server i can get another 20 added but when I run the test the grid acts if there are only 20 nodes (eventhough grid shows 40)

**Comment by kuroiokami** [comment]
Still don't totally understand the issue but upped the power of the server and was able to go above 20 now.

**Comment by ddavison** [comment]
> Still don't totally understand the issue

The issue is, is that these docker containers (as are *all* docker containerS) are meant to by tiny. they can be bigger, but yes - you have to share the resources from the host.

**Comment by kuroiokami** [comment]
Thanks for your feedback @ddavison ! I figured it was something like that but what determines how many you can fire up? Is there an X cpu / Xgb of ram that needs to be on each container before it restricts you? I couldn't find any information on this.

**Comment by ddavison** [comment]
> I couldn't find any information on this.

That's because it's "best guess" at this point 😜   there really isn't any statistics or benchmarks that are recorded yet for performance
