### ISSUE TITLE
Plans for node-edge and node-edge-debug images

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#326]
Are there plans for providing Docker images for running WebDriver tests against Edge browser similar to what we have currently for Chrome and Firefox? It looks like this should now be possible based on what I read here:

https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

Please correct me if I misread or misunderstood.

**Comment by elgalu** [comment]
AFAIK this is still true:

> what it's missing to achieve such thing is to have a Windows feature enabling to install the GUI within a windows container

https://github.com/Microsoft/Virtualization-Documentation/issues/214

**Comment by testphreak** [comment]
Thanks @elgalu. It's unfortunate that there's been no movement on that topic since June.

**Comment by smccarthy** [comment]
Looks to be closed as wont fix.

**Comment by webmutation** [comment]
Ping... does not appear to be something that will move forward.

**Comment by smccarthy** [comment]
This is not something the docker selenium project can add I believe.

**Comment by ddavison** [comment]
ok... i had spent several minutes last year replying to this message, and i never submitted it.

@smccarthy is right, for now.  I am monitoring the ability to run windows in a docker container.  for right now, this is not possible.  Just the same as Safari as we cannot run Safari without Mac.

(That's only paraphrasing what i actually said. i'm quite upset that i didn't click comment.)
