### ISSUE TITLE
Standalone-firefox-debug container does not start when linked to tomcat:7-jre8

### ISSUE THREAD

**Issue by tazle** [SeleniumHQ/docker-selenium#327]
## Meta -
Image(s):  standalone-firefox-debug
Docker Version:  2.53.1

## Expected Behavior -

Using Docker-composefile:

    app:
      image: tomcat:7-jre8

    selenium-server:
      image: selenium/standalone-firefox-debug:2.53.1
      links:
        - app:app

and running `docker-compose up`:

Expected Selenium server to start 

## Actual Behavior -

Selenium server fails with: `selenium-server_1 | -bash: 07E48665A34DCAFAE522E5E6266191C37C037D42: command not found`

The root cause is that tomcat:7-jre8 recently started using environment variables with spaces in the values, and the -debug versions of selenium containers do not do appropriate escaping when shuffling the environment so that it's available to the xvfb-run process even when it's run as a separate user.

It seems to me that the escaping mechanism should be fixed, or the environment variable passing mechanism limited to known variables if possible. The selenium container must not expect any particularly limited set of environment variables or values because it's usually used linked to another container, and because of docker leaks the environment of the linked container to the linking container.

**Comment by diemol** [comment]
@tazle did you move to Selenium 3? The issue was solved for new image versions, and I think it won't get fixed in the image version you were using.
Perhaps you can try the new image versions?

**Comment by tazle** [comment]
I think we moved away from the tomcat container.

**Comment by diemol** [comment]
Ah ok. Anyway, this issue with the spaces was solved in the recent releases by escaping the variables better.
Maybe you can try it or perhaps close the issue if it is not a problem anymore?

**Comment by ddavison** [comment]
closing, as assuming complete. we can reopen if need be!
