### ISSUE TITLE
What do the timeouts specified in dockerfile map to in the default hub configuration?

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#331]
## Meta -
Image(s):  
hub
Docker Version:  
2.53.x, 3.x

Seeing some timeout errors in our test runs. Would like to better understand each of these timeouts and the values to set.

Hub dockerfile - https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile
Default hub json - https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultHub.json

```
ENV GRID_NEW_SESSION_WAIT_TIMEOUT
ENV GRID_TIMEOUT
ENV GRID_BROWSER_TIMEOUT
ENV GRID_UNREGISTER_IF_STILL_DOWN_AFTER
```
Are each of these values in seconds or milliseconds? Also are these timeouts specified in the official [wiki](https://github.com/SeleniumHQ/selenium/wiki/Grid2) page?

**Comment by testphreak** [comment]
@ddavison, @elgalu, @kayabendroth could you provide some information regarding the timeouts above and if they are in seconds or milliseconds? 

My confusion stems from the fact that the hub dockerfile sets the `GRID_TIMEOUT` to 30000 where as the official wiki page for example sets the `-timeout` variable which I think this docker env variable maps to as 300 seconds.

I have asked a related question here - https://github.com/SeleniumHQ/selenium/issues/3071

**Comment by diemol** [comment]
Hi @testphreak,

I was checking both issues, and I was wondering if we need to keep both opened...
I see there was an answer on https://github.com/SeleniumHQ/selenium/issues/3071 but no more activity happened in none of the issues.

Do you know if there is anything pending? Perhaps we can close them.

**Comment by testphreak** [comment]
Hi @diemol, sure I'll close this one.
