### ISSUE TITLE
[node-firefox] Latest 3.0.1 build should run Firefox 50.0

### ISSUE THREAD

**Issue by alexgibson** [SeleniumHQ/docker-selenium#337]
## Meta -
Image(s):  
node-firefox

Docker Version:  
3.0.1-barium

## Expected Behavior -
build should contain `FIREFOX_VERSION=50.0`

## Actual Behavior -
build still contains `FIREFOX_VERSION=49.0.1`

Would it be possible to push a newer build to docker hub that runs Firefox 50.0?

**Comment by apascoal** [comment]
I had to downgrade the Firefox version to work with the Selenium 3.0.1.

**Comment by alexgibson** [comment]
Interesting, it seems to work for me. Can you link to what the issue is?

**Comment by alexgibson** [comment]
50.0 is in master, the commit is just not included in the new build: https://github.com/SeleniumHQ/docker-selenium/commit/31fbe36f54be9a88bc3c0842fdbd905cc3084ea3

**Comment by apascoal** [comment]
I had not created any issue with it, I have a stressful end of year.
On my PC it didn't work with the version I had of Firefox, and I downgraded the version on my PC and on the docker.

**Comment by alexgibson** [comment]
Ok, sounds like you just need to migrate your tests to use Marionette &a GeckoDriver. This does not have anything to do with this issue directly.

**Comment by ddavison** [comment]
can this issue be closed @alexgibson ? firefox version 50 is live in barium

**Comment by alexgibson** [comment]
The last build was 13 days ago, and as far as I can tell misses commit https://github.com/SeleniumHQ/docker-selenium/commit/31fbe36f54be9a88bc3c0842fdbd905cc3084ea3

**Comment by ddavison** [comment]
oh oh oh.. i see.  gotcha.  i'll pull a release sometime soon.  I guess it isn't live in barium :)

**Comment by ddavison** [comment]
released in carbon.
