### ISSUE TITLE
Can't seem to make a second session/test request to latest firefox node

### ISSUE THREAD

**Issue by marcmyers** [SeleniumHQ/docker-selenium#338]
## Meta -
Image(s):  
selenium/hub, selenium/node-firefox, and selenium/node-chrome
Docker Version:  
Docker version 1.12.3, build 6b644ec 

## Expected Behavior -
Ran each of these commands to bring up a small grid:
docker run -d -p 4444:4444 --name selenium-hub selenium/hub
docker run -d --link selenium-hub:hub selenium/node-firefox
docker run -d --link selenium-hub:hub selenium/node-chrome

Ran a very basic Selenium 3 smoke test in a Java project. Everything runs somewhat smoothly though Firefox took longer to ramp up.

When I attempt to run the tests a second time I expect them to both run again with no issues.

## Actual Behavior -
Second attempt to make a test request, Chrome runs the tests fine, Firefox appears to hang indefinitely until I kill the test process or the container/node itself.

Here's the console output from the node after making the second test request:

process 286: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
JavaScript error: https://dpm.demdex.net/ibs:dpid=96678&dpuuid=QGBj3eFaUZ6p, line 1: SyntaxError: illegal character
JavaScript warning: https://mathid.mathtag.com/device/id.js, line 1: unreachable code after return statement
JavaScript warning: https://mathid.mathtag.com/device/id.js, line 1: unreachable code after return statement
JavaScript warning: https://mathid.mathtag.com/device/id.js, line 1: unreachable code after return statement
JavaScript warning: https://mathid.mathtag.com/device/id.js, line 1: unreachable code after return statement
[Parent 209] WARNING: pipe error (54): Connection reset by peer: file /builds/slave/m-rel-l64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 316
2016-11-29T14:29:52.973584086Z 
###!!! [Parent][MessageChannel] Error: (msgtype=0x2C007A,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
2016-11-29T14:29:52.973641718Z 
1480429830997	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/49.0.1/20160922113459/Linux_x86_64-gcc3/en-US/release/Linux%204.4.27-moby%20(GTK%203.18.9%2Clibpulse%20not-available)/default/default/update.xml
1480429831315	addons.productaddons	INFO	Completed downloading document
1480429831789	addons.productaddons	INFO	downloadXHR File download. status=200
1480429831797	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
1480430369156	addons.manager	INFO	Skipping background update check
1480430609178	DeferredSave.extensions.json	DEBUG	Save changes
1480430609179	DeferredSave.extensions.json	DEBUG	Starting timer
1480430609203	DeferredSave.extensions.json	DEBUG	Starting write
1480430609210	DeferredSave.extensions.json	DEBUG	Write succeeded

I've tried starting and stopping the node between session/test requests but the issue persists. 

It may be worth noting that I can run these tests using Selenium 3 and the latest binaries for the browsers locally as many times as I need to with no issues, I only have this issue when I attempt to use the selenium docker grid.

Any help would be greatly appreciated.

**Comment by saifsysim** [comment]
I am facing the same issue using Hub 3.0.2 and Firefox 50.0.0.

**Comment by ddavison** [comment]
```sh
$ docker pull selenium/hub; docker pull selenium/node-chrome; docker pull selenium/node-firefox
$ docker run -d -p 4444:4444 --name selenium-hub selenium/hub
$ docker run -d --link selenium-hub:hub selenium/node-firefox
$ docker run -d --link selenium-hub:hub selenium/node-chrome
```

```java
public class Test338 {
  @Test
  public void test338() {
    doit();
  }

  @Test
  public void test338_1() {
    doit();
  }

  private void doit() {
    WebDriver chromeDriver = new ChromeDriver();
    WebDriver firefoxDriver = new FirefoxDriver();

    chromeDriver.get("http://google.com");
    firefoxDriver.get("http://google.com");

    System.out.println(chromeDriver.getTitle());
    System.out.println(firefoxDriver.getTitle());
  }
}
```

Couldn't reproduce.  Ran this test class several times, and was able to open firefox numerous times.

Please update with more detail, maybe something else is going on.
