### ISSUE TITLE
Cannot connect to VNC server

### ISSUE THREAD

**Issue by techjacker** [SeleniumHQ/docker-selenium#34]
Thanks for the great work with this repo.

I'm having trouble connecting to the VNC server to debug why my selenium tests are failing. I've tried with multiple vnc clients on both mac and linux but without joy. I've also tried connecting without SSL in case the certificate missing was the issue.

I've tried connecting to:
127.0.0.1:49155
localhost:49155
selenium-hub-ip:49155
selenium-chrome-debug-ip:49155

``` Shell
$ docker ps
CONTAINER ID        IMAGE                               COMMAND                CREATED              STATUS              PORTS                     NAMES
0e68a29b6bf8        selenium/node-chrome-debug:2.44.0   "/opt/bin/entry_poin   About a minute ago   Up About a minute   0.0.0.0:49155->5900/tcp   angry_brown         
6bab0f7039ab        selenium/hub:2.44.0                 "java -jar /opt/sele   58 minutes ago       Up About a minute   0.0.0.0:4444->4444/tcp    selenium-hub 
```

Any ideas where I'm going wrong?

**Comment by techjacker** [comment]
I managed to get it working by creating a [standalone debug image](https://github.com/techjacker/StandaloneChromeDebug).

Then I was able to connect to 0.0.0.0:49154 with VNCReal viewer.

**Comment by mtscout6** [comment]
Is the only difference here the base image set to the standalone chrome image?

**Comment by techjacker** [comment]
Yes and I also removed all the selenium grid stuff from [the boostrap script](https://github.com/techjacker/StandaloneChromeDebug/blob/master/entry_point.sh)

**Comment by ddavison** [comment]
are you still having this issue @techjacker ?

**Comment by techjacker** [comment]
Not tried it again since I posted that last commit two years ago

**Comment by ddavison** [comment]
alrighty - well i'll close this out.  feel free to reopen if you ever run into it again, or validate that you still can't

😃

**Comment by ivanm376** [comment]
>Remmina vnc
For Remmina you must setup _Color depth_ to _24 bit_ first
