### ISSUE TITLE
SCREEN_WIDTH dynamic

### ISSUE THREAD

**Issue by nekulin** [SeleniumHQ/docker-selenium#342]
Is there a way then to programmatically change the values ? I have started the container, I want to change the settings

/bin/sh /usr/bin/xvfb-run-n 99 --server-args=-screen 0 1360x1020x24

Where I understand that I can't use dynamically ? only one value for a single container ?

**Comment by ddavison** [comment]
you are able to specify:

- `SCREEN_WIDTH`
- `SCREEN_HEIGHT`
- `SCREEN_DEPTH`

> I understand that I can't use dynamically ? only one value for a single container ?

I'm really not sure what you are asking here.  you can change any of these values, and it will change the respective screen scale.  If by dynamic you mean changing the screen size after your node is running, then no, you cannot.  that would be how vnc is designed.

**Comment by nekulin** [comment]
it will be true ?

docker run-d --link selenium-hub:hub -e SCREEN_WIDTH=1024 SCREEN_HEIGHT=780 selenium/node-firefox:3.0.1-aluminum

**Comment by nekulin** [comment]
thank
