### ISSUE TITLE
Add Chrome Extensions

### ISSUE THREAD

**Issue by phibsholo** [SeleniumHQ/docker-selenium#343]
## Meta -
Image(s):  
node-chrome-debug

Docker Version:  
2.53.1

Hi,

I have a doubt, because I want to open chrome browser with some extensions and I don't find the properly way to do it. 

I'm using docker-compose with selenium/hub and selenium/node-chrome-debug that execute tests in another docker image.

Thanks.

**Comment by ddavison** [comment]
extensions are added before your `driver.get` method.

example:

```java
ChromeOptions options = new ChromeOptions();
options.addExtensions(new File("/path/to/extension.crx"));
ChromeDriver driver = new ChromeDriver(options);
```
([source](https://sites.google.com/a/chromium.org/chromedriver/capabilities))

This means, that in theory, adding extensions is possible.  (i have not personally done this as i have no need for extensions in my tests.)

You might be able to solve it by mounting the volume from the host, and the host has the .crx file, and point it to that crx file.

**Comment by phibsholo** [comment]
What do you mean when you say that I have to mount a volume in host? that means that I have to do a build in composer file using a Dockerfile that do this action?

**Comment by ddavison** [comment]
nope, by mounting a volume, i mean just specifying 

`-v /dev/shm:/dev/shm`

see [https://github.com/seleniumhq/docker-selenium#running-the-images](the readme).

**Comment by phibsholo** [comment]
OK!! thanks ;) I will try it

**Comment by phibsholo** [comment]
Sorry for the questions... but where is the extensions directory into chrome image? and I added the volume that you commented before but I don't understand why I have to do it, because I read that this volume is to share more host memory and I think that is not my currently problem.

**Comment by phibsholo** [comment]
This is my docker-compose.yml:

version: '2'

services:

  behat:
    image: bergil/docker-behat:v1.1.4
    container_name: behat_container
    environment:
      COMPOSER_UPDATE: 1
      HUB_PORT_4444_TCP_ADDR: hub
    restart: on-failure:5
    volumes:
      - ./behat/behat.yml:/srv/behat.yml
      - ./behat/features:/srv/features
      - ./behat/composer.json:/srv/composer.json
    depends_on:
      - hub

  hub:
    image: selenium/hub:2.53.1
    container_name: hub_container
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox-debug:2.53.1
    container_name: firefox_container
    ports:
      - "59000:5900"
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
    extends:
      file: docker-compose.local.yml
      service: custom_data

  chrome:
    image: selenium/node-chrome-debug:2.53.1
    container_name: chrome_container
    ports:
      - "59001:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      SE_OPTS: "-debug"
    extends:
      file: docker-compose.local.yml
      service: custom_data

**Comment by ddavison** [comment]
well that location is just an example of how to mount shared memory. you can mount any directory.

Say on your host machine, you have:

`/opt/selenium-shared/some-extension.xpi`

you could mount by doing:

`-v /opt/selenium-shared:/opt/selenium-shared`

then in your test, add

`options.addExtension('/opt/selenium-shared/some-extension.xpi')`.

since that folder is mounted, you could add as many as you'd like, or even update them.

**Comment by phibsholo** [comment]
I imagined that it was an example, but I didn't understood how to used it.  
The really thing that I didn't know it was to call options.addExtension('/opt/selenium-shared/some-extension.xpi'), when and where do it? because my tests are in behat extending mink, and I don't know how get chromeDriver that is usually using.

**Comment by ddavison** [comment]
i'm not sure - i've never used behat or mink.  it looks as if though, that this has traversed out of the realm of Selenium Docker, so i will close this issue.

My recommendation to you, is to take this issue up with one of those projects, and link this issue.

Search around and see if there is a "behat mink google chrome extension xpi" answer somewhere.  otherwise, ask one of those projects.

sorry i couldn't help you more!

**Comment by phibsholo** [comment]
OK, thanks a lot!! ;)

**Comment by deadnight7** [comment]
@ddavison - How would I pass in the arguments if the shared volume is mounted to the different directory?

I have issues in mapping Chrome Extension in Docker - It works locally.

I have it configured my dir like below, (Using a mac)
/Users/Shared-DirectoryLocalFolder/:/home/seluser/Downloads

Which path should I be passing in ChromeOptions?

Please help,
Thanks and Regards,
Chirag Pandit

**Comment by prashanth-sams** [comment]
@deadnight7 @phibsholo replace `'chromeOptions'` with `'goog:chromeOptions` to make this work [follow](https://devopsqa.wordpress.com/)

**Comment by deadnight7** [comment]
@prashanth-sams  thanks for the update, will check that out. Currently running on Chrome XVFB Session in Jenkins without docker
