### ISSUE TITLE
Sometimes Chrome does not start in debug images

### ISSUE THREAD

**Issue by mulyoved** [SeleniumHQ/docker-selenium#349]
## Meta -
Image(s):  chrome-debug-stable
Docker Version:  3.0.0-dubnium

## Expected Behavior -
Chrome should be started each time

## Actual Behavior -
Chrome is not started sometimes around 1 in 10 cases can duplicate it in automated testing environment by running multiple time until it happen

## Notes
- does not happen at all in chrome-stable, so think it is the VNC/vfb related issue 
- DBUS_SESSION_BUS_ADDRESS=/dev/null is set correctly
- host environment is not busy at all, ton of memory and cpu

## Attached
[chromedriver.log](https://github.com/SeleniumHQ/docker-selenium/files/657129/chromedriver.log.txt)
[env variables values](https://github.com/SeleniumHQ/docker-selenium/files/657599/env.txt)
[log of the container](https://github.com/SeleniumHQ/docker-selenium/files/657131/log-chubby-bone-main.txt)

**Comment by mulyoved** [comment]
there is a $100 bounty on this one http://codemill.io/task/585e88dbd2d2ba0004422923

**Comment by diemol** [comment]
@mulyoved could you please try with the most recent release? 3.4.0-Chromium
Let us know how it went.

**Comment by diemol** [comment]
Closing this issue as we didn't get feedback from the OP. Please re-open if more information is available.
