### ISSUE TITLE
XVFB with a graphics card.

### ISSUE THREAD

**Issue by nekulin** [SeleniumHQ/docker-selenium#351]
XVFB uses RAM, and if you put a graphics card then I think the memory will be spent much less ?

If you just add the video card and start the container, will it run the graphics card instead of XVFB ? start with XVFB

**Comment by elgalu** [comment]
But how?

**Comment by nekulin** [comment]
I want to optimize the consumption of RAM by graphics card

**Comment by diemol** [comment]
@nekulin can you please show how the graphics card could be put to the container? 
Otherwise, I think we should just close this issue.

**Comment by diemol** [comment]
No feedback from original poster, closing issue.
