### ISSUE TITLE
Unable to run rpsec tests with Selenium Hub 3.0.1-carbon images

### ISSUE THREAD

**Issue by ipai84** [SeleniumHQ/docker-selenium#352]
## Meta -
Image(s):  Hub, NodeChrome

Docker Version:  

We use dockerized Selenium Setup for our End to End framework built in Watir. We updated Selenium hub images to 3.0.1-carbon, Also updated the selenium-webdriver gem version to 3.0.3
## Expected Behavior -
Latest images should get pulled and tests should execute with latest images. 
## Actual Behavior -
Latest images get pulled, but unable to run tests , get the following error : Selenium::WebDriver::Error::UnknownError:
       Error forwarding the new session Empty pool of VM for setup Capabilities [{rotatable=false, nativeEvents=false, browserName=chrome, takesScreenshot=false, javascriptEnabled=true, version=, platform=ANY, cssSelectorsEnabled=true}] (org.openqa.grid.common.exception.GridException)
     # [remote server] org.openqa.grid.web.servlet.handler.RequestHandler(RequestHandler.java):113:in `process'
     # [remote server] org.openqa.grid.web.servlet.DriverServlet(DriverServlet.java):83:in `process'
     # [remote server] org.openqa.grid.web.servlet.DriverServlet(DriverServlet.java):67:in `doPost'
     # [remote server] javax.servlet.http.HttpServlet(HttpServlet.java):707:in `service'
     # [remote server] javax.servlet.http.HttpServlet(HttpServlet.java):790:in `service'
     # [remote server] org.seleniumhq.jetty9.servlet.ServletHolder(ServletHolder.java):808:in `handle'
     # [remote server] org.seleniumhq.jetty9.servlet.ServletHandler(ServletHandler.java):587:in `doHandle'
     # [remote server] org.seleniumhq.jetty9.server.session.SessionHandler(SessionHandler.java):221:in `doHandle'
     # [remote server] org.seleniumhq.jetty9.server.handler.ContextHandler(ContextHandler.java):1127:in `doHandle'
     # [remote server] org.seleniumhq.jetty9.servlet.ServletHandler(ServletHandler.java):515:in `doScope'
     # [remote server] org.seleniumhq.jetty9.server.session.SessionHandler(SessionHandler.java):185:in `doScope'
     # [remote server] org.seleniumhq.jetty9.server.handler.ContextHandler(ContextHandler.java):1061:in `doScope'
     # [remote server] org.seleniumhq.jetty9.server.handler.ScopedHandler(ScopedHandler.java):141:in `handle'
     # [remote server] org.seleniumhq.jetty9.server.handler.HandlerWrapper(HandlerWrapper.java):97:in `handle'
     # [remote server] org.seleniumhq.jetty9.server.Server(Server.java):499:in `handle'
     # [remote server] org.seleniumhq.jetty9.server.HttpChannel(HttpChannel.java):310:in `handle'
     # [remote server] org.seleniumhq.jetty9.server.HttpConnection(HttpConnection.java):257:in `onFillable'
     # [remote server] org.seleniumhq.jetty9.io.AbstractConnection$2(AbstractConnection.java):540:in `run'
     # [remote server] org.seleniumhq.jetty9.util.thread.QueuedThreadPool(QueuedThreadPool.java):635:in `runJob'
     # [remote server] org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3(QueuedThreadPool.java):555:in `run'
     # [remote server] java.lang.Thread(Thread.java):745:in `run'

This doest happen with 2.53.1 images.  This is urgent from a release perceptive, request you to look into this asap.

**Comment by diemol** [comment]
@ipai84 can you please try again with the latest release? Many improvements have been done both in Selenium and docker-selenium since you created this issue.

**Comment by diemol** [comment]
Closing this issue as we didn't get feedback from the OP. Please re-open if more information is available.
