### ISSUE TITLE
Selenium hub crashes when registering more than 70 nodes

### ISSUE THREAD

**Issue by macroking** [SeleniumHQ/docker-selenium#353]
## Meta -
Image(s):  hub: 3.0.1-aluminum

Docker Version:  
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

## Expected Behavior -
Should be able to register node to hub.

## Actual Behavior -
I have a Ubuntu machine in Microsoft Azure.  I tried spinning up chrome node depends on the number of automated tests available in Jenkins Job. When I started registering chrome nodes to the hub, it stopped working after 70+nodes.  Is it some limitation with the docker-selenium:hub image or the general functionality of selenium grid?

**Comment by madhavajay** [comment]
How much CPU and Ram?
I think its largely a CPU limitation, I cant effectively run more than about 50ish Chrome nodes on 16 cores, but I can run over 100 PhantomJS nodes on the same hardware. It doesnt need Selenium Standalone or Xvfb so its much lighter. But the Grid itself on the same machine seems to allow me to connect 200 PhantomJS nodes okay, so I dont think its the fault of the grid.

**Comment by ddavison** [comment]
that's correct, @madhavajay.  i've had the grid working with over 100 active sessions at once.  it all depends on the underline hardware.

**Comment by macroking** [comment]
Closing this, look like more of hardware configuration related.
