### ISSUE TITLE
Provide environment variable to use local custom firefox profile 

### ISSUE THREAD

**Issue by jkowalczyk** [SeleniumHQ/docker-selenium#359]
Firefox is started with a default profile, and there is now way to use a custom profile (to disable the "share location" popup for instance)

**Comment by ddavison** [comment]
that's correct - at this time, there is no way to use a custom profile. this definitely is within the scope of this project, and will eventually be done.

**Comment by ddavison** [comment]
actually - you know what?  I believe this is possible.

this is all theory, but i think would work -

```bash
$ docker run ... -v /some/local/profilesdir:/opt/selenium/profiles
```

then in your script, specify the directory in your test.

*note this is pseudo-code*
```java
...
ChromeOptions options = new ChromeOptions();
options.addArguments("user-data-dir=/opt/selenium/profiles/profile");
```

**Comment by jatinkapoor** [comment]
@ddavison is there a way to do so in chrome too ???

**Comment by rnemeth1980** [comment]
Using VMs starting the node I set the profile with “-Dwebdriver.firefox.profile=seleniumuser” for Selenium Grid.

Using Docker as I understand /opt/selenium/generate_config is used to configure the node.

echo "
{
  \"capabilities\": [
    {
      \"version\": \"$FIREFOX_VERSION\",
      \"browserName\": \"firefox\",
      \"maxInstances\": $NODE_MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    }
  ],
  \"proxy\": \"org.openqa.grid.selenium.proxy.DefaultRemoteProxy\",
  \"maxSession\": $NODE_MAX_SESSION,
  \"port\": $NODE_PORT,
  \"register\": true,
  \"registerCycle\": $NODE_REGISTER_CYCLE
  }
}" 

How do I set the firefox profile there?

I tried adding "webdriver.firefox.profile":"default" as suggested here http://grokbase.com/t/gg/selenium-users/14b69pd7q0/has-the-json-format-changed-for-grid-node-config-i-am-getting-an-error but
the container stops after a couple of seconds and I assume this addition is wrong and causing trouble.

Is there any progress on this topic? How can a custom firefox profile be set on the node?

Creating the profile inside the container accessing it via VNC and committing it to image is no problem, but this custom profile is never used by running tests.

Thank you for any help,
Roland

**Comment by diemol** [comment]
I wrote a [gist](https://gist.github.com/diemol/53ad9065686f4c330596725a8147aad5) with some useful info about this. I think @rnemeth1980 was able to use a custom profile at the end.

@jkowalczyk please check it and let us know, @rnemeth1980 also shared how he did it in the gist.

**Comment by ddavison** [comment]
If this works @diemol, feel free to add a wiki page regarding this

**Comment by diemol** [comment]
Hey @ddavison, 

I merged my gist and @rnemeth1980's comment into a wiki page here:
https://github.com/SeleniumHQ/docker-selenium/wiki/How-to-use-a-Firefox-custom-profile

After this, I think this issue could be closed, right?

**Comment by ddavison** [comment]
sweet!

**Comment by pumba-lt** [comment]
`-Dwebdriver.firefox.profile` does not work for me. Firefox still uses some temp profile:
```12:49:52.086 INFO - Capabilities are: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:firefoxOptions: {args: [], prefs: {}}}
12:49:52.088 INFO - Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:firefoxOptions: {args: [], prefs: {}}} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1517143792123	geckodriver	INFO	geckodriver 0.19.1
1517143792134	geckodriver	INFO	Listening on 127.0.0.1:12360
1517143792286	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.XaBBRVcr2xAW"
1517143792803	Marionette	INFO	Enabled via --marionette```

**Comment by pumba-lt** [comment]
At which point does `webdriver.firefox.profile` get set? I can't find such string anywhere in the `docker-selenium` codebase.
