### ISSUE TITLE
Use specific Firefox Version

### ISSUE THREAD

**Issue by mtscout6** [SeleniumHQ/docker-selenium#36]
Currently the docker image for firefox just gets the latest release of Firefox. Let's change that!

/cc @ericfrancis

**Comment by elgalu** [comment]
Agree, this is particularly relevant now: https://code.google.com/p/selenium/issues/detail?id=8390

**Comment by mtscout6** [comment]
Near as I can tell there's only two versions available for ubuntu. Unless I'm missing something.

```
root@4660bdde9f6d:/# apt-cache madison firefox
   firefox | 35.0+build3-0ubuntu0.14.04.2 | http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
   firefox | 28.0+build2-0ubuntu2 | http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

Since I'm hearing that 35.0 is not working right with Selenium 2.44.0, I'll go with 28.0 of firefox for now. Does anyone care or know of something else I should take into account?

**Comment by elgalu** [comment]
Agree @mtscout6 and the problem with that is that apt-cache will change eventually.
Another option is to trust [Firefox ftp archive](https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/) where [Firefox 34.0.5](https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/34.0.5/linux-x86_64/en-US/) is found but it requires the unpack/configure/make/install *nix flow.

**Comment by mtscout6** [comment]
That sounds more involved, but preferred since it opens the doors to more versions of firefox. Hmm, I'll have to think about this one for a bit.

**Comment by ericfrancis** [comment]
This is my Dockerfile with 33: https://github.com/ericfrancis/docker-selenium/blob/master/NodeFirefox33/Dockerfile

**Comment by mtscout6** [comment]
That doesn't look any more difficult to maintain than chrome driver, I like it!

**Comment by ericfrancis** [comment]
I'll look into ways to make this a little more dynamic. @elgalu brings up a good point regarding auto-updates being enabled by default. Searching briefly, there is a `-safe-mode` option that starts FF with extensions disabled as well as a `pref.js` file: https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences

**Comment by mtscout6** [comment]
Ah yes, the auto-update, I need to re-read issue threads again before commenting.

**Comment by wysow** [comment]
Hello,

Is this in WIP or should we try something about it?

And btw thanks a lot for this images guys!

**Comment by mtscout6** [comment]
It's still a work in progress. Other priorities at work have not allowed me to tackle this right away. Feel free to jump in if you think you can get a pull request that addresses all the concerns mentioned here.

**Comment by willroden** [comment]
How would the tags work for this?  I'm thinking something like this:
selenium/node-firefox:2.45.0_firefox37.0.2  points to firefox version 37.0.2.
selenium/node-firefox:2.45.0 points to stable firefox at build time.

**Comment by smccarthy** [comment]
I think this is taken care of with https://github.com/SeleniumHQ/docker-selenium/commit/670c94785b466139512c0e3d3db9f8ffa6dd812b ?

**Comment by diemol** [comment]
@smccarthy is right, that commit addressed this issue. Can someone close it?
