### ISSUE TITLE
node-firefox-debug crash trying to add certificate

### ISSUE THREAD

**Issue by avrelio** [SeleniumHQ/docker-selenium#362]
I launch an instance of firefox using webdriver-remote inside vncviewer; when going to import a certificate,  I select one; when clicking on the "import" button, firefox aborts; the log says:

(firefox:2369): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
WARNING: pipe error (3): Connection reset by peer: file /build/firefox-MkV0Xf/firefox-50.1.0+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 320
ABORT: Aborting on channel error.: file /build/firefox-MkV0Xf/firefox-50.1.0+build2/ipc/glue/MessageChannel.cpp, line 2056

Any workaround, please? Thanks

**Comment by diemol** [comment]
@avrelio could you tell us which image version were/are you using? I would like to reproduce the error.

**Comment by diemol** [comment]
Closing this issue as we didn't get feedback from the OP. Please re-open if more information is available.
