### ISSUE TITLE
Chinese garbled in node-firefox and node-chrome when screen shot

### ISSUE THREAD

**Issue by zhengchunxi** [SeleniumHQ/docker-selenium#367]
## Meta -
Image(s):  
selenium/node-firefox and selenium/node-chrome
Docker Version:  
3.0.1
OS: 
ubuntu 14.04 x86_64

## Expected Behavior -
Chinese show normal
## Actual Behavior -
Chinese garbled

I use my Physical device as a node,Chinese show normal
but use docker image, Chinese garbled

**Comment by elgalu** [comment]
probably related to #339

**Comment by individual-it** [comment]
same problem with Devanagari script
![image](https://user-images.githubusercontent.com/2425577/34718320-4bae844e-f55e-11e7-9016-b82328f64cb2.png)

**Comment by diemol** [comment]
This should be solved in the latest release
https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.11.0-bismuth

Somehow fonts were only being installed in the debug images, now they are available for both types of images.

Please reopen or comment if the issue persists.
