### ISSUE TITLE
When we try to scale using swarm, new services(nodes) which are scaled are being registered to (hub) with duplicate IP address.

### ISSUE THREAD

**Issue by abhisheksreepal** [SeleniumHQ/docker-selenium#368]
## Meta -
Image(s): **selenium/node-firefox-debug:latest and selenium/node-chrome-debug:latest and selenium/hub:latest**

Docker Version:  **Server Version: 1.13.0-rc7**

OS: **Ubuntu 16.04**

### Description: 
We have moved our grid setup from docker-compose to docker swarm to support multi host network. Here is below configs

We have created **docker-compose.yml** (Please refer file attached below as txt as file upload did not support **yml** extension)
[docker-compose.yml](https://github.com/SeleniumHQ/docker-selenium/files/711842/docker-compose.txt)

a) We have created docker swarm and have 1 leader and 3 slaves
b) Now **"docker stack deploy -c docker-compose.yml mystack"**
c) When we do **"docker service scale mystack_nodechrome=2"**, it is scaling but new service is registered with same IP as the first one which effectively cancels out the first one

## Expected Behavior -
New Services (nodes) on scale, should register with new IP

## Actual Behavior -
New Services (nodes) on scale, is registering with duplicate IP. Refer screenshot below
<img width="1427" alt="dockerswarm" src="https://cloud.githubusercontent.com/assets/1538269/22032904/6a76c3ac-dd0c-11e6-904c-eb1a45df8441.png">

**Comment by diemol** [comment]
@abhisheksreepal when I check the logs on the right bottom screen, I see:
`Cleaning up stale test sessions on the unregistered node http://10.0.0.2:5555`

This means that, for some reason, the node was unregistered from the hub. When the node notices that, it tries to register itself again, that is why you see again:
`Registered a node http://10.0.0.2:5555`

But it is not a duplicated IP address, it is the same node trying to register again and again. Check your setup, there is something making the node to get unregistered.

**Comment by abhisheksreepal** [comment]
Thanks @diemol for the reply. I am out on vacation.  Will check back once i am in.

Other Info:  For now, I have created my own image based on seleniumhq and modifed it to register using hub name instead.

**Comment by diemol** [comment]
Hey @abhisheksreepal,

Were you able to check your setup? Did it work?

Let us know, otherwise we can close this issue.

**Comment by abhisheksreepal** [comment]
@diemol, 
Verified my setup and i don't see anything which make node unregister. 

 For now, Please close the issue. Will try to investigate and update the same jira or create  new one

Thanks,
Abhishek

**Comment by diemol** [comment]
OK, let us know if how it went. 
Closing the issue for now then, please feel free to reopen if you find any more info.
