### ISSUE TITLE
FireFox Native Events

### ISSUE THREAD

**Issue by ahirreddy** [SeleniumHQ/docker-selenium#37]
I can't seem to enable native events when using Firefox Standalone. I've tried by creating a FireFox profile on the remote end and within the container, but I can't seem to get it to work. How does one go about doing this?

**Comment by diemol** [comment]
@ahirreddy 
I've document a way to do it, please check
https://gist.github.com/diemol/53ad9065686f4c330596725a8147aad5

If this is not needed anymore, please close this issue.

**Comment by ddavison** [comment]
no response for years. closing.
