### ISSUE TITLE
Wrong image versions in README.md

### ISSUE THREAD

**Issue by konfilios** [SeleniumHQ/docker-selenium#371]
In the README.md of the repository all the instructions refer to version `3.0.1-fermium` of the images which does not exist in the docker hub ( https://hub.docker.com/r/selenium/hub/tags/ ).

**Comment by ddavison** [comment]
yea - it's a botched release i tried to publish yesterday.  i'll try to spend some time on it today

**Comment by ddavison** [comment]
fixed
