### ISSUE TITLE
Support Google Chrome 56

### ISSUE THREAD

**Issue by wheleph** [SeleniumHQ/docker-selenium#383]
This a potential issue that may complicate upgrade of Google Chrome within the images.

I tried to rebuild `node-chrome` image based on RHEL-like OS instead of Ubuntu. I noticed that Google Chrome crashed inside of the new image. It turned out that the problem is related to Google Chrome version 56 and is present in "official" images also (i. e. if you rebuilt the image today you would see the same issue because of the newer version of the browser).

## Meta -
Image(s):  
selenium/node-chrome
Docker Version:  
1.12.3, build 6b644ec
OS: 
Ubuntu 16.04
```
$ uname -a
Linux wheleph-laptop 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

## Expected Behavior -
It's possible to upgrade Google Chrome to version 56 (the latest at the time of writing) inside selenium/node-chrome. The new version of the browser if fully functional.

## Actual Behavior -
After the upgrade Google Chrome cannot be started. It crashes with the following error:
```
seluser@d5109fb59a5f:/$ google-chrome --version
Google Chrome 56.0.2924.87 
seluser@d5109fb59a5f:/$ google-chrome
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Illegal instruction (core dumped)
seluser@d5109fb59a5f:/$  
```

**Comment by ddavison** [comment]
I believe this has been fixed, please try the new version and see if the problem persists.

**Comment by wheleph** [comment]
The new version of `node-chrome` image contains Google Chrome 56 which works well. The issue seem to be related not to the browser itself but rather to the installation process.

If I take the image and remove Google Chrome via `apt purge` and reinstall it via `apt install` I still get the following:

```
seluser@cf37c71c54b0:/$google-chrome
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Illegal instruction (core dumped)
seluser@cf37c71c54b0:/$ google-chrome --version
Google Chrome 56.0.2924.87 
```

But there's no issues with the "official" image so this one can be closed. But if you have any idea why I get the error, please let me know.

**Comment by elgalu** [comment]
@wheleph I managed to solved the `Failed to move to new namespace` issue by using [--no-sandbox](https://github.com/elgalu/docker-selenium#chrome-not-reachable-or-timeout-after-60-secs)

**Comment by wheleph** [comment]
The original issue I had with RHEL-like systems was due to missing fonts. Here's the solution:
```
yum install liberation-mono-fonts liberation-narrow-fonts liberation-sans-fonts liberation-serif-fonts
```
See http://stackoverflow.com/questions/41641546/chrome-fails-with-illegal-instruction-in-minimal-centos7xvfb and https://www.centos.org/forums/viewtopic.php?f=48&t=60908&sid=6e5b5c743f897b9b300fe69bbae36337&start=10#p257122 for more details
