### ISSUE TITLE
Base is 2.53.1 in 2.53.0

### ISSUE THREAD

**Issue by loganrenz** [SeleniumHQ/docker-selenium#387]
I noticed in my tests that there were conflicting versions in a stack trace. I checked on my end and I have everything pointed at 2.53.0, but I see here that base is updated 2.53.1. That doesn't seem right.

https://github.com/SeleniumHQ/docker-selenium/tree/2.53.0

**Comment by diemol** [comment]
@loganrenz true, seems that there was an issue with the version handling in that tag. 

Nevertheless, is this a big issue for you, or did you already move to Selenium 3? To be honest, I think that efforts should be put in newer versions instead of this little mistake :)

**Comment by ddavison** [comment]
yes, i took over this project at 2.53.1.  it's possible that i screwed up the 2.53.0 version from my testing

**Comment by diemol** [comment]
Closing it since it was just a little mistake that does not affect functionality at the end.
