### ISSUE TITLE
firefox issues

### ISSUE THREAD

**Issue by VarunEnishetty** [SeleniumHQ/docker-selenium#389]
## Meta -
Image(s):  
   hub, node-firefox-debug 
Docker Version:  
  1.13.0
OS: 
  windows 7

## Expected Behavior -
      Firefox should start executing the test case. 
## Actual Behavior -
     
![capture](https://cloud.githubusercontent.com/assets/25792749/22973085/95d5ea6c-f3a2-11e6-9b97-f4f5a6918e5d.PNG)

**Comment by diemol** [comment]
@VarunEnishetty Is this still an issue? Have you tried with the latest 3.3.1 images?
Could you please provide some text formatted logs instead of screenshots?

**Comment by diemol** [comment]
Closing the issue since we never got feedback from the OP.
