### ISSUE TITLE
Timeout seems to be too large

### ISSUE THREAD

**Issue by wheleph** [SeleniumHQ/docker-selenium#390]
## Meta -
Image(s):  
hub

## Actual Behavior -
The timeout value is 30000 (https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile.txt#L14). But Selenium assumes that the value is in seconds: https://github.com/SeleniumHQ/selenium/blob/b1c2cf6ceeab96856cf42feb4e84d2400a0a61eb/java/server/src/org/openqa/grid/internal/utils/configuration/StandaloneConfiguration.java#L194

As a result the hub waits for more than 8 hours before ditching stale client sessions. It might be better to set it to something lower like 30.

**Comment by ddavison** [comment]
good catch, would you want to try your hand at a pull request?
