### ISSUE TITLE
noce-chrome-debug VNC is not responding

### ISSUE THREAD

**Issue by arpadcseh** [SeleniumHQ/docker-selenium#398]
## Meta - 
Image(s):  
selenium/node-chrome-debug:3.1.0-astatine     
selenium/node-chrome:3.1.0-astatine 
selenium/node-base:3.1.0-astatine      
selenium/hub:3.1.0-astatine 
selenium/base:3.1.0-astatine   
(official latest images from this repo)

Docker Version:  
Docker version 1.6.2, build 7c8fca2/1.6.2
OS: 
Linux 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior -
successful connection through VNC viewer
## Actual Behavior -
connection can't established

I can't connect to node-chrome-debug image with VNC viewer. I even tried a simple wget 0.0.0.0:5904 it was refused and didn't show in the logs that there was a try. However node-firefox-debug works correctly with VNC and logs some messages when I try wget. Unfortunately I don't have any clue whats the issue :disappointed: Could you give me some advice? Do you see any issue in the logs below?
Thanks in advance!

## Outputs - 

**docker ps**
`ecc5baf38c4b selenium/node-chrome-debug:3.1.0-astatine "/opt/bin/entry_poin   36 minutes ago      Up 36 minutes  5900/tcp, 0.0.0.0:5904->5901/tcp   
25e3a9084879 selenium/hub:3.1.0-astatine "/opt/bin/entry_poin   36 minutes ago      Up 36 minutes       0.0.0.0:4447->4444/tcp`

**docker logs ecc5baf38c4b** 
`Waiting xvfb...
08:41:38.156 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
08:41:38.157 INFO - Launching a Selenium Grid node
23/02/2017 08:41:38 passing arg to libvncserver: -rfbport
23/02/2017 08:41:38 passing arg to libvncserver: 5900
23/02/2017 08:41:38 -usepw: found /root/.vnc/passwd
23/02/2017 08:41:38 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 127
23/02/2017 08:41:38 Using X display :99.0
23/02/2017 08:41:38 rootwin: 0x25c reswin: 0x200001 dpy: 0x1f52970
23/02/2017 08:41:38
23/02/2017 08:41:38 ------------------ USEFUL INFORMATION ------------------
23/02/2017 08:41:38 X DAMAGE available on display, using it for polling hints.
23/02/2017 08:41:38   To disable this behavior use: '-noxdamage'
23/02/2017 08:41:38
23/02/2017 08:41:38   Most compositing window managers like 'compiz' or 'beryl'
23/02/2017 08:41:38   cause X DAMAGE to fail, and so you may not see any screen
23/02/2017 08:41:38   updates via VNC.  Either disable 'compiz' (recommended) or
23/02/2017 08:41:38   supply the x11vnc '-noxdamage' command line option.
23/02/2017 08:41:38
23/02/2017 08:41:38 Wireframing: -wireframe mode is in effect for window moves.
23/02/2017 08:41:38   If this yields undesired behavior (poor response, painting
23/02/2017 08:41:38   errors, etc) it may be disabled:
23/02/2017 08:41:38    - use '-nowf' to disable wireframing completely.
23/02/2017 08:41:38    - use '-nowcr' to disable the Copy Rectangle after the
23/02/2017 08:41:38      moved window is released in the new position.
23/02/2017 08:41:38   Also see the -help entry for tuning parameters.
23/02/2017 08:41:38   You can press 3 Alt_L's (Left "Alt" key) in a row to
23/02/2017 08:41:38   repaint the screen, also see the -fixscreen option for
23/02/2017 08:41:38   periodic repaints.
23/02/2017 08:41:38
23/02/2017 08:41:38 XFIXES available on display, resetting cursor mode
23/02/2017 08:41:38   to: '-cursor most'.
23/02/2017 08:41:38   to disable this behavior use: '-cursor arrow'
23/02/2017 08:41:38   or '-noxfixes'.
23/02/2017 08:41:38 using XFIXES for cursor drawing.
23/02/2017 08:41:38 GrabServer control via XTEST.
23/02/2017 08:41:38
23/02/2017 08:41:38 Scroll Detection: -scrollcopyrect mode is in effect to
23/02/2017 08:41:38   use RECORD extension to try to detect scrolling windows
23/02/2017 08:41:38   (induced by either user keystroke or mouse input).
23/02/2017 08:41:38   If this yields undesired behavior (poor response, painting
23/02/2017 08:41:38   errors, etc) it may be disabled via: '-noscr'
23/02/2017 08:41:38   Also see the -help entry for tuning parameters.
23/02/2017 08:41:38   You can press 3 Alt_L's (Left "Alt" key) in a row to
23/02/2017 08:41:38   repaint the screen, also see the -fixscreen option for
23/02/2017 08:41:38   periodic repaints.
23/02/2017 08:41:38
23/02/2017 08:41:38 XKEYBOARD: number of keysyms per keycode 7 is greater
23/02/2017 08:41:38   than 4 and 51 keysyms are mapped above 4.
23/02/2017 08:41:38   Automatically switching to -xkb mode.
23/02/2017 08:41:38   If this makes the key mapping worse you can
23/02/2017 08:41:38   disable it with the "-noxkb" option.
23/02/2017 08:41:38   Also, remember "-remap DEAD" for accenting characters.
23/02/2017 08:41:38
23/02/2017 08:41:38 X FBPM extension not supported.
23/02/2017 08:41:38 X display is not capable of DPMS.
23/02/2017 08:41:38 --------------------------------------------------------
23/02/2017 08:41:38
23/02/2017 08:41:38 Default visual ID: 0x21
23/02/2017 08:41:38 Read initial data from X display into framebuffer.
23/02/2017 08:41:38 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5440
23/02/2017 08:41:38
23/02/2017 08:41:38 X display :99.0 is 32bpp depth=24 true color
23/02/2017 08:41:38
23/02/2017 08:41:38 Listening for VNC connections on TCP port 5900
23/02/2017 08:41:38 rfbListenOnTCP6Port: error in bind IPv6 socket: Address family not supported by protocol
23/02/2017 08:41:38 listen6: socket: Address family not supported by protocol
23/02/2017 08:41:38 (Ignore the above error if this system is IPv4-only.)
23/02/2017 08:41:38 Not listening on IPv6 interface.
23/02/2017 08:41:38
23/02/2017 08:41:38 Xinerama is present and active (e.g. multi-head).
23/02/2017 08:41:38 Xinerama: number of sub-screens: 1
23/02/2017 08:41:38 Xinerama: no blackouts needed (only one sub-screen)
23/02/2017 08:41:38
23/02/2017 08:41:38 fb read rate: 1146 MB/sec
23/02/2017 08:41:38 fast read: reset -wait  ms to: 10
23/02/2017 08:41:38 fast read: reset -defer ms to: 10
23/02/2017 08:41:38 The X server says there are 10 mouse buttons.
23/02/2017 08:41:38 screen setup finished.
23/02/2017 08:41:38

The VNC desktop is:      ecc5baf38c4b:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
2017-02-23 08:41:38.571:INFO::main: Logging initialized @809ms
08:41:38.613 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
08:41:38.613 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
08:41:38.613 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:41:38.613 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
08:41:38.614 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:41:38.614 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
08:41:38.614 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-02-23 08:41:38.646:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-02-23 08:41:38.668:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@353d0772{/,null,AVAILABLE}
2017-02-23 08:41:38.680:INFO:osjs.ServerConnector:main: Started ServerConnector@6ca8564a{HTTP/1.1}{0.0.0.0:5555}
2017-02-23 08:41:38.680:INFO:osjs.Server:main: Started @919ms
08:41:38.681 INFO - Selenium Grid node is up and ready to register to the hub
08:41:38.687 INFO - Starting auto registration thread. Will try to register every 5000 ms.
08:41:38.688 INFO - Registering the node to the hub: http://172.17.10.108:4444/grid/register
08:41:38.737 INFO - The node is registered to the hub and ready to use
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.screen0.slit.acceptKdeDockapps
Setting default value
Failed to read: session.screen0.slit.autoHide
Setting default value
Failed to read: session.screen0.slit.maxOver
Setting default value
Failed to read: session.screen0.slit.placement
Setting default value
Failed to read: session.screen0.slit.alpha
Setting default value
Failed to read: session.screen0.slit.onhead
Setting default value
Failed to read: session.screen0.slit.layer
Setting default value
Failed to read: session.screen0.toolbar.autoHide
Setting default value
Failed to read: session.screen0.toolbar.maxOver
Setting default value
Failed to read: session.screen0.toolbar.visible
Setting default value
Failed to read: session.screen0.toolbar.alpha
Setting default value
Failed to read: session.screen0.toolbar.layer
Setting default value
Failed to read: session.screen0.toolbar.onhead
Setting default value
Failed to read: session.screen0.toolbar.placement
Setting default value
Failed to read: session.screen0.toolbar.height
Setting default value
Failed to read: session.screen0.iconbar.mode
Setting default value
Failed to read: session.screen0.iconbar.alignment
Setting default value
Failed to read: session.screen0.iconbar.iconWidth
Setting default value
Failed to read: session.screen0.iconbar.iconTextPadding
Setting default value
Failed to read: session.screen0.iconbar.usePixmap
Setting default value
08:41:48.907 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000`

**Comment by arpadcseh** [comment]
Oh my bad!! :smile: I've forwarded the wrong port

`docker run -d --link selenium-hub-3.1.0:hub  -v /dev/shm:/dev/shm --name "selenium-chrome-debug-3.1.0" -p 5904:5901 selenium/node-chrome-debug:3.1.0-astatine`

After changing 5901 to 5900 it works correctly!

**Comment by luckytaxi** [comment]
Im running into the same issue but I'm using `docker-compose`. This used to work but one day it just stopped working.
