### ISSUE TITLE
How to build with FF 47.0.1?

### ISSUE THREAD

**Issue by rafaferreira** [SeleniumHQ/docker-selenium#404]
Hi there,

I would like to rebuild the images but using a different version of FF (**47.0.1**), seems to be easy but I'm facing issues and I would like a help if possible.

What I did was simple: download the raw file of Docker files (**StandaloneFirefoxDebug**) and tried to build the image, example:

```
$ wget https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/master/StandaloneFirefoxDebug/Dockerfile
$ docker build -t stand-alone-firefox-debug-4701 .
```

Then the build **failed** as I don't have entry_point.sh so I downloaded from (StandaloneFirefox):

```
 wget https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/master/StandaloneFirefox/entry_point.sh
```

and tried again the build that works fine. But I can't connect into VNC.

Maybe the key thing is: Is it correct to get the entry_point.sh from StandaloneFirefox instead of StandaloneFirefox**Debug**?

Any help would be appreciated, my frameworks did not work with the latest version of FF so I need to guarantee that I can build on my end, the next step is to try to build: **NodeFirefox** where I can change the version to what I need.

**Comment by ddavison** [comment]
we have a [wiki page](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images#specify-chromedriver-and-chrome-versions) that details how you can build your own images, but that is building using our make file.

if you want to build yourself using `docker build`, you are able to just convert the commands found in the wiki page above into bare docker build parameters.

**Comment by rafaferreira** [comment]
Amazing, I'll give a try. Thanks for now!

------------------------------------
Rafael C. Ferreira
Mobile: +1 669 221 9549 (USA)

**Comment by ddavison** [comment]
will close, let me know if we need to reopen 👍
