### ISSUE TITLE
Docker hub selenium/standalone-chrome-debug build is failing for 6 months

### ISSUE THREAD

**Issue by Sovetnikov** [SeleniumHQ/docker-selenium#406]
Docker hub selenium/standalone-chrome-debug build is failing for 6 months, please fix it.
https://hub.docker.com/r/selenium/standalone-chrome-debug/builds/

**Comment by enolan** [comment]
Looking at the build logs, `entry_point.sh` is missing. Is it as simple as rerunning `generate.sh`?

**Comment by ersuniljoshi** [comment]
+1, I am also facing the same issue

**Comment by ersuniljoshi** [comment]
Fixed for FF and Chrome: https://github.com/SeleniumHQ/docker-selenium/pull/419

**Comment by diemol** [comment]
The release is done in Travis now through the Makefile present in the root folder, the build in the docker hub is obsolete now.
@ddavison I think we just need to deactivate the option in the docker hub, right?
After that, I think, this issue and #419 can be closed.

**Comment by diemol** [comment]
I just reviewed the configuration in the docker hub and there were still some repos linked between them, which was triggering the builds over there. I removed them and now the builds are done only in Travis.
