### ISSUE TITLE
Newer versions of Firefox have dropped some libraries ; breaks older versions

### ISSUE THREAD

**Issue by awilkins** [SeleniumHQ/docker-selenium#415]
## Meta -
Image(s):  Firefox

Docker Version:  17-03, 3.0.1-germanium

OS: 
Ubuntu 16.04

## Expected Behavior -

* Set FIREFOX_VERSION to 45.0.2
* Build images
* Testing on the image works

## Actual Behavior -

* XPCOMGlueLoad error

Shelling the docker container and checking library links reveals...

```
# Removed libraries that were actually found

seluser@eaf279429169:/opt/firefox-45.0.1$ ldd libxul.so 
	libmozsqlite3.so => not found
	liblgpllibs.so => not found
	libasound.so.2 => not found

```

Theory : Firefox 52 (the version you get now if you `apt-get install firefox` on Ubuntu) has dropped dependencies on these libraries.

Therefore the Dockerfile behaviour of installing the latest version of Firefox to get the dependencies isn't sound if you're not building the latest version.

Possible solutions : 
- Have the script read through the apt cache and find the available version that's closest to the version you specified in FIREFOX_VERSION, and install that instead.

On Ubuntu 16.04 (the base of the image) this is limited to versions 45.0.2 and 52 at present. Maybe work out which version of Firefox dropped these libraries and pick one either side of that divide.

Happily I wanted Firefox 45 (my target user base is trapped in a government-sponsored time warp).

What I actually did :
- Patched the Dockerfile for the base image to specifically install Firefox 45.0.2+build1-0ubuntu1

**Comment by awilkins** [comment]
Success : built an image that runs Firefox 45 properly.

**Comment by gangadharahn** [comment]
Hi,

I am also trying to build firefox images for lower versions, could please tell me the changes you did on base?

Thanks for your help in advance.

Regards,
Ganga

**Comment by awilkins** [comment]
The change I did was to look up the available package versions of Firefox for the base 16.04 version of Ubuntu that's used for the Docker base image, and change the Dockerfile template to specifically install that version instead of latest.

e.g. 

```
&& apt-get -qqy --no-install-recommends install firefox=45.0.2+build1-0ubuntu1 \
```

Given there's a FIREFOX_VERSION environment variable, I guess it should detect versions under 52 and make this change to the file - or define another variable like FIREFOX_DEPENDENCY_PACKAGE_VERSION and set that to latest or that version 45 depending.

**Comment by ddavison** [comment]
possibly related to #418

**Comment by diemol** [comment]
Hi all,

Is this still an issue? I mean, are there many scenarios where people are testing with a Firefox version lower than 52?

**Comment by diemol** [comment]
Hi all,

We didn't get more feedback on this, so I'll close the issue. If something related pops up, please comment so we can check it and reopen (please provide enough information).

**Comment by dorner** [comment]
Seeing this issue here. Trying to dockerize an older application which uses a *really* old version of Firefox (18) and seeing the same error mentioned above:
```
XPCOMGlueLoad error for file /opt/firefox-18.0/libxpcom.so:
libxul.so: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by cgoldberg** [comment]
@dorner firefox-18.0 is way too old and not compatible with current geckodriver.

**Comment by dorner** [comment]
Actually it worked just fine when I followed the instructions @awilkins suggested. :)

**Comment by awilkins** [comment]
It occurs to me that manually adding instructions to install those missing dependencies in addition to the latest firefox package to the dockerfile may make it work for older versions (without the hackery I suggested) but don't have time to test that.
