### ISSUE TITLE
How to create node image with down graded browser version

### ISSUE THREAD

**Issue by gangadharahn** [SeleniumHQ/docker-selenium#416]
Could please help in creating the node version having lower versions of Firefox and Chrome.

We wanted to test the applications in lower browser version like Firefox 49, 50 and 51. how and where to modify the images to downgrade the browser versions

**Comment by zypherman** [comment]
You should be able to modify the browser version inside the docker file so you can use the image locally. Then build the image and name is something different so you know its your new version after you built it. You will have to make sure you can still copy this file into your image https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefox/generate_config for firefox. For chrome you will need https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/chrome_launcher.sh as well as that config script. So probably easiest to just check the entire project out locally and build the images with docker inside the project directories.

**Comment by gangadharahn** [comment]
Thanks for your help, now i am able build the images

**Comment by ddavison** [comment]
we have a [wiki page](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images) that is dedicated to building images :)
