### ISSUE TITLE
How to create multiple chrome instance (not the sessions) in selenium chrome node docker container?

### ISSUE THREAD

**Issue by Dhananjayulu** [SeleniumHQ/docker-selenium#428]
- [ ##

 Meta -
Image(s):  

Docker Version:  

OS:

**Comment by tparikka** [comment]
@Dhananjayulu You can do this by setting the NODE_MAX_INSTANCES environment variable. If you're using docker run you would include the arguments:

`-e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5`

replacing the number 5 with however many browser instances you want to permit. If you're using docker-compose you would include this in the compose for your node-chrome service:

```
environment:
 - NODE_MAX_INSTANCE=5
 - NODE_MAX_SESSION=5
```

You can see these environment variables defined at the [Dockerfile of standalone-chrome](https://hub.docker.com/r/selenium/standalone-chrome/~/dockerfile/). There is information about how these values work [on this Stackoverflow post](https://stackoverflow.com/questions/13723349/selenium-grid-maxsessions-vs-maxinstances) and in the [docs for Selenium Grid](https://seleniumhq.github.io/docs/grid.html) (they work the same, Docker just changes how you pass the parameters into the node). I also found [this Stackoverflow ](https://stackoverflow.com/questions/30494050/how-to-pass-environment-variables-to-docker-containers)article to be a good reference for writing startup scripts that use docker run without having to type in the entire command every time. If you have more questions reply and tag me and I'll try to answer. I'm also learning this as I go :-)

**Comment by Dhananjayulu** [comment]
Awesome. Suggestion worked well with both docker run and docker-compose!

Thanks very much @tparikka

**Comment by tparikka** [comment]
You're welcome! If all your questions are answered can you please close this GitHub issue? Thanks!

**Comment by ddavison** [comment]
thanks @tparikka :)

**Comment by JonathanHosea** [comment]
Just in case anyone is having trouble getting the above suggestion to work, I was able to get this to work using:

environment:
 - NODE_MAX_INSTANCES=5
 - NODE_MAX_SESSIONS=5
