### ISSUE TITLE
Is selenium-hub /chrome node supports Watir and page objects gems ?

### ISSUE THREAD

**Issue by Dhananjayulu** [SeleniumHQ/docker-selenium#433]
Issue: Chrome is not lunching in chrome nod (Docker container) Watir browser Capabilities, but works well when I tried with Selenium::WebDriver. 

**here is the hooks file looks like:**

**Watir ( not working with Watir)** 

require 'watir'
require 'selenium-webdriver'

Before do

    caps = {
       :browserName => "Chrome"
     }
 
   @browser = Watir::Browser.new(:remote,
       :url => 'http://localhost:4444/wd/hub/',
       :desired_capabilities => caps)
end

**Selenium WebDriver (works well with Selenium Webdriver)**
require 'watir'
require 'selenium-webdriver'

Before do

 caps=Selenium::WebDriver::Remote::Capabilities.chrome
    @browser = Selenium::WebDriver.for(:remote,
                                      :url => 'http://localhost:4444/wd/hub/',
                                      :desired_capabilities => caps)

end

**Please help me**

**Comment by ddavison** [comment]
Watir is just a wrapper around Selenium, and we support everything Selenium does.

You didn't follow the format of the [GitHub Issue Template](https://github.com/seleniumhq/docker-selenium/blob/master/.github/ISSUE_TEMPLATE.md) so i can't tell from this issue what the actual error is. 

More likely than not - you probably don't have any nodes connected to the hub

**Comment by ddavison** [comment]
@titusfortner (for your edification)

**Comment by Dhananjayulu** [comment]
Thank for clarification!
