### ISSUE TITLE
Unable to pull latest image of selenium/node-phantomjs 

### ISSUE THREAD

**Issue by dforrest88** [SeleniumHQ/docker-selenium#434]
I am unable to pull the latest tag of the node-phantomjs image. Others have also left comments on Docker Hub that they are experiencing the same problem.

`dforrest-ltm:.ssh dforrest$ docker pull selenium/node-phantomjs
Using default tag: latest
Error response from daemon: manifest for selenium/node-phantomjs:latest not found
dforrest-ltm:.ssh dforrest$ docker pull selenium/node-phantomjs:3.3.0
3.3.0: Pulling from selenium/node-phantomjs
d54efb8db41d: Already exists 
f8b845f45a87: Already exists 
e8db7bf7c39f: Already exists 
9654c40e9079: Already exists 
6d9ef359eaaa: Already exists 
a625bef0200c: Already exists 
3dddcf35f68a: Already exists 
eb9f893a00c6: Already exists 
dc6729d226ab: Already exists 
eb04bdaf2d92: Already exists 
432207f77286: Already exists 
391beaadc81f: Already exists 
cf0fbccee83c: Already exists 
67c06c482753: Pull complete 
7786d2c6ae80: Pull complete 
3aef9650962e: Pull complete 
8a326f0d7571: Pull complete 
c0d8bfc7f2b1: Pull complete 
b033a07f3a35: Pull complete 
fa3da498d633: Pull complete 
0c24c76e86cd: Pull complete 
Digest: sha256:53654b81b93ffc5a7d081063b29df05aeb63242f86d657ba917a4efba8bcb37e
Status: Downloaded newer image for selenium/node-phantomjs:3.3.0`

**Comment by marten-cz** [comment]
I'll push fix tonight.

**Comment by marten-cz** [comment]
@ddavison Can you please try to build phantomjs image and pushed it docker hub? This issue should be fixed.

**Comment by ddavison** [comment]
should be fixed with 3.3.1-cesium (if it's not, we'll reopen)
