### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownCommandException] mouseMoveTo

### ISSUE THREAD

**Issue by bscheshirwork** [SeleniumHQ/docker-selenium#435]
## Meta -
Image(s):  
standalone-firefox
Docker Version:  Docker version 17.03.0-ce, build 60ccb22
OS: Ubuntu 16.04
## Expected Behavior -
mouse move
## Actual Behavior -
unknown command mouseMoveTo
https://github.com/Codeception/Codeception/issues/4104

**Comment by diemol** [comment]
As mentioned in https://github.com/Codeception/Codeception/issues/4104#issuecomment-291508538, it is a problem related to the Firefox driver, not related to docker-selenium.

@bscheshirwork can you please close this issue?
