### ISSUE TITLE
CONTRIBUTING.md Points To Selenium Archive Page

### ISSUE THREAD

**Issue by tparikka** [SeleniumHQ/docker-selenium#439]
Not related to code at all.

The CONTRIBUTING.md file currently points at https://code.google.com/p/selenium/wiki/CommitYourCode, which redirects to the Google Code Issue Archive at https://github.com/seleniumhq/selenium-google-code-issue-archive. Assuming that the correct location for up to date contributor guidelines is [CONTRIBUTING.md at the parent Selenium project](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md), I have a PR prepared that updates it. Can anyone confirm that it is the correct URL first?

**Comment by ddavison** [comment]
Yes absolutely.  i'd definitely like if it were to be pointing to https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md

**Comment by ddavison** [comment]
fixed from #440
