### ISSUE TITLE
3.3.1

### ISSUE THREAD

**Issue by bscheshirwork** [SeleniumHQ/docker-selenium#442]
So... Its new release for hub.docker.com?
 7 days ago
3.3.1-arsenic 

3.3.0 version won't work properly with latest Firefox/Geckodriver.

**Comment by DerFlatulator** [comment]
See #430

**Comment by tparikka** [comment]
@bscheshirwork As said above, there's already an issue open for the 3.3.1 build issues. Are you looking for help specifically with 3.3.0 and Firefox/Geckodriver as well, or can this be closed as duplicate of issue 430?

**Comment by ddavison** [comment]
duplicate of #430
