### ISSUE TITLE
"java.lang.NullPointerException"

### ISSUE THREAD

**Issue by vgoklani** [SeleniumHQ/docker-selenium#446]
I ran the following

    docker run -d -p 4444:4444 -e JAVA_OPTS=-Xmx512m --name selenium-hub selenium/hub

opened a browser on my mac with this link: http://127.0.0.1:4444/wd/hub

and saw this:

		{
		status: 13,
		value: {
		class: "java.lang.NullPointerException",
		stackTrace: [
		{
		fileName: "ExternalSessionKey.java",
		className: "org.openqa.grid.internal.ExternalSessionKey",
		methodName: "fromWebDriverRequest",
		lineNumber: 77
		},
		{
		fileName: "WebDriverRequest.java",
		className: "org.openqa.grid.web.servlet.handler.WebDriverRequest",
		methodName: "extractSession",
		lineNumber: 58
		},
		{
		fileName: "RequestHandler.java",
		className: "org.openqa.grid.web.servlet.handler.RequestHandler",
		methodName: "getSession",
		lineNumber: 231
		},
		{
		fileName: "RequestHandler.java",
		className: "org.openqa.grid.web.servlet.handler.RequestHandler",
		methodName: "process",
		lineNumber: 117
		},
		{
		fileName: "DriverServlet.java",
		className: "org.openqa.grid.web.servlet.DriverServlet",
		methodName: "process",
		lineNumber: 83
		},
		{
		fileName: "DriverServlet.java",
		className: "org.openqa.grid.web.servlet.DriverServlet",
		methodName: "doGet",
		lineNumber: 61
		},
		{
		fileName: "HttpServlet.java",
		className: "javax.servlet.http.HttpServlet",
		methodName: "service",
		lineNumber: 687
		},
		{
		fileName: "HttpServlet.java",
		className: "javax.servlet.http.HttpServlet",
		methodName: "service",
		lineNumber: 790
		},
		{
		fileName: "ServletHolder.java",
		className: "org.seleniumhq.jetty9.servlet.ServletHolder",
		methodName: "handle",
		lineNumber: 841
		},
		{
		fileName: "ServletHandler.java",
		className: "org.seleniumhq.jetty9.servlet.ServletHandler",
		methodName: "doHandle",
		lineNumber: 543
		},
		{
		fileName: "ScopedHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ScopedHandler",
		methodName: "nextHandle",
		lineNumber: 188
		},
		{
		fileName: "SessionHandler.java",
		className: "org.seleniumhq.jetty9.server.session.SessionHandler",
		methodName: "doHandle",
		lineNumber: 1584
		},
		{
		fileName: "ScopedHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ScopedHandler",
		methodName: "nextHandle",
		lineNumber: 188
		},
		{
		fileName: "ContextHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ContextHandler",
		methodName: "doHandle",
		lineNumber: 1228
		},
		{
		fileName: "ScopedHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ScopedHandler",
		methodName: "nextScope",
		lineNumber: 168
		},
		{
		fileName: "ServletHandler.java",
		className: "org.seleniumhq.jetty9.servlet.ServletHandler",
		methodName: "doScope",
		lineNumber: 481
		},
		{
		fileName: "SessionHandler.java",
		className: "org.seleniumhq.jetty9.server.session.SessionHandler",
		methodName: "doScope",
		lineNumber: 1553
		},
		{
		fileName: "ScopedHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ScopedHandler",
		methodName: "nextScope",
		lineNumber: 166
		},
		{
		fileName: "ContextHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ContextHandler",
		methodName: "doScope",
		lineNumber: 1130
		},
		{
		fileName: "ScopedHandler.java",
		className: "org.seleniumhq.jetty9.server.handler.ScopedHandler",
		methodName: "handle",
		lineNumber: 141
		},
		{
		fileName: "HandlerWrapper.java",
		className: "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
		methodName: "handle",
		lineNumber: 132
		},
		{
		fileName: "Server.java",
		className: "org.seleniumhq.jetty9.server.Server",
		methodName: "handle",
		lineNumber: 564
		},
		{
		fileName: "HttpChannel.java",
		className: "org.seleniumhq.jetty9.server.HttpChannel",
		methodName: "handle",
		lineNumber: 320
		},
		{
		fileName: "HttpConnection.java",
		className: "org.seleniumhq.jetty9.server.HttpConnection",
		methodName: "onFillable",
		lineNumber: 251
		},
		{
		fileName: "AbstractConnection.java",
		className: "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
		methodName: "succeeded",
		lineNumber: 279
		},
		{
		fileName: "FillInterest.java",
		className: "org.seleniumhq.jetty9.io.FillInterest",
		methodName: "fillable",
		lineNumber: 112
		},
		{
		fileName: "ChannelEndPoint.java",
		className: "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
		methodName: "run",
		lineNumber: 124
		},
		{
		fileName: "QueuedThreadPool.java",
		className: "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
		methodName: "runJob",
		lineNumber: 672
		},
		{
		fileName: "QueuedThreadPool.java",
		className: "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
		methodName: "run",
		lineNumber: 590
		},
		{
		fileName: "Thread.java",
		className: "java.lang.Thread",
		methodName: "run",
		lineNumber: 745
		}
		]
		}

What am I doing wrong?

**Comment by diemol** [comment]
@vgoklani 
That is the correct output for that url.

If you want to see the grid console, go to http://127.0.0.1:4444/grid/console
