### ISSUE TITLE
Does StandaloneChrome image allows popups?

### ISSUE THREAD

**Issue by scythargon** [SeleniumHQ/docker-selenium#448]
## Meta -
Image(s):  
StandaloneChrome
Docker version 17.03.0-ce, build 60ccb22
OS: 
Ubuntu 16.10 (Yakkety Yak)

Hi! I open page that opens popup via window.open and I could not access this popup - it does not appear in `driver.window_handles`

**Comment by tparikka** [comment]
I believe you should be able to access popups in the Chrome Standalone container just like if it was a local instance. What version of the container are you using? I.e. 3.3.1, 3.3.0, etc. Which Selenium bindings are you using and what code are you using to call into the handle list?

**Comment by diemol** [comment]
I'll close this issue since we didn't get feedback from the OP. Feel free to reopen when more accurate info is provided.
