### ISSUE TITLE
/wd/hub/status returns 500

### ISSUE THREAD

**Issue by peterebden** [SeleniumHQ/docker-selenium#454]
## Meta -
Image(s):  
standalone-chrome
Docker Version:  
3.3.0
OS: 
Ubuntu 16.04

## Expected Behavior -
`curl http://localhost:4444/wd/hub/status` returns 200, as it did in older versions (e.g. 3.2.0)

## Actual Behavior -
`curl http://localhost:4444/wd/hub/status` returns 500 and the following:
```
{"state":"unknown error","sessionId":null,"hCode":1747075273,"value":{"localizedMessage":"wrong number of arguments","cause":null,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"suppressed":[],"message":"wrong number of arguments","hCode":1198549837,"class":"java.lang.IllegalArgumentException"},"class":"org.openqa.selenium.remote.Response","status":13}
```

**Comment by diemol** [comment]
@peterebden that is a bug in Selenium 3.3.0, which was fixed in Selenium 3.3.1.
