### ISSUE TITLE
Node*Debug variable for VNC port

### ISSUE THREAD

**Issue by apakhomov** [SeleniumHQ/docker-selenium#457]
Hi!

I've moved to docker net=host configuration and it works well with headless containers. However there is a problem to launch multiple original debug images as vnc port is hardcoded in entry_point:

x11vnc -forever -usepw -shared -rfbport 5900 -display $DISPLAY &

Is there a chance of moving it to variables?

**Comment by ddavison** [comment]
the port that the container uses shouldn't matter.

you can forward the port to any port you want.  for example:

```sh
$ docker run -d -P --net=something --link selenium-hub:hub selenium/node-chrome
abcd1234
```

when you specify `-P`, docker will take any exposed ports from the container, and assign them a random port to the host.

**Comment by apakhomov** [comment]
> the port that the container uses shouldn't matter.
In case of net=host it matters. I don't want to use custom network, port forwarding, nat as it's overhead for my case. I use host's network stack directly and it works until I need to launch more than 1 container with vnc. This is one of the cases I need to use custom images instead of official

**Comment by diemol** [comment]
True, when the network is the host this wouldn't work. Maybe you would like to submit a PR @apakhomov ?

**Comment by diemol** [comment]
After leaving this open for a while, no one showed interest or the need for this feature. Therefore I'll close it.
In case someone wants to contribute, feel free to comment and we'll reopen it to discuss it.
