### ISSUE TITLE
Add PhantomJS support.

### ISSUE THREAD

**Issue by aholtventuretech** [SeleniumHQ/docker-selenium#46]
Should really add support for PhantomJS containers.

I have an active pull request for this issue:  https://github.com/SeleniumHQ/docker-selenium/pull/38

This is an issue due to the need to potentially pull this image from the public docker registry as selenium/node-phantomjs:2.44.0

Currently have this image pushed through a different account (venturetech/node-phantomjs:2.44.0), but would like to keep all of the node images with the same naming convention within my scripts.

**Comment by ddavison** [comment]
this is definitely something I would like to do.  would you mind submitting a pull request?  if not, i'll get to it myself eventually

**Comment by aholtventuretech** [comment]
I submitted a pull request for this issue when I created the issue:  #38

**Comment by ddavison** [comment]
oh perfect!  thanks - i'll close this in favor of #38
