### ISSUE TITLE
geckodriver v0.16 is recommended for selenium v3.4.0

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#466]
## Meta -
Image(s):  
node-firefox, node-firefox-debug, standalone-firefox, standalone-firefox-debug

##
I see a few test failures with Firefox and would like to eliminate the possibility of the failures being due to an older geckodriver.

- According to the [changelog posted](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG) for selenium v3.4.0, geckodriver v0.16 is recommended. The latest 3.4.0 firefox image available has v0.15
- Would be great if the Firefox is upgraded as well to [v53](https://www.mozilla.org/en-US/firefox/53.0/releasenotes/). Latest image has v52.0.2.

**Comment by lmtierney** [comment]
The releases of 3.4 and geckodriver 0.16 were coordinated together so it is best they are used together.

**Comment by manoj9788** [comment]
This can be closed

**Comment by testphreak** [comment]
@manoj9788 sure will close this. Unfortunately Firefox keeps crashing inside the containers #468, which makes the new image unusable.
