### ISSUE TITLE
Chrome DBus

### ISSUE THREAD

**Issue by vv-p** [SeleniumHQ/docker-selenium#473]
## Meta -
Image(s):  
standalone-chrome-debug:3.3.1-cesium
Docker Version:  
Docker version 1.12.6, build 3a094bd/1.12.6
OS: 
CentOS Linux release 7.3.1611 (Core) 

According to https://github.com/SeleniumHQ/docker-selenium/issues/87#issuecomment-297645284 is it possible to auto-detect dbus socket on host machine and setting up the DBUS_SESSION_BUS_ADDRESS with it ?

**Comment by ddavison** [comment]
the next release of the containers should fix this.  i'll try and release today

**Comment by ddavison** [comment]
should be fixed in 3.4.0-chromium
