### ISSUE TITLE
Implement New Test Suite

### ISSUE THREAD

**Issue by ddavison** [SeleniumHQ/docker-selenium#476]
I will be rewriting the tests to use Python instead of NodeJS.

*Reasoning*:  
1. None of the maintainers now use NodeJS.
2. The current suite is not scalable (for new images)
3. The current suite does not seem maintainable (see reason 1)
4. The current suite uses `wd`.  a third party binding

### Checklist

- [x] Create Test Framework
- [x] Write smoke test for Hub
- [x] Write smoke and selenium test for NodeChrome
- [x] Write smoke and selenium test for NodeFirefox
- [ ] Write smoke and selenium test for NodePhantomJS
- [x] Write smoke and selenium test for StandaloneChrome
- [x] Write smoke and selenium test for StandaloneChromeDebug
- [x] Write smoke and selenium test for StandaloneFirefox
- [x] Write smoke and selenium test for StandaloneFirefoxDebug

**Comment by diemol** [comment]
Implemented via #579
