### ISSUE TITLE
Firefox ignores desiredCapabilities proxy settings

### ISSUE THREAD

**Issue by tnguyen14** [SeleniumHQ/docker-selenium#478]
## Meta -
Image(s):  
standalone-firefox, standalone-firefox-debug
Docker-Selenium Image Version(s):  
3.1.0
OS: 
RHEL 7.3

With the following proxy settings:
```js
desiredCapabilities: {
  proxy: {
    proxyType: 'manual',
    httpProxy: 'proxy.corp.com:8080',
    sslProxy: 'proxy.corp.com:8080',
    noProxy: 'localhost'
  } 
}
```

## Expected Behavior -
The browser session will use the proxy settings

## Actual Behavior -
Proxy is not observed in Firefox. It works when using the chrome versions however (`standalone-chrome` and `standalone-chrome-debug`).

**Comment by diemol** [comment]
@tnguyen14 
Googling for a while, I realised that the proxy attributes are not the same for Chrome and Firefox (at least now). Check https://github.com/mozilla/geckodriver#proxy-object for the correct ones. 

For example, in Chrome you pass `httpProxy: 'proxy.corp.com:8080'`, but it seems that in Firefox you need to pass: `{httpProxy: "proxy.corp.com", httpProxyPort: 8080}`.

**Comment by tnguyen14** [comment]
@diemol  I just tried your suggestion, but that doesn't seem to make a difference.

**Comment by diemol** [comment]
@tnguyen14 my suggestion was more to check how Geckodriver expects the proxy info in the capabilities, did yo check that?

**Comment by tnguyen14** [comment]
@diemol From searching around, I found the same results that you mentioned, i.e. `httpProxy` and `httpProxyPort` as separate properties.

**Comment by diemol** [comment]
@tnguyen14 exactly, so I think you need to reflect that in your code. Basically Firefox profiles have different properties. It is not an issue of docker-selenium I think.

**Comment by diemol** [comment]
@tnguyen14 exactly, so I think you need to reflect that in your code. Basically Firefox profiles have different properties. It is not an issue of docker-selenium I think.

**Comment by tnguyen14** [comment]
Right. And when I updated the properties to use those specific to firefox, it still did not work.

**Comment by diemol** [comment]
Perhaps you can post that problem here and reference this issue? https://github.com/mozilla/geckodriver 
Since it seems clearly related to the Firefox options.

**Comment by tnguyen14** [comment]
I just looked at the options again, and it seems like they don't support the `noProxy` option anymore? Do you know if there's a different way to set that?

**Comment by diemol** [comment]
Not really, I have never used Firefox profiles in that way. I just noticed that the settings are different from Chrome profiles.
Maybe it is better to ask them directly❓

**Comment by tnguyen14** [comment]
I asked the question in https://github.com/mozilla/geckodriver/issues/725

**Comment by tnguyen14** [comment]
I was told that `webdriver` does not support `noProxy`, so I raised it in https://github.com/w3c/webdriver/issues/913

**Comment by tnguyen14** [comment]
One thing I've noticed is that the `node-firefox` version will respect environment variables set for http_proxy and no_proxy, but the `node-firefox-debug` version will not. What do you think might cause this difference?

**Comment by diemol** [comment]
@tnguyen14 that should get fixed when #477 gets solved.

Aside from that, it seems that the `noProxy` thing is being handled in the issue you raised at the w3c project. 

Since this is not a docker-selenium issue, could you please close this issue?

Thanks!

**Comment by tnguyen14** [comment]
Thanks @diemol. Any estimate on when you think #477 will land?

**Comment by diemol** [comment]
@ddavison is working on having better tests so #477 can be merged together. That is a very important task and good tests take time sometimes, so we just need to have some patience :)

**Comment by tnguyen14** [comment]
@diemol I've also seen Chrome not respecting the http proxy environment variables as well (the proxy settings in webdriver works though). Is that a known issue as well?

**Comment by tnguyen14** [comment]
@diemol should I file a separate issue for Chrome?

**Comment by tnguyen14** [comment]
From https://github.com/mozilla/geckodriver/issues/725#issuecomment-327216744

>This is all done now and will be available with Firefox 57 and the next release of geckodriver.

I'm reopening this issue for now. Please close it when there's a `docker-selenium` release that includes the fixed geckodriver version.

**Comment by ddavison** [comment]
does the latest push release fix this?  3.5.3

**Comment by diemol** [comment]
I'll close this issue since the latest Geckodriver is in the most recent release and we didn't get feedback from the OP.

**Comment by lmtierney** [comment]
From what I understand, geckodriver & Firefox do not yet support the proxy passed in via capabilities and the only way to get it to do so is to create a Firefox profile with the proxy set and then use that profile

**Comment by diemol** [comment]
OK, then I'll reopen it and double check.

**Comment by tnguyen14** [comment]
I am trying to look into this again, using the latest version `3.7.1`, and I'm getting this error

```
Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ value:
   { sessionId: 'c272b552-69f2-4b6e-a9fb-550a23994d63',
     capabilities:
      { 'moz:profile': '/tmp/rust_mozprofile.zcKX5Nlyq169',
        rotatable: false,
        timeouts: [Object],
        pageLoadStrategy: 'normal',
        'moz:headless': false,
        proxy: [Object],
        'moz:accessibilityChecks': false,
        acceptInsecureCerts: false,
        browserVersion: '57.0',
        platformVersion: '4.9.49-moby',
        'moz:processID': 342,
        browserName: 'firefox',
        platformName: 'linux',
        'moz:webdriverClick': false } } }```

I know it's probably something really simple, but I can't figure out why. I am running with the `node-firefox-debug` image, and when I open the VNC viewer, I can see the browser window being opened, though the browser URL bar is empty. 

If I switch the same setup , but just the browser name to `chrome`, it works fine.

**Comment by diemol** [comment]
I just re-read the whole thread again, and if I understand correctly:
- The specification was changed so 'noProxy' was supported via https://github.com/w3c/webdriver/issues/913
- Geckodriver and Marionette implemented it via https://github.com/mozilla/geckodriver/issues/725
- @tnguyen14 tested it and found that the Java bindings used handle it as a string but the spec details it as a list, which is being handled in https://github.com/SeleniumHQ/selenium/issues/5004

From my point of view, seems that we can close this issue here and just follow up on the last issue I linked above.
What do you think @tnguyen14?

PS: @tnguyen14 good job by going all the way and triggering the change in the spec!

**Comment by tnguyen14** [comment]
Thanks for the summary!

I can't confirm that firefox now works with the `desiredCapabilities` object yet, because I can't get nightwatch to connect to selenium. However, if others can confirm that this now works on their Firefox setup, I'm happy to close this.

**Comment by diemol** [comment]
@tnguyen14 I am confused, is the whole `desiredCapabilities` not working with Firefox? Or is it just the `proxy` part of it? Isn't that being tracked on SeleniumHQ/selenium#5004?

**Comment by diemol** [comment]
That looks like Nightwatch cannot connect to the url where Selenium Grid is.
But we are drifting away from the original issue...

To get back to it, I created this small [test](https://github.com/diemol/docker-selenium-issues/blob/master/issue-478/src/test/java/com/elementalselenium/RunWithProxyTest.java). It shows that setting a proxy works, but there is still the issue of `noProxy` (which is being handled here SeleniumHQ/selenium#5004).

If you want to run the test, checkout the repo, go into the folder and run: 

```
docker-compose -f docker-compose.yaml up --abort-on-container-exit --build
```

First go to https://api.ipify.org, and check your IP, then go into the container via VNC and check that the IP shown is different from yours. You can try it with a different proxy if you want (I got that one from https://free-proxy-list.net/). 


This shows that setting the proxy options works, except `noProxy` (again, which is being handled here SeleniumHQ/selenium#5004). Therefore, I think this is not a docker-selenium issue anymore.

**Comment by tnguyen14** [comment]
Thanks @diemol. I'll close this now.

Just to confirm, if you set `noProxy` to [`localhost`], it works, right?

**Comment by diemol** [comment]
@tnguyen14 no, it does not work (in Java at least), that is what I meant by saying that the `noProxy` issue is being handled in SeleniumHQ/selenium#5004. Please subscribe to that issue for updates.
