### ISSUE TITLE
selenium/node-firefox-debug trying to load some addons and freezes

### ISSUE THREAD

**Issue by eino-makitalo** [SeleniumHQ/docker-selenium#483]
## Meta -
Image(s):  selenium/node-firefox-debug

Docker-Selenium Image Version(s):  latest

OS: 
Host machine: ubuntu but docker in use

## Expected Behavior -
Not downloading any addons when using docker image of selenium/node-firefox-debug
## Actual Behavior -
Freezes and then shows in screen 
"1494517195363	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/53.0/20170414022702/Linux_x86_64-gcc3/en-US/release/Linux%204.4.0-75-generic%20(GTK%203.18.9%2Clibpulse%20not-available)/default/default/update.xml
firefox_1        | 1494517196009	addons.productaddons	INFO	Completed downloading document
firefox_1        | 1494517196261	addons.productaddons	INFO	downloadXHR File download. status=200
firefox_1        | 1494517196263	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
"

**Comment by ddavison** [comment]
I'm not sure when / wh yyou'd be seeing this.  I'm certainly not getting this.  When running `docker run -it -p 5900:5900 --link selenium-hub:hub selenium/node-firefox-debug`, i get [this output](https://gist.github.com/ddavison/1f52de7a5375fd4e2ab9dc48380a142d)

**Comment by ddavison** [comment]
try sharing your invocation with us so we can see if something else is going on here.

**Comment by eino-makitalo** [comment]
Yes, my firefox hangs up in first page of application... then nothing happens.
I have took template from https://github.com/Eficode/Docker-Selenium-Example
Chrome goes nice


[docker-compose.test.yml.txt](https://github.com/SeleniumHQ/docker-selenium/files/1000890/docker-compose.test.yml.txt)
[firefoxHangsExample.txt](https://github.com/SeleniumHQ/docker-selenium/files/1000893/firefoxHangsExample.txt)

**Comment by diemol** [comment]
Hi @eino-makitalo,

In the template you mention, I don't see that the containers are started with the host's shared memory mounted (`-v /dev/shm:/dev/shm`, this is now needed for Firefox as well), see [here](https://github.com/SeleniumHQ/docker-selenium#running-the-images) 

Are you trying that when you start the docker-selenium?

**Comment by persifal** [comment]
was the same problem with selenium. tried to download pdf\pdfx and was dying. Solved it with added ability to autodownload that files:
```groovy
profile.setPreference("browser.download.dir", System.getProperty("java.io.tmpdir"))
profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/pdf,application/x-pdf")
```

**Comment by diemol** [comment]
Closing as we didn't get feedback from the OP.
