### ISSUE TITLE
Error checking TLS connection: Machine does not have a host-only adapter

### ISSUE THREAD

**Issue by baozhida** [SeleniumHQ/docker-selenium#484]
on windows 7 , I set bridge type. there is an error when start default docker machine.

only host-only adapter can use？ 

now only my window can connect hub.

How other windows at  same network connect hub （http://192.168.99.100:4444/grid/console）？

**Comment by diemol** [comment]
Hi @baozhida,

I am guessing that you want to access the grid from other host, and you are using docker with virtual box in Windows 7. If that is correct, this should help you https://stackoverflow.com/questions/33814696/how-to-connect-to-a-docker-container-from-outside-the-host-same-network-windo

Else, I would suggest you to research that, it mostly sounds like a docker configuration that needs to be adjusted on your host. Not really a docker-selenium issue.

**Comment by diemol** [comment]
Closing this issue since we didn't get feedback from the OP.
