### ISSUE TITLE
NoSuchSessionException

### ISSUE THREAD

**Issue by khalistan** [SeleniumHQ/docker-selenium#486]
**Hello, I am getting following error while running tests with docker slaves.**

> org.openqa.selenium.NoSuchSessionException: no such session
> (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 16 milliseconds
> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
> System info: host: 'cf0700220c99', ip: '172.17.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.2.2.el7.x86_64', java.version: '1.8.0_121'
> Driver info: org.openqa.selenium.chrome.ChromeDriver
> Capabilities [{message=unknown error: Chrome failed to start: crashed
> (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64), platform=ANY}]
> Session ID: 232948004c7606aa1ae73296281ea607

**I have tried to set** shm size upto 1.0G and also to set export DBUS_SESSION_BUS_ADDRESS=/dev/null but still getting same error.
**I have also tried this:**

> sudo rm -f /var/lib/dbus/machine-id
> sudo mkdir -p /var/run/dbus
> sudo service dbus restart
> service dbus status
> export $(dbus-launch)
> export NSS_USE_SHARED_DB=ENABLED

**I run docker:**

> docker run -d --name jenkins-slave ecom/jenkins-slave -master "http://192.168.38.100:8080" -username "Admin" -password "admin" -executors "20" -name "localhost" -labels "webtest" -deleteExistingClients

**My docker file:**

> FROM jenkinsci/jenkins
> 
> USER root
> 
> RUN apt-get update \
> 	&& curl -sL https://deb.nodesource.com/setup_7.x | bash - \
> 	&& apt-get install -y wget expect nodejs locales xvfb dbus 	\
> 	&& npm install -g backstopjs
> 
> ARG CHROME_VERSION="google-chrome-stable"
> RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
>   && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
>   && apt-get update -qqy \
>   && apt-get -qqy install \
>     ${CHROME_VERSION:-google-chrome-stable} \
>   && rm /etc/apt/sources.list.d/google-chrome.list \
>   && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
> 
> 
> ARG CHROME_DRIVER_VERSION=2.29
> RUN wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip \
>   && rm -rf /opt/selenium/chromedriver \
>   && unzip /tmp/chromedriver_linux64.zip -d /opt/selenium \
>   && rm /tmp/chromedriver_linux64.zip \
>   && mv /opt/selenium/chromedriver /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION \
>   && chmod 755 /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION \
>   && ln -fs /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION /usr/bin/chromedrive
> 
> 
> RUN rm -rf /var/lib/apt/lists/* /var/cache/
> 
> USER jenkins

**Comment by diemol** [comment]
Hi @khalistan,

Can you please post the docker run instruction to see how you start docker-selenium? Also, which image are you using?

**Comment by diemol** [comment]
@khalistan thanks for the info.

But it seems that you are using a complete different image, from your docker run:
`docker run -d --name jenkins-slave ...`

Also from your docker-file:
`FROM jenkinsci/jenkins`

I think you are not using this project, am I right? Perhaps you need to post the issue in the correct project.

**Comment by khalistan** [comment]
I am not Docker guy. I am just Selenium guy :) Can you still help me? Please

**Comment by diemol** [comment]
I would recommend to read first the [README](https://github.com/SeleniumHQ/docker-selenium) of the project and also check the [wiki](https://github.com/SeleniumHQ/docker-selenium/wiki) to get started.

In general, the images provided should be ready for you to use.

After going through that, if you still have problems, please create an issue with the specific problem and a way to reproduce it.

**Comment by ddavison** [comment]
closing this issue, as it does not pertain to our images.
