### ISSUE TITLE
Support Chrome Sandboxing on Ubuntu 

### ISSUE THREAD

**Issue by LusciousPear** [SeleniumHQ/docker-selenium#487]
## Meta -
Image(s):  
standalone-chrome

Docker-Selenium Image Version(s):  
3.4.0-actinium

OS: 
Ubuntu 16.10

## Expected Behavior -

Chrome starts normally, with sandboxing enabled. This is important because we need to run tests on real-world sites with security, as well as test for malware vulnerabilities.

## Actual Behavior -

Error message:

> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

The only way is to run with --no-sandbox enabled, which we cannot do because we need the security and protections.

## Question

Is there any way to run Chrome with sandboxing in docker on Ubuntu?

**Comment by elgalu** [comment]
You can pass it through the capabilities, see:

https://github.com/elgalu/docker-selenium#chrome-not-reachable-or-timeout-after-60-secs

**Comment by LusciousPear** [comment]
Thanks -- actually, I know how to disable the sandboxing. But we don't want to, because we need the security and sandboxing abilities.

**Comment by elgalu** [comment]
Ah ok, I'm reading now :) 

Can you try `docker run --cap-add=SYS_ADMIN` ? as suggested here:
https://github.com/jessfraz/dockerfiles/issues/17#issuecomment-99330284

Others are sharing `-v /dev/dri:/dev/dri` but doesn't seem to solve the problem, though you could also try if `--cap-add=SYS_ADMIN` doesn't work.

Finally you could also try `docker run --privileged`

Sorry for just googling and copy pasting but I don't have time to search into this as I don't have customers that need this for now, but if you find the solution please share it.

**Comment by mfoksinski** [comment]
@LusciousPear 
Have you been able to fix this ? I am encountering the same problem.

**Comment by diemol** [comment]
@LusciousPear @mfoksinski did you try the workaround suggested in the previous comment?

We haven't heard any feedback in a while. Therefore, I will close this issue, but feel free to reopen it in case the issue is still present and more feedback is provided.
