### ISSUE TITLE
Getting connection Refuse in Chrome when trying to open docker Selenium grid 

### ISSUE THREAD

**Issue by arvinder06** [SeleniumHQ/docker-selenium#491]
Both the node and hub are up and running and I can see the execution going in node via VNC. But cannot open grid console. 

![image](https://cloud.githubusercontent.com/assets/28785545/26238354/04fbe60a-3cbc-11e7-9feb-8620343c289b.png)

![image](https://cloud.githubusercontent.com/assets/28785545/26238398/3af569f2-3cbc-11e7-8588-e82452d1381e.png)

$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.04.0-ce

Note: I am running the docker behind corporate proxy.
Please help.

**Comment by diemol** [comment]
Hi @arvinder06,

Are you running docker natively on Windows? If so, I think you can go directly to localhost instead of 192.168.99.100.

If you still have a problem, please provide more information:
- Exact image version you are using.
- Commands used to start the docker images

**Comment by arvinder06** [comment]
@diemol Thanks a lot for your reply.
I have installed Docker toolbox for Windows from docker's official site. I am running this in office (behind corporate  proxy). 
The IP adddress I am using to see grid console is actually the IP address of Selemium Hub container which I got from Kitemetic after running the selenium containers (Hub and node) using below commands on docker:

Hub
docker run -d -p 5000:4444 --name selenium-hub -P selenium/hub:2.53.1

Node
docker run -d --link selenium-hub:hub -P --name chrome selenium/node-chrome-debug:2.53.1

Using localhost for grid show below problem:
![image](https://cloud.githubusercontent.com/assets/28785545/26547491/ad2a8fcc-44b2-11e7-8c46-d01d22be58b6.png)

Also, using VNC, I can see the chrome browser is opening in Node but google.com or any other website is not opening. Therefore, instead of successful setup, I believe there is still a gap somewhere which I need to fix.

Please suggest.

**Comment by diemol** [comment]
@arvinder06 Which Windows version are you using?

**Comment by arvinder06** [comment]
Windows 7

**Comment by diemol** [comment]
If you are using docker toolbox then I guess that localhost doesn't work.

Try with your docker-machine ip instead of localhost.
https://docs.docker.com/machine/reference/ip/

**Comment by arvinder06** [comment]
Yup, I tried this also. This shows Connection Refused, as in screenshot above.

**Comment by elgalu** [comment]
You could also try posting your question in stackoverflow @arvinder06 and put the link here so we can keep track of it.

**Comment by diemol** [comment]
> I have installed Docker toolbox for Windows from docker's official site. I am running this in office (behind corporate proxy).
> Also, using VNC, I can see the chrome browser is opening in Node but google.com or any other website is not opening. Therefore, instead of successful setup, I believe there is still a gap somewhere which I need to fix.

I couldn't get a Windows machine to try your setup. Nevertheless, after reading your comments above, it looks like an issue with your network configuration. Perhaps you can ask directly to the network guys in your company?

You can also try to the basic docker container with nginx tutorial https://docs.docker.com/kitematic/nginx-web-server/
If you can connect to the app being built there, you should follow the same idea to connect to the docker-selenium containers. 
Also, try to use the default ports (4444 instead of 5000).

**Comment by arvinder06** [comment]
@diemol 
Thanks again for your reply. The problem is when I am opening Kitematic, below error:

![image](https://cloud.githubusercontent.com/assets/28785545/26574011/295ee196-4563-11e7-8ba4-3669f21a5c8a.png)

**Comment by diemol** [comment]
It really looks like your docker setup is not correct. It is hard for us to help when docker is not working properly, sorry.

I would suggest that you research on your own a bit those errors and fix your docker environment, for example the first google result for that message is https://github.com/docker/kitematic/issues/1633

When you are able to run docker properly, try docker-selenium again please. If you have still problems you should open another issue with the specific docker-selenium problem.

For now, this is not really a docker-selenium issue. I suggest it to be closed.

**Comment by arvinder06** [comment]
Ok, thanks Guys. I will do more research on this and will post the solution here if find anything. Thanks again for your time. :)
