### ISSUE TITLE
NodePhantomJS Browser_Timout

### ISSUE THREAD

**Issue by jconroy** [SeleniumHQ/docker-selenium#497]
Image(s):  
* Hub
* NodePhantomJS
* NodeChrome

Docker-Selenium Image Version(s):  
* 3.4.0-dysprosium

OS: 
* Ubuntu
* OSX

### Behaviour

I run the follow commands to load up a small grid configuration - 1 Hub, 1 Chrome Node, 1 PhantomJS Node and I set some custom timeouts e.g.

```
docker run -d --restart always -p 4444:4444 -e GRID_BROWSER_TIMEOUT=1800 -e GRID_TIMEOUT=1800 --name selenium-hub selenium/hub:3.4.0-dysprosium
docker run -d --restart always --link selenium-hub:hub selenium/node-chrome:3.4.0-dysprosium
docker run -d --restart always --link selenium-hub:hub selenium/node-phantomjs:3.4.0-dysprosium
docker run -d --restart always --link selenium-hub:hub prospress/node-phantomjs:3.4.0-chromium (custom node - with the grid connect fix to run phantomjs 2.1.1)
```

When I view the hub config I can see the timeouts are set for the hub e.g. [https://cl.ly/0M2N3S3a3J21](https://cl.ly/0M2N3S3a3J21)

When I view the node configs for the the Chrome node it appears to pick up the timeout settings

When I view the node configs for the PhantomJS node it does not appear to pick up the timeouts 

e.g. [https://cl.ly/1E2x0C0U2u3f](https://cl.ly/1E2x0C0U2u3f)

Subsequently when I run one of my tests against the phantomjs node (via the hub) it sometimes takes ever so slightly longer than other tests and it fails with a BROWSER_TIMEOUT error e.g.

```
Session [6f237320-5041-11e7-9c49-b72001ed2c43] was terminated due to BROWSER_TIMEOUT
```

From what I understand this is coming from the hub and not the node? 

Other things that I find confusing are that from what I understand the `browser_timeout=0` should mean no timeout and my test runs at most for 30-40sec (which isn't very long) so I don't quite understand why it is timing out.

Short and sharp tests using phantomjs seem to work fine.

---

I've searched high and low across the phantom and ghostdriver repos for anyone with similar issue but can't find any similar / workaround / fix.

I've looked at https://github.com/SeleniumHQ/docker-selenium/issues/150 - The timeouts do appear to be working - just not the phantomjsnode.

---

If I run standardlone phantomjs with essentially the same script as https://github.com/SeleniumHQ/docker-selenium/blob/master/NodePhantomJS/entry_point.sh#L20 (minus the hub stuff) I don't get the browser_timeout errors - ever.

Has anyone come across and/or know a fix / way to get around the BROWSER_TIMEOUT? Thought I'd check to see if there is just something I'm doing wrong with the grid or if there is another option I can set.

Thanks in advance.

**Comment by ddavison** [comment]
this is indeed an interesting issue - will have to investigate.

**Comment by jconroy** [comment]
thanks @ddavison I'm going to keep digging as well, greatly appreciate the extra brain cycles.

**Comment by jconroy** [comment]
@jesg or @Vitallium have either of you come across timeout issues with phantomjs in grid configuration?

**Comment by jesg** [comment]
> From what I understand this is coming from the hub and not the node?

correct it is from the hub.  ghostdriver does not implement timeout

imo it's best to start up a fresh phantomjs instance per test.  phantomjs has fast startup performance so there shouldn't be much difference.  @jconroy you might be running into a memory issue when running phantomjs for a long period of time.

**Comment by jconroy** [comment]
thanks for the thinking @jesg !

> you might be running into a memory issue when running phantomjs for a long period of time.

I'm not totally sure its that here - in all of my debugging above phantomjs has been up for less than an minute - I've been firing it up and then testing, all my tests in totally only go for 2-3min. I've actually been surprised how long I can keep phantomjs up and up running (days, usually weeks without too many issues).

> imo it's best to start up a fresh phantomjs instance per test. phantomjs has fast startup performance so there shouldn't be much difference

Ok I'll look into some approaches for this, thanks for the tip.

**Comment by diemol** [comment]
Hi, I am going to close this issue since PhantomJS will not be supported anymore in Selenium and docker-selenium (starting from 3.8), and we won't fix previous releases.

Hopefully you are already using Chrome or Firefox headless to replace PhantomJS :)
