### ISSUE TITLE
webdriver very slow when running 20 browsers

### ISSUE THREAD

**Issue by ycwdaaaa** [SeleniumHQ/docker-selenium#499]
when I use docker-selenium hub and chrome node, I found that it runs very fast when I use only one node and browsers, but it was very slow after I change the config to run 20 browsers.

**Comment by ddavison** [comment]
ok a few questions here:

"run 20 browsers"  how exactly are you running 20 browsers?

20 selenium/node-chrome's connecting to 1 hub?
1 selenium/node-chrome with NODE_MAX_INSTANCES set to 20 connected to 1 hub?

please share your invocation code with us so we can help

**Comment by ycwdaaaa** [comment]
@ddavison I use 4 nodes and 4 browsers per node.  below is my docker-compile file
hub:
  image: selenium/hub:3.2.0
  ports:
    - 4444:4444
  environment:
    - GRID_TIMEOUT=0
    - GRID_THROW_ON_CAPABILITY_NOT_PRESENT=true
    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
    - GRID_BROWSER_TIMEOUT=15000
    - GRID_TIMEOUT=30000
    - GRID_CLEAN_UP_CYCLE=30000
chrome1:
  image: chrome_test
  container_name: chrome_test_1
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
  links:
    - hub
chrome2:
  image: chrome_test
  container_name: chrome_test_2
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
  links:
    - hub
chrome3:
  image: chrome_test
  container_name: chrome_test_3
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
  links:
    - hub
chrome4:
  image: chrome_test
  container_name: chrome_test_4
  environment:
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
    - NODE_REGISTER_CYCLE=5000
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  volumes:
    - /dev/shm:/dev/shm
  links:
    - hub

**Comment by diemol** [comment]
@ycwdaaaa,

A few questions:
* What is this `chrome_test` image you are using? Did you build it yourself? Maybe you can try with the official images?
* You are using the `selenium/hub:3.2.0` image, can you try to upgrade? Many improvements to the images have been done since that release.
* How do you limit each node to use 4 browsers? Besides I see 4 Chrome nodes, but you mention slowness when running 20 browsers, can you please elaborate more so we can help?

**Comment by diemol** [comment]
Closing as we didn't get feedback from the OP.
