### ISSUE TITLE
Cannot open browser in Docker container

### ISSUE THREAD

**Issue by jmewes** [SeleniumHQ/docker-selenium#50]
# Observed result:
Cannot connect to virtual display
```
07:39:51.778 INFO - Executing: [new session: Capabilities [{platform=ANY, browserName=firefox, version=}]])
07:39:51.780 INFO - Creating a new session for Capabilities [{platform=ANY, browserName=firefox, version=}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
(process:87): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: cannot open display: :99.0
(process:95): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: cannot open display: :99.0
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
```

# Expected result:
- browser is started, 

# Steps to reproduce:
- start docker-selenium hub
- start docker-selenium node
```
docker run -i -t --cap-add=NET_ADMIN -p 5555:5555 selenium/node-firefox /bin/bash

java -jar ./opt/selenium/selenium-server-standalone.jar -role wd -hub http://<hostname>:4444/grid/register -browser browserName="firefox",maxInstances=1
```

# Environment
- CentOS 
- selenium 2.45.0
- selenium/hub
- selenium/node-chrome
- selenium/node-firefox
- docker-selenium firefox node as well as chrome

# Workaround
```
docker run -i -t --cap-add=NET_ADMIN -p 5555:5555 selenium/node-firefox /bin/bash
Xvfb :1 -screen 0 1024x768x16 &
export DISPLAY=:1
java -jar ./opt/selenium/selenium-server-standalone.jar -role wd -hub http://<hostname>:4444/grid/register -browser browserName="firefox",maxInstances=1
```

**Comment by jmewes** [comment]
Might be a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/31

**Comment by rubytester** [comment]
We see this same issue on CentOS 6.6. Which version of CentOS do you run?

**Comment by jmewes** [comment]
We experienced this issue with CentOS 6.6, too.

**Comment by elgalu** [comment]
CentOS is the host operating system or you modified the Dockerfile?
Can you recreate with [elgalu/docker-selenium](https://github.com/elgalu/docker-selenium) ? i.e.

```sh
docker run -p 4444:4444 -p 5900:5900 -e SCREEN_WIDTH=1550 -e SCREEN_HEIGHT=1110 -e VNC_PASSWORD=secret elgalu/selenium:v2.45.0-berlin5
```

**Comment by jmewes** [comment]
CentOS was the host operating system. We were using the standard Selenium Docker project without a modified Dockerfile. 

Sorry, I cannot just try to recreate. We evaluated Selenium Docker in a Hackathon project and are not using it in production yet. I'll talk with my collegues later this afternoon if we can manage to try your suggestion.

**Comment by rubytester** [comment]
Still an issue? I have moved all tests to run on CentOS 7.1 and using docker 1.6.2 and since then I have not see issues.

Please reopen if this continues to plague you.

**Comment by jmewes** [comment]
No it is not an issue anymore. My collegue reported that with Selenium-Docker running on Debian 8 everything went on alright.
