### ISSUE TITLE
Unable to use a host port other than 5555 for Selenium Grid nodes

### ISSUE THREAD

**Issue by saharshsingh** [SeleniumHQ/docker-selenium#501]
## Meta -
Image(s):  selenium/node-chrome, selenium/node-firefox

Docker-Selenium Image Version(s):  3.4.0, 3.2 (might be all 3.x.x)

OS: Red Hat 4.8.3-9

## Expected Behavior -

Running the following command should succesfully start a Chrome Node and register it with a hub running at 1.2.3.4:4444.

`docker run -d --restart unless-stopped -e HUB_PORT_4444_TCP_ADDR=1.2.3.4 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 1.2.3.4 -port 5556" -p 5556:5555 --name selenium-chrome-node selenium/node-chrome:3.4.0`

## Actual Behavior -

The node starts, however it can't be accessed at either 1.2.3.4:5556 or [local_docker_ip]:5555. Trying to access it keeps giving a 'Connection reset by peer' socket exception. This seems to be the case for any host port other than 5555.

**Comment by tparikka** [comment]
See #432 for information.

**Comment by saharshsingh** [comment]
I reverted my container versions back to 2.53.0, and the expected behavior can be achieved via the following command:

`docker run -d --restart unless-stopped -e HUB_PORT_4444_TCP_ADDR=1.2.3.4 -e HUB_PORT_4444_TCP_PORT=4444 -e REMOTE_HOST="http://1.2.3.4:5556" -p 5556:5555 --name selenium-chrome-node selenium/node-chrome:2.53.0`

Seems like something that was working in 2.x.x (using REMOTE_HOST) is no longer working in 3.x.x (using SE_OPTS). This makes it very hard to have a Selenium Grid setup spread across multiple machines.

**Comment by saharshsingh** [comment]
Thanks tparikka!

I see the `-e NODE_PORT=5556 -p 5556:5556` part is what I was missing.

Closing this issue.
