### ISSUE TITLE
Cannot find how provide hub address to a node

### ISSUE THREAD

**Issue by thibaut-sticky** [SeleniumHQ/docker-selenium#503]
Images:  node-chrome or node-firefox
Docker-Selenium Image Version: 2.53.0 and latest.
OS: Debian 8

**Expected behavior**
Give to a docker selenium node, a remote hub address. Like I did it already for a non docker node.

**Current behavior**
It look like I have to use REMOTE_HOST, or SE_OPTS with -hub. But I cannot find any documentation about this. 

So how to do it?

**Comment by tparikka** [comment]
You can specify the hub address using the environment variables HUB_PORT_444_TCP_ADDR or HUB_PORT_444_TCP_PORT. For example, if running from command line:

-e HUB_PORT_4444_TCP_ADDR=10.10.1.10 -e HUB_PORT_4444_TCP_PORT=4444

**Comment by thibaut-sticky** [comment]
Works perfectly. :)
It's the same for version 3+?

**Comment by ddavison** [comment]
was thinking the same.   the documentation is fairly lacking right now.  I'll be in Seattle for the next two weeks in office and very busy so if somebody else could try their hand at it, that'd be awesome!

**Comment by diemol** [comment]
I just created #507. I'll close the issue when it gets merged.

**Comment by diemol** [comment]
Just merged #507, closing this issue then.

**Comment by thibaut-sticky** [comment]
Perfect, thx!
