### ISSUE TITLE
New containers stop receiving connections after a while

### ISSUE THREAD

**Issue by endqwerty** [SeleniumHQ/docker-selenium#504]
## Meta -
Image(s):  standalone-chrome
Docker-Selenium Image Version(s):  3.4.0-dysprosium
OS: OSX
## Expected Behavior -

New containers work (receive selenium commands) and the Selenium Console is accessible through the exposed port

e.g. http://localhost:32778/wd/hub/static/resource/hub.html

## Actual Behavior -

After a couple of executions (approx 5) the standalone containers refuse connections on the port and I cannot access the Selenium Hub Console.

**Comment by tparikka** [comment]
This sounds like you're describing the issue reported at docker/for-win#426. It was reported in January and has still not been fixed. The Docker team last responded to the ticket April 21, and has not updated since then.

**Comment by endqwerty** [comment]
@tparikka Thanks. It looks like the exact issue I'm getting. Interestingly though, my issue with just one container running at a time. I have Jenkins managing the docker container and it prevents executing tests in parallel.

From the comments, it looks like a potential solution is to run docker in a linux VM? I'm not opposed to using a VM or other machine, I just want the Docker containers to be reliable.

**Comment by tparikka** [comment]
I read the same although I haven't tried it myself so I can't verify. The is solely in Docker itself though, not at all related to anything in our repo.

**Comment by diemol** [comment]
Thanks @tparikka for checking it! 
Closing it as it is not a docker-selenium issue.
