### ISSUE TITLE
3.4.0-dysprosium still has FF53 instead of FF54

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#506]
## Meta -
Image(s):  3.4.0-dysprosium

Docker-Selenium Image Version(s):  

OS: LINUX

**Comment by ddavison** [comment]
[correct](https://github.com/SeleniumHQ/docker-selenium/blob/3.4.0-dysprosium/NodeFirefox/Dockerfile#L13).

[the commit](https://github.com/SeleniumHQ/docker-selenium/commit/9ff16f9f453e1345df0e7bac391cc39fcc529d0a) to change the firefox version was merged in **after** dysprosium was released.  the next release will have it :+1:
