### ISSUE TITLE
Tag for `latest` is not pointing to the most recent image release

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/docker-selenium#508]
## Expected Behavior -
 When I do `docker pull selenium/standalone-chrome-debug`, I should get the latest release, right now is 3.4.0-dysprosium.
## Actual Behavior -
Right now I am getting a release done 2 months ago. This is because the `latest` is pointing to the wrong image.
Check https://hub.docker.com/r/selenium/standalone-chrome-debug/tags/

I think we made a mistake in the most recent release. I will check the other images to see if this is also happening there.

**Comment by diemol** [comment]
Also happening on:
https://hub.docker.com/r/selenium/node-phantomjs/tags/
https://hub.docker.com/r/selenium/base/tags/
https://hub.docker.com/r/selenium/standalone-firefox-debug/tags/

**Comment by ddavison** [comment]
this should be fixed from https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.4.0-einsteinium.

let's wait and see. we'll leave this issue open until validated.

**Comment by diemol** [comment]
Yeah, I checked and the tag is well placed in all the images. Thanks!
