### ISSUE TITLE
Unable to set -remoteHost parameter for nodes without using custom config.json

### ISSUE THREAD

**Issue by charford** [SeleniumHQ/docker-selenium#51]
Hi,

I've got this setup on separate hosts. So one host runs the HUB, and then several other hosts have nodes running on them. In this use case, I am unable to link containers, so I need to expose ports, and public IPs of hosts running nodes in order to connect to the HUB. Below is the example command that we use to start a node (replace 1.2.3.4 with IP of hub):

```
docker run -d -p 5555:5555 -e HUB_PORT_4444_TCP_ADDR="1.2.3.4" -e HUB_PORT_4444_TCP_PORT="4444" --name firefox-node selenium/node-firefox
```

What ends up happening, is the value for remoteHost gets set to the 'private' IP of the docker container itself. If you exec into a running docker container, and execute ipconfig, you'll see the IP that it uses. This is fine if you are 'linked' to the hub, but when running on separate hosts, the hub cannot contact the private IP. To enable this to work, we need support for -remoteHost parameter when starting the nodes. 

-remoteHost is a built in parameter for selenium. More info available here: http://automatictester.co.uk/2012/10/27/selenium-grid-2-0-and-remotehost-parameter/

After this feature is implemented, we should be able to run nodes like this (notice the addition of the REMOTE_HOST env variable):

```
docker run -d -p 5555:5555 -e REMOTE_HOST="http://1.2.3.4:5555" -e HUB_PORT_4444_TCP_ADDR="1.2.3.4" -e HUB_PORT_4444_TCP_PORT="4444" --name firefox-node selenium/node-firefox
```
NOTE: In example above, you would need to provide correct IP for REMOTE_HOST and HUB, not the 1.2.3.4 that I provided as an example.

**Comment by charford** [comment]
Implemented with PR: https://github.com/SeleniumHQ/docker-selenium/pull/52

**Comment by austo** [comment]
Great PR - I hope this gets pulled in!

**Comment by jcostello84** [comment]
+1 for merging. I tested it out locally and it works great.

**Comment by viveksoundarrajan** [comment]
I am trying to connect the "docker selenium remote node" to "remote docker hub", But it's not connecting, It shows the connection refused exception, Even I can connect my "remote node" to "docker hub". please help me.

**Comment by charford** [comment]
@viveksoundarrajan it looks like your docker run command is routing the port 5558 to 5555(inside container), with the -p 5558:5555 parameter. This means your REMOTE_HOST parameter should be using the the same port (5558). This parameter tells the hub how it can reach the node over network, so it should be configured to match the IP of the docker host running your node, and the port 5558. Also, in your run parameter it looks like you're using the IP of your hub for the REMOTE_HOST. The remote host is not your hub, that is the node itself, and is sent to the hub to let it know how to reach the node. The REMOTE_HOST parameter should include the IP that your node is running on.

**Comment by testphreak** [comment]
Hi @charford, it looks like the -remoteHost parameter no longer works on Docker images with Selenium Grid v3.0.0 (selenium-server-standalone.jar). See #306 and #307 for exact error. Any idea what might have changed between 2.53.1 and 3.0.0?

I wonder if it has anything to do with the command line argument parser change that was made for v3. https://github.com/SeleniumHQ/selenium/issues/2566

As far as I can see, the remoteHost parameter continues to be supported - https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridNodeConfiguration.java

**Comment by charford** [comment]
@testphreak I haven't had a chance to try this in the latest (3.0) version. But the SE_OPTS solution mentioned in #307 looks promising.

**Comment by testphreak** [comment]
@charford figured it out finally :).

```
bash -c 'SE_OPTS="-host $HOSTNAME" /opt/bin/entry_point.sh'
```

**Comment by yatheeshAtzenq** [comment]
I am trying to run docker Selenium on diff hosts

using these commands on Hub
> docker run -p 4444:4444 -d -P --name selenium-hub selenium/hub
on Node
> docker run -d -p 5558:5556 -e SE_OPTS="-host 10.20.50.53 -port 5558" -e HUB_PORT_4444_TCP_ADDR="10.20.50.92" -e HUB_PORT_4444_TCP_PORT="4444" --name firefox selenium/node-firefox

How ever,I see the that the node is registered , but when i fire a test the request says pending
Here are the Hub logs and screenshot 

> 12:26:43.302 INFO - Unregistering the node http://10.20.50.53:5558 because it's been down for 60014 milliseconds
 12:26:43.302 WARN - Cleaning up stale test sessions on the unregistered node http://10.20.50.53:5558
 12:26:43.389 INFO - Registered a node http://10.20.50.53:5558
 12:27:03.395 INFO - Marking the node http://10.20.50.53:5558 as down: cannot reach the node for 2 tries

![image](https://cloud.githubusercontent.com/assets/10920243/22064802/2b94f394-ddab-11e6-9c12-5975b658af03.png)
 
 The Node seems to be up and running. Not sure what can be the issue

**Comment by aapande** [comment]
@lukeis This is happening on selenium standalone version3.3.1 . Nodes are continuously getting reconnected to hub.
Can some one please take look at it?

**Comment by McSnowflake** [comment]
@yatheeshAtzenq This is happaning because the SE_OPTS option does not exectly the same as the good old REMOTE_HOST option. Instead it overwrites the nodes port and ip setting.
So while your port mapping thinks the node uses 5556, the node uses 5558. And that's why the hub can't reach it.
