### ISSUE TITLE
Tab crashes

### ISSUE THREAD

**Issue by grafa** [SeleniumHQ/docker-selenium#510]
## Image(s)
Chrome standalone

## Docker-Selenium Image Version(s)
Latest (master on github) - 3.4.0 - build from this Dockerfile: https://github.com/SeleniumHQ/docker-selenium/blob/7b6ca64/StandaloneChrome/Dockerfile

## OS
Host OS is Linux Debian

## Expected Behavior
Not crashing

## Actual Behavior
Crashing :)

I have a set of URL's. These URLs point to Yahoo (so pretty heavy page). I walk thru those URL's and my 3rd - 5th URL crashes Selenium everytime. The URL is 90% same like the previous ones. My idea is memory overflow or something like that.

I kick of the remote webdriver and then walk thru all URLs. Can I cleanup somehow after each URL gets done? Maybe I have to quit and set up new driver for every URL but... really? Just thinking...

Tracelog says this:

`unknown error: session deleted because of page crash selenium from tab crashed`

I get that as tab crash just like we all know from browser:

![Crash](https://www.geek.com/wp-content/uploads/2011/03/Chrome-tab-crash.png)

**Traceback here** (the message is highlighted inside)
https://pastebin.com/D5RH941F

I use [Python driver](https://github.com/baijum/selenium-python).

Thank you.

**Comment by ddavison** [comment]
Could you share the Dockerfile/docker command that you are using to launch the container(s)?


FYI, for the future - instead of pastebin, you can more easily paste inside of the github issue (that way we don't have to rely on an external link that could expire)

<details>
<summary>Stack trace</summary>
This is the stack trace paste
</details>

I gave the above with this code:

```
<details>
<summary>Stack trace</summary>
This is the stack trace paste
</details>
```

**Comment by grafa** [comment]
Thank you for your response.

The Selenium part in my `docker-compose.yql` is pretty simple:

```yml
    selenium:
        image: selenium/standalone-chrome
        container_name: selenium
        networks:
            - richy
```

I run my app with `docker-compose up`

@pastebin
I did it on purpose because the stacktrace is "wide" and if you paste it to github issue which is like 500px wide it gets shrinked and pretty much unreadable. I guess pastebin is pretty much stable service and I chose expiration "never".

**Comment by psiedlinski** [comment]
Just a comment - I am facing similar issue using java (I bet this is a browser issue). Simple code like `driver.getElement(...).click()` causes the browser to crash. (selenium hub - chrome node on aws ec2 instance). 
It works perfectly fine on my local and on firefox.

**Comment by grafa** [comment]
Later this week I will try to rewrite my code to terminate and re-setup browser after each URL. I will report the result.

BTW: any updates?

**Comment by grafa** [comment]
Hey guys,

I've tried to quit browser instance after each URL and it seem like it's working - no more terminations. I guess it was memory issue but who knows. So `browser.quit()` after you are done does the thick.

**Comment by diemol** [comment]
Closing as the OP reported the issue solved.
