### ISSUE TITLE
How to install vncviewer in ec2 instance

### ISSUE THREAD

**Issue by vijayrcse** [SeleniumHQ/docker-selenium#514]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  

OS: 

## Expected Behavior -
I would like to install vncviewer in my ec2 instance where my docker nodes are running
I am trying to run the ./bin/vnviewer command. After resolving many dependency issues I am getting the below error message. Please advise
https://www.realvnc.com/docs/6.1/foss.html
<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: vncviewer: unable to open display ""
<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: TXMsgBox: unable to open display ""
<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: TXMsgBox: unable to open display ""

**Comment by diemol** [comment]
Hi @vijayrcse,

Are you exposing your Selenium Grid publicly on AWS? I guess you need to double check your networking rules and everything related to the exposed ports...

But more importantly, if you are exposing the Grid, it wouldn't be a good idea, check these two issues:
https://github.com/SeleniumHQ/selenium/issues/2076 and #147

**Comment by vijayrcse** [comment]
No , its not aabout Selenium grid publicy on AWS. I have my hub and node docker container running in ec2 instance( Amazon llinux). I have trying to use the vncviewer command from ./bin/vnvviewer.
I downloaded the vnc viewer binary from realvnc and placed in path

But when i start the vncviwer from my amazon linux ec2 instance , connectting to the port where vnc server is exposed by node image, it could not connect. Getting the below error

<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: vncviewer: unable to open display ""
<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: TXMsgBox: unable to open display ""
<11> 2017-07-04T10:39:09.092Z ip-1X-XX-X-XX vncviewer[12283]: TXMsgBox: unable to open display ""

I am looking for clear instruction of running the vncviewer from linux machine sso i can connect to the 5900 port. Current documentation is not helping. Please advise

**Comment by vijayrcse** [comment]
I am closing this thread. I have used vnc from windows and connected
