### ISSUE TITLE
Using docker selenium node image in AWS ECS - how to pass the node port for hub registration

### ISSUE THREAD

**Issue by vijayrcse** [SeleniumHQ/docker-selenium#516]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  

OS: 

## Expected Behavior -
Below is my TaskDefinition in my ecs yaml

Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-node-server
      ContainerDefinitions:
        - Name: node-server
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:${Tag}
          Essential: true
          Memory: !Ref Memory
          MemoryReservation: !Ref MemoryReservation
          Cpu: !Ref Cpu
          PortMappings:
            - ContainerPort: 4444
          Environment:
            - Name: HUB_PORT_4444_TCP_ADDR
              Value: !Ref HubLoadBalancerDNS
            - Name: HUB_PORT_4444_TCP_PORT
              Value: 80
            - Name: SE_OPTS
              Value: !Sub "-host ${NodeLoadBalancerDNS} -port 80"

I have only defined ContainerPort. No HostPort. In this case what could be the value for -port ??

I tried giving 80, it didn't connect throwing permission error. The port is dynamic port which i could not know.

Does it work only if i use HostPort mapping ?

**Comment by lareeth** [comment]
You will need to connect this task to an Application Load Balancer that forwards the randomised host port back to a fixed port. You can then replace the server without needing to update your application when the container gets a new random IP assigned.

**Comment by vijayrcse** [comment]
I was able to pass the port by connecting to application loadbalancer and its listerner port. thx for clarification
