### ISSUE TITLE
Selenium python test against selenium grid created from SeleniumHQ docker images

### ISSUE THREAD

**Issue by namgivu** [SeleniumHQ/docker-selenium#521]
Today I failed to run tests against selenium grid i.e. the sub+node containers - though I can run the same test with the standalone one

My demo test can view here
- start the selenium grid 
  https://github.com/namgivu/selenium-docker-sandbox/blob/master/s01a_start_selenium_grid.sh
- my simple tests
  https://github.com/namgivu/selenium-docker-sandbox/blob/master/s02a1_tiny_test.py

Would be lovely as you may show me how to get a test run against the grid!

Thank you,
Nam

p.s. I also asked on stackoverflow here
https://stackoverflow.com/q/45127482/248616

**Comment by lmtierney** [comment]
I'm guessing you're running into seleniumhq/selenium#3808. For python you can downgrade to `3.3.1` until the fix for that is released.

**Comment by namgivu** [comment]
Confirmed that my test works now after installing python selenium 3.3.1

```bash
pip uninstall selenium ; pip install selenium==3.3.1
```

**Comment by qiuyuhome** [comment]
OK，thanks

发自我的 iPhone

**Comment by VireshDoshi** [comment]
Hi
my setup: centos7, docker-compose, python 2.7, virtualenv, selenium==3.9.0
I have the latest selenium grid up and running ( version: 3.9.1-actinium ) but it failed to run a test against the selenium grid. The following did the trick! :-)
``` $ pip uninstall selenium ; pip install selenium==3.3.1 ```
