### ISSUE TITLE
Using docker selenium images for various browser testing( combination of versions and OS )

### ISSUE THREAD

**Issue by vijayrcse** [SeleniumHQ/docker-selenium#523]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  

OS: 

## Expected Behavior -

HI 

I have a requirement where i need to do web automation testing with various browser combination. Some example combination are below

Chrome , Windows 7/XP, version1(not giving exact version for simplification)
Chrome , Windows 7/XP, version2
Firefox, Windows 7/XP, version1
Firefox, Windows 7/XP, version2
IE, Windows 7/XP, version1
IE, Windows 7/XP, version2
Edge, Windows 10, version1
Chrome, Linux/Ubuntu, version1
Firefox, Linux/Ubuntu, version1

etc

We see that docker selenium container are built with ubuntu as base image and windows/IE is not supported.

Could you please advise if docker selenium project is the right way for our use cases? If so how to fill the gaps of Windows/IE combination ?

**Comment by ddavison** [comment]
the simplest answer, however not easiest.. would be to have dedicated nodes and not use docker at all.   

you could still use docker to control your hub, and linux firefox/chrome nodes, but you'd have to have dedicated nodes running your desired operating systems, and you can just connect to the same hub run by docker.

**Comment by vijayrcse** [comment]
Thanks ddavison. When you say dedicated node I believe you are referring to dedicated VM's with required windows OS and browsers installed.

This means docker selenium can still be re-used for HUB and nodes with firefox, chrome (Ubuntu/linux OS combination )

Thanks for your response

**Comment by ddavison** [comment]
exactly right.  have your own nodes with your required OS's and browsers installed, then have those nodes connect right to the hub that you have hosted with docker.
