### ISSUE TITLE
VNC Password is Undefined

### ISSUE THREAD

**Issue by peterstory** [SeleniumHQ/docker-selenium#524]
## Meta -
Image(s):  
selenium/node-firefox-debug:3.4.0-einsteinium

## Expected Behavior -

VNC Should be accessible at port 5900.

## Actual Behavior -

VNC isn't started properly: I cannot connect until I start it myself.

It appears that the password isn't set properly in `entry_point.sh`. 

```
x11vnc -forever -usepw -shared -rfbport 5900 -display $DISPLAY &
```

If I run this command manually, I get the following output:
```
root@6a59498df15d:/# x11vnc -forever -usepw -shared -rfbport 5900 -display $DISPLAY
19/07/2017 16:53:04 passing arg to libvncserver: -rfbport
19/07/2017 16:53:04 passing arg to libvncserver: 5900
Enter VNC password: 
```
Which seems to indicate that a password must be specified interactively. 

If this is changed to:

```
x11vnc -forever -passwd secret -shared -rfbport 5900 -display $DISPLAY &
```

Then things work again.

**Comment by ddavison** [comment]
the password is set here: https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefoxDebug/Dockerfile#L59

**Comment by peterstory** [comment]
Hmm, it must be that that file isn't accessible or being used in my containers. I added a couple extra steps before using the `entry_point.sh`. Assuming nobody using the stock image is encountering this same problem, my changes must have caused the problem. 

`firefox.Dockerfile`
```Dockerfile
FROM selenium/node-firefox-debug:3.4.0-einsteinium

# We need to modify '/etc/hosts'. We restore the appropriate user at runtime in
# 'start_firefox.sh'.
USER root

# ...
# Misc. setup code
# ...

CMD ["/root/docker_resources/start_firefox.sh"]
```

`start_firefox.sh`
```sh
#!/bin/sh
# ...
# Misc. setup code
# ...
su - seluser
exec /opt/bin/entry_point.sh
```

**Comment by navels** [comment]
I'm running into this issues as well with the latest release.  Not sure how this was ever working, because the x11vnc docs say you are supposed to specify the path to the password file:
```
x11vnc -rfbauth .vnc/passwd
```

**Comment by navels** [comment]
Wondering if this changed with https://github.com/SeleniumHQ/docker-selenium/pull/477

**Comment by navels** [comment]
Sorted out our issue.  We had "USER root" in a Dockerfile and needed to set it back to seluser at the end of the file so that entry_point.sh executes as seluser.

**Comment by peterstory** [comment]
Interesting. I was using `su - seluser` in a script to get back to the seluser account, and things still weren't working. So there must be some difference in behavior between `su - seluser` and a Dockerfile's `USER seluser`.

**Comment by diemol** [comment]
The images were running as root before but we switched that to "seluser" for better practices. Seems that you were also able to switch to the user and use the VNC thing properly as well.

From my understanding this issue is not longer relevant, so I'll go ahead and close it. If a problem shows up, please feel free to reopen and provide enough info.
