### ISSUE TITLE
entry_point.sh is missing from StandaloneChromeDebug

### ISSUE THREAD

**Issue by stsvilik** [SeleniumHQ/docker-selenium#533]
## Meta -
Image(s): standalone-chrome-debug 

Docker-Selenium Image Version(s):  

OS: All

## Expected Behavior -
StandaloneChromeDebug should build locally
## Actual Behavior -
Build fails due to missing entry_point.sh file

**Comment by stsvilik** [comment]
I tried to build only StandaloneChromeDebug manually from within a folder. Using ```make build``` works fine without this file.

**Comment by ddavison** [comment]
glad you figured it out :+1:
