### ISSUE TITLE
Build Firefox Developer Edition 

### ISSUE THREAD

**Issue by saulshanabrook** [SeleniumHQ/docker-selenium#536]
First off, thanks for all of your work on these images. They have helped us immensely for our testing in CI.

I am trying to test web extension through Protractor and Selenium using these images. Firefox won't run the addon, because it is a folder and unsigned. In [order to run an unsigned extension in Firefox, you can't use the main Firefox release, but can use the developer edition with a custom setting](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users). Would it be possible to have images with the Firefox Developer Edition, so that we can test extensions on them?

I am happy to submit a pull request with this functionality, if it's something you are interested in.

**Comment by ddavison** [comment]
if we are able to duplicate the same functionality that the [chrome containers use](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile.txt#L18) then this would definitely be doable.  

might also be related to #470

**Comment by saulshanabrook** [comment]
In the meantime, I [am building](https://gitlab.com/passit/docker-selenium/) Firefox Developer Edition standalone with debug for my own use. 

Haven't figured out yet how to get predictable extension URLs (https://github.com/mozilla/web-ext/issues/1043), but loading an extension folder is working, using Protractor:

```javascript
const firefox = require('selenium-webdriver/firefox');

var profile = new firefox.Profile();
profile.addExtension('/dist/dist/');
profile.setPreference('xpinstall.signatures.required', false);
```

**Comment by saulshanabrook** [comment]
I have given up on using Firefox Developer Edition in Selenium to run extensions because I cannot figure out how to get the URL for the extensions once they are loaded. My other idea was to create a keyboard shortcut to launch the extension popup, then target that, but it seems webdriver isn't mean to support switching to these not-quite-pages.

If anyone else is trying to do this, the next thing I was going to try was to run a script that is activated on all pages that uses `extension.getURL()` to get the URL of the extension and saves this in a global variable on all pages, so that then in Selenium we can access that URL. 

I am going to close this, because I don't need this issue resolved anymore, but feel free to re-open if you are still interested.

**Comment by l0b0** [comment]
Please reopen this issue - I would like very much to test my extension using an official Selenium image.

**Comment by diemol** [comment]
Right now it is possible to build the image with Firefox Nightly, if you want to, please send us a PR enhancing this logic: https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefox/Dockerfile.txt#L7
adding Firefox Developer Edition, so anyone could build the image on their own.
