### ISSUE TITLE
Set log level to WARN?

### ISSUE THREAD

**Issue by smoll** [SeleniumHQ/docker-selenium#54]
In the readme it mentions [all output is directed to stdout](https://github.com/SeleniumHQ/docker-selenium#troubleshooting), however the log level appears to be INFO or lower.

I searched the repo and the only line referencing log level appears to be this one: https://github.com/SeleniumHQ/docker-selenium/blob/951caf23b215bfeb3ceb2e718b9d8b29493b3293/NodeChrome/chrome_launcher.sh#L66

Is modifying this shell script the only way to set a higher log level of, say, WARN? And is it possible to do that without forking this repo, changing that line, and then using my changed version? (My gut instinct is that there must be a more elegant way -- unless this feature has yet to be implemented)

Thanks in advance if anyone can answer this question; I appreciate all the great work you guys are doing here.

**Comment by selvakn** [comment]
@smoll : do you mind sharing how you fixed this problem?

**Comment by smoll** [comment]
Hi @selvakn, sorry but I no longer work for the company where I posed this initial question or use this image for any of my current projects, so I can't be of much assistance here.

**Comment by selvakn** [comment]
Figured out that this can be controlled by JAVA_OPTS `-Dselenium.LOGGER.level=<LEVEL>`
