### ISSUE TITLE
Latest release (hub:3.4.0-francium) from readme file is not available to download from docker hub

### ISSUE THREAD

**Issue by bhaku** [SeleniumHQ/docker-selenium#542]
Latest release 3.4.0-francium is not available on https://hub.docker.com/r/selenium/hub/tags/

## Expected Behavior -
`docker pull selenium/hub:3.4.0-francium `
Will download latest release from readme file.
## Actual Behavior -
`docker pull selenium/hub:3.4.0-francium`
Error response from daemon: manifest for selenium/hub:3.4.0-francium not found

**Comment by bhaku** [comment]
@ddavison When you will release 3.4.0-francium?

**Comment by ddavison** [comment]
yea - sometimes upon a release, the tests fail.  all that needed to be done is a re-push of the release.  done, and fixed.
