### ISSUE TITLE
Create VNC '-debug' images for standalone Selenium

### ISSUE THREAD

**Issue by pataquets** [SeleniumHQ/docker-selenium#55]
I'm not faimliar with Selenium Docker images, but as referenced in #34:
https://github.com/techjacker/StandaloneChromeDebug

It has even more sense for standalone to debug, because for local development and debugging, currently you're forced to boot a hub+node stack. Also, it would work for Selenium 1/RC debugging. I could not manage the grid to work for Selenium 1/RC.
TIA.

**Comment by rubytester** [comment]
see pull request #53

**Comment by rubytester** [comment]
pull request #53 was merged but I think docker images were not built. I need to find out what to do next to ensure they are available on https://registry.hub.docker.com/repos/selenium/

**Comment by rubytester** [comment]
standalone-firefox-debug and standalone-chrome-debug are here now https://registry.hub.docker.com/repos/selenium/

**Comment by pataquets** [comment]
Thank you!
