### ISSUE TITLE
Is it possible to set the user agent for the chrome browser?

### ISSUE THREAD

**Issue by WillGibson** [SeleniumHQ/docker-selenium#552]
This is just a question, nothing more to it than what you see in the subject.

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by WillGibson** [comment]
Sorry, I posted on the wrong project, I meant to be looking in https://github.com/elgalu/docker-selenium.
