### ISSUE TITLE
Test suite is failing during runtime saying 'no tests were run' when executing with docker selenium grid

### ISSUE THREAD

**Issue by nagaiah** [SeleniumHQ/docker-selenium#555]
Hi Team,

I have created selenium grid with docker swarm mode, am trying to execute a suite consists of above 200 test cases. During test execution test suite is failing saying as 'no tests were run',Any one of you please suggest me to tackle it and please find the attached screen for the error mentioned, Is it the issue with docker containers or selenium issue?

Docker images used for the docker swarm setup:
selenium/hub:2.53.1
selenium/node-chrome:2.53.1
selenium/node-firefox:2.53.1

Thanks in advance,
Nagaiah

**Comment by lmtierney** [comment]
Selenium is not a test runner, it controls web browsers via vendor webdrivers. It would have nothing to do with finding tests in your test runner
