### ISSUE TITLE
3.5.3 Images ?

### ISSUE THREAD

**Issue by pascalheraud** [SeleniumHQ/docker-selenium#556]
## Meta -
Image(s):  node-firefox

Docker-Selenium Image Version(s):  3.5.3 ?

OS: 

## Expected Behavior -
I'm expecting to find a 3.5.3 docker image.

## Actual Behavior -
Last one is 3.5.2

**Comment by ddavison** [comment]
yep, i'll get to it ;)

**Comment by niQo** [comment]
3.5.3 are now available

**Comment by pascalheraud** [comment]
great thanks !
