### ISSUE TITLE
Exception: unknown error: unable to discover open pages

### ISSUE THREAD

**Issue by phlegx** [SeleniumHQ/docker-selenium#56]
Having the following issue with docker image "selenium/node-chrome" 

https://gist.github.com/anonymous/b4b0f90d2889d310a1a0 

any ideas what might causing this?
the firefox node is just working like a charm

thanks a lot
m

**Comment by phlegx** [comment]
I also tried the standalone chrome Docker image, but same error their appeared also. Also updating the Chromedriver to 1.5 in the "selenium/node-chrome" image. But same problem still.

It works however with this image: https://github.com/elgalu/docker-selenium

**Comment by phlegx** [comment]
@elgalu Maybe you have a clue what is wong? thanks!

**Comment by phlegx** [comment]
Getting a timeout also with https://github.com/elgalu/docker-selenium when I remove the privileged tag. Will now test also "selenium/node-chrome" in privileged mode.

**Comment by elgalu** [comment]
So privileged fixes the issue on this repo too? Idk how to troubleshoot this issue unless you provide a public GitHub minimum selenium project that reproduces it.

**Comment by phlegx** [comment]
Unortunately I have only time to test this repo next week again. I'm not sure if I can provide such a minimal project here. The thing is locally on my private machine all works fine, however on server side (digitalocean, Docker 1.4.1, ubuntu precise) the problem occurs.

**Comment by Joel-fogue** [comment]
If anyone still has an issue with this error please check my proposed solution at this link: http://stackoverflow.com/questions/21001652/chrome-driver-error-using-selenium-unable-to-discover-open-pages/38700776#38700776

Look for the answer by pelican, hope that helps out someone!

**Comment by diemol** [comment]
Closing this issue as it got solved in the SO link provided above.
