### ISSUE TITLE
Upgrade chromedriver to 2.32

### ISSUE THREAD

**Issue by papegaaij** [SeleniumHQ/docker-selenium#560]
## Meta -
Image(s):  
standalone-chrome (chrome 61, chromedriver 2.31)

Docker-Selenium Image Version(s):  
3.5.3-astatine

## Description
Due to a bug in chromedriver 2.31, Chrome does not always scroll an element into view before clicking. This was fixed in 2.32. Please update the chromedriver. More information can be found here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1852

**Comment by papegaaij** [comment]
I just confirmed that downgrading to selenium/standalone-chrome:3.5.2 fixes the issues we have. 3.5.3 is totally unusable for us, failing almost 50% of the tests.

**Comment by ddavison** [comment]
[this](https://github.com/SeleniumHQ/docker-selenium/pull/545) was merged in yesterday which should fix that. let me push another release for 3.5.3 and that should fix the issue ;)

**Comment by DannyBen** [comment]
So will the fixed docker image have the same 3.5.3 tag? If so, can you please post here when the new one is on docker hub?

**Comment by dearmond** [comment]
He probably meant that he'll push "another release for 3.5", meaning 3.5.4. Looking forward to it! My tests are breaking all over the place now!

**Comment by gwhorley** [comment]
Guessing that he won't wait for selenium 3.5.4 and simply tags 3.5.3 with another element name

**Comment by dearmond** [comment]
Right. Thanks!

**Comment by jamesottaway** [comment]
Any update on updated images on Docker Hub? 3.5.3 still has v2.31 of Chromedriver:

```
$ docker pull selenium/node-chrome:3.5.3
3.5.3: Pulling from selenium/node-chrome
Digest: sha256:4165564835e6848539162ca5d8e9c6adc401589afec5157497375dec162cd714
Status: Image is up to date for selenium/node-chrome:3.5.3
$ docker run --rm -it selenium/node-chrome:3.5.3 chromedriver --version
ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8)
```

**Comment by picklelv** [comment]
Also waiting for image with 2.32 Chromedriver.

**Comment by ddavison** [comment]
chromedriver [downloads latest automatically](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile.txt#L30-L39) now.  try newest version
