### ISSUE TITLE
reset connectin by peer when im try to run selenium node 

### ISSUE THREAD

**Issue by DmtryJS** [SeleniumHQ/docker-selenium#565]
## Meta -
Image(s):  node-chrome-debug
Docker-Selenium Image Version(s):  2.53.1 
OS: Redhat

Hi. On the server CI stopped to download correctly and start the container selenium nodes
`sudo docker run -e TZ="Europe/Moscow" -d -P -p 127.0.0.1:5900:5900 --link selenium-hub:hub selenium/node-chrome-debug:2.53.1`

Today 13.09  container ceased to be downloaded and started correctly

## Expected Behavior -
The container has been downloaded and successfully launched

## Actual Behavior -
sudo docker run -d -P -p 172.30.54.91:5900:5900 --link selenium-hub:hub selenium/node-chrome-debug:2.53.1
Unable to find image 'selenium/node-chrome-debug:2.53.1' locally
Trying to pull repository registry.access.redhat.com/selenium/node-chrome-debug ...
Trying to pull repository docker.io/selenium/node-chrome-debug ...
/usr/bin/docker-current: Get https://registry-1.docker.io/v2/selenium/node-chrome-debug/manifests/2.53.1: read tcp 132.31.54.91:33992->51.2.185.86:443: read: connection reset by peer.
See '/usr/bin/docker-current run --help'.

**Comment by diemol** [comment]
Hi @DmtryJS,

Why are you using that docker registry URL and not https://index.docker.io/v1/? 

I just tried the pull and it works, the image is still there. I guess it is a network issue on your side.

**Comment by diemol** [comment]
Closing due to the lack of feedback. Feel free to reopen when more detailed information is provided.
