### ISSUE TITLE
Selenium base - docker - not built since 3.0.0

### ISSUE THREAD

**Issue by gbataille** [SeleniumHQ/docker-selenium#568]
## Meta -
Image(s):  
Base
Docker-Selenium Image Version(s):  
latest
OS: 

When my test on a docker cluster composed of the hub:latest image and the node-chrome:latest images, I see behaviour (checkbox click) that are consistent with **selenium 3.0.0** rather than the expected **3.5.3**

`selenium/hub:latest` is supposedly built from `selenium/base:3.5.3-astatine`
But it seems that `selenium/base` is **not built** anymore in dockerhub since 3.0.0

--> https://hub.docker.com/r/selenium/base/builds/
--> https://hub.docker.com/r/selenium/base/~/dockerfile/  --> (shows `https://selenium-release.storage.googleapis.com/3.0-beta4`)

That would explain why I don't have consistent behaviour between my local (which runs 3.5.3) and my docker cluster which runs hub:latest (supposedly 3.5.3) but which I guess actually runs 3.0.0. And since when I install 3.0.0 locally I get the same test behavior, that seems like a good possibility.

**Comment by diemol** [comment]
@gbataille 

The images are not built in the docker hub anymore, they are built in and pushed from Travis in every release. 

Please check https://hub.docker.com/r/selenium/base/tags/, the last one was pushed 7 days ago (3.5.3-boron). The other images are based on this one.

If you have an issue related to any given behaviour in Selenium, feel free to open an issue with the images you used, the docker command, and a test script to reproduce the issue.

**Comment by gbataille** [comment]
Hi Diego,

ok sorry for the wrong alert.
What's odd though is that on the cluster, I can't click on a checkbox that
is inside a label, and on local I reproduced it with 3.0.0 so it looked
really promising.
I'm back to square one then. Can't see what's the difference between my
local setup and the cluster one :(

Thanks

**Comment by diemol** [comment]
I would compare the ids of the images in your cluster and the ones locally to start. Also in the stacktrace of the error you can check the selenium version being executed.
