### ISSUE TITLE
selenium/node-firefox

### ISSUE THREAD

**Issue by pasha0070** [SeleniumHQ/docker-selenium#569]
1505637910553        addons.xpi      WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallSt

**Comment by diemol** [comment]
@pasha0070 

Can you please provide additional information?
- Which images are you using
- What docker command do you execute to start the containers?
- A test script to reproduce the error.

**Comment by diemol** [comment]
Closing since we didn't get feedback. Please feel free to reopen when enough info is provided.
