### ISSUE TITLE
[Question] How to run selenium within the container

### ISSUE THREAD

**Issue by dhanvi** [SeleniumHQ/docker-selenium#572]
## Meta -
Image(s):  standalone-chrome
Docker-Selenium Image Version(s): node-chrome:3.5.3-astatine [Dockerfile](https://github.com/SeleniumHQ/docker-selenium/blob/master/StandaloneChrome/Dockerfile)  
OS: OS Independent (Image's OS is Ubuntu 16.04)

I am trying to run selenium within the container but have little success. Here is my Dockerfile

```
FROM selenium/standalone-chrome

RUN cd /opt/bin && nohup bash entry_point.sh &

RUN sudo apt-get update && sudo apt-get install -y curl && curl http://0.0.0.0:4444/wd/hub/status
```
Form the image's [Dockerfile](https://github.com/SeleniumHQ/docker-selenium/blob/master/StandaloneChrome/Dockerfile) I understand entry_point.sh is the starting point, Am I missing something here ?
## Expected Behavior -
Curl request should return a json
## Actual Behavior -
Curl is throwing `Failed to connect to 0.0.0.0 port 4444: Connection refused`

**Comment by testphreak** [comment]
Not sure I completely follow what you are trying to do. Are you unable to stand up a Selenium Grid by following the steps [here](https://github.com/SeleniumHQ/docker-selenium#running-the-images)?

**Comment by dhanvi** [comment]
@testphreak I am trying to run the code within the container after the selenium server is up. (So I have started the script entry_point.sh)

Think of it as I am trying to run a hello-world selenium project with in the container. (I am using curl here to see just the selenium server's status).

**Comment by dhanvi** [comment]
Apologies, multiple RUN commands is the culprit here. Every RUN command is created in a different container and the previous container is stopped.
