### ISSUE TITLE
Unable to set SE_OPTS with 3.5.3 images. Fails with a ParameterException.

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/docker-selenium#574]
## Meta -
**Image(s):**  
hub, node-chrome, node-firefox
**Docker-Selenium Image Version(s):**  
3.5.3, 3.5.3-boron
**OS:** 
MacOS Sierra, Ubuntu 16.04

## Expected Behavior -

I want to set `SE_OPTS` with 3.5.3. For example: `-debug` on hub and nodes. Setting `SE_OPTS` works with 3.4.0 images.

## Actual Behavior -
Unable to set `SE_OPTS`. Hub and Node fail to star with the error below.

Command

```
docker run -d -p 4444:4444 -e GRID_MAX_SESSION=5 -e SE_OPTS="-debug true" --name selenium-hub selenium/hub:3.5.3
```

Logs
```java

starting selenium hub with configuration:
{
  "host": null,
  "port": 4444,
  "role": "hub",
  "maxSession": 5,
  "newSessionWaitTimeout": -1,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "jettyMaxThreads": -1,
  "cleanUpCycle": 5000,
  "browserTimeout": 0,
  "timeout": 30,
  "debug": false
}
appending selenium options: -debug true
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'true' but no main parameter was defined
	at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$2.setConfiguration(GridLauncherV3.java:245)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)

```

**Comment by lmtierney** [comment]
`-debug` was changed to be a flag that is true if passed, so just drop the `true` from your `SE_OPTS` and make it `SE_OPTS="-debug"`

**Comment by lmtierney** [comment]
https://github.com/SeleniumHQ/selenium/commit/8f325df6feb805f40990929ee01e3b8cd528b2a6#diff-951fbb9276fd3bcbea8c6555cffada2fR149

**Comment by testphreak** [comment]
@lmtierney thanks. I am still unable to set `-enablePassThrough false` on the `node`. Always defaults to true. Works with the `hub`.

Command

```
docker run -d -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 -e SE_OPTS="-debug -enablePassThrough false" -v /dev/shm:/dev/shm --link selenium-hub:hub selenium/node-chrome:3.5.3
```

Screenshot

![image](https://user-images.githubusercontent.com/10567800/30625701-985f8122-9d79-11e7-91a4-0ac853eaa3ec.png)

**Comment by lmtierney** [comment]
@testphreak I have a feeling that the web ui is just giving the wrong value. When you have it all up and running, try performing a `GET` to this and check the value of `enablePassThrough`:

```
http://172.17.0.2:4444/grid/api/proxy?id=http://172.17.0.3:5555
```

If your IPs have changed since you posted that config, the `GET` should be formed such as:

```
http://<hub url>:<hub port>/grid/api/proxy?id=<hub id>
```

**Comment by lmtierney** [comment]
Actually I take that back, that only gives you the original requested parameters. Your node should always be passthrough as the HUB will make the correct requests and the node should just pass them through as-is

**Comment by testphreak** [comment]
@lmtierney the debug log on both hub and node appears to confirm what you said. `enablePassThrough is true`

`
17:11:56.351 DEBUG - http-outgoing-0 >> "{"class":"org.openqa.grid.common.RegistrationRequest","name":null,"description":null,"configuration":{"hubHost":"172.17.0.2","hubPort":4444,"id":"http://172.17.0.3:5555","capabilities":[{"seleniumProtocol":"WebDriver","browserName":"firefox","maxInstances":5,"version":"55.0.3","applicationName":"","platform":"LINUX"}],"downPollingLimit":2,"hub":"http://172.17.0.2:4444/grid/register","nodePolling":5000,"nodeStatusCheckTimeout":5000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","register":true,"registerCycle":5000,"unregisterIfStillDownAfter":60000,"cleanUpCycle":null,"custom":{},"host":"172.17.0.3","maxSession":5,"servlets":[],"withoutServlets":[],"browserTimeout":0,"debug":false,"jettyMaxThreads":null,"log":null,"port":5555,"role":"node","timeout":30,"**enablePassThrough":true**}}"
`
