### ISSUE TITLE
'Latest' tags not pointing to the latest docker image

### ISSUE THREAD

**Issue by JoepWeijers** [SeleniumHQ/docker-selenium#581]
## Expected Behavior -
I expect the 'latest' tag to point to the 3.5.3-boron version.

## Actual Behavior -
The following images have their 'latest' pointing to an older version (~3.5.2 ish):
https://hub.docker.com/r/selenium/base/tags/
https://hub.docker.com/r/selenium/standalone-chrome-debug/tags/
https://hub.docker.com/r/selenium/standalone-firefox-debug/tags/
https://hub.docker.com/r/selenium/node-phantomjs/tags/

**Comment by ddavison** [comment]
thanks for reporting this. confirmed that this is an issue - investigating.

**Comment by diemol** [comment]
Hi @JoepWeijers,

After releasing [3.6.0-americium](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.6.0-americium), the `latest` tags are back to normal.

@ddavison I checked the Travis build and the tagging looked fine to me, not sure why it happened. Unless you have something else to add, I guess we can close this issue.

**Comment by JoepWeijers** [comment]
Thanks, seems OK now.

**Comment by ddavison** [comment]
yea.. some weird anomaly.   if it happens again, we'll re-release said image
