### ISSUE TITLE
Do you know semver?

### ISSUE THREAD

**Issue by Pierozi** [SeleniumHQ/docker-selenium#585]
Guys do you know what semver is for real?

You cannot accept to bump chromium driver without increasing, **AT LEAST**, the patch version.
Having a BC break between 3.4.0-chromium and 3.4.0-francium is unacceptable.
 
Related : #559

**Comment by lmtierney** [comment]
https://github.com/SeleniumHQ/docker-selenium/wiki/Tagging-Convention

**Comment by Pierozi** [comment]
Right, and this is not semver...

**Comment by Pierozi** [comment]
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

**Comment by lmtierney** [comment]
Was there somewhere stating that the project follows this exactly?

If a new chromedriver comes out that supports the new Chrome version that came out, you want to wait until the selenium project itself comes out with a new release even if using Chrome is broken without it?

**Comment by Pierozi** [comment]
You are not forced to follow the Selenium version, the think is between two tags with the same PATCH version you iterate some changes.

If the `-<Chemical Element in Alphabetical order>` was only to identify new build on same github tag, to identify an immutable image state, that's fine.

But introduce an update of chrome driver (or any other change actually) is not.

**Comment by ddavison** [comment]
We follow the versioning of selenium, and make small "patch" updates by updating the `-<element>` of the specific selenium version we are going against.

Selenium follows semver, and the docker-selenium does its best with what we have.  if you have a better alternative, feel free to file a PR.  if not, then this process is not going to change unless you provide some sort of valid explanation / reasoning / alternative.

**Comment by EricTheRed-VT** [comment]
Selenium does not follow semver at all. 
https://github.com/SeleniumHQ/selenium/commit/8c9d0185e220e55d12071acb58913c2c8f80ee8d#commitcomment-32222018
