### ISSUE TITLE
Node Chrome Headless Timeout

### ISSUE THREAD

**Issue by mitchellmaler** [SeleniumHQ/docker-selenium#588]
## Meta -
Image(s):  
node-chrome:latest
Docker Version:  17.09.0-ce-win32
OS: Windows 10

Hello, I am trying to prove out using Selenium Grid using docker and ran into a snag with running the chrome tests. The code for the webdriver is in C# and setup to run Chrome headlessly with something like this: 
```
ChromeOptions chromeHeadlessGridOptions = new ChromeOptions();
chromeHeadlessGridOptions.AddArgument("incognito");
chromeHeadlessGridOptions.AddArgument("headless");
chromeHeadlessGridOptions.AddArgument("disable-gpu");
chromeHeadlessGridOptions.AddArgument("no-sandbox");
chromeHeadlessGridOptions.AddArgument("start-maximized");
WebDriver = new RemoteWebDriver(HubUri, chromeHeadlessGridOptions.ToCapabilities());
```
The issue is when I leave in the headless and disable-gpu using the latest node-chrome it wont run. It just times out 
HUB LOG: 
```
21:24:53.609 INFO - Got a request to create a new session: Capabilities [{goog:chromeOptions={args=[incognito, headless, disable-gpu, no-sandbox, start-maximized]}, browserName=chrome, platformName=ANY, version=, platform=ANY}]
```

NODE LOG:
```
21:25:15.919 INFO - /session: Executing POST on /session (handler: BeginSession)
21:25:15.920 INFO - Capabilities are: Capabilities {goog:chromeOptions={args=[incognito, headless, disable-gpu, no-sandbox, start-maximized]}, browserName=chrome, platformName=ANY, version=, platform=ANY, }
21:25:15.921 INFO - Capabilities {goog:chromeOptions={args=[incognito, headless, disable-gpu, no-sandbox, start-maximized]}, browserName=chrome, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
21:25:15.921 INFO - Capabilities {goog:chromeOptions={args=[incognito, headless, disable-gpu, no-sandbox, start-maximized]}, browserName=chrome, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351) on port 1585
Only local connections are allowed.
```
and the tests all fail due to a server timeout with the web driver.

If I remove those two arguments in the code the RemoteWebDriver is generated and all the tests run on the node.

## Expected Behavior -
Selenium Tests run on chrome node with the headless mode and disable-gpu arguments.
## Actual Behavior -
Node does not run tests with those arguments but will is they are removed.

**Comment by Lgalan90** [comment]
I am also receiving the error: Starting ChromeDriver 2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351) on port 31324
Only local connections are allowed.

But I only receive it when I run the Selenium as a service, When I run it using the command line it creates the sessions successfully for each of the browser along with it's driver installed on the machine. I still have not found a solution but I'll follow this thread in case of any news.

**Comment by diemol** [comment]
Hi @mitchellmaler @Lgalan90,

Were you using tag 3.6.0-bromine? The wrapper to launch Chrome changed in this version (we were using a very old one). Also we have Chromedriver 2.33 in that release.

If you used a previous release, could you please try again?

**Comment by mitchellmaler** [comment]
I just updated the tag to the latest and that fixed this issue. I'll need to pay more attention when new releases come out! 
Thanks!

**Comment by diemol** [comment]
Great! Closing the issue then.
