### ISSUE TITLE
Can't print page

### ISSUE THREAD

**Issue by khalistan** [SeleniumHQ/docker-selenium#592]
I am trying to print page with `window.print();`. It opens a pdf print view but then suddenly get closed.
If I use chrome driver without docker, then its working.
--->
I am using docker: node-chrome-debug which is working perfect. On my test page there is one link, if you click on that it just open a chrome window to print that page. where you can save that page as PDF.
To try this, just open chrome and navigate to e.g  https://www.amazon.de/ . Now in console just enter `window.print();` . You will see a print option page. This page is not opening in docker chrome node. Its opens for a few seconds and then get closed itself.
<-----Thanks for any info or help
## Meta -
Image(s):  selenium/node-chrome-debug 3.5.3, selenium/hub 3.5.3

Docker-Selenium Image Version(s):  

Docker Version:  17.07.0-ce

OS: Linux

## Expected Behavior -
Same way as firefox is capable for bringing option to view page as PDF and download as PDF, chrome should also do. Chrome only get closed in docker, without docker selenium/chrome driver can show page as PDF and can be downloaded as PDF.
## Actual Behavior -
This functionality works perfect with selenium/node-firefox:3.5.3-boron
## Commands used -
```
docker pull selenium/hub
docker pull slenium/node-chrome-debug
docker pull selenium/node-firefox-debug

docker run -d -p 4446:4444 --name selenium-hub -P selenium/hub
docker run -d -P --link selenium-hub:hub selenium/node-chrome-debug
docker run -d -P --link selenium-hub:hub selenium/node-firefox-debug
```

**Comment by diemol** [comment]
Hi @khalistan,

Can you please provide more information? docker-image used, docker command, a script to reproduce the test case? It is not so easy for us to help without enough information.

PS: Why did you delete the issue template? :)

**Comment by khalistan** [comment]
I have added more info. 👍

**Comment by diemol** [comment]
Hi again @khalistan,

I just followed your instructions with the recent release `3.6.0-darmstadtium`, like this:

* `docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug:3.6.0-darmstadtium`
* Went inside the container via VNC
* Opened Chrome
* Went to www.google.com in the browser, opened the DevTools
* Typed `window.print()` on the console, and the print page opened and stayed there. It did not close.

I am not sure if this was broken in an earlier version of Chrome, but I am pretty sure that version 3.5.3 had a give version of Chrome installed, and in your machine there was a different version installed.

So, please try it again with the most recent release and let us know how it went.

**Comment by khalistan** [comment]
ok I will try again

**Comment by khalistan** [comment]
I tried your version but problem is still there. If we try print on Google its working as Google Homepage is very light. Try on https://www.amazon.de/  <-- here it driver will crash as Amazon website have more content as compare to Google.
@diemol

**Comment by diemol** [comment]
Oh sorry, when I tried it the first time I forgot to add the `/dev/shm` part. Without that it won't work as you say.

Please try it with it, like this:

`docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.6.0-darmstadtium`

and then it works, even with the page you mention.

**Comment by khalistan** [comment]
yes, now its working perfect. You may close this issue. Thanks.

**Comment by diemol** [comment]
Thanks for the feedback @khalistan
