### ISSUE TITLE
Node chrome will fail to take screenshot

### ISSUE THREAD

**Issue by straris** [SeleniumHQ/docker-selenium#593]
## Meta
Image(s):  
node-chrome
Docker-Selenium Image Version(s):  
3.6.0-bromine
Docker Version:  
17.06.2
OS: 
Ubuntu 17.10 64bit
## Description
An attempt to take a screenshot with node-chrome will fail with `Unable to receive message from renderer`
- At first I thought it was a chrome driver issue but running the same versions of chrome driver and selenium outside of docker showed no problems (driver 2.33 & selenium 3.6.0).

- node-firefox had no problem either.

**Comment by diemol** [comment]
Hi @straris,

Is this issue present only in the headless image? Did you try with the node-chrome-debug image?

**Comment by straris** [comment]
@diemol indeed tried with both images.
Also 3.6.0-copper

**Comment by straris** [comment]
Closing this, it was because I run the container without `-v /dev/shm:/dev/shm`

**Comment by diemol** [comment]
thanks for the feedback @straris!
