### ISSUE TITLE
Fails to build standalone-chrome-debug (missing node-chrome-debug dependency)

### ISSUE THREAD

**Issue by eitany** [SeleniumHQ/docker-selenium#599]
## Meta -
Image(s):  
standalone-chrome-debug
Docker-Selenium Image Version(s):  
3.6.0-copper
Docker Version:  
1.8.2
OS: 
OSX Yosemite

## Actual Behavior -
Docker build fails, missing dependency node-chrome-debug

**Comment by diemol** [comment]
Hi @eitany,

Good catch, I was able to reproduce it. I made some comments to your PR #600, please solve them and we can merge.

Thanks!

**Comment by diemol** [comment]
#600 was merged, so closing this issue.
Thanks @eitany
