### ISSUE TITLE
Docker entry_point fails to execute due to missing permissions

### ISSUE THREAD

**Issue by eitany** [SeleniumHQ/docker-selenium#601]
## Meta -
Image(s):  
standalone-chrome-debug
Docker-Selenium Image Version(s):  
3.6.0-copper
Docker Version:  
1.8.2
OS: 
OSX Yosemite

## Expected Behavior -
Docker container running

## Actual Behavior -
oci runtime error: exec: "/opt/bin/entry_point.sh": permission denied

**Comment by diemol** [comment]
Hi @eitany,

How can I reproduce that? I just tried to run a container with the command:

```
docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug:local
```

after building the image with the changes you submitted in #600 and I don't get the error.

**Comment by eitany** [comment]
It seems to have been a local issue, I am closing the Issue
