### ISSUE TITLE
Chrome processes not always closed

### ISSUE THREAD

**Issue by AndreSteenbergen** [SeleniumHQ/docker-selenium#605]
## Meta -
Docker-Selenium NodeChrome:lateste
Docker Version: 17.09.0-ce
OS: Ubuntu 16.04

## Issue -
When sessions are lost because, timeouts chrome crashes etc. It seems the chrome node does not properly handle closing the chrome processes. I have a docker hub and 2 nodes with both 5 instances and 5 max sessions. I use the nodes as long running processes to make screenshots of websites.

After a longer period of time I am running `ps aux |  grep chome | wc -l` on the docker host. I rarely see figures below 100 chrome processes, after about 1 hour or so. I don't mind sessions crashing for whatever reason, but I think it is strange I see so many chrome processes.

## Expected Behavior -
number of chrome processes equal or lower then max_instances

## Actual Behavior -
number of chrome processes a lot higher then max instances

**Comment by diemol** [comment]
Hi @AndreSteenbergen,

I guess you are mounting `-v /dev/shm:/dev/shm`? This should reduce the amount of crashing pages and "lost" Chrome processes.

And even if you are sharing it, I don't discard that the page is too heavy and after a while working on it Chrome crashes as well. 

The thing is the containers are thought to be short lived, that is why they don't have any recovery/cleaning logic in them. In a normal (non-container) grid, you have normally those problems with zombie processes. The usual approach in docker-selenium, is just to throw away that container and start a new one.

Nevertheless, if you have any suggestions or an idea how to improve this, we can discuss them and perhaps we would be happy if that ends up with a PR.

**Comment by AndreSteenbergen** [comment]
Thx for the pointer about shared memory. I actually forgot to mount shm. It is already quite a lot better. I guess I'll add a cronjob to kill containers running longer then two hours.

**Comment by diemol** [comment]
Cool! That is nice to know. 
Should we keep this issue open?
PS: Thanks for your interest in commenting and contributing to other issues.

**Comment by AndreSteenbergen** [comment]
I'll close the issue
