### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:5902: bind: address already in use 

### ISSUE THREAD

**Issue by simplyviks** [SeleniumHQ/docker-selenium#608]
## Meta -
Image(s):  
standalone-firefox
Docker-Selenium Image Version(s): 
3.4.0
Docker Version:  
Version:      17.03.0-ce

OS: 
Ubuntu 16.04

ERROR: for selenium-server Cannot start service selenium-server: driver failed programming external connectivity on endpoint selenium-server (d0180123fa634d472b4ce1a1be38558117686bb10bc192aacde8da4f7f427b38): Error starting userland proxy: listen tcp 0.0.0.0:5902: bind: address already in use 

## Expected Behavior -

docker container should start
## Actual Behavior -
container failed to start

**Comment by simplyviks** [comment]
Hi @diemol 
Thanks for responding. 

I use docker-compose utility to start the containers.
EG:docker-compose -f compose file start
FYI, No other service in the environment uses the port 5902,so is there any leaks on port release?

**Comment by diemol** [comment]
@simplyviks
Can you please share the docker-compose file as well?

**Comment by simplyviks** [comment]
I cannot share the entire docker file   :)

below is the service.

   selenium-server:
        image: ${env.getValue("docker_config.artifactory_url")}/selenium-standalone-firefox-debug:3.4.0
        container_name: selenium-server
        shm_size: 2g
        restart: always
        ports:
            - "4444:4444"
            - "5902:5900"
        stdin_open: true
        tty: true
        networks:
            - XXX_net
        logging:
            driver: fluentd
            options:
                fluentd-address: "0.0.0.0:24224"
                tag: "docker.{{.ID}}"
        depends_on:
            - fluentd

**Comment by diemol** [comment]
Sorry, but if we cannot see how you are starting the containers with the full docker-compose file, or a similar one to reproduce the issue, how could we help?

**Comment by tparikka** [comment]
@simplyviks Are you using Docker for Windows? If so, can you please look at docker/for-win#426 and let us know if this is the issue you are encountering? There is a known defect in Docker on Windows related to vpnkit that causes sockets placed under heavy load to fail, and become locked until the entire Docker service is terminated and restarted.

**Comment by diemol** [comment]
Closing this one as the OP didn't give us enough info to help. Feel free to reopen when more information is provided.
