### ISSUE TITLE
SeleniumHQ/docker-selenium for windowes

### ISSUE THREAD

**Issue by barahate90** [SeleniumHQ/docker-selenium#610]
Hello Team , 

Anyone here tried to convert the docker-selenium in windows ?.
If yes can you please help by sharing samples .

**Comment by diemol** [comment]
Hi @barahate90,

Currently there is no support for windows images in docker, there was an request [here](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214), but it was declined.

I'd recommend that you ask questions like this one in the [Selenium Users Group](https://groups.google.com/forum/#!forum/selenium-users) or in the [IRC/Slack channel for Selenium](https://seleniumhq.herokuapp.com/). 

It is not really intended to have this space as a forum or a generic space to exchange ideas, but rather to report specific bugs or provide concrete improvements to the project. Thus, I'll close this issue.
