### ISSUE TITLE
Firefox  container GUI is not visible using VNC

### ISSUE THREAD

**Issue by barahate90** [SeleniumHQ/docker-selenium#615]
## Meta -
Image(s):  
selenium/standalone-firefox-debug:3.7.1-beryllium 
OS: 
Red hat 7

## Expected Behavior -

Trying to run following command and as a result it should map Firefox with VNC .
when trying to open Firefox using VNC  GUI should be displayed for Firefox .

command :
sudo docker run -d -p 4442:4444 -p 5913:5900 selenium/standalone-firefox-debug:3.7.1-beryllium

## Actual Behavior -

VNC port mapping is done properly .
Able to open the VNC screen .
FF browser is not opening . 

command used   : sudo docker run -d -p 4442:4444 -p 5913:5900 selenium/standalone-firefox-debug:3.7.1-beryllium

![ff_container](https://user-images.githubusercontent.com/3815898/33167887-0290bb9a-d00d-11e7-932d-c8f7301fcb91.PNG)

**Comment by diemol** [comment]
Hi @barahate90,

You can start Firefox manually by opening a shell and typing `firefox`.

![image](https://user-images.githubusercontent.com/5992658/33172646-4720b1f4-d051-11e7-9e70-a2e422752460.png)

![image](https://user-images.githubusercontent.com/5992658/33172770-be41bcc4-d051-11e7-936e-33326a2f572f.png)

**Comment by barahate90** [comment]
@diemol  : Great !!, It didn't clicked me that point of time . Appreciate your work  .

**Comment by diemol** [comment]
Glad it worked! Thanks for the feedback.

**Comment by RuslanSkiraRaccoongang** [comment]
Hello manually it opened but selenium steal didn't see it.
