### ISSUE TITLE
When will a node container be ended and removed?

### ISSUE THREAD

**Issue by coodoo** [SeleniumHQ/docker-selenium#62]
As stated in the readme, `I like to remove the containers after each e2e test with --rm since this docker container is not meant to preserve state`, I'm wondering when will each node container be stopped and removed? From what I see so far the node container simply continue running when the all test suites are completed.

**Comment by rubytester** [comment]
I am trying to understand your use case. 

You can run those containers however you wish. This project builds containers and shows you examples of how you can run a hub and how you can link a node to the hub.

If you no longer need to run a node you can stop it and remove it with `docker` cli. 

Containers run until you want them stoppped, removed, nuked etc...

**Comment by coodoo** [comment]
Yep, figured it out yesterday and thanks for answering.
