### ISSUE TITLE
standalone chrome  debug not able to launch in VNC

### ISSUE THREAD

**Issue by barahate90** [SeleniumHQ/docker-selenium#620]
## Meta -
Image(s):  
https://hub.docker.com/r/selenium/node-chrome/~/dockerfile/
Docker Version:  

OS: 
Red hat 7

## Expected Behavior -
Trying to create standalone-chrome-debug for beta version 63.*.*

1) 
Instead of  ARG CHROME_VERSION="google-chrome-stable" this  is my 
ARG CHROME_VERSION="google-chrome-beta" .

2) ${CHROME_VERSION:-google-chrome-stable} replaced with  ${CHROME_VERSION:-google-chrome-beta}.

3)I have  build the new node chrome file after the above changes.

4)with the new node-chrome file , I have build the new node-chrome-debug file.

5)I am using new node-chrome-debug file to build standalone-chrome-debug file.

Now when I run the built image  , It is successfully launching the container.

command I am using  
docker run -d -p 4444:4444 -p <port4VNC>:5900 selenium/standalone-chrome-debug:3.7.1-beryllium

Both the headless  browser expose at 4444 and for VNC should work fine.

-I am able launch the newly build Node-chrome  and Node-Chrome-debug.

## Actual Behavior -
Standalone-chrome-debug image build from newly create Node-Chrome and Node=Chrome-Debug , As this image individually working fine with VNC and Grid registration .

![vnc -error](https://user-images.githubusercontent.com/3815898/33271215-9e00393a-d354-11e7-988b-426579611e9f.PNG)

**Comment by diemol** [comment]
Hi @barahate90,

I tried to reproduce it but it was not possible, here are the steps I went through: 

- I removed all the images from my laptop

![image](https://user-images.githubusercontent.com/5992658/33328395-2f044286-d45a-11e7-9e44-0fc39b55d7da.png)

- I executed this command:

```
VERSION=local BUILD_ARGS="--build-arg CHROME_VERSION=google-chrome-beta" make standalone_chrome_debug
```

- And that command created the following images:

![image](https://user-images.githubusercontent.com/5992658/33329438-de0e90ae-d45c-11e7-90c8-42cc8a73dc1e.png)

- So I went to use the standalone-chrome-debug image that was just created with the command:

```
docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:local
```

- I am on OSX, so I executed `vncviewer localhost:5900`

- And then I went inside the container and opened Chrome, beta is installed:

![image](https://user-images.githubusercontent.com/5992658/33329688-549cedf6-d45d-11e7-88d4-74884911a7a9.png)

Please double check the commands you used, and let us know how it went.

**Comment by barahate90** [comment]
@diemol :  I was not dealing with Make file in right way. Thank you for right direction 

Works fine !!

**Comment by diemol** [comment]
Cool, thanks for the feedback @barahate90.
