### ISSUE TITLE
Run with SELinux without --privileged

### ISSUE THREAD

**Issue by tnguyen14** [SeleniumHQ/docker-selenium#631]
In order to run `node-chrome`, I need to mount `/dev/shm` into the container. In RHEL boxes with SELinux, this doesn't work without the `--privileged` flag.

In order to get around SELinux issues, I created this SELinux policy module:

```
module dockershm 1.0;

require {
	type tmpfs_t;
	type svirt_lxc_net_t;
	class file { create open unlink };
	class dir { add_name remove_name write };
}

#============= svirt_lxc_net_t ==============

allow svirt_lxc_net_t tmpfs_t:dir { add_name remove_name write };
allow svirt_lxc_net_t tmpfs_t:file { create open unlink };
```
You could try this out by saving the above snippet to a file named `dockershm.te`,  then run
```
make -f /usr/share/selinux/strict/include/Makefile dockershm.pp
semodule -i dockershm.pp
```

After this, I no longer see any SELinux denied messages in `/var/log/audit/audit.log` anymore. However, the test script still cannot connect to the selenium server. 

The only way to get it to work is to run the selenium container with `--privileged` flag.

Is there anything that I might be missing that could be preventing docker selenium from being run without `--privileged`?

On my Mac, I can run it without `--privileged` and it still works fine.

**Comment by diemol** [comment]
Hi @tnguyen14,

Yes, the image should work without the need of `--privileged`, I had no clue that it was needed in SELinux (since you need to mount `/dev/shm`).

Let me ask two questions:
- Is the test environment too sensitive that you cannot use `--privileged`? 
- What happens if you set the shm size instead of mounting it? E.g. `docker run ... --shm-size=2g`

**Comment by tnguyen14** [comment]
Yeah if I run it with `shm_size='2gb` option without privileged it does work.

**Comment by diemol** [comment]
Good! The effect should be the same one.
I think we can close this issue then, right?

**Comment by tnguyen14** [comment]
If the effect is the same, should the doc be updated to say that `shm-size`
should be used for both Chrome and Firefox?

**Comment by diemol** [comment]
I updated the README to highlight the importance of using either `/dev/shm` or `--shm-size`.

Both work and have the same effect, I guess that there are cases like the one you mention where only one works.

I'll close the issue since we documented it better.

**Comment by tnguyen14** [comment]
Amazing! Thanks!
