### ISSUE TITLE
Feature request: noVNC type remote viewing

### ISSUE THREAD

**Issue by danbo** [SeleniumHQ/docker-selenium#632]
Is it possible / an option to have these images support viewing the remote desktop via the browser instead of using a VNC client, similar to the following:

https://github.com/ConSol/docker-headless-vnc-container

**Comment by diemol** [comment]
Hi @danbo,

I know it is helpful to have something like that, but so far we have seen it is not a common use case and the need is supplied with VNC clients. Overall, what we try to do is to keep the images as generic as possible.

If you really need this feature, why don't you try this image: https://github.com/elgalu/docker-selenium, it has the feature you are looking for.

**Comment by diemol** [comment]
PS: Thanks for the link in your comment, looks interesting and I didn't know those images.
