### ISSUE TITLE
Chrome extensions not loading in 3.8+

### ISSUE THREAD

**Issue by Zechtitus** [SeleniumHQ/docker-selenium#642]
I found I have been unable to load chrome extensions in node-chrome-debug 3.8+. I was able to verify this by going to the chrome://extensions url and take a screenshot

node-chrome-debug 3.8+
![screen shot 2017-12-27 at 10 57 09 am](https://user-images.githubusercontent.com/10325856/34389128-23ac409e-eaf5-11e7-9668-dad6b51320e9.png)

node-chrome-debug 3.7
![screen shot 2017-12-27 at 11 07 54 am](https://user-images.githubusercontent.com/10325856/34389333-4a9f1220-eaf6-11e7-87d7-70c1b4665546.png)

**Config**:
I am using nightwatch to drive the tests. Here is my config (the encoding method can be included as well but it simply converts to a base64 string.
```

      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: [
            '--no-sandbox',
            '--disable-popup-blocking',
            '--disable-infobars',
          ],
          useAutomationExtension: true,
          extensions: [
            common.encode('./extensions/ModHeader_v2.1.2.crx'),
            common.encode('./extensions/Private-Internet-Access_v1.4.0.crx'),
          ],
          prefs: {
            credentials_enable_service: false,
            profile: {
              password_manager_enabled: false,
            },
          },
        },
```
Additional Info:
I also tried loading exensions with the --load-extension flag in desiredCapabilities. The same result occurred. 3.7 works, 3.8+ I do not see the extensions being loaded.

**Expectation**:
I should be able to load extensions in node-chrome-chrome 3.8 +, currently have to lock version to 3.7 for some tests which use extensions to run.

**Comment by Zechtitus** [comment]
as an update to this. Turns out my issue was from using chromeOptions instead of 'goog:chromeOptions' in desiredCapabilities.

**Comment by ddavison** [comment]
glad you got it working!
