### ISSUE TITLE
chrome connection refused but wget works

### ISSUE THREAD

**Issue by zuernBernhard** [SeleniumHQ/docker-selenium#644]
## Meta -
Image(s):  
selenium/standalone-chrome-debug:3.8.1-bohrium
Docker-Selenium Image Version(s):  
selenium/standalone-chrome-debug:3.8.1-bohrium
Docker Version:  
Docker version 17.12.0-ce-rc4, build 6a2c058
![bildschirmfoto 2018-01-03 um 12 58 48](https://user-images.githubusercontent.com/1442798/34519794-272e51a8-f086-11e7-8a64-6f0f7258d0c9.png)

OS: 
OSX High Sierra

## Expected Behavior -
Browser can reach Host
## Actual Behavior -
Connection refused in chrome browser - no entry in the hosts apache access log

**Comment by diemol** [comment]
Hi @zuernBernhard,

You are facing this issue: https://github.com/SeleniumHQ/docker-selenium/issues/511

Anything with `localhost` Chrome will resolve it locally, try to change that entry to something different.

**Comment by zuernBernhard** [comment]
Yes you are right. Thanks a lot ! I worked around it by using xip.io

**Comment by diemol** [comment]
Glad it worked out!
