### ISSUE TITLE
Firefox crashes on selenium/node-firefox 3.8.1 image

### ISSUE THREAD

**Issue by AlinaIo** [SeleniumHQ/docker-selenium#650]
## Meta -
Image(s):  selenium/node-firefox 3.8.1

Docker-Selenium Image Version(s):  selenium/hub 3.8.1

Docker Version:  Docker version 17.12.0-ce, build c97c6d6

OS: Linux etc-VirtualBox 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior -
Should not crash.

## Actual Behavior -
Firefox browser crashes when trying to execute login action to a specific site.
I can even reproduce manually without running the automated test. 
I cannot reproduce that on other Firefox except the one in the node-firefox container.
Steps to reproduce:
1. Go to https://shop.haufe.de/
2. Click on account icon -> "Zur Anmeldung"
3. Login with following user: driver@mailinator.com and pass: 123456 -> "Anmelden" 
=> Firefox crashes

Let me know if you need help reproducing this.

**Comment by ddavison** [comment]
hey @AlinaIo thanks for your report.

Could you do us a favor and provide a script that we can run, as well as your docker run command or docker-compose file.  

This will help us immensely, and we can figure this out.

Thanks! 👍

**Comment by AlinaIo** [comment]
Hey @ddavison <https://github.com/ddavison>

I have extracted from our framework the script we are running. Please find
attached. The commented parts are extra options we are using, but I
couldn't find one that breaks things. I left them there so you can
un-comment them and try.
When I initially tried with the new, extracted from the framework script,
it actually worked. But after some time, after trying multiple times it
started failing and the browser crashing.
The docker-compose.yml file is also attached. I am running the test from my
local Intellij.

I am using VNC Viewer extension from Google to see what happens inside the
container. And here is a screenshot with the browser crashing when I start
it manually from shell and try to run the test. Maybe the error displayed
there will help.

Let me know if you need more info. Or we can make a video call and debug,
if necessary.

[image: Inline image 1]

Thank you,
Alina

**Comment by diemol** [comment]
Hi @AlinaIo,

Can you please post the script directly on the GitHub issue? Attachments per email don't work.

Please also show us how you are starting the containers (docker run... commands).

**Comment by AlinaIo** [comment]
Hi, Sorry about that. This should be better :)

docker-compose.yml

===============
```
version: '2'
services:
  hub:
    image: selenium/hub:3.8.1
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox-debug:3.8.1
    privileged: true
    dns:
       - 10.12.1.147
    environment:
      - TZ=DE
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    ports:
      - 5900
```
===================

I run that like this:
`docker-compose up -d hub firefox`

=========================

The test that I run from my local Intellij.
I have extracted from our framework the script we are running. The commented parts are extra options we are using, but I couldn't find one that breaks things. I left them there so you can un-comment them and try.
When I initially tried with the new, extracted from the framework script, it actually worked. But after some time, after trying multiple times it started failing and the browser crashing.

```
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;

import static java.lang.Thread.sleep;

public class TestFirefox {
    @Test
    public void test_firefox_crash() throws InterruptedException, MalformedURLException {
//        FirefoxProfile fp = new FirefoxProfile();
//        fp.setPreference("browser.startup.homepage", "about:blank");
//        fp.setPreference("startup.homepage_welcome_url", "about:blank");
//        fp.setPreference("startup.homepage_welcome_url.additional", "about:blank");
        FirefoxOptions fo = new FirefoxOptions();
//        fo.setLogLevel(FirefoxDriverLogLevel.TRACE);
//        fo.setProfile(fp);
//        fo.setCapability("overlappingCheckDisabled", true);
//        System.setProperty("webdriver.firefox.logfile", "/dev/null");
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), fo);

        driver.get("https://shop.haufe.de/");
        driver.findElement(By.id("headerAccount")).click();
        sleep(1000);
        driver.findElement(By.partialLinkText("Zur Anmeldung")).click();
        sleep(1000);
        driver.findElement(By.id("regEmail")).sendKeys("driver@mailinator.com");
        driver.findElement(By.id("password")).sendKeys("123456");
        sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"nextTop\"]")).click();
//        Actions builder = new Actions(driver);
//        WebElement loginButton = driver.findElement(By.xpath("//*[@id=\"nextTop\"]"));
//        if (driver.findElements(By.xpath("//*[@id=\"nextTop\"]")).size() > 0) {
//            builder.click(loginButton).build().perform();
//        }
        sleep(10000);
        //Fails here. After clicking on Login button.
        driver.findElement(By.xpath("//a[@class='btn_headerAccount active icon']")).isDisplayed();
        driver.quit();
    }
}
```
==============

I am using VNC Viewer extension from Google to see what happens inside the container. And here is a [screenshot](https://drive.google.com/open?id=1xNmXXqP13fAMUc32nQJK7NWq92Rp8_D3) with the browser crashing when I start it manually from shell and try to run the test. Maybe the error displayed there will help.

Let me know if you need more info. Or we can make a video call and debug, if necessary.

**Comment by diemol** [comment]
I haven't tried the code, but after checking the docker-compose file, I think the `/dev/shm:/dev/shm` mount is missing.

Can you please check this docker-compose sample, add the mount in yours and try again?
https://github.com/SeleniumHQ/docker-selenium#via-docker-compose

**Comment by AlinaIo** [comment]
Seems like this was the problem. Thank you so much for looking into this. You can close the issue.

**Comment by diemol** [comment]
Cool, I am glad it works for you!
