### ISSUE TITLE
Unable to set the user agent v3.8.1

### ISSUE THREAD

**Issue by psmod2** [SeleniumHQ/docker-selenium#655]
## Meta -
Image(s):  
node-chrome, hub
Docker-Selenium Image Version(s):  
3.8.1
Docker Version:  
17.09.0-ce
OS: 
Centos6

Is there a known issue with applying the user agent and v3.8.1

I've set a user agent which I am able to confirm in the Hub logs:

`INFO - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [user-agent=testx, window-size=420,800]}, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 5, proxy: {httpProxy: , proxyType: autodetect, sslProxy: }, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.10.1}, rotatable: true}`

## Expected Behavior -
The user agent should be applied

## Actual Behavior -
However it is not as I am taking a screenshot and it shows a version without the user agent

**Comment by diemol** [comment]
Hi @psmod2,

I see that the sent capability is named `chromeOptions`, could you please try again with `goog: chromeOptions`?

**Comment by psmod2** [comment]
Great. All good now!
Also found this 'vendor-prefixed' detail here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1786
