### ISSUE TITLE
Uploads with non-Latin characters do not work correctly

### ISSUE THREAD

**Issue by individual-it** [SeleniumHQ/docker-selenium#657]
## Meta -
Image(s):  
selenium/standalone-chrome
Docker-Selenium Image Version(s):  
 	3.8.1-erbium
Docker Version:  
17.12.0-ce, build c97c6d6
OS: 
Ubuntu 17.04

## Expected Behavior -
Uploads with non-Latin  characters should work
## Actual Behavior -
When uploading a file with non-latin characters e.g. `äé` they are converted into a `?`

This happens on selenium/standalone-chrome but not on selenium/standalone-chrome-debug
When login interactively into the container I notices that `$LANG` is not set. But it is in the selenium/standalone-chrome-debug container.
I run into the same problem when I'm setting `export LANG=C` on my local machine before starting selenium.

**Comment by diemol** [comment]
Hi @individual-it,

You are right. I don't know why the Dockerfiles are like that but it makes sense to change them so the `LANG` is set properly.

We are evaluating to merge both normal and debug images, depending if there is a performance impact or not. That would solve several issues that come from slightly different configurations.

We'll figure it out in the following weeks, for now please use the debug image. I'll leave this issue open until we decide about merging the images.

**Comment by diemol** [comment]
I just moved the config to the normal images from the debug images, since this is causing different behaviours which should not be the case.

It will be released soon.
