### ISSUE TITLE
Selenium 2.46

### ISSUE THREAD

**Issue by chris-orchard** [SeleniumHQ/docker-selenium#66]
Are you updating the image to 2.46 now it's out?

**Comment by elgalu** [comment]
Closing as duplicate of https://github.com/SeleniumHQ/docker-selenium/pull/65

**Comment by chris-orchard** [comment]
Sorry I searched for '2.46' not '2.46.0' so the existing issue didn't come up

**Comment by elgalu** [comment]
No problem ;)
