### ISSUE TITLE
Passing download.default_directory pref to chrome in hub/node setup no longer works

### ISSUE THREAD

**Issue by shames0** [SeleniumHQ/docker-selenium#663]
Attempting to pass preferences to the chrome instance like this no longer works when using the Docker-selenium **hub/node** setup (ruby):
```
$download_subfolder = SecureRandom.uuid.split(pattern="-")[4]
capabilities  = Selenium::WebDriver::Remote::Capabilities.chrome(
    'chromeOptions' => {
        'prefs' => {
            'download.default_directory'   => "/home/seluser/Downloads/#{$download_subfolder}",
            'download.prompt_for_download' => false,
            'plugins.plugins_disabled'     => ['Chrome PDF Viewer']
        }
    }
)

driver = Selenium::WebDriver.for(
    :remote,
    :desired_capabilities => capabilities,                                                                                                                                                                         
    :url                  => 'http://selenium_hub:4444/wd/hub'
)
```
However, it does work just fine when using the `standalone-chrome` image.

Using this on the grid setup has worked for me in the last few months. Though, I honestly can't recall the exact version of Docker-Selenium that this worked with. I removed all the containers and images that were using the old version only to find this new issue with the current version after creating new containers

## Meta -
Docker-Selenium Image Version(s):  3.8.1-erbium
Docker Version:  Docker version 17.12.0-ce, build c97c6d6
OS: Fedora 26 / Ubuntu 17.10

## Scripts to help replicate the issue -
[https://github.com/shames0/sel-hub-dl-trouble](https://github.com/shames0/sel-hub-dl-trouble)

## Expected Behavior -
Downloads would appear in the given `download.default_directory` for both **standalone-chrome**, and **hub/node** setup.

## Actual Behavior -
Downloads only appear in the given `download.default_directory` for **standalone-chrome**.

**Comment by diemol** [comment]
Hi @shames0, 

Please try to use the `goog:` prefix in `'chromeOptions' => {`.
Like this `goog:'chromeOptions' => {`.

I am not sure if the Ruby bindings provide something like this natively.

**Comment by shames0** [comment]
Thank you for your quick helpful reply! I made this change:
```
-    'chromeOptions' => {
+    'goog:chromeOptions' => {
```

That handled it nicely!

**Comment by diemol** [comment]
Nice, I am glad it helped :)
