### ISSUE TITLE
selenium/standalone-firefox-debug doesn't build on Docker Cloud

### ISSUE THREAD

**Issue by ad-m** [SeleniumHQ/docker-selenium#664]
## Meta -
Image(s):   selenium/standalone-firefox-debug
Docker-Selenium Image Version(s): latest
Docker Version:  ??
OS: ??

## Expected Behavior -

Images on https://hub.docker.com/r/selenium/standalone-firefox-debug/builds/ will be updated and automated builded.

## Actual Behavior -

Since year ``selenium/standalone-firefox-debug`` has not update due build fail. 

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-93-generic
Arch: amd64
BuildTime: 2017-08-17T22:50:04.828747906+00:00
ApiVersion: 1.30
Version: 17.06.1-ce
MinAPIVersion: 1.12
GitCommit: 874a737
Os: linux
GoVersion: go1.8.3
Starting build of index.docker.io/selenium/standalone-firefox-debug:latest...
Step 1/6 : FROM selenium/node-firefox-debug:3.5.3-boron

 ---> 01e76f9cf2ab

Step 2/6 : LABEL authors SeleniumHQ

 ---> Running in f885eb935f8d

 ---> be5d251a9160

Removing intermediate container f885eb935f8d

Step 3/6 : USER seluser

 ---> Running in e37ab719b871

 ---> 410ec1b678af

Removing intermediate container e37ab719b871

Step 4/6 : COPY entry_point.sh /opt/bin/entry_point.sh

COPY failed: stat /var/lib/docker/tmp/docker-builder194738696/entry_point.sh: no such file or directory
```

**Comment by diemol** [comment]
Hi @ad-m,

Builds are not done in Docker Cloud since a while ago, we use Travis for building and pushing releases.

Check https://travis-ci.org/SeleniumHQ/docker-selenium to see logs and more.

I'll close the issue since this is not really an error or an action item for us to work on :)
