### ISSUE TITLE
Downgrade temporary default chromedriver version to 2.33

### ISSUE THREAD

**Issue by JGladykowski-modus** [SeleniumHQ/docker-selenium#671]
## Meta -
Image(s):  
node-chrome / nod-chrome-debug

Docker-Selenium Image Version(s):  
latest
Docker Version:  
latest
OS: 
not applicable

There is nasty bug in Chromedriver, which causes many tests to fail:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198

Please consider downgrading Chromedriver version to 2.33 till above is fixed. Currently Chromedriver is not usable without putting waits everywhere in the code, before interacting with newly created / destroyed iframes

**Comment by ddavison** [comment]
this *should* be able to be eluded by using explicit waits

**Comment by ddavison** [comment]
also, by default we pull latest.  the good news is, if people do see this issue - they can specify the `CHROME_DRIVER_VERSION` as `2.33` 

`BUILD_ARGS="--build-arg CHROME_DRIVER_VERSION=2.33" VERSION=temp make chrome chrome_debug`

I'm not sure i want to change the default version from pulling latest as it makes our release process much simpler.

I'm closing this for now

**Comment by aimadghssisse** [comment]
probleme in version of chrome you should update chrome and will work
