### ISSUE TITLE
Bug when driver.get(url) second time

### ISSUE THREAD

**Issue by vavdagic** [SeleniumHQ/docker-selenium#672]
## Meta -
Image(s):  
selenium/hub:latest
node-chrome-debug:latest

OS: 
Latest docker version on Ubuntu 16.4

When you first time load URL with driver.get('some_url'), it loads it as it should and gives it proper sessionID, but when you second time use driver.get('some_url') within that session (eg. navigation href url of the same web app), the browser starts to hang without the timeout.
This only happens on the newest versions of node-chrome 3.9 > 
Downgrading to 3.8.1-erbium solved the issue.

**Comment by lmtierney** [comment]
I know there was a bug in chrome/chromedriver where performing `get` on a url that ended with a hash location didn't work, but I cannot find it right now. Regardless, this is an issue with chrome/chromedriver.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lmtierney** [comment]
Actually, this could be something different, so I'm leaving it open for now. Can you try with `3.9.1`?

**Comment by baflQA** [comment]
I think You thought about this issue: https://github.com/SeleniumHQ/selenium/issues/5419
It's a Chrome 64 issue.

**Comment by lmtierney** [comment]
@baflQA that's the one along with https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239, thanks! @vavdagic are you attempting to go to a hash url?

**Comment by vavdagic** [comment]
I think there might be a # in the URL because it is a angular 4 app, and they use # when routing, but i dont think it is at the end of the URL. I can not confirm this until Monday. This is very strange because it was not present on the older versions of node-chrome.

**Comment by ssims-de** [comment]
Saw this with a `#` in the middle of the URL upon calling driver.get() a second time in the same session. Tried both ChromeDriver 2.34 and 3.35 with Chrome 64.0.3282.140. ChromeDriver 3.33 works fine though.

**Comment by vavdagic** [comment]
@lmtierney Both my apps are having # in URL's.

**Comment by lmtierney** [comment]
@vavdagic Closing in favor of the chromium bug. Please see their final comment:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239#c10
