### ISSUE TITLE
Error retrieving a new session from the selenium server with Node-firefox

### ISSUE THREAD

**Issue by chris-tn** [SeleniumHQ/docker-selenium#677]
## Meta -
Image(s):  
node-firefox
Docker-Selenium Image Version(s):  
3.9.1-actinium 
Docker Version:  
Docker version 17.12.0-ce, build c97c6d6
OS: 
Ubuntu 16.04

Docker selenium node-firefox return difference with standalone-firefox:

## Expected Behavior -
{ status: 0,
  sessionId: 'e5cb66b7-285e-4140-9fd4-fced7b18dcdb',
  value: 
   { 'moz:profile': '/tmp/rust_mozprofile.IhM7CfCGYBSF',
     rotatable: false,
     timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
     pageLoadStrategy: 'normal',
     'moz:headless': false,
     'moz:accessibilityChecks': false,
     acceptInsecureCerts: false,
     browserVersion: '58.0.1',
     platformVersion: '4.4.0-87-generic',
     'moz:processID': 287,
     browserName: 'firefox',
     platformName: 'linux',
     'moz:webdriverClick': true,
     'webdriver.remote.sessionid': 'e5cb66b7-285e-4140-9fd4-fced7b18dcdb' } }

## Actual Behavior -
{ value: 
   { sessionId: '21fa5462-57b0-42e7-a45a-5132e639e3af',
     capabilities: 
      { 'moz:profile': '/tmp/rust_mozprofile.3JFy9UyunbNK',
        rotatable: false,
        timeouts: { implicit: 10000, pageLoad: 300000, script: 30000 },
        pageLoadStrategy: 'normal',
        'moz:headless': false,
        'moz:accessibilityChecks': false,
        acceptInsecureCerts: true,
        browserVersion: '58.0.1',
        platformVersion: '4.4.0-87-generic',
        'moz:processID': 68,
        browserName: 'firefox',
        platformName: 'linux',
        'moz:webdriverClick': true,
        'webdriver.remote.sessionid': '21fa5462-57b0-42e7-a45a-5132e639e3af' } } }

It's missing params on the json return so the error will get when run nightwatch

> Error retrieving a new session from the selenium server
> Connection refused! Is selenium server started?
With Node-firefox
![image](https://user-images.githubusercontent.com/2877420/36587574-2b9bbc44-18b8-11e8-9b0a-c944296dc3ea.png)
With standalone-firefox
![image](https://user-images.githubusercontent.com/2877420/36587629-4cb3f73e-18b8-11e8-8c51-a66152bd5565.png)

**Comment by chuonchuonit** [comment]
https://github.com/nightwatchjs/nightwatch/issues/1628

#646

**Comment by diemol** [comment]
Hi @chris-tn,

Thanks for referencing the other issues, and yes, hopefully this gets fixed soon in Nightwatch and the payload is sent properly (the PHP bindings have currently the same issue).

I'm closing this issue since there is no action item for us to work on.
