### ISSUE TITLE
Tag nightly/dev edition Firefox images as such

### ISSUE THREAD

**Issue by l0b0** [SeleniumHQ/docker-selenium#680]
## Meta -
Image(s):  All Firefox images
Docker-Selenium Image Version(s):  N/A
Docker Version:  N/A
OS: N/A

When building for example dev edition Firefox with `make BUILD_ARGS='--build-arg FIREFOX_VERSION=devedition' firefox` the resulting image is tagged as "selenium/node-firefox:3.9.1-actinium". This is confusing, and makes it difficult to know whether I am actually using the right image.

**Comment by ddavison** [comment]
how about something like this:

```sh
VERSION=devedition-3.9.1 make BUILD_ARGS='--build-arg FIREFOX_VERSION=devedition' firefox
# this would produce
#   selenium/node-firefox:devedition-3.9.1
```

right now, the Makefile doesn't allow the customization of the image name.  you could always fall back to a raw `docker build` command :)
