### ISSUE TITLE
Provide base docker images for other common use cases

### ISSUE THREAD

**Issue by benjaminapetersen** [SeleniumHQ/docker-selenium#681]
Greetings!  This issue/feature request bubbled up out of a discussion via the slack channel with @diemol & a few others.  The proposal is that it would be extremely handy to have a base `docker` image that users could easily extend for running their own tests in containers.

My use case:
- I have some tests written in `node.js`
- using `webdriver.io` and `selenium-standalone` currently.
- We have a containerized web app running on a `kube` cluster.  We occasionally roll out updates (as software devs do), and would like to run a separate container w/smoke tests against that web app to verify the updates did not break in a production environment, but without having to have devs go manually click through the interface.

I attempted to create a `Dockerfile` like this: 

```bash 
# seems like this would be a good place to start
FROM selenium/base:latest
# or this
# FROM selenium/standalone-firefox:latest

# if i started with the above, I would not assume node.js would be included so 
# would probably install that here.
# install my dependencies
ADD package.json /tmp/dependencies/package.json
RUN cd /tmp/dependencies && yarn install
RUN mkdir -p /opt/origin-smoke-test \
    && cp -a /tmp/dependencies/node_modules /opt/origin-smoke-test
WORKDIR /opt/origin-smoke-test
ADD . /opt/origin-smoke-test
EXPOSE 3000

# and finally, run my tests
CMD ["yarn", "test:run_once"]
```

But, this doesn't really work as these dockerfiles are not intended to do what I need.

We don't really need a `grid` or anything like that, but simply a single container with the necessary dependencies inside to run once & verify things are ok.  After that, we may write some log files, or perhaps pipe the results into prometheus somehow.  

Thanks!

**Comment by arnaud-deprez** [comment]
Isn't it something like [zalenium](https://github.com/zalando/zalenium) you're looking for ? 
Basically, they configure a docker image with a full grid (hub + firefox + chrome).

**Comment by diemol** [comment]
It is not exactly that. The idea is to build images only with Chrome+ChromeDriver and Firefox+GeckoDriver, which would be one of the base images for the other Grid images. With the reorganisation done by introducing Supervisor, this is now easier to implement.

**Comment by meshfields** [comment]
I would also be interested how to achieve e.g. adding python3 and some pip packages to the e.g. firefox-standalone Dockerfile without cloning the whole repo.

**Comment by diemol** [comment]
@benjaminapetersen I started to work on this, and after a few moments, I realised that there is no need to create new images, all that we need from docker-selenium is already there. In addition, creating new images just increases the complexity of the project and makes it harder to maintain.

So, basically, I followed your initial idea, create a `Dockerfile` having one of the docker-selenium images as base, install node, and run tests. So here it is:

```Dockerfile
FROM selenium/standalone-firefox-debug:3.141.0-actinium

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - \
  && sudo apt-get install -y nodejs \
  && node -v \
  && npm -v

COPY package.json \
  package-lock.json \
  test.js \
  start-virtual-desktop.sh \
  /home/seluser/

WORKDIR /home/seluser

RUN sudo chmod +x start-virtual-desktop.sh \
  && sudo npm install

CMD ["./start-virtual-desktop.sh", "node_modules/mocha/bin/mocha", "-t", "20000", "test.js"]

```

All the files can be found [here](https://github.com/diemol/docker-selenium-issues/tree/master/issue-681).

When running this image, it will just execute the sample test provided, but the idea can be followed to run your tests.

Therefore, I will close this issue since it is already possible to use the docker-selenium images for other use cases, one just needs to shape the `Dockerfile` properly.

**Comment by diemol** [comment]
@benjaminapetersen I just saw that you want to run tests with WebDriverIO, and I did the example with WebDriverJS. So you would need to start the Standalone Server as well by adding `/opt/bin/start-selenium-standalone.sh` to the `start-virtual-desktop.sh` file (this needs to be done after the `/opt/bin/start-xvfb.sh` one).
