### ISSUE TITLE
what's the realvnc password?

### ISSUE THREAD

**Issue by koala2012** [SeleniumHQ/docker-selenium#682]
I just ran docker vnc server successful, but via vnc viewer connect server. what's the password need?

**Comment by lmtierney** [comment]
It's at the bottom of https://github.com/SeleniumHQ/docker-selenium#debugging

>When you are prompted for the password it is **secret**. If you wish to change this then you should either change it in the /NodeBase/Dockerfile and build the images yourself, or you can define a Docker image that derives from the posted ones which reconfigures it
