### ISSUE TITLE
Docker images in docker repository use 3.5.3-boron

### ISSUE THREAD

**Issue by JGladykowski-modus** [SeleniumHQ/docker-selenium#688]
Not sure if this is bug or not, but all images  in docker repo point to 3.5.3 boron, and some builds are older than 6 months. 

https://hub.docker.com/r/selenium/hub/~/dockerfile/
https://hub.docker.com/r/selenium/node-base/~/dockerfile/
https://hub.docker.com/r/selenium/standalone-chrome-debug/~/dockerfile/

https://hub.docker.com/r/selenium/hub/builds/
https://hub.docker.com/r/selenium/node-base/builds/
https://hub.docker.com/r/selenium/standalone-chrome-debug/builds/

Is this intended ?

**Comment by ddavison** [comment]
thanks for the report, @JGladykowski-modus !

we actually don't use Docker Hub to build our images anymore.  we automatically build them from our CI side which then publishes to Docker Hub.

you can see that it indeed *does* have the latest version here:

https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile#L5


I'm inclined to believe that that "Dockerfile"  tab only shows the last Dockerfile built from Docker Hub's side.
