### ISSUE TITLE
Chrome is being controlled by automated test software

### ISSUE THREAD

**Issue by mariankral** [SeleniumHQ/docker-selenium#689]
I have just updated my project with the latest chrome driver 2.36.
When I run the browser through the driver, a yellow infobar "Chrome is being controlled by automated test software" is displayed.
I used the code below to disabling the infobar, but it does not work with latest Chrome browser and Chrome driver.
Do we have any solutions for this case, please ? 

ChromeOptions option = new ChromeOptions();
option.AddArguments("disable-infobars");
driver = new ChromeDriver(option);

## Meta -

Chrome Version(s):  65.0.3325.146

Chrome driver Version:  2.36

OS: Windows 10

**Comment by cgoldberg** [comment]
the option to disable it was removed from Chrome

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by toraylin** [comment]
I have the same issue in Chrome version 65 and Chrome driver 2.36 on Windows 7.
I use either  options.AddAdditionalCapability("useAutomationExtension", false) or option.AddArguments("disable-infobars")  and nothing works.

**Comment by cgoldberg** [comment]
@toraylin this is not a selenium issue

**Comment by diemol** [comment]
Besides this not being a Selenium issue... The latest images have ChromeDriver 2.35 and Chrome 64. So it is completely unrelated to the docker-selenium images.
