### ISSUE TITLE
official docker hub build process

### ISSUE THREAD

**Issue by rubytester** [SeleniumHQ/docker-selenium#69]
I think we need to solve the problem of automated build on docker hub. 

Our 11 images need to be built in ordered sequence (see Makefile):
 
- base
- hub, node-base
- node-firefox, node-chrome
- node-firefox-debug, node-chrome-debug
- standalone-firefox, standalone-chrome
- standalone-firefox-debug, standalone-chrome-debug

Problem: currently each Docker repo has an Automated Build `active` which creates race conditions when new commits trigger builds.

In order to create an ordered chain we can turn off deactivate Automated Build and:

- build manually with the established sequence

- or enable each build with trigger via curl in correct sequence

Thoughts? opinions?

AFAIK I dont't think docker hub provides build chains: https://docs.docker.com/v1.1/docker-hub/builds/

I like how CircleCI runs our build in sequence using `make build` defined in `circle.yml` but not docker hub.

I am now tempted to go with deactivating automated build and doing image release manually to avoid those race conditions.

**Comment by mtscout6** [comment]
Sounds reasonable to me.

**Comment by rubytester** [comment]
Ha, I think I found the trick: https://docs.docker.com/docker-hub/builds/#repository-links

**Comment by rubytester** [comment]
I think I have found the source of my misery.  The repos were already linked except the standalone debug images. I turned off the 'active' from the Automated Build on repos that have Repo link on them that points to the dependency.. All should be fixed now. 

I feel so stupid not noticing it before.

**Comment by mtscout6** [comment]
Ah, that makes sense I forgot about those as well since I originally set them up.

**Comment by rubytester** [comment]
Thank you.

**Comment by rubytester** [comment]
Just for my own sanity and because I am a bid pedantic I verified the sequence order of builds on docker hub and all is well...

```
create_date                     last_update                image
2015-06-11 12:23:15	2015-06-11 12:26:26  base
2015-06-11 12:27:27	2015-06-11 12:30:40  hub
2015-06-11 12:34:31	2015-06-11 12:41:38  node-firefox
2015-06-11 12:34:31	2015-06-11 12:46:38  node-chrome
2015-06-11 12:42:19	2015-06-11 12:47:54  standalone-firefox
2015-06-11 12:42:19	2015-06-11 12:54:22  node-firefox-debug
2015-06-11 12:47:15	2015-06-11 12:52:37  standalone-chrome
2015-06-11 12:47:38	2015-06-11 12:58:35  node-chrome-debug
2015-06-11 12:47:42	2015-06-11 12:59:14  standalone-firefox-debug
2015-06-11 12:53:16	2015-06-11 13:05:54  standalone-chrome-debug
```
