### ISSUE TITLE
Add HEALTHCHECK entry to Dockerfiles

### ISSUE THREAD

**Issue by rkrisztian** [SeleniumHQ/docker-selenium#691]
## Meta
Image(s):  standalone-chrome, standalone-firefox
Docker-Selenium Image Version(s):  2.53.0
Docker Version:  1.12.5
OS: RHEL 7

## Feature to request
When I execute my E2E tests, it may happen that I do them too soon, before the Selenium server is fully initialized. On my machine, I had to wait e.g. ~1.5 seconds before I could really connect to the server. If I don't wait, I get an exception like this:

```none
    org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
(...)
    Driver info: driver.version: RemoteWebDriver

        Caused by:
        java.net.SocketException: Connection reset
```

So far I've been using this code to make sure I wait enough:

```groovy
	private void waitForSeleniumServer(hostPort) {
		def healthy = (1..20).any {
			try {
				def driver = new RemoteWebDriver(new URL("http://localhost:${hostPort}/wd/hub"), healthCheckCapabilities)
				driver.quit()
				true
			}
			catch (UnreachableBrowserException e) {
				Thread.sleep 500
				false
			}
		}

		if (!healthy) {
			throw new GradleException("Timed out waiting for Selenium server to initialize on port ${hostPort}.")
		}
	}
```

However, I think it would be much better to implement a HEALTHCHECK entry in the docker images, because Gradle plugins provide support for waiting until the image is healthy. (Unfortunately, the solution may be different from what I shown above, because multiple parallel sessions might not be supported. I don't know the details of this, so I might be wrong.)

**Comment by rkrisztian** [comment]
Well, I was told a better idea that does not create a session, but queries `/status` via RestAssured as the REST API client:

```groovy
	private void waitForSeleniumServer(hostPort) {
		project.logger.info 'Waiting for Selenium server to become ready...'

		def requestSpecification = new RequestSpecBuilder().setBaseUri("http://localhost:${hostPort}/wd/hub").build()

		def healthy = (1..healthCheckRetries).any { counter ->
			def errorReason

			try {
				def response = RestAssured
						.given()
						.config(new RestAssuredConfig())
						.spec(requestSpecification)
						.auth().none()
						.when()
						.get('/status')
				def responseJson = new JsonSlurper().parseText(response.body.asString())

				if (!responseJson.ready) {
					errorReason = "Selenium server is not ready: ${responseJson.message}"
				}
			}
			catch (NoHttpResponseException | SocketException e) {
				errorReason = "Could not connect to Selenium server: ${e.message}"
			}

			if (errorReason) {
				project.logger.info "Attempt #${counter}: ${errorReason}"
				Thread.sleep 500
			}

			errorReason
		}

		if (!healthy) {
			throw new GradleException("Timed out waiting for Selenium server to initialize on port ${hostPort}.")
		}
	}
```

However, interestingly one test of mine ended up with the following unexpected result:

```
:inspectSeleniumContainer
(...)
Waiting for Selenium server to become ready...
Attempt #1: Could not connect to Selenium server: localhost:33035 failed to respond
(...)
:acceptanceTest
(...)
SimpleAcceptanceTest > classMethod FAILED
    org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
(...)
        Caused by:
        java.net.SocketException: Connection reset
```

I have to add though, this happened only 1 time, and so far I could not reproduce it ever again. So I might just ignore it. Time will tell.

**Comment by ddavison** [comment]
check out https://github.com/seleniumhq/docker-selenium/tree/wait-for-it

**Comment by rkrisztian** [comment]
That should do the job as well, thanks.

**Comment by diemol** [comment]
Yes, that is a good option to notify that things are up and ready, in addition is one of ways docker recommends to check that everything is up https://docs.docker.com/compose/startup-order/

Hopefully we can add this to the master branch and release it in the next weeks.

**Comment by rkrisztian** [comment]
Do you happen to have any progress with the release? Thanks in advance.

**Comment by rkrisztian** [comment]
Sorry, I have to correct myself. I looked into the implementation of the *wait-for-it* branch, and I found out that all that is done is waiting for the port to exist. However, I discovered [in the recent past](https://github.com/SeleniumHQ/docker-selenium/issues/691#issuecomment-371828568) that it's not enough even to wait for the `/status` request to respond with okay. The only working way I found was to try and open up a browser, but it's not very elegant in the sense that we will see a browser window quickly flashing up just for that. What would be nice is to know what API to call to really make sure that the node is fully done initializing itself.

**Comment by tnguyen14** [comment]
I have seen this error quite often, albeit intermittently, on my selenium hub - node chrome docker-compose setup. Do you think it's related to this?

```
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true}
```

**Comment by shankarkc** [comment]
What i typically do is curl hubs console page and check if hostname or ip address is present in console page. If its present then it is in good shape. It always works for me @tnguyen14. I am already using this as my nodes health check
