### ISSUE TITLE
GET /wd/hub/session/.../source and strange ambigous output in latest version selenium/standalone-chrome-debug

### ISSUE THREAD

**Issue by bscheshirwork** [SeleniumHQ/docker-selenium#697]
## Meta -
Image(s):  
    image: selenium/standalone-chrome-debug:3.11.0
Docker-Selenium Image Version(s):  
    image: selenium/standalone-chrome-debug:3.11.0
Docker Version:  
Docker version 17.12.1-ce, build 7390fc6
OS: 
Ubuntu 14.04

## Expected Behavior -
Use 3.11 like to 3.7
## Actual Behavior -
I get a strange answer from selenium browser and selenium browser try to connect to strange url:
#675 https://github.com/SeleniumHQ/docker-selenium/issues/675#issuecomment-373000222

**Comment by bscheshirwork** [comment]
I try to use some like this composition

https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/seleniun-proxy-test/docker-codeception-run/docker-compose.yml
and this config
https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/seleniun-proxy-test/nginx-conf-browser/nginx.conf

for record suspect log.

Also I can see in my main app nginx log. See #675

**Comment by diemol** [comment]
Hi @bscheshirwork,

Please check my [comment](https://github.com/SeleniumHQ/docker-selenium/issues/675#issuecomment-373815624) in the referenced issue.

Shortly quoting the comment:
>Of course, I can be wrong, therefore If you still think that this should be working, please create an issue on the main [Selenium repo](https://github.com/SeleniumHQ/selenium/issues/new) with a reproducible test case.
In the end, the docker-selenium project just put the Selenium jar and browsers in images for public use.
