### ISSUE TITLE
Can't set timezone in container

### ISSUE THREAD

**Issue by timmipetit** [SeleniumHQ/docker-selenium#70]
We're running into timezone issues because the docker-selenium containers have a different timezone than our host has. This is mostly due to this line in the Dockerfile:
https://github.com/SeleniumHQ/docker-selenium/blob/52233f089aeec8c24d047a5a932d3c9e40d979c2/NodeBase/Dockerfile#L11

We can fix `/etc/timezone` and `/etc/localtime` by running the container with: `-v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:r`, but that doesn't allow us to overwrite the `TZ` env var. This results in tools like `date` and Firefox still using the `US/Pacific` timezone.

**Comment by timmipetit** [comment]
I found out that I could fix this by doing `docker run -e TZ="Europe/Amsterdam" `. Maybe this should be added to the docs? Because it seems a non-standard way of setting timezone for a container.

**Comment by rubytester** [comment]
the NodeBase has TZ set which means it will propagate to all the Nodes (however Hub doesn't get TZ set so booo... we can fix it by moving TZ setting to Base image). 

A case could be made to chagne TZ to be Zulu and operate on UTC for all. 

And yes, when you `docker run` add the TZ you need with `-e TZ="<your tz>"`

So I vote on 2 things:

1.  move TZ to Base Docker file so Hub gets it
1. set TZ to utc timezone as universal

thoughts?

**Comment by manoj9788** [comment]
Recently I ran into this issue  and used the docker run -e TZ="< >" as well. 
What sort of help is required to fix this ?

**Comment by ddavison** [comment]
agreed, @rubytester, both points. making those changes now.

**Comment by ddavison** [comment]
also wrote a quick'n'simple wiki to using it: https://github.com/SeleniumHQ/docker-selenium/wiki/Setting-a-Timezone
