### ISSUE TITLE
Dummy sound playing support

### ISSUE THREAD

**Issue by giorgiosironi** [SeleniumHQ/docker-selenium#700]
## Meta -
Image(s):  standalone-firefox-debug
Docker-Selenium Image Version(s):  3.11.0-antimony
Docker Version: 17.12.1-ce
OS: Ubuntu 16.04

## Expected Behavior

[This podcast page](https://ui-patterns.elifesciences.org/patterns/04-pages-podcast/04-pages-podcast.html) should be able to load the podcast when the play button is pressed.

## Actual Behavior

Observing this through VNC, the play button turns into a loading spinner and stays there, probably because of some underlying failure. This is not surprising as we had to [fiddle with kernel modules and packages](https://github.com/elifesciences/builder-base-formula/blob/master/elife/selenium.sls#L45-L60) to support this on an EC2 instance.

I'm looking for guidance on how to extend the image to support this, and I will report back with what I discover to see if it may be integrated upstream. Full portability probably depends on the underlying kernel being used, but packages or documentation could be useful.

**Comment by diemol** [comment]
Hi @giorgiosironi,

If you are looking to build your image with these additional packages, you can either do a new Dockerfile and taking as base one of the docker-selenium images. Another option would be to clone the repo and follow this [generic instructions from the Wiki](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images) to do if that way.

About merging upstream, so far it looks like not many people are using the containers to test sound or to do something related to sound. That is why, for now, we are suggesting that people take these ones as base and extend them. We are trying to provide a very generic image that can be used for common purposes, and adding specific packages makes thing harder (one person might want a different package for the same purpose, or it could cause conflicts for users who are already extending the image, and it makes the images harder to maintain).

I'll leave this issue open for a few days in case you'd like to report more findings that can be relevant for some people.

**Comment by giorgiosironi** [comment]
By extending the image in this way:
```
FROM selenium/standalone-firefox-debug:3.11.0-antimony
USER root
RUN apt-get update && apt-get -y install mplayer linux-sound-base
# does it make sense to install a kernel module inside a container? Probably not necessary, but was originally ported from another implementation, untested the removal
RUN apt-get -y install linux-image-extra-4.13.0-37-generic
USER seluser
```
the browser is able to load an audio file and show, for example, its duration. It is not able to play it but that was out of scope for me.
