### ISSUE TITLE
ENV variable to disable password

### ISSUE THREAD

**Issue by schmunk42** [SeleniumHQ/docker-selenium#701]
## Meta -
Image(s):  
standalone-firefox-debug

Docker-Selenium Image Version(s):  
3.11.0-antimony

Docker Version:  
any

OS: 
any

## Expected Behavior -

set `VNC_NO_PASSWORD=1` (or similar) to disable password auth for VNC

## Actual Behavior -

We have to build a custom `Dockerfile`, which is feasible, but for local development it would just be great of we could use an ENV var.

**Comment by schmunk42** [comment]
I meant the part of the README :)
But if that is a change you’re willing to accept I can create a PR.

**Comment by kkim-sf** [comment]
VNC_NO_PASSWORD ENV VAR seems to be added for standalone files only, but the way the readme reads almost makes it seem like it's available for all variants. We should probably add them to the node ones as well if not added already?
