### ISSUE TITLE
Cannot find home/seluser/Downloads folder in selenium docker container

### ISSUE THREAD

**Issue by Larry19b** [SeleniumHQ/docker-selenium#704]
## Meta -
Image(s): standalone-chrome
Docker-Selenium Image Version(s):  33.7.1-beryllium
Docker Version: 17.12.0-ce
OS: Mac OS X

## Description
When I enter the following command:

docker exec [containerId] find /home -iname "*"

## Expected Behavior -
/home/seluser/Downloads should be listed

## Actual Behavior -
/home
/home/seluser
/home/seluser/.bashrc
/home/seluser/.bash_logout
/home/seluser/.profile
/home/seluser/.local
/home/seluser/.local/share
/home/seluser/.local/share/applications
/home/seluser/.local/share/applications/mimeapps.list
/home/seluser/.sudo_as_admin_successful

The above is listed instead and does not include the 'Downloads' folder

**Comment by diemol** [comment]
Hi @Larry19b,

The folder is created when something is downloaded, not before. 

Please check and let us know.

**Comment by Larry19b** [comment]
Hi Diemol,

It was an error on my part. I forgot to run the 'export DOCKER_HOST=docker'. It works now.
