### ISSUE TITLE
Docker container cannot share data with host 

### ISSUE THREAD

**Issue by Larry19b** [SeleniumHQ/docker-selenium#705]
## Meta -
Image(s): standalone-chrome
Docker-Selenium Image Version(s): 3.7.1-beryllium
Docker Version: 17.12.0-ce
OS: Mac OS X

## Description
When I run the following command:
docker run -v /Users/MyUsername/Downloads/MappedFolder:/home/seluser/Downloads -d -P -p 4444:4444 selenium/standalone-chrome:3.7.1-beryllium

## Expected Behavior -
Downloaded files in the docker container should appear in the host (/Users/MyUsername/Downloads/MappedFolder)

## Actual Behavior -
Dowloaded files in the docker container are not present in the host

**Comment by diemol** [comment]
Hi @Larry19b,

I tried to reproduce what you describe, executing it on Mac OSX but with the latest release (3.11.0-bismuth), and the downloaded file was there.

You can check the code I used here: https://github.com/diemol/docker-selenium-issues/tree/master/issue-628, you could clone the repo and try to run it via the docker-compose file.

If it does not work, feel free to comment or reopen this issue.
