### ISSUE TITLE
GRID_JETTY_MAX_THREADS not working

### ISSUE THREAD

**Issue by HowHai** [SeleniumHQ/docker-selenium#717]
Docker-Selenium Image Version(s): selenium/hub:3.11.0

I have tried setting `GRID_JETTY_MAX_THREADS` ranging from 200 to 2000, and it doesn't seem to have any effect on the grid. The number of threads count is always under 300 for the box that I am using.

    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.11.0
        ports:
          - containerPort: 4444 
        env:
          - name: GRID_BROWSER_TIMEOUT
            value: '30000'
          - name: GRID_TIMEOUT
            value: '30000'
          - name: GRID_NEW_SESSION_WAIT_TIMEOUT
            value: '30000'
          - name: GRID_JETTY_MAX_THREADS
            value: '200'

**Comment by ddavison** [comment]
this doesn't look like a docker-compose file. what type of file is this?

**Comment by ddavison** [comment]
it could also be that you are using strings rather than integers.   try unwrapping the integer (remove the single quotes)

**Comment by HowHai** [comment]
@ddavison It's a kubernetes file. When I check the config.json, it does seems to read from GRID_JETTY_MAX_THREADS. 

cat /opt/selenium/config.json
{
  "port": 4444,
  "role": "hub",
  "maxSession": 5,
  "newSessionWaitTimeout": 30000,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "jettyMaxThreads": 200,
  "cleanUpCycle": 5000,
  "browserTimeout": 30000,
  "timeout": 30000,
  "debug": false
}

**Comment by HowHai** [comment]
@ddavison I must have done something wrong. I just rebuilt the box, and now it's updating the config.json. Thank you!

**Comment by ddavison** [comment]
good to hear!  glad you figured it out! 🎉
