### ISSUE TITLE
Failed to create /.pki/nssdb directory.

### ISSUE THREAD

**Issue by vikassahnimca** [SeleniumHQ/docker-selenium#722]
From Automation scripts i am able to connect with selenium hub and selenium hub is also able to connect with node. As per node logs chrome driver is also launched but it is failing due to error..**Failed to create /.pki/nssdb directory.**

**Selenium-node-chrome logs Please refer below**
/opt/bin/entry_point.sh: line 4: /opt/selenium/config.json: Permission denied
07:34:23.031 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
07:34:23.084 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
2018-04-13 07:34:23.486:INFO::main: Logging initialized @1651ms to org.seleniumhq.jetty9.util.log.StdErrLog
07:34:24.009 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
07:34:24.009 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
07:34:24.009 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
07:34:24.016 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
07:34:24.016 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
07:34:24.860 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
07:34:24.997 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
**07:35:45.193 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: chrome, goog:chromeOptions: {}, platform: LINUX, version: }
07:35:45.196 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7) on port 22140
Only local connections are allowed.
[1523604945.584][SEVERE]: Failed to create /.pki/nssdb directory.
07:35:49.094 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
07:35:50.399 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 7891f20fa2584a915256af2e2e42f0b8 (org.openqa.selenium.chrome.ChromeDriverService)
07:37:58.586 INFO [ActiveSessions$1.onStop] - Removing session 7891f20fa2584a915256af2e2e42f0b8 (org.openqa.selenium.chrome.ChromeDriverService)**

**Comment by vikassahnimca** [comment]
Any help/information on this .how i can resolve this issue.

**Comment by diemol** [comment]
Hi @vikassahnimca,

Could you please fill the information requested in the issue template? For example, in this case, we don't know which tag of the images is being used, how the docker command to start the images look like, and so on... With more information it is easier to understand your scenario and see how we can help.

**Comment by diemol** [comment]
Closing since we didn't get more feedback from the OP.
