### ISSUE TITLE
firefox-debug-2.45 showing 2.46 in the selenium hub

### ISSUE THREAD

**Issue by g13013** [SeleniumHQ/docker-selenium#73]
![screen shot 2015-06-30 at 15 41 34](https://cloud.githubusercontent.com/assets/2730430/8433564/8b83b47a-1f3e-11e5-9685-f7e09ae44e90.png)
![screen shot 2015-06-30 at 15 42 16](https://cloud.githubusercontent.com/assets/2730430/8433584/a2438b0e-1f3e-11e5-9b18-0aada4331c1b.png)

**Comment by rubytester** [comment]
I should be blamed for this probably when I first started and didn't configure the docker hub automated build correctly. 

I don't recommend using 2.45.0 and sorry for the mess

**Comment by g13013** [comment]
👍

**Comment by kayabendroth** [comment]
Can be closed?

**Comment by g13013** [comment]
I guess yes, thank you ;)
