### ISSUE TITLE
Using apt-get instead of apt

### ISSUE THREAD

**Issue by vv-p** [SeleniumHQ/docker-selenium#732]
## Meta -
Image(s):  
NodeBase

Docker-Selenium Image Version(s):  
3.12.0-americium

Docker Version:  
18.03.1-ce, build 9ee9f40

OS: 
OSX Yosemite

## Expected Behavior -
Building images without warnings

## Actual Behavior -
Warning logs while building NodeBase docker image:

`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

**Comment by diemol** [comment]
Hi @vv-p,

Would you like to send a PR for this? It theory it is just to change the apt command for apt-get

**Comment by vv-p** [comment]
Here it is - https://github.com/SeleniumHQ/docker-selenium/pull/733

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/docker-selenium/commit/c3263940d5d2956b85e1d9ba8e0457fe95050344
