### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:24224: bind: address already in use

### ISSUE THREAD

**Issue by asifbhat222** [SeleniumHQ/docker-selenium#740]
Hi Team,

I am getting below error while using the "docker-compose up" command 
===================================================================
[root@clm-aus-t301fd docker]# docker-compose up -d
docker_elasticsearch_1 is up-to-date
Starting docker_fluentd_1 ...
Starting docker_fluentd_1 ... error

ERROR: for docker_fluentd_1  Cannot start service fluentd: b'driver failed programming external connectivity on endpoint docker_fluentd_1 (e98c381f833d944707992202c1351fa97f716f5d3363709664edd8179e494350): Error starting userland proxy: listen tcp 0.0.0.0:24224: bind: address already in use'

ERROR: for fluentd  Cannot start service fluentd: b'driver failed programming external connectivity on endpoint docker_fluentd_1 (e98c381f833d944707992202c1351fa97f716f5d3363709664edd8179e494350): Error starting userland proxy: listen tcp 0.0.0.0:24224: bind: address already in use'
ERROR: Encountered errors while bringing up the project.
===================================================================
**docker-compose.yml file**
version: '2'
services:
  tomcat:
    image: tomcat
    ports:
      - "8080:8080"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: tomcat.access

  fluentd:
    image: fluent/fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
=================================================================

[root@clm-aus-t301fd docker]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
fluent/fluentd      latest              f060ea32df38        2 days ago          40.7MB
elasticsearch       latest              671bb2d7da44        2 weeks ago         486MB
tomcat              latest              9f1191b287da        2 weeks ago         465MB
kibana              latest              006eb7921543        4 weeks ago         389MB
hello-world         latest              e38bc07ac18e        7 weeks ago         1.85kB
===================================================================
[root@clm-aus-t301fd docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS                              NAMES
d0a2e8a8e7c1        fluent/fluentd      "/bin/entrypoint.sh …"   10 minutes ago      Created                                                           docker_fluentd_1
16f925ee76f9        kibana              "/docker-entrypoint.…"   10 minutes ago      Up 10 minutes                  0.0.0.0:5601->5601/tcp             docker_kibana_1
f082e9c11ef3        elasticsearch       "/docker-entrypoint.…"   10 minutes ago      Up 10 minutes                  0.0.0.0:9200->9200/tcp, 9300/tcp   docker_elasticsearch_1
794f2c962481        fluent/fluentd      "/bin/entrypoint.sh …"   34 minutes ago      Exited (0) 34 minutes ago                                         distracted_bohr
8d2c918489f5        kibana              "/docker-entrypoint.…"   35 minutes ago      Exited (0) 35 minutes ago                                         nostalgic_babbage
82d3a34b66f1        elasticsearch       "/docker-entrypoint.…"   38 minutes ago      Exited (0) 38 minutes ago                                         nifty_euler
990d02f5c86f        tomcat              "ls -lah"                39 minutes ago      Exited (0) 39 minutes ago                                         blissful_johnson
3d8f9b30726a        hello-world         "/hello"                 43 minutes ago      Exited (0) 43 minutes ago                                         affectionate_kare
535c34686862        hello-world         "/hello"                 About an hour ago   Exited (0) About an hour ago                                      angry_aryabhata
===================================================================

Kind Regards,
Asif Bhat

**Comment by ddavison** [comment]
Hi @asifbhat222 , your issue looks like it doesn't have anything to do with our `docker-selenium` repository.

You may have better luck on StackOverflow.  Closing as everything included here has nothing to do with Selenium or Docker-Selenium.
