### ISSUE TITLE
Dockerfile on master has reference to entry_point.sh

### ISSUE THREAD

**Issue by schoolboytom** [SeleniumHQ/docker-selenium#746]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  n/a

Docker Version:  Docker version 18.03.1-ce, build 9ee9f40

OS: Ubuntu 17.10

## Expected Behavior -
In the docker-selenium/NodeFirefoxDebug/Dockerfile the entry_point.sh file is being referenced, but doesn't actually exist on the master branch.
## Actual Behavior -
When running docker build on the master branch Dockerfile I'm recieving the following error:

> ERROR: Service 'firefox_hub' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder329738945/entry_point.sh: no such file or directory

**Comment by diemol** [comment]
Hi @schoolboytom,

To build the images yourself, please follow
https://github.com/SeleniumHQ/docker-selenium#building-the-images
and 
https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images

if any issue is found after following those instructions, please feel free to open a new issue.
