### ISSUE TITLE
Japanese characters garbled in node-firefox and node-chrome on UI

### ISSUE THREAD

**Issue by vishalgupta305** [SeleniumHQ/docker-selenium#747]
## Meta -
Image(s):  
selenium/node-firefox and selenium/node-chrome
Docker-Selenium Image Version(s):  
3.9.1-actinium
Docker Version:  
17.04.0-ce
OS: 
ubuntu 14.04 x86_64

## Expected Behavior -
Japanese characters should show normal

## Actual Behavior -
Japanese characters garbled

**Comment by vishalgupta305** [comment]
Related Issue: https://github.com/SeleniumHQ/docker-selenium/issues/367

**Comment by vishalgupta305** [comment]
![japanese](https://user-images.githubusercontent.com/40439010/41677117-12e8ffc0-74e5-11e8-99be-204eece6dda3.JPG)
Image Attached

**Comment by ddavison** [comment]
hi @vishalgupta305 , if you notice from that linked issue - this should've been fixed since [3.11.0-bismuth](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.11.0-bismuth).  

if you upgrade and realize this is still an issue - we'll reopen.
