### ISSUE TITLE
How to increase the number of instances/webdrivers/slots

### ISSUE THREAD

**Issue by venkatasykam** [SeleniumHQ/docker-selenium#757]
Hi 

By default if I setup the Selenium grid using this docker containers chrome & firefox, its creating single web-driver slot for each chrome & firefox. 

I have more than one selenium projects. If I run three jobs one after one as to test my script on chrome browser, the second, and third job is waiting to run the script on the chrome browser.

I can see this message on the grid console: 
2 requests waiting for a slot to be free.
Capabilities [{browserName=chrome, version=, platform=ANY}]Capabilities [{browserName=chrome, version=, platform=ANY}]
view config

Could you please help me, how we can run these docker containers with more than one slot/webdriver/instance for chrome & firefox?

Thanks,
Venkat

**Comment by diemol** [comment]
Hi @venkatasykam,

Some docs have been added to clarify this https://github.com/SeleniumHQ/docker-selenium#increasing-the-number-of-browser-instancesslots

There is also a docker-compose file that can be used as an example here: https://github.com/diemol/docker-selenium-issues/blob/master/issue-757/docker-compose.yml

**Comment by venkatasykam** [comment]
really thanks for the docs.
