### ISSUE TITLE
when running test with mobileEmulation on Chrome, cannot click on a located element.

### ISSUE THREAD

**Issue by jerrylizilong** [SeleniumHQ/docker-selenium#758]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  
latest:  3.13.0

Docker Version:  
17.09.0-ce

OS:  linux

docker.io/selenium/node-chrome-debug:latest
docker.io/selenium/node-chrome-debug@sha256:d27e9f28ec443a08144206fa9aaa1cdc76cc9f1de780201acf6b48ba162a3f9e

## Actual Behavior -

The cases are fine in the 3.11.0 version, but when I run the same tests in the latest version (3.13.0) docker image, the located element is not clicked and no error message is given. 

The element is located since I can get it's attributes.

the DesiredCapabilities is :

{'version': '', 'browserName': 'chrome', 'platform': 'ANY', 'goog:chromeOptions': {'mobileEmulation': {'deviceName': 'Galaxy S5'}, 'extensions': [], 'args': ['lang=en_US', 'start-maximized']}}

**Comment by diemol** [comment]
@jerrylizilong 

Please check the ChromeDriver versions used in the docker images you are using, then try to reproduce the issue locally directly with Chrome using the ChromeDriver versions you found, if it is failing there, report the issue (if it does not exist) to the ChromeDriver project.

If it did not fail, please try to reproduce using the plain Selenium Grid jar (no docker) and the versions of ChromeDriver. If it fails there, please report to the upstream Selenium project filling the complete template.

**Comment by jerrylizilong** [comment]
@diemol  
I updated my Chrome to the latest version and the click also failed.  It seems to be a bug on Chrome.

**Comment by jerrylizilong** [comment]
@lmtierney 
Thanks

**Comment by diemol** [comment]
Thanks for replying @jerrylizilong, then I would suggest to report it to the Chrome team if the issue does not exist yet.

Closing.
