### ISSUE TITLE
Setting up VNC fails

### ISSUE THREAD

**Issue by jjmurre** [SeleniumHQ/docker-selenium#76]
When trying to use the 'standalone-chrome-debug' image I cannot connect to the vnc port.

In the logs I see:
09/07/2015 01:59:50 passing arg to libvncserver: -rfbport
09/07/2015 01:59:50 passing arg to libvncserver: 5900
Enter VNC password: stty: standard input: Inappropriate ioctl for device
fgets: No such file or directory
stty: standard input: Inappropriate ioctl for device
x11vnc -usepw: could not find a password to use.
Failed to read: session.ignoreBorder

It seems that vnc tries to 'obfuscate' the password that is entered in the tty, but that is not possible in stty.

**Comment by rubytester** [comment]
Strange indeed. 

I just did a test with the docker image ( selenium/standalone-chrome-debug with id `be801ca81579` ) and I get this on starting docker container

```
09/07/2015 13:18:47 passing arg to libvncserver: -rfbport
09/07/2015 13:18:47 passing arg to libvncserver: 5900
09/07/2015 13:18:47 -usepw: found /root/.vnc/passwd
09/07/2015 13:18:47 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 43
09/07/2015 13:18:47 Using X display :99.0
```

Retracing me step on mac os x as this: 

```shell
$ cid=$(docker run -d -P selenium/standalone-chrome-debug)
$ docker logs $cid
```


And finally connecting as client:

```shell
$ docker port $cid
5900/tcp -> 0.0.0.0:32770
4444/tcp -> 0.0.0.0:32771

$ docker-machine ip dev
192.168.99.100

$ open vnc://:secret@192.168.99.100:32770
```

and the logs show client connected. 
At this point I can start a session on standalone at 

`http://192.168.99.100:32771/wd/hub/static/resource/hub.html`

**Comment by jjmurre** [comment]
I tried it again and get the same problem. However, when I use the Dockerfile below, vnc  works.
Really strange, because that is exactly what happens in the 'StandaloneDebugChrome' Dockerfile.

FROM ubuntu
RUN apt-get update && apt-get install -y x11vnc xvfb 
RUN mkdir ~/.vnc
RUN x11vnc -storepasswd 1234 ~/.vnc/passwd
EXPOSE 5900
CMD    ["x11vnc", "-forever", "-usepw", "-create"]

**Comment by rubytester** [comment]
Sorry if this is a stupid question but do you build the images locally? If you do can you rebuild with `--no-cache` option. I use the officially built from docker. Please pull the latest from hub and try. 

I have tried on my locally built image and all if fine. I tested on Mac OS X with docker-machine in virtualbox . Maybe there is another setup that's messed up?

I am perplexed.

**Comment by jjmurre** [comment]
I used the image from the hub. I tried it now with `latest` (c0de4f4abc1d) and get the same result.
I also rebuilt the image locally, same problem.
However, when I tried it with `latest` on another machine (Ubuntu 14:04 server), vnc works ok.
My local laptop is also Ubuntu 14:04 (desktop).

**Comment by rkerr** [comment]
I ran into the same issue today with selenium/standalone-firefox-debug:latest from the hub.

Going through the x11vnc code it seems that if x11vnc can't find the password file for -usepw it will try to create it by calling `x11vnc --storepasswd` - that will try to prompt for a password on stdin which is in turn generating the stty/fgets errors.

What I'm not sure of is why x11vnc isn't finding the password file or why it apparently works for some people and not others...

**Comment by rkerr** [comment]
Seems to be related to the setting of $HOME in containers. It appears that behaviour in docker changed at some point: https://github.com/docker/docker/issues/2968

For recent versions of docker $HOME gets set to /root and that's where the VNC password file ends up in the published image. If you're using an older version of docker $HOME gets set to / which stops the password file being found.

The -debug images could be made compatible with both versions of docker by symlinking /.vnc to /root/.vnc
