### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by wck821829906** [SeleniumHQ/docker-selenium#760]
@ddavison I am wordering why the exception happens "ValueError: No JSON object could be decoded" when I use the latest(3.14.0) selenium docker

Environment:
1. Client: selenium 3.13.0 , robotframework  3.0.4
2. docker selenium 3.14.0 ( selenium/hub & selenium/node-chrome-debug  )

**Comment by diemol** [comment]
Hi @wck821829906,

Please open a new issue and filling up the template. The information provided here is not enough. Also, please provide a script to reproduce the issue.
