### ISSUE TITLE
websocket on port. connection refused

### ISSUE THREAD

**Issue by jmurphy87** [SeleniumHQ/docker-selenium#766]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  node-chrome, and hub

Docker Version:  bug is on 3.14.0 works on 3.13.0

OS: 18.03.1-ce-win65

Windows 10

## Expected Behavior -
ws://localhost:8016 request to remain in pending state or connect
works on 3.13.0 not on 3.14.0

## Actual Behavior -
connection is refused

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
