### ISSUE TITLE
Documentation mismatch in readme and Getting-Started-with-Hub-and-Nodes doc.

### ISSUE THREAD

**Issue by abhishkk** [SeleniumHQ/docker-selenium#769]
**Scenario**: Selenium Grid - Hub and nodes

[Readme.md](https://github.com/SeleniumHQ/docker-selenium/blob/master/README.md#using---link) file mentions that `--link` is legacy feature.
But [Getting Started with Hub and Nodes](https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Hub-and-Nodes) doc still suggests to use `--link`.
Can this be corrected?

**Comment by diemol** [comment]
Hi @abhishkk,

Thanks for pointing that out, we just updated the wiki by adding a note.

https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Hub-and-Nodes#a-note-about-using---link-in-the-examples
