### ISSUE TITLE
Chrome setInterval() limits for inactive tab

### ISSUE THREAD

**Issue by PeteZero1** [SeleniumHQ/docker-selenium#77]
This bug / feature in chrome means that tests take forever to run...

https://codereview.chromium.org/6577021

What happens is that chrome opens up with the Selenium window then another window (tab) is opened that starts a test. The test will progress slowly unless the original tab is selected due to inactive tab setInterval() calls being limited to at least 1000ms between calls.

-- Use WebWorker to avoid the issue --
http://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome

-- Force it to open a new window, avoiding the limit --
http://stackoverflow.com/questions/15818892/chrome-javascript-window-open-in-new-tab

Sorry if this is not an issue with Selenuim directly but please correct me if it is an issue with the tests themselves.

**Comment by PeteZero1** [comment]
I am running https://github.com/magento/taf

It in turn uses "PHPUnit_Extensions_SeleniumTestCase"

Thanks!

**Comment by elgalu** [comment]
That magento/taf project dates 2013, what version of selenium client is using?

**Comment by PeteZero1** [comment]
I am using Selenium 2.46 (standalone-chrome-debug). I personally don't think the bug is in magento/taf thou since it is Selenium that opens the tab in chrome, making its running tab deactive, causing the slow down?

**Comment by elgalu** [comment]
I mean the version of selenium client php bindings, not the server.

**Comment by PeteZero1** [comment]
Is this what you mean?

$ apt-cache show phpunit-selenium
Package: phpunit-selenium
...
Version: 1.2.6-3

$ /usr/bin/phpunit --version
PHPUnit 3.7.28 by Sebastian Bergmann.

**Comment by elgalu** [comment]
Exactly, I would first try to upgrade 1.2.6 to latest 1.4.2 see https://github.com/giorgiosironi/phpunit-selenium/releases

**Comment by PeteZero1** [comment]
Ok, so I have upgraded to PHPUnit 4.7.7 (Comes with latest Selenium classes) and amended some code that was not working in the latest version.

https://github.com/PeteZero1/taf/commit/74552c4c022a46b405cddf6e79b019f0b62ffc3a

The issue still persists.

**Comment by PeteZero1** [comment]
Confirmed it is using phpunit-selenium in the latest PhpUnit.phar file...

abstract class PHPUnit_Extensions_Selenium2TestCase extends PHPUnit_Framework_TestCase
{
    const VERSION = '1.4.2';
    .....

Thanks

**Comment by PeteZero1** [comment]
Just to add more information that may be useful.

The tab URL...

http://www.mydomain.co.uk/selenium-server/core/RemoteRunner.html?sessionId=19c313e5cd9f42229e497a97e2fcb212&multiWindow=true&baseUrl=http%3A%2F%2Fstaging.www.harmonystore.co.uk%2Fadmin%2F&debugMode=false

Opens the following new tab...
http://www.mydomain.co.uk/admin/

The "selenium-server" tab then becomes inactive and this causes the javascript running in that tab to become limited. Clicking the first tab making it active (Via VNC) immediately restores the expected test speeds.

**Comment by elgalu** [comment]
You may need to switch to the first tab using selenium API in your tests. I don't think this issue belongs to docker-selenium.

**Comment by PeteZero1** [comment]
Thanks for all the help but that sounds like a very hacky solution to the issue?

If the issue does not belong in docker-selenium where would I be better raising it?

**Comment by ddeath** [comment]
Hey do not know how much relevant is this and if it works (did not any tests) but if you run the tests in separate windows(not tabs) it should not throttle according to [this blog post](https://blog.pivotal.io/labs/labs/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs)
