### ISSUE TITLE
mozilla moveto does not match a known command

### ISSUE THREAD

**Issue by jmurphy87** [SeleniumHQ/docker-selenium#771]
## Meta -
Image(s):  
node-firefox and node-firefox-debug

Docker-Selenium Image Version(s):  
latest

Docker Version:  
17.06.2-ce

OS: 
windows 10

## Expected Behavior -
browser.actions().mouseMove(element).click().perform();
for the mouse action to be performed

This issue only occurs when using selenium-grid and node-firefox or node-firefox-debug, un sure if it occurs with the firefox-standalone, but it does work with my own firefox install and selenium server

## Actual Behavior -
throws 
POST /session/6283c838-6834-439c-ba02-255f2a650bb8/moveto did not match a known command

**Comment by diemol** [comment]
Hi @jmurphy87,

Would it be possible for you to provide a script we could use to replicate the issue? We just don't want to make any assumptions.

**Comment by lmtierney** [comment]
`moveto` is not a valid command for a w3c compatible webdriver

**Comment by jmurphy87** [comment]
Why does it work outside of docker then? On just a local install of Mozilla and selenium server.

**Comment by jmurphy87** [comment]
Thank you all for the quick response, I will get you an example tomorrow when I get into work.

**Comment by jmurphy87** [comment]
My local install of webdriver is 4.0.0-alpha1(something like that), and my local version of firefox is 61.0.2, where as the docker Mozilla is 61.0.1, which I imagine isn't the problem since its only one dot cut. Unsure which version of webdriver you are running but if its not 4.0.0-alpha1 im sure its that.

**Comment by lmtierney** [comment]
@jmurphy87 I am not a JS guy by any means, but `mouseMove` is a legacy action and you should switch to [move](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html#move) action for Firefox or any other `w3c` browser. There's also the option of `bridge` mode as documented [here](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#changes-for-w3c-webdriver-spec-compliance)

**Comment by jmurphy87** [comment]
Awesome, I was unaware about mouseMove being a legacy action, I will give that a try and let you know tomorrow. Also, in my onPrepare method I do have browser.driver.actions({bridge:true}); It seemed like it was still having trouble, but I will double check tomorrow.

**Comment by lmtierney** [comment]
Bridge mode might be what is giving you the issue then. Bridge mode attempts w3c action and falls back to legacy action if any piece of the action sequence gives an error, which is definitely not what you want to have happen in Firefox.

**Comment by jmurphy87** [comment]
I wrote this line after I started getting this error tho, in hopes to resolve it.

**Comment by jmurphy87** [comment]
So, I am back at work, and was unable to get the mouseMove to work. It seems like the only difference between my dev environment vs the docker environment is the version of selenium being used. If Im right (found in the base Dockerfile)
RUN  sudo mkdir -p /opt/selenium \
  && sudo chown seluser:seluser /opt/selenium \
  && wget --no-verbose https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar \
    -O /opt/selenium/selenium-server-standalone.jar

you are using version 3.14.0 where I am using version 4.0.0-alpha.1. would there be a way you could release a version with the 4.0.0-alpha.1 selenium version

**Comment by jmurphy87** [comment]
yeah after relooking I can see that now, let me go ahead and get you all a test project going.

**Comment by jmurphy87** [comment]
3.14.0

**Comment by diemol** [comment]
@jmurphy87 when you provide the test project, please also include the exact docker commands you use to start the containers.

**Comment by jmurphy87** [comment]
`#!/usr/bin/env bash

RUN_MOZILLA=$2

cd `dirname $0`

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

docker pull selenium/hub
docker pull selenium/node-chrome
docker pull selenium/node-chrome-debug #has VNC server for remoting in

docker pull selenium/node-firefox
docker pull selenium/node-firefox-debug #has VNC server for remoting in

docker run -d -p 4446:4444 --name selenium-hub -P selenium/hub

COUNTER=0
while [  $COUNTER -lt $1 ]; do
    echo Creating container$COUNTER
	if [ $RUN_MOZILLA == "true" ]
	then
		docker run -d -P --name=container$COUNTER --link selenium-hub:hub -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -e SCREEN_DEPTH=24 selenium/node-firefox-debug
		while ! (curl -sSL "http://localhost:4446/grid/console" | grep -i firefox) >/dev/null 2>&1; do printf "connecting...\n"; sleep 0.2; done
	else
		docker run -d -P --name=container$COUNTER --link selenium-hub:hub -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -e SCREEN_DEPTH=24 selenium/node-chrome
		while ! (curl -sSL "http://localhost:4446/grid/console" | grep -i chrome) >/dev/null 2>&1; do printf "connecting...\n"; sleep 0.2; done
    fi
	
	let COUNTER=COUNTER+1 
done
`

**Comment by diemol** [comment]
When you said
>but it does work with my own firefox install and selenium server

What versions of Firefox and Selenium server were you using? How did you start the Selenium server?

**Comment by lmtierney** [comment]
Please also share some of the javascript code you are using to produce this error

**Comment by jmurphy87** [comment]
firefox version is 61.0.2 and selenium is 3.14.0.

#!/usr/bin/env bash

cd `dirname $0`

nohup ../node_modules/.bin/webdriver-manager start &

**Comment by jmurphy87** [comment]
let me just go ahead and get a test project going

**Comment by lmtierney** [comment]
Sigh... you're using protractor, which is known to have issues with geckodriver. I wish you would have mentioned that. Have you raised the issue there? This definitely isn't a docker issue so it shouldn't be in this repo; but I don't know what repo it should be in. We may be able to narrow it down if you use a SMALL reproducible scenario using ONLY the selenium-webdriver node library. I will not be running shell scripts without digging into all of them to see what exactly will run, and I don't have time to do that.

**Comment by jmurphy87** [comment]
I placed the issue here because it does work outside of docker. It just seems like the container is missing something that my local has.

**Comment by lmtierney** [comment]
I'll be happy to look if you provide a scenario outside of shell scripts and using selenium-webdriver. Other than that (using webdriver-manager and protractor) I will be unable to help. It should be as simple as the command line command you use to start your docker instance and a small snippet of js code. Other than that, I'll leave it up to someone else to tackle this.

**Comment by jmurphy87** [comment]
Well, unfortunately at this point it is going to cost the company more money than the value of having both chrome and firefox tests if I continue to work on this. Thank you for your time, and for helping me out!
