### ISSUE TITLE
Both Chrome and Firefox are getting executed on firefox debug node during parallel execution.

### ISSUE THREAD

**Issue by anshuman00329** [SeleniumHQ/docker-selenium#775]
Image(s):  
    selenium/hub:3.14.0-beryllium
    selenium/node-firefox-debug:3.14.0-beryllium
    selenium/node-chrome-debug:3.14.0-beryllium
Docker Version:  
    18.06.0-ce, build 0ffa825
OS: 
    Windows 10

-->
## Expected Behavior - 
    1. Chrome browser should launch and test case should be executed on chrome debug node.
    2. Firefox browser should launch and test case should be executed on firefox debug node.

## Actual Behavior - Both the executions are happening on firefox debug node.

Note:
1. Issue is observed during parallel execution.
2. If test case is executed on one browser(Chrome/Firefox) execution is proper.

Steps to reproduce:
1. docker-compose up -d command is used to launch the hub and nodes, compose file is below:

version: '2'
services:
  firefox:
    image: selenium/node-firefox-debug:3.14.0-beryllium
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome-debug:3.14.0-beryllium
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-beryllium
    ports:
      - "4444:4444"

2. Java code to handle the execution:

String nodeURL = ""http://localhost:4444/wd/hub"";
public static WebDriver driver;
public static DesiredCapabilities capability;

public static WebDriver launchBrowser(String executionEnv, String browser) throws MalformedURLException {
  if(executionEnv.equals("docker")){
            if (browser.equalsIgnoreCase("firefox")) {
                capability = new DesiredCapabilities().firefox();
                driver = new RemoteWebDriver(new URL(nodeURL), capability);
            }
            else if (browser.equalsIgnoreCase("chrome")) {
                capability = new DesiredCapabilities().chrome();
                driver = new RemoteWebDriver(new URL(nodeURL), capability);
            }
        }
   return driver;
}

3. TestNG.xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite parallel="tests" name="Autothon" thread-count="2" preserve-order="true">
<test name="FirefoxTest" parallel = "false" preserve-order="true" >
        <parameter name="executionEnv" value="docker"/>
        <parameter name="browser" value="firefox" />
        <classes>

            <class name="driver.DriverLaunch" />

        </classes>

    </test>
</suite>

**Comment by diemol** [comment]
Hi @anshuman00329,

Please complete the full template and provide us a well formatted script so we can reproduce the issue.

**Comment by anshuman00329** [comment]
Hi @diemol  I filled all the configuration related information from the template.

Please let me know if any specific information is needed on the issue.

**Comment by anshuman00329** [comment]
Apologies @diemol  I have updated the same.

**Comment by diemol** [comment]
The problem lays down in the Java code, you are using `public static WebDriver driver;`.

Having it as a public static variable means that all tests running will reuse the same variable, which ends up in one test using a session created by another test. That is why it always works sequentially but not in parallel.

Please double check your code and ensure that the driver creation part is thread safe.
