### ISSUE TITLE
Chrome and proxy environment variables

### ISSUE THREAD

**Issue by cristian-smocot** [SeleniumHQ/docker-selenium#78]
Chrome doesn't respect ``http_proxy`` and`` https_proxy`` environment variables.

I'm using the variables like this
```
https_proxy=http://user:password@proxycorp.com:8080
http_proxy=http://user:password@proxycorp.com:8080
```

I've also tried:
```
https_proxy=user:password@http://proxycorp.com:8080
http_proxy=user:password@http://proxycorp.com:8080
```
to no avail.

I've also used the uppercase variants like HTTP_PROXY and HTTPS_PROXY, with no success.

Chrome doesn't respect these environment variables.
In the debug images, I used bash to see if my environment variable exist, and they do. When I start the container in `ENV` I put the proxies environment variables.

**Comment by cristian-smocot** [comment]
In case anyone is interested for a fix or workaround this, here is what I did:
 - I Installed these extensions on Chrome
  * [__Proxy Auto Auth__](https://chrome.google.com/webstore/detail/proxy-auto-auth/ggmdpepbjljkkkdaklfihhngmmgmpggp?hl=en)
  * [Give Me CRX](https://chrome.google.com/webstore/detail/give-me-crx/acpimoebmfjpfnbhjgdgiacjfebmmmci?hl=en)

__Give me CRX__ is only used in your local browser (not the Docker Node Chrome) to obtain the .crx file of the first extension, __Proxy Auto Auth__. 

I installed on my local browser the extension __Proxy Auto Auth__, only to play with it and see what is the URL for the options of this extension.

Anyway, it seems, that the options object that you pass to Selenium, for Chrome, can take the following structure:
``` javascript
 var options = {

	host                         : '127.1.2.3',
	port                         : 4444,

	desiredCapabilities          : {
		seleniumProtocol         : 'WebDriver',
		platform                 : 'any',
		browserName              : 'chrome',
		acceptSslCerts           : true,
		cssSelectorsEnabled      : true,
		handlesAlerts            : true,
		unexpectedAlertBEhaviour : 'accept',

		proxy                    : {
			proxyType            : 'MANUAL',
			httpProxy            : 'proxycorp.com:8080'
//or you can put here user:password@proxycorp.com:8080, but not every proxy is recognized by Chrome,
//when I used my corporate proxy, Chrome is asking for the user and password and ignore what I put here
			sslProxy             : 'proxycorp.com:8080',
			ftpProxy             : 'proxyCorp.com:8080'
		},

		chromeOptions            : {
			extensions           : [
 'This string must be a BASE64 encoded string of the file content of the .crx Chrome extension',
 'This string is yet another BASE64 encoded string of the file content of the yet another .crx Chrome extension',
									]
		}
	}
};
```

Take notice of:
  -  __`options.desiredCapabilities.proxy`__
  - __`options.desiredCapabilities.chromeOptions.extensions`__

So, what I did was:
  - I obtained the __`.crx`__ file of the extension ProxyAutoAuth

  - I read this file with 
``` javascript 
var Q  = require('q'),
	fs = require('fs');

var readCrxExtension = function (file) {

	var deferred = Q.defer();

	fs.readFile(file, function (error, data) {
		error
			? deferred.reject(error)
			: deferred.resolve(data.toString('base64'));
	});

	return deferred.promise;
};

readCrxExtension('extension_file.crx')
	.then(function (base64String) {
		options.desiredCapatilities.chromeOptions.extensions.push(base64String);
	});
```

  - I  set the BASE64 encoded string in the  __`options.desiredCapabilities.chromeOptions.extensions`__ with   
```javascript
options.desiredCapabilities.chromeOptions.extensions.push(base64String);
```
  
 - before any kind of automation test, In chrome, in the Docker container, I instruct Webdriver to:
  * got to the url of the extension, which is chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html
  * set the user and password of the propxy and save
``` javascript
client
	.url('chrome-extension://ggmdpepbjljkkkdaklfihhngmmgmpggp/options.html')
	.setValue('//*[@id="login"]', 'user001')
	.setValue('//*[@id="password"]', 'pass123#')
	.click('//*[@id="save"]');
```

The above code is using [__Webdriver.io__](http://webdriver.io/) library.
What the above code does, is:
  - navigates to the options page of the extension
  - sets the user and password
  - clicks on SAVE button

This will ensure that if Chrome needs to authenticate  with the proxy, the extension will automatically apply the proxy auth data to Chrome.


Credits: [__http://stackoverflow.com/a/27278322/4999637__](http://stackoverflow.com/a/27278322/4999637)

**Comment by bbaassssiiee** [comment]
This issue has been closed without a fix.
