### ISSUE TITLE
API to check if a node is registered to the grid

### ISSUE THREAD

**Issue by moijes12** [SeleniumHQ/docker-selenium#783]
Hi

I have a setup a selenium grid setup with a hub and 2 nodes. Is there any API at the host level or at the grid level which tells me if the node is registerd to the hub ? I can check the number of free slots using grid/api/hub/status . However, is there an API which provides the node registration status ?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
