### ISSUE TITLE
Sporadic failure of node-firefox with "Error: cannot open display: :99"

### ISSUE THREAD

**Issue by anto-ac** [SeleniumHQ/docker-selenium#785]
## Meta -

Image(s):  
node-firefox

Docker-Selenium Image Version(s):  
3.14.0-curium and previous versions

Docker Version:  
17.06.2-ce

OS: 
Debian 3.16.43-2 (2017-04-30)

Setup:

- wdio grid with a hub, 8 chrome nodes and 8 firefox nodes.
- Tests run on a Jenkins slave
- Here you can find a simple repository with a simplified version of the test setup: https://github.com/anto-ac/node-firefox-cannot-open-display

## Expected Behavior -

All nodes work as expected throughout the duration of the test run.

## Actual Behavior -

Sporadically, one or firefox nodes fail to have a session initiated, leading to the spec assigned to that session not being executed and the whole.
This happens mostly when there are two jobs running in parallel on the same node. 
The error is:

```
selenium-firefox-6_1  | 11:07:32.919 INFO [ActiveSessionFactory.apply] - Capabilities are: {
selenium-firefox-6_1  |   "browserName": "firefox",
selenium-firefox-6_1  |   "handlesAlerts": true,
selenium-firefox-6_1  |   "javascriptEnabled": true,
selenium-firefox-6_1  |   "locationContextEnabled": true,
selenium-firefox-6_1  |   "loggingPrefs": {
selenium-firefox-6_1  |     "browser": "ALL",
selenium-firefox-6_1  |     "driver": "ALL"
selenium-firefox-6_1  |   },
selenium-firefox-6_1  |   "maxInstances": 8,
selenium-firefox-6_1  |   "moz:firefoxOptions": {
selenium-firefox-6_1  |     "log": {
selenium-firefox-6_1  |       "level": "trace"
selenium-firefox-6_1  |     }
selenium-firefox-6_1  |   },
selenium-firefox-6_1  |   "requestOrigins": {
selenium-firefox-6_1  |     "url": "http:\u002f\u002fwebdriver.io",
selenium-firefox-6_1  |     "version": "4.13.1",
selenium-firefox-6_1  |     "name": "webdriverio"
selenium-firefox-6_1  |   },
selenium-firefox-6_1  |   "rotatable": true
selenium-firefox-6_1  | }
selenium-firefox-6_1  | 11:07:32.924 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
selenium-firefox-6_1  | 1536664052956	geckodriver	INFO	geckodriver 0.21.0
selenium-firefox-6_1  | 1536664052961	geckodriver	INFO	Listening on 127.0.0.1:18242
selenium-firefox-6_1  | 1536664053031	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Ryd3XPLJrwdQ"
selenium-firefox-6_1  | 1536664053033	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:51617
selenium-firefox-6_1  | Failed to connect to Mir: Failed to connect to server socket: No such file or directory
selenium-firefox-6_1  | Unable to init server: Could not connect: Connection refused
selenium-firefox-6_1  | Error: cannot open display: :99
selenium-firefox-6_1  | 1536664053235	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}}
ui-test_1             | ERROR: Process unexpectedly closed with status 1
ui-test_1             | Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
ui-test_1             | System info: host: '717d6d70bd0f', ip: '172.19.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-4-amd64', java.version: '1.8.0_181'
ui-test_1             | Driver info: driver.version: unknown
ui-test_1             | remote stacktrace: 
ui-test_1             | firefox
ui-test_1             |     at new RuntimeError (/home/xxxxxx/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
ui-test_1             |     at Request._callback (/home/xxxxxx/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
ui-test_1             |     at Request.self.callback (/home/xxxxxx/node_modules/webdriverio/node_modules/request/request.js:186:22)
ui-test_1             |     at emitTwo (events.js:126:13)
ui-test_1             |     at Request.emit (events.js:214:7)
ui-test_1             |     at Request.<anonymous> (/home/xxxxxx/node_modules/webdriverio/node_modules/request/request.js:1163:10)
ui-test_1             |     at emitOne (events.js:116:13)
ui-test_1             |     at Request.emit (events.js:211:7)
ui-test_1             |     at IncomingMessage.<anonymous> (/home/xxxxxx/node_modules/webdriverio/node_modules/request/request.js:1085:12)
ui-test_1             |     at Object.onceWrapper (events.js:313:30)

```

## What has been tried already -

1. These PRs were made to improve how the xbvr DISPLAY is chosen:
 - https://github.com/SeleniumHQ/docker-selenium/pull/778/commits/8fdb9290a5f9869e402f16fe5d2712caa1c39c54
 - https://github.com/SeleniumHQ/docker-selenium/pull/779/commits/640f37098724d934ef8dce25b243e65e21c69e0b
2. `dbus-x11` has been installed on the host machine as suggested here: https://github.com/SeleniumHQ/docker-selenium/issues/31.

**Comment by diemol** [comment]
Hi @anto-ac,

Just to keep digging into the issue, is this only happening in Debian 3.16.43-2? What if you try a different OS?

**Comment by diemol** [comment]
Yes, to discard that it is something related to that environment, to have a different OS for the host, not the images.

**Comment by anto-ac** [comment]
I've just verified that this also happens on Debian Stretch (4.9.0-3-amd64).

I haven't had a chance to try on Ubuntu yet.

**Comment by diemol** [comment]
Is it possible to reproduce the issue by running the tests without Jenkins?
E.g. running the test suite from the command line two or more times concurrently?

**Comment by anto-ac** [comment]
Yes, it’s possible. I’ve reproduced it without Jenkins and directly on a machine on both Jessie and Stretch versions of Debian.

**Comment by anto-ac** [comment]
Simply by running the run-tests.sh script on two different shells.

**Comment by cgoldberg** [comment]
geckodriver listens on port 4444 by default.  Once running, you can can't bind to the same socket again.  Subsequest instances need to be called with the --port option to specifying a unique port (--port=0 will have geckodriver choose a free port)

**Comment by whimboo** [comment]
We had a similar problem with Mir, and after upgrading the docker image from using Ubuntu 16.04 to Ubuntu 18.04, it's all fine now.

**Comment by anto-ac** [comment]
@whimboo Which docker image? 

I’ve had promising resaults using a host with Ubuntu 18.04 rather than Debian.

**Comment by whimboo** [comment]
Actually Vagrant is used but I just wanted to point out that a possible upgrade could fix the problem too. For details see https://github.com/web-platform-tests/results-collection/issues/602#issuecomment-424064941.

**Comment by anto-ac** [comment]
An upgrade of the host or of the docker images?

**Comment by diemol** [comment]
That's interesting... I cannot say why it does not work in the version of Centos you were trying. But happy to know it has not failed in Ubuntu 18.04.

Should we keep this issue open?

**Comment by anto-ac** [comment]
It was Debian, not CentOS :-)

I think we can close it for now. Should it happen again or should someone else be impacted by it, it can still be reopened.

**Comment by diemol** [comment]
Right, I read Debian and I wrote CentOS, sorry! 

OK, I will close it and in any case we can reopen as you mention. Thank you for the feedback.
