### ISSUE TITLE
Examples for running the images in kubernetes

### ISSUE THREAD

**Issue by reegnz** [SeleniumHQ/docker-selenium#794]
The README only provides exampes for running via plain docker-cli and docker-compose.
I would welcome it if the README would be extended with a simplified kubernetes example as well.

I already did such an example myself that could be used as a base for that: https://github.com/reegnz/kube-selenium-grid

Would that be a good idea to include such an example?
I am open to doing a PR for that.

**Comment by ay0o** [comment]
You have such examples on Kubernetes repository.

https://github.com/kubernetes/examples/tree/master/staging/selenium

**Comment by reegnz** [comment]
Cool, didn't know about that, thanks!
I will then issue a PR to mention that in the README as well.
