### ISSUE TITLE
Setting REMOTE_HOST causes node register/unregister loop

### ISSUE THREAD

**Issue by ay0o** [SeleniumHQ/docker-selenium#799]
## Meta -
Image(s):  
node-chrome, hub

Docker-Selenium Image Version(s):  
3.14 (francium and europium)

Docker Version:  
18.06.1-ce

OS: 
MacOS 10.13.6, Ubuntu 16.04 (only Mac, Only Ubuntu, and mixed Mac and Ubuntu, all cases failed)

## Expected Behavior -
To be able to establish a stable connection between a hub and a node on a different machine, setting `REMOTE_HOST`

## Actual Behavior -
If `REMOTE_HOST` is set, the node is constantly registering and unregistering. 

To discard any possible network issue, I tried to also run both containers in the same host, setting `HUB_HOST` and `REMOTE_HOST` to that host's IP. Same issue happen. 

If `REMOTE_HOST` is not set, everything is fine. However, I need it for using nodes on different hosts with the same hub.

Hub log:

```
09:41:54.366 INFO [DefaultGridRegistry.add] - Registered a node http://192.168.107.68
09:41:54.368 WARN [DefaultGridRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://192.168.107.68
```

Node log:
```
09:41:48.716 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://192.168.107.68:4444/grid/register
09:41:49.312 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
```

## Steps to reproduce -
If trying with a single host:
`docker run -d -p 4444:4444 --name selenium-hub --rm selenium/hub:3.14`
`docker run -d --name chrome --rm -e "HUB_HOST=<HOST_IP>" -e "HUB_PORT=4444" -e "REMOTE_HOST=http://<HOST_IP>" --shm-size=2g selenium/node-chrome:3.14`

In this case, if you remove the `REMOTE_HOST` variable, it will work.

If trying with N different hosts (my actual need):
Host A: `docker run -d -p 4444:4444 --name selenium-hub --rm selenium/hub:3.14`
Host B: `docker run -d --name chrome --rm -e "HUB_HOST=<HOST_A_IP>" -e "HUB_PORT=4444" -e "REMOTE_HOST=http://<HOST_B_IP>" --shm-size=2g selenium/node-chrome:3.14`

Here you can't remove `REMOTE_HOST` because otherwise the HUB will get the container IP in the docker network, and therefore, won't be able to reach it.

**Comment by JordiGiros** [comment]
I think I'm experimenting  the same problem. My node-chrome docker service dies again and again while trying to reconnect to the hub. Impossible to run any chrome test.

 version: '3'

services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    deploy:
     mode: global
     placement:
       constraints:
         - node.role == manager
    environment:
     - GRID_BROWSER_TIMEOUT=0
     - GRID_TIMEOUT=60000
     - GRID_MAX_SESSION=50
     - GRID_MAX_INSTANCES=20
     - GRID_CLEAN_UP_CYCLE=60000
     - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
     - GRID_NEW_SESSION_WAIT_TIMEOUT=60000
    networks:
     - back
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
      - GRID_CLEAN_UP_CYCLE=60000
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5556 -browserTimeout 600 -sessionTimeout 600" /opt/bin/entry_point.sh'
    ports:
      - "5556:5556"
    deploy:
      replicas: 1
    networks:
      - back
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M

networks:
  back:
    external: true

**Comment by ay0o** [comment]
@JordiGiros I think we are speaking here of different issues. You are deploying the stack with Swarm or with docker-compose, and therefore, you are using the Docker Network. At least for me, sharing through Docker Network is fine.

In my case, I don't want to use the Docker Network. Each node will be stand-alone on their own host, host that is not member of a Swarm either.

**Comment by captainbuzzlightyear** [comment]
I can confirm this issue! Using: 3.14 (francium and europium)

**Comment by ay0o** [comment]
Ok, just found the issue, a misconfiguration on my end.

There were two issues going on:
- I wasn't adding the port to `REMOTE_HOST`, so the Hub was actually trying to reach the node on `http://192.168.107.68` instead of `http://192.168.107.68:5555`.
- Once the previous was fixed, I obviously needed to open port 5555 as well on the chrome container.
