### ISSUE TITLE
Cannot kill a standalone image started with the `--rm` option

### ISSUE THREAD

**Issue by aberonni** [SeleniumHQ/docker-selenium#806]
## Meta
Image(s):  
selenium/standalone-chrome-debug

Docker-Selenium Image Version(s):  
3.14.0-gallium

Docker Version:  
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

OS: 
macOS High Sierra 10.13.6

## Expected Behavior -
When running a standalone image with the `--rm` option, I should be able to kill it by simply using `ctrl+c`
## Actual Behavior -
I have to switch to another terminal instance and run `docker kill <docker instance name>` to kill it

## Steps to reproduce -
`docker run --name selenium-chrome --rm -p 4444:4444 -p 5900:5900 --shm-size=2g selenium/standalone-chrome-debug:3.14.0-gallium`

Try to kill with `ctrl+c`

## Extra notes

Works as expected with the previous version, https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.14.0-francium

**Comment by diemol** [comment]
Fix has landed to master, will be released soon.
