### ISSUE TITLE
GRID_TIMEOUT does not match default selenium

### ISSUE THREAD

**Issue by rubytester** [SeleniumHQ/docker-selenium#81]
Just noticed that [default timeout in selenium](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultHub.json#L12) is `300000` but in our docker GRID_TIMEOUT [the default is](https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile.txt#L13) `30000`.

Has someone forgot the extra `0` or was this shorter timeout by design? 

I would really like to modify the default to `300000` (5 min). 

thoughts?

**Comment by elgalu** [comment]
Yeah looks like a typo.

**Comment by rubytester** [comment]
maybe a typo or the mozilla grid also has the 30 second timeout but they have 180 seconds for hanging browserTimeout. 

https://github.com/mozilla/moz-grid-config/blob/master/hub_configuration.json#L2

I am curious why? 30 seconds idle kills your session while they wait 180 seconds after browser becomes dead.

**Comment by aksharpanchal** [comment]
+1

**Comment by ddavison** [comment]
I'm sure this doesn't happen anymore.  Closing.
