### ISSUE TITLE
Not able to run my testcase in firefox using Protractor.

### ISSUE THREAD

**Issue by ochanig33** [SeleniumHQ/docker-selenium#810]
I have used docker-compose to create a selenium grid, chrome and firefox containers. All these containers gets up and running however when I am trying to run in protractor, tests are running fine in chrome but not in firefox. Can you please help ?

docker-compose.yml
#Mainter : Promode
version: '2'

services:
    progrid:
        image: selenium/hub:3.1.0
        container_name: progrid
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - progrid_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:2.53.1-americium
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - progrid_grid_internal

    nodefirefox:
        image: selenium/node-firefox-debug:2.53.1
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5901  
        environment:
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - progrid_grid_internal

networks:
    progrid_grid_internal:

-----------------------------------------------------------------------------------------------------------------------------
config.js
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    baseUrl: baseUrl,
    params: {
        screen: {
            width: screen[0],
            height: screen[1]
        },

// Please ignore this below line
        screenshotPath: "./report/WI/" + serverConfig.browserName

    },
    allScriptsTimeout: 25000,
    //capabilities: capabilities

  multiCapabilities: [{
    'browserName': 'firefox'
  }, {
    'browserName': 'chrome'
  }],
    suites: suites,
    specs: specs,

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 3600000
    },

    framework: "jasmine2",
    onPrepare: '../utilities/WIpreparation.js'

};

**Comment by ochanig33** [comment]
Sorry, I tried to see this issue again and feel that I am not able to connect using VNC but tests are running in protractor. Can someone please review the docker-compose.yml file ?

**Comment by diemol** [comment]
Hi @ochanig33,

You are not mapping the VNC ports to your host. You need to do something like `- 5900:5900`.

Anyway, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
