### ISSUE TITLE
DevToolsActivePort file doesn't exist when container used by Jenkins ?? 

### ISSUE THREAD

**Issue by AlbertShamsiyan** [SeleniumHQ/docker-selenium#822]
## 🐛 Bug Report

Tests are successfully executed when using the image manually, yet, failes when using Jenkinsfile to orchatrate proccess. 

## To Reproduce

1. Spin up container using `docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome` 
2. Execute selenium testings using `mvn clean test` etc - successful passed. 
3. stop container. 
4. Try to have this proccess managed by Jenkinsfile using:
`
def server = Artifactory.server 'Artifactory'
def rtMaven = Artifactory.newMavenBuild()
def buildInfo
docker.image("selenium/standalonechrome:latest").inside('--volume=/dev/shm:/dev/shm --publish=4444:4444')
{
	stage ('code Build') 
	{
		timestamps 
		{
			try 
			{
				withEnv(['JAVA_HOME=/usr/jdk1.8.0_171/', 'MAVEN_HOME=/usr/local/apache-maven/'])
				{ // Java home of the container							
					rtMaven.run pom: 'allure-junit-example-master/pom.xml', goals: 'clean test', buildInfo: buildInfo
					//sh 'sleep 8200'
				}
			} 
			catch(err) 
			{
				echo "****************Error: " + err
				//	sh 'sleep 8200'
				throw err										
			}				
		}
	}
}
`
5. The follwing error shall be raised:

> org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
>   (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 3.10.0-862.3.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 

> Client:
>  Version:      18.03.1-ce
>  API version:  1.37
>  Go version:   go1.9.5
>  Git commit:   9ee9f40
>  Built:        Thu Apr 26 07:20:16 2018
>  OS/Arch:      linux/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:23:58 2018
>   OS/Arch:      linux/amd64
>   Experimental: false

Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Hi @AlbertShamsiyan,

If it works locally and it does not work in Jenkins, it must be something in the Jenkins config.

You could try to create a freestyle project in Jenkins and enter the bash commands to run it, if it works, it is probably the Jenkinsfile.

In addition, with the information provided, there is no simple way to reproduce and verify if it is an issue.

**Comment by diemol** [comment]
Closing as we didn't get more info.
