### ISSUE TITLE
Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by bluepenfc** [SeleniumHQ/docker-selenium#825]
## 🐛 Bug Report

Fails when run selenium test against selenium/standalone-chrome:latest docker image

## To Reproduce
$ docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest

## Expected behavior

Expect test to run

## Test script reproducing this issue (when applicable)

             RemoteWebDriver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new 
              ChromeOptions());
             string homepage = "http://www.google.co.uk";
             driver.Navigate().GoToUrl(homepage);

get following error:
Message: System.InvalidOperationException : Unable to create new service: ChromeDriverService
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: '*******', ip: '1*****', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown (SessionNotCreated)

## Environment

OS: local Windows 7
Docker-Selenium image version: selenium/standalone-chrome:latest
"Id": "sha256:3cd2e1cdb9bb7d03deecec259bfe052fbefb7e7c585e699e631c7316c9b62c71"
-->
Docker version: local 18.06.1-ce
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Hi @bluepenfc, 

You report Windows 7 as operating system, but docker 18.06.1-ce needs Windows 10 to run.

Are you sure that you have the right components installed?

Could you also provide the logs from the docker container?

**Comment by bluepenfc** [comment]
yes, my host machine is Windows 7.
Docker version 18.03.0-ce, build 0520e24302
here is the default configuration I get from http://localhost:4444/grid/console
browserTimeout: 0

debug: false

host: ********************

port: 4445

role: node

timeout: 1800

cleanUpCycle: 5000

maxSession: 5

capabilities: Capabilities {browserName: internet explorer, jenkins.nodeName: (master), maxInstances: 1, platform: VISTA, platformName: VISTA, seleniumProtocol: WebDriver, server:CONFIG_UUID: 00f2b1c1-9407-49de-b7bc-a13..., version: 11}

capabilities: Capabilities {browserName: firefox, jenkins.nodeName: (master), maxInstances: 5, platform: VISTA, platformName: VISTA, seleniumProtocol: WebDriver, server:CONFIG_UUID: c8df28ac-4884-4b93-971a-0c8..., version: 8}

capabilities: Capabilities {browserName: chrome, jenkins.nodeName: (master), maxInstances: 5, platform: VISTA, platformName: VISTA, seleniumProtocol: WebDriver, server:CONFIG_UUID: 2f04056b-d455-4eae-b6b9-a42..., version: 8}

downPollingLimit: 2

hub: http://localhost:4444/wd/hub

id: http://********:4445

nodePolling: 5000

nodeStatusCheckTimeout: 5000

proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy

register: true

registerCycle: 5000

remoteHost: http://NSL-5CG6111WB2.corporate.administaff.com:4445

unregisterIfStillDownAfter: 60000

<h1>here is the log from docker:</h1>

2018-11-01 20:55:48,317 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing

2018-11-01 20:55:48,335 INFO supervisord started with pid 7

2018-11-01 20:55:49,341 INFO spawned: 'xvfb' with pid 10
2018-11-01 20:55:49,345 INFO spawned: 'selenium-standalone' with pid 11

2018-11-01 20:55:50,356 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2018-11-01 20:55:50,356 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

20:55:53.659 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'

20:55:53.661 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444

2018-11-01 20:55:54.157:INFO::main: Logging initialized @4063ms to org.seleniumhq.jetty9.util.log.StdErrLog

20:55:54.770 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444

**Comment by diemol** [comment]
@bluepenfc

I think you missed my point, if you check the docker requirements, it is not possible to install version 18.03.0-ce on Windows 7. So the docker container must be running in a different machine.

In addition, the docker logs do not show any error, they just show how successfully the container started.

My assumption is that the container is running in a different machine, otherwise you would see more activity in the docker logs (e.g. showing how the session is requested and so on...).

**Comment by bluepenfc** [comment]
@diemol 

Hi: It is an issue related to company firewall, security policies. It runs smoothly on my home computer.
Thanks,
