### ISSUE TITLE
Hub doesn't release a node after a GRID_TIMEOUT

### ISSUE THREAD

**Issue by FzmTYustas** [SeleniumHQ/docker-selenium#828]
## Meta
OS: Ubuntu 14.04.3 LTS with latest docker images: Hub + NodeFirefoxDebug
Selenium Version: 3.14.0
Browser: Firefox
Browser Version:  62.0.3

## Environment
- 4 selenium/node-firefox-debug images + 1 selenium/hub images (run using docker-compose)
- GRID_TIMEOUT=30

Hub config:
![grid_config](https://user-images.githubusercontent.com/33956805/47214061-7de4a080-d3a5-11e8-8d46-51c6b24400f9.png)

## Steps
1. Run in a PyCharm:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep

firefox = webdriver.Remote(
          command_executor='http://localhost:4444/wd/hub',
          desired_capabilities=DesiredCapabilities.FIREFOX)

firefox.get('https://www.google.com')

sleep(120)
```
2. Stop execution of the script after ~10 seconds.
3. Wait for ~50-60 seconds.

## Result
Node is still busy in a grid console.

## Expected
Node should be released after GRID_TIMEOUT seconds.

**Comment by diemol** [comment]
@FzmTYustas, I just confirmed that it is broken in 3.14.0, and fixed in 3.141.0.
Since we have not released the docker-selenium images with 3.141.0 yet, I'll move this issue to this repo in the meantime.

**Comment by FzmTYustas** [comment]
@diemol, ok! Waiting for new images to check the fix)

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.0-actinium was just released

**Comment by FzmTYustas** [comment]
Works in 3.141.0.
