### ISSUE TITLE
Remote host resolution issue since 3.141

### ISSUE THREAD

**Issue by jdiprizio** [SeleniumHQ/docker-selenium#832]
## 🐛 Bug Report

Since updating to 3.141, remote host parameter is acting differently when connecting to the hub. Nodes connecting to the hub do not seem to use remote host and use the bridge Docker container IP address instead.

Example Hub log for 3.14 below:
```
[...]
10:08:17.826 INFO [Hub.start] - Selenium Grid hub is up and running
10:08:17.826 INFO [Hub.start] - Nodes should register to http://172.18.0.4:4444/grid/register/
10:08:17.826 INFO [Hub.start] - Clients should connect to http://172.18.0.4:4444/wd/hub
10:08:19.585 INFO [DefaultGridRegistry.add] - Registered a node http://chrome_1.selenium:5555
```

Hub log for 3.141:
```
[...]
10:08:49.914 INFO [Hub.start] - Selenium Grid hub is up and running
10:08:49.914 INFO [Hub.start] - Nodes should register to http://172.18.0.4:4444/grid/register/
10:08:49.914 INFO [Hub.start] - Clients should connect to http://172.18.0.4:4444/wd/hub
10:08:51.740 INFO [DefaultGridRegistry.add] - Registered a node http://172.18.0.6:5555
```

## To Reproduce

Example problematic compose file:
```
version: '3'
services:
  chrome_1:
    image: selenium/node-chrome:3.141
    container_name: selenium_chrome_1
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub.selenium
      HUB_PORT: 4444
      REMOTE_HOST: 'http://chrome_1.selenium:5555'
    networks:
      selenium:
        aliases:
          - chrome_1
  hub:
    image: selenium/hub:3.141
    container_name: selenium_hub
    restart: always
    networks:
      selenium:
        aliases:
          - hub

networks:
  selenium:
    external: true
```

You should create an external network: `docker network create selenium`

Downgrading Selenium Hub and Node to 3.14 will fix the issue.

## Expected behavior

Nodes should register with the remote host address instead of an IP.

## Environment

OS: Debian Stretch
Docker-Selenium image version: 3.141 (hub: `4493038e8e4f` ; node-chrome : `729577b4908d`)
Docker version: 18.06.1-ce
Docker-Compose version (if applicable): 1.23.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): `docker-compose up -d`

**Comment by diemol** [comment]
Hi @jdiprizio,

Yes, there is a regression there. This will be fixed when we merge https://github.com/SeleniumHQ/selenium/pull/6627 and release.

**Comment by gaurav517** [comment]
Any idea when it is going to be released? Thanks.

**Comment by diemol** [comment]
It was released a moment ago, we will be releasing new images through the day.

**Comment by diemol** [comment]
Hi, the release has been done https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-antimony

and the images are currently being built and pushed
https://travis-ci.org/SeleniumHQ/docker-selenium/builds/455164406

**Comment by jdiprizio** [comment]
Awesome work and thanks a lot for keeping us updated!
