### ISSUE TITLE
Selenium fails to launch when running on a single cpu

### ISSUE THREAD

**Issue by stephenarifin** [SeleniumHQ/docker-selenium#834]
## 💥 Regression Report

In v3.141.0, there was a regression where Selenium throws an exception when ran on a single core processor. The issue is tracked [here](https://github.com/SeleniumHQ/selenium/issues/6605), and was fixed in v3.141.5.

Can we update to v3.141.5 to fix this bug in the docker image?

**Comment by diemol** [comment]
Hi @stephenarifin,

This has been released https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.5-astatine
and it is being currently pushed to Docker Hub https://travis-ci.org/SeleniumHQ/docker-selenium/builds/452029448, 
Please check in a few moments.
