### ISSUE TITLE
Firefox not launching URL when running tests in selenium/node-firefox-debug

### ISSUE THREAD

**Issue by aban20** [SeleniumHQ/docker-selenium#839]
## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
docker pull selenium/hub
docker pull selenium/node-firefox-debug
docker run -d -p 4446:4444 --name hub selenium/hub
docker run -d --link selenium-hub:hub -P --name node1 selenium/node-firefox-debug

## Expected behavior
Firefox browser should be started and URL should be launched.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by aban20** [comment]
While running tests , firefox gets started but does not launch the URL. Throws an error 


Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ value:
   { sessionId: '5f94263f-7b81-46c3-9137-c8f27834c92b',
     capabilities:
      { acceptInsecureCerts: true,
        browserName: 'firefox',
        browserVersion: '63.0.1',
        'moz:accessibilityChecks': false,
        'moz:geckodriverVersion': '0.23.0',
        'moz:headless': false,
        'moz:processID': 294,
        'moz:profile': '/tmp/rust_mozprofile.4RlEuSdneSwZ',
        'moz:useNonSpecCompliantPointerOrigin': false,
        'moz:webdriverClick': true,
        pageLoadStrategy: 'normal',
        platformName: 'linux',
        platformVersion: '4.9.93-linuxkit-aufs',
        rotatable: false,
        setWindowRect: true,
        timeouts: [Object],
        unhandledPromptBehavior: 'dismiss and notify',
        'webdriver.remote.sessionid': '5f94263f-7b81-46c3-9137-c8f27834c92b' } } }

Docker containers used:
selenium/hub
selenium/node-firefox-debug

Selenium server version: 3.14

**Comment by diemol** [comment]
Hi @aban20,

Could you please show us the script used to run the test? Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by arijitb1710** [comment]
Hi ,

Sorry for late reply. Was busy with work.
Please find the link of the GIT repo. Refer the README for running the test cases.
https://github.com/arijitb1710/nightwatch_automation

In the repo , there is a nightwatch.json file. This file file has a profile created as firefox which is run.
The exposed port of selenium hub is 4446 and the ip is that of the selenium hub

**Comment by diemol** [comment]
Hi @arijitb1710, 

I just checked the repo you linked above, I am not very familiar with NightWatch, but I don't see in your configuration file how you use the Grid running in the docker containers.

Have you been able to use it before? Or is this the first time you try to use a Grid with those tests?

**Comment by aban20** [comment]
Hi ,

You just need to run the selenium hub docker image and get a node-firefox-debug container registered with it.
Then , in the nightwatch.json file you need to mention the ip and port of the selenium hub. In this case it's the exposed port.
Yeah , I have used it before. I have used the node-chrome-debug container with selenium hub container.

Thanks,
Arijit

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aban20** [comment]
Hi ,

You just need to run the selenium hub docker image and get a node-firefox-debug container registered with it.

Then , in the nightwatch.json file you need to mention the ip and port of the selenium hub. In this case it's the exposed port.

Yeah , I have used it before. I have used the node-chrome-debug container with selenium hub container.

Thanks,

Arijit



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by diemol** [comment]
@aban20 but in the repo you provided, that configuration is not present. You are using the jar locally.

**Comment by arijitb1710** [comment]
Hi, 

You will get the configuration in the profile named as "firefox" in nightwatch.json file.
You can comment or erase the path for the jar. I tried that too. Same result.

**Comment by diemol** [comment]
@aban20 there is no firefox profile in that file. Could you please set the repo properly so we can try to reproduce the issue? 
Also, have you checked in the NightWatch issue tracker? I suspect this is an issue with that framework.

**Comment by arijitb1710** [comment]
In case you are having trouble viewing the setup , I am pasting the entire setup here.


{
    "src_folders" : ["tests"],
    "output_folder" : "reports",
    "custom_commands_path" : "",
    "custom_assertions_path" : "",
    "page_objects_path" : "./pageobjects",
    "globals_path" : "",
  
    "selenium" : {
      "start_process" : true,
      "server_path" : "./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.14.0.jar",
      "log_path" : "",
      "port" : 4444,
      "cli_args" : {
        "webdriver.chrome.driver" : "./node_modules/chromedriver/lib/chromedriver/chromedriver.exe",
        "webdriver.gecko.driver" : "",
        "webdriver.edge.driver" : ""
      }
    },
  
    "test_settings" : {
      "docker" : {
        "launch_url" : "http://www.google.com",
        "selenium_port"  : 4446,
        "selenium_host"  : "192.168.99.100",
        "silent": true,
        "screenshots" : {
          "enabled" : true,
          "path" : "./reports",
          "on_failure" : true,
          "on-error" : true
        },
        "desiredCapabilities": {
          "browserName": "firefox"
        },

      "default" : {
        "launch_url" : "http://www.google.com",
        "selenium_port"  : 4444,
        "selenium_host"  : "localhost",
        "silent": true,
        "screenshots" : {
          "enabled" : true,
          "path" : "./reports",
          "on_failure" : true,
          "on-error" : true
        },
        "desiredCapabilities": {
          "browserName": "chrome"
          
        }
      },

      "firefox" : {
        "launch_url" : "http://www.google.com",
        "selenium_port"  : 4446,
        "selenium_host"  : "192.168.99.100",
        "silent": true,
        "screenshots" : {
          "enabled" : true,
          "path" : "./reports",
          "on_failure" : true,
          "on-error" : true
        },
        "desiredCapabilities": {
          "browserName": "firefox",
           "marionette" : true 
        }
      },
  
      "chrome" : {
        "desiredCapabilities": {
          "browserName": "chrome"
        }
      },
  
      "edge" : {
        "desiredCapabilities": {
          "browserName": "MicrosoftEdge"
        }
      }
    }
  }
}

**Comment by arijitb1710** [comment]
I have tried running the following combinations and they run fine.

hub and node-chrome-debug
standalone firefox-debug
standalone chrome-debug

All the above combinations run fine except the combination hub and node-firefox-debug , hub node-firefox. so doesnt seem like an issue with nightwatch

**Comment by diemol** [comment]
@aban20 the file is not a valid json, I could not get it to run.

But 5 minutes of googling the same error, lead me to #677, which is your error. This will take you to https://github.com/nightwatchjs/nightwatch/issues/1628, where it says that it should be [solved in v1.0.14](https://github.com/nightwatchjs/nightwatch/issues/1628#issuecomment-439701632). 

Closing as this is a NightWatch issue and not a docker-selenium one.
