### ISSUE TITLE
Disable "Reader View" dialog

### ISSUE THREAD

**Issue by zoechi** [SeleniumHQ/docker-selenium#84]
I get this dialog every time Firefox loads a page 
![image](https://cloud.githubusercontent.com/assets/405837/8981953/dc6230b6-36bc-11e5-9eda-ca37a6238a85.png)
selenium/node-firefox-debug:2.46.0
Would be nice if this were disabled by default. Don't know if Firefox allows this though.
Might be http://stackoverflow.com/questions/30764805/how-to-disable-reader-view-in-firefox-using-webdriver

**Comment by rubytester** [comment]
You can disable it by default in using the configuration of your webdriver launcher code. Add FirefoxProfile to have a setting false for `reader.parse-on-load.enabled`. 

Sorry, this project does not have browser launcher code for configuring how to start drivers.

**Comment by zoechi** [comment]
@rubytester thanks a lot! 
Got it working google/webdriver.dart#98

**Comment by rubytester** [comment]
I am really curious what popup do you get. 
I tested on a standalone-firefox-debug and I can start a browser session and got a page has a reader iew but I didn't see any pop. youtube click here https://www.youtube.com/watch?v=HTz1Ad2FmAA

**Comment by zoechi** [comment]
See the screenshot in my first comment. I didn't get this message today but I didn't try with the same url. I just wanted to figure out how to modify Firefox config once and for all.

**Comment by rubytester** [comment]
Wow, sorry I just discovered I've had images turned OFF for github (using this http://singleclickapps.com/images-on-off/).... Ok, I see now

I presume since this was a new feature in Firefox 38 the popup showed up. Now I don't see it in Firefox 40 any more. here is a youtube clip of driving browser to a page with selenium cli. no more popup. 
https://www.youtube.com/watch?v=nUMjrdxiVOc

**Comment by zoechi** [comment]
Great, thanks for checking!  I'm just glad I finally figured out how to modify the Firefox profile using the Dart WebDriver package which isn't yet as full featured as the APIs for other languages like Java,  Python and a few others, but getting there. I needed this a few times already but wasn't able to make it work previously.
