### ISSUE TITLE
 Timed out receiving message from renderer:-0.005

### ISSUE THREAD

**Issue by louyu65** [SeleniumHQ/docker-selenium#844]
## 🐛 Bug Report

hub：selenium/hub:3.13.0
node：selenium/node-chrome:3.13.0
site:http://cj.sdust.edu.cn/
chrome version:Version 67.0.3396.99 (Official Build) (64-bit)

## To Reproduce

docker run -d -p 4444:4444 -e GRID_MAX_SESSION=700 -e GRID_NEW_SESSION_WAIT_TIMEOUT=60000 -e GRID_TIMEOUT=100 --name selehub selenium/hub:3.13.0
docker run -d --name chromenode --link selehub:hub --shm-size=512m -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 -e NODE_REGISTER_CYCLE=5000  selenium/node-chrome:3.13.0

 String domainUrl= "http://cj.sdust.edu.cn";
RemoteWebDriver webDriver = new RemoteWebDriver(url, GetChromeCapabilities());
 webDriver.navigate().to(domainUrl);

## Expected behavior

expect to get the page resource od this url
but timeout ,node print error message ,such as:
Timed out receiving message from renderer: 200.000
 Timed out receiving message from renderer: -0.005

## Environment

OS: Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

hub：selenium/hub:3.13.0
node：selenium/node-chrome:3.13.0

Docker version: docker-ce-17.12.0.ce

**Comment by louyu65** [comment]
org.openqa.selenium.TimeoutException: timeout
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.10-1.el7.elrepo.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 300.11 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'ADMIN-PC', ip: '192.168.28.141', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=LINUX, acceptSslCerts=false, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7), userDataDir=/tmp/.org.chromium.Chromium.ZmguhX}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=67.0.3396.99, browserConnectionEnabled=false, nativeEvents=true, webdriver.remote.sessionid=d0f289bf3587acb569a8e7a2febf4350, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: d0f289bf3587acb569a8e7a2febf4350

**Comment by diemol** [comment]
Hi @louyu65,

That normally means that the page you want to visit is taking too long to load, like right now, the page does not even load for me in Chrome (without using Docker).

Try to tweak the waiting time with `pageLoadTimeout` so ChromeDriver waits a bit longer for it. But moreover, check that the page is actually working. Also try to use the latest versions of bindings, and images.

Since this is not an issue with docker-selenium, I invite you to join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well, and give you tips on how to improve your test script.
