### ISSUE TITLE
Whenever I am launching selenium grid from docker on my Oracle linux VM, I notice that http://*.*.*.*:*/grid/api/hub/status shows the slotCounts as zero

### ISSUE THREAD

**Issue by avinash10993** [SeleniumHQ/docker-selenium#859]
## 🐛 Bug Report

http://*.*.*.*:*/wd/hub/status
------------------------------------
{
  "status": 0,
  "value": {
    "ready": false,
    "message": "No spare hub capacity",
    "build": {
      "revision": "e82be7d358",
      "time": "2018-11-14T08:25:53",
      "version": "3.141.59"
    },
    "os": {
      "arch": "amd64",
      "name": "Linux",
      "version": "4.1.12-124.18.6.el7uek.x86_64"
    },
    "java": {
      "version": "1.8.0_191"
    }
  }
}
----------------------------------------
 http://*.*.*.*:*:/grid/api/hub/status

{
  "browserTimeout": 0,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "cleanUpCycle": 5000,
  "custom": {
  },
  "debug": false,
  "host": "172.17.0.2",
  "jettyMaxThreads": -1,
  "newSessionRequestCount": 0,
  "newSessionWaitTimeout": -1,
  "port": 4444,
  "registry": "org.openqa.grid.internal.DefaultGridRegistry",
  "role": "hub",
  "servlets": [
  ],
  "slotCounts": {
    "free": 0,
    "total": 0
  },
  "success": true,
  "throwOnCapabilityNotPresent": true,
  "timeout": 1800,
  "withoutServlets": [
  ]
}
------------------------------------------

## Environment

OS: Oracle Linux
Docker-Selenium image version: 3.141.59
Docker version: 17.06.2-ol

**Comment by diemol** [comment]
Hi @avinash10993,

Please create new issue and fill out the complete template, in this one it is not possible to understand what is going on, what you are trying and there are no steps to reproduce it.
