### ISSUE TITLE
Add Images for Mobile Testing

### ISSUE THREAD

**Issue by th3l0g4n** [SeleniumHQ/docker-selenium#86]
Would it be possible to provide Images to support Mobile Tests?
I thought about:
http://selendroid.io and
http://appium.io/

The intention, at least from my side, is not to run tests against native apps but mobile versions of websites. It seems that both implement the JSON Wire Protocol so it might be possible?

**Comment by rubytester** [comment]
I don't know what your request is here.

You can use mobileEmulation settings in chromeOptions for chrome browser. https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation

**Comment by lukeis** [comment]
selendroid seems possible or maybe just the android aspect of appium.  But appium for iOS is a non-starter here until docker supports OSX containers.

**Comment by vbanthia** [comment]
Well, In case someone needs appium image, they can check [here](https://github.com/vbanthia/docker-appium/blob/master/appium-base/Dockerfile). I have created a base image which comes with appium and its dependencies installed.

In case docker-selenium community want to support appium too, then I would be happy to make a PR.

**Comment by diemol** [comment]
The [appium-docker](https://github.com/appium/appium-docker-android) project already exists.

I think this issue can be closed.
