### ISSUE TITLE
Chromedriver not able to launch due to address assignment.

### ISSUE THREAD

**Issue by quldude** [SeleniumHQ/docker-selenium#863]
## Bug Report

When running a test against a selenium node running as a docker container started with REMOTE_HOST parameter, chromedriver fails to bind with requested address.

## To Reproduce

1. Run below command to start a container with node registering to an external hub:
`docker run -d -p 5551:5555 -e TZ=America/Chicago -e HUB_HOST=10.15.100.35 -e HUB_PORT=4445 -e REMOTE_HOST="http://10.13.169.35:5551" -v /dev/shm:/dev/shm -v /home/vagrant/docker/Recordings:/tmp/Recordings --name node1 selenium/node-chrome`

2. Execute a test against it. At this point, the node tries to start chromedriver and the driver displays an error:
`[SEVERE]: bind() failed: Cannot assign requested address (99)`

The node is then taken out from the grid (unregisters).

Hub start command (on a different machine):
`java -jar selenium-server-standalone.jar -role hub -port 4445`

Chrome node logs:
2019-01-13 15:05:29,394 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2019-01-13 15:05:29,396 INFO supervisord started with pid 7
2019-01-13 15:05:30,399 INFO spawned: 'xvfb' with pid 10
2019-01-13 15:05:30,401 INFO spawned: 'selenium-node' with pid 11
Connecting to the Hub using the host 10.15.100.35 and port 4445
REMOTE_HOST variable is set, appending -remoteHost
2019-01-13 15:05:30,705 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-01-13 15:05:30,705 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:05:31.600 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
15:05:32.022 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
2019-01-13 15:05:32.403:INFO::main: Logging initialized @1609ms to org.seleniumhq.jetty9.util.log.StdErrLog
15:05:33.308 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
15:05:33.694 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
15:05:33.695 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
15:05:33.893 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
15:05:35.112 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://10.15.100.35:4445/grid/register
15:05:35.269 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
15:06:32.987 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "--disable-extensions",
      "disable-infobars"
    ],
    "prefs": {
      "credentials_enable_service": false,
      "download.default_directory": "\u002ftmp\u002fRecordings",
      "download.prompt_for_download": false,
      "profile.password_manager_enabled": false,
      "safebrowsing.enabled": true
    }
  },
  "loggingPrefs": {
    "performance": "ALL"
  },
  "platform": "LINUX"
}
15:06:32.992 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 8512
Only local connections are allowed.
[1547413593.095][SEVERE]: bind() failed: Cannot assign requested address (99)
15:06:36.308 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:06:37.808 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 18e24aea16a7e6c21458dbfb14108028 (org.openqa.selenium.chrome.ChromeDriverService)
15:06:38.997 INFO [ActiveSessions$1.onStop] - Removing session 18e24aea16a7e6c21458dbfb14108028 (org.openqa.selenium.chrome.ChromeDriverService)

## Expected behavior

chromedriver should not throw an error and test should run.

## Environment

OS: Ubuntu 16.04.5
Docker-Selenium image version: 3.141.59-dubnium

docker version
Client:
Version: 18.09.1
API version: 1.39
Go version: go1.10.6
Git commit: 4c52b90
Built: Wed Jan 9 19:35:23 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.1
API version: 1.39 (minimum version 1.12)
Go version: go1.10.6
Git commit: 4c52b90
Built: Wed Jan 9 19:02:44 2019
OS/Arch: linux/amd64
Experimental: false

**Comment by diemol** [comment]
Hi @quldude 

Could you please fill out the complete template? It is not possible to give any feedback with the information provided.

**Comment by quldude** [comment]
> Hi @quldude
> 
> Could you please fill out the complete template? It is not possible to give any feedback with the information provided.

I updated my info.

**Comment by diemol** [comment]
What is the full log of the node?
What happens if you remove the `-m 512m --cpus 0.5` options? 
How do you start the hub? Can you provide complete information please? Otherwise we need to fill out the gaps and probably won't be able to verify if it is an issue or not.

**Comment by quldude** [comment]
> What is the full log of the node?
> What happens if you remove the `-m 512m --cpus 0.5` options?
> How do you start the hub? Can you provide complete information please? Otherwise we need to fill out the gaps and probably won't be able to verify if it is an issue or not.

Updated with more info. I get the same result even if I remove the `-m 512m --cpus 0.5`.

**Comment by quldude** [comment]
> The `[SEVERE]: bind() failed: Cannot assign requested address (99)` is thrown by ChromeDriver but so far it does not affect the tests.
> Are tests failing in your case?

I missed to give 1 more info and that is when i start the selenium node, I run as (modified the `NodeBase/start-selenium-node.sh` script):
`java ${JAVA_OPTS} -cp "/opt/selenium/*" org.openqa.grid.selenium.GridLauncherV3 \
  -servlets com.node.servlets.ExecuteServlet,com.node.servlets.RecorderServlet,com.node.servlets.FileServlet,com.node.servlets.MouseServlet \
  -role node \
  -hub http://$HUB_PORT_4444_TCP_ADDR:$HUB_PORT_4444_TCP_PORT/grid/register \
  ${REMOTE_HOST_PARAM} \
  -nodeConfig /opt/selenium/config.json \
  -unregisterIfStillDownAfter 1 \
  ${SE_OPTS} \
  -maxSession 1 -browser $browserOpts`

Notice I pass in some servlets. Those servlets are not getting started when I run the original docker command. And so the tests stop executing because trying to access an endpoint in the node that is not registered.

But when I run the workaround docker command, I see this in the logs:

2019-01-13 15:29:54,212 WARN Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2019-01-13 15:29:54,215 INFO supervisord started with pid 7
2019-01-13 15:29:55,218 INFO spawned: 'xvfb' with pid 10
2019-01-13 15:29:55,220 INFO spawned: 'selenium-node' with pid 11
Connecting to the Hub using the host 10.15.100.35 and port 4445
2019-01-13 15:29:55,620 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-01-13 15:29:55,620 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
appending selenium options: -remoteHost http://10.13.169.35:5551
Run Selenium node.
15:29:56.692 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
15:29:57.209 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
_15:29:57.490 INFO [SelfRegisteringRemote.addExtraServlets] - binding com.node.servlets.ExecuteServlet to /extra/ExecuteServlet/*
15:29:57.491 INFO [SelfRegisteringRemote.addExtraServlets] - binding com.node.servlets.RecorderServlet to /extra/RecorderServlet/*
15:29:57.492 INFO [SelfRegisteringRemote.addExtraServlets] - binding com.node.servlets.FileServlet to /extra/FileServlet/*
15:29:57.492 INFO [SelfRegisteringRemote.addExtraServlets] - binding com.node.servlets.MouseServlet to /extra/MouseServlet/*_
2019-01-13 15:29:57.625:INFO::main: Logging initialized @1926ms to org.seleniumhq.jetty9.util.log.StdErrLog
15:29:58.787 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
15:29:59.214 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
15:29:59.214 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
15:29:59.600 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
15:30:01.100 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://10.15.100.35:4445/grid/register
15:30:01.253 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
15:34:12.496 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "--disable-extensions",
      "disable-infobars"
    ],
    "prefs": {
      "credentials_enable_service": false,
      "download.default_directory": "\u002ftmp\u002fRecordings",
      "download.prompt_for_download": false,
      "profile.password_manager_enabled": false,
      "safebrowsing.enabled": true
    }
  },
  "loggingPrefs": {
    "performance": "ALL"
  },
  "platform": "LINUX"
}
15:34:12.499 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5) on port 5901
Only local connections are allowed.
[1547415252.691][SEVERE]: bind() failed: Cannot assign requested address (99)
15:34:16.194 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
15:34:17.596 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session e50bd4f197933d66e089541d431eb96a (org.openqa.selenium.chrome.ChromeDriverService)
Remaining disk space: 34 gb / 39 gb
15:38:02.342 INFO [ActiveSessions$1.onStop] - Removing session e50bd4f197933d66e089541d431eb96a (org.openqa.selenium.chrome.ChromeDriverService)


Notice that the servlets get registered. The tests then execute successfully.

**Comment by diemol** [comment]
Of course the any non-standard Grid won't work in these docker images right away, in your case you want to use some custom servlets, therefore you would need to customise the image to hook them when the node is starting, that is completely expected.

So, please help me to understand, what is the issue?

**Comment by quldude** [comment]
> Of course the any non-standard Grid won't work in these docker images right away, in your case you want to use some custom servlets, therefore you would need to customise the image to hook them when the node is starting, that is completely expected.
> 
> So, please help me to understand, what is the issue?

My issue is why chromedriver is throwing that error `[SEVERE]: bind() failed: Cannot assign requested address (99)`? Is there something I'm missing when running the docker command:
`docker run -d -p 5551:5555 -e TZ=America/Chicago -e HUB_HOST=10.15.100.35 -e HUB_PORT=4445 -e REMOTE_HOST="http://10.13.169.35:5551" -v /dev/shm:/dev/shm -v /home/vagrant/docker/Recordings:/tmp/Recordings --name node1 selenium/node-chrome`?

**Comment by diemol** [comment]
Right, as I mentioned before, we have seen ChromeDriver throwing that message, but so far it does not affect the tests. We have done some checks and tried to avoid it, but we haven't been able to do that, and since it does not affect, we haven't taken any more actions on it. 

Nevertheless, are you having any tests failing due to that message thrown by ChromeDriver?

**Comment by quldude** [comment]
> Right, as I mentioned before, we have seen ChromeDriver throwing that message, but so far it does not affect the tests. We have done some checks and tried to avoid it, but we haven't been able to do that, and since it does not affect, we haven't taken any more actions on it.
> 
> Nevertheless, are you having any tests failing due to that message thrown by ChromeDriver?

So far I dont see tests failing due to that.

Also is there a way to specify the remote_host variable in a docker compose file such as:
version: "2.4"
services:
  chrome:
    image: dtr-node-chrome
    volumes:
      - /dev/shm:/dev/shm
      - /home/vagrant/docker/Recordings:/tmp/Recordings
    environment:
      - TZ=America/Chicago
      - HUB_HOST=172.16.24.8
      - HUB_PORT=4444
      - REMOTE_HOST=http://????
    ports:
      - "5900"
      - "5555"
    mem_limit: 512m
    cpus: 0.5
?

With this file, I'm not aware of what the public ports would be. So how would I provide the public ip and port of the node in the compose file?

**Comment by diemol** [comment]
OK, so there is no issue with the tests and it seems that it is more a questions.

About using variables in docker-compose files, you can check https://docs.docker.com/compose/environment-variables/ and https://docs.docker.com/compose/compose-file/#variable-substitution

Closing as this is not really an issue.

**Comment by webratz** [comment]
hitting the same issue, it seems to try to bind to some interfaces that are not availlable in the docker env:
`bind(10, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12 <unfinished ...>`

 `bind(9, {sa_family=AF_INET6, sin6_port=htons(9515), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28 <unfinished ...>`
it would be cool to have a way to configure the bind addresses

**Comment by maurorappa** [comment]
I have the same issuem, and it's very much likely related to:
https://github.com/RobCherry/docker-chromedriver/issues/15
