### ISSUE TITLE
Test run in headless mode by default

### ISSUE THREAD

**Issue by quyennt44** [SeleniumHQ/docker-selenium#867]
Hi,

I'm using the selenium grid docker compose version 2 to run my test: https://github.com/SeleniumHQ/docker-selenium#version-2.
When the test run, it runs in headless mode by default(the test shows steps in jenkins console but I don't see any browser is opened).
So my question is: 
- Is the headless mode is the default mode?
- If I don't want to run in headless mode, what should I do then?

**Comment by diemol** [comment]
Hi @quyennt44 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
