### ISSUE TITLE
After version 3.141.59-copernicium, webElement.isDisplayed() is giving wrong result when running multi-threaded test

### ISSUE THREAD

**Issue by djpasch** [SeleniumHQ/docker-selenium#869]
## 🐛 Bug Report
I'm running tests using TestNG framework version 6.14.3. All tests are executed using the Chromedriver.
To reduce the lead time for testing the test is running multi-threaded. My tests were running stable up and till version 3.141.59-copernicium.

After upgrading my docker container to a newer version my test results started getting flaky. This would happen when calling the webElement.isDisplayed(). This would return false, while the element was displayed.
I tried the following versions:
- 3.141.59-europium
- 3.141.59-fluorine
- 3.141.59-gold

It did not fail all the time, but occasionally.

After switching back to copernicium my tests were again stable.
My guess is, the issue is caused by chromedrivers version 2.45 and 2.46.

## To Reproduce
I'm using the following command to start the docker container:
docker run -d -e NODE_MAX_INSTANCES=20 --restart unless-stopped -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-copernicium

## Environment
OS: Linux Redhat

**Comment by diemol** [comment]
Hi @djpasch,

As you mention
>My guess is, the issue is caused by chromedrivers version 2.45 and 2.46.
is most clearly the reason.

Therefore I'd suggest to report the bug to as a ChromeDriver issue to the Chromium project: https://bugs.chromium.org/p/chromedriver. It is very important that you provide a script to reproduce the issue.

**Comment by djpasch** [comment]
After further analysis i found out the issue was caused by the framework i was using from our supplier. They were re-using an element objects causing tests to fail when running multi-threaded.
