### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by flynet** [SeleniumHQ/docker-selenium#871]
Hello, I'm going to use Hub docker container with Edge node,
Since Edge is not default option according to 
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json
Does default config support Edge or should I add my custom JSON config ?
So question is, if - yes. How I can add my own json config for HUB ?

**Comment by smccarthy** [comment]
@flynet Are you creating a docker-selenium Edge node (a windows container with selenium server + Edge) ?

**Comment by diemol** [comment]
That was the same thought I had, is it possible to run Edge in docker already @flynet? I think it is not possible yet.

**Comment by smccarthy** [comment]
@diemol I thought it was possible with Microsoft's "new" containers https://hub.docker.com/_/microsoft-windows-insider that they released last June/July ?

**Comment by flynet** [comment]
Hello. let me clarify. Yes, I'm going to run IE, Edge Microsoft Images under docker container with installed VirtualBox inside. If you are interested, please, have a look (Jencryzthers/VboxInsideDocker). I figured out that I mixed up node/hub configs. I got it working by providing correct node.json конфиг for 2.53.1 version, someone noticed that node config for config 2.x and 3.x have different syntax.

**Comment by diemol** [comment]
@flynet cool, that sounds interesting! Will follow that project and try to play with it, thanks for sharing!
