### ISSUE TITLE
unable to interact with webdriver after page load timeout.

### ISSUE THREAD

**Issue by irajtaghlidi** [SeleniumHQ/docker-selenium#875]
## 🐛 Bug Report
after `page load timeout` exception, can not interact with selenium driver. **JUST** when URL response (html) received and it is loading other staffs like JS files.

## To Reproduce
create a page with this content ( to get it with selenium) :
_we call it http://example.com/timeout.php for example here._
```html
<html>
    <head>
        <title>Page with Timeout</title>
    </head>
    <body>
        <script src="https://httpstat.us/200?sleep=600000"></script>
    </body>
</html>
```
**Python Script**
```python
from selenium import webdriver

host = 'http://localhost:4444/wd/hub'

options = webdriver.ChromeOptions()
options.add_argument('start-maximized')

desired_capabilities = options.to_capabilities()

driver = webdriver.Remote(
   command_executor = host,
   desired_capabilities = desired_capabilities)

######

driver.set_page_load_timeout(10)

try:
    driver.get('http://example.com/timeout.php')
except:
    print("Timeouted!")
	
driver.get('https://yahoo.com') # Or any other command
```
**Output:**
```
Timeouted!
Traceback (most recent call last):
  File "tests/timeout.py", line 35, in <module>
    driver.get('https://yahoo.com')
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=72.0.3626.81)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.19.8-1.el7.elrepo.x86_64 x86_64)
```

## Expected behavior

It's expected to timeout exception catched and script continue to run, and access to browser session, for example get() new URLs or interact with DOM elements of current page.

## Environment

OS: **CentOS Linux release 7.6.1810 (Core)**
Docker-Selenium image version: **3.141.59-gold** (multiple versions tested with same problem!)
Docker version: **18.09.2, build 6247962**
Docker-Compose version (if applicable): **NaN**
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
`docker run -d --name worker -p 4444:4444 -p 5900:5900 -v /opt/shared:/home/seluser/shared -v /dev/shm:/dev/shm --restart unless-stopped --network bridge-net selenium/standalone-chrome-debug:latest`

**Comment by irajtaghlidi** [comment]
I found it's a Chromedriver bug, but anyone knows any patch for that?

**Comment by diemol** [comment]
Not really, it all depends to the ChromeDriver releases. If it is a ChromeDriver bug, 
then please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver

**Comment by irajtaghlidi** [comment]
**JUST FOR ARCHIVE**

I test 10-20 version to found start of problem.

**## this setup work without problem:**

```
Selenium: 3.8.1
Google Chrome: 62.0.3202.94
ChromeDriver: 2.33.506092
Link: [3.8.1-aluminum](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.8.1-aluminum)
```

### this setup and newer does NOT work (timeout problem):

Selenium: 3.8.1
Google Chrome: 63.0.3239.84
ChromeDriver: 2.34
Link: [3.8.1-bohrium](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.8.1-bohrium)
