### ISSUE TITLE
Strange behaviour on setSize

### ISSUE THREAD

**Issue by subvertnormality** [SeleniumHQ/docker-selenium#88]
browser.manage().window().setSize has strange results when attempting to resize to a window size to a width less than 348.

```
browser.manage().window().setSize(347, 600);

browser.manage().window().getSize().then(function(size) {
    console.log('browser size', size);
});

browser.manage().window().setSize(348, 600);

browser.manage().window().getSize().then(function(size) {
   console.log('browser size', size);
});
```

Logs out the following:

```
browser size { height: 61,
  width: 348,
  class: 'org.openqa.selenium.Dimension',
  hCode: 178176 }
browser size { height: 600,
  width: 348,
  class: 'org.openqa.selenium.Dimension',
  hCode: 1433600 }
```

Ideally it should be possible to resize below 348. If this is not feasible, when attempting to resize below the minimum width the height resize should at least still honour the defined setting.

It's worth noting that this behaviour does not happen outside of the docker container.

**Comment by rubytester** [comment]
No idea. can you set size (5,5) just for fun?

Also if you are running chrome you can set chromeOptions args to  have `--window-size=340,600` on startup.

**Comment by diemol** [comment]
Closing this issue since we didn't get any feedback from the original poster.
