### ISSUE TITLE
Firefox 67 tab crashes when AudioContext is being initialized

### ISSUE THREAD

**Issue by sviik** [SeleniumHQ/docker-selenium#889]
## 🐛 Bug Report

Firefox 67 (beta) tab crashes when [initializing AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext).
Could only reproduce this when using Docker Selenium node.
Works fine when using Firefox 67 installed on my machine.
Also works fine when using `selenium/node-firefox:latest` (which currently features Firefox 66).

## To Reproduce

1. `docker build --build-arg FIREFOX_VERSION="67.0b4" --build-arg GECKODRIVER_VERSION="0.24.0" NodeFirefox -t firefox-beta`
2. `docker run -d -p 4444:4444 --name selenium-hub selenium/hub:latest`
3. `docker run --rm --link selenium-hub:hub --shm-size=2g firefox-beta`
4. Open a page and execute `new AudioContext()`. Here I'm using `execute_script` for simplicity but the outcome is the same when the code snippet is executed on the page rather than by webdriver:
```ruby
#!/usr/bin/env ruby

require 'selenium-webdriver'

client = Selenium::WebDriver::Remote::Http::Default.new
capabilities = Selenium::WebDriver::Remote::Capabilities.firefox({accept_insecure_certs: true})
driver = Selenium::WebDriver.for(:remote, url: 'http://localhost:4444/wd/hub', http_client: client, desired_capabilities: capabilities)

driver.navigate.to 'https://www.google.com/'
driver.execute_script('new AudioContext()')
driver.quit
```
Output from docker (errors are likely thrown just because the tab crashed):
```
18:14:31.117 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "cssSelectorsEnabled": true,
  "javascriptEnabled": true,
  "marionette": true,
  "nativeEvents": false,
  "rotatable": false,
  "takesScreenshot": true,
  "version": ""
}
18:14:31.117 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1553624071197	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.nXlpiI8jwJmy"
1553624071841	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1553624071842	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1553624071843	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1553624075201	Marionette	INFO	Listening on port 37285
1553624075267	Marionette	WARN	TLS certificate errors will be ignored for this session
18:14:35.367 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
18:14:35.369 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 9e6e3f60-110c-4f16-a9bb-18ada7a7d34e (org.openqa.selenium.firefox.GeckoDriverService)
[Parent 260, Gecko_IOThread] WARNING: pipe error (92): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357

###!!! [Parent][MessageChannel] Error: (msgtype=0x1F0088,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1553624075730	Marionette	INFO	Stopped listening on port 37285
18:14:36.605 INFO [ActiveSessions$1.onStop] - Removing session 9e6e3f60-110c-4f16-a9bb-18ada7a7d34e (org.openqa.selenium.firefox.GeckoDriverService
```
Output from running the Ruby snippet (same here, error was likely thrown because remote session was killed):
```
Traceback (most recent call last):
  10: from ./run.rb:43:in `<main>'
   9: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:166:in `quit'
   8: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:139:in `quit'
   7: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
   6: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
   5: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
   4: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
   3: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
   2: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
   1: from /Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/Users/sviik/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': Failed to decode response from marionette (Selenium::WebDriver::Error::UnknownError)
```

I also tested this using a NodeFirefoxDebug image which embodies Firefox 67. Ran it and used the browser via VNC client. Running `new AudioContext()` made the tab to crash immediately (the `Gah. Your tab just crashed.` page was shown).

## Expected behavior

Tab does not crash.

## Environment

OS: macOS 10.14.3
Docker-Selenium version: `3.141.59-mercury`, `2c23a3c`
Docker version 18.09.2, build 6247962

**Comment by diemol** [comment]
@sviik 
Does this only happen with the 67 beta version? Is it reproducible with 66? Do you know if something else is needed inside the container to have it working?

**Comment by sviik** [comment]
> Does this only happen with the 67 beta version?

Yes.

Happens with:
- 67 beta version in NodeFirefox

Does not happen with:
- 66 version in NodeFirefox
- 66 beta version in NodeFirefox
- 67 beta version installed on my machine

> Do you know if something else is needed inside the container to have it working?

Sorry, I don't.

**Comment by deiwin** [comment]
> Do you know if something else is needed inside the container to have it working?

@sviik, correct me if I'm wrong, but it didn't happen with the debug version with fluxbox etc installed.

**Comment by sviik** [comment]
> @sviik, correct me if I'm wrong, but it didn't happen with the debug version with fluxbox etc installed.

Nope, a little confusion there. It actually happened with the debug version, too.

**Comment by sviik** [comment]
Not an issue anymore starting from version `67.0b5`.

**Comment by sviik** [comment]
Not an issue anymore starting from version `67.0b5`.
