### ISSUE TITLE
Headless mode on Firefox - hanging after session has been created

### ISSUE THREAD

**Issue by hoooli** [SeleniumHQ/docker-selenium#890]
Hi,
I am running Selenium Hub with six Chrome nodes and six Firefox nodes.
I've just pulled latest images right now, but I am still facing same issue. When I am trying to run my simple test, it works for Chrome node as well as for Firefox node.
When I set headless to TRUE for browser options, test passed for Chrome but hanging for Firefox.

My test in Java looks like:
```
FirefoxOptions options = new FirefoxOptions();
// ChromeOptions options = new ChromeOptions();
options.setHeadless(true);
WebDriver driver = new RemoteWebDriver(new URL("http://IP_ADDR:4444/wd/hub"), options);
```
So default Options and nothing else.

Here is what I can see from command docker logs container_name:

> 17:22:08.700 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
> 17:50:21.417 INFO [ActiveSessionFactory.apply] - Capabilities are: {
>   "acceptInsecureCerts": true,
>   "browserName": "firefox",
>   "moz:firefoxOptions": {
>     "args": [
>       "-headless"
>     ],
>     "prefs": {
>     }
>   }
> }
> 17:50:21.441 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
> 1553709022243   mozrunner::runner   INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.s8cCmu6XpkVH"
> *** You are running in headless mode.
> 1553709031024   addons.webextension.screenshots@mozilla.org WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
> 1553709031026   addons.webextension.screenshots@mozilla.org WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
> 1553709031026   addons.webextension.screenshots@mozilla.org WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
> 1553709036307   Marionette  INFO    Listening on port 38441
> 1553709036387   Marionette  WARN    TLS certificate errors will be ignored for this session
> 17:50:42.133 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
> 17:50:43.708 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 4849ee02-0f11-4632-8ba1-3b62dcc4cf21 (org.openqa.selenium.firefox.GeckoDriverService)

I am running it on Oracle Linux 7.

> Docker version:
> Client:
>  Version:           18.09.1-ol
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        c3ab8a8
>  Built:             Mon Feb 11 23:20:32 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.1-ol
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.8
>   Git commit:       c3ab8a8
>   Built:            Mon Feb 11 23:09:34 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>   Default Registry: docker.io

I already have set shm to 2g via shm_size option for docker_container module in Ansible. I am using Ansible for spawning hub with nodes.

Any suggestions how to track down a root cause? Same test works no Firefox and Chrome with headed mode. But in headless mode, it works only on Chrome and not on Firefox.

Also after attempt to run it in headless mode, it is hanging and when I force stopped test run, WebDriver has been released (based on Grid Console), but when I will check this released node container, there is neverending logging of:

> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
> 

Is it related to trying run test in headless mode?
Any help or suggestions would be greatly appreciated. Thanks!

**Comment by hoooli** [comment]
I've tried to clean docker (docker system prune, docker volume prune) - nothing helped. There was not any mounted volume, but after restarting machine where containers are running, headless mode works now.

**Comment by murcraft** [comment]
I have the same issue, the part of tests is passes, but another are closed and error are appeared in Travis. I run selenium version 3.14.0 , geckodriver 0.24
```'moz:firefoxOptions': {
        args: [
          '--width=1920',
          '--height=1080',
          '--private',
          // '--headless'
        ], ...
```
Logs from Travis
```
###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x350020,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x350020,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA7000B,name=PWebSocket::Msg_OnAcknowledge) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0xA7000C,name=PWebSocket::Msg_OnServerClose) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0xA70008,name=PWebSocket::Msg_OnStop) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0087,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
FF1556634167371	Marionette	INFO	Stopped listening on port 41304
```

I noticed, that logs are not printed for a long time, when are run a large of number of tests. I tried set  verboseMultiSession: true, in protractor config file, but it doesn't matter.
