### ISSUE TITLE
Add support for Hindi

### ISSUE THREAD

**Issue by skilip** [SeleniumHQ/docker-selenium#897]
## 🚀 Feature Proposal

As a follow up on <https://github.com/SeleniumHQ/docker-selenium/issues/367> it would be great if the Hindi language is supported as well. 

Just add `fonts-indic` to the list of fonts to be installed.

**Comment by diemol** [comment]
Hi @skilip, do you know how much the images will grow if those fonts are added? If it is not too much, feel free to send us a PR adding it.

**Comment by ddavison** [comment]
i wonder if Hindi is included in the bionic release?

the only indian fonts i can find as external packages are samyak fonts. https://packages.ubuntu.com/bionic/fonts/fonts-samyak

since we extend our images from ubuntu:bionic*.

**Comment by ddavison** [comment]
@skilip did you get a chance to see my comment and see if Hindi is included in ubuntu:bionic?  our containers extend from this release

**Comment by diemol** [comment]
Closing this as we did not get more information from the OP.
