### ISSUE TITLE
Expose env var for changing hub port, please?

### ISSUE THREAD

**Issue by LudwigHoff** [SeleniumHQ/docker-selenium#90]
Hub/generate_config:

Could it be:
   \"port\": ${HUB_PORT_4444_TCP_PORT:-4444}, 
please?

The nodes can take a different hub port, please could the hub as well?

(I need this because of various local service discovery limitations at our end).

I am extending locally (work private repos) which is why I am not pull requesting this.  Many apologies.

**Comment by rubytester** [comment]
with docker you can -p 4445:4444. Basically internally hub starts on port 4444 but on the outside it's visible on port 4445. Is that your issue?

**Comment by LudwigHoff** [comment]
Absolutely, this is completely a request based on our set up.  (It's a one of the standard "don't want to start from here" situations.  Some lovely work which now locks us in: we gen docker-compose.yml on the fly - but this also restricts us somewhat.

Thanks for this very nice repo by the way.

The more I think about this, my request is utterly bound to what I do here.

Sorry to have bothered.

BR
