### ISSUE TITLE
set custom firefox profile to different versions, show worse time

### ISSUE THREAD

**Issue by Vereschak** [SeleniumHQ/docker-selenium#900]
Hi!
I always used selenium/standalone-firefox:3.7.1-cadmium and I always used custom profiles
But when I decided to use newer versions of selenium/standalone -I got poor results
0n 3.7.1 My time was 2-5 seconds, on newer versions(example 3.9.1) I got 25-35 seconds for start up browser.
It's only for custom profiles
How can I fixed it ?
Thank you!

**Comment by diemol** [comment]
There is little or nothing we can do without more information. Additionally I am not sure if this is something on the scope of docker-selenium, we just wrap the Selenium JAR and the browser into docker images.

I would advice you to analise the performance locally in you machine without docker, then using the Selenium JAR. If you only find a slowness when using the docker images, feel free to reopen the issue and fill the complete template.
