### ISSUE TITLE
Documentation about Standalone Node

### ISSUE THREAD

**Issue by simhem** [SeleniumHQ/docker-selenium#905]
I was going through the selenium documentation, and i didn't find any trace of node-standalone.

I tried using the selenium-standalone-node image, but i couldn't really find any information about how it works, how to connect to it remotely, which REST api does it expose ....

Could someone explain to me or give me some documentation or example ?

**Comment by ddavison** [comment]
we have a Standalone section [in the README](https://github.com/SeleniumHQ/docker-selenium#standalone-chrome-and-firefox).

Also, it looks like you're conflating Standalone and Node.  They are mutually exclusive. If it's Standalone, it's not a Node. If it's a Node, it's not Standalone.
