### ISSUE TITLE
Add support for configuring xvfb dpi and scale

### ISSUE THREAD

**Issue by CaffeinatedCM** [SeleniumHQ/docker-selenium#908]
## 🚀 Feature Proposal

Add SCREEN_DPI and SCREEN_SCALE settings to provide greater control of the xvfb display

## Motivation

We recently discovered a bug in our product and would like to be able to automate testing of different screen scales and dpi settings with the docker containers. 

## Example

Testing and validating how websites behave when used on a 4k display where the screen is being scaled

**Comment by ddavison** [comment]
could you elaborate on what these settings in particular would change as far as the Xvfb run is concerned?

https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/start-xvfb.sh

perhaps we could just open up specifying options?  something like `XVFB_OPTIONS=-screen 1024x768x32 -pixdepths 32` then just pass that into the command

**Comment by CaffeinatedCM** [comment]
It looks like opening up specifying those options will help for setting the DPI, since [xserver accepts that option](https://www.x.org/releases/X11R7.6/doc/man/man1/Xserver.1.xhtml). 

I did some more research, and setting screen scale appears to have to be done using [xrandr](https://www.x.org/releases/X11R7.6/doc/man/man1/xrandr.1.xhtml) after the server is started, so perhaps we could add a call to `xrandr` if an environment variable XRANDR_OPTIONS is supplied?

**Comment by diemol** [comment]
@CaffeinatedCM it is hard to say. Would you like to give it a try and send us a PR which includes documentation?

**Comment by CaffeinatedCM** [comment]
@diemol sure, I can do that 😄

**Comment by diemol** [comment]
Closing this one and will follow up in the PR, thanks @CaffeinatedCM
