### ISSUE TITLE
Grid node host is not registered with correct IP

### ISSUE THREAD

**Issue by ygveem** [SeleniumHQ/docker-selenium#909]
## 🐛 Bug Report

I am starting my Chrome Node using :
sudo docker run -d  -e HUB_HOST=xx.xxx.xxx.xx -e HUB_PORT=4444  selenium/node-chrome:3.141.59-antimony

The docker is started successfully and finding the Hub correctly. But it is registered with :
host: 172.17.0.2
port: 5555

The host is wrong therefore i am getting
" DefaultRemoteProxy unknown version,Failed to connect to /172.17.0.2:5555" 

When i run with specifying port and host :
sudo docker run -d -e  NODE_PORT=5558 -e NODE_HOST="xx.xxx.xxx.xx" -e HUB_HOST=xx.xxx.xxx.xx -e HUB_PORT=4444  selenium/node-chrome:3.141.59-antimony
getting the error at the start :
Port 5558 is busy, please choose a free port and specify it using -port option

Was trying several last version - all is the same result

**Comment by diemol** [comment]
Please use the `REMOTE_HOST` option mentioned in the README, [here](https://github.com/SeleniumHQ/docker-selenium#selenium-hub-and-node-configuration-options).

**Comment by ygveem** [comment]
Same result with REMOTE_HOST. The host is still wrong and unable to get back to a node

**Comment by diemol** [comment]
Can you share the command you used please?
