### ISSUE TITLE
Unexpected behavior of moveToElement() in Node-Firefox-Container

### ISSUE THREAD

**Issue by software2000** [SeleniumHQ/docker-selenium#910]
## 🐛 Bug Report

The Firefox browser behaves differently in the container than locally. When opening a drop-down menu by hovering element A and selecting element B within the drop-down, the mouse pointer does not remain on element B, so the drop-down menu is closed. Locally, the mouse pointer remains on element B and the drop-down menu remains open.

## To Reproduce

Set up a small environment consisting of a 'selenium/node-firefox' container and a 'selenium/hub' container, the used versions don't matter. I tried several versions, e.g. with the label 'latest'.

## Expected behavior

The mouse pointer should remain on element B, similiar to the execution on a local computer.

## Test script reproducing this issue (when applicable)

Small example with TestNG 6.8 and Selenium-Java 3.141.59

`

    import org.openqa.selenium.WebElement;
    import org.openqa.selenium.interactions.Actions;
    import org.openqa.selenium.remote.DesiredCapabilities;
    import org.openqa.selenium.remote.RemoteWebDriver;
    import org.testng.annotations.Test;

    import java.net.MalformedURLException;
    import java.net.URL;

    public class SeleniumTest {

        @Test
        public void exampleTest() throws InterruptedException, MalformedURLException {
            RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),
                    DesiredCapabilities.firefox());
            Actions actions = new Actions(driver);

            driver.get("https://www.w3schools.com/howto/tryhow_css_mega_menu_responsive.htm");
            WebElement dropdown = driver.findElementByClassName("dropbtn");
            actions.moveToElement(dropdown).perform();
            Thread.sleep(3000);
            WebElement dropdownElement = driver.findElementByXPath("//div[@class='dropdown']//div[@class='row']//a");
            actions.moveToElement(dropdownElement).perform();
            Thread.sleep(3000);
            dropdownElement.click();

            driver.close();
        }

    }

`

I have attached a larger version of the script which shows that only the Firefox browser in the 'selenium/node-firefox' container is affected.

[FullExample.zip](https://github.com/SeleniumHQ/docker-selenium/files/3224106/FullExample.zip)

## Environment

OS: Ubuntu 18.04.2 LTS
Docker-Selenium image version: 3.141.59
Also provide the docker image id 
--> selenium/node-firefox
Docker version: 18.09.2
Docker-Compose version (if applicable): x
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
sudo docker run --name selenium-node-firefox-latest --net grid -e HUB_HOST=selenium-hub --shm-size 2g -d -v /dev/shm:/dev/shm selenium/node-firefox:latest

**Comment by diemol** [comment]
@software2000 what operating system are you using when you say "locally"?

**Comment by software2000** [comment]
@diemol I'm using Ubuntu 18.04.2 LTS

**Comment by software2000** [comment]
I have created some GIFs that show the different behavior.

Container execution:
![container](https://user-images.githubusercontent.com/22871230/58786769-98902080-85e8-11e9-973e-313ce5a1e166.gif)


Local execution:
![local](https://user-images.githubusercontent.com/22871230/58786685-6bdc0900-85e8-11e9-8c41-20f4590f1e0e.gif)

**Comment by diemol** [comment]
This is interesting, my only explanation would be that the container uses fluxbox as a window manager and you local machine something different. But more than that, I have no other clues on why the behaviour is different.

I am not sure how to proceed 😞

**Comment by software2000** [comment]
@diemol Were you able to reproduce the bug?

Interestingly, moving the mouse pointer to the title bar via xdotools solves the problem. But only for the node-firefox-debug container, tests insinde the node-firefox container still fail.

Furthermore, neither node-chrome nor node-chrome-debug are affected.

**Comment by xendk** [comment]
I got a slightly different problem, but the talk of moving the mouse pointer suggests to me that there might be a relatively simple solution to both our problems.

My problem is that I'm using the image to take some screenshots of pages. However I was getting screenshots with unexpected page elements being in a hover state. Using the debug image and VNC server in view mode, I noticed that the pointer in the image X server was at the center of the screen, as is the default starting position for the pointer in X.

Using the VNC server to move the pointer before running my screenshotting produced the result I was expecting.

So it seems to me that using xdotool, or something similar, in the `start-selenium-standalone.sh` script to move the pointer to, say, 0,0 before starting selenium in  might solve both our problems.

What do you say @diemol?

**Comment by software2000** [comment]
@xendk Thank you very much for your contribution. 

I also tried to solve this problem with xdotools. However, this approach only worked for debug containers. I was not able to use xdotools with standard containers. 

Were you able to use xdotools with non-debug containers (e.g. selenium/node-chrome)?

**Comment by xendk** [comment]
@software2000 
I've spent most of the evening trying to convince `selenium/standalone-chrome:3.141.59-vanadium` to move the mouse pointer, without success.

I've managed to build an image based on `selenium/standalone-chrome-debug:3.141.59-vanadium` with an extra script that waits for X to be available and move the mouse pointer to 0,0 using xdotool. Works fine.

Seems that Xvf wont listen to xdotool without fluxbox as a middleman. I don't know why, random hits in Google suggest that it should just work, while some report trouble.

For my usecase I can live with an image derived from `selenium/standalone-chrome-debug:3.141.59-vanadium`, but it would be nice not having to depend on a custom image.

**Comment by xendk** [comment]
For what it's worth, I tried using selenium-standalone on CircleCI. It too uses Xvfb without a window manager, and there xdotool works.

Apparently they use the command `Xvfb :99 -screen 0 1280x1024x24`...

**Comment by bugzooka** [comment]
I have a similar experience now:
Use Action moveToElement to hover an element is not possible with selenium/node-firefox:3.141.59. Using a "fresh" selenium/standalone-firefox-debug:3.141.59 also fails until i connect via vnc and move the mouse once to the right. Then repeating the test were always sucessful. 

I tried several workarounds (like changing screen and browser sizes) and end up in the only running one by using the JavascriptExecutor:
   
```
var element = document.getElementById('$ID');

var event = new MouseEvent('mouseover', {
  'view': window,
  'bubbles': true,
  'cancelable': true
});

element.dispatchEvent(event);
```

**Comment by diemol** [comment]
Just wanted to circle back on this, are you having the same behavior with the Selenium 4 Alpha docker images?

**Comment by bugzooka** [comment]
Hi @diemol,

I couldn't reproduce it with the newest selenium 3 docker images:

selenium/hub:3.141.59
selenium/node-firefox:3.141.59
selenium/standalone-firefox-debug:latest

Firefox v:83.0

**Comment by diemol** [comment]
I will close as it seems this issue is gone with Selenium 4 Grid and bindings.
