### ISSUE TITLE
Nodes should wait the hub for their timeout configuration

### ISSUE THREAD

**Issue by theredfish** [SeleniumHQ/docker-selenium#913]
## 🚀 Feature Proposal

Nodes should wait the Selenium Hub to get their timeout configuration (and not the default one). I can submit a PR if you are interested by this feature proposal.

## Motivation

At Oui.sncf we use a custom entry_point.sh script to wait the hub before running our nodes. By doing that we ensure that our nodes can receive their timeout configuration from the hub, especially when they have been launched before the hub.

## Example

1. The firefox node is launched
2. The firefox node wait the Selenium hub (by checking /wd/hub/status) during a certain amount of time
3. When the hub is ready (it returns a response 200), the node can connect itself to the hub and receive its timeout configuration.

**Comment by diemol** [comment]
@theredfish 

Well, that is how Grid works already. If you start a node before a hub, it will try to connect until it is able to do it (this is until the hub is up). 
The timeout configuration works in a way that if the node has no specific configuration, it gets the default one from the hub. If the node has a configuration, it overwrites the one from the hub.

Am I missing something?

**Comment by diemol** [comment]
Closing as we didn't get more info.
