### ISSUE TITLE
 [PHPUnit\Framework\Exception] Undefined index: ELEMENT 

### ISSUE THREAD

**Issue by chucky2305** [SeleniumHQ/docker-selenium#916]
## 🐛 Bug Report

With the latest release (3.141.59-palladium) we faced the issue, that all our acceptance tests failed. 

The message is: ` [PHPUnit\Framework\Exception] Undefined index: ELEMENT `
Unluckily we did not specify an exact version for selenium/standalone-chrome. To get our tests back to work, we went back to an older version. Hope this helps. If you need more information to find the actual bug, just hit me up.

**Comment by diemol** [comment]
@chucky2305 
From ChromeDriver & Chrome 75 and up, it will default to W3C mode, see release notes:
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

It means that all commands must be W3C complaint, if you still need time to update your test scripts, you can pass `w3c: false` inside the `goog:chromeOptions` block. Take into account that the flag will probably be removed in future ChromeDriver releases.
