### ISSUE TITLE
node-chrome 3.141.59 changed chrome version

### ISSUE THREAD

**Issue by dvarrazzo** [SeleniumHQ/docker-selenium#917]
Hey,

https://hub.docker.com/r/selenium/node-chrome/tags

you changed an existing tag!

3.141.59 used to install chrome 72. Now it installs chrome 75. This breaks selenium python 3.13, resulting in the error:

        Cannot call non W3C standard command while in W3C mode

https://stackoverflow.com/questions/56452798/how-to-turn-off-w3c-in-chromedriver-to-address-the-error-unknown-command-cannot

Why did you overwrite it?

**Comment by deviantintegral** [comment]
I ran into a different regression, where finding elements by xpath fail. It looks like tags are created with `-element` prefixes, so in my case pinning to `3.141.59-oxygen` fixed our tests until we can figure out what broke with Chrome 75.

**Comment by ddavison** [comment]
thanks @deviantintegral ,

yes, we tag our images with an element suffix

see [our tagging convention](https://github.com/SeleniumHQ/docker-selenium/wiki/Tagging-Convention).
