### ISSUE TITLE
Selenium in container cannot connect to host in /etc/hosts

### ISSUE THREAD

**Issue by pandeiro** [SeleniumHQ/docker-selenium#92]
I want a selenium container to be able to connect to an application running on the docker host. I am using a script like this to include that in `/etc/hosts`:

```
#!/bin/bash

SED="$(which sed)"
NETSTAT="$(which netstat)"
GREP="$(which grep)"
AWK="$(which awk)"
CAT="$(which cat)"


$SED '/dockerhost$/d' /etc/hosts > /etc/hosts.tmp
DOCKERHOST="$($NETSTAT -nr | $GREP '^0\.0\.0\.0' | $AWK '{print $2}')"

echo "$DOCKERHOST dockerhost" >> /etc/hosts.tmp

$CAT /etc/hosts.tmp > /etc/hosts

rm -rf /etc/hosts.tmp
```

This script is `COPY`'d and run in building an image derived from `selenium/standalone-chrome-debug:latest`.

**However when I try to connect to a URL such as "http://dockerhost:8000/foo.html", the selenium container's Chrome cannot access the URL.**

Is this expected behavior? Why doesn't Chrome seem to resolve this host that is located `/etc/hosts`? Is there something I can do to be able to connect to such a host?

**Comment by pandeiro** [comment]
It seems from inspecting the resulting image's container that `/etc/hosts` does **not** include the entry explicitly added by my script, above.

Is either the `selenium/standalone-chrome-debug` image or docker itself possibly overwriting this `/etc/hosts` file?

**Comment by pandeiro** [comment]
Closing as this is a docker issue: see [#2267](https://github.com/docker/docker/issues/2267)

**Comment by chunji08** [comment]
Hi there, I had followed the same way and was able to add the extra rows in the /etc/hosts file, the question I have is, during the selenium execution time,  does it really reads the setting of the "/etc/hosts" file, within  this container ?
