### ISSUE TITLE
Driver method get_attribute() fails after upgrade to 3.141.59-palladium

### ISSUE THREAD

**Issue by DamianDex** [SeleniumHQ/docker-selenium#921]
## 🐛 Bug Report

Driver method get_attribute() fails after upgrade to 3.141.59-palladium

## To Reproduce

1. Run selenium standalone locally:
docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:3.141.59
2. Execute test on that node, test should call driver.get_attribute() method
3. Test failed, because get_attribute() returns None (I use Python)

I found that js script which is executed during get_attribute() is failing, because script variable is undefined and hasn't attribute toLowerCase/toUpperCase

## Expected behavior

Attribute should be returned (instead of None)

## Environment

OS: MacOs High Sierra
Docker-Selenium image version: 09fb5857c74e
Docker version: Version 2.0.0.2 (30215)
Start: docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome:3.141.59

**Comment by diemol** [comment]
@DamianDex 

From ChromeDriver & Chrome 75 and up, it will default to W3C mode, see release notes:
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

It means that all commands must be W3C complaint, if you still need time to update your test scripts, you can pass `w3c: false` inside the `goog:chromeOptions` block. Take into account that the flag will probably be removed in future ChromeDriver releases.

**Comment by DamianDex** [comment]
@diemol Let's assume that I don't want use `w3c: false` flag, because is going to be removed.
What should I do with get_attribute() methods? I cannot use that anymore?

**Comment by diemol** [comment]
I would either create an issue in the repo of the bindings you are using with a way to reproduce the issue or join the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the question can be asked.
