### ISSUE TITLE
PHP Behat Mink Selenium not working for 3.141.59-palladium

### ISSUE THREAD

**Issue by phil-davis** [SeleniumHQ/docker-selenium#922]
## 💥 Regression Report

`3.141.59-palladium` was  released as `latest` docker image yesterday. When that happened, our webUI tests started failing e.g. https://drone.owncloud.com/owncloud/core/18073/681
```
  Scenario: simple user login                                                                 # /drone/src/tests/acceptance/features/webUILogin/login.feature:12
    Given these users have been created with default attributes but not initialized:          # FeatureContext::theseUsersHaveBeenCreated()
      | username |
      | user1    |
    When user "user1" logs in using the webUI                                                 # WebUILoginContext::theUserLogsInUsingTheWebUI()
      Exception: Page\LoginPage::waitTillPageIsLoaded timeout waiting for page to load in /drone/src/tests/acceptance/features/lib/LoginPage.php:103
      Stack trace:
      #0 /tmp/ProxyManagerGeneratedProxy__PM__PageLoginPageGenerated6312256563dff9947346b9792a817253.php(44): Page\LoginPage->waitTillPageIsLoaded(Object(Behat\Mink\Session), 10000)
      #1 /drone/src/tests/acceptance/features/bootstrap/WebUIGeneralContext.php(226): ProxyManagerGeneratedProxy\__PM__\Page\LoginPage\Generated6312256563dff9947346b9792a817253->waitTillPageIsLoaded(Object(Behat\Mink\Session))
      #2 /drone/src/tests/acceptance/features/bootstrap/WebUILoginContext.php(152): WebUIGeneralContext->loginAs('user1', '1234')
```
The Apache server sees the request for the login page, so a browser is starting, being sent a URL and does try to go there. But somehow the connection through selenium to chromedriver and the browser seems to just not "see" the web page (elements) that come back.

Reverting back to `selenium/standalone-chrome-debug:3.141.59-oxygen` PR https://github.com/owncloud/core/pull/35442 makes UI testing great again.

## Last working version

Worked up to version: `3.141.59-oxygen`

Stopped working in version: `3.141.59-palladium`

## To Reproduce

- run the ownCloud webUI tests with `3.141.59-palladium`

## Expected behavior

The tests should pass. In particular, the login page should be found and filled in.

## Test script reproducing this issue (when applicable)

The https://github.com/owncloud/core repo webUI CI reproduces the issue - it is a bit of a large example ;)

## Environment

OS: Ubuntu 18.04
Docker-Selenium image version: `3.141.59-palladium`

**Comment by phil-davis** [comment]
If really necessary I could try to work up some sort of small example. But I am hoping that there is some "obvious" problem with the release, or some BC break and a small change that I need to make to get CI working with the new `3.141.59-palladium`

**Comment by diemol** [comment]
@phil-davis 

From what you mention, it just sounds that PHP Behat Mink is not sending W3C commands, have you checked in their repo if they are already doing that?

**Comment by phil-davis** [comment]
See also https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-499405228
There seems to be no W3C webdriver support yet in the Behat-Mink-Selenium stack.
Now to see how I can tell it `w3c:false`

**Comment by diemol** [comment]
Oh, that is a shame 😞 
You can add the flag in the `goog:chromeOptions` block.

**Comment by diemol** [comment]
So, I'll close this issue since it is not related to docker-selenium, hopefully PHP Behat Mink adds support for W3C soon since ChromeDriver will probably remove the flag in future releases.
