### ISSUE TITLE
Chrome browser not working inside in selenium/node-chrome-debug container

### ISSUE THREAD

**Issue by nibus1034** [SeleniumHQ/docker-selenium#926]
## 🐛 Bug Report

I'm running the latest Selenium/hub & selenium/node-chrome-debug images & i'm able to connect the nodes with the hub & when i'm trying to execute some scripts in the node using remotewebdriver, the chrome browsers are getting launched but not getting navigated to the respective page. Upon checking using the VNC viewer i could see that the chrome browser is not able to connect to internet. 

## Expected behavior

Upon executing scripts,chrome browser should launch & navigate to the respective page 

## Environment
<b>docker version </b>:
 
Client: Docker Engine - Community
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:33:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:41:08 2019
  OS/Arch:          linux/amd64
  Experimental:     false
----
<b>docker info</b>

Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
Docker-Selenium image version: <!-- 3, 3.141, 3.141.59-palladium etc
Also provide the docker image id 

please find the below image of chrome browser inside the selenium/node-chrome-debug container.

![image](https://user-images.githubusercontent.com/41526190/59112783-573d9f00-8961-11e9-998f-012c3ed39224.png)

Please guide me why this error is happening.

**Comment by ddavison** [comment]
could you also share your command(s) to run these nodes?

this sort of problem could be a number of things including firewall issues even to iptables

**Comment by nibus1034** [comment]
Sure ddavison.
Please find the below commands i used to run these nodes 

docker images 
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
selenium/node-firefox-debug        latest              15887b1db339        2 days ago          799MB
selenium/node-chrome-debug         latest              f74c203c4e92        2 days ago          891MB
selenium/hub                       latest              6078723749ff        12 days ago         285MB


docker run -d -p 4444:4444 -P --name selenium-hubP selenium/hub
docker run -d --link selenium-hubP:hub -P --name chrome13 selenium/node-chrome-debug
docker run -d --link selenium-hubP:hub -P --name firefox13 selenium/node-firefox-debug


is there any commands to check the iptables or firewall config.so that we can get to know the status of it.

**Comment by nibus1034** [comment]
Hi team,
any updates regarding the above request ?

**Comment by diemol** [comment]
Are you behind a proxy or firewall?

**Comment by nibus1034** [comment]
Yes I'm behind a corporate proxy.

**Comment by diemol** [comment]
Ah ok, that is the reason why. You need to configure the proxy env vars for the docker containers as well.
https://docs.docker.com/network/proxy/

**Comment by nibus1034** [comment]
Hi Team,

I have tried the following steps 
1.  Inside .docker/config.json, i have added the proxy details 
2. tried running the container in the following format, after setting environment variable  
     >> docker container run -e http_proxy 

<b>PS</b>: we have installed docker in a REDHAT machine using below commands 

  >> install docker with zip file
  >> tar xzvf /opt/dockerlib/docker-18.09.6.tgz
  >> cp docker/* /usr/bin/
  >> dockerd &

Thanks,
Subin

**Comment by diemol** [comment]
The most simple approach is to reach to the networking area of your company, so they help you figure out the proper values that need to be used for the proxy configuration.
