### ISSUE TITLE
While launching the hub its throwing error

### ISSUE THREAD

**Issue by siva90144** [SeleniumHQ/docker-selenium#929]
## 🐛 Bug Report
OS: Windows 10 enterprise 
Creating Linux containers 

I am able to register the create the hub successfully.

20:53:22.781 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1        | 20:53:22.782 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1        | 20:53:22.824 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
chrome_1        | 20:53:23.149 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://selenium-hub:4444/grid/register
chrome_1        | 20:53:23.215 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
selenium-hub    | 20:53:23.215 INFO [DefaultGridRegistry.add] - Registered a node http://172.18.0.3:5555

**After that I am trying lo launch hub in browser and its throwing error as below**

org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: |Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'|System info: host: 'b4c7647b75ca', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_212'|Driver info: driver.version: unknown
selenium-hub    |       at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:290)
selenium-hub    |       at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:220)
selenium-hub    |       at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
selenium-hub    |       at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:145)
selenium-hub    |       at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:69)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:55)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:50)
selenium-hub    |       at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:83)
selenium-hub    |       at org.openqa.grid.web.servlet.RegistrationServlet.doGet(RegistrationServlet.java:64)
selenium-hub    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
selenium-hub    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

here is the file:

version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

**Comment by diemol** [comment]
Hi @siva90144,
 
We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template by creating a new issue. Please also include the test script you use to start the browser.
