### ISSUE TITLE
While launching the hub its throwing error

### ISSUE THREAD

**Issue by siva90144** [SeleniumHQ/docker-selenium#930]
## 🐛 Bug Report

While launching hub in browser its throwing error. 

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers):
1. create docker selenium hub  and chrome node with below file.
## Expected behavior

It should open in browser  and display nodes

## Test script reproducing this issue (when applicable)

version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

## Environment

OS: Windows 10 Enterprise
Docker-Selenium image version:  3.141.59
Also provide the docker image id :1536a986b2d6 
Name: selenium/node-chrome:3.141.59 
dockerfiles_chrome_1
-->
Docker version: 
Docker-Compose version (if applicable): Docker version 18.09.2, build 6247962
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

command: docker-compose -f docker-compose.yaml up

version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by siva90144** [comment]
After creating hub successfully I was trying to launch the client status in browser with below url.

**http://172.18.0.2:4444/wd/hub** or **http://localhost:4444/wd/hub**

Then its throwing error ad below.

error log:

 org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: |Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'|System info: host: 'b4c7647b75ca', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_212'|Driver info: driver.version: unknown
selenium-hub    |       at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:290)
selenium-hub    |       at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:220)
selenium-hub    |       at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
selenium-hub    |       at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:145)
selenium-hub    |       at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:69)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:55)
selenium-hub    |       at org.openqa.selenium.json.Json.toType(Json.java:50)
selenium-hub    |       at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:83)
selenium-hub    |       at org.openqa.grid.web.servlet.RegistrationServlet.doGet(RegistrationServlet.java:64)
selenium-hub    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
selenium-hub    |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
selenium-hub    |       at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
selenium-hub    |       at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
selenium-hub    |       at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
selenium-hub    |       at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
selenium-hub    |       at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
selenium-hub    |       at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
selenium-hub    |       at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium-hub    |       at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
selenium-hub    |       at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
selenium-hub    |       at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
selenium-hub    |       at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
selenium-hub    |       at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
selenium-hub    |       at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
selenium-hub    |       at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
selenium-hub    |       at java.lang.Thread.run(Thread.java:748)


**FYI... Hub is created successfully** 

20:53:19.490 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium-hub    | 20:53:19.578 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
selenium-hub    | 2019-06-13 20:53:19.972:INFO::main: Logging initialized @671ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub    | 20:53:20.110 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub    | 20:53:20.111 INFO [Hub.start] - Nodes should register to http://172.18.0.2:4444/grid/register/
selenium-hub    | 20:53:20.111 INFO [Hub.start] - Clients should connect to http://172.18.0.2:4444/wd/hub
selenium-hub    | 20:53:23.215 INFO [DefaultGridRegistry.add] - Registered a node http://172.18.0.3:5555
selenium-hub    | 2019-06-13 20:53:43.421:WARN:osjs.HttpChannel:qtp289639718-13: /grid/register/

**Comment by diemol** [comment]
How can I reproduce this? Can you please provide a test script that can I can run to have the same error?

**Comment by siva90144** [comment]
command: docker-compose -f docker-compose.yaml up
save below code in  docker-compose.yaml file and execute above command(Its already mentioned in issue)
 
version: "3"
services:
selenium-hub:
image: selenium/hub:3.141.59
container_name: selenium-hub
ports:
- "4444:4444"
chrome:
image: selenium/node-chrome:3.141.59
volumes:
- /dev/shm:/dev/shm
depends_on:
- selenium-hub
environment:
- HUB_HOST=selenium-hub
- HUB_PORT=4444

**Comment by diemol** [comment]
That is how the containers are started, which you already mentioned that it works...
But what is the script you use when:
>After creating hub successfully I was trying to launch the client status in browser with below url.
