### ISSUE TITLE
Azure AKS/ACI containers have 2 IP addresses

### ISSUE THREAD

**Issue by matthew-horrocks** [SeleniumHQ/docker-selenium#946]
Based on the outcome of this AZure Kubernetes Service / Azure Container Instance bug https://github.com/Azure/AKS/issues/901, the node containers will come up with 2 ip addresses; a 169.x.x.x and a 10.x.x.x.

This causes the nodes to register with the grid using the 169.x.x.x address, when they should use the 10.x.x.x address.

Any idea why Selenium node would use the 169.x.x.x address to register with the Grid? (Perhaps the 10.x.x.x address hasn't come up by the time the node registers with the grid?)

Is there a way to specify which address the node should use?

**Comment by diemol** [comment]
Check https://github.com/SeleniumHQ/docker-selenium#selenium-hub-and-node-configuration-options, `REMOTE_HOST`

**Comment by matthew-horrocks** [comment]
Thanks, I'll give that a try.

I'm not sure I understand how supplying a `REMOTE_HOST` value will stop the Selenium node registering against the Grid server with its 169.x.x.x address, rather than its 10.x.x.x address, though, so any info would be great.

**Comment by matthew-horrocks** [comment]
Ah, `REMOTE_HOST` the node ip address, not the Hub/Grid server address.

**Comment by matthew-horrocks** [comment]
I've been looking at this this afternoon. If I'm deploying the `selenium/node-chrome` container via a yaml file to AKS (or any other Kubernetes platform) I don't know the container's hostname or ip address before it's created, so how can I set the `REMOTE_HOST` value in the yaml file?

Any suggestions @diemol ?

**Comment by matthew-horrocks** [comment]
For anyone else looking for how to do this... you can use this in your `yaml` file

```
command: ["/bin/sh"]
        args: ["-c", "export REMOTE_HOST=http://$(/bin/hostname -i):5555 && /opt/bin/entry_point.sh"]
```
