### ISSUE TITLE
Not possible to switch tabs with the latest images (standalone-chrome-debug)

### ISSUE THREAD

**Issue by shizzleliz** [SeleniumHQ/docker-selenium#949]
## 🐛 Bug Report
Summary:
Since a month the tests which run in a Jenkinspipeline with the latest tag will fail with an error: org.openqa.selenium.InvalidArgumentException: invalid argument: 'handle' must be a string

Details:
Our test run on a Jenkinsserver from a Jenkinsscript using: 
docker run -d -d -p 5999:5900 -p 4444:4444 -v /dev/shm:/dev/shm -e JAVA_OPTS=-Xmx768m selenium/standalone-chrome-debug

On this server a standalone-chrome-debug image is present with a latest tag (as i found out, encountering this problem) and this image only will be renewed if de server is rebooted. So this happend, and now the problem occurs.

The test itself goes to a page, logs in, clicks a button, which opens a tab and the test should proceed on the open tab. To do so I created a method switchTab.

`public void switchTab(Integer tabnr) {
    String currentHandle = driver.getWindowHandle();
    Set<String> handles = driver.getWindowHandles();

    for (String handle : handles){
        if (!handle.equalsIgnoreCase(currentHandle)){
            driver.switchTo().window(handle);
        }
    }
}`

And with the latest images the error "org.openqa.selenium.InvalidArgumentException: invalid argument: 'handle' must be a string" is thrown. As far as I know iam giving a String. 

When I go back to image standalone-chrome-debug:3.141.59-oxygen then all is well and the tests run well.

I hope it's a finding for the image, otherwise I am sorry for my ignorance

## Environment

OS: Windows 10? OSX
Chromedriver in container: ChromeDriver 75.0.3770.140
Docker-Selenium image version: 3.141.59:Latest
Container id =97631ac1271a7610a524b67f7c87c9c644ed321877e1abbb491a666a082dc780 (?)
-->
Docker version: 
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

**Comment by diemol** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/docker-selenium/issues/new/choose) and we'll make sure to look at it.

When the new issue is created, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
