### ISSUE TITLE
Please, change README with debug details

### ISSUE THREAD

**Issue by niberius** [SeleniumHQ/docker-selenium#953]
## 💬 Questions and Help

Hello. 

I'd suggest to add the following info into README.md, Troubleshooting section, that we can specify the following env option to get DEBUG logs:
`SE_OPTS="-debug"`

I spent a lot of time to find the details, how I can get DEBUG logging info for selenium hub / nodes (and found it accidentally, by the way). I tried JAVA_OPTS, and GRID_DEBUG - nothing did help.

I think, it would be useful for users. 

Thanks.

**Comment by diemol** [comment]
@niberius feel free to send us a PR and add that to the README, with that contribute to OSS and give back to the community!
