### ISSUE TITLE
Google Auth declined with Chrome Debug Standalone

### ISSUE THREAD

**Issue by AlexanderWM** [SeleniumHQ/docker-selenium#956]
## 🐛 Bug Report

When I'm trying to login to test Google Account, now I'm get an error like this:

![image](https://user-images.githubusercontent.com/12584519/62422691-3b374f00-b6bf-11e9-9f75-68df6ea978b3.png)

Some days ago, I run the same scenario without any problems. 

When I run chrome manually (connecting with VNC and run chrome) - all is ok. No any errors while login. But in automatic mode, when Chrome started with selenium - google detect it, and disallow me to run test. 

The only difference is selenium chrome extension. How I can remove it?

**Comment by diemol** [comment]
Seems that Google is blocking automated WebDriver scripts on their platform, which doing so is probably against their terms of usage. 
This is not really a Selenium issue per se, you could submit an issue to the Chrome/ChromeDriver project (Chromium team), either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
