### ISSUE TITLE
selenium/standalone-firefox:2.47.1 has memory leak

### ISSUE THREAD

**Issue by bitliner** [SeleniumHQ/docker-selenium#97]
I am running e2e test using protractor that uses the `standalone-firefox:2.47.1` image.

At every test the RAM increases, and it is never made free.

I have 20 test, and at the end the total RAM made busy by the whole set of apps involved in the e2e test is about 8GB.

From monitoring the RAM, I can see it is the firefox image that wastes a lot of RAM (some gigabytes).

**Comment by bitliner** [comment]
https://github.com/SeleniumHQ/selenium/issues/384

**Comment by bitliner** [comment]
I experience the same with `standalone-chrome:2.47.1`.

Is there any way to fix it?

Going to investigate soon

**Comment by bitliner** [comment]
The bug was in my code. 

I was running 2 concurrent browsers for testing, and I was supposing that browser2.quit() would have been directly called by the testing framework in `afterEach` method, while it was not.

**Comment by daxia4444** [comment]
I only use one browsers instance, but  Firefox appears  memory leak sometimes. Do you have any idea?
