### ISSUE TITLE
Chrome Node not opening Mobile Browser emulation mode

### ISSUE THREAD

**Issue by qburst-hari** [SeleniumHQ/docker-selenium#977]
## 🐛 Bug Report

Since my automation needs to be run on mobile emulation mode, I am passing the capabilities for mobile emulation. But the Chrome browser is not opening in mobile emulation view. I have checked my scripts in local selenium grid to understand its not my script issue. But its working fine in local grid. So I feel its something to do with the chrome container as its not accepting the capabilities.

## To Reproduce

Below is the Capability I am passing : 
`
  capabilities: [
    {
      browserName: "chrome",
      chromeOptions: {
        args: [
          "--reduce-security-for-testing",
          "--use-mobile-user-agent",
          "--user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3",
          "--window-size=390,670"
        ]
      },

      mobileEmulation: {
        deviceName: "Apple iPhone 6"
      }
    }
  ],`

## Expected behavior

The chrome browser should open in mobile emulation mode.

## Environment

OS:  Ubuntu
-->
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
Please use `goog:chromeOptions` instead.

**Comment by qburst-hari** [comment]
Even after using goog:chromeOptions, its not opening in mobile emulation view. Please reopen this ticket.

**Comment by qburst-hari** [comment]
@diemol I changed to goog:chromeOptions but no luck
