### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by hawzie197** [SeleniumHQ/docker-selenium#982]
## 🐛 Bug Report

Link is broken in Docker Compose WIKI.

Link to WIKI: [Link to WIKI](https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose)

Under Step 4: Running Tests, the link to the _official documentation_ is broken and navigates to a 404

Mike

**Comment by diemol** [comment]
Fixed, thank you for reporting it.
