### ISSUE TITLE
node-firefox does not set screen height and width via docker-compose

### ISSUE THREAD

**Issue by RvL001** [SeleniumHQ/docker-selenium#983]
## 🐛 Bug Report

When starting a selenium-hub with node-firefox using docker-compose, the parameters SCREEN_HEIGHT and SCREEN_WIDTH are not set correctly.

However, when using node-firefox-debug or node-chrome, the screen size is set correctly

## To Reproduce

Use the following docker-compose.yml and build it with docker-compose
```groovy
version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  node-firefox:
    depends_on:
      - selenium-hub
    image: selenium/node-firefox:latest
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - HUB_HOST=selenium-hub
    volumes:
      - /dev/shm:/dev/shm
```

Execute a simple test, such as this test in Java:
```java
public void test01() {
       //Change the following strings to the valid URL
        String grid = "http://localhost:4444/wd/hub";
        String console = "http://localhost:4444/grid/console";
        
        FirefoxOptions options = new FirefoxOptions();
        options.setCapability("platform", Platform.LINUX);
        try {
            WebDriver driver = new RemoteWebDriver(new URL(grid), options);
            driver.get(console);
            
            System.out.println(String.format("Screen size: %1$sx%2$s", driver.manage().window().getSize().width, driver.manage().window().getSize().height));
            driver.manage().window().maximize();
            System.out.println(String.format("Screen size after maximize: %1$sx%2$s", driver.manage().window().getSize().width, driver.manage().window().getSize().height));

        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }
```

## Expected behavior
Before maximize the browser, the size of the browser window can/shall be smaller than the screen resolution, for instance the first System.out will print
Screen size: 1280x972

After maximizing the screen, the browser windows will be close to the screen resolution. The second System.out will output:
Screen size after maximize: 1920x1033

## Actual behavior
When using the normal node-firefox, the screen size is the same both before and after maximizing the browser:
Screen size: 1280x972
Screen size after maximize: 1280x972

This tells me that the resolution of the node probably isn't set to 1920x1080

When using node-firefox-debug, screen size does differ meaning that the node's resolution is changed:
Screen size: 1280x952
Screen size after maximize: 1920x1033

## Test script reproducing this issue (when applicable)

Any simple test will suffice, for instance
```java
public void test01() {
       //Change the following strings to the valid URL
        String grid = "http://localhost:4444/wd/hub";
        String console = "http://localhost:4444/grid/console";
        
        FirefoxOptions options = new FirefoxOptions();
        options.setCapability("platform", Platform.LINUX);
        try {
            WebDriver driver = new RemoteWebDriver(new URL(grid), options);
            driver.get(console);
            
            System.out.println(String.format("Screen size: %1$sx%2$s", driver.manage().window().getSize().width, driver.manage().window().getSize().height));
            driver.manage().window().maximize();
            System.out.println(String.format("Screen size after maximize: %1$sx%2$s", driver.manage().window().getSize().width, driver.manage().window().getSize().height));

        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }
```

## Environment

OS: Alpine Linux 3.8.1 (docker image
Docker-Selenium image version: latest
Docker image ID: 35031487365f

Docker version: 18.06.1-ce, build d72f525745
Docker-Compose version (if applicable): 1.23.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): *docker-compose -f support/docker-compose.yml up -d*, using the docker-compose.yml as described above

**Comment by diemol** [comment]
@RvL001 can you please try with the `-debug` image?

**Comment by RvL001** [comment]
I did (as described), and in that case it does work

**Comment by diemol** [comment]
Exactly, because the `debug` images have a window manager (needed for VNC), and that is why it can set the window size. The other images cannot do that. 
We are planning to merge them in the near future to avoid this differences.

**Comment by RvL001** [comment]
OK, thanks for the reply.

This doesn't apply to the node-chrome, because there I can set the SCREEN_WIDTH and HEIGHT and it is set accordingly. That why I assumed this would work the same for the Firefox node
