### ISSUE TITLE
NodeChromeDebug flags to enable port-forwarder

### ISSUE THREAD

**Issue by dimadeveatii** [SeleniumHQ/docker-selenium#989]
## 🚀 Feature Proposal

Install [`socat`](https://linux.die.net/man/1/socat) in the `NodeChromeDebug` image and add the possibility to start it as a background process for port forwarding.  
Using and environment variable like `PORT_FORWARDING=<container-port>:<local-port>` would allow then to forward TCP container port `<container-port>` to `localhost` port `<local-port>`.  

## Motivation

Using VNC it's possible to see visually what is done in the browser. However, that implies that you start chrome without the `--headless` flag, otherwise the VNC is useless and you don't see what happens to the browser inside the container.  

Currently if there are tests that interact with the *devtools* then you get an error:
```
Error: socket hang up
``` 
And this happens because Chrome doesn't allow to connect to the devtools from a remote IP in a non-headless mode. Therefore you cannot debug your tests and use simultaneously VNC viewer and Chrome's devtools.  

Using the `socat` tool it would be possible to forward ports and use VNC viewer together with devtools. 

## Example

Start the node with port forwarder:
```sh
$ docker run -d -p 5900:5900 -e PORT_FORWARDING=9223:9222 --link selenium-hub:hub -v /dev/shm:/dev/shm selenium/node-chrome-debug
```
This will forward TCP container-ip:9223 port to localhost:9222 inside the container. You start chrome with args `--remote-debugging-port=9222` but then use container's IP and port `9223` to configure devtools in tools like `puppeteer`.

By default, if not specifying `PORT_FORWARDING` environment variable then `socat` will not be started:
```sh
# the image is used same as it's used now without any additional background processes
$ docker run -d -p 5900:5900 --link selenium-hub:hub -v /dev/shm:/dev/shm selenium/node-chrome-debug
```

## Contribution
We're already using this workaround but build a separate image based on `selenium/NodeChromeDebug`. If the feature sounds reasonable I'm willing to contribute and submit a PR.

**Comment by mvrogowski** [comment]
Sometimes, you can have Selenium being redirect to localhost - allowing forward localhost to another host would be gold.

**Comment by diemol** [comment]
@dimadeveatii docker already allows you to access the localhost from the container.
In addition, accessing devtools this way is more a hack than a proper solution. We are working in Grid 4 and it will at some point allow you to access devtools through the Grid.

Thanks for raising this, but in the end, this will be doable through the Grid itself.

**Comment by dimadeveatii** [comment]
Indeed, it's a hack but there is no other way to access devtools in a non headless mode. 
Great news that this will be supported in Grid 4. I agree that adding this is than doable. Will wait for Grid 4.
