### ISSUE TITLE
Running a node-chrome no matter what page i try to load the page is not found

### ISSUE THREAD

**Issue by darkyelox** [SeleniumHQ/docker-selenium#99]
Hi, i install docker and run my selenium-hub without problems and then run my node-chrome, then i run docker ps -a for make sure that everything is running, finally i use a RemoteWebDriver for connect to the grid and everything works

But when i run my test and load a page and then make an screenshot i get the 404 error page of chrome, i test my code before using PhantomJS without this problem, what can be? i see the logs using 'docker logs -f <chrome-node-name>' and no errors throws

Later i use node-firefox and the same history... page not found, i test with a local(localhost) and a domain url (like google.com)

**Comment by darkyelox** [comment]
i try to test and see what is the error in the browser by clicking the details button using Geb:

public void test_page_load(){
		new Browser().drive {
			go "http://127.0.0.1:4444/grid/console" // se navega a la pagina principal
			println "page loaded"
			$("button#details-button").click()
			report "test_page_load"
		}
	}

i get this:

![test_page_load](https://cloud.githubusercontent.com/assets/8183191/10048197/742fc300-61d7-11e5-8833-1a9aa0a20c86.png)

**Comment by darkyelox** [comment]
i found a solution for now, the problem is the DNS so i use the comands like this, in the hub and in the nodes:

docker run --dns 8.8.8.8 --dns 8.8.4.4 -d -p 4444:4444 --name selenium-hub selenium/hub:2.47.1

docker run --dns 8.8.8.8 --dns 8.8.4.4 -d -P --link selenium-hub:hub selenium/node-chrome-debug:2.47.1

but this can be a bug of docker because i use ubuntu image and i need to do the same thing with ping

**Comment by rubytester** [comment]
The host machine where you run your docker images needs to have dns setup to resolve to the outside world. Sorry, but that's beyond the scope of this project.

**Comment by rogoit** [comment]
I have the same issue

**Comment by ddavison** [comment]
check DNS as rubytester had mentioned, @rogoit.
