### ISSUE TITLE
--unsafely-treat-insecure-origin-as-secure chrome option flag set in protractor does not work with selenium/node-chrome:3.141.59

### ISSUE THREAD

**Issue by RogierdeRuijter** [SeleniumHQ/docker-selenium#993]
## 🐛 Bug Report
Chrome options in protractor:
```
chromeOptions: {
      args: ['--unsafely-treat-insecure-origin-as-secure=https://webserver-e2e' ]
}
```
Chorme options in node-chrome container logs:
```
"chromeOptions": {
    "args": [
      "--unsafely-treat-insecure-origin-as-secure=https:\u002f\u002fwebserver-e2e",
    ]
  },
```

I believe this makes the flag unusable

## To Reproduce

Run protractor tests with the chorme options  '--unsafely-treat-insecure-origin-as-secure'  flag.

## Expected behavior

Being able to use the --unsafely-treat-insecure-origin-as-secure flag

## Environment

OS: OSX
Docker-Selenium image version: selenium/hub:3.141.59
Docker version: Docker version 19.03.5, build 633a0ea
Docker-Compose version (if applicable): docker-compose version 1.24.1, build 4667896b

**Comment by diemol** [comment]
@RogierdeRuijter could you please tell us in which version this was working?
It seems that the protractor version being used is not putting the prefix needed for ChomeOptions.
It should look like `goog:chromeOptions`.

Please have a look and let us know if it works so we can close this issue.

**Comment by RogierdeRuijter** [comment]
@diemol Thanks or your response.

I am working with the following versions:
Protractor: 5.4.2
selenium/hub: 3.141.59
selenium/node-chrome: 3.141.59

This is part of the protractor.conf
```
capabilities: {
    'browserName': 'chrome',
    trustAllSSLCertificates: true,
    acceptInsecureCerts: true,
    acceptSslCerts: true,
    chromeOptions: {
      args: [
        '--ignore-certificate-errors',
        '--unsafely-treat-insecure-origin-as-secure=https://webserver-e2e/',
        '--window-size=800x600', 
        'no-sandbox', 
        '--whitelisted-ips'
      ],
    },
    'goog:chromeOptions': {
      'w3c': false,
    }
  }
```

I tried putting the  '--unsafely-treat-insecure-origin-as-secure=https://webserver-e2e/', in the goog:chomeOptions in the following way.

```
 'goog:chromeOptions': {
      'w3c': false,
       '--unsafely-treat-insecure-origin-as-secure': 'https://webserver-e2e/'
    }
```

But this results in protractor configuration errors.

**Comment by RogierdeRuijter** [comment]
This was a mistake from my part.

The solution is to replace `chromeOptions` with `goog:chromeOptions`.

Which results in this protractor conf:
```
apabilities: {
    'browserName': 'chrome',
    trustAllSSLCertificates: true,
    acceptInsecureCerts: true,
    acceptSslCerts: true,
    'goog:chromeOptions': {
      'w3c': false,
      args: [
        '--ignore-certificate-errors',
        '--unsafely-treat-insecure-origin-as-secure=https://webserver-e2e/',
        '--window-size=800x600', 
        'no-sandbox', 
        '--whitelisted-ips'
      ],
    }
  },
```

My bad :)

Closing the issue
