### ISSUE TITLE
multiarch/arm support

### ISSUE THREAD

**Issue by cyberb** [SeleniumHQ/docker-selenium#996]
Do you have any plans to add docker multiarch or arm images?

**Comment by cgoldberg** [comment]
Node images contain webdriver binaries, which are not currently built for ARM (by Google or Mozilla for example).  Browser vendors would need to start releasing ARM builds of their webdrivers before this would be feasible (AFAICT).

**Comment by diemol** [comment]
Thanks @cgoldberg for replying.
