### ISSUE TITLE
Creating images with Selenium Webdriver 4 version

### ISSUE THREAD

**Issue by szamacz** [SeleniumHQ/docker-selenium#997]
## 🚀 Feature Proposal

As Selenium Webdriver  4 is still in alpha version since almost one year, and all new fixes lands here, not in version 3, it would be convenient to think about release selenium docker images with Selenium Webdriver version 4.

## Motivation

Lot of people already migrated to Selenium Webdriver  4, even if this is still alpha version, mostly due to fact that all fixes are not merged to version 3. Docker images are being created still with version 3, which prevents of using them for running tests using Remote Webdriver and docker images for CI purposes.

## Example

We can replace version of WebDriver for next images, or create separate images for version 3 and 4

**Comment by omkarnathsingh** [comment]
Love this proposal, we can start using selenium 4, it will help us adapt faster too.

**Comment by diemol** [comment]
Thanks for raising this, this is currently work in progress.

**Comment by szamacz** [comment]
@diemol  Great to hear that, when we can expect first images?

**Comment by carlos-gva** [comment]
Will this be optional (separated images) are all of them will come with the v4?

**Comment by diemol** [comment]
We just released an initial version using the Alpha 5 from Selenium.
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-alpha-5-20200326.
Partly updated README can be seen here https://github.com/SeleniumHQ/docker-selenium/tree/selenium-4-alpha
This can be already used, but keep in mind that it is work in progress. Feel free to report any bugs or missing functionality.
